package com.kareem.cortex;

import android.annotation.TargetApi;
import android.content.*;
import android.media.AudioFormat;
import android.os.*;
import android.speech.*;
import java.io.*;
import java.util.*;

/** Android on-device recognizer, shadow-only. API 33+ feeds the immutable WAV PCM through EXTRA_AUDIO_SOURCE. */
public final class AndroidOnDeviceAsrCandidate implements AsrCandidate {
    public String id(){return"android_on_device_speech";} public String displayName(){return"Android On-device Speech";}
    public boolean isReady(Context c){return Build.VERSION.SDK_INT>=33&&SpeechRecognizer.isOnDeviceRecognitionAvailable(c);}
    public void transcribe(Context c,File wav,Callback cb){long s=SystemClock.elapsedRealtime();if(!isReady(c)){cb.fail(new IllegalStateException("Android on-device speech recognition unavailable"),0);return;}new Handler(Looper.getMainLooper()).post(()->start(c,wav,s,cb));}
    @TargetApi(33) private void start(Context c,File wav,long started,Callback cb){SpeechRecognizer r=null;ParcelFileDescriptor rd=null,wr=null;try{WavData w=WavData.read(wav);ParcelFileDescriptor[]p=ParcelFileDescriptor.createPipe();rd=p[0];wr=p[1];final ParcelFileDescriptor fr=rd,fw=wr;r=SpeechRecognizer.createOnDeviceSpeechRecognizer(c);final SpeechRecognizer sr=r;final boolean[]done={false};
        r.setRecognitionListener(new RecognitionListener(){void fail(Exception e){if(done[0])return;done[0]=true;close(fr);close(fw);try{sr.destroy();}catch(Exception ignored){}cb.fail(e,SystemClock.elapsedRealtime()-started);}public void onReadyForSpeech(Bundle b){}public void onBeginningOfSpeech(){}public void onRmsChanged(float f){}public void onBufferReceived(byte[]b){}public void onEndOfSpeech(){}public void onError(int e){fail(new IllegalStateException("Android ASR error "+e));}public void onPartialResults(Bundle b){}public void onEvent(int e,Bundle b){}public void onResults(Bundle b){if(done[0])return;ArrayList<String>x=b==null?null:b.getStringArrayList(SpeechRecognizer.RESULTS_RECOGNITION);if(x==null||x.isEmpty()||x.get(0).trim().isEmpty()){fail(new IllegalStateException("Android ASR returned no transcript"));return;}done[0]=true;TranscriptResult o=new TranscriptResult();o.text=x.get(0).trim();o.language="ar-EG+en-US";o.engine="android_on_device_speech";o.version=String.valueOf(Build.VERSION.SDK_INT);o.durationMs=w.durationMs();close(fr);close(fw);try{sr.destroy();}catch(Exception ignored){}cb.ok(o,SystemClock.elapsedRealtime()-started);}});
        Intent i=new Intent(RecognizerIntent.ACTION_RECOGNIZE_SPEECH);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE_MODEL,RecognizerIntent.LANGUAGE_MODEL_FREE_FORM);i.putExtra(RecognizerIntent.EXTRA_LANGUAGE,"ar-EG");i.putExtra(RecognizerIntent.EXTRA_PREFER_OFFLINE,true);i.putExtra(RecognizerIntent.EXTRA_AUDIO_SOURCE,rd);i.putExtra(RecognizerIntent.EXTRA_AUDIO_SOURCE_CHANNEL_COUNT,w.channels);i.putExtra(RecognizerIntent.EXTRA_AUDIO_SOURCE_ENCODING,AudioFormat.ENCODING_PCM_16BIT);i.putExtra(RecognizerIntent.EXTRA_AUDIO_SOURCE_SAMPLING_RATE,w.sampleRate);if(Build.VERSION.SDK_INT>=34){ArrayList<String>ls=new ArrayList<>(Arrays.asList("ar-EG","en-US"));i.putExtra(RecognizerIntent.EXTRA_ENABLE_LANGUAGE_DETECTION,true);i.putStringArrayListExtra(RecognizerIntent.EXTRA_LANGUAGE_DETECTION_ALLOWED_LANGUAGES,ls);i.putExtra(RecognizerIntent.EXTRA_ENABLE_LANGUAGE_SWITCH,RecognizerIntent.LANGUAGE_SWITCH_BALANCED);i.putStringArrayListExtra(RecognizerIntent.EXTRA_LANGUAGE_SWITCH_ALLOWED_LANGUAGES,ls);}r.startListening(i);final ParcelFileDescriptor writer=wr;new Thread(()->stream(wav,w,writer),"cortex-asr-pcm").start();
    }catch(Exception e){close(rd);close(wr);if(r!=null)try{r.destroy();}catch(Exception ignored){}cb.fail(e,SystemClock.elapsedRealtime()-started);}}
    private static void stream(File f,WavData w,ParcelFileDescriptor fd){try(FileInputStream in=new FileInputStream(f);OutputStream out=new ParcelFileDescriptor.AutoCloseOutputStream(fd)){long s=w.dataOffset;while(s>0){long n=in.skip(s);if(n<=0)break;s-=n;}byte[]b=new byte[8192];long left=w.dataLength;while(left>0){int n=in.read(b,0,(int)Math.min(b.length,left));if(n<0)break;out.write(b,0,n);left-=n;}out.flush();}catch(Exception ignored){}}
    private static void close(ParcelFileDescriptor p){if(p!=null)try{p.close();}catch(Exception ignored){}}
    private static final class WavData{final long dataOffset,dataLength;final int sampleRate,channels,bits;WavData(long o,long l,int r,int c,int b){dataOffset=o;dataLength=l;sampleRate=r;channels=c;bits=b;}long durationMs(){long x=(long)sampleRate*channels*(bits/8);return x<=0?0:dataLength*1000L/x;}static WavData read(File f)throws Exception{try(RandomAccessFile r=new RandomAccessFile(f,"r")){byte[]id=new byte[4];r.readFully(id);if(!"RIFF".equals(new String(id,"US-ASCII")))throw new IllegalArgumentException("Not RIFF WAV");r.skipBytes(4);r.readFully(id);if(!"WAVE".equals(new String(id,"US-ASCII")))throw new IllegalArgumentException("Not WAVE audio");int rate=16000,ch=1,bits=16;long off=-1,len=-1;while(r.getFilePointer()+8<=r.length()){r.readFully(id);String n=new String(id,"US-ASCII");long l=u32(r),st=r.getFilePointer();if("fmt ".equals(n)&&l>=16){int format=u16(r);ch=u16(r);rate=(int)u32(r);r.skipBytes(6);bits=u16(r);if(format!=1)throw new IllegalArgumentException("Only PCM WAV supported");}else if("data".equals(n)){off=st;len=Math.min(l,r.length()-st);break;}r.seek(Math.min(st+l+(l&1),r.length()));}if(off<0||len<=0||bits!=16)throw new IllegalArgumentException("Unsupported Cortex WAV");return new WavData(off,len,rate,ch,bits);}}static int u16(RandomAccessFile r)throws Exception{return r.readUnsignedByte()|(r.readUnsignedByte()<<8);}static long u32(RandomAccessFile r)throws Exception{return(long)r.readUnsignedByte()|((long)r.readUnsignedByte()<<8)|((long)r.readUnsignedByte()<<16)|((long)r.readUnsignedByte()<<24);}}
}
