package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.util.*;

/** Ask starts with conversation. Retrieval/runtime details stay behind Sources. */
public class AskCortexActivity extends Activity {
    VaultDb db;LinearLayout conversation;ScrollView scroll;EditText input;TextView send;boolean busy=false;
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);build();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);
        LinearLayout header=new LinearLayout(this);header.setOrientation(LinearLayout.HORIZONTAL);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(20),dp(13),dp(20),dp(9));TextView h=CortexUi.plain(this,"Ask Cortex",29,CortexUi.TEXT);CortexUi.medium(h);header.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView settings=CortexUi.chip(this,"Settings",CortexUi.MUTED,false);settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));header.addView(settings,new LinearLayout.LayoutParams(-2,dp(36)));root.addView(header);
        scroll=new ScrollView(this);scroll.setFillViewport(true);conversation=new LinearLayout(this);conversation.setOrientation(LinearLayout.VERTICAL);conversation.setPadding(dp(20),dp(8),dp(20),dp(18));scroll.addView(conversation);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));suggestions();
        LinearLayout composer=new LinearLayout(this);composer.setOrientation(LinearLayout.HORIZONTAL);composer.setGravity(Gravity.CENTER_VERTICAL);composer.setPadding(dp(14),dp(7),dp(14),dp(7));input=new EditText(this);input.setHint("Ask about something you've saved…");input.setHintTextColor(CortexUi.FAINT);input.setTextColor(CortexUi.TEXT);input.setTextSize(14);input.setMinLines(1);input.setMaxLines(4);input.setSingleLine(false);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);input.setPadding(dp(15),dp(11),dp(12),dp(11));input.setBackground(CortexUi.round(this,CortexUi.SURFACE,android.graphics.Color.TRANSPARENT,18));composer.addView(input,new LinearLayout.LayoutParams(0,-2,1));send=CortexUi.action(this,"Ask",CortexUi.ACCENT,true);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(68),dp(48));sp.setMargins(dp(8),0,0,0);composer.addView(send,sp);send.setOnClickListener(v->submit());root.addView(composer);CortexUi.addBottomNav(this,root,"ask",null);setContentView(root);}

    void suggestions(){TextView sh=CortexUi.plain(this,"Try asking",11,CortexUi.MUTED);CortexUi.medium(sh);sh.setPadding(0,dp(4),0,dp(10));conversation.addView(sh);addSuggestion("What still needs my attention?");addSuggestion("What did I decide recently?");addSuggestion("What do I know about this project?");}
    void addSuggestion(String s){TextView c=CortexUi.plain(this,s,13,CortexUi.TEXT);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(14),0,dp(14),0);CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,android.graphics.Color.TRANSPARENT,16));c.setOnClickListener(v->{input.setText(s);input.setSelection(input.length());submit();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(44));p.setMargins(0,0,0,dp(8));conversation.addView(c,p);}

    void submit(){if(busy)return;String q=input.getText().toString().trim();if(q.isEmpty())return;busy=true;send.setText("…");send.setEnabled(false);hideKeyboard();addUser(q);input.setText("");TextView thinking=thinking("Searching…");scrollEnd();new Thread(()->{LocalAskRouter.Result r=LocalAskRouter.fast(this,db,q);runOnUiThread(()->{conversation.removeView(thinking);addAnswer(r,q,false);busy=false;send.setText("Ask");send.setEnabled(true);input.requestFocus();scrollEnd();});},"CortexAskFast").start();}
    void refine(String q,TextView button){button.setEnabled(false);button.setText("Improving…");TextView thinking=thinking("Improving answer…");scrollEnd();new Thread(()->{LocalAskRouter.Result r=LocalAskRouter.ask(this,db,q);runOnUiThread(()->{conversation.removeView(thinking);if("local-qwen".equals(r.provider))addAnswer(r,q,true);else{TextView e=CortexUi.text(this,"Could not improve the wording right now.",11,CortexUi.MUTED);e.setPadding(dp(2),dp(10),dp(2),dp(10));conversation.addView(e);button.setText("Improve wording");button.setEnabled(true);}scrollEnd();});},"CortexAskRefine").start();}

    void addUser(String q){LinearLayout wrap=new LinearLayout(this);wrap.setGravity(Gravity.RIGHT);TextView bubble=CortexUi.text(this,q,14,CortexUi.TEXT);bubble.setPadding(dp(14),dp(11),dp(14),dp(11));bubble.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,android.graphics.Color.TRANSPARENT,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(dp(42),dp(14),0,dp(10));wrap.addView(bubble,p);conversation.addView(wrap);}
    TextView thinking(String s){TextView t=CortexUi.plain(this,s,11,CortexUi.MUTED);t.setPadding(dp(2),dp(8),dp(2),dp(8));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(0,0,dp(48),dp(8));conversation.addView(t,p);return t;}

    void addAnswer(LocalAskRouter.Result r,String q,boolean refined){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(0,dp(10),0,dp(16));TextView label=CortexUi.plain(this,"Cortex",13,CortexUi.TEXT);CortexUi.medium(label);card.addView(label);TextView body=CortexUi.text(this,r.answer,15,CortexUi.TEXT);body.setPadding(0,dp(8),0,0);body.setTextIsSelectable(true);card.addView(body);
        LinearLayout details=new LinearLayout(this);details.setOrientation(LinearLayout.VERTICAL);details.setVisibility(View.GONE);details.setPadding(dp(12),dp(8),dp(12),dp(8));details.setBackground(CortexUi.round(this,CortexUi.SURFACE,android.graphics.Color.TRANSPARENT,14));TextView tech=CortexUi.plain(this,(refined?"Improved wording":"Grounded answer")+"  •  "+friendlyMs(r.totalMs),10,CortexUi.MUTED);details.addView(tech);for(int i=0;i<Math.min(4,r.grounded.sources.size());i++){KnowledgeItem k=r.grounded.sources.get(i).item;TextView source=CortexUi.text(this,"M"+(i+1)+"  ·  "+clean(k.title),11,CortexUi.MUTED);source.setMaxLines(2);source.setPadding(0,dp(5),0,dp(2));details.addView(source);}if(!r.grounded.sources.isEmpty()){TextView toggle=CortexUi.plain(this,"Sources ("+r.grounded.sources.size()+")",11,CortexUi.MUTED);CortexUi.medium(toggle);toggle.setPadding(0,dp(12),0,dp(8));toggle.setOnClickListener(v->{boolean show=details.getVisibility()!=View.VISIBLE;details.setVisibility(show?View.VISIBLE:View.GONE);toggle.setText((show?"Hide sources":"Sources ("+r.grounded.sources.size()+")"));});card.addView(toggle);card.addView(details);}
        if(!refined&&LocalModelManager.installed(this)){TextView improve=CortexUi.action(this,"Improve wording",CortexUi.MUTED,false);improve.setOnClickListener(v->refine(q,improve));LinearLayout.LayoutParams improveParams=new LinearLayout.LayoutParams(-1,dp(42));improveParams.setMargins(0,dp(10),0,0);card.addView(improve,improveParams);}conversation.addView(card);conversation.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}

    String friendlyMs(long ms){return ms<1000?ms+" ms":String.format(Locale.US,"%.1f s",ms/1000f);}String clean(String s){if(empty(s))return"Memory";String x=s.trim();return x.length()>76?x.substring(0,76)+"…":x;}boolean empty(String s){return s==null||s.trim().isEmpty();}void scrollEnd(){scroll.postDelayed(()->scroll.fullScroll(View.FOCUS_DOWN),60);}void hideKeyboard(){try{((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(input.getWindowToken(),0);}catch(Throwable ignored){}}
}
