package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.util.*;

/** Ask answers from retrieval first. Local Qwen is an optional refinement, never a blocking dependency. */
public class AskCortexActivity extends Activity {
    VaultDb db;LinearLayout conversation;ScrollView scroll;EditText input;TextView send,status;boolean busy=false;
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);build();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);
        LinearLayout header=new LinearLayout(this);header.setOrientation(LinearLayout.HORIZONTAL);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(18),dp(11),dp(18),dp(9));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Ask Cortex",27,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);status=CortexUi.plain(this,LocalModelManager.installed(this)?"Fast grounded answers  •  local refinement available":"Fast grounded answers  •  private Vault retrieval",11,CortexUi.MUTED);titles.addView(status);header.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView settings=CortexUi.chip(this,"SETTINGS",CortexUi.MUTED,false);settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));header.addView(settings,new LinearLayout.LayoutParams(-2,dp(36)));root.addView(header);
        scroll=new ScrollView(this);scroll.setFillViewport(true);conversation=new LinearLayout(this);conversation.setOrientation(LinearLayout.VERTICAL);conversation.setPadding(dp(20),dp(8),dp(20),dp(18));scroll.addView(conversation);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));welcome();
        LinearLayout composer=new LinearLayout(this);composer.setOrientation(LinearLayout.HORIZONTAL);composer.setGravity(Gravity.CENTER_VERTICAL);composer.setPadding(dp(14),dp(7),dp(14),dp(7));input=new EditText(this);input.setHint("Ask about something you've saved…");input.setHintTextColor(CortexUi.FAINT);input.setTextColor(CortexUi.TEXT);input.setTextSize(14);input.setMinLines(1);input.setMaxLines(4);input.setSingleLine(false);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);input.setPadding(dp(15),dp(11),dp(12),dp(11));input.setBackground(CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER,18));composer.addView(input,new LinearLayout.LayoutParams(0,-2,1));send=CortexUi.action(this,"Ask",CortexUi.ACCENT,true);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(68),dp(48));sp.setMargins(dp(8),0,0,0);composer.addView(send,sp);send.setOnClickListener(v->submit());root.addView(composer);CortexUi.addBottomNav(this,root,"ask",null);setContentView(root);}

    void welcome(){LinearLayout note=CortexUi.card(this,22);note.setPadding(dp(16),dp(15),dp(16),dp(15));TextView t=CortexUi.plain(this,"Your memory first",16,CortexUi.TEXT);CortexUi.medium(t);note.addView(t);TextView b=CortexUi.text(this,"Cortex returns the grounded answer immediately. If you want a more natural rewrite, you can refine that answer with the local model afterward.",12,CortexUi.MUTED);b.setPadding(0,dp(5),0,0);note.addView(b);conversation.addView(note);TextView sh=CortexUi.section(this,"Try asking");sh.setPadding(0,dp(18),0,dp(9));conversation.addView(sh);addSuggestion("What still needs my attention?");addSuggestion("What did I decide recently?");addSuggestion("What do I know about this project?");}
    void addSuggestion(String s){TextView c=CortexUi.chip(this,s,CortexUi.ACCENT,false);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(14),0,dp(14),0);c.setOnClickListener(v->{input.setText(s);input.setSelection(input.length());submit();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(42));p.setMargins(0,0,0,dp(8));conversation.addView(c,p);}

    void submit(){if(busy)return;String q=input.getText().toString().trim();if(q.isEmpty())return;busy=true;send.setText("…");send.setEnabled(false);hideKeyboard();addUser(q);input.setText("");TextView thinking=thinking("Searching your Vault…");scrollEnd();new Thread(()->{LocalAskRouter.Result r=LocalAskRouter.fast(this,db,q);runOnUiThread(()->{conversation.removeView(thinking);addAnswer(r,q,false);busy=false;send.setText("Ask");send.setEnabled(true);input.requestFocus();scrollEnd();});},"CortexAskFast").start();}
    void refine(String q,TextView button){button.setEnabled(false);button.setText("Refining locally…");TextView thinking=thinking("Local AI is refining the grounded answer…");scrollEnd();new Thread(()->{LocalAskRouter.Result r=LocalAskRouter.ask(this,db,q);runOnUiThread(()->{conversation.removeView(thinking);if("local-qwen".equals(r.provider))addAnswer(r,q,true);else{TextView e=CortexUi.text(this,empty(r.error)?"Local refinement was unavailable.":r.error,11,CortexUi.MUTED);e.setPadding(dp(14),dp(11),dp(14),dp(11));e.setBackground(CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,16));conversation.addView(e);button.setText("Refine with local AI");button.setEnabled(true);}scrollEnd();});},"CortexAskRefine").start();}

    void addUser(String q){LinearLayout wrap=new LinearLayout(this);wrap.setGravity(Gravity.RIGHT);TextView bubble=CortexUi.text(this,q,14,CortexUi.TEXT);bubble.setPadding(dp(14),dp(11),dp(14),dp(11));bubble.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(dp(42),dp(14),0,dp(10));wrap.addView(bubble,p);conversation.addView(wrap);}
    TextView thinking(String s){TextView t=CortexUi.plain(this,s,11,CortexUi.ACCENT);t.setPadding(dp(13),dp(10),dp(13),dp(10));t.setBackground(CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,16));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(0,0,dp(48),dp(10));conversation.addView(t,p);return t;}

    void addAnswer(LocalAskRouter.Result r,String q,boolean refined){LinearLayout card=CortexUi.card(this,22);card.setPadding(dp(17),dp(15),dp(17),dp(15));LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);TextView label=CortexUi.plain(this,refined?"Cortex • Local refinement":"Cortex • Grounded",13,CortexUi.TEXT);CortexUi.medium(label);head.addView(label,new LinearLayout.LayoutParams(0,-2,1));TextView provider=CortexUi.chip(this,refined?"LOCAL":"FAST",refined?CortexUi.SAGE:CortexUi.ACCENT,true);head.addView(provider,new LinearLayout.LayoutParams(-2,dp(27)));card.addView(head);TextView body=CortexUi.text(this,r.answer,15,CortexUi.TEXT);body.setPadding(0,dp(12),0,0);body.setTextIsSelectable(true);card.addView(body);TextView meta=CortexUi.plain(this,r.grounded.sources.size()+" sources  •  "+friendlyMs(r.totalMs),10,CortexUi.MUTED);meta.setPadding(0,dp(11),0,0);card.addView(meta);
        if(!r.grounded.sources.isEmpty()){TextView sec=CortexUi.section(this,"Evidence");sec.setPadding(0,dp(14),0,dp(5));card.addView(sec);for(int i=0;i<Math.min(3,r.grounded.sources.size());i++){KnowledgeItem k=r.grounded.sources.get(i).item;TextView source=CortexUi.text(this,"M"+(i+1)+"  ·  "+clean(k.title),11,CortexUi.MUTED);source.setMaxLines(2);source.setPadding(0,dp(3),0,dp(3));card.addView(source);}}
        if(!refined&&LocalModelManager.installed(this)){TextView refine=CortexUi.action(this,"Refine with local AI",CortexUi.ACCENT,false);refine.setOnClickListener(v->refine(q,refine));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(43));rp.setMargins(0,dp(12),0,0);card.addView(refine,rp);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(12));conversation.addView(card,p);}

    String friendlyMs(long ms){return ms<1000?ms+" ms":String.format(Locale.US,"%.1f s",ms/1000f);}String clean(String s){if(empty(s))return"Memory";String x=s.trim();return x.length()>76?x.substring(0,76)+"…":x;}boolean empty(String s){return s==null||s.trim().isEmpty();}void scrollEnd(){scroll.postDelayed(()->scroll.fullScroll(View.FOCUS_DOWN),60);}void hideKeyboard(){try{((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(input.getWindowToken(),0);}catch(Throwable ignored){}}
}
