package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import java.util.*;

/** Brain starts with conversation. Retrieval/runtime details stay behind Sources. */
public class AskCortexActivity extends Activity {
    VaultDb db;LinearLayout conversation,modeBar;ScrollView scroll;EditText input;TextView send,modeNote;boolean busy=false;String sourceMode="your_data";
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);build();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);
        LinearLayout header=new LinearLayout(this);header.setOrientation(LinearLayout.HORIZONTAL);header.setGravity(Gravity.CENTER_VERTICAL);header.setPadding(dp(20),dp(13),dp(20),dp(7));TextView h=CortexUi.plain(this,"Brain",29,CortexUi.TEXT);CortexUi.medium(h);header.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView settings=CortexUi.chip(this,"Settings",CortexUi.MUTED,false);settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));header.addView(settings,new LinearLayout.LayoutParams(-2,dp(36)));root.addView(header);
        modeBar=new LinearLayout(this);modeBar.setOrientation(LinearLayout.HORIZONTAL);modeBar.setPadding(dp(20),dp(2),dp(20),0);addMode("Your data","your_data");addMode("External","external");addMode("Combined","combined");root.addView(modeBar,new LinearLayout.LayoutParams(-1,dp(42)));modeNote=CortexUi.plain(this,"Private Cortex data only · no cloud memory upload",9,CortexUi.MUTED);modeNote.setPadding(dp(20),0,dp(20),dp(4));root.addView(modeNote,new LinearLayout.LayoutParams(-1,dp(27)));styleModes();
        scroll=new ScrollView(this);scroll.setFillViewport(true);conversation=new LinearLayout(this);conversation.setOrientation(LinearLayout.VERTICAL);conversation.setPadding(dp(20),dp(8),dp(20),dp(18));scroll.addView(conversation);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));suggestions();
        LinearLayout composer=new LinearLayout(this);composer.setOrientation(LinearLayout.HORIZONTAL);composer.setGravity(Gravity.CENTER_VERTICAL);composer.setPadding(dp(14),dp(7),dp(14),dp(7));input=new EditText(this);input.setHint("Ask Brain…");input.setHintTextColor(CortexUi.FAINT);input.setTextColor(CortexUi.TEXT);input.setTextSize(14);input.setMinLines(1);input.setMaxLines(4);input.setSingleLine(false);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);input.setPadding(dp(15),dp(11),dp(12),dp(11));input.setBackground(CortexUi.round(this,CortexUi.SURFACE,android.graphics.Color.TRANSPARENT,18));composer.addView(input,new LinearLayout.LayoutParams(0,-2,1));send=CortexUi.action(this,"Ask",CortexUi.ACCENT,true);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(68),dp(48));sp.setMargins(dp(8),0,0,0);composer.addView(send,sp);send.setOnClickListener(v->submit());root.addView(composer);CortexUi.addBottomNav(this,root,"ask",null);setContentView(root);}

    void addMode(String label,String key){TextView c=CortexUi.chip(this,label,CortexUi.MUTED,false);c.setTag(key);c.setOnClickListener(v->{if(busy)return;sourceMode=(String)v.getTag();styleModes();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(36),1);if(modeBar.getChildCount()>0)p.setMargins(dp(7),0,0,0);modeBar.addView(c,p);}
    void styleModes(){if(modeBar==null)return;for(int i=0;i<modeBar.getChildCount();i++){TextView t=(TextView)modeBar.getChildAt(i);boolean on=sourceMode.equals(t.getTag());t.setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);t.setBackground(CortexUi.round(this,on?CortexUi.SURFACE_2:CortexUi.SURFACE,on?CortexUi.ACCENT:CortexUi.BORDER_SOFT,999));if(on)CortexUi.medium(t);}if(modeNote!=null){if("combined".equals(sourceMode))modeNote.setText("Explicit cloud route · selected Cortex evidence is sent to configured Gemini");else if("external".equals(sourceMode))modeNote.setText("External AI only · your Cortex memory is not sent");else modeNote.setText("Private Cortex data only · no cloud memory upload");}}

    void suggestions(){TextView sh=CortexUi.plain(this,"Try asking",11,CortexUi.MUTED);CortexUi.medium(sh);sh.setPadding(0,dp(4),0,dp(10));conversation.addView(sh);addSuggestion("What still needs my attention?");addSuggestion("What did I decide recently?");addSuggestion("What do I know about this project?");}
    void addSuggestion(String s){TextView c=CortexUi.plain(this,s,13,CortexUi.TEXT);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(14),0,dp(14),0);CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,android.graphics.Color.TRANSPARENT,16));c.setOnClickListener(v->{input.setText(s);input.setSelection(input.length());submit();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(44));p.setMargins(0,0,0,dp(8));conversation.addView(c,p);}

    void submit(){if(busy)return;String q=input.getText().toString().trim();if(q.isEmpty())return;busy=true;send.setText("…");send.setEnabled(false);hideKeyboard();addUser(q);input.setText("");TextView thinking=thinking("Understanding request  •  0%");scrollEnd();final String requestedMode=sourceMode;new Thread(()->{LocalAskRouter.Result r=BrainRouter.fast(this,db,q,requestedMode,(job,label,percent)->progress(thinking,label,percent));runOnUiThread(()->{conversation.removeView(thinking);addAnswer(r,q,false);busy=false;send.setText("Ask");send.setEnabled(true);input.requestFocus();scrollEnd();});},"CortexBrainRoute").start();}
    void refine(String q,TextView button){button.setEnabled(false);button.setText("Improving…");TextView thinking=thinking("Understanding request  •  0%");scrollEnd();new Thread(()->{LocalAskRouter.Result r=LocalAskRouter.ask(this,db,q,(job,label,percent)->progress(thinking,label,percent));runOnUiThread(()->{conversation.removeView(thinking);if("local-qwen".equals(r.provider))addAnswer(r,q,true);else{TextView e=CortexUi.text(this,r.error.isEmpty()?"Could not improve the answer right now.":"Grounded answer kept because the local refinement was unavailable.",11,CortexUi.MUTED);e.setPadding(dp(2),dp(10),dp(2),dp(10));conversation.addView(e);button.setText("Improve wording");button.setEnabled(true);}scrollEnd();});},"CortexAskRefine").start();}

    void progress(TextView view,String label,int percent){runOnUiThread(()->{if(view.getParent()!=null){view.setText(label+"  •  "+Math.max(0,Math.min(100,percent))+"%");scrollEnd();}});}
    void addUser(String q){LinearLayout wrap=new LinearLayout(this);wrap.setGravity(Gravity.RIGHT);TextView bubble=CortexUi.text(this,q,14,CortexUi.TEXT);bubble.setPadding(dp(14),dp(11),dp(14),dp(11));bubble.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,android.graphics.Color.TRANSPARENT,18));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(dp(42),dp(14),0,dp(10));wrap.addView(bubble,p);conversation.addView(wrap);}
    TextView thinking(String s){TextView t=CortexUi.plain(this,s,11,CortexUi.MUTED);t.setPadding(dp(2),dp(8),dp(2),dp(8));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(0,0,dp(48),dp(8));conversation.addView(t,p);return t;}

    void addAnswer(LocalAskRouter.Result r,String q,boolean refined){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(0,dp(10),0,dp(16));LinearLayout labelRow=new LinearLayout(this);labelRow.setGravity(Gravity.CENTER_VERTICAL);TextView label=CortexUi.plain(this,"Brain",13,CortexUi.TEXT);CortexUi.medium(label);labelRow.addView(label,new LinearLayout.LayoutParams(0,-2,1));TextView mode=CortexUi.plain(this,modeLabel(r.sourceMode),10,CortexUi.MUTED);labelRow.addView(mode);card.addView(labelRow);TextView body=CortexUi.text(this,r.answer,15,CortexUi.TEXT);body.setPadding(0,dp(8),0,0);body.setTextIsSelectable(true);card.addView(body);
        LinearLayout details=new LinearLayout(this);details.setOrientation(LinearLayout.VERTICAL);details.setVisibility(View.GONE);details.setPadding(dp(12),dp(8),dp(12),dp(8));details.setBackground(CortexUi.round(this,CortexUi.SURFACE,android.graphics.Color.TRANSPARENT,14));TextView tech=CortexUi.plain(this,modeLabel(r.sourceMode)+"  •  "+friendlyMs(r.totalMs)+(r.jobId>0?"  •  job "+r.jobId:""),10,CortexUi.MUTED);details.addView(tech);for(int i=0;i<Math.min(4,r.grounded.sources.size());i++){KnowledgeItem k=r.grounded.sources.get(i).item;TextView source=CortexUi.text(this,"M"+(i+1)+"  ·  "+clean(k.title),11,CortexUi.MUTED);source.setMaxLines(2);source.setPadding(0,dp(5),0,dp(2));details.addView(source);}if(!r.grounded.sources.isEmpty()){TextView toggle=CortexUi.plain(this,"Sources ("+r.grounded.sources.size()+")",11,CortexUi.MUTED);CortexUi.medium(toggle);toggle.setPadding(0,dp(12),0,dp(8));toggle.setOnClickListener(v->{boolean show=details.getVisibility()!=View.VISIBLE;details.setVisibility(show?View.VISIBLE:View.GONE);toggle.setText(show?"Hide sources":"Sources ("+r.grounded.sources.size()+")");});card.addView(toggle);card.addView(details);}
        if(!refined&&"your_data".equals(r.sourceMode)&&LocalModelManager.installed(this)&&!"failed".equals(r.provider)){TextView improve=CortexUi.action(this,"Improve wording",CortexUi.MUTED,false);improve.setOnClickListener(v->refine(q,improve));LinearLayout.LayoutParams improveParams=new LinearLayout.LayoutParams(-1,dp(42));improveParams.setMargins(0,dp(10),0,0);card.addView(improve,improveParams);}conversation.addView(card);conversation.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}

    String modeLabel(String mode){if("external".equals(mode))return"External";if("combined".equals(mode))return"Combined";return"Your data";}String friendlyMs(long ms){return ms<1000?ms+" ms":String.format(Locale.US,"%.1f s",ms/1000f);}String clean(String s){if(empty(s))return"Memory";String x=s.trim();return x.length()>76?x.substring(0,76)+"…":x;}boolean empty(String s){return s==null||s.trim().isEmpty();}void scrollEnd(){scroll.postDelayed(()->scroll.fullScroll(View.FOCUS_DOWN),60);}void hideKeyboard(){try{((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(input.getWindowToken(),0);}catch(Throwable ignored){}}
}
