package com.kareem.cortex;

import android.database.Cursor;
import java.util.*;

/** Answers state questions from live Cortex state instead of semantic similarity. */
public final class AskOperationalEngine {
    private AskOperationalEngine(){}

    public static GroundedAnswer tryAnswer(VaultDb db,String question){String q=n(question),norm=LocalSemanticEmbedder.norm(q);if(q.isEmpty())return null;if(isRunningApps(norm))return runningApps(db,q);if(isPhoneContext(norm))return phoneContext(db,q);if(isAttention(norm))return attention(db,q);if(isWaiting(norm))return waiting(db,q);if(isRecentDecisions(norm))return decisions(db,q);if(isGoals(norm))return kinds(db,q,"Your active goals",new String[]{"GOAL_SIGNAL"},12);if(isIdeas(norm))return kinds(db,q,"Ideas and opportunities currently in Cortex",new String[]{"IDEA","OPPORTUNITY","INSIGHT","HYPOTHESIS"},12);if(isContextlessProject(norm))return new GroundedAnswer(q,"Tell me which project you mean, and I’ll ground the answer in that project’s Cortex context.",1.0,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());return null;}

    private static GroundedAnswer runningApps(VaultDb db,String q){try{PhoneContextStore.ensure(db);int count=PhoneContextStore.activeProcessCount(db);String s=PhoneContextStore.activeProcessSummary(db,35);if(count<=0||s.isEmpty())return new GroundedAnswer(q,"Cortex doesn’t have a current system-process snapshot yet. Standard foreground/recent-app context may still be available; Shizuku access is needed for the deeper running-process snapshot.",.98,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());return new GroundedAnswer(q,"Latest running-process state ("+count+" visible process names):\n"+s,.98,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());}catch(Throwable e){return new GroundedAnswer(q,"Cortex couldn’t read the current running-process state right now.",.80,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());}}
    private static GroundedAnswer phoneContext(VaultDb db,String q){try{PhoneContextStore.ensure(db);String s=PhoneContextStore.recentSummary(db,6L*60L*60L*1000L,14);if(s.isEmpty())return new GroundedAnswer(q,"Cortex doesn’t have recent phone-context events yet. Enable Phone context access for Notification, Accessibility and Usage Access, then use the phone normally.",.98,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());return new GroundedAnswer(q,"Recent phone context:\n"+s,.98,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());}catch(Throwable e){return new GroundedAnswer(q,"Cortex couldn’t read the local phone-context timeline right now.",.80,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());}}

    private static GroundedAnswer attention(VaultDb db,String q){ContactSafetyMaintenance.run(db);CognitiveStore.ensure(db);ReviewQueueStore.expireStale(db);LinkedHashSet<String> lines=new LinkedHashSet<>();ArrayList<SemanticHit> sources=new ArrayList<>();ArrayList<String> loops=new ArrayList<>();String legacySql="SELECT a.item_id,a.action_text,a.due_text FROM actions a JOIN knowledge_items k ON k.id=a.item_id LEFT JOIN smart_inbox si ON si.item_id=k.id WHERE a.status='open' AND NOT (k.type='CONTACT' AND k.source='contacts_sync') AND (k.type NOT IN ('SCREENSHOT','IMAGE') OR COALESCE(si.manual_bucket,0)=1) AND NOT EXISTS (SELECT 1 FROM source_links sl JOIN derived_items di ON di.id=sl.to_id WHERE sl.from_type='memory' AND sl.from_id=k.id AND sl.to_type='derived' AND di.kind='ACTION' AND di.state='open') ORDER BY CASE WHEN a.due_text IS NULL OR TRIM(a.due_text)='' THEN 1 ELSE 0 END,a.created_at DESC LIMIT 12";Cursor c=db.getReadableDatabase().rawQuery(legacySql,null);while(c.moveToNext()){long itemId=c.getLong(0);String action=n(c.getString(1)),due=n(c.getString(2));if(action.isEmpty())continue;String line=action+(due.isEmpty()?"":" — due: "+TemporalResolver.displayStored(due));if(lines.add(line)){loops.add(line);addSource(db,sources,itemId,.98,action);}}c.close();Cursor d=db.getReadableDatabase().rawQuery("SELECT kind,title,body,confidence FROM derived_items WHERE state='open' AND kind IN ('ACTION','WAITING') ORDER BY importance DESC,updated_at DESC LIMIT 12",null);while(d.moveToNext()){String kind=n(d.getString(0)),title=n(d.getString(1)),body=n(d.getString(2));String payload=!body.isEmpty()?body:title;if(payload.isEmpty())continue;String line=("WAITING".equals(kind)?"Waiting: ":"Action: ")+clip(payload,180);if(lines.add(line))loops.add(line);}d.close();for(ReviewQueueStore.Item r:ReviewQueueStore.pending(db,5)){String payload=!r.body.isEmpty()?r.body:r.title;String line="Review "+friendly(r.candidateKind)+": "+clip(payload,160);lines.add(line);}Cursor f=db.getReadableDatabase().rawQuery("SELECT id,title FROM knowledge_items WHERE status IN ('analysis_failed','failed_retryable') AND NOT (type='CONTACT' AND source='contacts_sync') ORDER BY updated_at DESC LIMIT 5",null);while(f.moveToNext()){long id=f.getLong(0);String line="Needs retry: "+n(f.getString(1));if(lines.add(line))addSource(db,sources,id,.90,line);}f.close();String answer;if(lines.isEmpty())answer="Nothing currently needs your attention in Cortex.";else{StringBuilder s=new StringBuilder("Here’s what currently needs your attention:\n");int i=0;for(String x:lines){s.append("• ").append(x).append('\n');if(++i>=10)break;}answer=s.toString().trim();}return new GroundedAnswer(q,answer,.97,sources,loops,new ArrayList<String>());}
    private static GroundedAnswer waiting(VaultDb db,String q){CognitiveStore.ensure(db);LinkedHashSet<String> xs=new LinkedHashSet<>();ArrayList<String> loops=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT title,body FROM derived_items WHERE kind='WAITING' AND state='open' ORDER BY importance DESC,updated_at DESC LIMIT 12",null);while(c.moveToNext()){String x=n(c.getString(1));if(x.isEmpty())x=n(c.getString(0));if(!x.isEmpty())xs.add(clip(x,180));}c.close();for(String x:xs)loops.add(x);String answer;if(xs.isEmpty())answer="Cortex doesn’t currently have any confirmed Waiting items.";else{StringBuilder s=new StringBuilder("You’re currently waiting on:\n");for(String x:xs)s.append("• ").append(x).append('\n');answer=s.toString().trim();}return new GroundedAnswer(q,answer,.97,new ArrayList<SemanticHit>(),loops,new ArrayList<String>());}
    private static GroundedAnswer decisions(VaultDb db,String q){CognitiveStore.ensure(db);ArrayList<String> xs=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT title,body FROM derived_items WHERE kind='DECISION' AND state IN ('open','confirmed') ORDER BY updated_at DESC LIMIT 10",null);while(c.moveToNext()){String x=n(c.getString(1));if(x.isEmpty())x=n(c.getString(0));if(!x.isEmpty())xs.add(clip(x,220));}c.close();String answer;if(xs.isEmpty())answer="I don’t have any confirmed recent decisions in the Cortex decision ledger yet.";else{StringBuilder s=new StringBuilder("Recent confirmed decisions:\n");for(String x:xs)s.append("• ").append(x).append('\n');answer=s.toString().trim();}return new GroundedAnswer(q,answer,.96,new ArrayList<SemanticHit>(),new ArrayList<String>(),xs);}
    private static GroundedAnswer kinds(VaultDb db,String q,String heading,String[] kinds,int limit){CognitiveStore.ensure(db);StringBuilder marks=new StringBuilder();for(int i=0;i<kinds.length;i++){if(i>0)marks.append(',');marks.append('?');}String sql="SELECT kind,title,body FROM derived_items WHERE state IN ('open','confirmed') AND kind IN ("+marks+") ORDER BY importance DESC,updated_at DESC LIMIT ?";String[] args=new String[kinds.length+1];System.arraycopy(kinds,0,args,0,kinds.length);args[kinds.length]=String.valueOf(limit);LinkedHashSet<String> lines=new LinkedHashSet<>();Cursor c=db.getReadableDatabase().rawQuery(sql,args);while(c.moveToNext()){String kind=n(c.getString(0)),body=n(c.getString(2));if(body.isEmpty())body=n(c.getString(1));if(!body.isEmpty())lines.add(friendly(kind)+": "+clip(body,220));}c.close();if(lines.isEmpty())return new GroundedAnswer(q,"Cortex doesn’t have any confirmed items for that yet.",.96,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());StringBuilder out=new StringBuilder(heading).append(":\n");for(String x:lines)out.append("• ").append(x).append('\n');return new GroundedAnswer(q,out.toString().trim(),.97,new ArrayList<SemanticHit>(),new ArrayList<String>(),new ArrayList<String>());}

    private static boolean isRunningApps(String q){return has(q,"what apps are running","what is running on my phone","running apps","running processes","background apps","background processes","ايه الابلكيشنات الشغاله","إيه الابلكيشنات الشغالة","ايه التطبيقات الشغاله","إيه التطبيقات الشغالة","ايه شغال على الموبايل","إيه شغال على الموبايل","البرامج اللي شغاله","البرامج اللي شغالة");}
    private static boolean isPhoneContext(String q){return has(q,"what app am i using","what app was i using","what was i doing on my phone","what was i doing","recent apps","last apps","current app","phone context","what did i open","what have i been doing on my phone","كنت فاتح ايه","كنت فاتح إيه","انا فاتح ايه","أنا فاتح إيه","كنت بعمل ايه على الموبايل","كنت بعمل إيه على الموبايل","آخر ابلكيشنات","اخر ابلكيشنات","آخر تطبيقات","اخر تطبيقات","عملت ايه على الموبايل","عملت إيه على الموبايل");}
    private static boolean isAttention(String q){return has(q,"what still needs my attention","what needs my attention","what needs me","what do i need to do","what should i do","needs attention","محتاج انتباهي","محتاج مني","محتاج اعمل ايه","محتاج أعمل ايه","ايه اللي محتاجني","إيه اللي محتاجني","ايه اللي محتاج اهتمامي","إيه اللي محتاج اهتمامي");}
    private static boolean isWaiting(String q){return has(q,"what am i waiting for","what am i waiting on","what are we waiting for","waiting on","waiting for","مستني ايه","مستنى ايه","منتظر ايه","في انتظار ايه");}
    private static boolean isRecentDecisions(String q){return has(q,"what did i decide recently","recent decisions","what have i decided","قررت ايه مؤخرا","قررت ايه قريب","ايه القرارات الاخيره","إيه القرارات الأخيرة");}
    private static boolean isGoals(String q){return has(q,"what are my goals","what am i trying to achieve","my active goals","my goals","اهدافي ايه","أهدافي ايه","ايه اهدافي","إيه أهدافي","هدفي ايه","هدفي إيه");}
    private static boolean isIdeas(String q){return has(q,"what ideas do i have","what opportunities do i have","ideas and opportunities","my ideas","my opportunities","افكاري ايه","أفكاري ايه","ايه الفرص","إيه الفرص","ايه الافكار","إيه الأفكار");}
    private static boolean isContextlessProject(String q){return has(q,"this project","المشروع ده","المشروع دا","البروجكت ده","البروجكت دا");}
    private static boolean has(String t,String... xs){for(String x:xs)if(t.contains(LocalSemanticEmbedder.norm(x)))return true;return false;}
    private static void addSource(VaultDb db,ArrayList<SemanticHit> out,long id,double score,String snippet){for(SemanticHit h:out)if(h.item.id==id)return;KnowledgeItem k=db.getById(id);if(k!=null)out.add(new SemanticHit(k,score,snippet));}
    private static String friendly(String x){String k=n(x).toUpperCase(Locale.ROOT);if("GOAL_SIGNAL".equals(k))return"Goal";if("IDEA".equals(k))return"Idea";if("OPPORTUNITY".equals(k))return"Opportunity";if("INSIGHT".equals(k))return"Insight";if("HYPOTHESIS".equals(k))return"Hypothesis";String low=k.toLowerCase(Locale.ROOT).replace('_',' ');return low.isEmpty()?"item":low;}
    private static String clip(String s,int n){String x=s==null?"":s.replaceAll("\\s+"," ").trim();return x.length()<=n?x:x.substring(0,n)+"…";}
    private static String n(String s){return s==null?"":s.trim();}
}
