package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.util.*;

/** Developer harness for calibrating attention decisions against real Cortex data. */
public final class AttentionEvaluationActivity extends Activity {
    VaultDb db;LinearLayout content;
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(getApplicationContext());CognitiveStore.ensure(db);AttentionAdjudicationStore.ensure(db);build();render();}
    @Override protected void onDestroy(){if(db!=null)try{db.close();}catch(Throwable ignored){}db=null;super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(14),dp(18),dp(28));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);CortexUi.fitSystemBars(this,root);}
    void render(){content.removeAllViews();TextView h=CortexUi.plain(this,"Attention Evaluation",28,CortexUi.TEXT);CortexUi.medium(h);content.addView(h);TextView sub=CortexUi.text(this,"Judge whether Cortex is surfacing the right things now. Corrections affect attention calibration only; they do not rewrite relevance or memory.",12,CortexUi.MUTED);sub.setPadding(0,dp(5),0,dp(14));content.addView(sub);
        ArrayList<Row> rows=load(40);Stats s=stats();content.addView(summary(s));if(rows.isEmpty()){TextView e=CortexUi.text(this,"No open Action / Waiting / Decision candidates to evaluate.",13,CortexUi.MUTED);e.setPadding(0,dp(22),0,0);content.addView(e);return;}for(Row r:rows)card(r);
    }
    View summary(Stats s){LinearLayout box=CortexUi.card(this,20);box.setPadding(dp(14),dp(13),dp(14),dp(13));TextView a=CortexUi.plain(this,s.total+" judged  •  "+s.correct+" correct  •  "+s.tooHigh+" too high  •  "+s.tooLow+" too low",11,CortexUi.TEXT);box.addView(a);if(s.total>0){int acc=Math.round(100f*s.correct/s.total);TextView b=CortexUi.plain(this,"Agreement: "+acc+"%",10,CortexUi.MUTED);b.setPadding(0,dp(5),0,0);box.addView(b);}return box;}
    void card(Row r){LinearLayout c=CortexUi.card(this,18);c.setPadding(dp(14),dp(13),dp(14),dp(13));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView t=CortexUi.text(this,clip(r.item.title.isEmpty()?r.item.kind:r.item.title,100),14,CortexUi.TEXT);CortexUi.medium(t);top.addView(t,new LinearLayout.LayoutParams(0,-2,1));TextView chip=CortexUi.chip(this,r.learned.band+"  "+r.learned.score,bandColor(r.learned.band),true);top.addView(chip,new LinearLayout.LayoutParams(-2,dp(32)));c.addView(top);
        if(!r.item.body.isEmpty()){TextView body=CortexUi.text(this,clip(r.item.body,220),12,CortexUi.MUTED);body.setPadding(0,dp(6),0,0);body.setMaxLines(4);c.addView(body);}TextView flow=CortexUi.plain(this,"Baseline "+r.baseline.score+" → AI "+(r.aiAvailable?String.valueOf(r.aiScore):"—")+" → Learned "+r.learned.score+"  •  "+r.item.kind,10,CortexUi.MUTED);flow.setPadding(0,dp(8),0,0);c.addView(flow);TextView why=CortexUi.text(this,"Why now: "+r.learned.whyNow,11,CortexUi.TEXT);why.setPadding(0,dp(6),0,dp(10));c.addView(why);
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);String[] labels={"CORRECT","TOO HIGH","TOO LOW"};String[] verdicts={"correct","too_high","too_low"};for(int i=0;i<labels.length;i++){final String v=verdicts[i];TextView b=CortexUi.action(this,labels[i],i==0?CortexUi.SAGE:CortexUi.MUTED,false);b.setOnClickListener(x->{judge(r.item.id,v,r.learned.score);Toast.makeText(this,"Recorded "+v.replace('_',' '),Toast.LENGTH_SHORT).show();render();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(42),1);if(i>0)p.setMargins(dp(6),0,0,0);actions.addView(b,p);}c.addView(actions);
        LinearLayout actions2=new LinearLayout(this);actions2.setOrientation(LinearLayout.HORIZONTAL);TextView quiet=CortexUi.action(this,"SHOULD BE QUIET",CortexUi.MUTED,false),now=CortexUi.action(this,"SHOULD BE NOW",CortexUi.ACCENT,false);quiet.setOnClickListener(x->{judge(r.item.id,"should_be_quiet",0);AttentionLearning.record(db,r.item.id,"dismissed");render();});now.setOnClickListener(x->{judge(r.item.id,"should_be_now",100);AttentionLearning.record(db,r.item.id,"opened");render();});actions2.addView(quiet,new LinearLayout.LayoutParams(0,dp(42),1));LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(0,dp(42),1);np.setMargins(dp(6),dp(6),0,0);actions2.addView(now,np);c.addView(actions2);
        LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(10),0,0);content.addView(c,cp);
    }
    ArrayList<Row> load(int limit){ArrayList<Row> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,kind,title,body,source_key,state,confidence,importance,thread_id,anchor_signal_id,updated_at FROM derived_items WHERE state='open' AND kind IN ('ACTION','WAITING','DECISION') ORDER BY updated_at DESC LIMIT ?",new String[]{String.valueOf(limit)});while(c.moveToNext()){PrimeBriefStore.Item item=new PrimeBriefStore.Item(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getInt(7),c.getLong(8),c.getLong(9),c.getLong(10));AttentionEngine.Decision baseline=AttentionEngine.evaluate(item,System.currentTimeMillis());AiSnapshot ai=ai(item.id,item.updatedAt,baseline);AttentionEngine.Decision merged=ai.available?ai.decision:baseline;AttentionEngine.Decision learned=AttentionLearning.apply(db,item,merged);out.add(new Row(item,baseline,learned,ai.available,ai.score));}c.close();out.sort((a,b)->Integer.compare(b.learned.score,a.learned.score));return out;}
    AiSnapshot ai(long id,long updated,AttentionEngine.Decision baseline){try{Cursor c=db.getReadableDatabase().query("attention_adjudications",new String[]{"item_updated_at","final_score","band","why_now","model_score","confidence","expires_at"},"derived_id=?",new String[]{String.valueOf(id)},null,null,"adjudicated_at DESC","1");if(!c.moveToFirst()){c.close();return new AiSnapshot(false,baseline.score,baseline);}long itemUpdated=c.getLong(0),expires=c.getLong(6);if(itemUpdated!=updated||expires<=System.currentTimeMillis()||c.getDouble(5)<0.72){c.close();return new AiSnapshot(false,baseline.score,baseline);}int score=c.getInt(1),model=c.getInt(4);String why=c.getString(3),bandName=c.getString(2);double conf=c.getDouble(5);c.close();AttentionEngine.Band b;try{b=AttentionEngine.Band.valueOf(bandName);}catch(Exception e){b=band(score);}AttentionEngine.Decision d=new AttentionEngine.Decision(score,b,why==null||why.trim().isEmpty()?baseline.whyNow:why,baseline.urgency,baseline.consequence,baseline.responsibility,baseline.temporalPressure,baseline.openLoopPressure,baseline.novelty,conf);return new AiSnapshot(true,model,d);}catch(Throwable e){return new AiSnapshot(false,baseline.score,baseline);}}
    void judge(long id,String verdict,int target){try{JSONObject v=new JSONObject().put("verdict",verdict).put("target_score",target);CognitiveStore.feedback(db,"derived",id,"attention_eval",v.toString(),"attention_eval_001");}catch(Exception ignored){}}
    Stats stats(){Stats s=new Stats();Cursor c=db.getReadableDatabase().query("feedback_events",new String[]{"value_json"},"event_type='attention_eval'",null,null,null,"created_at DESC","500");while(c.moveToNext()){try{String v=new JSONObject(c.getString(0)).optString("verdict","");s.total++;if("correct".equals(v))s.correct++;else if("too_high".equals(v)||"should_be_quiet".equals(v))s.tooHigh++;else if("too_low".equals(v)||"should_be_now".equals(v))s.tooLow++;}catch(Exception ignored){}}c.close();return s;}
    int bandColor(AttentionEngine.Band b){if(b==AttentionEngine.Band.NOW)return CortexUi.RED;if(b==AttentionEngine.Band.LATER)return CortexUi.ORANGE;if(b==AttentionEngine.Band.WATCHING)return CortexUi.YELLOW;return CortexUi.MUTED;}AttentionEngine.Band band(int s){return s>=72?AttentionEngine.Band.NOW:s>=54?AttentionEngine.Band.LATER:s>=36?AttentionEngine.Band.WATCHING:AttentionEngine.Band.QUIET;}String clip(String s,int n){String x=s==null?"":s.replaceAll("\\s+"," ").trim();return x.length()<=n?x:x.substring(0,n)+"…";}
    static final class Row{final PrimeBriefStore.Item item;final AttentionEngine.Decision baseline,learned;final boolean aiAvailable;final int aiScore;Row(PrimeBriefStore.Item i,AttentionEngine.Decision b,AttentionEngine.Decision l,boolean a,int s){item=i;baseline=b;learned=l;aiAvailable=a;aiScore=s;}}static final class AiSnapshot{final boolean available;final int score;final AttentionEngine.Decision decision;AiSnapshot(boolean a,int s,AttentionEngine.Decision d){available=a;score=s;decision=d;}}static final class Stats{int total,correct,tooHigh,tooLow;}
}
