package com.kareem.cortex;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

public class BrainActivity extends Activity {
    static final int REQ_NOTIFY=88,REQ_BACKUP=910;
    VaultDb db;LinearLayout feed;TextView status;int bg=Color.rgb(16,17,20),panel=Color.rgb(24,26,31),text=Color.rgb(243,244,246),muted=Color.rgb(165,168,176),accent=Color.rgb(143,169,255),ok=Color.rgb(143,220,170);
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}void pad(View v,int x){v.setPadding(dp(x),dp(x),dp(x),dp(x));}
    TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);return v;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);CortexNotifications.ensureChannels(this);ProactiveScheduler.enableDaily(this);build();refresh();}
    @Override protected void onResume(){super.onResume();if(db!=null)refresh();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);pad(root,16);
        TextView title=tv("CORTEX PRIME",27,text);title.setTypeface(null,1);root.addView(title);root.addView(tv("Second brain • capture → understand → remember → act",14,muted));
        LinearLayout row1=new LinearLayout(this);row1.setOrientation(LinearLayout.HORIZONTAL);row1.setPadding(0,dp(14),0,0);Button ask=button("ASK"),loops=button("LOOPS"),timeline=button("TIMELINE");addEq(row1,ask,0);addEq(row1,loops,7);addEq(row1,timeline,7);root.addView(row1);
        LinearLayout row2=new LinearLayout(this);row2.setOrientation(LinearLayout.HORIZONTAL);row2.setPadding(0,dp(7),0,0);Button graph=button("GRAPH"),capture=button("CAPTURE"),backup=button("BACKUP"),proactive=button("PROACTIVE");addEq(row2,graph,0);addEq(row2,capture,7);addEq(row2,backup,7);addEq(row2,proactive,7);root.addView(row2);
        status=tv("",12,muted);status.setPadding(0,dp(10),0,dp(10));root.addView(status);ScrollView sv=new ScrollView(this);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);sv.addView(feed);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
        ask.setOnClickListener(v->askDialog());loops.setOnClickListener(v->loopsDialog());timeline.setOnClickListener(v->timelineDialog());graph.setOnClickListener(v->graphDialog());capture.setOnClickListener(v->startActivity(new Intent(this,MainActivity.class)));backup.setOnClickListener(v->startBackup());proactive.setOnClickListener(v->proactiveDialog());
    }
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(9);b.setTextColor(text);b.setBackgroundColor(panel);return b;}void addEq(LinearLayout r,View v,int m){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(46),1);p.setMargins(dp(m),0,0,0);r.addView(v,p);}

    void refresh(){feed.removeAllViews();int loops=SecondBrainEngine.openLoops(db,200).size(),items=count("knowledge_items","1=1"),failed=count("knowledge_items","status='analysis_failed'");ArrayList<BrainNode> nodes=SecondBrainEngine.graph(db,10);boolean notify=CortexNotifications.allowed(this);status.setText(items+" memories  •  "+loops+" open loops  •  "+nodes.size()+" active nodes"+(notify?"  •  proactive on":"  •  notifications off")+(failed>0?"  •  "+failed+" failed":""));
        ArrayList<ProactiveSignal> signals=ProactiveEngine.scan(this,db,3);sectionTitle("RESURFACED FOR YOU");if(signals.isEmpty())feed.addView(tv("Nothing urgent or forgotten enough to resurface right now.",14,muted));else for(ProactiveSignal s:signals)addSignalCard(feed,s);
        sectionTitle("ATTENTION NOW");ArrayList<BrainOpenLoop> os=SecondBrainEngine.openLoops(db,5);if(os.isEmpty())feed.addView(tv("No open loops detected.",14,muted));else for(BrainOpenLoop l:os)addLoopCard(feed,l,false);
        sectionTitle("ACTIVE CONTEXT");if(nodes.isEmpty())feed.addView(tv("Add more memories and Cortex Prime will build people/project/topic context here.",14,muted));else for(int i=0;i<Math.min(6,nodes.size());i++)addNodeCard(feed,nodes.get(i));
        sectionTitle("RECENT MEMORY");for(KnowledgeItem k:db.lexicalSearch("",6))addMemoryCard(feed,k,null);
    }
    int count(String table,String where){Cursor c=db.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM "+table+" WHERE "+where,null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
    void sectionTitle(String s){TextView h=tv(s,11,accent);h.setTypeface(null,1);h.setPadding(0,dp(16),0,dp(7));feed.addView(h);}

    void addSignalCard(LinearLayout parent,ProactiveSignal s){LinearLayout c=card();c.setClickable(true);c.setOnClickListener(v->{KnowledgeItem k=db.getById(s.itemId);if(k!=null)memoryDetail(k);ProactiveEngine.markSurfaced(this,Collections.singletonList(s));});TextView t=tv(s.title,15,text);t.setTypeface(null,1);c.addView(t);if(!empty(s.body)){TextView b=tv(s.body,13,text);b.setPadding(0,dp(5),0,0);c.addView(b);}c.addView(tv(s.kind.replace('_',' ')+"  •  "+s.reason,11,muted));addCard(parent,c);}

    void askDialog(){EditText q=new EditText(this);q.setHint("What do I know about…? What is still pending? What did we decide?");q.setMinLines(3);AlertDialog d=new AlertDialog.Builder(this).setTitle("Ask Cortex Prime").setMessage("Grounded answer • only your saved memory is used").setView(q).setNegativeButton("Cancel",null).setPositiveButton("ANSWER",null).create();d.setOnShowListener(x->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String s=q.getText().toString().trim();if(s.isEmpty())return;d.dismiss();Toast.makeText(this,"Building grounded answer…",Toast.LENGTH_SHORT).show();new Thread(()->{GroundedAnswer a=SecondBrainEngine.ask(db,s);runOnUiThread(()->answerDialog(a));}).start();}));d.show();}
    void answerDialog(GroundedAnswer a){ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);pad(box,16);sv.addView(box);label(box,"ANSWER");box.addView(tv(a.answer,15,text));label(box,"GROUNDING");box.addView(tv("Confidence "+Math.round(a.confidence*100)+"%  •  "+a.sources.size()+" memory sources\nCortex Prime does not add facts that are not present in these sources.",12,muted));if(!a.openLoops.isEmpty()){label(box,"OPEN LOOPS");box.addView(tv(bullets(a.openLoops),13,text));}if(!a.decisions.isEmpty()){label(box,"DECISIONS");box.addView(tv(bullets(a.decisions),13,text));}if(!a.sources.isEmpty()){label(box,"SOURCES");for(int i=0;i<a.sources.size();i++)addMemoryCard(box,a.sources.get(i).item,"M"+(i+1)+" • "+Math.round(a.sources.get(i).score*100)+"%");}new AlertDialog.Builder(this).setTitle("Ask Cortex Prime").setView(sv).setNegativeButton("Close",null).show();}

    void loopsDialog(){ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);pad(box,14);sv.addView(box);ArrayList<BrainOpenLoop> loops=SecondBrainEngine.openLoops(db,120);if(loops.isEmpty())box.addView(tv("No open loops detected.",14,muted));else for(BrainOpenLoop l:loops)addLoopCard(box,l,true);new AlertDialog.Builder(this).setTitle("Open Loops • "+loops.size()).setView(sv).setNegativeButton("Close",null).show();}
    void addLoopCard(LinearLayout parent,BrainOpenLoop l,boolean controls){LinearLayout c=card();TextView t=tv(l.action,14,text);t.setTypeface(null,1);c.addView(t);c.addView(tv(l.title+(empty(l.due)?"":"  •  due: "+l.due),11,muted));if(controls){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL);Button done=button("MARK DONE"),remind=button("REMIND");r.addView(done,new LinearLayout.LayoutParams(0,dp(42),1));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,dp(42),1);rp.setMargins(dp(7),0,0,0);r.addView(remind,rp);done.setOnClickListener(v->{android.content.ContentValues x=new android.content.ContentValues();x.put("status","done");db.getWritableDatabase().update("actions",x,"id=?",new String[]{String.valueOf(l.actionId)});Toast.makeText(this,"Loop closed",Toast.LENGTH_SHORT).show();refresh();});remind.setOnClickListener(v->scheduleReminder(l));c.addView(r);}addCard(parent,c);}
    void scheduleReminder(BrainOpenLoop l){requestNotifyIfNeeded();Calendar cal=Calendar.getInstance();DatePickerDialog d=new DatePickerDialog(this,(view,y,m,day)->{Calendar target=Calendar.getInstance();target.set(Calendar.YEAR,y);target.set(Calendar.MONTH,m);target.set(Calendar.DAY_OF_MONTH,day);TimePickerDialog t=new TimePickerDialog(this,(vv,h,min)->{target.set(Calendar.HOUR_OF_DAY,h);target.set(Calendar.MINUTE,min);target.set(Calendar.SECOND,0);target.set(Calendar.MILLISECOND,0);if(target.getTimeInMillis()<=System.currentTimeMillis()){Toast.makeText(this,"Choose a future time",Toast.LENGTH_LONG).show();return;}ProactiveScheduler.reminder(this,l.actionId,"Cortex Prime reminder",l.action,target.getTimeInMillis());Toast.makeText(this,"Reminder scheduled for "+new SimpleDateFormat("dd MMM • HH:mm",Locale.getDefault()).format(target.getTime()),Toast.LENGTH_LONG).show();},cal.get(Calendar.HOUR_OF_DAY),cal.get(Calendar.MINUTE),false);t.show();},cal.get(Calendar.YEAR),cal.get(Calendar.MONTH),cal.get(Calendar.DAY_OF_MONTH));d.show();}

    void timelineDialog(){ArrayList<KnowledgeItem> items=db.lexicalSearch("",240);ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);pad(box,14);sv.addView(box);String last="";SimpleDateFormat key=new SimpleDateFormat("yyyy-MM-dd",Locale.US),heading=new SimpleDateFormat("EEE, dd MMM yyyy",Locale.getDefault());for(KnowledgeItem k:items){String day=key.format(new Date(k.createdAt));if(!day.equals(last)){label(box,heading.format(new Date(k.createdAt)).toUpperCase(Locale.getDefault()));last=day;}addMemoryCard(box,k,null);}new AlertDialog.Builder(this).setTitle("Cortex Prime Timeline • "+items.size()).setView(sv).setNegativeButton("Close",null).show();}

    void graphDialog(){ArrayList<BrainNode> nodes=SecondBrainEngine.graph(db,80);String[] labels=new String[nodes.size()];for(int i=0;i<nodes.size();i++){BrainNode n=nodes.get(i);labels[i]=n.type+" • "+n.label+"  ("+n.mentions+")";}if(labels.length==0){Toast.makeText(this,"No graph nodes yet",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("People • Projects • Topics").setItems(labels,(d,w)->nodeContext(nodes.get(w))).setNegativeButton("Close",null).show();}
    void addNodeCard(LinearLayout parent,BrainNode n){LinearLayout c=card();c.setClickable(true);c.setOnClickListener(v->nodeContext(n));TextView t=tv(n.label,15,text);t.setTypeface(null,1);c.addView(t);c.addView(tv(n.type+"  •  "+n.mentions+" mentions  •  "+fmt(n.latestAt),11,muted));addCard(parent,c);}
    void nodeContext(BrainNode n){ArrayList<KnowledgeItem> items=SecondBrainEngine.context(db,n,12);ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);pad(box,14);sv.addView(box);box.addView(tv(n.type+" • "+n.mentions+" mentions",12,muted));for(KnowledgeItem k:items)addMemoryCard(box,k,null);new AlertDialog.Builder(this).setTitle(n.label).setView(sv).setNegativeButton("Close",null).show();}

    void proactiveDialog(){ArrayList<ProactiveSignal> xs=ProactiveEngine.scan(this,db,12);ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);pad(box,14);sv.addView(box);box.addView(tv(CortexNotifications.allowed(this)?"Daily proactive notifications are enabled.":"Daily scan is scheduled. Enable notification permission to receive proactive alerts.",13,muted));if(xs.isEmpty())box.addView(tv("\nNothing needs resurfacing right now.",14,text));else{label(box,"WHAT CORTEX PRIME WOULD SURFACE");for(ProactiveSignal s:xs)addSignalCard(box,s);}AlertDialog d=new AlertDialog.Builder(this).setTitle("Proactive Cortex Prime").setView(sv).setNegativeButton("Close",null).setPositiveButton(CortexNotifications.allowed(this)?"REFRESH":"ENABLE ALERTS",null).create();d.setOnShowListener(v->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(x->{if(CortexNotifications.allowed(this)){d.dismiss();refresh();}else requestNotifyIfNeeded();}));d.show();}
    void requestNotifyIfNeeded(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ_NOTIFY);}
    @Override public void onRequestPermissionsResult(int req,String[] p,int[] g){super.onRequestPermissionsResult(req,p,g);if(req==REQ_NOTIFY){boolean yes=g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED;Toast.makeText(this,yes?"Proactive notifications enabled":"Notifications remain disabled",Toast.LENGTH_SHORT).show();refresh();}}

    void startBackup(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/zip");i.putExtra(Intent.EXTRA_TITLE,"Cortex-Prime-backup-"+new SimpleDateFormat("yyyy-MM-dd-HHmm",Locale.US).format(new Date())+".zip");startActivityForResult(i,REQ_BACKUP);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==REQ_BACKUP&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();Toast.makeText(this,"Creating Cortex Prime backup…",Toast.LENGTH_SHORT).show();new Thread(()->{try{int n=BackupExporter.write(this,db,u);runOnUiThread(()->Toast.makeText(this,"Backup complete • "+n+" memories",Toast.LENGTH_LONG).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Backup failed: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}}

    void addMemoryCard(LinearLayout parent,KnowledgeItem k,String prefix){LinearLayout c=card();c.setClickable(true);c.setOnClickListener(v->memoryDetail(k));TextView t=tv((prefix==null?"":prefix+"  ")+k.title,14,text);t.setTypeface(null,1);c.addView(t);c.addView(tv(k.category+"  •  "+k.type+"  •  "+fmt(k.createdAt),11,muted));String p=!empty(k.summary)?k.summary:(!empty(k.extractedText)?k.extractedText:k.rawText);if(p==null)p="";if(p.length()>220)p=p.substring(0,220)+"…";TextView b=tv(p,13,text);b.setPadding(0,dp(5),0,0);c.addView(b);addCard(parent,c);}
    void memoryDetail(KnowledgeItem k){ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);pad(box,15);sv.addView(box);label(box,"SUMMARY");box.addView(tv(empty(k.summary)?"No summary":k.summary,14,text));if(!empty(k.extractedText)){label(box,"EXTRACTED / TRANSCRIPT");String x=k.extractedText;if(x.length()>5000)x=x.substring(0,5000)+"…";box.addView(tv(x,13,text));}ArrayList<String> acts=db.actions(k.id);if(!acts.isEmpty()){label(box,"OPEN ACTIONS");box.addView(tv(bullets(acts),13,text));}ArrayList<SemanticHit> rel=SemanticIndex.related(db,k,5);if(!rel.isEmpty()){label(box,"RELATED MEMORIES");for(SemanticHit h:rel)addMemoryCard(box,h.item,Math.round(h.score*100)+"%");}new AlertDialog.Builder(this).setTitle(k.title).setView(sv).setNegativeButton("Close",null).show();}

    LinearLayout card(){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackgroundResource(R.drawable.rounded_panel);pad(c,12);return c;}void addCard(LinearLayout p,View c){LinearLayout.LayoutParams x=new LinearLayout.LayoutParams(-1,-2);x.setMargins(0,0,0,dp(8));p.addView(c,x);}void label(LinearLayout p,String s){TextView h=tv(s,11,accent);h.setTypeface(null,1);h.setPadding(0,dp(12),0,dp(5));p.addView(h);}String bullets(ArrayList<String> xs){StringBuilder s=new StringBuilder();for(String x:xs){if(s.length()>0)s.append('\n');s.append("• ").append(x);}return s.toString();}boolean empty(String s){return s==null||s.trim().isEmpty();}String fmt(long ms){return new SimpleDateFormat("dd MMM • HH:mm",Locale.getDefault()).format(new Date(ms));}
}
