package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.util.*;
import java.util.concurrent.*;

/** Visible, actionable truth table for the 43 Cortex capabilities. */
public final class CapabilityMatrixActivity extends Activity {
    LinearLayout list;TextView summary;volatile boolean destroyed=false;final ExecutorService worker=Executors.newSingleThreadExecutor();
    int dp(int x){return CortexUi.dp(this,x);}
    static final class Row{CortexCapabilityRegistry.Capability c;CortexCapabilityRegistry.State s;Row(CortexCapabilityRegistry.Capability c,CortexCapabilityRegistry.State s){this.c=c;this.s=s;}}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);build();load();}
    @Override protected void onResume(){super.onResume();load();}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),dp(30));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout hs=new LinearLayout(this);hs.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"43 Cortex capabilities",27,CortexUi.TEXT);CortexUi.medium(h);hs.addView(h);hs.addView(CortexUi.text(this,"Runtime truth, not feature inventory. Tap a capability to open its working surface, setup or recovery path.",11,CortexUi.MUTED));head.addView(hs,new LinearLayout.LayoutParams(0,-2,1));body.addView(head);summary=CortexUi.text(this,"Checking…",13,CortexUi.MUTED);summary.setPadding(0,dp(12),0,dp(12));body.addView(summary);TextView phone=CortexUi.action(this,"Phone context access",CortexUi.ACCENT,true);phone.setOnClickListener(v->open(PhoneContextAccessActivity.class));body.addView(phone,new LinearLayout.LayoutParams(-1,dp(48)));TextView audit=CortexUi.action(this,"Open full functional diagnostics",CortexUi.MUTED,false);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(46));ap.setMargins(0,dp(8),0,dp(14));body.addView(audit,ap);audit.setOnClickListener(v->open(CortexAuditActivity.class));list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);setContentView(root);CortexUi.fitSystemBars(this,root);}

    void load(){if(destroyed||worker.isShutdown())return;try{worker.execute(()->{ArrayList<Row> rows=new ArrayList<>();int active=0,ready=0,access=0,setup=0,failed=0,other=0;VaultDb db=null;try{db=new VaultDb(getApplicationContext());for(CortexCapabilityRegistry.Capability c:CortexCapabilityRegistry.all()){CortexCapabilityRegistry.State s=CortexCapabilityRegistry.evaluate(getApplicationContext(),db,c);if("stability_soak".equals(c.key))s=soakState(db,s);else if("warm_qwen".equals(c.key))s=warmState(s);rows.add(new Row(c,s));if(CortexCapabilityRegistry.ACTIVE.equals(s.status))active++;else if(CortexCapabilityRegistry.READY.equals(s.status))ready++;else if(CortexCapabilityRegistry.NEEDS_ACCESS.equals(s.status))access++;else if(CortexCapabilityRegistry.NEEDS_SETUP.equals(s.status))setup++;else if(CortexCapabilityRegistry.FAILED.equals(s.status))failed++;else other++;}}catch(Throwable e){}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}final int a=active,r=ready,ac=access,se=setup,f=failed,o=other;post(()->render(rows,a,r,ac,se,f,o));});}catch(RejectedExecutionException ignored){}}
    CortexCapabilityRegistry.State soakState(VaultDb db,CortexCapabilityRegistry.State fallback){try{CortexAuditScheduler.SoakState s=CortexAuditScheduler.soakState(db);if(s==null)return new CortexCapabilityRegistry.State(CortexCapabilityRegistry.READY,"30-minute real stability soak is available · tap to start");if(s.active()){long left=Math.max(0,s.targetEndAt-System.currentTimeMillis());return new CortexCapabilityRegistry.State(CortexCapabilityRegistry.ACTIVE,"Stability soak running · about "+Math.max(1,(left+59_999L)/60_000L)+" min remaining · tap to stop/open");}if("complete".equals(s.status))return new CortexCapabilityRegistry.State(CortexCapabilityRegistry.ACTIVE,"Last real stability soak completed · tap to run again");if("canceled".equals(s.status))return new CortexCapabilityRegistry.State(CortexCapabilityRegistry.READY,"Last stability soak was stopped · tap to run again");return fallback;}catch(Throwable e){return fallback;}}
    CortexCapabilityRegistry.State warmState(CortexCapabilityRegistry.State fallback){try{if(!LocalModelManager.verified(this))return new CortexCapabilityRegistry.State(CortexCapabilityRegistry.NEEDS_SETUP,"Verify/install Local Qwen first");long age=LocalLlmBridge.cachedModelAgeMs();if(age>0)return new CortexCapabilityRegistry.State(CortexCapabilityRegistry.ACTIVE,"Production Qwen cache is warm · age "+friendlyAge(age)+" · tap to refresh");return new CortexCapabilityRegistry.State(CortexCapabilityRegistry.READY,"Local Qwen verified · production cache is cold · tap to warm");}catch(Throwable e){return fallback;}}

    void render(ArrayList<Row> rows,int active,int ready,int access,int setup,int failed,int other){if(destroyed)return;summary.setText(active+" ACTIVE · "+ready+" READY · "+access+" NEEDS ACCESS · "+setup+" NEEDS SETUP · "+failed+" FAILED"+(other>0?" · "+other+" NOT VERIFIED":""));summary.setTextColor(failed>0?CortexUi.CORAL:(access+setup>0?CortexUi.COPPER:CortexUi.SAGE));list.removeAllViews();for(Row r:rows){LinearLayout c=CortexUi.card(this,18);c.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=CortexUi.text(this,r.c.number+". "+r.c.title,13,CortexUi.TEXT);CortexUi.medium(title);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView badge=CortexUi.chip(this,r.s.status,statusColor(r.s.status),true);top.addView(badge,new LinearLayout.LayoutParams(-2,dp(30)));c.addView(top);TextView detail=CortexUi.text(this,r.s.detail,11,CortexUi.MUTED);detail.setPadding(0,dp(6),0,0);c.addView(detail);
            if("stability_soak".equals(r.c.key)){TextView hint=CortexUi.plain(this,"Tap to start / stop stability soak  ›",10,CortexUi.ACCENT);hint.setPadding(0,dp(7),0,0);c.addView(hint);CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,18));c.setOnClickListener(v->toggleSoak());}
            else if("warm_qwen".equals(r.c.key)){TextView hint=CortexUi.plain(this,"Tap to warm / refresh production cache  ›",10,CortexUi.ACCENT);hint.setPadding(0,dp(7),0,0);c.addView(hint);CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,18));c.setOnClickListener(v->warmQwen());}
            else{Class<?> target=target(r.c.key);if(target!=null){TextView hint=CortexUi.plain(this,"Tap to open / configure  ›",10,CortexUi.ACCENT);hint.setPadding(0,dp(7),0,0);c.addView(hint);CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,18));c.setOnClickListener(v->open(target));}}
            LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));list.addView(c,p);}}

    void toggleSoak(){if(destroyed||worker.isShutdown())return;try{worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());CortexAuditScheduler.SoakState s=CortexAuditScheduler.soakState(db);if(s!=null&&s.active()){final long id=s.runId;post(()->new AlertDialog.Builder(this).setTitle("Stop stability soak?").setMessage("Samples already captured will stay in diagnostics.").setNegativeButton("Keep running",null).setPositiveButton("Stop",(d,w)->{CortexAuditScheduler.stop(this,id);load();}).show());return;}CortexAuditStore.Run active=CortexAuditStore.active(db);if(active!=null){post(()->Toast.makeText(this,"Another Cortex diagnostic run is already active. Stop or finish it first.",Toast.LENGTH_LONG).show());return;}CortexAuditScheduler.startSoak(getApplicationContext());post(()->{Toast.makeText(this,"30-minute Cortex stability soak started",Toast.LENGTH_LONG).show();load();open(CortexAuditActivity.class);});}catch(Throwable e){post(()->Toast.makeText(this,"Stability soak could not start safely",Toast.LENGTH_LONG).show());}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}});}catch(RejectedExecutionException ignored){}}

    void warmQwen(){if(destroyed||worker.isShutdown())return;if(!LocalModelManager.verified(this)){Toast.makeText(this,"Install/verify Local Qwen first",Toast.LENGTH_LONG).show();open(EnvironmentActivity.class);return;}Toast.makeText(this,"Warming Local Qwen production cache…",Toast.LENGTH_SHORT).show();try{worker.execute(()->{VaultDb db=null;try{long at=System.currentTimeMillis();LocalLlmBridge.CompletionResult r=LocalLlmBridge.completeCached(LocalModelManager.modelFile(getApplicationContext()).getAbsolutePath(),"Reply with exactly CORTEX_WARM_OK. /no_think","You are a deterministic Cortex cache warm-up. Reply exactly CORTEX_WARM_OK. /no_think",24);boolean ok=r.getText()!=null&&r.getText().toUpperCase(Locale.ROOT).contains("CORTEX_WARM_OK");try{db=new VaultDb(getApplicationContext());InteractionTelemetry.ensure(db);InteractionTelemetry.log(db,"Local Brain","warm_qwen","complete",0,r.getDurationMs(),ok?"ok":"warning",ok?"Production model cache warmed":"Warm-up completed with unexpected text",new JSONObject().put("cache_hit",r.getCacheHit()).put("model_load_ms",r.getModelLoadMs()).put("generation_ms",r.getGenerationMs()).put("tokens_per_second",r.getTokensPerSecond()).put("started_at",at));}catch(Throwable ignored){}post(()->{Toast.makeText(this,ok?"Local Qwen cache is warm":"Qwen loaded, but warm-up response was unexpected",Toast.LENGTH_LONG).show();load();});}catch(Throwable e){post(()->Toast.makeText(this,"Local Qwen warm-up failed safely",Toast.LENGTH_LONG).show());}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}});}catch(RejectedExecutionException ignored){}}

    Class<?> target(String k){
        if(any(k,"permissions","notification_capture"))return PhoneContextAccessActivity.class;
        if(any(k,"ocr"))return OcrTestActivity.class;
        if(any(k,"visual_intelligence","visual_actions"))return VisualIntelligenceActivity.class;
        if(any(k,"strong_vision"))return ExternalModelCheckActivity.class;
        if(any(k,"local_qwen","screenshot_folder","screenshot_queue","background_visual","app_identity","components","db_integrity","db_schema","attachments","dedup","performance","debug_export","interaction_telemetry"))return EnvironmentActivity.class;
        if(any(k,"grounded_ask","semantic_retrieval"))return AskCortexActivity.class;
        if(any(k,"smart_inbox","proactive_needs","briefs"))return PremiumHomeActivity.class;
        if(any(k,"people_memory","projects_context","graph_relations"))return PeopleProjectsActivity.class;
        if(any(k,"prompt_library"))return PromptLibraryActivity.class;
        if(any(k,"vault_readability"))return VaultActivity.class;
        if(any(k,"screenshot_learning","corrections","user_feedback"))return CorrectionLearningActivity.class;
        if(any(k,"audio_asr"))return AsrSettingsActivity.class;
        if(any(k,"privacy_guard","calendar_read","contacts_read","backup_export","calendar_write","restore","external_writes","temporal_actions"))return FeatureHubActivity.class;
        return null;
    }
    boolean any(String k,String...xs){for(String x:xs)if(x.equals(k))return true;return false;}
    int statusColor(String s){if(CortexCapabilityRegistry.ACTIVE.equals(s))return CortexUi.SAGE;if(CortexCapabilityRegistry.FAILED.equals(s))return CortexUi.CORAL;if(CortexCapabilityRegistry.NEEDS_ACCESS.equals(s)||CortexCapabilityRegistry.NEEDS_SETUP.equals(s))return CortexUi.COPPER;return CortexUi.MUTED;}
    void open(Class<?> cls){try{startActivity(new Intent(this,cls));}catch(Throwable e){Toast.makeText(this,"This Cortex surface could not open",Toast.LENGTH_SHORT).show();}}
    void post(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())r.run();});}
    String friendlyAge(long ms){long s=Math.max(0,ms/1000L);if(s<60)return s+"s";long m=s/60;if(m<60)return m+"m";return(m/60)+"h "+(m%60)+"m";}
}
