package com.kareem.cortex;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.io.File;
import java.util.Locale;
import java.util.concurrent.*;

/** Fast capture sheet: capture first, then immediately show Cortex understanding. */
public class CaptureActivity extends Activity {
    static final int REQ_MIC=771,REQ_FILE=772,REQ_PHOTO=773;
    VaultDb db;AudioCapture recorder=new AudioCapture();long recordingStarted;Handler handler=new Handler(Looper.getMainLooper());Runnable tick;FrameLayout root;LinearLayout sheet,recordPanel,choices;TextView timer,importState;volatile boolean destroyed=false;boolean healthContext=false;
    final ExecutorService io=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"cortex-capture-io");t.setPriority(Thread.NORM_PRIORITY-1);return t;});
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);healthContext=getIntent()!=null&&getIntent().getBooleanExtra("health_context",false);db=new VaultDb(this);build();handleIncoming(getIntent());handler.postDelayed(()->handleMode(getIntent()),120);}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);if(i!=null&&i.hasExtra("health_context"))healthContext=i.getBooleanExtra("health_context",false);handleIncoming(i);handler.postDelayed(()->handleMode(i),120);}
    @Override protected void onDestroy(){destroyed=true;if(tick!=null)handler.removeCallbacks(tick);if(recorder.isRunning())try{File f=recorder.stop();if(f!=null)f.delete();}catch(Throwable ignored){}try{if(db!=null)db.close();}catch(Throwable ignored){}io.shutdown();super.onDestroy();}

    void build(){Window w=getWindow();w.setBackgroundDrawableResource(android.R.color.transparent);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);WindowManager.LayoutParams lp=w.getAttributes();lp.dimAmount=.55f;w.setAttributes(lp);
        root=new FrameLayout(this);root.setBackgroundColor(Color.TRANSPARENT);root.setOnClickListener(v->finish());
        sheet=new LinearLayout(this);sheet.setOrientation(LinearLayout.VERTICAL);sheet.setPadding(dp(20),dp(16),dp(20),dp(20));sheet.setBackground(CortexUi.round(this,CortexUi.SURFACE,Color.TRANSPARENT,28));sheet.setOnClickListener(v->{});
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);TextView title=CortexUi.plain(this,healthContext?"Health evidence":"Capture",24,CortexUi.TEXT);CortexUi.medium(title);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView close=CortexUi.plain(this,"×",28,CortexUi.MUTED);close.setGravity(Gravity.CENTER);close.setOnClickListener(v->{CortexHaptics.press(v);finish();});head.addView(close,new LinearLayout.LayoutParams(dp(42),dp(42)));sheet.addView(head);
        importState=CortexUi.plain(this,"Importing safely…",11,CortexUi.ACCENT);importState.setPadding(0,dp(7),0,dp(5));importState.setVisibility(View.GONE);sheet.addView(importState);
        choices=new LinearLayout(this);choices.setOrientation(LinearLayout.VERTICAL);choices.setPadding(0,dp(10),0,0);LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);addTile(top,"Voice",this::startVoice,0);addTile(top,"Text",this::quickNote,8);choices.addView(top,new LinearLayout.LayoutParams(-1,dp(92)));LinearLayout bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.HORIZONTAL);addTile(bottom,"File",this::pickFile,0);addTile(bottom,"Photo",this::pickPhoto,8);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(92));bp.setMargins(0,dp(8),0,0);choices.addView(bottom,bp);sheet.addView(choices);
        FrameLayout.LayoutParams sp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);sp.setMargins(dp(12),0,dp(12),dp(12));root.addView(sheet,sp);setContentView(root);applyInsets();}

    /** CaptureSheetTheme can ignore adjustResize on some devices, so move the sheet above the IME explicitly. */
    void applyInsets(){root.setOnApplyWindowInsetsListener((v,insets)->{int l=0,t=0,r=0,b=0,ime=0;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets sys=insets.getInsets(WindowInsets.Type.systemBars());android.graphics.Insets keyboard=insets.getInsets(WindowInsets.Type.ime());l=sys.left;t=sys.top;r=sys.right;b=sys.bottom;ime=keyboard.bottom;}else{l=insets.getSystemWindowInsetLeft();t=insets.getSystemWindowInsetTop();r=insets.getSystemWindowInsetRight();b=insets.getSystemWindowInsetBottom();}v.setPadding(l,t,r,0);ViewGroup.LayoutParams raw=sheet.getLayoutParams();if(raw instanceof FrameLayout.LayoutParams){FrameLayout.LayoutParams p=(FrameLayout.LayoutParams)raw;p.leftMargin=dp(12);p.rightMargin=dp(12);p.bottomMargin=dp(12)+Math.max(b,ime);sheet.setLayoutParams(p);}return insets;});root.requestApplyInsets();}

    void addTile(LinearLayout row,String label,Runnable action,int left){TextView tile=CortexUi.plain(this,label,16,CortexUi.TEXT);CortexUi.medium(tile);tile.setGravity(Gravity.CENTER);CortexUi.pressable(this,tile,CortexUi.round(this,CortexUi.SURFACE_2,Color.TRANSPARENT,20));tile.setOnClickListener(v->action.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(left),0,0,0);row.addView(tile,p);}

    void handleIncoming(Intent i){if(i==null)return;String a=i.getAction();if(Intent.ACTION_SEND.equals(a)){importIntentAsync(new Intent(i),false);}else if(Intent.ACTION_SEND_MULTIPLE.equals(a)){importIntentAsync(new Intent(i),true);}}
    void handleMode(Intent i){if(i==null)return;String a=i.getAction();if(Intent.ACTION_SEND.equals(a)||Intent.ACTION_SEND_MULTIPLE.equals(a))return;String mode=i.getStringExtra("mode");if(mode==null||mode.isEmpty())return;i.removeExtra("mode");if("voice".equals(mode))startVoice();else if("text".equals(mode))quickNote();else if("photo".equals(mode))pickPhoto();else if("file".equals(mode))pickFile();}

    void quickNote(){choices.setVisibility(View.GONE);final EditText e=new EditText(this);e.setHint(healthContext?"Health note, symptom, question or follow-up…":"Type or paste…");e.setHintTextColor(CortexUi.FAINT);e.setTextColor(CortexUi.TEXT);e.setTextSize(15);e.setGravity(Gravity.TOP);e.setMinLines(4);e.setMaxLines(8);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,Color.TRANSPARENT,18));sheet.addView(e,new LinearLayout.LayoutParams(-1,-2));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setPadding(0,dp(12),0,0);TextView cancel=CortexUi.action(this,"Cancel",CortexUi.MUTED,false),save=CortexUi.action(this,"Capture",CortexUi.ACCENT,true);actions.addView(cancel,new LinearLayout.LayoutParams(0,dp(46),1));LinearLayout.LayoutParams saveParams=new LinearLayout.LayoutParams(0,dp(46),1);saveParams.setMargins(dp(8),0,0,0);actions.addView(save,saveParams);sheet.addView(actions);cancel.setOnClickListener(v->{sheet.removeView(e);sheet.removeView(actions);choices.setVisibility(View.VISIBLE);});save.setOnClickListener(v->{String s=e.getText().toString().trim();if(s.isEmpty()){e.setError("Write something first");return;}String cat=healthContext?"Health":AutoClassifier.category(s,"text/plain");String tags=healthContext?"health,note,evidence":AutoClassifier.tags(s,cat);long id=db.insert("TEXT",healthContext?"health_manual":"manual",AutoClassifier.title(s,"text/plain"),s,cat,tags,"",Fingerprint.text(s),healthContext?"{\"health_context\":true}":"{}");if(id<0)Toast.makeText(this,"Already in Cortex",Toast.LENGTH_SHORT).show();else{if(healthContext)try{HealthStore.linkKnowledgeEvidence(db,id,"text_note","health_import");}catch(Throwable ignored){}AnalysisQueue.kick(this,null,null);showResult(id);}});e.requestFocus();handler.postDelayed(()->{try{((android.view.inputmethod.InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).showSoftInput(e,android.view.inputmethod.InputMethodManager.SHOW_IMPLICIT);}catch(Throwable ignored){}},120);}

    void pickFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,REQ_FILE);}
    void pickPhoto(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,REQ_PHOTO);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();try{int take=data.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION);if((data.getFlags()&Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION)!=0)getContentResolver().takePersistableUriPermission(uri,take&Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Throwable ignored){}String mime=null;try{mime=getContentResolver().getType(uri);}catch(Throwable ignored){}importUriAsync(uri,mime,req);}

    void importUriAsync(Uri uri,String mime,int req){setImporting(true,"Importing safely…");final String type=mime;final boolean health=healthContext;io.execute(()->{VaultDb local=null;long id=0;Throwable error=null;try{local=new VaultDb(getApplicationContext());ShareImporter importer=new ShareImporter(getApplicationContext(),local);if(req==REQ_FILE&&type!=null&&type.startsWith("audio/"))id=importer.importAudio(uri,type);else{Intent share=new Intent(Intent.ACTION_SEND);share.setType(type==null?"application/octet-stream":type);share.putExtra(Intent.EXTRA_STREAM,uri);share.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);id=importer.importSingle(share);}if(health&&id>0)HealthStore.linkKnowledgeEvidence(local,id,req==REQ_PHOTO?"scan_or_photo":(type!=null&&type.startsWith("audio/")?"audio_import":"document"),"health_import");}catch(Throwable t){error=t;}finally{if(local!=null)try{local.close();}catch(Throwable ignored){}}final long itemId=id;final Throwable failure=error;runOnUiThread(()->{if(destroyed||isFinishing()||isDestroyed())return;if(itemId>0){AnalysisQueue.kick(this,null,null);showResult(itemId);}else{setImporting(false,"");Toast.makeText(this,failure==null?"Could not import or it already exists":"Import failed safely",Toast.LENGTH_LONG).show();}});});}

    void importIntentAsync(Intent incoming,boolean multiple){setImporting(true,"Importing shared content safely…");final boolean health=healthContext;io.execute(()->{VaultDb local=null;long single=0;int count=0;Throwable error=null;try{local=new VaultDb(getApplicationContext());ShareImporter importer=new ShareImporter(getApplicationContext(),local);if(multiple)count=importer.importIntent(incoming);else single=importer.importSingle(incoming);if(health&&!multiple&&single>0)HealthStore.linkKnowledgeEvidence(local,single,"shared_import","health_import");}catch(Throwable t){error=t;}finally{if(local!=null)try{local.close();}catch(Throwable ignored){}}final long id=single;final int n=count;final Throwable failure=error;runOnUiThread(()->{if(destroyed||isFinishing()||isDestroyed())return;if((multiple&&n>0)||(!multiple&&id>0)){AnalysisQueue.kick(this,null,null);if(multiple){Toast.makeText(this,n+" items captured. Cortex is analyzing them.",Toast.LENGTH_SHORT).show();startActivity(new Intent(this,PremiumHomeActivity.class));finish();}else showResult(id);}else{setImporting(false,"");Toast.makeText(this,failure==null?"Could not import or it already exists":"Import failed safely",Toast.LENGTH_LONG).show();}});});}

    void setImporting(boolean on,String message){if(importState!=null){importState.setText(message==null?"":message);importState.setVisibility(on?View.VISIBLE:View.GONE);}if(choices!=null)choices.setVisibility(on?View.GONE:View.VISIBLE);}

    void startVoice(){if(!GroqKeyStore.has(this)&&!GeminiKeyStore.has(this)){Toast.makeText(this,"Set up voice transcription in Settings first",Toast.LENGTH_LONG).show();finish();startActivity(new Intent(this,SettingsActivity.class));return;}if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}beginVoice();}
    @Override public void onRequestPermissionsResult(int req,String[] p,int[] g){super.onRequestPermissionsResult(req,p,g);if(req==REQ_MIC&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)beginVoice();else if(req==REQ_MIC)Toast.makeText(this,"Microphone permission is required",Toast.LENGTH_LONG).show();}
    void beginVoice(){try{recorder.start(this);recordingStarted=System.currentTimeMillis();showRecordingPanel();}catch(Throwable e){Toast.makeText(this,"Could not start recording",Toast.LENGTH_LONG).show();}}
    void showRecordingPanel(){choices.setVisibility(View.GONE);recordPanel=new LinearLayout(this);recordPanel.setOrientation(LinearLayout.VERTICAL);recordPanel.setPadding(0,dp(12),0,0);timer=CortexUi.plain(this,"00:00",38,CortexUi.TEXT);CortexUi.medium(timer);timer.setGravity(Gravity.CENTER);recordPanel.addView(timer);LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setPadding(0,dp(14),0,0);TextView cancel=CortexUi.action(this,"Discard",CortexUi.MUTED,false),save=CortexUi.action(this,"Stop & analyze",CortexUi.ACCENT,true);actions.addView(cancel,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams saveParams=new LinearLayout.LayoutParams(0,dp(48),1);saveParams.setMargins(dp(8),0,0,0);actions.addView(save,saveParams);recordPanel.addView(actions);cancel.setOnClickListener(v->finishVoice(false));save.setOnClickListener(v->finishVoice(true));sheet.addView(recordPanel);tick=new Runnable(){public void run(){long sec=(System.currentTimeMillis()-recordingStarted)/1000;if(timer!=null)timer.setText(String.format(Locale.US,"%02d:%02d",sec/60,sec%60));if(recorder.isRunning())handler.postDelayed(this,500);}};handler.post(tick);}
    void finishVoice(boolean save){try{File f=recorder.stop();if(tick!=null)handler.removeCallbacks(tick);if(f==null)return;if(!save){f.delete();finish();return;}if(recordPanel!=null)recordPanel.setVisibility(View.GONE);setImporting(true,"Saving voice capture safely…");persistVoiceAsync(f);}catch(Throwable e){Toast.makeText(this,"Could not save recording",Toast.LENGTH_LONG).show();}}
    void persistVoiceAsync(File f){final boolean health=healthContext;io.execute(()->{VaultDb local=null;long id=0;Throwable error=null;try{JSONObject m=new JSONObject();m.put("mime","audio/wav");m.put("bytes",f.length());m.put("recorded_at",System.currentTimeMillis());if(health)m.put("health_context",true);local=new VaultDb(getApplicationContext());id=local.insert("AUDIO",health?"health_voice":"manual_recording",health?"Health voice note":"Voice recording","",health?"Health":"Voice & Audio",health?"health,voice,evidence":"voice,audio,transcript",f.getAbsolutePath(),Fingerprint.file(f.getAbsolutePath()),m.toString());if(id<0)f.delete();else if(health&&id>0)HealthStore.linkKnowledgeEvidence(local,id,"voice_note","health_import");}catch(Throwable t){error=t;}finally{if(local!=null)try{local.close();}catch(Throwable ignored){}}final long itemId=id;final Throwable failure=error;runOnUiThread(()->{if(destroyed||isFinishing()||isDestroyed())return;if(itemId>0){AnalysisQueue.kick(this,null,null);showResult(itemId);}else{setImporting(false,"");Toast.makeText(this,failure==null?"Already in Cortex":"Could not save recording",Toast.LENGTH_LONG).show();}});});}

    void showResult(long id){try{Intent i=new Intent(this,CaptureResultActivity.class);i.putExtra("item_id",id);startActivity(i);finish();}catch(Throwable e){Toast.makeText(this,"Captured successfully. Open Brief to see it.",Toast.LENGTH_LONG).show();try{startActivity(new Intent(this,PremiumHomeActivity.class));}catch(Throwable ignored){}finish();}}
}
