package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.io.File;

/** Immediate post-capture surface: show processing, understanding and useful next actions. */
public class CaptureResultActivity extends Activity {
    VaultDb db;long itemId;Handler handler=new Handler(Looper.getMainLooper());LinearLayout content;TextView state;volatile boolean stopped=false;
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);itemId=getIntent().getLongExtra("item_id",0);build();refresh();}
    @Override protected void onDestroy(){stopped=true;handler.removeCallbacksAndMessages(null);if(db!=null){try{db.close();}catch(Throwable ignored){}db=null;}super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(16),dp(20),dp(28));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"input",null);setContentView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView h=CortexUi.plain(this,"Cortex is understanding this",24,CortexUi.TEXT);CortexUi.medium(h);head.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView close=CortexUi.chip(this,"Close",CortexUi.MUTED,false);close.setOnClickListener(v->finish());head.addView(close,new LinearLayout.LayoutParams(-2,dp(36)));content.addView(head);state=CortexUi.plain(this,"Queued for analysis…",11,CortexUi.ACCENT);state.setPadding(0,dp(7),0,dp(14));content.addView(state);}

    void refresh(){
        if(stopped||db==null||itemId<=0||isFinishing()||isDestroyed())return;
        try{
            KnowledgeItem k=db.getById(itemId);if(k==null){state.setText("Capture could not be found.");return;}render(k);if(pending(k)&&!stopped)handler.postDelayed(this::refresh,650);
        }catch(Throwable e){if(!stopped&&state!=null)state.setText("Capture is safe. Status will refresh when Cortex is ready.");}
    }
    boolean pending(KnowledgeItem k){String s=n(k.status);return s.isEmpty()||"pending".equals(s)||"queued".equals(s)||"analyzing".equals(s)||"processing".equals(s);}

    void render(KnowledgeItem k){if(stopped||content==null)return;while(content.getChildCount()>2)content.removeViewAt(2);String s=n(k.status);if("analyzed".equals(s))state.setText("Understood • ready");else if("failed_retryable".equals(s)||"analysis_failed".equals(s)||"failed".equals(s))state.setText("Analysis needs attention");else state.setText("Analyzing • extracting evidence and connecting context…");
        if(isImage(k)&&!empty(k.attachmentPath)){Bitmap bm=preview(k.attachmentPath);if(bm!=null){ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.FIT_CENTER);im.setImageBitmap(bm);im.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER_SOFT,18));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,-2);ip.setMargins(0,0,0,dp(14));content.addView(im,ip);}}
        TextView title=CortexUi.text(this,empty(k.title)?friendlyType(k.type):k.title,18,CortexUi.TEXT);CortexUi.medium(title);content.addView(title);TextView meta=CortexUi.plain(this,friendlyType(k.type)+" • "+friendlyState(s),10,CortexUi.MUTED);meta.setPadding(0,dp(5),0,dp(12));content.addView(meta);
        if(pending(k)){LinearLayout card=CortexUi.card(this,20);card.addView(CortexUi.text(this,"Cortex is reading the capture, checking what it means, and deciding whether it should become useful context, a review item, or an action.",13,CortexUi.TEXT));content.addView(card);return;}
        if("failed_retryable".equals(s)||"analysis_failed".equals(s)||"failed".equals(s)){LinearLayout card=CortexUi.card(this,20);card.addView(CortexUi.text(this,empty(k.analysisError)?"Analysis did not finish successfully.":k.analysisError,12,CortexUi.MUTED));TextView retry=CortexUi.action(this,"Retry analysis",CortexUi.ACCENT,true);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(46));rp.setMargins(0,dp(12),0,0);card.addView(retry,rp);retry.setOnClickListener(v->{if(stopped||db==null)return;try{db.retry(k.id);AnalysisQueue.kick(getApplicationContext(),null,this::refresh);state.setText("Retrying…");handler.postDelayed(this::refresh,250);}catch(Throwable e){state.setText("Retry could not start yet.");}});content.addView(card);return;}
        String understood=understanding(k);if(!empty(understood)){content.addView(CortexUi.section(this,"What Cortex understood"));TextView u=CortexUi.text(this,understood,14,CortexUi.TEXT);u.setTextIsSelectable(true);content.addView(u);}
        content.addView(CortexUi.section(this,"What you can do"));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.VERTICAL);TextView brain=CortexUi.action(this,"Ask Brain about this",CortexUi.ACCENT,true);brain.setOnClickListener(v->{try{Intent i=new Intent(this,AskCortexActivity.class);i.putExtra("prefill",brainPrompt(k));startActivity(i);}catch(Throwable ignored){}});actions.addView(brain,new LinearLayout.LayoutParams(-1,dp(46)));if(isImage(k)){TextView visual=CortexUi.action(this,"Open visual intelligence",CortexUi.MUTED,false);LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(-1,dp(44));vp.setMargins(0,dp(8),0,0);actions.addView(visual,vp);visual.setOnClickListener(v->{try{Intent i=new Intent(this,VisualIntelligenceActivity.class);i.putExtra("item_id",k.id);startActivity(i);}catch(Throwable ignored){}});}TextView archive=CortexUi.action(this,"Open evidence",CortexUi.MUTED,false);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(44));ap.setMargins(0,dp(8),0,0);actions.addView(archive,ap);archive.setOnClickListener(v->{try{Intent i=new Intent(this,VaultActivity.class);i.putExtra("item_id",k.id);startActivity(i);}catch(Throwable ignored){}});content.addView(actions);
        String raw=!empty(k.extractedText)?k.extractedText:k.rawText;if(!empty(raw)){content.addView(CortexUi.section(this,"Extracted evidence (optional)"));TextView e=CortexUi.text(this,clip(raw,1400),11,CortexUi.MUTED);e.setTextIsSelectable(true);content.addView(e);}
    }

    String understanding(KnowledgeItem k){String raw=!empty(k.extractedText)?k.extractedText:k.rawText;if(!empty(k.summary)&&VoiceTextPresentation.materiallyDifferent(k.summary,raw))return k.summary;if(!empty(k.category)&&!"Notes".equalsIgnoreCase(k.category))return "This looks like "+k.category.toLowerCase()+" content. Cortex kept the original evidence and linked it for later reasoning.";if("AUDIO".equals(k.type))return "The voice note was transcribed and indexed. Use Brain to turn its meaning into a decision, action, follow-up, or next step.";if(isImage(k))return "Visible text was extracted as evidence. Use Visual intelligence when the important meaning is in the image itself, not just the words.";if("FILE".equals(k.type))return "The file was imported and analyzed as evidence. Brain can now reason over what Cortex extracted from it.";return "The text was analyzed and indexed. Brain can now reason over its meaning instead of merely storing a copy.";}
    String brainPrompt(KnowledgeItem k){String base=empty(k.summary)?(!empty(k.extractedText)?k.extractedText:k.rawText):k.summary;base=clip(base,900);return "I just captured this in Cortex. Understand what it means in context, tell me why it may matter, connect it to anything relevant in my data, and suggest the most useful next actions.\n\n"+base;}
    Bitmap preview(String path){try{File f=new File(path);return SafeImageDecoder.decode(f,1200,1_600_000L);}catch(Throwable e){return null;}}
    boolean isImage(KnowledgeItem k){return"SCREENSHOT".equals(k.type)||"IMAGE".equals(k.type);}String friendlyType(String t){if("AUDIO".equals(t))return"Voice";if("FILE".equals(t))return"File";if("SCREENSHOT".equals(t)||"IMAGE".equals(t))return"Image";return"Text";}String friendlyState(String s){if("analyzed".equals(s))return"analysis complete";if("analyzing".equals(s))return"analyzing";if("failed_retryable".equals(s))return"retry available";return s.isEmpty()?"captured":s.replace('_',' ');}String clip(String s,int n){String x=n(s);return x.length()<=n?x:x.substring(0,n)+"…";}boolean empty(String s){return s==null||s.trim().isEmpty();}String n(String s){return s==null?"":s.trim();}
}
