package com.kareem.cortex;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.io.File;
import java.util.Locale;

/** Fast capture sheet: Voice, Text, File or Photo. Configuration lives in Settings. */
public class CaptureActivity extends Activity {
    static final int REQ_MIC=771,REQ_FILE=772,REQ_PHOTO=773;
    VaultDb db;AudioCapture recorder=new AudioCapture();long recordingStarted;Handler handler=new Handler(Looper.getMainLooper());Runnable tick;LinearLayout sheet,recordPanel,choices;TextView timer;
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);build();handleIncoming(getIntent());handler.postDelayed(()->handleMode(getIntent()),120);}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);handleIncoming(i);handler.postDelayed(()->handleMode(i),120);}
    @Override protected void onDestroy(){super.onDestroy();if(tick!=null)handler.removeCallbacks(tick);if(recorder.isRunning())try{File f=recorder.stop();if(f!=null)f.delete();}catch(Throwable ignored){}}

    void build(){Window w=getWindow();w.setBackgroundDrawableResource(android.R.color.transparent);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);WindowManager.LayoutParams lp=w.getAttributes();lp.dimAmount=.55f;w.setAttributes(lp);
        FrameLayout root=new FrameLayout(this);root.setBackgroundColor(Color.TRANSPARENT);root.setOnClickListener(v->finish());
        sheet=new LinearLayout(this);sheet.setOrientation(LinearLayout.VERTICAL);sheet.setPadding(dp(20),dp(16),dp(20),dp(20));sheet.setBackground(CortexUi.round(this,CortexUi.SURFACE,Color.TRANSPARENT,28));sheet.setOnClickListener(v->{});
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);TextView title=CortexUi.plain(this,"Capture",24,CortexUi.TEXT);CortexUi.medium(title);head.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView close=CortexUi.plain(this,"×",28,CortexUi.MUTED);close.setGravity(Gravity.CENTER);close.setOnClickListener(v->finish());head.addView(close,new LinearLayout.LayoutParams(dp(42),dp(42)));sheet.addView(head);
        choices=new LinearLayout(this);choices.setOrientation(LinearLayout.VERTICAL);choices.setPadding(0,dp(10),0,0);LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);addTile(top,"Voice",this::startVoice,0);addTile(top,"Text",this::quickNote,8);choices.addView(top,new LinearLayout.LayoutParams(-1,dp(92)));LinearLayout bottom=new LinearLayout(this);bottom.setOrientation(LinearLayout.HORIZONTAL);addTile(bottom,"File",this::pickFile,0);addTile(bottom,"Photo",this::pickPhoto,8);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(92));bp.setMargins(0,dp(8),0,0);choices.addView(bottom,bp);sheet.addView(choices);
        FrameLayout.LayoutParams sp=new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM);sp.setMargins(dp(12),0,dp(12),dp(12));root.addView(sheet,sp);setContentView(root);CortexUi.fitSystemBars(this,root);}

    void addTile(LinearLayout row,String label,Runnable action,int left){TextView tile=CortexUi.plain(this,label,16,CortexUi.TEXT);CortexUi.medium(tile);tile.setGravity(Gravity.CENTER);CortexUi.pressable(this,tile,CortexUi.round(this,CortexUi.SURFACE_2,Color.TRANSPARENT,20));tile.setOnClickListener(v->action.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(left),0,0,0);row.addView(tile,p);}

    void handleIncoming(Intent i){if(i==null)return;String a=i.getAction();if(!Intent.ACTION_SEND.equals(a)&&!Intent.ACTION_SEND_MULTIPLE.equals(a))return;int n=new ShareImporter(this,db).importIntent(i);if(n>0){Toast.makeText(this,"Saved to Cortex",Toast.LENGTH_SHORT).show();kick();handler.postDelayed(this::finish,220);}}
    void handleMode(Intent i){if(i==null)return;String a=i.getAction();if(Intent.ACTION_SEND.equals(a)||Intent.ACTION_SEND_MULTIPLE.equals(a))return;String mode=i.getStringExtra("mode");if(mode==null||mode.isEmpty())return;i.removeExtra("mode");if("voice".equals(mode))startVoice();else if("text".equals(mode))quickNote();else if("photo".equals(mode))pickPhoto();else if("file".equals(mode))pickFile();}

    void quickNote(){choices.setVisibility(View.GONE);final EditText e=new EditText(this);e.setHint("Type or paste…");e.setHintTextColor(CortexUi.FAINT);e.setTextColor(CortexUi.TEXT);e.setTextSize(15);e.setGravity(Gravity.TOP);e.setMinLines(6);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,Color.TRANSPARENT,18));sheet.addView(e,new LinearLayout.LayoutParams(-1,-2));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setPadding(0,dp(12),0,0);TextView cancel=CortexUi.action(this,"Cancel",CortexUi.MUTED,false),save=CortexUi.action(this,"Save",CortexUi.ACCENT,true);actions.addView(cancel,new LinearLayout.LayoutParams(0,dp(46),1));LinearLayout.LayoutParams saveParams=new LinearLayout.LayoutParams(0,dp(46),1);saveParams.setMargins(dp(8),0,0,0);actions.addView(save,saveParams);sheet.addView(actions);cancel.setOnClickListener(v->{sheet.removeView(e);sheet.removeView(actions);choices.setVisibility(View.VISIBLE);});save.setOnClickListener(v->{String s=e.getText().toString().trim();if(s.isEmpty()){e.setError("Write something first");return;}String cat=AutoClassifier.category(s,"text/plain");long id=db.insert("TEXT","manual",AutoClassifier.title(s,"text/plain"),s,cat,AutoClassifier.tags(s,cat),"",Fingerprint.text(s),"{}");if(id<0)Toast.makeText(this,"Already in Cortex",Toast.LENGTH_SHORT).show();else{Toast.makeText(this,"Saved",Toast.LENGTH_SHORT).show();kick();finish();}});e.requestFocus();getWindow().setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);}

    void pickFile(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,REQ_FILE);}
    void pickPhoto(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,REQ_PHOTO);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();try{String mime=getContentResolver().getType(uri);long id;if(req==REQ_FILE&&mime!=null&&mime.startsWith("audio/"))id=new ShareImporter(this,db).importAudio(uri,mime);else{id=importUri(uri,mime);}if(id>0){Toast.makeText(this,"Saved to Cortex",Toast.LENGTH_SHORT).show();kick();finish();}else Toast.makeText(this,"Could not import or it already exists",Toast.LENGTH_LONG).show();}catch(Throwable e){Toast.makeText(this,"Import failed",Toast.LENGTH_LONG).show();}}
    long importUri(Uri uri,String mime){Intent share=new Intent(Intent.ACTION_SEND);share.setType(mime==null?"application/octet-stream":mime);share.putExtra(Intent.EXTRA_STREAM,uri);share.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);return new ShareImporter(this,db).importIntent(share)>0?1:0;}

    void startVoice(){if(!GroqKeyStore.has(this)&&!GeminiKeyStore.has(this)){Toast.makeText(this,"Set up voice transcription in Settings first",Toast.LENGTH_LONG).show();finish();startActivity(new Intent(this,SettingsActivity.class));return;}if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}beginVoice();}
    @Override public void onRequestPermissionsResult(int req,String[] p,int[] g){super.onRequestPermissionsResult(req,p,g);if(req==REQ_MIC&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)beginVoice();else if(req==REQ_MIC)Toast.makeText(this,"Microphone permission is required",Toast.LENGTH_LONG).show();}
    void beginVoice(){try{recorder.start(this);recordingStarted=System.currentTimeMillis();showRecordingPanel();}catch(Throwable e){Toast.makeText(this,"Could not start recording",Toast.LENGTH_LONG).show();}}
    void showRecordingPanel(){choices.setVisibility(View.GONE);recordPanel=new LinearLayout(this);recordPanel.setOrientation(LinearLayout.VERTICAL);recordPanel.setPadding(0,dp(12),0,0);timer=CortexUi.plain(this,"00:00",38,CortexUi.TEXT);CortexUi.medium(timer);timer.setGravity(Gravity.CENTER);recordPanel.addView(timer);LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setPadding(0,dp(14),0,0);TextView cancel=CortexUi.action(this,"Discard",CortexUi.MUTED,false),save=CortexUi.action(this,"Stop & save",CortexUi.ACCENT,true);actions.addView(cancel,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams saveParams=new LinearLayout.LayoutParams(0,dp(48),1);saveParams.setMargins(dp(8),0,0,0);actions.addView(save,saveParams);recordPanel.addView(actions);cancel.setOnClickListener(v->finishVoice(false));save.setOnClickListener(v->finishVoice(true));sheet.addView(recordPanel);tick=new Runnable(){public void run(){long sec=(System.currentTimeMillis()-recordingStarted)/1000;if(timer!=null)timer.setText(String.format(Locale.US,"%02d:%02d",sec/60,sec%60));if(recorder.isRunning())handler.postDelayed(this,500);}};handler.post(tick);}
    void finishVoice(boolean save){try{File f=recorder.stop();if(tick!=null)handler.removeCallbacks(tick);if(f==null)return;if(!save){f.delete();finish();return;}JSONObject m=new JSONObject();m.put("mime","audio/wav");m.put("bytes",f.length());m.put("recorded_at",System.currentTimeMillis());long id=db.insert("AUDIO","manual_recording","Voice recording","","Voice & Audio","voice,audio,transcript",f.getAbsolutePath(),Fingerprint.file(f.getAbsolutePath()),m.toString());if(id<0){f.delete();Toast.makeText(this,"Already in Cortex",Toast.LENGTH_SHORT).show();}else{Toast.makeText(this,"Voice saved",Toast.LENGTH_SHORT).show();kick();}finish();}catch(Throwable e){Toast.makeText(this,"Could not save recording",Toast.LENGTH_LONG).show();}}
    void kick(){AnalysisQueue.kick(this,db,()->{});}
}
