package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** User-facing observability. Raw evidence, processing state and validated meaning stay visibly separate. */
public final class CaptureOverviewActivity extends Activity {
    VaultDb db;LinearLayout content;Handler ui=new Handler(Looper.getMainLooper());boolean destroyed=false;int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);try{db=new VaultDb(getApplicationContext());PhoneContextStore.ensure(db);NotificationEventEngine.ensure(db);UniversalEventStore.ensure(db.getWritableDatabase());build();}catch(Throwable t){renderRecovery(t);}}
    @Override protected void onResume(){super.onResume();safeRefresh();ui.removeCallbacks(tick);ui.post(tick);}
    @Override protected void onPause(){ui.removeCallbacks(tick);super.onPause();}
    @Override protected void onDestroy(){destroyed=true;ui.removeCallbacksAndMessages(null);if(db!=null)try{db.close();}catch(Throwable ignored){}db=null;super.onDestroy();}
    final Runnable tick=new Runnable(){@Override public void run(){if(!destroyed&&!isFinishing()){safeRefresh();ui.postDelayed(this,1500);}}};
    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(10),dp(18),dp(24));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"capture",null);setContentView(root);CortexUi.fitSystemBars(this,root);safeRefresh();}
    void safeRefresh(){if(content==null||db==null||destroyed)return;try{refresh();}catch(Throwable t){renderInlineRecovery(t);}}

    void refresh(){if(content==null||db==null||destroyed)return;content.removeAllViews();header();long day=startOfDay();boolean notifications=notificationListenerEnabled(),screen=CortexScreenAccessibilityService.enabled(this),anyLive=notifications||screen;long raw=ue("SELECT COUNT(*) FROM ue_raw_observations WHERE occurred_at>=?",day),streams=ue("SELECT COUNT(*) FROM ue_streams WHERE last_seen_at>=?",day),meaningful=meaningfulCount(day),waiting=ueNoArg("SELECT COUNT(*) FROM ue_semantic_events WHERE semantic_state IN ('waiting','blocked') AND superseded_by=0"),failed=ue("SELECT COUNT(*) FROM ue_pipeline_stages WHERE state='failed' AND started_at>=?",day),apps=ue("SELECT COUNT(DISTINCT source_key) FROM ue_raw_observations WHERE source_type='notification' AND occurred_at>=?",day);
        LinearLayout live=CortexUi.card(this,24);live.setPadding(dp(15),dp(15),dp(15),dp(14));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(CortexUi.glyph(this,"capture",anyLive?CortexUi.GREEN:CortexUi.ORANGE,true),new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(12),0,dp(8),0);top.addView(tx,xp);TextView h=CortexUi.plain(this,"Live Capture",19,CortexUi.TEXT);CortexUi.medium(h);tx.addView(h);TextView sub=CortexUi.text(this,anyLive?"Raw evidence is stored first. Only validated understanding appears as meaningful activity.":"Capture sources need access before Cortex can observe the phone.",11,CortexUi.MUTED);sub.setPadding(0,dp(4),0,0);tx.addView(sub);top.addView(CortexUi.chip(this,anyLive?"● LIVE":"SETUP",anyLive?CortexUi.GREEN:CortexUi.ORANGE,true),new LinearLayout.LayoutParams(-2,dp(32)));live.addView(top);TextView m=CortexUi.plain(this,"Raw "+raw+"   •   Objects "+streams+"   •   Understood "+meaningful+"   •   Apps "+apps,10,CortexUi.MUTED);m.setPadding(0,dp(12),0,0);live.addView(m);TextView p=CortexUi.plain(this,"Processing "+waiting+"   •   Failed "+failed,10,CortexUi.MUTED);p.setPadding(0,dp(5),0,0);live.addView(p);content.addView(live,margins(0,dp(8),0,0));
        content.addView(CortexUi.section(this,"Capture sources"));category("Notifications",notifications?"Live · raw observations retained":"Access needed · notification listener is off","phone",notifications?CortexUi.GREEN:CortexUi.ORANGE,ue("SELECT COUNT(*) FROM ue_raw_observations WHERE source_type='notification' AND occurred_at>=?",day),this::showNotifications);category("Screen",screen?"Live · accessibility source enabled":"Access needed · screen understanding is off","open",screen?CortexUi.GREEN:CortexUi.ORANGE,countScreen(day),()->showPhone("Screen",new String[]{"app_transition","window_context","interaction"}));category("Voice","Raw recordings and transcription evidence","voice",CortexUi.RED,countKnowledge(day,new String[]{"AUDIO"}),()->showKnowledge("Voice",new String[]{"AUDIO"}));category("Images","Photos and screenshots as captured evidence","photo",CortexUi.GREEN,countKnowledge(day,new String[]{"IMAGE","SCREENSHOT"}),()->showKnowledge("Images",new String[]{"IMAGE","SCREENSHOT"}));category("Files","Imported documents and attachments","file",CortexUi.ORANGE,countKnowledge(day,new String[]{"FILE","DOCUMENT","PDF","TEXT","TABLE"}),()->showKnowledge("Files",new String[]{"FILE","DOCUMENT","PDF","TEXT","TABLE"}));category("Calls & SMS","Direct provider capture not enabled; notification hints are not counted","phone",CortexUi.YELLOW,0,()->showText("Calls & SMS","No direct Call Log / SMS provider capture is enabled yet. Conversation notifications stay under Notifications and are never presented as direct SMS/call data."));
        if(waiting>0){content.addView(CortexUi.section(this,"Processing now"));renderProcessingFeed();}content.addView(CortexUi.section(this,"Meaningful live activity"));renderSemanticFeed();
    }
    void renderRecovery(Throwable t){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER);root.setPadding(dp(24),dp(24),dp(24),dp(24));root.setBackgroundColor(CortexUi.BG);TextView h=CortexUi.plain(this,"Capture is recovering",22,CortexUi.TEXT);CortexUi.medium(h);root.addView(h);TextView b=CortexUi.text(this,"Cortex protected the app from a Capture data-view failure. Your captured evidence has not been deleted.",12,CortexUi.MUTED);b.setPadding(0,dp(10),0,0);root.addView(b);setContentView(root);auditFailure("capture_overview_open_failure",t);}
    void renderInlineRecovery(Throwable t){if(content==null)return;content.removeAllViews();header();TextView b=CortexUi.text(this,"Capture data is temporarily unavailable. Cortex kept the app open and preserved the underlying evidence.",12,CortexUi.MUTED);b.setPadding(0,dp(16),0,dp(16));content.addView(b);auditFailure("capture_overview_refresh_failure",t);}
    void auditFailure(String event,Throwable t){if(db==null)return;try{CortexAuditStore.Run r=CortexAuditStore.latest(db);if(r!=null)CortexAuditStore.log(db,r.id,"error","capture",event,String.valueOf(t),null);}catch(Throwable ignored){}}
    void header(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(2),dp(8),dp(2),dp(8));LinearLayout t=new LinearLayout(this);t.setOrientation(LinearLayout.VERTICAL);row.addView(t,new LinearLayout.LayoutParams(0,-2,1));TextView h=CortexUi.plain(this,"Capture",30,CortexUi.TEXT);CortexUi.medium(h);t.addView(h);TextView s=CortexUi.text(this,"Proof of what Cortex saw, what is processing, and what it actually understood.",11,CortexUi.MUTED);s.setPadding(0,dp(3),0,0);t.addView(s);TextView settings=CortexUi.chip(this,"Settings",CortexUi.MUTED,false);settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));row.addView(settings,new LinearLayout.LayoutParams(-2,dp(36)));content.addView(row);}
    void category(String title,String status,String icon,int color,long count,Runnable open){LinearLayout card=CortexUi.card(this,18);card.setPadding(dp(12),dp(11),dp(11),dp(11));card.setOrientation(LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.addView(CortexUi.glyph(this,icon,color,true),new LinearLayout.LayoutParams(dp(46),dp(46)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(dp(11),0,dp(8),0);card.addView(tx,tp);TextView h=CortexUi.plain(this,title,15,CortexUi.TEXT);CortexUi.medium(h);tx.addView(h);TextView s=CortexUi.text(this,status,10,CortexUi.MUTED);s.setPadding(0,dp(4),0,0);tx.addView(s);card.addView(CortexUi.chip(this,String.valueOf(count),color,true),new LinearLayout.LayoutParams(-2,dp(32)));CortexUi.pressable(this,card,CortexUi.velvet(this,18));card.setOnClickListener(v->open.run());content.addView(card,margins(0,0,0,dp(8)));}
    long meaningfulCount(long day){Cursor c=null;long n=0;try{c=db.getReadableDatabase().rawQuery("SELECT semantic_type,semantic_state,confidence,subject,summary FROM ue_semantic_events WHERE occurred_at>=? AND meaningful=1 AND superseded_by=0",new String[]{String.valueOf(day)});while(c.moveToNext())if(UniversalProjectionPolicy.userFacingSemantic(c.getString(0),c.getString(1),c.getDouble(2),c.getString(3),c.getString(4)))n++;}finally{if(c!=null)c.close();}return n;}
    void renderProcessingFeed(){Cursor c=null;int n=0;try{c=db.getReadableDatabase().rawQuery("SELECT e.occurred_at,r.source_key,r.title,r.body,e.semantic_state FROM ue_semantic_events e JOIN ue_raw_observations r ON r.id=e.raw_observation_id WHERE e.semantic_state IN ('waiting','blocked') AND e.superseded_by=0 ORDER BY e.occurred_at DESC LIMIT 8",null);while(c.moveToNext()){n++;String title=safe(c.getString(2));if(title.isEmpty())title=safe(c.getString(1));addFeedRow(title,safe(c.getString(3)),clock(c.getLong(0))+"  •  "+("blocked".equals(c.getString(4))?"Waiting for local model":"Understanding…"));}}finally{if(c!=null)c.close();}if(n==0)addEmpty("Nothing is waiting for semantic understanding.");}
    void renderSemanticFeed(){Cursor c=null;int n=0;HashSet<String> seen=new HashSet<>();try{c=db.getReadableDatabase().rawQuery("SELECT e.occurred_at,e.semantic_type,e.subject,e.summary,e.semantic_state,e.confidence,s.source_key FROM ue_semantic_events e JOIN ue_streams s ON s.id=e.stream_id WHERE e.meaningful=1 AND e.superseded_by=0 AND e.semantic_state='complete' AND e.confidence>=0.70 ORDER BY e.occurred_at DESC LIMIT 80",null);while(c.moveToNext()){String type=c.getString(1),subject=c.getString(2),summary=c.getString(3),state=c.getString(4);double conf=c.getDouble(5);if(!UniversalProjectionPolicy.userFacingSemantic(type,state,conf,subject,summary))continue;String title=CanonicalPresentation.cleanTitle(c.getString(6),type,subject,subject);String key=LocalSemanticEmbedder.norm(type+"|"+title+"|"+summary);if(!seen.add(key))continue;addFeedRow(title,safe(summary),clock(c.getLong(0))+"  •  "+friendlyType(type)+"  •  understood "+Math.round(conf*100)+"%");n++;if(n>=20)break;}}finally{if(c!=null)c.close();}if(n==0)addEmpty("No validated meaningful events yet. Raw observations remain safely stored while Cortex processes them.");}
    void addFeedRow(String title,String body,String meta){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(3),dp(10),dp(3),dp(10));TextView h=CortexUi.text(this,title,12,CortexUi.TEXT);CortexUi.medium(h);h.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);row.addView(h);if(!body.isEmpty()&&!body.equals(title)){TextView b=CortexUi.text(this,body,11,CortexUi.MUTED);b.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);b.setPadding(0,dp(4),0,0);b.setMaxLines(3);row.addView(b);}TextView m=CortexUi.plain(this,meta,9,CortexUi.MUTED);m.setPadding(0,dp(4),0,0);row.addView(m);content.addView(row);content.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}
    void addEmpty(String text){TextView e=CortexUi.text(this,text,12,CortexUi.MUTED);e.setPadding(dp(2),dp(5),0,dp(12));content.addView(e);}
    String friendlyType(String x){String s=safe(x).replace('_',' ');return s.isEmpty()?"event":s;}
    void showNotifications(){StringBuilder b=new StringBuilder();Cursor c=null;try{c=db.getReadableDatabase().rawQuery("SELECT r.id,r.occurred_at,r.source_key,r.event_type,r.platform_hint,r.technical_type,r.title,r.body,COALESCE((SELECT semantic_type FROM ue_semantic_events e WHERE e.raw_observation_id=r.id AND e.superseded_by=0 ORDER BY e.id DESC LIMIT 1),''),COALESCE((SELECT semantic_state FROM ue_semantic_events e WHERE e.raw_observation_id=r.id AND e.superseded_by=0 ORDER BY e.id DESC LIMIT 1),'coalesced') FROM ue_raw_observations r WHERE r.source_type='notification' ORDER BY r.occurred_at DESC LIMIT 120",null);while(c.moveToNext()){b.append(clock(c.getLong(1))).append("  •  ").append(c.getString(2)).append("\n");if(!safe(c.getString(6)).isEmpty())b.append("Title: ").append(c.getString(6)).append("\n");if(!safe(c.getString(7)).isEmpty())b.append("Text: ").append(c.getString(7)).append("\n");b.append("Platform hint: ").append(c.getString(4)).append("  •  Technical: ").append(c.getString(5)).append("\nSemantic: ").append(c.getString(8)).append("  •  State: ").append(c.getString(9)).append("\nRaw ID: ").append(c.getLong(0)).append("\n\n");if(b.length()>18000)break;}}finally{if(c!=null)c.close();}showText("Notification Capture",b.length()==0?"No notification observations yet.":b.toString());}
    void showPhone(String title,String[] kinds){ArrayList<PhoneContextStore.Event> all=PhoneContextStore.recent(db,0,200);StringBuilder b=new StringBuilder();for(PhoneContextStore.Event e:all){if(!contains(kinds,e.kind))continue;b.append(clock(e.occurredAt)).append("  •  ").append(e.human()).append("\n\n");if(b.length()>16000)break;}showText(title,b.length()==0?"No matching captures yet.":b.toString());}
    void showKnowledge(String title,String[] types){StringBuilder b=new StringBuilder();for(KnowledgeItem k:db.captureSearch("",250)){if(!contains(types,k.type))continue;b.append(clock(k.createdAt)).append("  •  ").append(CanonicalPresentation.cleanTitle(k.type,k.type,k.title,k.title)).append("\nState: ").append(k.status).append("\n\n");if(b.length()>16000)break;}showText(title,b.length()==0?"No matching captures yet.":b.toString());}
    void showText(String title,String text){TextView t=CortexUi.text(this,text,12,CortexUi.TEXT);t.setTextIsSelectable(true);t.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);t.setPadding(dp(8),dp(4),dp(8),dp(4));ScrollView s=new ScrollView(this);s.addView(t);new AlertDialog.Builder(this).setTitle(title).setView(s).setPositiveButton("Close",null).show();}
    boolean notificationListenerEnabled(){try{String enabled=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");if(enabled==null)return false;ComponentName c=new ComponentName(this,NotificationCaptureService.class);return enabled.contains(c.flattenToString())||enabled.contains(c.flattenToShortString());}catch(Throwable ignored){return false;}}
    long ue(String sql,long since){Cursor c=null;try{c=db.getReadableDatabase().rawQuery(sql,new String[]{String.valueOf(since)});return c.moveToFirst()?c.getLong(0):0;}finally{if(c!=null)c.close();}}long ueNoArg(String sql){Cursor c=null;try{c=db.getReadableDatabase().rawQuery(sql,null);return c.moveToFirst()?c.getLong(0):0;}finally{if(c!=null)c.close();}}
    long countScreen(long since){return scalar("SELECT COUNT(*) FROM phone_context_events WHERE occurred_at>=? AND kind IN ('app_transition','window_context','interaction')",new String[]{String.valueOf(since)});}long countKnowledge(long since,String[] types){StringBuilder q=new StringBuilder("SELECT COUNT(*) FROM knowledge_items WHERE created_at>=? AND UPPER(type) IN (");String[] args=new String[types.length+1];args[0]=String.valueOf(since);for(int i=0;i<types.length;i++){if(i>0)q.append(',');q.append('?');args[i+1]=types[i].toUpperCase(Locale.ROOT);}q.append(')');return scalar(q.toString(),args);}long scalar(String sql,String[] args){Cursor c=null;try{c=db.getReadableDatabase().rawQuery(sql,args);return c.moveToFirst()?c.getLong(0):0;}finally{if(c!=null)c.close();}}
    long startOfDay(){Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}boolean contains(String[] xs,String x){if(xs==null||x==null)return false;for(String s:xs)if(s.equalsIgnoreCase(x))return true;return false;}String clock(long ms){return new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(ms));}String safe(String s){return s==null?"":s.trim();}LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
}
