package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.drawable.ColorDrawable;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** Pure observability read model: Evidence -> Understood -> Judged -> Shown. No attention decisions occur here. */
public final class CaptureOverviewActivity extends Activity {
    VaultDb db;LinearLayout content;Handler ui=new Handler(Looper.getMainLooper());boolean destroyed=false;long lastSignature=Long.MIN_VALUE;int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);try{db=new VaultDb(getApplicationContext());build();}catch(Throwable t){renderRecovery(t);}}
    @Override protected void onResume(){super.onResume();AnalysisQueue.kick(getApplicationContext(),null,this::safeRefresh);safeRefresh();ui.removeCallbacks(tick);ui.postDelayed(tick,2500);}
    @Override protected void onPause(){ui.removeCallbacks(tick);super.onPause();}
    @Override protected void onDestroy(){destroyed=true;ui.removeCallbacksAndMessages(null);if(db!=null)try{db.close();}catch(Throwable ignored){}db=null;super.onDestroy();}
    final Runnable tick=new Runnable(){@Override public void run(){if(destroyed||isFinishing())return;try{AnalysisQueue.kick(getApplicationContext(),null,CaptureOverviewActivity.this::safeRefresh);long sig=readSignature();if(sig!=lastSignature)safeRefresh();}catch(Throwable ignored){}ui.postDelayed(this,2500);}};

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setVerticalScrollBarEnabled(false);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(18),dp(8),dp(18),dp(26));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"capture",null);setContentView(root);CortexUi.fitSystemBars(this,root);safeRefresh();}
    void safeRefresh(){if(content==null||db==null||destroyed)return;try{refresh();lastSignature=readSignature();}catch(Throwable t){renderInlineRecovery(t);}}

    void refresh(){
        content.removeAllViews();header();long day=startOfDay();boolean notifications=notificationListenerEnabled(),screen=CortexScreenAccessibilityService.enabled(this),anyLive=notifications||screen;
        long observed=table("ue_raw_observations")?scalar("SELECT COUNT(*) FROM ue_raw_observations WHERE occurred_at>=?",new String[]{String.valueOf(day)}):0;
        long objects=table("ue_source_instances")?scalar("SELECT COUNT(*) FROM ue_source_instances WHERE last_seen_at>=?",new String[]{String.valueOf(day)}):(table("ue_streams")?scalar("SELECT COUNT(*) FROM ue_streams WHERE last_seen_at>=?",new String[]{String.valueOf(day)}):0);
        long understood=table("ue_semantic_events")?scalar("SELECT COUNT(*) FROM ue_semantic_events WHERE occurred_at>=? AND semantic_state='complete' AND superseded_by=0 AND confidence>=0.70 AND semantic_type NOT IN ('technical_state','notification_event','CortexEvent')",new String[]{String.valueOf(day)}):0;
        long judged=table("ue_judgment_trace")?scalar("SELECT COUNT(*) FROM ue_judgment_trace WHERE created_at>=?",new String[]{String.valueOf(day)}):0;
        long shown=table("ue_attention_items")?scalar("SELECT COUNT(*) FROM ue_attention_items WHERE created_at>=?",new String[]{String.valueOf(day)}):0;
        long promoted=table("ue_projection_decisions")?scalar("SELECT COUNT(DISTINCT semantic_event_id) FROM ue_projection_decisions WHERE eligible=1 AND projection IN ('NOW','BRIEF','BRAIN') AND created_at>=?",new String[]{String.valueOf(day)}):0;
        long waiting=table("ue_semantic_events")?scalar("SELECT COUNT(*) FROM ue_semantic_events WHERE semantic_state IN ('waiting','blocked') AND superseded_by=0",null):0;
        long failed=table("ue_pipeline_stages")?scalar("SELECT COUNT(*) FROM ue_pipeline_stages WHERE state='failed' AND started_at>=?",new String[]{String.valueOf(day)}):0;
        long apps=table("ue_raw_observations")?scalar("SELECT COUNT(DISTINCT source_key) FROM ue_raw_observations WHERE source_type='notification' AND occurred_at>=?",new String[]{String.valueOf(day)}):0;

        LinearLayout live=CortexUi.card(this,CortexUi.R_HERO);live.setPadding(dp(16),dp(16),dp(16),dp(15));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(CortexUi.glyph(this,"capture",anyLive?CortexUi.GREEN:CortexUi.ORANGE,true),new LinearLayout.LayoutParams(dp(52),dp(52)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(12),0,dp(8),0);top.addView(tx,xp);TextView h=CortexUi.plain(this,"Live pipeline",19,CortexUi.TEXT);CortexUi.medium(h);tx.addView(h);TextView sub=CortexUi.text(this,anyLive?"Evidence stays raw first. Each later stage remains separately inspectable.":"Capture sources need access before Cortex can observe the phone.",11,CortexUi.MUTED);sub.setPadding(0,dp(4),0,0);tx.addView(sub);TextView livePill=CortexUi.chip(this,anyLive?"● LIVE":"SETUP",anyLive?CortexUi.GREEN:CortexUi.ORANGE,true);top.addView(livePill,new LinearLayout.LayoutParams(-2,dp(32)));if(anyLive)CortexMotion.breathe(livePill);live.addView(top);TextView compact=CortexUi.plain(this,waiting>0?waiting+" items still processing · "+failed+" failed today":"Caught up · "+failed+" failed today",10,waiting>0?CortexUi.YELLOW:CortexUi.MUTED);compact.setPadding(0,dp(12),0,0);live.addView(compact);content.addView(live,margins(0,dp(6),0,0));CortexMotion.hero(live);

        content.addView(CortexUi.section(this,"Source → understood → judged → shown"));LinearLayout flow=new LinearLayout(this);flow.setOrientation(LinearLayout.HORIZONTAL);flow.addView(stage("Source",observed,CortexUi.ORANGE),new LinearLayout.LayoutParams(0,dp(72),1));LinearLayout.LayoutParams f1=new LinearLayout.LayoutParams(0,dp(72),1);f1.setMargins(dp(6),0,0,0);flow.addView(stage("Understood",understood,CortexUi.GREEN),f1);LinearLayout.LayoutParams f2=new LinearLayout.LayoutParams(0,dp(72),1);f2.setMargins(dp(6),0,0,0);flow.addView(stage("Judged",judged,CortexUi.YELLOW),f2);LinearLayout.LayoutParams f3=new LinearLayout.LayoutParams(0,dp(72),1);f3.setMargins(dp(6),0,0,0);flow.addView(stage("Shown",shown,CortexUi.LIME),f3);content.addView(flow);CortexMotion.enter(flow,1);
        TextView boundary=CortexUi.plain(this,"Promotion today: "+promoted+" · sources/apps: "+apps+" · observed objects: "+objects,9,CortexUi.FAINT);boundary.setPadding(dp(2),dp(7),0,0);content.addView(boundary);

        content.addView(CortexUi.section(this,"Capture sources"));category("Notifications",notifications?"Live · immutable observations retained":"Access needed · notification listener is off","phone",notifications?CortexUi.GREEN:CortexUi.ORANGE,table("ue_raw_observations")?scalar("SELECT COUNT(*) FROM ue_raw_observations WHERE source_type='notification' AND occurred_at>=?",new String[]{String.valueOf(day)}):0,this::showNotifications);category("Screen",screen?"Live · accessibility evidence enabled":"Access needed · screen understanding is off","open",screen?CortexUi.GREEN:CortexUi.ORANGE,countScreen(day),()->showPhone("Screen evidence",new String[]{"app_transition","window_context","interaction"}));category("Voice","Recordings and transcription evidence","voice",CortexUi.ORANGE,countKnowledge(day,new String[]{"AUDIO"}),()->startActivity(new Intent(this,VoiceLibraryActivity.class)));category("Visual Memory","Screenshots, OCR and semantic retrieval","photo",CortexUi.GREEN,countKnowledge(day,new String[]{"IMAGE","SCREENSHOT"}),()->{try{startActivity(new Intent(this,VisualMemoryActivity.class));}catch(Throwable ignored){}});category("Files","Imported documents and attachments","file",CortexUi.OLIVE,countKnowledge(day,new String[]{"FILE","DOCUMENT","PDF","TEXT","TABLE"}),()->showKnowledge("Files",new String[]{"FILE","DOCUMENT","PDF","TEXT","TABLE"}));
        if(waiting>0){content.addView(CortexUi.section(this,"Processing"));renderProcessingFeed();}content.addView(CortexUi.section(this,"Understood"));renderUnderstoodFeed();content.addView(CortexUi.section(this,"Promoted elsewhere"));renderPromotedFeed();
    }

    LinearLayout stage(String label,long value,int color){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setGravity(Gravity.CENTER_VERTICAL);box.setPadding(dp(9),dp(9),dp(9),dp(8));box.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER_SOFT,16));TextView n=CortexUi.plain(this,"0",17,color);CortexUi.medium(n);box.addView(n);TextView l=CortexUi.plain(this,label,8,CortexUi.MUTED);l.setMaxLines(1);l.setPadding(0,dp(4),0,0);box.addView(l);CortexMotion.count(n,0,value,"");return box;}

    void renderProcessingFeed(){if(!table("ue_semantic_events")||!table("ue_raw_observations")){addEmpty("No processing ledger yet.");return;}Cursor c=null;int n=0;try{c=db.getReadableDatabase().rawQuery("SELECT e.occurred_at,r.source_key,r.title,r.body,e.semantic_state FROM ue_semantic_events e JOIN ue_raw_observations r ON r.id=e.raw_observation_id WHERE e.semantic_state IN ('waiting','blocked') AND e.superseded_by=0 ORDER BY e.occurred_at DESC LIMIT 8",null);while(c.moveToNext()){n++;String title=safe(c.getString(2));if(title.isEmpty())title=safe(c.getString(1));addFeedRow(title,safe(c.getString(3)),clock(c.getLong(0)),"blocked".equals(c.getString(4))?"Waiting":"Understanding",CortexUi.YELLOW);}}finally{if(c!=null)c.close();}if(n==0)addEmpty("Nothing is waiting for semantic understanding.");}
    void renderUnderstoodFeed(){if(!table("ue_semantic_events")||!table("ue_raw_observations")){addEmpty("No semantic ledger yet.");return;}Cursor c=null;int n=0;HashSet<String> seen=new HashSet<>();try{c=db.getReadableDatabase().rawQuery("SELECT e.id,e.occurred_at,e.semantic_type,e.subject,e.summary,e.confidence,r.source_key FROM ue_semantic_events e JOIN ue_raw_observations r ON r.id=e.raw_observation_id WHERE e.superseded_by=0 AND e.semantic_state='complete' AND e.confidence>=0.70 AND e.semantic_type NOT IN ('technical_state','notification_event','CortexEvent') ORDER BY e.occurred_at DESC LIMIT 100",null);while(c.moveToNext()){String type=safe(c.getString(2)),subject=safe(c.getString(3)),summary=safe(c.getString(4)),title=CanonicalPresentation.cleanTitle(c.getString(6),type,subject,subject);String key=type+"|"+LocalSemanticEmbedder.norm(title+" "+summary);if(!seen.add(key))continue;double conf=c.getDouble(5);String meta=clock(c.getLong(1))+(conf<.78?" · "+Math.round(conf*100)+"% confidence":"");int accent="conversation_message".equals(type)?CortexUi.LIME:("captured_artifact".equals(type)?CortexUi.OLIVE:CortexUi.GREEN);addFeedRow(title,summary,meta,friendlyType(type),accent);if(++n>=20)break;}}finally{if(c!=null)c.close();}if(n==0)addEmpty("No validated understanding yet. Raw evidence remains stored.");}
    void renderPromotedFeed(){if(!table("ue_projection_decisions")||!table("ue_semantic_events")){addEmpty("Nothing has been promoted to Now, Brief or Brain yet.");return;}Cursor c=null;int n=0;try{String sql="SELECT e.occurred_at,e.semantic_type,e.subject,e.summary,e.confidence,GROUP_CONCAT(p.projection, ', ') FROM ue_projection_decisions p JOIN ue_semantic_events e ON e.id=p.semantic_event_id WHERE p.eligible=1 AND p.projection IN ('NOW','BRIEF','BRAIN') AND p.policy_version=? AND e.superseded_by=0 GROUP BY e.id ORDER BY e.occurred_at DESC LIMIT 20";c=db.getReadableDatabase().rawQuery(sql,new String[]{StatefulMeaningPolicy.VERSION});while(c.moveToNext()){String type=safe(c.getString(1)),subject=safe(c.getString(2)),summary=safe(c.getString(3)),where=safe(c.getString(5));addFeedRow(CanonicalPresentation.cleanTitle("projection",type,subject,subject),summary,clock(c.getLong(0)),"Promoted · "+where,CortexUi.LIME);n++;}}finally{if(c!=null)c.close();}if(n==0)addEmpty("Nothing has been promoted to Now, Brief or Brain yet.");}

    void renderRecovery(Throwable t){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setGravity(Gravity.CENTER);root.setPadding(dp(24),dp(24),dp(24),dp(24));root.setBackgroundColor(CortexUi.BG);TextView h=CortexUi.plain(this,"Capture is recovering",22,CortexUi.TEXT);CortexUi.medium(h);root.addView(h);TextView b=CortexUi.text(this,"Cortex protected the app from a Capture read-model failure. Captured evidence was not deleted.",12,CortexUi.MUTED);b.setPadding(0,dp(10),0,0);root.addView(b);setContentView(root);android.util.Log.e("CortexCapture","Capture open failed",t);}
    void renderInlineRecovery(Throwable t){if(content==null)return;content.removeAllViews();header();TextView b=CortexUi.text(this,"Capture data is temporarily unavailable. Cortex kept the app open and preserved the underlying evidence.",12,CortexUi.MUTED);b.setPadding(0,dp(16),0,dp(16));content.addView(b);android.util.Log.e("CortexCapture","Capture refresh failed",t);}
    void header(){content.addView(CortexUi.header(this,"CORTEX · LIVE PIPELINE","Pipeline",CortexUi.ORANGE,"Settings",v->startActivity(new Intent(this,SettingsActivity.class))));TextView s=CortexUi.text(this,"Inspect what Cortex observed, what is still processing, what it understood, and what was actually shown.",11,CortexUi.MUTED);s.setPadding(dp(1),0,dp(1),dp(8));content.addView(s);}
    void category(String title,String status,String icon,int color,long count,Runnable open){LinearLayout card=new LinearLayout(this);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(12),dp(11),dp(11),dp(11));CortexUi.pressable(this,card,CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER_SOFT,18));card.addView(CortexUi.glyph(this,icon,color,true),new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(dp(11),0,dp(8),0);card.addView(tx,tp);TextView h=CortexUi.plain(this,title,14,CortexUi.TEXT);CortexUi.medium(h);tx.addView(h);TextView s=CortexUi.text(this,status,10,CortexUi.MUTED);s.setPadding(0,dp(4),0,0);tx.addView(s);card.addView(CortexUi.chip(this,String.valueOf(count),color,true),new LinearLayout.LayoutParams(-2,dp(30)));card.setOnClickListener(v->open.run());content.addView(card,margins(0,0,0,dp(8)));}
    void addFeedRow(String title,String body,String meta,String kind,int accent){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(3),dp(11),dp(3),dp(11));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView h=CortexUi.text(this,title,12,CortexUi.TEXT);CortexUi.medium(h);h.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);h.setMaxLines(2);top.addView(h,new LinearLayout.LayoutParams(0,-2,1));top.addView(CortexUi.chip(this,kind,accent,false),new LinearLayout.LayoutParams(-2,dp(26)));row.addView(top);if(!safe(body).isEmpty()&&!safe(body).equals(safe(title))){TextView b=CortexUi.text(this,body,11,CortexUi.MUTED);b.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);b.setPadding(0,dp(5),0,0);b.setMaxLines(3);row.addView(b);}TextView m=CortexUi.plain(this,meta,9,CortexUi.FAINT);m.setPadding(0,dp(5),0,0);row.addView(m);content.addView(row);content.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}
    void addEmpty(String text){TextView e=CortexUi.text(this,text,12,CortexUi.MUTED);e.setPadding(dp(2),dp(5),0,dp(12));content.addView(e);}String friendlyType(String x){String s=safe(x).replace('_',' ');if("conversation message".equals(s))return"Conversation";if("captured artifact".equals(s))return"Evidence";return s.isEmpty()?"Event":s.substring(0,1).toUpperCase()+s.substring(1);}

    void showNotifications(){if(!table("ue_raw_observations")){showText("Notification capture","No notification ledger yet.");return;}Dialog d=inspector("Notification capture","Latest immutable notification evidence");LinearLayout holder=(LinearLayout)d.getWindow().getDecorView().findViewWithTag("inspector_content");Cursor c=null;int n=0;try{c=db.getReadableDatabase().rawQuery("SELECT r.id,r.occurred_at,r.source_key,r.platform_hint,r.technical_type,r.title,r.body,COALESCE((SELECT semantic_type FROM ue_semantic_events e WHERE e.raw_observation_id=r.id AND e.superseded_by=0 ORDER BY e.id DESC LIMIT 1),''),COALESCE((SELECT semantic_state FROM ue_semantic_events e WHERE e.raw_observation_id=r.id AND e.superseded_by=0 ORDER BY e.id DESC LIMIT 1),'coalesced') FROM ue_raw_observations r WHERE r.source_type='notification' ORDER BY r.occurred_at DESC LIMIT 36",null);while(c.moveToNext()){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(dp(13),dp(12),dp(13),dp(11));card.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER_SOFT,18));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(CortexUi.eyebrow(this,clock(c.getLong(1))+" · "+safe(c.getString(2)),CortexUi.ORANGE),new LinearLayout.LayoutParams(0,-2,1));String state=safe(c.getString(8));top.addView(CortexUi.chip(this,state.isEmpty()?"raw":state,"complete".equals(state)?CortexUi.GREEN:CortexUi.MUTED,false),new LinearLayout.LayoutParams(-2,dp(26)));card.addView(top);String title=safe(c.getString(5));if(title.isEmpty())title="Notification event";TextView h=CortexUi.text(this,title,13,CortexUi.TEXT);CortexUi.medium(h);h.setPadding(0,dp(7),0,0);card.addView(h);String body=safe(c.getString(6));if(!body.isEmpty()){TextView b=CortexUi.text(this,body,11,CortexUi.MUTED);b.setPadding(0,dp(4),0,0);b.setMaxLines(4);card.addView(b);}String sem=safe(c.getString(7));String tech=safe(c.getString(4));TextView details=CortexUi.plain(this,(sem.isEmpty()?"No semantic projection":sem)+" · "+(tech.isEmpty()?"generic":tech)+" · raw #"+c.getLong(0),9,CortexUi.FAINT);details.setPadding(0,dp(8),0,0);card.addView(details);holder.addView(card,margins(0,0,0,dp(8)));CortexMotion.enter(card,Math.min(n++,5));}}finally{if(c!=null)c.close();}if(n==0)holder.addView(CortexUi.text(this,"No notification observations yet.",12,CortexUi.MUTED));d.show();sizeInspector(d);}
    void showPhone(String title,String[] kinds){ArrayList<PhoneContextStore.Event> all=PhoneContextStore.recent(db,0,200);StringBuilder b=new StringBuilder();for(PhoneContextStore.Event e:all){if(!contains(kinds,e.kind))continue;b.append(clock(e.occurredAt)).append("  •  ").append(e.human()).append("\n\n");if(b.length()>12000)break;}showText(title,b.length()==0?"No matching captures yet.":b.toString());}
    void showKnowledge(String title,String[] types){StringBuilder b=new StringBuilder();for(KnowledgeItem k:db.captureSearch("",250)){if(!contains(types,k.type))continue;b.append(clock(k.createdAt)).append("  •  ").append(CanonicalPresentation.cleanTitle(k.type,k.type,k.title,k.title)).append("\nState: ").append(k.status).append("\n\n");if(b.length()>12000)break;}showText(title,b.length()==0?"No matching captures yet.":b.toString());}
    void showText(String title,String text){Dialog d=inspector(title,"Evidence details");LinearLayout holder=(LinearLayout)d.getWindow().getDecorView().findViewWithTag("inspector_content");TextView t=CortexUi.text(this,text,11,CortexUi.TEXT);t.setTextIsSelectable(true);t.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);holder.addView(t);d.show();sizeInspector(d);}
    Dialog inspector(String title,String subtitle){Dialog d=new Dialog(this);d.requestWindowFeature(Window.FEATURE_NO_TITLE);LinearLayout shell=new LinearLayout(this);shell.setOrientation(LinearLayout.VERTICAL);shell.setPadding(dp(18),dp(15),dp(18),dp(16));shell.setBackground(CortexUi.round(this,CortexUi.SURFACE,Color.argb(90,220,230,210),28));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);head.addView(tx,new LinearLayout.LayoutParams(0,-2,1));tx.addView(CortexUi.eyebrow(this,"CORTEX · INSPECTOR",CortexUi.ORANGE));TextView h=CortexUi.plain(this,title,21,CortexUi.TEXT);CortexUi.medium(h);h.setPadding(0,dp(3),0,0);tx.addView(h);TextView close=CortexUi.chip(this,"Close",CortexUi.MUTED,false);close.setOnClickListener(v->d.dismiss());head.addView(close,new LinearLayout.LayoutParams(-2,dp(34)));shell.addView(head);TextView s=CortexUi.text(this,subtitle,10,CortexUi.MUTED);s.setPadding(0,dp(5),0,dp(12));shell.addView(s);ScrollView scroll=new ScrollView(this);LinearLayout holder=new LinearLayout(this);holder.setTag("inspector_content");holder.setOrientation(LinearLayout.VERTICAL);scroll.addView(holder);shell.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));d.setContentView(shell);Window w=d.getWindow();if(w!=null){w.setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));w.setGravity(Gravity.BOTTOM);w.addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);WindowManager.LayoutParams p=w.getAttributes();p.dimAmount=.68f;w.setAttributes(p);}return d;}
    void sizeInspector(Dialog d){Window w=d.getWindow();if(w!=null){int h=(int)(getResources().getDisplayMetrics().heightPixels*.86f);w.setLayout(WindowManager.LayoutParams.MATCH_PARENT,h);}}

    boolean notificationListenerEnabled(){try{String enabled=Settings.Secure.getString(getContentResolver(),"enabled_notification_listeners");if(enabled==null)return false;ComponentName c=new ComponentName(this,NotificationCaptureService.class);return enabled.contains(c.flattenToString())||enabled.contains(c.flattenToShortString());}catch(Throwable ignored){return false;}}
    long countScreen(long since){if(!table("phone_context_events"))return 0;return scalar("SELECT COUNT(*) FROM phone_context_events WHERE occurred_at>=? AND kind IN ('app_transition','window_context','interaction')",new String[]{String.valueOf(since)});}long countKnowledge(long since,String[] types){if(!table("knowledge_items"))return 0;StringBuilder q=new StringBuilder("SELECT COUNT(*) FROM knowledge_items WHERE created_at>=? AND UPPER(type) IN (");String[] args=new String[types.length+1];args[0]=String.valueOf(since);for(int i=0;i<types.length;i++){if(i>0)q.append(',');q.append('?');args[i+1]=types[i].toUpperCase(Locale.ROOT);}q.append(')');return scalar(q.toString(),args);}long readSignature(){long raw=table("ue_raw_observations")?scalar("SELECT COALESCE(MAX(id),0) FROM ue_raw_observations",null):0,sem=table("ue_semantic_events")?scalar("SELECT COALESCE(MAX(id),0) FROM ue_semantic_events",null):0,rev=table("ue_projection_revisions")?scalar("SELECT COALESCE(MAX(revision),0) FROM ue_projection_revisions",null):0;return raw*31L+sem*17L+rev;}boolean table(String name){Cursor c=db.getReadableDatabase().rawQuery("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1",new String[]{name});boolean yes=c.moveToFirst();c.close();return yes;}long scalar(String sql,String[] args){Cursor c=null;try{c=db.getReadableDatabase().rawQuery(sql,args);return c.moveToFirst()?c.getLong(0):0;}finally{if(c!=null)c.close();}}long startOfDay(){Calendar c=Calendar.getInstance();c.set(Calendar.HOUR_OF_DAY,0);c.set(Calendar.MINUTE,0);c.set(Calendar.SECOND,0);c.set(Calendar.MILLISECOND,0);return c.getTimeInMillis();}boolean contains(String[] xs,String x){if(xs==null||x==null)return false;for(String s:xs)if(s.equalsIgnoreCase(x))return true;return false;}String clock(long ms){return new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(ms));}String safe(String s){return s==null?"":s.trim();}LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
}
