package com.kareem.cortex;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.net.Uri;
import android.os.*;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.io.File;
import java.util.Locale;

/** Single, premium capture surface. The legacy MainActivity remains only for old/advanced flows. */
public class CaptureActivity extends Activity {
    static final int REQ_MIC=771,REQ_IMPORT=772;
    VaultDb db;AudioCapture recorder=new AudioCapture();File recordingFile;long recordingStarted;Handler handler=new Handler(Looper.getMainLooper());Runnable tick;LinearLayout body,recordPanel;TextView timer;
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);build();int imported=new ShareImporter(this,db).importIntent(getIntent());if(imported>0){Toast.makeText(this,"Saved to Cortex",Toast.LENGTH_SHORT).show();kick();}}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);int n=new ShareImporter(this,db).importIntent(i);if(n>0){Toast.makeText(this,"Saved to Cortex",Toast.LENGTH_SHORT).show();kick();}}
    @Override protected void onDestroy(){super.onDestroy();if(tick!=null)handler.removeCallbacks(tick);if(recorder.isRunning())try{File f=recorder.stop();if(f!=null)f.delete();}catch(Throwable ignored){}}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),dp(24));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Capture",29,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);titles.addView(CortexUi.plain(this,"Add one thing. Cortex handles the rest.",11,CortexUi.MUTED));head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));body.addView(head);
        TextView intro=CortexUi.text(this,"Choose the source. Capture is intentionally separate from search, Ask and Focus so the app has one clear job per screen.",13,CortexUi.MUTED);intro.setPadding(dp(2),dp(18),dp(2),dp(4));body.addView(intro);
        body.addView(CortexUi.section(this,"Capture now"));addChoice("Voice note","Record directly in Cortex","VOICE",this::startVoice);addChoice("Quick note","Paste or type a thought, link, log or research note","TEXT",this::quickNote);addChoice("Import recording","Choose an audio file and transcribe it","AUDIO",this::importRecording);
        body.addView(CortexUi.section(this,"Setup"));addChoice("Transcription providers","Groq / Gemini keys and ASR preferences","ASR",()->startActivity(new Intent(this,AsrSettingsActivity.class)));
        CortexUi.addBottomNav(this,root,"",null);setContentView(root);}

    void addChoice(String title,String sub,String badge,Runnable action){LinearLayout c=CortexUi.card(this,22);c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(15),dp(14),dp(14),dp(14));CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,22));TextView b=CortexUi.chip(this,badge,CortexUi.ACCENT,true);c.addView(b,new LinearLayout.LayoutParams(dp(62),dp(34)));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);text.setPadding(dp(13),0,0,0);TextView t=CortexUi.plain(this,title,15,CortexUi.TEXT);CortexUi.medium(t);text.addView(t);TextView s=CortexUi.text(this,sub,11,CortexUi.MUTED);s.setPadding(0,dp(3),0,0);text.addView(s);c.addView(text,new LinearLayout.LayoutParams(0,-2,1));TextView arrow=CortexUi.plain(this,"›",27,CortexUi.MUTED);arrow.setGravity(Gravity.CENTER);c.addView(arrow,new LinearLayout.LayoutParams(dp(30),dp(44)));c.setOnClickListener(v->action.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));body.addView(c,p);}

    void quickNote(){final Dialog d=new Dialog(this);Window w=d.getWindow();LinearLayout box=CortexUi.card(this,26);box.setPadding(dp(18),dp(18),dp(18),dp(18));TextView title=CortexUi.plain(this,"Quick note",21,CortexUi.TEXT);CortexUi.medium(title);box.addView(title);TextView sub=CortexUi.text(this,"Save the raw note first. Understanding and indexing happen after capture.",12,CortexUi.MUTED);sub.setPadding(0,dp(5),0,dp(12));box.addView(sub);EditText e=new EditText(this);e.setHint("Type or paste anything…");e.setHintTextColor(CortexUi.FAINT);e.setTextColor(CortexUi.TEXT);e.setTextSize(14);e.setGravity(Gravity.TOP);e.setMinLines(7);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);e.setPadding(dp(13),dp(12),dp(13),dp(12));e.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER,17));box.addView(e,new LinearLayout.LayoutParams(-1,-2));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setPadding(0,dp(14),0,0);TextView cancel=CortexUi.action(this,"Cancel",CortexUi.MUTED,false),save=CortexUi.action(this,"Save",CortexUi.ACCENT,true);actions.addView(cancel,new LinearLayout.LayoutParams(0,dp(46),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(46),1);sp.setMargins(dp(9),0,0,0);actions.addView(save,sp);box.addView(actions);cancel.setOnClickListener(v->d.dismiss());save.setOnClickListener(v->{String s=e.getText().toString().trim();if(s.isEmpty()){e.setError("Write something first");return;}String cat=AutoClassifier.category(s,"text/plain");long id=db.insert("TEXT","manual",AutoClassifier.title(s,"text/plain"),s,cat,AutoClassifier.tags(s,cat),"",Fingerprint.text(s),"{}");if(id<0)Toast.makeText(this,"Already in Cortex",Toast.LENGTH_SHORT).show();else{Toast.makeText(this,"Saved",Toast.LENGTH_SHORT).show();kick();d.dismiss();}});d.setContentView(box);w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout(WindowManager.LayoutParams.MATCH_PARENT,WindowManager.LayoutParams.WRAP_CONTENT);}d.setOnShowListener(x->{Window ww=d.getWindow();if(ww!=null)ww.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.92f),WindowManager.LayoutParams.WRAP_CONTENT);});d.show();}

    void importRecording(){if(!GroqKeyStore.has(this)&&!GeminiKeyStore.has(this)){Toast.makeText(this,"Set up a transcription provider first",Toast.LENGTH_LONG).show();startActivity(new Intent(this,AsrSettingsActivity.class));return;}Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("audio/*");startActivityForResult(i,REQ_IMPORT);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req!=REQ_IMPORT||result!=RESULT_OK||data==null||data.getData()==null)return;Uri uri=data.getData();try{long id=new ShareImporter(this,db).importAudio(uri,getContentResolver().getType(uri));if(id>0){Toast.makeText(this,"Recording imported — transcribing…",Toast.LENGTH_SHORT).show();kick();}else Toast.makeText(this,"Could not import or it already exists",Toast.LENGTH_LONG).show();}catch(Throwable e){Toast.makeText(this,"Import failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}

    void startVoice(){if(!GroqKeyStore.has(this)&&!GeminiKeyStore.has(this)){Toast.makeText(this,"Set up a transcription provider first",Toast.LENGTH_LONG).show();startActivity(new Intent(this,AsrSettingsActivity.class));return;}if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}beginVoice();}
    @Override public void onRequestPermissionsResult(int req,String[] p,int[] g){super.onRequestPermissionsResult(req,p,g);if(req==REQ_MIC&&g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED)beginVoice();else if(req==REQ_MIC)Toast.makeText(this,"Microphone permission is required",Toast.LENGTH_LONG).show();}
    void beginVoice(){try{recordingFile=recorder.start(this);recordingStarted=System.currentTimeMillis();showRecordingPanel();}catch(Throwable e){Toast.makeText(this,"Could not start recording: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    void showRecordingPanel(){recordPanel=CortexUi.card(this,26);recordPanel.setPadding(dp(20),dp(22),dp(20),dp(20));recordPanel.setBackground(CortexUi.gradient(this,Color.rgb(24,29,40),CortexUi.SURFACE,CortexUi.BORDER,26));TextView live=CortexUi.chip(this,"RECORDING",CortexUi.ACCENT,true);recordPanel.addView(live,new LinearLayout.LayoutParams(-2,dp(30)));timer=CortexUi.plain(this,"00:00",40,CortexUi.TEXT);CortexUi.medium(timer);timer.setPadding(0,dp(12),0,0);recordPanel.addView(timer);TextView info=CortexUi.text(this,"Arabic + English transcription starts after you save.",12,CortexUi.MUTED);info.setPadding(0,dp(4),0,dp(16));recordPanel.addView(info);LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);TextView cancel=CortexUi.action(this,"Discard",CortexUi.MUTED,false),save=CortexUi.action(this,"Stop & save",CortexUi.ACCENT,true);actions.addView(cancel,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(48),1);p.setMargins(dp(9),0,0,0);actions.addView(save,p);recordPanel.addView(actions);cancel.setOnClickListener(v->finishVoice(false));save.setOnClickListener(v->finishVoice(true));body.addView(recordPanel,2,new LinearLayout.LayoutParams(-1,-2));tick=new Runnable(){public void run(){long sec=(System.currentTimeMillis()-recordingStarted)/1000;if(timer!=null)timer.setText(String.format(Locale.US,"%02d:%02d",sec/60,sec%60));if(recorder.isRunning())handler.postDelayed(this,500);}};handler.post(tick);}
    void finishVoice(boolean save){try{File f=recorder.stop();if(tick!=null)handler.removeCallbacks(tick);if(recordPanel!=null){body.removeView(recordPanel);recordPanel=null;}if(f==null)return;if(!save){f.delete();Toast.makeText(this,"Recording discarded",Toast.LENGTH_SHORT).show();return;}JSONObject m=new JSONObject();m.put("mime","audio/wav");m.put("bytes",f.length());m.put("recorded_at",System.currentTimeMillis());long id=db.insert("AUDIO","manual_recording","Voice recording","","Voice & Audio","voice,audio,transcript",f.getAbsolutePath(),Fingerprint.file(f.getAbsolutePath()),m.toString());if(id<0){f.delete();Toast.makeText(this,"Already in Cortex",Toast.LENGTH_SHORT).show();}else{Toast.makeText(this,"Voice saved — transcribing…",Toast.LENGTH_SHORT).show();kick();}}catch(Throwable e){Toast.makeText(this,"Could not save recording: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    void kick(){AnalysisQueue.kick(this,db,()->{});}
}
