package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Bitmap;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.io.File;
import java.util.*;
import java.util.concurrent.*;

/** Immediate post-capture surface: extraction is evidence; understanding + action + learning is the product. */
public class CaptureResultActivity extends Activity {
    VaultDb db;long itemId;Handler handler=new Handler(Looper.getMainLooper());LinearLayout content;TextView state;volatile boolean stopped=false,visionRequested=false;final ExecutorService worker=Executors.newSingleThreadExecutor();
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);itemId=getIntent().getLongExtra("item_id",0);build();refresh();}
    @Override protected void onDestroy(){stopped=true;handler.removeCallbacksAndMessages(null);worker.shutdownNow();if(db!=null)try{db.close();}catch(Throwable ignored){}db=null;super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(16),dp(20),dp(28));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"input",null);setContentView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView h=CortexUi.plain(this,"Cortex is understanding this",24,CortexUi.TEXT);CortexUi.medium(h);head.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView close=CortexUi.chip(this,"Close",CortexUi.MUTED,false);close.setOnClickListener(v->finish());head.addView(close,new LinearLayout.LayoutParams(-2,dp(36)));content.addView(head);state=CortexUi.plain(this,"Queued for analysis…",11,CortexUi.ACCENT);state.setPadding(0,dp(7),0,dp(14));content.addView(state);}
    void refresh(){if(stopped||db==null||itemId<=0||isFinishing()||isDestroyed())return;try{KnowledgeItem k=db.getById(itemId);if(k==null){state.setText("Capture could not be found.");return;}render(k);if(pending(k)&&!stopped)handler.postDelayed(this::refresh,650);}catch(Throwable e){if(!stopped&&state!=null)state.setText("Capture is safe. Status will refresh when Cortex is ready.");}}
    boolean pending(KnowledgeItem k){String s=n(k.status);return s.isEmpty()||"pending".equals(s)||"queued".equals(s)||"analyzing".equals(s)||"processing".equals(s);}

    void render(KnowledgeItem k){if(stopped||content==null)return;while(content.getChildCount()>2)content.removeViewAt(2);String s=n(k.status);VisualInsightStore.Insight vi=isImage(k)?safeInsight(k.id):null;boolean visualReady=vi!=null&&vi.ready();if(pending(k))state.setText("Analyzing • extracting evidence and connecting context…");else if(failed(s))state.setText("Analysis needs attention");else if(isImage(k)&&!visualReady&&visionCanRun(k))state.setText("Evidence ready • understanding the image itself…");else state.setText("Understood • ready");
        if(isImage(k)&&!empty(k.attachmentPath)){Bitmap bm=preview(k.attachmentPath);if(bm!=null){ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.FIT_CENTER);im.setImageBitmap(bm);im.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER_SOFT,18));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,-2);ip.setMargins(0,0,0,dp(14));content.addView(im,ip);}}
        TextView title=CortexUi.text(this,displayTitle(k,vi),18,CortexUi.TEXT);CortexUi.medium(title);content.addView(title);TextView meta=CortexUi.plain(this,friendlyType(k.type)+" • "+friendlyState(s)+(visualReady?" • visual understanding ready":""),10,CortexUi.MUTED);meta.setPadding(0,dp(5),0,dp(12));content.addView(meta);
        if(pending(k)){LinearLayout card=CortexUi.card(this,20);card.addView(CortexUi.text(this,"Cortex is reading the capture, checking what it means, and deciding whether it should become useful context, a review item, or an action.",13,CortexUi.TEXT));content.addView(card);return;}
        if(failed(s)){LinearLayout card=CortexUi.card(this,20);card.addView(CortexUi.text(this,empty(k.analysisError)?"Analysis did not finish successfully.":k.analysisError,12,CortexUi.MUTED));TextView retry=CortexUi.action(this,"Retry analysis",CortexUi.ACCENT,true);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(46));rp.setMargins(0,dp(12),0,0);card.addView(retry,rp);retry.setOnClickListener(v->{if(stopped||db==null)return;try{db.retry(k.id);AnalysisQueue.kick(getApplicationContext(),null,this::refresh);state.setText("Retrying…");handler.postDelayed(this::refresh,250);}catch(Throwable e){state.setText("Retry could not start yet.");}});content.addView(card);return;}

        if(isImage(k)&&!visualReady)ensureVisualUnderstanding(k,vi);content.addView(CortexUi.section(this,"What Cortex understood"));TextView u=CortexUi.text(this,understanding(k,vi),14,CortexUi.TEXT);u.setTextIsSelectable(true);content.addView(u);if(visualReady&&!empty(vi.usefulnessReason)){content.addView(CortexUi.section(this,"Why it may matter"));content.addView(CortexUi.text(this,vi.usefulnessReason,13,CortexUi.MUTED));}
        content.addView(CortexUi.section(this,"What you can do"));LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.VERTICAL);addBrainAction(actions,k,brainLabel(k,vi),brainPrompt(k,vi),true);if(visualReady)addContextActions(actions,k,vi);addCommonActions(actions,k,vi);if(isImage(k)&&!visualReady){TextView visual=CortexUi.action(this,"Open visual intelligence",CortexUi.MUTED,false);addActionView(actions,visual);visual.setOnClickListener(v->openVisual(k.id));}TextView archive=CortexUi.action(this,"Open evidence",CortexUi.MUTED,false);addActionView(actions,archive);archive.setOnClickListener(v->{try{Intent i=new Intent(this,VaultActivity.class);i.putExtra("item_id",k.id);startActivity(i);}catch(Throwable ignored){}});content.addView(actions);
        addFeedback(k,vi);String raw=!empty(k.extractedText)?k.extractedText:k.rawText;if(!empty(raw)){content.addView(CortexUi.section(this,"Extracted evidence (optional)"));TextView e=CortexUi.text(this,clip(raw,1600),11,CortexUi.MUTED);e.setTextIsSelectable(true);content.addView(e);}
    }

    void addCommonActions(LinearLayout box,KnowledgeItem k,VisualInsightStore.Insight vi){TextView project=CortexUi.action(this,"Add to project",CortexUi.MUTED,false);addActionView(box,project);project.setOnClickListener(v->CortexActionExecutor.chooseProject(this,db,k.id,this::refresh));String reminderText=!empty(k.summary)?k.summary:(!empty(vi==null?"":vi.description)?vi.description:k.title);TextView reminder=CortexUi.action(this,"Create reminder draft",CortexUi.MUTED,false);addActionView(box,reminder);reminder.setOnClickListener(v->CortexActionExecutor.calendarDraft(this,empty(k.title)?"Cortex follow-up":k.title,clip(reminderText,1600),System.currentTimeMillis()+60L*60L*1000L));}
    void addFeedback(KnowledgeItem k,VisualInsightStore.Insight vi){content.addView(CortexUi.section(this,"Teach Cortex"));LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);TextView useful=CortexUi.action(this,"Useful",CortexUi.SAGE,false),bad=CortexUi.action(this,"Not useful",CortexUi.MUTED,false);row.addView(useful,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(44),1);bp.setMargins(dp(8),0,0,0);row.addView(bad,bp);content.addView(row);useful.setOnClickListener(v->{if(isImage(k)&&vi!=null)try{VisualInsightStore.setUserValue(db,k.id,1);}catch(Throwable ignored){}CortexActionExecutor.recordFeedback(db,k.id,"useful","true");Toast.makeText(this,"Cortex will learn from this",Toast.LENGTH_SHORT).show();});bad.setOnClickListener(v->{if(isImage(k)&&vi!=null)try{VisualInsightStore.setUserValue(db,k.id,-1);}catch(Throwable ignored){}CortexActionExecutor.recordFeedback(db,k.id,"not_useful","true");Toast.makeText(this,"Marked not useful",Toast.LENGTH_SHORT).show();});if(isImage(k)){TextView teach=CortexUi.action(this,"Teach what matters in this image",CortexUi.ACCENT,false);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,dp(44));tp.setMargins(0,dp(8),0,0);content.addView(teach,tp);teach.setOnClickListener(v->teachScreenshot(k,vi));}}
    void teachScreenshot(KnowledgeItem k,VisualInsightStore.Insight vi){String type=vi!=null&&vi.ready()&&!empty(vi.contentType)?vi.contentType:ScreenshotLearning.contentType(db,k.id);String[] opts=ScreenshotLearning.options(type);boolean[] checked=ScreenshotLearning.suggested(db,type,opts);HashSet<String> existing=new HashSet<>(ScreenshotLearning.selected(db,k.id));for(int i=0;i<opts.length;i++)if(existing.contains(opts[i]))checked[i]=true;new AlertDialog.Builder(this).setTitle("What should Cortex learn from this?").setMultiChoiceItems(opts,checked,(d,w,on)->checked[w]=on).setNegativeButton("Cancel",null).setPositiveButton("Save learning",(d,w)->{ScreenshotLearning.record(db,k.id,type,opts,checked);CortexActionExecutor.recordFeedback(db,k.id,"taught_screenshot",type);Toast.makeText(this,"Learning saved",Toast.LENGTH_SHORT).show();}).show();}

    void ensureVisualUnderstanding(KnowledgeItem k,VisualInsightStore.Insight existing){if(visionRequested||stopped||!isImage(k)||existing!=null&&("done".equals(existing.status)||"local_only".equals(existing.status)||"rate_limited".equals(existing.status)))return;VisualTriage.Result triage=VisualTriage.evaluate(k);if(triage.sensitive){try{VisualInsightStore.saveState(db,k.id,"local_only","local_only",triage.reason);}catch(Throwable ignored){}return;}if(!PrivacyPolicy.canUseCloud(this,"images")||!GeminiKeyStore.has(this))return;visionRequested=true;final KnowledgeItem snapshot=k;try{worker.execute(()->{VaultDb workDb=null;try{JSONObject r=GeminiVisionAnalyzer.analyze(getApplicationContext(),snapshot);workDb=new VaultDb(getApplicationContext());VisualInsightStore.saveModel(workDb,snapshot.id,r);}catch(GeminiVisionAnalyzer.VisionException e){try{if(workDb==null)workDb=new VaultDb(getApplicationContext());VisualInsightStore.saveState(workDb,snapshot.id,e.rateLimited()?"rate_limited":"failed","safe",e.getMessage());}catch(Throwable ignored){}}catch(Throwable e){try{if(workDb==null)workDb=new VaultDb(getApplicationContext());VisualInsightStore.saveState(workDb,snapshot.id,"failed","safe",e.getClass().getSimpleName()+": "+safe(e.getMessage()));}catch(Throwable ignored){}}finally{if(workDb!=null)try{workDb.close();}catch(Throwable ignored){}postUi(()->{visionRequested=false;refresh();});}});}catch(RejectedExecutionException ignored){visionRequested=false;}}
    boolean visionCanRun(KnowledgeItem k){if(!isImage(k))return false;try{VisualTriage.Result t=VisualTriage.evaluate(k);return !t.sensitive&&PrivacyPolicy.canUseCloud(this,"images")&&GeminiKeyStore.has(this);}catch(Throwable e){return false;}}
    String understanding(KnowledgeItem k,VisualInsightStore.Insight vi){if(vi!=null&&vi.ready()&&!empty(vi.description))return vi.description;if(vi!=null&&"local_only".equals(vi.status))return"Cortex kept this image local because it may contain sensitive information. Supporting text is available below, and Brain can reason locally without uploading the image.";String raw=!empty(k.extractedText)?k.extractedText:k.rawText;if(!empty(k.summary)&&VoiceTextPresentation.materiallyDifferent(k.summary,raw))return k.summary;if("AUDIO".equals(k.type))return"Cortex captured the voice note as evidence. Ask Brain to interpret the intent, connect it to your current context, and turn it into a decision, follow-up, reminder, or next action.";if(isImage(k))return visionCanRun(k)?"Local evidence is ready. Cortex is now inspecting the image itself so the result can describe what it actually represents rather than repeating OCR.":"Cortex extracted supporting evidence locally. Strong visual understanding is unavailable or protected by the current privacy/provider state; the original image remains available to Brain under the selected mode.";if("FILE".equals(k.type))return"The file was imported as evidence. Brain can reason over its content, connect it to people/projects, and suggest useful next actions.";return"The text was indexed as evidence. Brain can now interpret its meaning, connect it to your Cortex context, and suggest executable next steps.";}
    String displayTitle(KnowledgeItem k,VisualInsightStore.Insight vi){if(vi!=null&&vi.ready()&&!empty(vi.description)){String d=vi.description.replaceAll("\\s+"," ").trim();if(d.length()>70)d=d.substring(0,70)+"…";return d;}return empty(k.title)?friendlyType(k.type):k.title;}
    void addBrainAction(LinearLayout box,KnowledgeItem k,String label,String prompt,boolean primary){TextView b=CortexUi.action(this,label,primary?CortexUi.ACCENT:CortexUi.MUTED,primary);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,primary?dp(48):dp(44));if(box.getChildCount()>0)p.setMargins(0,dp(8),0,0);box.addView(b,p);b.setOnClickListener(v->CortexActionExecutor.openBrain(this,k.id,prompt));}
    void addContextActions(LinearLayout box,KnowledgeItem k,VisualInsightStore.Insight vi){String type=safe(vi.contentType).toLowerCase(Locale.ROOT);if(type.contains("product")){addBrainAction(box,k,"Deep research this product","Research this product deeply from the attached capture. Explain what it is and its uses, identify anything important or uncertain, compare useful alternatives, and focus on availability/prices/options in Egypt when you have reliable information.",false);addSearchAction(box,empty(vi.searchQuery)?vi.description+" Egypt buy price reviews":vi.searchQuery,"Search this product online");}else if(type.contains("document")||type.contains("receipt")){addBrainAction(box,k,"Summarize + extract actions","Read this attached document/receipt as primary evidence. Summarize what matters, extract dates, amounts, commitments and actions, and flag anything I should follow up on.",false);}else if(type.contains("ui")||type.contains("chat")){addBrainAction(box,k,"Explain / diagnose this screen","Inspect this attached screen itself. Explain what is happening, identify any problem or important state, connect it to my Cortex context, and suggest concrete fixes or next steps.",false);}else if(type.contains("design")||type.contains("photo")){addBrainAction(box,k,"Analyze this visual","Analyze the attached image itself: subject, style, important details, possible use as a reference, and the most useful next actions.",false);}else addBrainAction(box,k,"Get deeper insight","Use the attached capture itself plus my Cortex context to explain what it means and what I can usefully do next.",false);if(!empty(vi.searchQuery)&&!type.contains("product"))addSearchAction(box,vi.searchQuery,"Search online");}
    void addSearchAction(LinearLayout box,String query,String label){TextView v=CortexUi.action(this,label,CortexUi.MUTED,false);addActionView(box,v);v.setOnClickListener(x->CortexActionExecutor.searchWeb(this,query));}void addActionView(LinearLayout box,TextView v){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(44));if(box.getChildCount()>0)p.setMargins(0,dp(8),0,0);box.addView(v,p);}
    String brainLabel(KnowledgeItem k,VisualInsightStore.Insight vi){if(vi!=null&&vi.ready()&&safe(vi.contentType).toLowerCase(Locale.ROOT).contains("product"))return"Ask Brain about this product";return"Ask Brain about this";}String brainPrompt(KnowledgeItem k,VisualInsightStore.Insight vi){if(vi!=null&&vi.ready())return"Use this exact attached Cortex capture as primary evidence. Explain what it is, what it means in my context, why it may matter, connect it to relevant Cortex data, and suggest the most useful executable next actions. Do not merely repeat OCR.";return"I just captured this in Cortex. Use the attached item itself as the subject. Understand what it means in context, tell me why it may matter, connect it to relevant data, and suggest useful executable next actions.";}
    void openVisual(long id){try{Intent i=new Intent(this,VisualIntelligenceActivity.class);i.putExtra("item_id",id);startActivity(i);}catch(Throwable ignored){}}VisualInsightStore.Insight safeInsight(long id){try{return VisualInsightStore.get(db,id);}catch(Throwable e){return null;}}void postUi(Runnable r){if(stopped||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!stopped&&!isFinishing()&&!isDestroyed())try{r.run();}catch(Throwable ignored){}});}
    Bitmap preview(String path){try{return SafeImageDecoder.decode(new File(path),1200,1_600_000L);}catch(Throwable e){return null;}}boolean isImage(KnowledgeItem k){return k!=null&&("SCREENSHOT".equals(k.type)||"IMAGE".equals(k.type));}boolean failed(String s){return"failed_retryable".equals(s)||"analysis_failed".equals(s)||"failed".equals(s);}String friendlyType(String t){if("AUDIO".equals(t))return"Voice";if("FILE".equals(t))return"File";if("SCREENSHOT".equals(t)||"IMAGE".equals(t))return"Image";return"Text";}String friendlyState(String s){if("analyzed".equals(s))return"analysis complete";if("analyzing".equals(s))return"analyzing";if("failed_retryable".equals(s))return"retry available";return s.isEmpty()?"captured":s.replace('_',' ');}String clip(String s,int n){String x=safe(s).trim();return x.length()<=n?x:x.substring(0,n)+"…";}boolean empty(String s){return s==null||s.trim().isEmpty();}String n(String s){return s==null?"":s.trim();}String safe(String s){return s==null?"":s;}
}
