package com.kareem.cortex;

import android.accounts.AccountManager;
import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.Gravity;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;
import org.json.JSONObject;

public final class ChatGptTeacherActivity extends Activity {
    private static final int REQ_BRIDGE_ACCOUNT=4511,REQ_BRIDGE_CONSENT=4512;
    private static final String BRIDGE_PREFS="chatgpt_gmail_bridge",BRIDGE_ACCOUNT="account";
    private TextView status,launch,impact,promotion,rollback,bridgeStatus,bridgeHandshake,bridgePoll;
    private int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);build();}
    @Override protected void onResume(){super.onResume();if(status!=null){CortexChatGptAppTeacher.ImportResult r=CortexChatGptAppTeacher.importClipboardIfReady(this);if(r.ok)Toast.makeText(this,"ChatGPT policy activated in Cortex",Toast.LENGTH_LONG).show();refresh(r);refreshBridge();}}

    private void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),dp(28));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"ChatGPT Teacher",28,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);TextView sub=CortexUi.text(this,"Tunes final judgment only · Cortex keeps evidence and execution local.",11,CortexUi.MUTED);sub.setPadding(0,dp(2),0,0);titles.addView(sub);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));body.addView(head);

        body.addView(CortexUi.section(this,"Gmail bridge · test adjudication"));
        TextView bridgeInfo=CortexUi.text(this,"Phase 1 sends grounded test requests through Gmail and accepts only correlated ChatGPT verdicts. Original pipeline input, Cortex output, and reference evidence stay separate. Teaching remains disabled here until explicitly promoted through the existing bounded teacher path.",12,CortexUi.TEXT);bridgeInfo.setPadding(0,dp(4),0,dp(8));body.addView(bridgeInfo);
        bridgeStatus=CortexUi.text(this,"",12,CortexUi.MUTED);bridgeStatus.setPadding(0,dp(4),0,dp(8));bridgeStatus.setTextIsSelectable(true);body.addView(bridgeStatus);
        TextView choose=CortexUi.action(this,"CHOOSE GMAIL ACCOUNT",CortexUi.TEXT,false);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(44));cp.setMargins(0,dp(4),0,0);body.addView(choose,cp);choose.setOnClickListener(v->chooseBridgeAccount());
        bridgeHandshake=CortexUi.action(this,"SEND LIVE CORTEX HANDSHAKE",CortexUi.LIME,true);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,dp(46));hp.setMargins(0,dp(8),0,0);body.addView(bridgeHandshake,hp);bridgeHandshake.setOnClickListener(v->authorizeAndHandshake());
        bridgePoll=CortexUi.action(this,"POLL CHATGPT VERDICTS",CortexUi.TEXT,false);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(44));bp.setMargins(0,dp(8),0,0);body.addView(bridgePoll,bp);bridgePoll.setOnClickListener(v->pollBridgeVerdicts());

        body.addView(CortexUi.section(this,"How bounded teaching works"));TextView route=CortexUi.text(this,"1. Cortex builds a normalized Context Pack.\n2. ChatGPT proposes a bounded Policy Pack.\n3. Copy the returned JSON and come back.\n4. Cortex validates it, compares the same live candidates, stages a rollback-safe canary, then CortexAttentionJudge uses it locally.\n\nIf there are zero canonical candidates, Cortex will say so explicitly instead of pretending the shadow test proved anything.",12,CortexUi.TEXT);route.setPadding(0,dp(4),0,dp(8));body.addView(route);
        launch=CortexUi.action(this,"TEACH WITH CHATGPT",CortexUi.LIME,true);LinearLayout.LayoutParams yp=new LinearLayout.LayoutParams(-1,dp(46));yp.setMargins(0,dp(10),0,0);body.addView(launch,yp);launch.setOnClickListener(v->launchChatGpt());
        TextView paste=CortexUi.action(this,"PASTE POLICY FROM CLIPBOARD",CortexUi.TEXT,false);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(46));pp.setMargins(0,dp(10),0,0);body.addView(paste,pp);paste.setOnClickListener(v->{CortexChatGptAppTeacher.ImportResult r=CortexChatGptAppTeacher.importClipboardIfReady(this);refresh(r);Toast.makeText(this,r.ok?"Policy activated":"Import failed: "+r.error,Toast.LENGTH_LONG).show();});
        body.addView(CortexUi.section(this,"Status"));status=CortexUi.text(this,"",12,CortexUi.TEXT);status.setPadding(0,dp(4),0,dp(8));status.setTextIsSelectable(true);body.addView(status);
        body.addView(CortexUi.section(this,"Teacher impact"));impact=CortexUi.text(this,"",12,CortexUi.MUTED);impact.setPadding(0,dp(4),0,dp(8));body.addView(impact);
        body.addView(CortexUi.section(this,"Policy promotion"));promotion=CortexUi.text(this,"",12,CortexUi.MUTED);promotion.setPadding(0,dp(4),0,dp(8));body.addView(promotion);
        rollback=CortexUi.action(this,"ROLL BACK TO PREVIOUS POLICY",CortexUi.MUTED,false);LinearLayout.LayoutParams rbp=new LinearLayout.LayoutParams(-1,dp(44));rbp.setMargins(0,dp(4),0,0);body.addView(rollback,rbp);rollback.setOnClickListener(v->{boolean ok=CortexPolicyPromotion.rollback(this,"manual rollback from teacher screen");Toast.makeText(this,ok?"Previous policy restored":"No previous policy available",Toast.LENGTH_LONG).show();refresh(null);});
        body.addView(CortexUi.section(this,"Safety boundary"));TextView rules=CortexUi.text(this,"A teacher policy cannot create facts, classify raw notifications, mutate canonical knowledge, execute actions, or directly surface UI. Gmail is transport only. ChatGPT verdicts are external adjudication records, never canonical evidence.",12,CortexUi.MUTED);rules.setPadding(0,dp(4),0,0);body.addView(rules);setContentView(root);CortexUi.fitSystemBars(this,root);refresh(null);refreshBridge();
    }

    private void chooseBridgeAccount(){Intent i=AccountManager.newChooseAccountIntent(null,null,new String[]{AccountManagerGmailTokenProvider.GOOGLE_ACCOUNT_TYPE},false,"Choose Cortex Bridge Gmail account",null,null,null);startActivityForResult(i,REQ_BRIDGE_ACCOUNT);}

    private String bridgeAccount(){return getSharedPreferences(BRIDGE_PREFS,MODE_PRIVATE).getString(BRIDGE_ACCOUNT,"");}

    private void authorizeAndHandshake(){String account=bridgeAccount();if(account.isEmpty()){chooseBridgeAccount();return;}setBridgeBusy(true,"Requesting Gmail authorization…");new Thread(()->{try{AccountManagerGmailTokenProvider provider=new AccountManagerGmailTokenProvider(getApplicationContext(),account);provider.getAccessToken();ChatGptBridgeCoordinator coordinator=new ChatGptBridgeCoordinator(getApplicationContext(),new GmailBridgeTransport(provider,account));JSONObject original=new JSONObject().put("kind","BRIDGE_HANDSHAKE").put("instruction","Judge the grounded transport request independently. Do not create canonical facts.").put("package",getPackageName());JSONObject cortex=new JSONObject().put("bridgeReady",true).put("transport","GMAIL_REST").put("teachingEnabled",false);JSONObject reference=new JSONObject().put("expectedTransport","GMAIL_REST").put("expectedTeachingEnabled",false);ChatGptBridgeCoordinator.DispatchResult r=coordinator.dispatchTest("bridge-handshake-"+System.currentTimeMillis(),"transport-handshake",original,cortex,reference);runOnUiThread(()->{setBridgeBusy(false,r.sent?"Handshake sent from Cortex · Gmail id "+r.gmailMessageId:"Handshake failed · "+r.error);refreshBridge();});}catch(AccountManagerGmailTokenProvider.AuthRequiredException e){runOnUiThread(()->{setBridgeBusy(false,"Google authorization required");if(e.consentIntent!=null)startActivityForResult(e.consentIntent,REQ_BRIDGE_CONSENT);else Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();});}catch(Throwable e){runOnUiThread(()->setBridgeBusy(false,"Bridge error · "+e.getClass().getSimpleName()+" · "+safeMessage(e)));}},"cortex-gmail-bridge-handshake").start();}

    private void pollBridgeVerdicts(){String account=bridgeAccount();if(account.isEmpty()){chooseBridgeAccount();return;}setBridgeBusy(true,"Polling Gmail for ChatGPT verdicts…");new Thread(()->{try{AccountManagerGmailTokenProvider provider=new AccountManagerGmailTokenProvider(getApplicationContext(),account);provider.getAccessToken();ChatGptBridgeCoordinator coordinator=new ChatGptBridgeCoordinator(getApplicationContext(),new GmailBridgeTransport(provider,account));ChatGptBridgeCoordinator.PollResult r=coordinator.pollVerdicts(System.currentTimeMillis()-7L*24L*60L*60L*1000L,100);runOnUiThread(()->{setBridgeBusy(false,r.ok?"Verdicts · "+r.accepted+" accepted · "+r.rejected+" rejected · "+r.seen+" seen":"Poll failed · "+r.error);refreshBridge();});}catch(AccountManagerGmailTokenProvider.AuthRequiredException e){runOnUiThread(()->{setBridgeBusy(false,"Google authorization required");if(e.consentIntent!=null)startActivityForResult(e.consentIntent,REQ_BRIDGE_CONSENT);else Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();});}catch(Throwable e){runOnUiThread(()->setBridgeBusy(false,"Poll error · "+e.getClass().getSimpleName()+" · "+safeMessage(e)));}},"cortex-gmail-bridge-poll").start();}

    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode==REQ_BRIDGE_ACCOUNT&&resultCode==RESULT_OK&&data!=null){String name=data.getStringExtra(AccountManager.KEY_ACCOUNT_NAME);if(name!=null&&!name.trim().isEmpty()){getSharedPreferences(BRIDGE_PREFS,MODE_PRIVATE).edit().putString(BRIDGE_ACCOUNT,name.trim()).apply();refreshBridge();authorizeAndHandshake();}}else if(requestCode==REQ_BRIDGE_CONSENT){refreshBridge();if(resultCode==RESULT_OK)authorizeAndHandshake();}}

    private void refreshBridge(){if(bridgeStatus==null)return;String account=bridgeAccount();try{JSONObject s=new ChatGptBridgeStore(getApplicationContext()).summary();bridgeStatus.setText((account.isEmpty()?"Gmail account: not selected":"Gmail account: "+account)+"\nPending requests: "+s.optInt("pending",0)+"\nAccepted verdicts: "+s.optInt("verdicts",0)+"\nRejected responses: "+s.optInt("rejected",0)+"\nTeaching over bridge: DISABLED");boolean configured=!account.isEmpty();bridgeHandshake.setEnabled(configured);bridgePoll.setEnabled(configured);}catch(Throwable e){bridgeStatus.setText("Bridge store unavailable · "+e.getClass().getSimpleName());}}

    private void setBridgeBusy(boolean busy,String text){bridgeStatus.setText(text);bridgeHandshake.setEnabled(!busy&&!bridgeAccount().isEmpty());bridgePoll.setEnabled(!busy&&!bridgeAccount().isEmpty());}

    private void refresh(CortexChatGptAppTeacher.ImportResult latest){if(status==null)return;status.setText(statusText(latest));JSONObject r=CortexTeacherImpact.latest(this);if(r.length()==0)impact.setText("No shadow comparison yet.");else if(r.optInt("candidateCount",0)==0)impact.setText(CortexTeacherImpact.summary(this)+"\nNo canonical candidates were available. This is NOT counted as a passed behavioral test; the policy is only staged for future real judgments.");else impact.setText(CortexTeacherImpact.summary(this));promotion.setText(CortexPolicyPromotion.status(this));rollback.setEnabled(CortexPolicyPromotion.canRollback(this));}
    private void launchChatGpt(){launch.setEnabled(false);launch.setText("PREPARING…");new Thread(()->{try{CortexChatGptAppTeacher.launch(this);}catch(Throwable e){runOnUiThread(()->Toast.makeText(this,"Could not open ChatGPT: "+(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage()),Toast.LENGTH_LONG).show());}finally{runOnUiThread(()->{launch.setEnabled(true);launch.setText("TEACH WITH CHATGPT");refresh(null);});}},"cortex-chatgpt-app-teacher").start();}
    private String statusText(CortexChatGptAppTeacher.ImportResult latest){StringBuilder b=new StringBuilder();b.append("Active policy: ").append(CortexPersonalPolicy.version(this));b.append("\nPending ChatGPT request: ").append(CortexChatGptAppTeacher.pending(this)?"YES":"NO");b.append("\nLifecycle: ").append(CortexPolicyLifecycle.state(this));String reason=CortexPolicyLifecycle.reason(this);if(!reason.isEmpty())b.append(" · ").append(reason);if(CortexChatGptAppTeacher.launchedAt(this)>0)b.append("\nLast launch: ").append(new java.text.SimpleDateFormat("dd MMM · HH:mm:ss",java.util.Locale.getDefault()).format(new java.util.Date(CortexChatGptAppTeacher.launchedAt(this))));if(latest!=null){if(latest.ok)b.append("\nLast import: SUCCESS · ").append(latest.version);else if(!latest.error.isEmpty()&&!"Waiting for ChatGPT policy".equals(latest.error)&&!"No pending ChatGPT teacher request".equals(latest.error))b.append("\nClipboard status: ").append(latest.error);}JSONObject i=CortexTeacherImpact.latest(this);if(i.length()>0)b.append("\nLive comparison candidates: ").append(i.optInt("candidateCount",0)).append(" · Now ").append(i.optInt("beforeNow",0)).append(" → ").append(i.optInt("afterNow",0));b.append("\nPromotion: ").append(CortexPolicyPromotion.status(this).replace("\n"," · "));return b.toString();}
    private static String safeMessage(Throwable t){return t.getMessage()==null?"":t.getMessage();}
}
