package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.util.*;

/** Compact user-owned surface for Current Context: inspect, correct, resume or complete. */
public final class ContextNowActivity extends Activity {
    LinearLayout body;VaultDb db;
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);build();refresh();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){if(db!=null)try{db.close();}catch(Throwable ignored){}db=null;super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(12),dp(18),dp(28));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"brief",null);setContentView(root);CortexUi.fitSystemBars(this,root);}

    void refresh(){if(body==null||db==null)return;body.removeAllViews();try{ContextResolver.refresh(db);}catch(Throwable ignored){}header();ContextStateStore.ContextState current=ContextStateStore.primary(db);if(current==null||!usefulContext(current)){empty();return;}ContextPacketBuilder.Packet p=ContextPacketBuilder.buildLocal(db,420);currentCard(current,p);ArrayList<ContextStateStore.ContextState> stack=ContextStateStore.stack(db,8);ArrayList<ContextStateStore.ContextState> background=new ArrayList<>();for(ContextStateStore.ContextState x:stack)if(x.id!=current.id&&ContextStateStore.ROLE_BACKGROUND.equals(x.role)&&usefulContext(x))background.add(x);if(!background.isEmpty())backgroundSection(background);}

    void header(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());row.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Current Context",27,CortexUi.TEXT);CortexUi.medium(h);tx.addView(h);tx.addView(CortexUi.plain(this,"What Cortex thinks is happening now — and why.",10,CortexUi.MUTED));row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView replay=CortexUi.chip(this,"REPLAY",CortexUi.MUTED,false);replay.setOnClickListener(v->{try{startActivity(new Intent(this,ContextDiagnosticsActivity.class));}catch(Throwable ignored){}});row.addView(replay,new LinearLayout.LayoutParams(-2,dp(34)));body.addView(row);}

    void empty(){LinearLayout c=CortexUi.card(this,20);c.setPadding(dp(15),dp(16),dp(15),dp(16));c.addView(CortexUi.text(this,"Cortex does not have a strong meaningful current context yet. Ambient notifications, screenshots, charging state and app status are not promoted as work by themselves.",13,CortexUi.MUTED));TextView replay=CortexUi.action(this,"Open Context replay",CortexUi.MUTED,false);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(42));rp.setMargins(0,dp(12),0,0);c.addView(replay,rp);replay.setOnClickListener(v->{try{startActivity(new Intent(this,ContextDiagnosticsActivity.class));}catch(Throwable ignored){}});body.addView(c,margin(0,dp(16),0,0));}

    void currentCard(ContextStateStore.ContextState x,ContextPacketBuilder.Packet p){int color=x.stackConfidence>=.82?CortexUi.GREEN:CortexUi.ORANGE;LinearLayout c=CortexUi.card(this,22);c.setPadding(dp(14),dp(14),dp(14),dp(14));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(CortexUi.glyph(this,"brain",color,true),new LinearLayout.LayoutParams(dp(50),dp(50)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(12),0,dp(8),0);top.addView(tx,xp);TextView title=CortexUi.text(this,x.title,18,CortexUi.TEXT);CortexUi.medium(title);tx.addView(title);TextView conf=CortexUi.plain(this,"PRIMARY · "+Math.round(x.stackConfidence*100)+"% confidence",9,color);conf.setPadding(0,dp(4),0,0);tx.addView(conf);c.addView(top);
        if(p!=null&&p.available()){addFact(c,"GOAL",p.goal,CortexUi.YELLOW);addFact(c,"NOW",p.currentActivity,CortexUi.GREEN);addFact(c,"OPEN LOOP",p.openLoops,CortexUi.ORANGE);addFact(c,"NEXT",p.nextStep,CortexUi.RED);if((!p.openLoops.isEmpty()||!p.nextStep.isEmpty())&&!p.resumeProvenance.isEmpty())addProvenance(c,p.resumeProvenance);}
        ContextActionEngine.Move move=ContextActionEngine.primary(db,x.id);if(move.available())addNextMove(c,move);
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setPadding(0,dp(14),0,0);TextView why=CortexUi.action(this,"Why?",CortexUi.MUTED,false);TextView brain=CortexUi.action(this,"Ask Brain",CortexUi.RED,false);actions.addView(why,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(44),1);bp.setMargins(dp(8),0,0,0);actions.addView(brain,bp);c.addView(actions);why.setOnClickListener(v->showWhy());brain.setOnClickListener(v->CortexActionExecutor.openBrain(this,0,"What am I doing and where did I leave off?"));
        LinearLayout control=new LinearLayout(this);control.setOrientation(LinearLayout.HORIZONTAL);control.setPadding(0,dp(8),0,0);TextView sw=CortexUi.action(this,"Switch",CortexUi.ORANGE,false);TextView wrong=CortexUi.action(this,"Not this",CortexUi.RED,false);TextView done=CortexUi.action(this,"Done",CortexUi.GREEN,false);control.addView(sw,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams wp=new LinearLayout.LayoutParams(0,dp(44),1);wp.setMargins(dp(7),0,0,0);control.addView(wrong,wp);LinearLayout.LayoutParams dpv=new LinearLayout.LayoutParams(0,dp(44),1);dpv.setMargins(dp(7),0,0,0);control.addView(done,dpv);c.addView(control);sw.setOnClickListener(v->chooseContext());wrong.setOnClickListener(v->confirmWrong(x));done.setOnClickListener(v->confirmDone(x));body.addView(c,margin(0,dp(15),0,0));}

    void addFact(LinearLayout parent,String label,String value,int color){if(value==null||value.trim().isEmpty())return;TextView l=CortexUi.plain(this,label,9,color);CortexUi.medium(l);l.setPadding(dp(2),dp(13),0,0);parent.addView(l);TextView v=CortexUi.text(this,value,12,CortexUi.TEXT);v.setPadding(dp(2),dp(4),0,0);parent.addView(v);}
    void addProvenance(LinearLayout parent,String provenance){TextView p=CortexUi.plain(this,"Grounded in "+provenance+" · local only",8,CortexUi.FAINT);p.setPadding(dp(2),dp(5),0,0);parent.addView(p);}
    void addNextMove(LinearLayout parent,ContextActionEngine.Move move){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(11),dp(10),dp(11),dp(10));box.setBackground(CortexUi.round(this,Color.argb(18,255,86,54),Color.argb(54,255,86,54),16));TextView k=CortexUi.plain(this,ContextActionEngine.kindLabel(move)+" · GROUNDED NEXT MOVE",8,CortexUi.RED);CortexUi.medium(k);box.addView(k);TextView d=CortexUi.text(this,move.detail,11,CortexUi.TEXT);d.setPadding(0,dp(5),0,0);box.addView(d);if(!move.provenance.isEmpty()){TextView p=CortexUi.plain(this,move.provenance+" · no model inference",8,CortexUi.MUTED);p.setPadding(0,dp(5),0,0);box.addView(p);}TextView go=CortexUi.action(this,move.label,CortexUi.RED,false);LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(42));gp.setMargins(0,dp(9),0,0);box.addView(go,gp);go.setOnClickListener(v->CortexActionExecutor.openBrain(this,0,move.localBrainQuery()));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(13),0,0);parent.addView(box,p);}

    void backgroundSection(List<ContextStateStore.ContextState> xs){TextView h=CortexUi.plain(this,"SUSPENDED / BACKGROUND",9,CortexUi.MUTED);CortexUi.medium(h);h.setPadding(dp(2),dp(20),0,dp(8));body.addView(h);for(ContextStateStore.ContextState x:xs){if(!usefulContext(x))continue;LinearLayout row=CortexUi.card(this,17);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(12),dp(10),dp(10),dp(10));row.addView(CortexUi.glyph(this,"project",CortexUi.ORANGE,false),new LinearLayout.LayoutParams(dp(38),dp(38)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(10),0,dp(6),0);row.addView(tx,xp);TextView t=CortexUi.text(this,x.title,13,CortexUi.TEXT);CortexUi.medium(t);tx.addView(t);ContextActionEngine.Move move=ContextActionEngine.primary(db,x.id);String suffix=move.available()?" · resumable":"";TextView s=CortexUi.plain(this,x.lifecycle+" · "+Math.round(x.stackConfidence*100)+"%"+suffix,9,CortexUi.MUTED);s.setPadding(0,dp(3),0,0);tx.addView(s);TextView resume=CortexUi.chip(this,"RESUME",CortexUi.ORANGE,false);row.addView(resume,new LinearLayout.LayoutParams(-2,dp(32)));row.setOnClickListener(v->{if(ContextControls.switchTo(db,x.id)){CortexHaptics.confirm(row);refresh();}});body.addView(row,margin(0,0,0,dp(8)));}}

    void showWhy(){new AlertDialog.Builder(this).setTitle("Why Cortex chose this context").setMessage(ContextControls.why(db)).setPositiveButton("OK",null).show();}
    void chooseContext(){ArrayList<ContextStateStore.ContextState> xs=ContextStateStore.stack(db,12);ArrayList<ContextStateStore.ContextState> choices=new ArrayList<>();for(ContextStateStore.ContextState x:xs)if(!x.primary()&&usefulContext(x))choices.add(x);if(choices.isEmpty()){Toast.makeText(this,"No meaningful suspended context to switch to yet",Toast.LENGTH_SHORT).show();return;}String[] names=new String[choices.size()];for(int i=0;i<choices.size();i++)names[i]=choices.get(i).title;new AlertDialog.Builder(this).setTitle("Switch current context").setItems(names,(d,w)->{if(ContextControls.switchTo(db,choices.get(w).id))refresh();}).setNegativeButton("Cancel",null).show();}
    void confirmWrong(ContextStateStore.ContextState x){new AlertDialog.Builder(this).setTitle("Cortex got the context wrong?").setMessage(x.title+"\n\nThis suspends the inferred context and teaches Cortex not to immediately choose it again from the same old evidence. It does not mark the work Done or close linked actions.").setNegativeButton("Cancel",null).setPositiveButton("Not this",(d,w)->{if(ContextControls.rejectCurrent(db)){CortexHaptics.confirm(body);refresh();}}).show();}
    void confirmDone(ContextStateStore.ContextState x){int open=ContextOpenLoopResolver.linkedOpenCount(db,x.id);String message=x.title+"\n\nCortex will complete this context and resume the most recent suspended context when possible.";if(open>0)message+="\n\n"+open+" linked open obligation"+(open==1?" remains":"s remain")+" open. Marking the context Done will NOT silently resolve them.";new AlertDialog.Builder(this).setTitle("Mark this context done?").setMessage(message).setNegativeButton("Cancel",null).setPositiveButton("Done",(d,w)->{ContextControls.completeCurrent(db);refresh();}).show();}
    boolean usefulContext(ContextStateStore.ContextState x){if(x==null)return false;String semantic=(x.title+" "+x.summary).trim();return !semantic.isEmpty()&&!CortexTruthPolicy.ambientContext(semantic,"");}
    LinearLayout.LayoutParams margin(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(l,t,r,b);return p;}
}
