package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.util.*;
import java.util.concurrent.*;

/** User-approved corrections only. Raw provider diagnostics remain untouched. */
public class CorrectionLearningActivity extends Activity {
    LinearLayout feed;TextView state;volatile boolean destroyed=false;final ExecutorService worker=Executors.newSingleThreadExecutor();
    static final class Row{long id;String type,title,summary,extracted,source;Row(long i,String ty,String t,String s,String e,String so){id=i;type=ty;title=t;summary=s;extracted=e;source=so;}}
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);build();load();}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}
    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.setPadding(dp(20),dp(14),dp(20),dp(8));TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout hs=new LinearLayout(this);hs.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Corrections & learning",27,CortexUi.TEXT);CortexUi.medium(h);hs.addView(h);hs.addView(CortexUi.text(this,"Correct Cortex explicitly. Only user-approved corrections become learning data.",11,CortexUi.MUTED));head.addView(hs,new LinearLayout.LayoutParams(0,-2,1));root.addView(head);state=CortexUi.plain(this,"Loading…",11,CortexUi.MUTED);state.setPadding(dp(20),0,dp(20),dp(8));root.addView(state);ScrollView sv=new ScrollView(this);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(dp(20),dp(4),dp(20),dp(28));sv.addView(feed);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);}
    void load(){if(destroyed)return;try{worker.execute(()->{ArrayList<Row> rows=new ArrayList<>();int rules=0;VaultDb db=null;try{db=new VaultDb(getApplicationContext());FeatureStore.ensure(db);Cursor c=db.getReadableDatabase().rawQuery("SELECT id,type,title,summary,extracted_text,source FROM knowledge_items WHERE status='analyzed' ORDER BY updated_at DESC LIMIT 80",null);while(c.moveToNext())rows.add(new Row(c.getLong(0),nz(c.getString(1)),nz(c.getString(2)),nz(c.getString(3)),nz(c.getString(4)),nz(c.getString(5))));c.close();Cursor q=db.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM correction_rules",null);if(q.moveToFirst())rules=q.getInt(0);q.close();}finally{if(db!=null)db.close();}final int n=rules;post(()->render(rows,n));});}catch(RejectedExecutionException ignored){}}
    void render(ArrayList<Row> rows,int rules){if(destroyed)return;state.setText(rules+" correction rule"+(rules==1?"":"s")+" stored • choose a recent result to correct");feed.removeAllViews();for(Row r:rows){LinearLayout c=CortexUi.card(this,18);c.setPadding(dp(14),dp(12),dp(14),dp(12));TextView t=CortexUi.text(this,empty(r.title)?"Cortex result #"+r.id:r.title,14,CortexUi.TEXT);CortexUi.medium(t);c.addView(t);String current=!empty(r.summary)?r.summary:r.extracted;TextView p=CortexUi.text(this,clip(current,180),11,CortexUi.MUTED);p.setPadding(0,dp(5),0,0);p.setMaxLines(3);c.addView(p);TextView m=CortexUi.plain(this,r.type+" • "+r.source,9,CortexUi.MUTED);m.setPadding(0,dp(5),0,0);c.addView(m);c.setOnClickListener(v->correct(r));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(8));feed.addView(c,lp);}}
    void correct(Row r){boolean transcript="AUDIO".equals(r.type)&&!empty(r.extracted);String original=transcript?r.extracted:(!empty(r.summary)?r.summary:r.extracted);EditText e=new EditText(this);e.setText(original);e.setMinLines(4);e.setMaxLines(10);e.setGravity(Gravity.TOP);e.setSelection(e.length());CheckBox future=new CheckBox(this);future.setText("Apply this exact transcript replacement in future");future.setTextColor(CortexUi.MUTED);future.setVisibility(transcript&&original.length()<=120?View.VISIBLE:View.GONE);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),0,dp(18),0);box.addView(e);box.addView(future);new AlertDialog.Builder(this).setTitle(transcript?"Correct transcript":"Correct Cortex understanding").setMessage("The original evidence is preserved in diagnostics. This edits the user-facing derived result and records your correction.").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save correction",(d,w)->save(r,original,e.getText().toString().trim(),transcript,future.isChecked())).show();}
    void save(Row r,String original,String corrected,boolean transcript,boolean future){if(corrected.isEmpty()||corrected.equals(original))return;try{worker.execute(()->{VaultDb db=null;boolean ok=false;try{db=new VaultDb(getApplicationContext());FeatureStore.ensure(db);String field=transcript?"extracted_text":"summary";ContentValues v=new ContentValues();v.put(field,corrected);v.put("updated_at",System.currentTimeMillis());ok=db.getWritableDatabase().update("knowledge_items",v,"id=?",new String[]{String.valueOf(r.id)})>0;if(ok){FeatureStore.saveCorrection(db,r.id,field,original,corrected,transcript&&future);CognitiveStore.feedback(db,"memory",r.id,"user_correction",new JSONObject().put("field",field).put("apply_future",transcript&&future).toString(),"correction_ui_001");try{SemanticIndex.indexItem(db,r.id);}catch(Throwable ignored){}}}catch(Throwable ignored){}finally{if(db!=null)db.close();}final boolean saved=ok;post(()->{Toast.makeText(this,saved?"Correction saved · Cortex can learn from it":"Correction could not be saved",Toast.LENGTH_LONG).show();if(saved)load();});});}catch(RejectedExecutionException ignored){}}
    void post(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())r.run();});}String nz(String s){return s==null?"":s.trim();}boolean empty(String s){return s==null||s.trim().isEmpty();}String clip(String s,int n){String x=nz(s);return x.length()<=n?x:x.substring(0,n)+"…";}
}
