package com.kareem.cortex;

import android.content.Context;
import android.content.SharedPreferences;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONArray;
import org.json.JSONObject;
import java.io.File;

/** Interpreted runtime snapshot for the paths that are otherwise invisible in the UI. */
public final class CortexRuntimeDiagnosticV1 {
    public static final String VERSION="cortex_runtime_diagnostic_v3";
    private CortexRuntimeDiagnosticV1(){}

    public static JSONObject snapshot(Context context,VaultDb db)throws Exception{
        JSONObject root=new JSONObject();root.put("version",VERSION);root.put("generated_at_ms",System.currentTimeMillis());
        root.put("analysis",analysis(context,db));root.put("relay_tunnel",relay(db));root.put("cognitive_adjudicator_v2",adjudicator(context,db));root.put("cognitive_v4",cognitive(db));root.put("autonomous_gemini",reasoning(context,db));root.put("recent_internal_transitions",recentDiagnostics(db,160));return root;
    }

    private static JSONObject analysis(Context c,VaultDb db)throws Exception{
        SQLiteDatabase s=db.getReadableDatabase();JSONObject o=new JSONObject();o.put("queue_process_running",AnalysisQueue.isRunning());o.put("pending_count",db.pendingCount());o.put("failed_count",db.failedCount());o.put("cloud_audio_allowed",PrivacyPolicy.canUseCloud(c,"audio"));o.put("gemini_asr_configured",GeminiKeyStore.has(c));o.put("groq_asr_configured",GroqKeyStore.has(c));o.put("audio_by_status",group(s,"SELECT COALESCE(status,''),COUNT(*) FROM knowledge_items WHERE type='AUDIO' GROUP BY status ORDER BY COUNT(*) DESC"));
        Cursor q=s.rawQuery("SELECT id,COALESCE(source,''),COALESCE(title,''),COALESCE(status,''),COALESCE(analysis_error,''),COALESCE(attachment_path,''),LENGTH(COALESCE(extracted_text,'')),LENGTH(COALESCE(summary,'')),created_at,updated_at FROM knowledge_items WHERE type='AUDIO' ORDER BY created_at DESC LIMIT 10",null);JSONArray recent=new JSONArray();try{while(q.moveToNext()){JSONObject x=new JSONObject();long id=q.getLong(0);String path=q.getString(5);File f=path==null||path.isEmpty()?null:new File(path);x.put("item_id",id);x.put("source",q.getString(1));x.put("title",q.getString(2));x.put("status",q.getString(3));x.put("analysis_error",q.getString(4));x.put("attachment_exists",f!=null&&f.exists());x.put("attachment_bytes",f!=null&&f.exists()?f.length():0);x.put("extracted_text_chars",q.getInt(6));x.put("summary_chars",q.getInt(7));x.put("created_at",q.getLong(8));x.put("updated_at",q.getLong(9));x.put("latest_analysis",latestAnalysis(s,id));recent.put(x);}}finally{q.close();}o.put("recent_audio_items",recent);return o;
    }

    private static JSONObject latestAnalysis(SQLiteDatabase s,long itemId)throws Exception{JSONObject o=new JSONObject();Cursor c=s.rawQuery("SELECT COALESCE(engine,''),COALESCE(version,''),created_at,LENGTH(COALESCE(output_json,'')) FROM analyses WHERE item_id=? ORDER BY id DESC LIMIT 1",new String[]{String.valueOf(itemId)});try{if(c.moveToFirst()){o.put("engine",c.getString(0));o.put("version",c.getString(1));o.put("created_at",c.getLong(2));o.put("output_json_chars",c.getInt(3));}else o.put("present",false);}finally{c.close();}return o;}

    private static JSONObject relay(VaultDb db)throws Exception{
        SQLiteDatabase s=db.getReadableDatabase();JSONObject o=new JSONObject();o.put("client_table_present",table(s,"connector_clients"));o.put("event_table_present",table(s,"connector_ingest_events"));if(!table(s,"connector_clients")||!table(s,"connector_ingest_events"))return o;
        Cursor client=s.rawQuery("SELECT connector_id,package_name,COALESCE(capabilities_json,'[]'),source_priority,last_seen_at,last_event_at,accepted_events,rejected_events,updated_at FROM connector_clients ORDER BY updated_at DESC",null);JSONArray clients=new JSONArray();try{while(client.moveToNext()){JSONObject x=new JSONObject();x.put("connector_id",client.getString(0));x.put("package",client.getString(1));x.put("capabilities",jsonOrString(client.getString(2)));x.put("source_priority",client.getInt(3));x.put("last_seen_at",client.getLong(4));x.put("last_event_at",client.getLong(5));x.put("accepted_events",client.getLong(6));x.put("rejected_events",client.getLong(7));x.put("updated_at",client.getLong(8));clients.put(x);}}finally{client.close();}o.put("clients",clients);o.put("state_counts",group(s,"SELECT state,COUNT(*) FROM connector_ingest_events GROUP BY state ORDER BY COUNT(*) DESC"));
        Cursor e=s.rawQuery("SELECT event_id,connector_id,connector_package,source_type,source_package,occurred_at,received_at,state,signal_id,COALESCE(detail,''),updated_at FROM connector_ingest_events ORDER BY received_at DESC LIMIT 30",null);JSONArray events=new JSONArray();try{while(e.moveToNext()){JSONObject x=new JSONObject();x.put("event_id",e.getString(0));x.put("connector_id",e.getString(1));x.put("connector_package",e.getString(2));x.put("source_type",e.getString(3));x.put("source_package",e.getString(4));x.put("occurred_at",e.getLong(5));x.put("received_at",e.getLong(6));x.put("state",e.getString(7));x.put("signal_id",e.getLong(8));x.put("detail",e.getString(9));x.put("updated_at",e.getLong(10));events.put(x);}}finally{e.close();}o.put("recent_events",events);o.put("raw_signals_total",table(s,"raw_signals")?count(s,"SELECT COUNT(*) FROM raw_signals"):0);return o;
    }

    private static JSONObject adjudicator(Context c,VaultDb db)throws Exception{
        CognitiveRunStoreV2.ensure(db);SQLiteDatabase s=db.getReadableDatabase();JSONObject o=new JSONObject();
        JSONObject profile=new JSONObject();profile.put("model",LocalModelManager.MODEL_NAME);profile.put("model_file",LocalModelManager.MODEL_FILE);profile.put("model_present",LocalModelManager.filePresent(c));profile.put("model_verified",LocalModelManager.verified(c));profile.put("runtime_ready",LocalLlmRuntime.ready(c));profile.put("context_size",LocalBrainConfig.CONTEXT_SIZE);profile.put("max_output_tokens",LocalBrainConfig.MAX_OUTPUT_TOKENS);profile.put("temperature",LocalBrainConfig.TEMPERATURE);profile.put("top_p",LocalBrainConfig.TOP_P);profile.put("top_k",LocalBrainConfig.TOP_K);profile.put("threads",LocalBrainConfig.THREADS);profile.put("micro_batch_ms",LocalBrainConfig.MICRO_BATCH_MS);profile.put("max_batch_signals",LocalBrainConfig.MAX_BATCH_SIGNALS);profile.put("accept_local_confidence",LocalBrainConfig.ACCEPT_LOCAL_CONFIDENCE);profile.put("try_deep_confidence",LocalBrainConfig.TRY_DEEP_CONFIDENCE);profile.put("thermal_status",LocalBrainRuntimePolicy.thermalStatus(c));profile.put("thermal_allows_inference",LocalBrainRuntimePolicy.thermalAllowsInference(c));profile.put("cached_model_age_ms",LocalLlmBridge.cachedModelAgeMs());profile.put("cached_model_idle_ms",LocalLlmBridge.cachedIdleMs());o.put("local_brain",profile);
        JSONObject deep=new JSONObject();deep.put("enabled",DeepQwenConfig.enabled(c));deep.put("base_url_configured",!DeepQwenConfig.baseUrl(c).isEmpty());deep.put("model",DeepQwenConfig.MODEL);o.put("optional_deep_qwen",deep);
        if(table(s,"raw_signals")){o.put("cognitive_state_counts",group(s,"SELECT COALESCE(cognitive_state,''),COUNT(*) FROM raw_signals WHERE kind='notification' GROUP BY cognitive_state ORDER BY COUNT(*) DESC"));o.put("signal_family_counts",group(s,"SELECT COALESCE(signal_family,''),COUNT(*) FROM raw_signals WHERE kind='notification' GROUP BY signal_family ORDER BY COUNT(*) DESC"));o.put("signals_without_cognitive_state",count(s,"SELECT COUNT(*) FROM raw_signals WHERE kind='notification' AND COALESCE(cognitive_state,'')=''"));
            Cursor r=s.rawQuery("SELECT id,COALESCE(source,''),COALESCE(signal_family,''),COALESCE(cognitive_state,''),COALESCE(final_reason,''),importance,confidence,thread_id,promoted_item_id,cognitive_run_id,occurred_at,updated_at FROM raw_signals WHERE kind='notification' ORDER BY id DESC LIMIT 40",null);JSONArray a=new JSONArray();try{while(r.moveToNext()){JSONObject x=new JSONObject();x.put("signal_id",r.getLong(0));x.put("source",r.getString(1));x.put("family",r.getString(2));x.put("cognitive_state",r.getString(3));x.put("final_reason",r.getString(4));x.put("importance",r.getInt(5));x.put("confidence",r.getDouble(6));x.put("thread_id",r.getLong(7));x.put("promoted_item_id",r.getLong(8));x.put("cognitive_run_id",r.getLong(9));x.put("occurred_at",r.getLong(10));x.put("updated_at",r.getLong(11));a.put(x);}}finally{r.close();}o.put("recent_notification_outcomes",a);}
        o.put("run_status_counts",group(s,"SELECT status,COUNT(*) FROM cognitive_runs GROUP BY status ORDER BY COUNT(*) DESC"));Cursor cr=s.rawQuery("SELECT id,raw_signal_id,provider,model,started_at,completed_at,latency_ms,COALESCE(disposition,''),confidence,status,COALESCE(error,'') FROM cognitive_runs ORDER BY id DESC LIMIT 40",null);JSONArray runs=new JSONArray();try{while(cr.moveToNext()){JSONObject x=new JSONObject();x.put("run_id",cr.getLong(0));x.put("signal_id",cr.getLong(1));x.put("provider",cr.getString(2));x.put("model",cr.getString(3));x.put("started_at",cr.getLong(4));x.put("completed_at",cr.getLong(5));x.put("latency_ms",cr.getLong(6));x.put("disposition",cr.getString(7));x.put("confidence",cr.getDouble(8));x.put("status",cr.getString(9));x.put("error",cr.getString(10));runs.put(x);}}finally{cr.close();}o.put("recent_cognitive_runs",runs);
        if(table(s,"derived_items")){o.put("derived_kind_counts",group(s,"SELECT kind,COUNT(*) FROM derived_items GROUP BY kind ORDER BY COUNT(*) DESC"));Cursor d=s.rawQuery("SELECT id,kind,state,importance,urgency,priority_score,requires_user_action,requires_follow_up,requires_content_extraction,cognitive_run_id,updated_at FROM derived_items ORDER BY updated_at DESC LIMIT 30",null);JSONArray items=new JSONArray();try{while(d.moveToNext()){JSONObject x=new JSONObject();x.put("derived_id",d.getLong(0));x.put("kind",d.getString(1));x.put("state",d.getString(2));x.put("importance",d.getInt(3));x.put("urgency",d.getInt(4));x.put("priority_score",d.getInt(5));x.put("requires_user_action",d.getInt(6)!=0);x.put("requires_follow_up",d.getInt(7)!=0);x.put("requires_content_extraction",d.getInt(8)!=0);x.put("cognitive_run_id",d.getLong(9));x.put("updated_at",d.getLong(10));items.put(x);}}finally{d.close();}o.put("recent_derived_intelligence",items);}return o;
    }

    private static JSONObject cognitive(VaultDb db)throws Exception{
        SQLiteDatabase s=db.getReadableDatabase();JSONObject o=new JSONObject();o.put("evidence",table(s,"v4_evidence")?count(s,"SELECT COUNT(*) FROM v4_evidence"):0);o.put("memories",table(s,"v4_memories")?count(s,"SELECT COUNT(*) FROM v4_memories"):0);o.put("situations",table(s,"v4_situations")?count(s,"SELECT COUNT(*) FROM v4_situations"):0);
        if(table(s,"v4_situations")){o.put("situation_states",group(s,"SELECT state,COUNT(*) FROM v4_situations GROUP BY state ORDER BY COUNT(*) DESC"));Cursor c=s.rawQuery("SELECT id,kind,state,headline,relevant_from,relevant_until,attention_score,interruption_score,confidence,updated_at FROM v4_situations ORDER BY updated_at DESC LIMIT 20",null);JSONArray a=new JSONArray();try{while(c.moveToNext()){JSONObject x=new JSONObject();x.put("id",c.getString(0));x.put("kind",c.getString(1));x.put("state",c.getString(2));x.put("headline",c.getString(3));x.put("relevant_from",c.getLong(4));x.put("relevant_until",c.getLong(5));x.put("attention_score",c.getDouble(6));x.put("interruption_score",c.getDouble(7));x.put("confidence",c.getDouble(8));x.put("updated_at",c.getLong(9));a.put(x);}}finally{c.close();}o.put("recent_situations",a);}
        CognitivePulseProjectionV4.Snapshot pulse=CognitivePulseProjectionV4.current(db,20);JSONArray p=new JSONArray();if(pulse!=null)for(CognitivePulseProjectionV4.Item item:pulse.items){JSONObject x=new JSONObject();x.put("situation_id",item.situationId);x.put("kind",item.kind);x.put("state",item.state);x.put("headline",item.headline);x.put("attention_score",item.attentionScore);x.put("relevant_until",item.relevantUntil);x.put("new_since_deep_brain",item.newSinceDeepBrain);x.put("deep_brain_rank",item.deepBrainRank);x.put("changed_at",item.changedAt);p.put(x);}o.put("pulse",p);return o;
    }

    private static JSONObject reasoning(Context c,VaultDb db)throws Exception{
        JSONObject o=new JSONObject();long now=System.currentTimeMillis();o.put("enabled",CognitiveAutoReasoningSettingsV4.enabled(c));o.put("gemini_key_configured",GeminiKeyStore.has(c));o.put("effective_model",GeminiModelConfig.generationModel(c));o.put("last_success_at",CognitiveAutoReasoningSettingsV4.lastSuccessAt(c));
        o.put("last_pipeline_state",CognitiveAutoReasoningSettingsV4.lastPipelineState(c));o.put("last_pipeline_reason",CognitiveAutoReasoningSettingsV4.lastPipelineReason(c));o.put("last_pipeline_trigger",CognitiveAutoReasoningSettingsV4.lastPipelineTrigger(c));o.put("last_pipeline_at",CognitiveAutoReasoningSettingsV4.lastPipelineAt(c));
        SharedPreferences pref=c.getSharedPreferences("cortex_auto_reasoning_v4",Context.MODE_PRIVATE);o.put("last_started_at",pref.getLong("last_started",0));o.put("next_allowed_at",pref.getLong("next_allowed",0));o.put("consecutive_failures",pref.getInt("failures",0));o.put("day",pref.getString("day",""));o.put("day_calls",pref.getInt("day_calls",0));o.put("last_started_fingerprint",shortHash(pref.getString("last_started_fp","")));o.put("last_success_fingerprint",shortHash(pref.getString("last_success_fp","")));
        CognitivePulseProjectionV4.Snapshot pulse=CognitivePulseProjectionV4.current(db,20);CognitiveAutoReasoningPolicyV4.Decision decision=CognitiveAutoReasoningPolicyV4.evaluate(pulse,now);o.put("policy_should_run_now",decision.shouldRun);o.put("policy_urgent",decision.urgent);o.put("policy_reason",decision.reason);o.put("policy_fresh_count",decision.freshCount);o.put("policy_max_attention",decision.maxAttention);o.put("policy_fingerprint",shortHash(decision.fingerprint));if(decision.shouldRun){CognitiveAutoReasoningSettingsV4.Gate gate=CognitiveAutoReasoningSettingsV4.canStart(c,decision.fingerprint,decision.urgent,now);o.put("runtime_gate_allowed",gate.allowed);o.put("runtime_gate_reason",gate.reason);}else{o.put("runtime_gate_allowed",false);o.put("runtime_gate_reason","policy_did_not_request_run");}
        CognitiveReasoningRunStoreV4.Latest latest=CognitiveReasoningRunStoreV4.latest(db);if(latest!=null){JSONObject r=new JSONObject();r.put("provider",latest.provider);r.put("model",latest.model);r.put("trigger",latest.trigger);r.put("state",latest.state);r.put("started_at",latest.startedAt);r.put("completed_at",latest.completedAt);r.put("duration_ms",latest.durationMs);r.put("error",latest.error);o.put("latest_run",r);}else o.put("latest_run",JSONObject.NULL);return o;
    }

    private static JSONArray recentDiagnostics(VaultDb db,int limit)throws Exception{DiagnosticsLog.ensure(db);JSONArray out=new JSONArray();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,created_at,severity,component,event,status,error_class,error_code,item_id,thread_id,signal_id,job_id,model_run_id,latency_ms,COALESCE(metadata_json,'{}') FROM diagnostics_log ORDER BY id DESC LIMIT "+Math.max(1,Math.min(500,limit)),null);try{while(c.moveToNext()){JSONObject x=new JSONObject();x.put("id",c.getLong(0));x.put("created_at",c.getLong(1));x.put("severity",c.getString(2));x.put("component",c.getString(3));x.put("event",c.getString(4));x.put("status",c.getString(5));x.put("error_class",c.getString(6));x.put("error_code",c.getString(7));x.put("item_id",c.getLong(8));x.put("thread_id",c.getLong(9));x.put("signal_id",c.getLong(10));x.put("job_id",c.getLong(11));x.put("model_run_id",c.getLong(12));x.put("latency_ms",c.getLong(13));x.put("metadata",jsonOrString(c.getString(14)));out.put(x);}}finally{c.close();}return out;}
    private static JSONArray group(SQLiteDatabase s,String sql)throws Exception{JSONArray out=new JSONArray();Cursor c=s.rawQuery(sql,null);try{while(c.moveToNext()){JSONObject x=new JSONObject();x.put("key",c.isNull(0)?"":c.getString(0));x.put("count",c.getLong(1));out.put(x);}}finally{c.close();}return out;}
    private static long count(SQLiteDatabase s,String sql){Cursor c=s.rawQuery(sql,null);try{return c.moveToFirst()?c.getLong(0):0;}finally{c.close();}}
    private static boolean table(SQLiteDatabase s,String name){Cursor c=s.rawQuery("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1",new String[]{name});try{return c.moveToFirst();}finally{c.close();}}
    private static Object jsonOrString(String raw){String x=raw==null?"":raw.trim();if(x.isEmpty())return new JSONObject();try{if(x.startsWith("["))return new JSONArray(x);if(x.startsWith("{"))return new JSONObject(x);}catch(Throwable ignored){}return x;}
    private static String shortHash(String x){String s=x==null?"":x.trim();return s.length()<=16?s:s.substring(0,16);}
}
