package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** Non-programmer audit dashboard: immediate tap acknowledgement, current work, progress, evidence and user feedback. */
public class CortexAuditActivity extends Activity {
    VaultDb db;LinearLayout root,testsBox;TextView headline,current,timing,counts,recent;ProgressBar progress;Button start,feedback,export,stop,finishNow;Handler h=new Handler(Looper.getMainLooper());String lastTests="";
    int bg=Color.rgb(11,12,14),surface=Color.rgb(24,26,30),text=Color.rgb(245,244,240),muted=Color.rgb(156,159,168),accent=Color.rgb(232,177,72),ok=Color.rgb(120,205,150),warn=Color.rgb(238,184,94),danger=Color.rgb(246,124,118),border=Color.rgb(47,50,57);
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}GradientDrawable round(int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setReadable(v,s);return v;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);CortexAuditStore.ensure(db);build();refresh();}
    @Override protected void onResume(){super.onResume();h.post(tick);}
    @Override protected void onPause(){super.onPause();h.removeCallbacks(tick);}Runnable tick=new Runnable(){public void run(){if(!isFinishing()){refresh();h.postDelayed(this,1200);}}};

    void build(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(32));root.setBackgroundColor(bg);sv.addView(root);TextView t=tv("FULL CORTEX AUDIT",27,text);t.setTypeface(null,1);root.addView(t);TextView sub=tv("One test campaign for the whole app: safe automatic checks now + a 72-hour low-impact soak while you use Cortex normally.",13,muted);sub.setPadding(0,dp(4),0,dp(14));root.addView(sub);
        headline=card("OVERALL STATUS");progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(1000);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(9));pp.setMargins(dp(4),-dp(4),dp(4),dp(12));root.addView(progress,pp);current=card("WHAT CORTEX IS DOING NOW");timing=card("AUDIT WINDOW");counts=card("TEST COUNTS");
        start=button("START 72-HOUR FULL APP TEST");start.setOnClickListener(v->startAudit());root.addView(start,lp());feedback=button("ADD FEEDBACK / REPORT SOMETHING SLOW");feedback.setOnClickListener(v->feedback());root.addView(feedback,lp());export=button("EXPORT FULL DEBUG NOW");export.setOnClickListener(v->{export.setText("BUILDING FULL DEBUG…");export.setEnabled(false);DebugExporter.exportAndShare(this,db);h.postDelayed(()->{export.setEnabled(true);export.setText("EXPORT FULL DEBUG NOW");},2500);});root.addView(export,lp());stop=button("STOP AUDIT");stop.setOnClickListener(v->stopAudit());root.addView(stop,lp());finishNow=button("FINISH + SUMMARIZE NOW");finishNow.setOnClickListener(v->finishNow());root.addView(finishNow,lp());
        recent=card("RECENT AUDIT EVENTS");TextView all=tv("ALL FEATURES / TESTS",11,accent);all.setTypeface(null,1);all.setPadding(dp(2),dp(12),0,dp(7));root.addView(all);testsBox=new LinearLayout(this);testsBox.setOrientation(LinearLayout.VERTICAL);root.addView(testsBox);
        TextView note=tv("Safe by design: the audit never creates fake calendar events, sends messages, restores over your live Vault, or uploads a personal screenshot just to make a test pass. Those checks are kept as explicit NOT RUN items with the reason and prerequisites. You can close Cortex; WorkManager keeps the multi-day audit scheduled.",12,muted);note.setPadding(dp(4),dp(12),dp(4),0);root.addView(note);setContentView(sv);}

    TextView card(String label){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackground(round(surface,border,18));TextView l=tv(label,11,accent);l.setTypeface(null,1);c.addView(l);TextView x=tv("",13,text);x.setPadding(0,dp(6),0,0);c.addView(x);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));root.addView(c,p);return x;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(text);b.setAllCaps(false);b.setBackground(round(surface,border,16));return b;}LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,0,0,dp(9));return p;}

    void startAudit(){start.setEnabled(false);start.setText("TAP RECEIVED • STARTING…");headline.setText("Your tap was registered immediately. Cortex is creating the persistent test plan now…");current.setText("Preparing WorkManager jobs and the audit database. This should only take a moment.");new Thread(()->{try{long id=CortexAuditScheduler.start(this);runOnUiThread(()->{start.setEnabled(true);Toast.makeText(this,"Full Cortex audit started • run #"+id,Toast.LENGTH_LONG).show();refresh();});}catch(Exception e){runOnUiThread(()->{start.setEnabled(true);start.setText("START 72-HOUR FULL APP TEST");headline.setText("Could not start audit: "+e.getMessage());});}},"CortexAuditStart").start();}
    void stopAudit(){CortexAuditStore.Run r=CortexAuditStore.active(db);if(r==null)return;new AlertDialog.Builder(this).setTitle("Stop full audit?").setMessage("Collected results will stay in the debug export, but the remaining soak samples will be canceled.").setPositiveButton("Stop",(d,w)->{CortexAuditScheduler.stop(this,r.id);refresh();}).setNegativeButton("Keep running",null).show();}
    void finishNow(){CortexAuditStore.Run r=CortexAuditStore.active(db);if(r==null)return;new AlertDialog.Builder(this).setTitle("Finish audit now?").setMessage("This will take a final sample and summarize what has been observed so far. Tests that needed more time will be warnings rather than hidden.").setPositiveButton("Finish now",(d,w)->{CortexAuditScheduler.finalizeNow(this,r.id);current.setText("Final checkpoint queued…");}).setNegativeButton("Continue 72 hours",null).show();}
    void feedback(){CortexAuditStore.Run r=CortexAuditStore.latest(db);if(r==null){Toast.makeText(this,"Start an audit first so your feedback is attached to a run",Toast.LENGTH_LONG).show();return;}final EditText e=new EditText(this);e.setHint("Example: I tapped Analyze and nothing changed for 8 seconds…");e.setMinLines(3);e.setTextColor(text);e.setHintTextColor(muted);e.setPadding(dp(12),dp(8),dp(12),dp(8));new AlertDialog.Builder(this).setTitle("Add audit feedback").setMessage("Write exactly what felt slow, confusing, wrong, or surprisingly good. It will be timestamped inside the debug package.").setView(e).setPositiveButton("Save",(d,w)->{String x=e.getText().toString().trim();if(!x.isEmpty()){try{CortexAuditStore.log(db,r.id,"user","user_feedback","user_note",x,new JSONObject().put("app_version",getPackageManager().getPackageInfo(getPackageName(),0).versionName));Toast.makeText(this,"Feedback attached to audit",Toast.LENGTH_SHORT).show();refresh();}catch(Exception ex){Toast.makeText(this,"Could not save feedback: "+ex.getMessage(),Toast.LENGTH_LONG).show();}}}).setNegativeButton("Cancel",null).show();}

    void refresh(){CortexAuditStore.Run r=CortexAuditStore.latest(db);if(r==null){headline.setText("No full-app audit has been started yet.");current.setText("Press START once. The button acknowledges immediately, then the automatic checks run in the background.");timing.setText("Default test window: 72 hours. You can finish early if needed.");counts.setText(CortexAuditStore.defs().size()+" registered checks covering app, Vault, AI, Visual Intelligence, capture, privacy, integrations and diagnostics.");progress.setProgress(0);start.setEnabled(true);start.setText("START 72-HOUR FULL APP TEST");feedback.setEnabled(false);stop.setVisibility(View.GONE);finishNow.setVisibility(View.GONE);recent.setText("No audit events yet.");renderTests(0);return;}int pc=r.progress();progress.setProgress(pc*10);headline.setText(statusHuman(r.status)+" • "+pc+"%\n"+empty(r.summary,"Audit in progress"));current.setText(empty(r.phase,"Audit")+"\n"+empty(r.currentTest,"Waiting for next checkpoint")+(r.error.isEmpty()?"":"\nLast error: "+r.error));String end=new SimpleDateFormat("dd MMM • HH:mm",Locale.getDefault()).format(new Date(r.targetEndAt));String started=new SimpleDateFormat("dd MMM • HH:mm",Locale.getDefault()).format(new Date(r.startedAt));timing.setText("Started: "+started+"\nTarget finish: "+end+"\n"+remaining(r));JSONObject sc=CortexAuditStore.statusCounts(db,r.id);counts.setText("PASS "+sc.optInt("pass",0)+" • WARN "+sc.optInt("warn",0)+" • FAIL "+sc.optInt("fail",0)+"\nRUNNING "+sc.optInt("running",0)+" • OBSERVING "+sc.optInt("observing",0)+" • NOT RUN "+sc.optInt("not_run",0)+" • PENDING "+sc.optInt("pending",0)+"\nSoak samples saved: "+CortexAuditStore.sampleCount(db,r.id));boolean active=r.active();start.setEnabled(!active);start.setText(active?"AUDIT IS RUNNING":"complete".equals(r.status)?"START ANOTHER 72-HOUR AUDIT":"START NEW 72-HOUR FULL APP TEST");feedback.setEnabled(true);stop.setVisibility(active?View.VISIBLE:View.GONE);finishNow.setVisibility(active?View.VISIBLE:View.GONE);recent.setText(events(r.id));renderTests(r.id);}
    void renderTests(long runId){JSONArray a=runId>0?CortexAuditStore.testsJson(db,runId):CortexAuditStore.catalogJson();String sig=a.toString();if(sig.equals(lastTests))return;lastTests=sig;testsBox.removeAllViews();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String status=runId>0?o.optString("status","pending"):o.optString("mode","");LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(13),dp(11),dp(13),dp(11));c.setBackground(round(surface,statusColor(status),16));TextView t=tv((i+1)+". "+o.optString("title",o.optString("test_key","Test")),13,text);t.setTypeface(null,1);c.addView(t);TextView st=tv(status.toUpperCase(Locale.ROOT)+" • "+o.optString("feature",""),10,statusColor(status));st.setPadding(0,dp(4),0,0);c.addView(st);String detail=runId>0?o.optString("detail",""):o.optString("description","");if(!detail.isEmpty()){TextView d=tv(detail,11,muted);d.setPadding(0,dp(5),0,0);d.setMaxLines(5);c.addView(d);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(7));testsBox.addView(c,p);}}
    String events(long id){JSONArray a=CortexAuditStore.eventsJson(db,id,12);if(a.length()==0)return "Waiting for first event…";StringBuilder b=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;long at=o.optLong("created_at",0);String tm=at>0?new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(at)):"";b.append(tm).append(" • ").append(o.optString("component","")).append(" • ").append(o.optString("detail",o.optString("event",""))).append('\n');}return b.toString().trim();}
    int statusColor(String s){if("pass".equals(s))return ok;if("warn".equals(s)||"observing".equals(s))return warn;if("fail".equals(s))return danger;if("running".equals(s))return accent;return border;}
    String statusHuman(String s){if("complete".equals(s))return"AUDIT COMPLETE";if("canceled".equals(s))return"AUDIT STOPPED";if("soaking".equals(s))return"AUDIT OBSERVING";if("finalizing".equals(s))return"FINALIZING";if("running".equals(s)||"starting".equals(s))return"AUDIT RUNNING";return s.toUpperCase(Locale.ROOT);}
    String remaining(CortexAuditStore.Run r){if("complete".equals(r.status))return"Completed.";if("canceled".equals(r.status))return"Stopped early; collected evidence is preserved.";long d=r.targetEndAt-System.currentTimeMillis();if(d<=0)return"Final checkpoint due now.";long h=d/3600000,mins=(d%3600000)/60000;return"About "+h+"h "+mins+"m remaining in the soak window.";}
    String empty(String s,String f){return s==null||s.trim().isEmpty()?f:s.trim();}
}
