package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** Non-programmer audit dashboard: immediate acknowledgement, current test, progress, evidence and feedback. */
public class CortexAuditActivity extends Activity {
    VaultDb db;LinearLayout root,testsBox;TextView headline,current,timing,counts,recent;ProgressBar progress;Button start,feedback,export,stop;Handler h=new Handler(Looper.getMainLooper());String lastTests="";
    int bg=Color.rgb(11,12,14),surface=Color.rgb(24,26,30),text=Color.rgb(245,244,240),muted=Color.rgb(156,159,168),accent=Color.rgb(232,177,72),ok=Color.rgb(120,205,150),warn=Color.rgb(238,184,94),danger=Color.rgb(246,124,118),border=Color.rgb(47,50,57);
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}GradientDrawable round(int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setReadable(v,s);return v;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);CortexAuditStore.ensure(db);build();refresh();}
    @Override protected void onResume(){super.onResume();h.post(tick);}
    @Override protected void onPause(){super.onPause();h.removeCallbacks(tick);}Runnable tick=new Runnable(){public void run(){if(!isFinishing()){refresh();h.postDelayed(this,1000);}}};

    void build(){ScrollView sv=new ScrollView(this);root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(16),dp(16),dp(16),dp(32));root.setBackgroundColor(bg);sv.addView(root);TextView t=tv("FULL CORTEX AUDIT",27,text);t.setTypeface(null,1);root.addView(t);TextView sub=tv("Run the whole safe diagnostic suite now. Most checks should finish in minutes, not days. Anything that cannot be safely executed is still documented as NOT RUN with the reason.",13,muted);sub.setPadding(0,dp(4),0,dp(14));root.addView(sub);
        headline=card("OVERALL STATUS");progress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);progress.setMax(1000);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(9));pp.setMargins(dp(4),-dp(4),dp(4),dp(12));root.addView(progress,pp);current=card("WHAT CORTEX IS DOING NOW");timing=card("TEST TIMING");counts=card("TEST COUNTS");
        start=button("RUN FULL APP TEST NOW");start.setOnClickListener(v->startAudit());root.addView(start,lp());feedback=button("ADD FEEDBACK / REPORT SOMETHING SLOW");feedback.setOnClickListener(v->feedback());root.addView(feedback,lp());export=button("EXPORT FULL DEBUG NOW");export.setOnClickListener(v->{export.setText("BUILDING FULL DEBUG…");export.setEnabled(false);DebugExporter.exportAndShare(this,db);h.postDelayed(()->{export.setEnabled(true);export.setText("EXPORT FULL DEBUG NOW");},2500);});root.addView(export,lp());stop=button("STOP TEST");stop.setOnClickListener(v->stopAudit());root.addView(stop,lp());
        recent=card("RECENT AUDIT EVENTS");TextView all=tv("ALL FEATURES / TESTS",11,accent);all.setTypeface(null,1);all.setPadding(dp(2),dp(12),0,dp(7));root.addView(all);testsBox=new LinearLayout(this);testsBox.setOrientation(LinearLayout.VERTICAL);root.addView(testsBox);
        TextView note=tv("Safe by design: Cortex will not create fake calendar events, send messages, restore over the live Vault, or upload a personal screenshot just to make a test pass. Those capabilities are still inventoried in the final debug with exact state and why they were not executed. Long-term soak testing can be a separate optional mode later; this button does not wait 72 hours.",12,muted);note.setPadding(dp(4),dp(12),dp(4),0);root.addView(note);setContentView(sv);}

    TextView card(String label){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackground(round(surface,border,18));TextView l=tv(label,11,accent);l.setTypeface(null,1);c.addView(l);TextView x=tv("",13,text);x.setPadding(0,dp(6),0,0);c.addView(x);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));root.addView(c,p);return x;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(text);b.setAllCaps(false);b.setBackground(round(surface,border,16));return b;}LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,0,0,dp(9));return p;}

    void startAudit(){start.setEnabled(false);start.setText("TAP RECEIVED • STARTING…");headline.setText("Tap registered. Cortex is preparing the full test suite now…");current.setText("Creating the audit plan and starting the first test.");new Thread(()->{try{long id=CortexAuditScheduler.start(this);runOnUiThread(()->{Toast.makeText(this,"Full Cortex test started • run #"+id,Toast.LENGTH_LONG).show();refresh();});}catch(Exception e){runOnUiThread(()->{start.setEnabled(true);start.setText("RUN FULL APP TEST NOW");headline.setText("Could not start audit: "+e.getMessage());});}},"CortexAuditStart").start();}
    void stopAudit(){CortexAuditStore.Run r=CortexAuditStore.active(db);if(r==null)return;new AlertDialog.Builder(this).setTitle("Stop full test?").setMessage("Everything already tested will stay in the debug export.").setPositiveButton("Stop",(d,w)->{CortexAuditScheduler.stop(this,r.id);refresh();}).setNegativeButton("Keep running",null).show();}
    void feedback(){CortexAuditStore.Run r=CortexAuditStore.latest(db);if(r==null){Toast.makeText(this,"Start a test first so your feedback is attached to it",Toast.LENGTH_LONG).show();return;}final EditText e=new EditText(this);e.setHint("Example: I tapped Analyze and nothing changed for 8 seconds…");e.setMinLines(3);e.setTextColor(text);e.setHintTextColor(muted);e.setPadding(dp(12),dp(8),dp(12),dp(8));new AlertDialog.Builder(this).setTitle("Add test feedback").setMessage("Write exactly what felt slow, confusing, wrong, or surprisingly good. It will be timestamped in the debug package.").setView(e).setPositiveButton("Save",(d,w)->{String x=e.getText().toString().trim();if(!x.isEmpty()){try{CortexAuditStore.log(db,r.id,"user","user_feedback","user_note",x,new JSONObject().put("app_version",getPackageManager().getPackageInfo(getPackageName(),0).versionName));Toast.makeText(this,"Feedback attached",Toast.LENGTH_SHORT).show();refresh();}catch(Exception ex){Toast.makeText(this,"Could not save feedback: "+ex.getMessage(),Toast.LENGTH_LONG).show();}}}).setNegativeButton("Cancel",null).show();}

    void refresh(){CortexAuditStore.Run r=CortexAuditStore.latest(db);if(r==null){headline.setText("No full-app test has been run yet.");current.setText("Press RUN once. The button responds immediately and every safe automatic test starts now.");timing.setText("Expected: usually a few minutes. Slow provider/model checks can take longer, and the current test is always shown above.");counts.setText(CortexAuditStore.defs().size()+" registered checks covering app, Vault, AI, Visual Intelligence, capture, privacy, integrations and diagnostics.");progress.setProgress(0);start.setEnabled(true);start.setText("RUN FULL APP TEST NOW");feedback.setEnabled(false);stop.setVisibility(View.GONE);recent.setText("No audit events yet.");renderTests(0);return;}int pc=r.progress();progress.setProgress(pc*10);headline.setText(statusHuman(r.status)+" • "+pc+"%\n"+empty(r.summary,"Test in progress"));current.setText(empty(r.phase,"Audit")+"\n"+empty(r.currentTest,"Waiting for next check")+(r.error.isEmpty()?"":"\nLast error: "+r.error));String started=new SimpleDateFormat("dd MMM • HH:mm:ss",Locale.getDefault()).format(new Date(r.startedAt));long end=r.completedAt>0?r.completedAt:System.currentTimeMillis();timing.setText("Started: "+started+"\nElapsed: "+elapsed(end-r.startedAt)+(r.completedAt>0?"\nCompleted: "+new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(r.completedAt)):""));JSONObject sc=CortexAuditStore.statusCounts(db,r.id);counts.setText("PASS "+sc.optInt("pass",0)+" • WARN "+sc.optInt("warn",0)+" • FAIL "+sc.optInt("fail",0)+"\nRUNNING "+sc.optInt("running",0)+" • OBSERVING "+sc.optInt("observing",0)+" • NOT RUN "+sc.optInt("not_run",0)+" • PENDING "+sc.optInt("pending",0)+"\nDiagnostic snapshots saved: "+CortexAuditStore.sampleCount(db,r.id));boolean active=r.active();start.setEnabled(!active);start.setText(active?"FULL TEST IS RUNNING":"RUN FULL APP TEST AGAIN");feedback.setEnabled(true);stop.setVisibility(active?View.VISIBLE:View.GONE);recent.setText(events(r.id));renderTests(r.id);}
    void renderTests(long runId){JSONArray a=runId>0?CortexAuditStore.testsJson(db,runId):CortexAuditStore.catalogJson();String sig=a.toString();if(sig.equals(lastTests))return;lastTests=sig;testsBox.removeAllViews();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;String status=runId>0?o.optString("status","pending"):o.optString("mode","");LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(13),dp(11),dp(13),dp(11));c.setBackground(round(surface,statusColor(status),16));TextView t=tv((i+1)+". "+o.optString("title",o.optString("test_key","Test")),13,text);t.setTypeface(null,1);c.addView(t);TextView st=tv(status.toUpperCase(Locale.ROOT)+" • "+o.optString("feature",""),10,statusColor(status));st.setPadding(0,dp(4),0,0);c.addView(st);String detail=runId>0?o.optString("detail",""):o.optString("description","");if(!detail.isEmpty()){TextView d=tv(detail,11,muted);d.setPadding(0,dp(5),0,0);d.setMaxLines(5);c.addView(d);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(7));testsBox.addView(c,p);}}
    String events(long id){JSONArray a=CortexAuditStore.eventsJson(db,id,12);if(a.length()==0)return "Waiting for first event…";StringBuilder b=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);if(o==null)continue;long at=o.optLong("created_at",0);String tm=at>0?new SimpleDateFormat("HH:mm:ss",Locale.getDefault()).format(new Date(at)):"";b.append(tm).append(" • ").append(o.optString("component","")).append(" • ").append(o.optString("detail",o.optString("event",""))).append('\n');}return b.toString().trim();}
    int statusColor(String s){if("pass".equals(s))return ok;if("warn".equals(s)||"observing".equals(s))return warn;if("fail".equals(s))return danger;if("running".equals(s))return accent;return border;}
    String statusHuman(String s){if("complete".equals(s))return"TEST COMPLETE";if("canceled".equals(s))return"TEST STOPPED";if("finalizing".equals(s))return"FINALIZING";if("running".equals(s)||"starting".equals(s)||"soaking".equals(s))return"TEST RUNNING";return s.toUpperCase(Locale.ROOT);}
    String elapsed(long ms){if(ms<0)ms=0;long sec=ms/1000;long min=sec/60;sec%=60;if(min<60)return min+"m "+sec+"s";long hr=min/60;min%=60;return hr+"h "+min+"m";}
    String empty(String s,String f){return s==null||s.trim().isEmpty()?f:s.trim();}
}
