package com.kareem.cortex;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.content.pm.ResolveInfo;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.media.AudioManager;
import android.media.MediaRecorder;
import android.net.Uri;
import android.os.*;
import android.provider.CalendarContract;
import android.provider.MediaStore;
import android.speech.tts.TextToSpeech;
import androidx.core.app.NotificationCompat;
import androidx.core.content.FileProvider;
import org.json.*;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.zip.*;

/**
 * One-shot live verification for Cortex release testing.
 * Runtime/special Android permissions are granted by the shell launcher before this class runs.
 * The runner never sends email/SMS, never places a call, and rolls back synthetic restore state.
 */
public final class CortexAutopilotLiveRunner {
    public interface Progress{void update(int percent,String phase,String detail);}
    private static final String PASS="PASS",FAIL="FAIL",BLOCKED="BLOCKED",WARN="WARN";
    private CortexAutopilotLiveRunner(){}

    public static JSONObject run(Context context,boolean fullSoak,Progress progress)throws Exception{
        Context c=context.getApplicationContext();long started=System.currentTimeMillis();JSONArray tests=new JSONArray();
        CortexLiveTestResultStore.clearAll(c);
        phase(progress,2,"Autopilot","Starting live verification");
        runOne(c,tests,"notification_capture","Real notification capture",()->notification(c));phase(progress,8,"Autopilot","Notification route checked");
        runOne(c,tests,"mic_asr","Real microphone phrase + ASR",()->microphoneAsr(c));phase(progress,16,"Autopilot","Microphone + ASR checked");
        runOne(c,tests,"calendar_write","Reversible Calendar create/delete",()->calendar(c));phase(progress,22,"Autopilot","Calendar write/read/delete checked");
        runOne(c,tests,"backup_external","Backup external document write",()->externalBackup(c));phase(progress,28,"Autopilot","External backup checked");
        runOne(c,tests,"restore_rollback","Synthetic restore rollback",()->restoreRollback(c));phase(progress,34,"Autopilot","Restore rollback checked");
        runOne(c,tests,"screenshot_import","Live screenshot-folder import",()->screenshot(c));phase(progress,40,"Autopilot","Screenshot importer checked");
        runOne(c,tests,"local_qwen","Real Local Qwen inference",()->qwen(c));phase(progress,47,"Autopilot","Local model checked");
        runOne(c,tests,"strong_vision","Real Strong Vision provider call",()->vision(c));phase(progress,54,"Autopilot","Strong Vision checked");
        runOne(c,tests,"email_handoff","Email draft UI handoff",()->handoff(c,new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:cortex-autopilot@example.invalid")),"email"));
        runOne(c,tests,"sms_handoff","SMS draft UI handoff",()->handoff(c,new Intent(Intent.ACTION_SENDTO,Uri.parse("smsto:0000000000")),"sms"));
        runOne(c,tests,"dialer_handoff","Dialer UI handoff",()->handoff(c,new Intent(Intent.ACTION_DIAL,Uri.parse("tel:0000000000")),"dialer"));phase(progress,60,"Autopilot","External handoff contracts checked");
        if(fullSoak){runOne(c,tests,"soak_30m","30-minute stability soak",()->soak(c,progress));}else add(c,tests,"soak_30m","30-minute stability soak",BLOCKED,"Full soak disabled for this run",new JSONObject().put("full_soak",false));
        phase(progress,100,"Autopilot","Live verification complete");
        int pass=0,fail=0,blocked=0,warn=0;for(int i=0;i<tests.length();i++){String s=tests.optJSONObject(i).optString("status");if(PASS.equals(s))pass++;else if(FAIL.equals(s))fail++;else if(BLOCKED.equals(s))blocked++;else warn++;}
        return new JSONObject().put("schema","CORTEX_AUTOPILOT_LIVE_V1").put("started_at_ms",started).put("finished_at_ms",System.currentTimeMillis()).put("duration_ms",System.currentTimeMillis()-started).put("full_soak",fullSoak).put("tests",tests).put("summary",new JSONObject().put("pass",pass).put("fail",fail).put("blocked",blocked).put("warn",warn).put("overall",fail>0?FAIL:(blocked+warn)>0?"INCOMPLETE":PASS));
    }

    private interface Work{Outcome run()throws Exception;}
    private static final class Outcome{final String status,detail;final JSONObject evidence;Outcome(String s,String d,JSONObject e){status=s;detail=d;evidence=e==null?new JSONObject():e;}static Outcome pass(String d,JSONObject e){return new Outcome(PASS,d,e);}static Outcome fail(String d,JSONObject e){return new Outcome(FAIL,d,e);}static Outcome blocked(String d,JSONObject e){return new Outcome(BLOCKED,d,e);}static Outcome warn(String d,JSONObject e){return new Outcome(WARN,d,e);}}
    private static void runOne(Context c,JSONArray tests,String key,String name,Work w)throws Exception{try{Outcome o=w.run();add(c,tests,key,name,o.status,o.detail,o.evidence);}catch(Throwable e){add(c,tests,key,name,FAIL,e.getClass().getSimpleName()+": "+safe(e.getMessage()),new JSONObject().put("exception",e.getClass().getName()).put("message",safe(e.getMessage())));}}
    private static void add(Context c,JSONArray tests,String key,String name,String status,String detail,JSONObject evidence)throws Exception{CortexLiveTestResultStore.record(c,key,status,detail);JSONObject stored=CortexLiveTestResultStore.get(c,key);tests.put(new JSONObject().put("key",key).put("name",name).put("status",status).put("detail",detail).put("evidence",evidence==null?new JSONObject():evidence).put("ledger",stored==null?JSONObject.NULL:stored));}

    private static Outcome notification(Context c)throws Exception{
        if(Build.VERSION.SDK_INT>=33&&c.checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)return Outcome.blocked("POST_NOTIFICATIONS is not granted",new JSONObject());
        if(!CortexAuditSoakWorker.notificationListenerEnabled(c))return Outcome.blocked("Cortex Notification Listener is not enabled",new JSONObject());
        String marker="CORTEX_AUTOPILOT_NOTIFICATION_"+System.currentTimeMillis();NotificationManager nm=(NotificationManager)c.getSystemService(Context.NOTIFICATION_SERVICE);String channel="cortex-testlab";if(Build.VERSION.SDK_INT>=26)nm.createNotificationChannel(new NotificationChannel(channel,"Cortex Test Lab",NotificationManager.IMPORTANCE_DEFAULT));Notification n=new NotificationCompat.Builder(c,channel).setSmallIcon(android.R.drawable.stat_notify_more).setContentTitle("Cortex autopilot test").setContentText(marker).setAutoCancel(true).build();int nid=9631;nm.notify(nid,n);boolean found=false;long deadline=SystemClock.elapsedRealtime()+9000;try{while(SystemClock.elapsedRealtime()<deadline&&!found){Thread.sleep(300);VaultDb db=new VaultDb(c);try{for(PhoneContextStore.Event e:PhoneContextStore.recent(db,System.currentTimeMillis()-20000,300))if((e.text!=null&&e.text.contains(marker))||(e.metadataJson!=null&&e.metadataJson.contains(marker))){found=true;break;}}finally{db.close();}}}finally{nm.cancel(nid);}JSONObject e=new JSONObject().put("marker",marker).put("listener_enabled",true).put("found_in_phone_context",found);return found?Outcome.pass("Local test notification traversed the real NotificationListener into Cortex phone-context evidence",e):Outcome.fail("Notification posted but its marker did not reach Cortex phone-context evidence",e);
    }

    private static Outcome microphoneAsr(Context c)throws Exception{
        if(c.checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED)return Outcome.blocked("RECORD_AUDIO is not granted",new JSONObject());
        if(!PrivacyPolicy.canUseCloud(c,"audio"))return Outcome.blocked("Audio privacy is not AI allowed",new JSONObject().put("privacy",PrivacyPolicy.mode(c,"audio")));
        if(!GeminiKeyStore.has(c)&&!GroqKeyStore.has(c))return Outcome.blocked("No Gemini/Groq ASR provider is configured",new JSONObject());
        CountDownLatch init=new CountDownLatch(1);TextToSpeech[] holder=new TextToSpeech[1];int[] initStatus={TextToSpeech.ERROR};Handler main=new Handler(Looper.getMainLooper());main.post(()->holder[0]=new TextToSpeech(c,s->{initStatus[0]=s;init.countDown();}));
        if(!init.await(12,TimeUnit.SECONDS)||holder[0]==null||initStatus[0]!=TextToSpeech.SUCCESS){if(holder[0]!=null)holder[0].shutdown();return Outcome.blocked("Android TTS could not initialize for hands-free microphone loopback",new JSONObject().put("tts_status",initStatus[0]));}
        TextToSpeech tts=holder[0];int lang=tts.setLanguage(Locale.US);if(lang==TextToSpeech.LANG_MISSING_DATA||lang==TextToSpeech.LANG_NOT_SUPPORTED){tts.shutdown();return Outcome.blocked("English TTS voice is unavailable",new JSONObject().put("tts_language_status",lang));}
        AudioManager am=(AudioManager)c.getSystemService(Context.AUDIO_SERVICE);int oldVolume=am.getStreamVolume(AudioManager.STREAM_MUSIC),maxVolume=am.getStreamMaxVolume(AudioManager.STREAM_MUSIC);File f=new File(c.getCacheDir(),"cortex_autopilot_mic_"+System.currentTimeMillis()+".m4a");MediaRecorder r=Build.VERSION.SDK_INT>=31?new MediaRecorder(c):new MediaRecorder();
        try{
            am.setStreamVolume(AudioManager.STREAM_MUSIC,Math.max(oldVolume,Math.max(1,(int)Math.round(maxVolume*.72))),0);
            r.setAudioSource(MediaRecorder.AudioSource.MIC);r.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);r.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);r.setAudioSamplingRate(16000);r.setAudioEncodingBitRate(64000);r.setOutputFile(f.getAbsolutePath());r.prepare();r.start();Thread.sleep(600);
            main.post(()->tts.speak("Cortex live audio test forty two",TextToSpeech.QUEUE_FLUSH,null,"cortex-autopilot-tts"));Thread.sleep(7000);try{r.stop();}catch(Throwable stop){return Outcome.fail("Microphone recorder could not finish the TTS loopback capture",new JSONObject().put("error",safe(stop.getMessage())));}
        }finally{try{r.release();}catch(Throwable ignored){}try{tts.stop();tts.shutdown();}catch(Throwable ignored){}try{am.setStreamVolume(AudioManager.STREAM_MUSIC,oldVolume,0);}catch(Throwable ignored){}}
        if(!f.exists()||f.length()<700){try{f.delete();}catch(Throwable ignored){}return Outcome.fail("Microphone produced no usable loopback audio",new JSONObject().put("bytes",f.exists()?f.length():0));}
        long now=System.currentTimeMillis();KnowledgeItem item=new KnowledgeItem(-1,"AUDIO","autopilot_live_test","Autopilot microphone loopback","","","","Voice & Audio","autopilot,live",f.getAbsolutePath(),"queued",Fingerprint.text("autopilot-mic|"+now),"","{\"autopilot\":true}",now,now);CountDownLatch done=new CountDownLatch(1);AnalysisResult[] rr=new AnalysisResult[1];Exception[] err=new Exception[1];AudioAnalyzer.analyze(c,item,new AudioAnalyzer.Callback(){public void ok(AnalysisResult x){rr[0]=x;done.countDown();}public void fail(Exception x){err[0]=x;done.countDown();}});boolean callback=done.await(150,TimeUnit.SECONDS);long bytes=f.length();try{f.delete();}catch(Throwable ignored){}
        if(!callback)return Outcome.fail("Real ASR did not return within 150 seconds",new JSONObject().put("audio_bytes",bytes));if(err[0]!=null)return Outcome.fail("Real ASR rejected/failed the loopback audio: "+safe(err[0].getMessage()),new JSONObject().put("audio_bytes",bytes).put("error",safe(err[0].getMessage())));
        String transcript=rr[0]==null?"":safe(rr[0].extractedText).trim();String low=transcript.toLowerCase(Locale.ROOT);boolean cortex=low.contains("cortex"),fortyTwo=low.contains("forty two")||low.contains("42")||low.contains("forty-two");JSONObject e=new JSONObject().put("audio_bytes",bytes).put("transcript",transcript).put("engine",rr[0]==null?"":safe(rr[0].engine)).put("cortex_found",cortex).put("forty_two_found",fortyTwo).put("coverage",rr[0]==null?0:rr[0].audioCoverage);return cortex&&fortyTwo?Outcome.pass("Real speaker→microphone→ASR loopback recognized the prompted marker",e):Outcome.fail("ASR completed but did not recognize both Cortex and forty two",e);
    }

    private static Outcome calendar(Context c)throws Exception{
        if(c.checkSelfPermission(Manifest.permission.READ_CALENDAR)!=PackageManager.PERMISSION_GRANTED||c.checkSelfPermission(Manifest.permission.WRITE_CALENDAR)!=PackageManager.PERMISSION_GRANTED)return Outcome.blocked("Calendar read/write permissions are not granted",new JSONObject());
        Cursor q=null;long cal=-1,event=-1;Uri eventUri=null;String marker="CORTEX_AUTOPILOT_EVENT_"+System.currentTimeMillis();boolean verified=false;int deleted=0;try{q=c.getContentResolver().query(CalendarContract.Calendars.CONTENT_URI,new String[]{CalendarContract.Calendars._ID,CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL},CalendarContract.Calendars.VISIBLE+"=1",null,null);while(q!=null&&q.moveToNext())if(q.getInt(1)>=CalendarContract.Calendars.CAL_ACCESS_CONTRIBUTOR){cal=q.getLong(0);break;}if(cal<0)return Outcome.blocked("No writable visible calendar exists",new JSONObject());ContentValues v=new ContentValues();v.put(CalendarContract.Events.CALENDAR_ID,cal);v.put(CalendarContract.Events.TITLE,marker);v.put(CalendarContract.Events.DESCRIPTION,"Cortex autopilot reversible test");long st=System.currentTimeMillis()+3600000L;v.put(CalendarContract.Events.DTSTART,st);v.put(CalendarContract.Events.DTEND,st+60000L);v.put(CalendarContract.Events.EVENT_TIMEZONE,TimeZone.getDefault().getID());eventUri=c.getContentResolver().insert(CalendarContract.Events.CONTENT_URI,v);if(eventUri==null)throw new IOException("Calendar insert returned null");event=Long.parseLong(eventUri.getLastPathSegment());Cursor r=c.getContentResolver().query(eventUri,new String[]{CalendarContract.Events.TITLE},null,null,null);try{verified=r!=null&&r.moveToFirst()&&marker.equals(r.getString(0));}finally{if(r!=null)r.close();}deleted=c.getContentResolver().delete(eventUri,null,null);JSONObject e=new JSONObject().put("calendar_id",cal).put("event_id",event).put("verified",verified).put("deleted",deleted);return verified&&deleted==1?Outcome.pass("Marked Calendar event was created, read back and deleted immediately",e):Outcome.fail("Calendar reversible transaction did not verify and delete cleanly",e);}finally{if(q!=null)q.close();if(eventUri!=null&&deleted!=1)try{c.getContentResolver().delete(eventUri,null,null);}catch(Throwable ignored){}}
    }

    private static Outcome externalBackup(Context c)throws Exception{
        if(Build.VERSION.SDK_INT<29)return Outcome.blocked("MediaStore.Downloads external-document test requires Android 10+",new JSONObject().put("sdk",Build.VERSION.SDK_INT));ContentValues v=new ContentValues();String name="Cortex-Autopilot-Backup-"+System.currentTimeMillis()+".zip";v.put(MediaStore.MediaColumns.DISPLAY_NAME,name);v.put(MediaStore.MediaColumns.MIME_TYPE,"application/zip");v.put(MediaStore.MediaColumns.RELATIVE_PATH,android.os.Environment.DIRECTORY_DOWNLOADS+"/CortexTestLab");v.put(MediaStore.MediaColumns.IS_PENDING,1);Uri collection=MediaStore.Downloads.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY),u=c.getContentResolver().insert(collection,v);if(u==null)return Outcome.fail("Could not create a temporary external Downloads document",new JSONObject());VaultDb db=null;try{db=new VaultDb(c);int memories=BackupExporter.write(c,db,u);ContentValues ready=new ContentValues();ready.put(MediaStore.MediaColumns.IS_PENDING,0);c.getContentResolver().update(u,ready,null,null);BackupImporter.Inspection i=BackupImporter.inspect(c,u);JSONObject e=new JSONObject().put("uri",u.toString()).put("name",name).put("exported_memories",memories).put("valid",i.valid).put("entries",i.entries).put("memories",i.memories).put("attachments",i.attachments).put("checked_bytes",i.bytes);return i.valid&&i.entries>0?Outcome.pass("Real Cortex backup was written through external MediaStore and read back by BackupImporter",e):Outcome.fail("External backup was written but failed BackupImporter validation",e);}finally{if(db!=null)db.close();try{c.getContentResolver().delete(u,null,null);}catch(Throwable ignored){}}
    }

    private static Outcome restoreRollback(Context c)throws Exception{
        File f=new File(c.getCacheDir(),"cortex_autopilot_restore_"+System.currentTimeMillis()+".zip");createSyntheticBackup(f);Uri u=FileProvider.getUriForFile(c,c.getPackageName()+".feedback.files",f);VaultDb db=new VaultDb(c);boolean tx=false;try{BackupImporter.Inspection pre=BackupImporter.inspect(c,u);if(!pre.valid)return Outcome.fail("Synthetic restore backup failed preflight",new JSONObject().put("detail",pre.detail));SQLiteDatabase sql=db.getWritableDatabase();sql.beginTransaction();tx=true;int restored=BackupImporter.restore(c,db,u);Cursor q=sql.rawQuery("SELECT COUNT(*) FROM knowledge_items WHERE raw_text LIKE '%CORTEX_AUTOPILOT_RESTORE_TEST%'",null);long inside=q.moveToFirst()?q.getLong(0):0;q.close();sql.endTransaction();tx=false;Cursor a=sql.rawQuery("SELECT COUNT(*) FROM knowledge_items WHERE raw_text LIKE '%CORTEX_AUTOPILOT_RESTORE_TEST%'",null);long residue=a.moveToFirst()?a.getLong(0):0;a.close();JSONObject e=new JSONObject().put("restore_returned",restored).put("inside_transaction",inside).put("residue_after_rollback",residue).put("preflight_valid",pre.valid);return restored==1&&inside==1&&residue==0?Outcome.pass("Real restore path created the synthetic row inside a transaction and rollback left zero residue",e):Outcome.fail("Synthetic restore rollback invariants failed",e);}finally{if(tx)try{db.getWritableDatabase().endTransaction();}catch(Throwable ignored){}db.close();try{f.delete();}catch(Throwable ignored){}}
    }

    private static Outcome screenshot(Context c)throws Exception{Uri tree=ScreenshotIngestor.tree(c);if(tree==null)return Outcome.blocked("No persisted screenshot-folder SAF grant exists",new JSONObject().put("note","Android does not allow inventing a persistable SAF tree grant silently"));VaultDb db=new VaultDb(c);try{ScreenshotIngestor.Result r=ScreenshotIngestor.scan(c,db,1);JSONObject e=new JSONObject().put("tree",tree.toString()).put("found",r.totalFound).put("imported",r.imported).put("duplicates",r.duplicates).put("failed",r.failed).put("possible_evidence_side_effect",r.imported>0);return r.failed==0?Outcome.pass("Real screenshot-folder importer scanned at most one image",e):Outcome.fail("Screenshot-folder importer reported a failure",e);}finally{db.close();}}

    private static Outcome qwen(Context c)throws Exception{if(!LocalModelManager.verified(c)||!LocalLlmRuntime.ready(c))return Outcome.blocked("Local Qwen model/runtime is not verified and ready",new JSONObject().put("verified",LocalModelManager.verified(c)).put("runtime_ready",LocalLlmRuntime.ready(c)));long t=SystemClock.elapsedRealtime();LocalLlmBridge.CompletionResult r=LocalLlmBridge.completeCached(LocalModelManager.modelFile(c).getAbsolutePath(),"Reply exactly CORTEX_LIVE_QWEN_OK. /no_think","You are a deterministic test. Reply exactly CORTEX_LIVE_QWEN_OK. /no_think",24);String text=safe(r.getText());long ms=SystemClock.elapsedRealtime()-t;boolean ok=text.toUpperCase(Locale.ROOT).contains("CORTEX_LIVE_QWEN_OK");JSONObject e=new JSONObject().put("text",text).put("elapsed_ms",ms).put("tokens_generated",r.getTokensGenerated()).put("tokens_per_second",r.getTokensPerSecond()).put("cache_hit",r.getCacheHit());return ok?Outcome.pass("Actual on-device Qwen completion returned the deterministic marker",e):Outcome.fail("Local Qwen completed but missed the deterministic marker",e);}

    private static Outcome vision(Context c)throws Exception{ExternalBrainProvider.HealthReport h=GeminiVisionAnalyzer.healthCheck(c);JSONObject e=new JSONObject().put("configured",h.configured).put("ok",h.ok).put("provider",h.provider).put("model",h.model).put("status",h.status).put("error",h.error).put("response_preview",h.responsePreview).put("http",h.httpCode).put("latency_ms",h.latencyMs);if(!h.configured)return Outcome.blocked("Strong Vision provider is not configured",e);return h.ok?Outcome.pass("Generated non-private image traversed the production Strong Vision provider",e):Outcome.fail("Strong Vision production health check failed: "+h.status,e);}

    private static Outcome handoff(Context c,Intent intent,String kind)throws Exception{ResolveInfo r=c.getPackageManager().resolveActivity(intent,PackageManager.MATCH_DEFAULT_ONLY);JSONObject e=new JSONObject().put("kind",kind).put("action",safe(intent.getAction())).put("data",intent.getData()==null?"":intent.getData().toString()).put("resolved",r!=null).put("execution","safe handoff contract only; no send/call is performed");if(r!=null)e.put("handler",r.activityInfo.packageName+"/"+r.activityInfo.name);return r!=null?Outcome.pass("Android resolved a concrete "+kind+" handoff target; Cortex did not send or call",e):Outcome.fail("No Android handler resolved for "+kind,e);}

    private static Outcome soak(Context c,Progress progress)throws Exception{
        VaultDb db=new VaultDb(c);try{CortexAuditScheduler.SoakState before=CortexAuditScheduler.soakState(db);long prior=before==null?0:before.runId;long id=CortexAuditScheduler.startSoak(c);long deadline=SystemClock.elapsedRealtime()+42L*60L*1000L;while(SystemClock.elapsedRealtime()<deadline){CortexAuditScheduler.SoakState s=CortexAuditScheduler.soakState(db);if(s!=null&&s.runId==id){long elapsed=Math.max(0,System.currentTimeMillis()-s.startedAt),remaining=Math.max(0,s.targetEndAt-System.currentTimeMillis());int pct=60+(int)Math.min(38,elapsed*38/(30L*60L*1000L));phase(progress,pct,"30-minute stability soak","run "+id+" · "+Math.round(elapsed/60000.0)+" min elapsed · "+Math.round(remaining/60000.0)+" min target remaining");if("complete".equals(s.status)){int samples=CortexAuditStore.sampleCount(db,id),fails=CortexAuditStore.countTests(db,id,"fail"),warn=CortexAuditStore.countTests(db,id,"warn");long duration=s.completedAt>0?s.completedAt-s.startedAt:System.currentTimeMillis()-s.startedAt;JSONObject e=new JSONObject().put("run_id",id).put("previous_soak_id",prior).put("duration_ms",duration).put("samples",samples).put("failures",fails).put("warnings",warn).put("summary",s.summary);return duration>=25L*60L*1000L&&samples>=3&&fails==0?Outcome.pass("Real 30-minute WorkManager stability soak completed with no diagnostic failures",e):Outcome.fail("Stability soak completed but duration/sample/failure invariants were not clean",e);}if("canceled".equals(s.status))return Outcome.fail("Stability soak was canceled",new JSONObject().put("run_id",id));}Thread.sleep(15000);}return Outcome.fail("30-minute stability soak did not reach a terminal state within 42 minutes",new JSONObject().put("run_id",id));}finally{db.close();}}

    private static void createSyntheticBackup(File f)throws Exception{try(ZipOutputStream z=new ZipOutputStream(new BufferedOutputStream(new FileOutputStream(f)))){z.putNextEntry(new ZipEntry("memories.jsonl"));String line=new JSONObject().put("id",1).put("type","TEXT").put("source","synthetic_test").put("title","Autopilot restore test").put("raw_text","CORTEX_AUTOPILOT_RESTORE_TEST").put("extracted_text","").put("summary","Autopilot restore test").put("category","Diagnostics").put("tags","test").put("attachment_in_backup","").put("status","analyzed").put("metadata_json","{\"synthetic\":true}").put("created_at",System.currentTimeMillis()).put("updated_at",System.currentTimeMillis()).toString()+"\n";z.write(line.getBytes(java.nio.charset.StandardCharsets.UTF_8));z.closeEntry();z.putNextEntry(new ZipEntry("manifest.json"));z.write("{\"format\":\"CORTEX_BACKUP_V1\",\"memory_count\":1}".getBytes(java.nio.charset.StandardCharsets.UTF_8));z.closeEntry();}}
    private static void phase(Progress p,int pct,String phase,String detail){if(p!=null)try{p.update(Math.max(0,Math.min(100,pct)),phase,detail);}catch(Throwable ignored){}}
    private static String safe(String s){return s==null?"":s;}
}
