package com.kareem.cortex;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.media.MediaRecorder;
import android.net.Uri;
import android.os.*;
import android.provider.CalendarContract;
import android.view.*;
import android.widget.*;
import androidx.core.app.NotificationCompat;
import java.io.*;
import java.util.*;
import java.util.concurrent.*;

/** Explicit-confirmation tests for paths that require real Android interaction or temporary external state. */
public final class CortexProtectedLiveTestsActivity extends Activity {
    LinearLayout body;TextView status;final ExecutorService worker=Executors.newSingleThreadExecutor();volatile boolean destroyed=false;MediaRecorder recorder;File audioFile;
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);getWindow().addFlags(WindowManager.LayoutParams.FLAG_KEEP_SCREEN_ON);build();}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();releaseRecorder();super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),dp(32));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());h.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout hs=new LinearLayout(this);hs.setOrientation(LinearLayout.VERTICAL);TextView title=CortexUi.plain(this,"Protected live tests",25,CortexUi.TEXT);CortexUi.medium(title);hs.addView(title);hs.addView(CortexUi.text(this,"These tests touch real Android surfaces. Nothing sends email/SMS or places a call automatically. Calendar write is created with a test marker and deleted immediately.",11,CortexUi.MUTED));h.addView(hs,new LinearLayout.LayoutParams(0,-2,1));body.addView(h);status=CortexUi.text(this,"Choose a live test. Each risky/reversible mutation asks again before execution.",11,CortexUi.MUTED);status.setPadding(0,dp(14),0,dp(14));body.addView(status);
        row("Real notification capture","Posts one local Cortex test notification, waits for Notification Listener evidence, then cancels it.","Run notification test",v->confirm("Run real notification test?","A local Cortex notification will appear briefly.",this::notificationTest));
        row("Real microphone + ASR","Records five seconds from the microphone. Say: “Cortex live audio test forty two”. The file is deleted after transcription.","Run 5-second voice test",v->confirm("Run microphone test?","Microphone audio will be sent only according to your current Cortex audio privacy/provider settings.",this::microphoneTest));
        row("Reversible Calendar write","Creates a clearly marked event in the first writable calendar, verifies it, then deletes it immediately.","Run Calendar create/delete",v->confirm("Run reversible Calendar test?","The test event may briefly sync to your calendar provider before Cortex deletes it.",this::calendarTest));
        row("Internal backup + restore preflight","Builds a real Cortex backup into app-private test storage, validates it with BackupImporter, then deletes the file. No user data is restored.","Run backup/preflight",v->backupPreflight());
        row("Synthetic restore rollback","Creates a one-memory synthetic Cortex backup, runs the real restore function inside a SQLite rollback transaction, checks the restored row, then rolls it back.","Run restore rollback",v->confirm("Run restore rollback test?","Only a synthetic memory is restored and the database transaction is deliberately rolled back.",this::syntheticRestore));
        row("Live screenshot-folder scan","Scans at most one image from the connected screenshot folder using the real importer. This CAN add one screenshot to Evidence.","Import one screenshot",v->confirm("Import one real screenshot?","This test can permanently add one screenshot to Cortex Evidence. Continue only if that is okay.",this::screenshotScan));
        row("Local Qwen real inference","If the model is verified, runs an actual deterministic local completion and records latency.","Run Local Qwen",v->localQwen());
        row("Strong Vision provider","Opens Cortex's real external-model check so Gemini/vision can be tested with its normal privacy boundary.","Open model check",v->open(ExternalModelCheckActivity.class));
        row("Email draft handoff","Opens an unsent draft to a reserved invalid test address. Cortex never presses Send.","Open email draft",v->draft(new Intent(Intent.ACTION_SENDTO,Uri.parse("mailto:cortex-live-test@example.invalid")).putExtra(Intent.EXTRA_SUBJECT,"Cortex protected test draft").putExtra(Intent.EXTRA_TEXT,"CORTEX_TEST_ONLY — do not send.")));
        row("SMS draft handoff","Opens an unsent draft to a synthetic number. Cortex never presses Send.","Open SMS draft",v->draft(new Intent(Intent.ACTION_SENDTO,Uri.parse("smsto:0000000000")).putExtra("sms_body","CORTEX_TEST_ONLY — do not send.")));
        row("Dialer handoff","Opens the dialer with a synthetic number. Cortex never presses Call.","Open dialer",v->draft(new Intent(Intent.ACTION_DIAL,Uri.parse("tel:0000000000"))));
        row("30-minute stability soak","Opens the capability matrix where the real soak can be started/stopped and its samples are retained.","Open stability soak",v->open(CapabilityMatrixActivity.class));
        setContentView(root);CortexUi.fitSystemBars(this,root);}

    void notificationTest(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){result("Notification test BLOCKED · notification runtime permission is missing");return;}if(!CortexAuditSoakWorker.notificationListenerEnabled(this)){result("Notification test BLOCKED · enable Cortex Notification Access first");return;}String marker="CORTEX_LIVE_NOTIFICATION_"+System.currentTimeMillis();NotificationManager nm=(NotificationManager)getSystemService(NOTIFICATION_SERVICE);String channel="cortex-testlab";if(Build.VERSION.SDK_INT>=26)nm.createNotificationChannel(new NotificationChannel(channel,"Cortex Test Lab",NotificationManager.IMPORTANCE_DEFAULT));Notification n=new NotificationCompat.Builder(this,channel).setSmallIcon(android.R.drawable.stat_notify_more).setContentTitle("Cortex live test").setContentText(marker).setAutoCancel(true).build();int nid=9417;nm.notify(nid,n);result("Notification posted · waiting for Cortex listener…");new Handler(Looper.getMainLooper()).postDelayed(()->{boolean found=false;VaultDb db=null;try{db=new VaultDb(this);for(PhoneContextStore.Event e:PhoneContextStore.recent(db,System.currentTimeMillis()-15000,200))if((e.text!=null&&e.text.contains(marker))||(e.metadata!=null&&e.metadata.contains(marker))){found=true;break;}}catch(Throwable ignored){}finally{if(db!=null)db.close();nm.cancel(nid);}result(found?"PASS · real notification reached Cortex phone-context evidence":"FAIL · notification appeared but Cortex listener evidence did not contain the marker");},3500);}

    void microphoneTest(){if(checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){result("Microphone test BLOCKED · grant microphone permission first");return;}if(!GeminiKeyStore.has(this)&&!GroqKeyStore.has(this)){result("Microphone test BLOCKED · configure Gemini or Groq ASR first");return;}try{audioFile=new File(getCacheDir(),"cortex_live_audio_"+System.currentTimeMillis()+".m4a");recorder=Build.VERSION.SDK_INT>=31?new MediaRecorder(this):new MediaRecorder();recorder.setAudioSource(MediaRecorder.AudioSource.MIC);recorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);recorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);recorder.setAudioSamplingRate(16000);recorder.setAudioEncodingBitRate(64000);recorder.setOutputFile(audioFile.getAbsolutePath());recorder.prepare();recorder.start();result("Recording 5s · say: Cortex live audio test forty two");new Handler(Looper.getMainLooper()).postDelayed(this::finishMicrophone,5000);}catch(Throwable e){releaseRecorder();result("FAIL · microphone start: "+msg(e));}}
    void finishMicrophone(){try{if(recorder!=null)recorder.stop();}catch(Throwable ignored){}releaseRecorder();File f=audioFile;if(f==null||!f.exists()||f.length()<500){result("FAIL · microphone produced no usable audio file");return;}result("Audio captured · running real ASR…");long now=System.currentTimeMillis();KnowledgeItem item=new KnowledgeItem(-1,"AUDIO","diagnostic_live_test","Live microphone test","","","","Voice & Audio","live,test",f.getAbsolutePath(),"queued",Fingerprint.text("live-audio|"+now),"","{\"protected_live_test\":true}",now,now);AudioAnalyzer.analyze(this,item,new AudioAnalyzer.Callback(){public void ok(AnalysisResult r){String x=(r.extractedText==null?"":r.extractedText).trim();boolean pass=x.toLowerCase(Locale.ROOT).contains("cortex")||x.contains("42")||x.toLowerCase(Locale.ROOT).contains("forty two");result((pass?"PASS":"WARN")+" · ASR transcript: "+x);try{f.delete();}catch(Throwable ignored){}}public void fail(Exception e){result("FAIL/BLOCKED · ASR: "+msg(e));try{f.delete();}catch(Throwable ignored){}}});}

    void calendarTest(){if(checkSelfPermission(Manifest.permission.READ_CALENDAR)!=PackageManager.PERMISSION_GRANTED||checkSelfPermission(Manifest.permission.WRITE_CALENDAR)!=PackageManager.PERMISSION_GRANTED){result("Calendar test BLOCKED · grant read/write Calendar permission first");return;}runWorker(()->{Cursor c=null;long calId=-1,eventId=-1;String marker="CORTEX_TEST_EVENT_"+System.currentTimeMillis();try{c=getContentResolver().query(CalendarContract.Calendars.CONTENT_URI,new String[]{CalendarContract.Calendars._ID,CalendarContract.Calendars.CALENDAR_ACCESS_LEVEL},CalendarContract.Calendars.VISIBLE+"=1",null,null);while(c!=null&&c.moveToNext()){if(c.getInt(1)>=CalendarContract.Calendars.CAL_ACCESS_CONTRIBUTOR){calId=c.getLong(0);break;}}if(calId<0)throw new IllegalStateException("No writable visible calendar");ContentValues v=new ContentValues();v.put(CalendarContract.Events.CALENDAR_ID,calId);v.put(CalendarContract.Events.TITLE,marker);v.put(CalendarContract.Events.DESCRIPTION,"Cortex protected live test; delete immediately");long start=System.currentTimeMillis()+3600000L;v.put(CalendarContract.Events.DTSTART,start);v.put(CalendarContract.Events.DTEND,start+60000L);v.put(CalendarContract.Events.EVENT_TIMEZONE,TimeZone.getDefault().getID());Uri u=getContentResolver().insert(CalendarContract.Events.CONTENT_URI,v);if(u==null)throw new IOException("Calendar insert returned null");eventId=Long.parseLong(u.getLastPathSegment());Cursor q=getContentResolver().query(u,new String[]{CalendarContract.Events.TITLE},null,null,null);boolean verified=q!=null&&q.moveToFirst()&&marker.equals(q.getString(0));if(q!=null)q.close();int deleted=getContentResolver().delete(u,null,null);final boolean pass=verified&&deleted==1;final long id=eventId;post(()->result((pass?"PASS":"FAIL")+" · reversible Calendar event id="+id+" verified="+verified+" deleted="+deleted));}catch(Throwable e){if(eventId>0)try{getContentResolver().delete(Uri.withAppendedPath(CalendarContract.Events.CONTENT_URI,String.valueOf(eventId)),null,null);}catch(Throwable ignored){}post(()->result("FAIL · Calendar create/delete: "+msg(e)));}finally{if(c!=null)c.close();}});}

    void backupPreflight(){runWorker(()->{VaultDb db=null;File f=null;try{db=new VaultDb(getApplicationContext());File dir=new File(getFilesDir(),"debug_exports");dir.mkdirs();f=new File(dir,"cortex_protected_backup_test.zip");if(f.exists())f.delete();Uri u=androidx.core.content.FileProvider.getUriForFile(this,getPackageName()+".feedback.files",f);int memories=BackupExporter.write(this,db,u);BackupImporter.Inspection i=BackupImporter.inspect(this,u);final long bytes=f.length();final boolean ok=i.valid&&bytes>0;final int m=memories;final String detail=i.human();post(()->result((ok?"PASS":"FAIL")+" · backup bytes="+bytes+" · exported memories="+m+"\n"+detail));}catch(Throwable e){post(()->result("FAIL · backup/preflight: "+msg(e)));}finally{if(db!=null)db.close();if(f!=null)try{f.delete();}catch(Throwable ignored){}}});}

    void syntheticRestore(){runWorker(()->{VaultDb db=null;File f=null;boolean tx=false;try{db=new VaultDb(getApplicationContext());File dir=new File(getFilesDir(),"debug_exports");dir.mkdirs();f=new File(dir,"cortex_synthetic_restore_test.zip");createSyntheticBackup(f);Uri u=androidx.core.content.FileProvider.getUriForFile(this,getPackageName()+".feedback.files",f);BackupImporter.Inspection check=BackupImporter.inspect(this,u);if(!check.valid)throw new IOException(check.detail);android.database.sqlite.SQLiteDatabase sql=db.getWritableDatabase();sql.beginTransaction();tx=true;int restored=BackupImporter.restore(this,db,u);Cursor q=sql.rawQuery("SELECT COUNT(*) FROM knowledge_items WHERE source='backup_restore' AND raw_text LIKE '%CORTEX_SYNTHETIC_RESTORE_TEST%'",null);long rows=q.moveToFirst()?q.getLong(0):0;q.close();sql.endTransaction();tx=false;Cursor after=sql.rawQuery("SELECT COUNT(*) FROM knowledge_items WHERE raw_text LIKE '%CORTEX_SYNTHETIC_RESTORE_TEST%'",null);long residue=after.moveToFirst()?after.getLong(0):0;after.close();final boolean ok=restored==1&&rows==1&&residue==0;post(()->result((ok?"PASS":"FAIL")+" · restore returned="+restored+" · inside_tx="+rows+" · residue_after_rollback="+residue));}catch(Throwable e){post(()->result("FAIL · synthetic restore: "+msg(e)));}finally{if(tx&&db!=null)try{db.getWritableDatabase().endTransaction();}catch(Throwable ignored){}if(db!=null)db.close();if(f!=null)try{f.delete();}catch(Throwable ignored){}}});}

    void screenshotScan(){Uri tree=ScreenshotIngestor.tree(this);if(tree==null){result("Screenshot test BLOCKED · connect screenshot folder first");return;}runWorker(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());ScreenshotIngestor.Result r=ScreenshotIngestor.scan(this,db,1);final String x="Screenshot scan · found="+r.totalFound+" imported="+r.imported+" duplicate="+r.duplicates+" failed="+r.failed;post(()->result(r.failed==0?"PASS · "+x:"FAIL · "+x));}catch(Throwable e){post(()->result("FAIL · screenshot scan: "+msg(e)));}finally{if(db!=null)db.close();}});}

    void localQwen(){if(!LocalModelManager.verified(this)){result("Local Qwen BLOCKED · install/verify model first");return;}runWorker(()->{try{long t=SystemClock.elapsedRealtime();LocalLlmBridge.CompletionResult r=LocalLlmBridge.completeCached(LocalModelManager.modelFile(this).getAbsolutePath(),"Reply exactly CORTEX_LIVE_QWEN_OK. /no_think","You are a deterministic test. Reply exactly CORTEX_LIVE_QWEN_OK. /no_think",24);String x=r.getText()==null?"":r.getText();boolean ok=x.toUpperCase(Locale.ROOT).contains("CORTEX_LIVE_QWEN_OK");long ms=SystemClock.elapsedRealtime()-t;post(()->result((ok?"PASS":"FAIL")+" · Local Qwen "+ms+"ms · "+x));}catch(Throwable e){post(()->result("FAIL · Local Qwen: "+msg(e)));}});}

    void createSyntheticBackup(File f)throws Exception{try(java.util.zip.ZipOutputStream z=new java.util.zip.ZipOutputStream(new BufferedOutputStream(new FileOutputStream(f)))){z.putNextEntry(new java.util.zip.ZipEntry("memories.jsonl"));String line=new org.json.JSONObject().put("id",1).put("type","TEXT").put("source","synthetic_test").put("title","Synthetic restore test").put("raw_text","CORTEX_SYNTHETIC_RESTORE_TEST").put("extracted_text","").put("summary","Synthetic restore test").put("category","Diagnostics").put("tags","test").put("attachment_in_backup","").put("status","analyzed").put("metadata_json","{\"synthetic\":true}").put("created_at",System.currentTimeMillis()).put("updated_at",System.currentTimeMillis()).toString()+"\n";z.write(line.getBytes(java.nio.charset.StandardCharsets.UTF_8));z.closeEntry();z.putNextEntry(new java.util.zip.ZipEntry("manifest.json"));z.write("{\"format\":\"CORTEX_BACKUP_V1\",\"memory_count\":1}".getBytes(java.nio.charset.StandardCharsets.UTF_8));z.closeEntry();}}

    void row(String title,String detail,String action,View.OnClickListener l){LinearLayout card=CortexUi.card(this,18);card.setPadding(dp(14),dp(12),dp(14),dp(12));TextView t=CortexUi.text(this,title,13,CortexUi.TEXT);CortexUi.medium(t);card.addView(t);TextView d=CortexUi.text(this,detail,11,CortexUi.MUTED);d.setPadding(0,dp(5),0,dp(8));card.addView(d);TextView a=CortexUi.action(this,action,CortexUi.ACCENT,true);a.setOnClickListener(l);card.addView(a,new LinearLayout.LayoutParams(-1,dp(44)));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,0,0,dp(8));body.addView(card,lp);}
    void confirm(String title,String message,Runnable yes){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setNegativeButton("Cancel",null).setPositiveButton("Run test",(d,w)->yes.run()).show();}
    void result(String s){post(()->{status.setText(s);Toast.makeText(this,s.length()>160?s.substring(0,160)+"…":s,Toast.LENGTH_LONG).show();});}
    void draft(Intent i){try{startActivity(i);result("Handoff opened. Verify the target screen contains the synthetic test data and do not send/save unless you intentionally want to.");}catch(Throwable e){result("FAIL · no handler: "+msg(e));}}
    void open(Class<?> c){try{startActivity(new Intent(this,c));}catch(Throwable e){result("Could not open test surface: "+msg(e));}}
    void runWorker(Runnable r){try{worker.execute(r);}catch(Throwable e){result("Worker unavailable: "+msg(e));}}
    void post(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())r.run();});}
    void releaseRecorder(){try{if(recorder!=null)recorder.release();}catch(Throwable ignored){}recorder=null;}
    static String msg(Throwable e){if(e==null)return"unknown";String m=e.getMessage();return m==null||m.trim().isEmpty()?e.getClass().getSimpleName():m;}
}
