package com.kareem.cortex;

import android.content.*;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.net.*;
import android.os.*;
import android.provider.Settings;
import androidx.annotation.NonNull;
import androidx.work.Worker;
import androidx.work.WorkerParameters;
import org.json.JSONObject;

/** Low-impact periodic sample. It watches real behavior instead of manufacturing personal data just to make tests pass. */
public class CortexAuditSoakWorker extends Worker {
    public CortexAuditSoakWorker(@NonNull Context c,@NonNull WorkerParameters p){super(c,p);}
    @NonNull @Override public Result doWork(){long runId=getInputData().getLong("run_id",0);if(runId<=0)return Result.failure();Context ctx=getApplicationContext();VaultDb db=new VaultDb(ctx);try{CortexAuditStore.Run r=CortexAuditStore.get(db,runId);if(r==null||!r.active())return Result.success();JSONObject m=capture(ctx,db,runId,"periodic");int progress=r.progress();CortexAuditStore.updateRun(db,runId,"soaking","72-hour observation","Collecting real background evidence",progress,"Audit is observing normal Cortex behavior. You can keep using the phone normally.",null);CortexAuditStore.log(db,runId,"info","audit","soak_sample","Periodic observation sample captured",m);updateObservations(ctx,db,r,m,false);return Result.success();}catch(Exception e){CortexAuditStore.log(db,runId,"error","audit","soak_sample_error",e.toString(),null);return Result.success();}finally{db.close();}}

    public static JSONObject capture(Context ctx,VaultDb db,long runId,String kind)throws Exception{CortexAuditStore.ensure(db);VisualInsightStore.ensure(db);FeatureStore.ensure(db);CortexAuditStore.Run r=CortexAuditStore.get(db,runId);long started=r==null?0:r.startedAt;SQLiteDatabase s=db.getReadableDatabase();JSONObject m=new JSONObject();m.put("captured_at",System.currentTimeMillis());m.put("kind",kind);m.put("db_bytes",ctx.getDatabasePath("cortex.db").exists()?ctx.getDatabasePath("cortex.db").length():0);m.put("internal_free_bytes",ctx.getFilesDir().getFreeSpace());m.put("heap_used_bytes",Runtime.getRuntime().totalMemory()-Runtime.getRuntime().freeMemory());m.put("heap_max_bytes",Runtime.getRuntime().maxMemory());
        m.put("memory_total",count(s,"SELECT COUNT(*) FROM knowledge_items"));m.put("screenshots_total",count(s,"SELECT COUNT(*) FROM knowledge_items WHERE type IN ('SCREENSHOT','IMAGE')"));m.put("audio_total",count(s,"SELECT COUNT(*) FROM knowledge_items WHERE type='AUDIO'"));m.put("notifications_total",count(s,"SELECT COUNT(*) FROM knowledge_items WHERE type='NOTIFICATION'"));m.put("analysis_failures",count(s,"SELECT COUNT(*) FROM knowledge_items WHERE status IN ('analysis_failed','failed_retryable')"));m.put("screenshot_queued",count(s,"SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND status='queued'"));m.put("screenshot_analyzing",count(s,"SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND status='analyzing'"));m.put("open_actions",table(s,"actions")?count(s,"SELECT COUNT(*) FROM actions WHERE status='open'"):0);m.put("needs_count",FeatureStore.needs(db,5000).size());m.put("inbox_count",FeatureStore.inbox(db,5000).size());
        m.put("visual_total",count(s,"SELECT COUNT(*) FROM visual_insights"));m.put("visual_done",count(s,"SELECT COUNT(*) FROM visual_insights WHERE status='done'"));m.put("visual_failed",count(s,"SELECT COUNT(*) FROM visual_insights WHERE status='failed'"));m.put("visual_skipped_or_local",count(s,"SELECT COUNT(*) FROM visual_insights WHERE status IN ('skipped','local_only')"));m.put("visual_updated_since_audit",started>0?count(s,"SELECT COUNT(*) FROM visual_insights WHERE updated_at>="+started):0);m.put("visual_worker_state",VisualInsightStore.workerState(ctx));m.put("visual_worker_stage",VisualInsightStore.workerStage(ctx));m.put("visual_worker_detail",VisualInsightStore.workerDetail(ctx));
        LocalLlmRuntime.State lr=LocalLlmRuntime.state(ctx);m.put("local_llm_state",lr.state);m.put("local_llm_tps",lr.tokensPerSecond);m.put("notification_listener_enabled",notificationListenerEnabled(ctx));m.put("network_connected",network(ctx));battery(ctx,m);m.put("audit_feedback_events",count(s,"SELECT COUNT(*) FROM cortex_audit_events WHERE run_id="+runId+" AND component='user_feedback'"));CortexAuditStore.sample(db,runId,kind,m);return m;}

    static void updateObservations(Context ctx,VaultDb db,CortexAuditStore.Run r,JSONObject m,boolean finalPass)throws Exception{long id=r.id;int samples=CortexAuditStore.sampleCount(db,id);boolean listener=m.optBoolean("notification_listener_enabled",false);long notifications=m.optLong("notifications_total",0);JSONObject n=new JSONObject().put("listener_enabled",listener).put("notification_memories",notifications).put("samples",samples);CortexAuditStore.updateObservation(db,id,"notification_memory",finalPass?(listener?"pass":"warn"):"observing",listener?"ok":"warning",listener?"Notification listener is enabled; "+notifications+" notification memories currently exist.":"Notification listener is not enabled, so live notification capture cannot be proven.",n);
        long audio=m.optLong("audio_total",0);JSONObject a=new JSONObject().put("audio_memories",audio).put("samples",samples);CortexAuditStore.updateObservation(db,id,"audio_asr",finalPass?(audio>0?"pass":"warn"):"observing",audio>0?"ok":"warning",audio+" audio memories are visible during the audit. The audit never records fake microphone audio.",a);
        long visualNew=m.optLong("visual_updated_since_audit",0),visualFail=m.optLong("visual_failed",0);JSONObject v=new JSONObject().put("updated_since_start",visualNew).put("failed",visualFail).put("worker_state",m.optString("visual_worker_state","")).put("worker_stage",m.optString("visual_worker_stage",""));String vs=finalPass?(visualFail>0?"warn":(visualNew>0?"pass":"warn")):"observing";CortexAuditStore.updateObservation(db,id,"visual_background",vs,visualFail>0?"warning":"ok",visualNew+" Visual Intelligence record(s) changed since audit start • failures="+visualFail+" • worker="+m.optString("visual_worker_state",""),v);
        JSONObject soak=new JSONObject().put("samples",samples).put("started_at",r.startedAt).put("target_end_at",r.targetEndAt);CortexAuditStore.updateObservation(db,id,"background_soak",finalPass?(samples>=3?"pass":"warn"):"observing",samples>=3?"ok":"info",samples+" lightweight audit sample(s) captured so far.",soak);
        long failures=m.optLong("analysis_failures",0),queued=m.optLong("screenshot_queued",0);JSONObject p=new JSONObject().put("analysis_failures",failures).put("screenshot_queued",queued).put("db_bytes",m.optLong("db_bytes",0)).put("heap_used_bytes",m.optLong("heap_used_bytes",0)).put("internal_free_bytes",m.optLong("internal_free_bytes",0));String ps=finalPass?(failures==0&&queued<100?"pass":"warn"):"observing";CortexAuditStore.updateObservation(db,id,"performance_stability",ps,(failures==0&&queued<100)?"ok":"warning","Current failures="+failures+" • screenshot queue="+queued+" • samples="+samples,p);
        JSONObject pro=new JSONObject().put("needs",m.optInt("needs_count",0)).put("inbox",m.optInt("inbox_count",0)).put("open_actions",m.optLong("open_actions",0));CortexAuditStore.updateObservation(db,id,"proactive_cortex",finalPass?"pass":"observing","ok","Needs="+m.optInt("needs_count",0)+" • Inbox="+m.optInt("inbox_count",0)+" • open actions="+m.optLong("open_actions",0)+". This test observes real derived state and does not create fake tasks.",pro);
        int feedback=m.optInt("audit_feedback_events",0);JSONObject uf=new JSONObject().put("feedback_events",feedback);CortexAuditStore.updateObservation(db,id,"ui_feedback",finalPass?(feedback>0?"pass":"warn"):"observing",feedback>0?"ok":"info",feedback+" user feedback note(s) have been attached to this audit.",uf);
    }

    static boolean notificationListenerEnabled(Context c){try{String flat=Settings.Secure.getString(c.getContentResolver(),"enabled_notification_listeners");String me=c.getPackageName()+"/"+NotificationCaptureService.class.getName();return flat!=null&&(flat.contains(c.getPackageName())||flat.contains(me));}catch(Exception e){return false;}}
    static boolean network(Context c){try{ConnectivityManager cm=(ConnectivityManager)c.getSystemService(Context.CONNECTIVITY_SERVICE);Network n=cm.getActiveNetwork();NetworkCapabilities x=n==null?null:cm.getNetworkCapabilities(n);return x!=null&&x.hasCapability(NetworkCapabilities.NET_CAPABILITY_INTERNET);}catch(Exception e){return false;}}
    static void battery(Context c,JSONObject m)throws Exception{Intent i=c.registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));if(i==null)return;int level=i.getIntExtra(BatteryManager.EXTRA_LEVEL,-1),scale=i.getIntExtra(BatteryManager.EXTRA_SCALE,100),status=i.getIntExtra(BatteryManager.EXTRA_STATUS,-1),temp=i.getIntExtra(BatteryManager.EXTRA_TEMPERATURE,0);m.put("battery_percent",level<0?-1:Math.round(level*100f/Math.max(1,scale)));m.put("charging",status==BatteryManager.BATTERY_STATUS_CHARGING||status==BatteryManager.BATTERY_STATUS_FULL);m.put("battery_temp_c",temp/10.0);}
    static long count(SQLiteDatabase s,String q){Cursor c=s.rawQuery(q,null);long n=c.moveToFirst()?c.getLong(0):0;c.close();return n;}static boolean table(SQLiteDatabase s,String n){Cursor c=s.rawQuery("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1",new String[]{n});boolean b=c.moveToFirst();c.close();return b;}
}
