package com.kareem.cortex;

import android.Manifest;
import android.content.*;
import android.content.pm.*;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.*;
import android.net.Uri;
import android.os.*;
import android.provider.CalendarContract;
import android.provider.ContactsContract;
import androidx.annotation.NonNull;
import androidx.work.Worker;
import androidx.work.WorkerParameters;
import org.json.*;
import java.io.*;
import java.util.*;

/** Immediate safe test phase. No destructive user-data writes and no personal image is sent as a synthetic provider test. */
public class CortexAuditWorker extends Worker {
    static final class R {String status="pass",severity="ok",detail="";JSONObject evidence=new JSONObject();R(){}R(String st,String sev,String d){status=st;severity=sev;detail=d;}}
    public CortexAuditWorker(@NonNull Context c,@NonNull WorkerParameters p){super(c,p);}

    @NonNull @Override public Result doWork(){long runId=getInputData().getLong("run_id",0);if(runId<=0)return Result.failure();Context ctx=getApplicationContext();VaultDb db=new VaultDb(ctx);CortexAuditStore.ensure(db);CortexAuditStore.Run run=CortexAuditStore.get(db,runId);if(run==null||"canceled".equals(run.status)){db.close();return Result.success();}
        List<CortexAuditStore.TestDef> auto=new ArrayList<>();for(CortexAuditStore.TestDef t:CortexAuditStore.defs())if("auto".equals(t.mode))auto.add(t);CortexAuditStore.updateRun(db,runId,"running","Automatic safe checks","Starting automatic test suite",2,"Running read-only/synthetic checks",null);CortexAuditStore.log(db,runId,"info","audit","automatic_suite_started",auto.size()+" automatic checks registered",null);
        int i=0;try{for(CortexAuditStore.TestDef t:auto){if(isStopped())return Result.retry();CortexAuditStore.beginTest(db,runId,t);long started=SystemClock.elapsedRealtime();R r;try{r=run(ctx,db,t.key);}catch(Throwable e){r=new R("fail","error",e.getClass().getSimpleName()+": "+(e.getMessage()==null?"":e.getMessage()));try{r.evidence.put("exception",e.toString());}catch(Exception ignored){}}long dur=SystemClock.elapsedRealtime()-started;CortexAuditStore.finishTest(db,runId,t.key,r.status,r.severity,r.detail,r.evidence,dur);CortexAuditStore.log(db,runId,"fail".equals(r.status)?"error":("warn".equals(r.status)?"warning":"info"),t.feature,t.key,r.detail,r.evidence);i++;int progress=2+(int)Math.floor((i/(double)Math.max(1,auto.size()))*28);CortexAuditStore.updateRun(db,runId,"running","Automatic safe checks",t.title,progress,null,null);}
            JSONObject initial=CortexAuditSoakWorker.capture(ctx,db,runId,"initial");CortexAuditStore.updateRun(db,runId,"soaking","72-hour observation","Watching normal Cortex use in the background",30,"Immediate checks finished. Low-impact soak is running.",null);CortexAuditStore.log(db,runId,"info","audit","soak_started","Immediate suite finished. Cortex can be closed; WorkManager keeps the audit alive.",initial);return Result.success();
        }catch(Throwable e){CortexAuditStore.updateRun(db,runId,"soaking","72-hour observation","Immediate suite hit an error; soak will continue",30,"Audit continues with observation despite an immediate-suite error",e.toString());CortexAuditStore.log(db,runId,"error","audit","automatic_suite_error",e.toString(),null);return Result.success();}finally{db.close();}}

    private R run(Context ctx,VaultDb db,String key)throws Exception{switch(key){
        case "app_identity":return appIdentity(ctx);
        case "manifest_components":return manifest(ctx);
        case "permissions_inventory":return permissions(ctx);
        case "database_integrity":return dbIntegrity(db);
        case "database_schema":return dbSchema(db);
        case "vault_records":return vault(db);
        case "attachment_files":return attachments(db);
        case "screenshot_source":return screenshotSource(ctx);
        case "screenshot_queue":return screenshotQueue(db);
        case "screenshot_dedup":return screenshotDedup(db);
        case "supporting_ocr":return supportingOcr(ctx);
        case "visual_store":return visualStore(db);
        case "privacy_guard_synthetic":return privacySynthetic();
        case "gemini_vision_synthetic":return geminiSynthetic(ctx);
        case "local_llm_runtime":return localBrain(ctx);
        case "ask_cortex_route":return askRoute(ctx,db);
        case "semantic_search":return semanticSearch(db);
        case "smart_inbox":return smartInbox(db);
        case "temporal_actions":return temporal(db);
        case "memory_graph":return graph(db);
        case "people_memory":return people(db);
        case "projects_context":return projects(db);
        case "prompt_library":return prompts(db);
        case "screenshot_learning":return screenshotLearning(db);
        case "corrections_learning":return corrections(db);
        case "calendar_read":return calendarRead(ctx);
        case "contacts_read":return contactsRead(ctx);
        case "backup_export_preflight":return backupPreflight(ctx);
        case "debug_export_preflight":return debugPreflight(ctx);
        default:return new R("not_run","info","No automatic implementation is registered for this test key; it remains explicitly documented.");}}

    private R appIdentity(Context c)throws Exception{PackageInfo p=c.getPackageManager().getPackageInfo(c.getPackageName(),0);R r=new R();r.detail="Installed "+p.versionName+" (build "+(Build.VERSION.SDK_INT>=28?p.getLongVersionCode():p.versionCode)+") on Android "+Build.VERSION.RELEASE;put(r,"package",c.getPackageName());put(r,"version_name",p.versionName);put(r,"version_code",Build.VERSION.SDK_INT>=28?p.getLongVersionCode():p.versionCode);put(r,"sdk",Build.VERSION.SDK_INT);return r;}
    private R manifest(Context c)throws Exception{PackageManager pm=c.getPackageManager();int flags=PackageManager.GET_ACTIVITIES|PackageManager.GET_SERVICES|PackageManager.GET_PROVIDERS|PackageManager.GET_RECEIVERS|PackageManager.GET_PERMISSIONS;PackageInfo p=pm.getPackageInfo(c.getPackageName(),flags);JSONArray a=names(p.activities),s=names(p.services),pr=names(p.providers),rc=names(p.receivers);String[] required={"PremiumHomeActivity","EnvironmentActivity","VaultActivity","BrainActivity","VisualIntelligenceActivity","CortexAuditActivity"};ArrayList<String> missing=new ArrayList<>();for(String x:required)if(!containsSuffix(a,x))missing.add(x);R r=new R(missing.isEmpty()?"pass":"fail",missing.isEmpty()?"ok":"error",missing.isEmpty()?"Core Android components are registered.":"Missing core activities: "+String.join(", ",missing));put(r,"activities",a);put(r,"services",s);put(r,"providers",pr);put(r,"receivers",rc);put(r,"missing_required",new JSONArray(missing));return r;}
    private R permissions(Context c)throws Exception{PackageInfo p=c.getPackageManager().getPackageInfo(c.getPackageName(),PackageManager.GET_PERMISSIONS);JSONArray a=new JSONArray();int denied=0;if(p.requestedPermissions!=null)for(String x:p.requestedPermissions){boolean g=c.getPackageManager().checkPermission(x,c.getPackageName())==PackageManager.PERMISSION_GRANTED;JSONObject o=new JSONObject().put("permission",x).put("granted",g);a.put(o);if(!g&&(Manifest.permission.RECORD_AUDIO.equals(x)||Manifest.permission.READ_CALENDAR.equals(x)||Manifest.permission.READ_CONTACTS.equals(x)))denied++;}R r=new R(denied==0?"pass":"warn",denied==0?"ok":"warning",denied==0?"Requested permissions are currently granted where needed.":denied+" optional/user-controlled permission(s) are not granted; affected tests will say NOT RUN rather than pretending to pass.");put(r,"requested_permissions",a);return r;}
    private R dbIntegrity(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();String quick=scalar(s,"PRAGMA quick_check(1)");int fk=rows(s,"PRAGMA foreign_key_check");R r=new R("ok".equalsIgnoreCase(quick)&&fk==0?"pass":"fail",fk==0?"ok":"error","SQLite quick_check="+quick+" • foreign-key issues="+fk);put(r,"quick_check",quick);put(r,"foreign_key_issue_rows",fk);return r;}
    private R dbSchema(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();Cursor c=s.rawQuery("SELECT name,sql FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name",null);JSONArray a=new JSONArray();while(c.moveToNext()){String n=c.getString(0);JSONObject o=new JSONObject().put("table",n).put("rows",count(s,"SELECT COUNT(*) FROM \""+n.replace("\"","\"\"")+"\""));Cursor q=s.rawQuery("PRAGMA table_info(\""+n.replace("\"","\"\"")+"\")",null);o.put("columns",q.getCount());q.close();a.put(o);}c.close();R r=new R();r.detail=a.length()+" application tables are readable and inventoried.";put(r,"tables",a);return r;}
    private R vault(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();long total=count(s,"SELECT COUNT(*) FROM knowledge_items"),shots=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE type IN ('SCREENSHOT','IMAGE')"),audio=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE type='AUDIO'"),failed=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE status IN ('analysis_failed','failed_retryable')");R r=new R(failed==0?"pass":"warn",failed==0?"ok":"warning",total+" memories readable • "+shots+" screenshots/images • "+audio+" audio • "+failed+" analysis failures");put(r,"total",total);put(r,"screenshots",shots);put(r,"audio",audio);put(r,"failed",failed);return r;}
    private R attachments(VaultDb db)throws Exception{Cursor c=db.getReadableDatabase().rawQuery("SELECT id,attachment_path FROM knowledge_items WHERE attachment_path IS NOT NULL AND TRIM(attachment_path)<>''",null);int total=0,missing=0;JSONArray sample=new JSONArray();while(c.moveToNext()){total++;String p=c.getString(1);if(p==null||!new File(p).exists()){missing++;if(sample.length()<20)sample.put(new JSONObject().put("item_id",c.getLong(0)).put("path",p));}}c.close();R r=new R(missing==0?"pass":"fail",missing==0?"ok":"error",total+" attachment references checked • "+missing+" missing");put(r,"checked",total);put(r,"missing",missing);put(r,"missing_sample",sample);return r;}
    private R screenshotSource(Context c)throws Exception{Uri u=ScreenshotIngestor.tree(c);R r=new R(u!=null?"pass":"warn",u!=null?"ok":"warning",u==null?"Screenshot folder is not connected.":"Screenshot folder connected: "+ScreenshotIngestor.treeLabel(c));put(r,"connected",u!=null);put(r,"label",ScreenshotIngestor.treeLabel(c));put(r,"uri",u==null?"":u.toString());return r;}
    private R screenshotQueue(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();long q=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND status='queued'"),a=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND status='analyzing'"),f=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND status IN ('analysis_failed','failed_retryable')");String st=f>0?"warn":(q>100?"warn":"pass");R r=new R(st,"pass".equals(st)?"ok":"warning","queued="+q+" • analyzing="+a+" • failed="+f);put(r,"queued",q);put(r,"analyzing",a);put(r,"failed",f);return r;}
    private R screenshotDedup(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();long groups=count(s,"SELECT COUNT(*) FROM (SELECT fingerprint FROM knowledge_items WHERE source='screenshot-folder' AND COALESCE(fingerprint,'')<>'' GROUP BY fingerprint HAVING COUNT(*)>1)"),rows=count(s,"SELECT COALESCE(SUM(n-1),0) FROM (SELECT COUNT(*) n FROM knowledge_items WHERE source='screenshot-folder' AND COALESCE(fingerprint,'')<>'' GROUP BY fingerprint HAVING COUNT(*)>1)");R r=new R(groups==0?"pass":"warn",groups==0?"ok":"warning",groups==0?"No duplicate screenshot fingerprint groups found.":groups+" duplicate fingerprint groups / "+rows+" extra rows need review.");put(r,"duplicate_groups",groups);put(r,"extra_rows",rows);return r;}
    private R supportingOcr(Context c)throws Exception{boolean ar=ArabicOcr.modelReady(c);R r=new R(ar?"pass":"warn",ar?"ok":"warning",(ar?"Bundled Arabic OCR component is present.":"Arabic OCR component is not ready.")+" This check is component health only; it does not certify Arabic recognition quality.");put(r,"arabic_component_ready",ar);put(r,"quality_certified",false);return r;}
    private R visualStore(VaultDb db)throws Exception{VisualInsightStore.ensure(db);SQLiteDatabase s=db.getReadableDatabase();long total=count(s,"SELECT COUNT(*) FROM visual_insights"),done=count(s,"SELECT COUNT(*) FROM visual_insights WHERE status='done'"),failed=count(s,"SELECT COUNT(*) FROM visual_insights WHERE status='failed'"),skipped=count(s,"SELECT COUNT(*) FROM visual_insights WHERE status IN ('skipped','local_only')");R r=new R(failed==0&&total>0?"pass":"warn",failed==0?"ok":"warning",total+" visual insight records • done "+done+" • skipped/protected "+skipped+" • failed "+failed);put(r,"total",total);put(r,"done",done);put(r,"skipped_or_local",skipped);put(r,"failed",failed);return r;}
    private R privacySynthetic()throws Exception{KnowledgeItem otp=fake("Verification code 123456");KnowledgeItem card=fake("Card 4111 1111 1111 1111");KnowledgeItem pass=fake("Password: secret");KnowledgeItem temp=fake("Install this app? Package installer");KnowledgeItem normal=fake("Modern chair design reference product price EGP 1000");VisualTriage.Result a=VisualTriage.evaluate(otp),b=VisualTriage.evaluate(card),c=VisualTriage.evaluate(pass),d=VisualTriage.evaluate(temp),e=VisualTriage.evaluate(normal);boolean ok=a.sensitive&&b.sensitive&&c.sensitive&&d.ephemeral&&!e.sensitive;R r=new R(ok?"pass":"fail",ok?"ok":"error",ok?"Synthetic OTP/card/password were blocked locally and transient UI was recognized.":"One or more synthetic privacy cases did not route as expected.");put(r,"otp_sensitive",a.sensitive);put(r,"card_sensitive",b.sensitive);put(r,"password_sensitive",c.sensitive);put(r,"transient_ephemeral",d.ephemeral);put(r,"normal_sensitive",e.sensitive);put(r,"normal_value_score",e.valueScore);return r;}
    private R geminiSynthetic(Context c)throws Exception{if(!GeminiKeyStore.has(c))return new R("not_run","info","Gemini is not configured, so the real strong-vision provider test was not run. All prerequisites remain in the debug export.");File f=new File(c.getCacheDir(),"cortex_visual_audit.jpg");Bitmap b=Bitmap.createBitmap(900,900,Bitmap.Config.ARGB_8888);Canvas canvas=new Canvas(b);canvas.drawColor(Color.WHITE);Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);p.setColor(Color.BLACK);p.setTextSize(52);p.setTypeface(Typeface.DEFAULT_BOLD);canvas.drawText("CORTEX VISUAL AUDIT",50,110,p);p.setTypeface(Typeface.DEFAULT);p.setTextSize(42);canvas.drawText("Sample chair product",50,210,p);canvas.drawText("Price: EGP 1234",50,280,p);canvas.drawText("Design reference",50,350,p);canvas.drawText("اختبار كورتكس",50,430,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(10);canvas.drawRect(170,520,730,790,p);try(FileOutputStream out=new FileOutputStream(f)){b.compress(Bitmap.CompressFormat.JPEG,92,out);}b.recycle();KnowledgeItem k=new KnowledgeItem(-90001,"IMAGE","audit","Synthetic Cortex visual test","","","","","",f.getAbsolutePath(),"analyzed","audit-synthetic","","{}",System.currentTimeMillis(),System.currentTimeMillis());long t=SystemClock.elapsedRealtime();JSONObject root;try{root=GeminiVisionAnalyzer.analyze(c,k);}finally{f.delete();}long ms=SystemClock.elapsedRealtime()-t;String desc=root.optString("description","");String txt=root.optString("visible_text","");JSONArray actions=root.optJSONArray("suggested_actions");boolean structured=!desc.trim().isEmpty()&&actions!=null;boolean recognized=(txt.toUpperCase(Locale.ROOT).contains("CORTEX")||txt.contains("1234"));R r=new R(structured?(recognized?"pass":"warn"):"fail",structured?(recognized?"ok":"warning"):"error",structured?(recognized?"Gemini strong vision returned structured understanding and recognized synthetic text in "+ms+" ms.":"Strong vision returned structured understanding, but synthetic visible-text recognition was incomplete."):"Strong vision response was missing required structured fields.");put(r,"latency_ms",ms);put(r,"content_type",root.optString("content_type",""));put(r,"description",desc);put(r,"visible_text",txt);put(r,"usefulness",root.optJSONObject("usefulness"));put(r,"suggested_actions",actions);put(r,"provider",root.optString("_provider",""));return r;}
    private R localBrain(Context c)throws Exception{LocalLlmRuntime.State s=LocalLlmRuntime.state(c);boolean installed=LocalModelManager.installed(c);R r=new R(installed?"pass":"warn",installed?"ok":"warning",installed?"Local Qwen runtime is ready. Last self-test "+String.format(Locale.US,"%.2f tok/s",s.tokensPerSecond)+".":"Local runtime is not ready: "+s.state+(s.error.isEmpty()?"":" • "+s.error));put(r,"model_verified",LocalModelManager.verified(c));put(r,"installed",installed);put(r,"runtime_state",s.state);put(r,"tokens_per_second",s.tokensPerSecond);put(r,"tokens_generated",s.tokensGenerated);put(r,"duration_ms",s.durationMs);put(r,"error",s.error);return r;}
    private R askRoute(Context c,VaultDb db)throws Exception{if(!LocalModelManager.installed(c))return new R("not_run","warning","Local Qwen is not ready, so the local Ask routing test was not run; deterministic fallback remains available.");long t=SystemClock.elapsedRealtime();LocalAskRouter.Result x=LocalAskRouter.ask(c,db,"What kinds of information are currently stored in Cortex? Keep it brief.");long ms=SystemClock.elapsedRealtime()-t;boolean local="local-qwen".equals(x.provider);R r=new R(local?"pass":"warn",local?"ok":"warning",local?"Ask Cortex routed through local Qwen in "+ms+" ms.":"Ask completed through "+x.provider+" instead of local Qwen: "+x.error);put(r,"provider",x.provider);put(r,"wall_latency_ms",ms);put(r,"model_duration_ms",x.durationMs);put(r,"tokens_per_second",x.tokensPerSecond);put(r,"tokens_generated",x.tokensGenerated);put(r,"source_count",x.grounded==null?0:x.grounded.sources.size());put(r,"error",x.error);put(r,"answer_text_exported",false);return r;}
    private R semanticSearch(VaultDb db)throws Exception{long t=SystemClock.elapsedRealtime();GroundedAnswer g=SecondBrainEngine.ask(db,"Cortex");long ms=SystemClock.elapsedRealtime()-t;R r=new R();r.detail="Grounded retrieval completed in "+ms+" ms with "+g.sources.size()+" source(s).";put(r,"latency_ms",ms);put(r,"source_count",g.sources.size());put(r,"open_loop_count",g.openLoops.size());put(r,"decision_count",g.decisions.size());put(r,"answer_text_exported",false);return r;}
    private R smartInbox(VaultDb db)throws Exception{FeatureStore.ensure(db);int needs=FeatureStore.needs(db,5000).size(),inbox=FeatureStore.inbox(db,5000).size();long rows=count(db.getReadableDatabase(),"SELECT COUNT(*) FROM smart_inbox");R r=new R();r.detail="Needs="+needs+" • Inbox="+inbox+" • smart_inbox rows="+rows;put(r,"needs",needs);put(r,"inbox",inbox);put(r,"rows",rows);return r;}
    private R temporal(VaultDb db)throws Exception{TemporalResolver.ensure(db);SQLiteDatabase s=db.getReadableDatabase();long rows=count(s,"SELECT COUNT(*) FROM action_temporal"),actions=count(s,"SELECT COUNT(*) FROM actions"),relative=count(s,"SELECT COUNT(*) FROM actions WHERE status='open' AND (due_text LIKE '%بكر%' OR lower(due_text) LIKE '%tomorrow%' OR lower(due_text) LIKE '%today%' OR due_text LIKE '%النهاردة%')");R r=new R(relative==0?"pass":"warn",relative==0?"ok":"warning","action_temporal rows="+rows+" • actions="+actions+" • unresolved relative due text="+relative);put(r,"temporal_rows",rows);put(r,"actions",actions);put(r,"relative_due_unresolved",relative);return r;}
    private R graph(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();long rel=table(s,"relations")?count(s,"SELECT COUNT(*) FROM relations"):0,fac=table(s,"memory_facets")?count(s,"SELECT COUNT(*) FROM memory_facets"):0,packs=table(s,"context_packs")?count(s,"SELECT COUNT(*) FROM context_packs"):0;R r=new R();r.detail="relations="+rel+" • facets="+fac+" • context packs="+packs+". Zero values are reported as real state, not treated as a fake failure.";put(r,"relations",rel);put(r,"facets",fac);put(r,"context_packs",packs);return r;}
    private R people(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();long entityPeople=table(s,"entities")?count(s,"SELECT COUNT(*) FROM entities WHERE upper(kind) IN ('PERSON','PEOPLE','CONTACT')"):0,facets=table(s,"memory_facets")?count(s,"SELECT COUNT(*) FROM memory_facets WHERE upper(facet_type) LIKE '%PERSON%'"):0;R r=new R((entityPeople+facets)>0?"pass":"warn",(entityPeople+facets)>0?"ok":"warning","Person/contact entities="+entityPeople+" • person facets="+facets+". No people links are invented just to satisfy the audit.");put(r,"person_entities",entityPeople);put(r,"person_facets",facets);return r;}
    private R projects(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();long packs=table(s,"context_packs")?count(s,"SELECT COUNT(*) FROM context_packs"):0,items=table(s,"context_pack_items")?count(s,"SELECT COUNT(*) FROM context_pack_items"):0,entities=table(s,"entities")?count(s,"SELECT COUNT(*) FROM entities WHERE upper(kind)='PROJECT'"):0;R r=new R((packs+entities)>0?"pass":"warn",(packs+entities)>0?"ok":"warning","context packs="+packs+" • pack items="+items+" • project entities="+entities);put(r,"context_packs",packs);put(r,"context_pack_items",items);put(r,"project_entities",entities);return r;}
    private R prompts(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();long n=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE lower(COALESCE(tags,'')) LIKE '%prompt%' OR lower(COALESCE(category,'')) LIKE '%ai%'"),examples=table(s,"examples")?count(s,"SELECT COUNT(*) FROM examples"):0;R r=new R(n>0?"pass":"warn",n>0?"ok":"warning",n+" prompt/AI-tagged memories • "+examples+" examples rows");put(r,"prompt_or_ai_memories",n);put(r,"examples",examples);return r;}
    private R screenshotLearning(VaultDb db)throws Exception{ScreenshotLearning.ensure(db);long taught=ScreenshotLearning.taughtCount(db),prefs=ScreenshotLearning.learnedPreferenceCount(db),selected=count(db.getReadableDatabase(),"SELECT COUNT(*) FROM screenshot_intents WHERE selected=1");R r=new R((taught+prefs+selected)>0?"pass":"warn",(taught+prefs+selected)>0?"ok":"warning","taught screenshots="+taught+" • selected intents="+selected+" • learned rules="+prefs+(taught==0?". Learning exists but has no user teaching evidence yet.":""));put(r,"taught",taught);put(r,"selected_intents",selected);put(r,"preference_rules",prefs);return r;}
    private R corrections(VaultDb db)throws Exception{SQLiteDatabase s=db.getReadableDatabase();long rules=table(s,"correction_rules")?count(s,"SELECT COUNT(*) FROM correction_rules"):0,examples=table(s,"examples")?count(s,"SELECT COUNT(*) FROM examples"):0;R r=new R(rules>0?"pass":"warn",rules>0?"ok":"warning","correction rules="+rules+" • examples="+examples+". Empty learning data is explicit.");put(r,"correction_rules",rules);put(r,"examples",examples);return r;}
    private R calendarRead(Context c)throws Exception{boolean granted=c.checkSelfPermission(Manifest.permission.READ_CALENDAR)==PackageManager.PERMISSION_GRANTED;if(!granted){R r=new R("not_run","info","READ_CALENDAR is not granted; read-only provider test was not run.");put(r,"permission_granted",false);return r;}Cursor q=c.getContentResolver().query(CalendarContract.Calendars.CONTENT_URI,new String[]{CalendarContract.Calendars._ID},null,null,null);int n=q==null?0:q.getCount();if(q!=null)q.close();R r=new R();r.detail="Read-only Calendar provider query succeeded • calendars visible="+n;put(r,"permission_granted",true);put(r,"calendar_count",n);return r;}
    private R contactsRead(Context c)throws Exception{boolean granted=c.checkSelfPermission(Manifest.permission.READ_CONTACTS)==PackageManager.PERMISSION_GRANTED;if(!granted){R r=new R("not_run","info","READ_CONTACTS is not granted; read-only provider test was not run.");put(r,"permission_granted",false);return r;}Cursor q=c.getContentResolver().query(ContactsContract.Contacts.CONTENT_URI,new String[]{ContactsContract.Contacts._ID},null,null,null);int n=q==null?0:q.getCount();if(q!=null)q.close();R r=new R();r.detail="Read-only Contacts provider query succeeded • contacts visible="+n;put(r,"permission_granted",true);put(r,"contact_count",n);return r;}
    private R backupPreflight(Context c)throws Exception{Class.forName("com.kareem.cortex.BackupExporter");Class.forName("com.kareem.cortex.BackupImporter");File db=c.getDatabasePath("cortex.db");long free=c.getFilesDir().getFreeSpace();R r=new R("not_run","info","Backup/restore classes load correctly. Full backup was intentionally not written during automatic audit because it can copy every attachment; restore was not executed against live data.");put(r,"database_bytes",db.exists()?db.length():0);put(r,"internal_free_bytes",free);put(r,"exporter_class_loadable",true);put(r,"importer_class_loadable",true);put(r,"full_backup_executed",false);return r;}
    private R debugPreflight(Context c)throws Exception{File dir=new File(c.getFilesDir(),"debug_exports");boolean made=dir.exists()||dir.mkdirs();File probe=new File(dir,".audit_write_probe");boolean write=false;if(made)try(FileOutputStream o=new FileOutputStream(probe)){o.write("ok".getBytes("UTF-8"));write=true;}finally{probe.delete();}boolean provider=c.getPackageManager().resolveContentProvider(c.getPackageName()+".feedback.files",0)!=null;R r=new R(made&&write&&provider?"pass":"fail",made&&write&&provider?"ok":"error","Debug directory writable="+write+" • FileProvider registered="+provider);put(r,"directory",dir.getAbsolutePath());put(r,"writable",write);put(r,"file_provider",provider);return r;}

    private static KnowledgeItem fake(String text){long n=System.currentTimeMillis();return new KnowledgeItem(-1,"SCREENSHOT","audit","Audit synthetic", "",text,"","","","","analyzed","audit","","{}",n,n);}
    private static JSONArray names(ComponentInfo[] xs)throws Exception{JSONArray a=new JSONArray();if(xs!=null)for(ComponentInfo x:xs)a.put(x.name);return a;}
    private static boolean containsSuffix(JSONArray a,String suffix){for(int i=0;i<a.length();i++)if(a.optString(i).endsWith(suffix))return true;return false;}
    private static long count(SQLiteDatabase s,String q){Cursor c=s.rawQuery(q,null);long n=c.moveToFirst()?c.getLong(0):0;c.close();return n;}
    private static int rows(SQLiteDatabase s,String q){Cursor c=s.rawQuery(q,null);int n=c.getCount();c.close();return n;}
    private static String scalar(SQLiteDatabase s,String q){Cursor c=s.rawQuery(q,null);String x=c.moveToFirst()&&!c.isNull(0)?c.getString(0):"";c.close();return x;}
    private static boolean table(SQLiteDatabase s,String n){Cursor c=s.rawQuery("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1",new String[]{n});boolean b=c.moveToFirst();c.close();return b;}
    private static void put(R r,String k,Object v){try{r.evidence.put(k,v==null?JSONObject.NULL:v);}catch(Exception ignored){}}
}
