package com.kareem.cortex;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONArray;
import org.json.JSONObject;
import java.util.*;

/** Persistent, human-readable diagnostic campaign state. Survives app restarts and device reboots through WorkManager. */
public final class CortexAuditStore {
    public static final long DEFAULT_DURATION_MS=72L*60L*60L*1000L;

    public static final class TestDef {
        public final String key,feature,title,mode,description,expected;
        TestDef(String k,String f,String t,String m,String d,String e){key=k;feature=f;title=t;mode=m;description=d;expected=e;}
    }
    public static final class Run {
        public long id,startedAt,targetEndAt,completedAt,lastHeartbeat;
        public String uuid="",status="",phase="",currentTest="",summary="",error="";
        public int storedProgress;
        public boolean active(){return "starting".equals(status)||"running".equals(status)||"soaking".equals(status)||"finalizing".equals(status);}
        public int progress(){if("complete".equals(status))return 100;if("canceled".equals(status))return storedProgress;if("soaking".equals(status)&&targetEndAt>startedAt){double x=(System.currentTimeMillis()-startedAt)/(double)(targetEndAt-startedAt);return Math.max(storedProgress,Math.min(99,30+(int)Math.floor(Math.max(0,Math.min(1,x))*69)));}return Math.max(0,Math.min(100,storedProgress));}
    }

    private CortexAuditStore(){}

    private static TestDef d(String k,String f,String t,String m,String desc,String expected){return new TestDef(k,f,t,m,desc,expected);}
    public static List<TestDef> defs(){return Arrays.asList(
        d("app_identity","Application","App identity and build","auto","Checks the installed package, version and basic runtime identity.","Package com.kareem.cortex and a readable version/build."),
        d("manifest_components","Application","Activities, services and providers","auto","Inventories Android components and verifies core Cortex screens/services are registered.","Core activities, FileProvider and notification service resolve correctly."),
        d("permissions_inventory","Privacy & permissions","Permission inventory","auto","Records requested permissions and current grant state without changing any permission.","Every permission is reported; missing optional grants are explained, not hidden."),
        d("database_integrity","Vault","Database integrity","auto","Runs SQLite quick_check and foreign-key diagnostics without modifying memories.","quick_check=ok and no integrity failures."),
        d("database_schema","Vault","Database schema inventory","auto","Counts every table and records schema coverage for the diagnostic export.","All current tables are readable."),
        d("vault_records","Vault","Vault readability and counts","auto","Reads memory counts by type/status/source and confirms the Vault can be queried.","Vault queries complete without exceptions."),
        d("attachment_files","Vault","Archived attachment files","auto","Checks that attachment paths referenced by memories still exist.","No missing archived files."),
        d("screenshot_source","Universal Capture","Screenshot folder connection","auto","Checks Samsung screenshot-folder connection and persisted access state.","Screenshot source is connected when screenshot capture is expected."),
        d("screenshot_queue","Screenshot Intelligence","Screenshot extraction queue","auto","Checks queued/analyzing/failed screenshot records and backlog size.","No stuck or failed screenshot work."),
        d("screenshot_dedup","Universal Capture","Screenshot duplicate fingerprints","auto","Looks for duplicate stored fingerprints without deleting anything.","No unexpected duplicate fingerprint groups."),
        d("supporting_ocr","Supporting OCR","Supporting text extraction component","auto","Checks ML Kit/Tesseract component availability only. It does NOT claim OCR quality is good.","Component is available; quality is judged separately by Visual Intelligence/user feedback."),
        d("visual_store","Visual Intelligence","Visual Intelligence data layer","auto","Checks visual_insights states, providers and saved results.","Visual Intelligence table is healthy and results can be read."),
        d("privacy_guard_synthetic","Visual Privacy Guard","Synthetic privacy guard test","auto","Uses synthetic OTP/card/password/transient examples locally; no personal image is sent anywhere.","Sensitive examples are blocked and transient UI is recognized."),
        d("gemini_vision_synthetic","Visual Intelligence","Synthetic strong-vision test","auto","Creates a synthetic Cortex image and, when Gemini is configured, sends only that synthetic image to test the real vision route.","Provider returns structured image description, text/usefulness/actions JSON."),
        d("local_llm_runtime","Local Brain","Local Qwen readiness","auto","Checks verified model/runtime state and last real self-test telemetry.","Local model is verified and inference_ready."),
        d("ask_cortex_route","Ask Cortex","Grounded Ask routing","auto","Runs one grounded Ask request and records provider/latency/source count without storing the answer text.","Ask routes to local-qwen when the local runtime is ready, with deterministic fallback documented otherwise."),
        d("semantic_search","Memory Search","Semantic/grounded retrieval","auto","Runs a safe retrieval query and records source count without changing memory.","Retrieval completes and returns a valid GroundedAnswer."),
        d("smart_inbox","Smart Inbox","Smart Inbox queries","auto","Reads Needs and Inbox buckets and checks the derived inbox table.","Needs/Inbox queries complete without corruption."),
        d("temporal_actions","Reminders & Dates","Temporal action state","auto","Audits action_temporal, due-text state and unresolved relative dates.","Temporal tables are readable and unresolved relative dates are surfaced."),
        d("memory_graph","Memory Connections","Graph and relation state","auto","Reports relations, facets and context-pack counts; zero data is reported explicitly.","Graph tables remain readable and noise is visible."),
        d("people_memory","People Memory","People-memory data state","auto","Reports person-related facets/entities currently present. Does not fabricate people links.","Data layer state is explicit even if no people memory exists yet."),
        d("projects_context","Projects & Context Packs","Project/context-pack data state","auto","Reports context_packs/items and project entities without creating a project.","Implementation/data state is visible even when empty."),
        d("prompt_library","Prompt Library","Prompt/AI capture state","auto","Counts AI/prompt-tagged memories and examples without altering them.","Existing prompt captures are queryable; zero content is reported explicitly."),
        d("screenshot_learning","Corrections & Learning","Screenshot learning state","auto","Reports taught screenshots, selected intents and learned preference rules.","Learning tables are readable; lack of teaching data becomes a warning rather than a fake pass."),
        d("corrections_learning","Corrections & Learning","Correction-rule state","auto","Reports correction_rules and examples currently available.","Correction data is readable and absence is explicit."),
        d("calendar_read","Integrations","Calendar read access","auto","When permission is granted, performs a read-only Calendar provider query.","Calendar provider can be read without creating or changing events."),
        d("contacts_read","Integrations","Contacts read access","auto","When permission is granted, performs a read-only Contacts provider query.","Contacts provider can be read without changing contacts."),
        d("backup_export_preflight","Backup & Restore","Backup export preflight","auto","Checks backup classes/storage/database size. A full multi-GB-style backup is not automatically created during the audit.","Backup code is loadable and prerequisites are reported."),
        d("debug_export_preflight","Diagnostics","Exhaustive debug-export preflight","auto","Checks FileProvider and writable debug directory before the final diagnostic package.","A debug package can be written/shared."),
        d("notification_memory","Notification Memory","Notification capture observation","observation","Observes notification-listener enablement and notification-derived memory changes during the soak.","Listener state and any observed captures are documented over time."),
        d("audio_asr","Voice & Audio","Audio/ASR observation","observation","Observes voice items, analysis state and ASR evidence while you use Cortex normally.","Any audio processed during the audit is reflected in samples; no fake microphone recording is generated."),
        d("visual_background","Visual Intelligence","Background visual processing observation","observation","Observes new visual_insights, failures/skips and worker state during normal use.","Background Visual Intelligence progresses without repeated failures."),
        d("background_soak","Reliability","72-hour background soak","observation","Takes lightweight snapshots every few hours to catch stalls, queue growth and state drift.","Multiple samples are captured across the audit window."),
        d("performance_stability","Performance","Performance/stability observation","observation","Tracks database size, queue/failure counts, memory/storage telemetry and background progress.","No sustained failure/backlog growth is observed."),
        d("proactive_cortex","Proactive Cortex","Proactive/Needs observation","observation","Observes Needs/Inbox and derived actions during normal usage without creating fake personal tasks.","Proactive state is captured and any changes are traceable."),
        d("ui_feedback","Usability","User feedback during audit","observation","Stores your own notes about slowness, confusing buttons or wrong results directly inside the audit export.","Feedback is timestamped and included verbatim in diagnostics."),
        d("calendar_write","Integrations","Calendar write test","protected","Not executed automatically because it would create/modify a real calendar event.","Reported as NOT RUN with permission/provider state and reason."),
        d("backup_restore","Backup & Restore","Restore test","protected","Not executed against the live Vault because restore is destructive/mutating.","Reported as NOT RUN; restore implementation/prerequisites remain inventoried."),
        d("external_integration_writes","Integrations","External write actions","protected","No email/message/calendar/contact write is fabricated by diagnostics.","Reported as NOT RUN unless a safe sandbox is added later."),
        d("visual_action_execution","Visual Actions","Real-world visual action execution","protected","Search/recreate/project/reminder actions can affect external state or user workflow, so the audit inventories availability but does not click them for you.","Action support and missing implementations are visible in Visual Intelligence records/debug data."),
        d("daily_weekly_brief","Briefs","Daily/weekly brief observation","protected","No fake brief is injected into the live Brain merely to make a test pass.","Current implementation/data state is exported even when no live brief was generated during this run.")
    );}

    public static void ensure(VaultDb db){SQLiteDatabase s=db.getWritableDatabase();
        s.execSQL("CREATE TABLE IF NOT EXISTS cortex_audit_runs(id INTEGER PRIMARY KEY AUTOINCREMENT,run_uuid TEXT UNIQUE NOT NULL,status TEXT NOT NULL,phase TEXT,current_test TEXT,progress INTEGER DEFAULT 0,started_at INTEGER NOT NULL,target_end_at INTEGER NOT NULL,completed_at INTEGER DEFAULT 0,last_heartbeat INTEGER DEFAULT 0,summary TEXT,error TEXT)");
        s.execSQL("CREATE TABLE IF NOT EXISTS cortex_audit_tests(id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER NOT NULL,test_key TEXT NOT NULL,feature TEXT,title TEXT,mode TEXT,status TEXT,passed INTEGER DEFAULT -1,severity TEXT,description TEXT,expected TEXT,started_at INTEGER DEFAULT 0,finished_at INTEGER DEFAULT 0,duration_ms INTEGER DEFAULT 0,detail TEXT,evidence_json TEXT,UNIQUE(run_id,test_key))");
        s.execSQL("CREATE TABLE IF NOT EXISTS cortex_audit_events(id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER NOT NULL,created_at INTEGER NOT NULL,level TEXT,component TEXT,event TEXT,detail TEXT,metrics_json TEXT)");
        s.execSQL("CREATE TABLE IF NOT EXISTS cortex_audit_samples(id INTEGER PRIMARY KEY AUTOINCREMENT,run_id INTEGER NOT NULL,captured_at INTEGER NOT NULL,kind TEXT,metrics_json TEXT)");
        s.execSQL("CREATE INDEX IF NOT EXISTS idx_audit_run_status ON cortex_audit_runs(status)");s.execSQL("CREATE INDEX IF NOT EXISTS idx_audit_test_run ON cortex_audit_tests(run_id,status)");s.execSQL("CREATE INDEX IF NOT EXISTS idx_audit_event_run ON cortex_audit_events(run_id,created_at)");s.execSQL("CREATE INDEX IF NOT EXISTS idx_audit_sample_run ON cortex_audit_samples(run_id,captured_at)");
    }

    public static synchronized Run start(Context c,VaultDb db){ensure(db);Run active=active(db);if(active!=null)return active;long now=System.currentTimeMillis();ContentValues v=new ContentValues();String uuid="AUDIT-"+now+"-"+UUID.randomUUID().toString().substring(0,8);v.put("run_uuid",uuid);v.put("status","starting");v.put("phase","Preparing safe full-app checks");v.put("current_test","Registering test plan");v.put("progress",1);v.put("started_at",now);v.put("target_end_at",now+DEFAULT_DURATION_MS);v.put("last_heartbeat",now);v.put("summary","72-hour Cortex full application audit");long id=db.getWritableDatabase().insertOrThrow("cortex_audit_runs",null,v);seed(db,id);log(db,id,"info","audit","started","Button tap accepted. Persistent 72-hour audit created.",new JSONObject());return get(db,id);}

    private static void seed(VaultDb db,long runId){SQLiteDatabase s=db.getWritableDatabase();for(TestDef t:defs()){ContentValues v=new ContentValues();v.put("run_id",runId);v.put("test_key",t.key);v.put("feature",t.feature);v.put("title",t.title);v.put("mode",t.mode);v.put("description",t.description);v.put("expected",t.expected);if("auto".equals(t.mode)){v.put("status","pending");v.put("severity","info");v.put("detail","Waiting for automatic test.");}else if("observation".equals(t.mode)){v.put("status","observing");v.put("severity","info");v.put("detail","Observation window started; evidence will accumulate during normal use.");}else{v.put("status","not_run");v.put("severity","info");v.put("detail",t.description);}s.insertWithOnConflict("cortex_audit_tests",null,v,SQLiteDatabase.CONFLICT_IGNORE);}}

    public static Run latest(VaultDb db){ensure(db);Cursor c=db.getReadableDatabase().rawQuery("SELECT * FROM cortex_audit_runs ORDER BY id DESC LIMIT 1",null);Run r=c.moveToFirst()?run(c):null;c.close();return r;}
    public static Run active(VaultDb db){ensure(db);Cursor c=db.getReadableDatabase().rawQuery("SELECT * FROM cortex_audit_runs WHERE status IN ('starting','running','soaking','finalizing') ORDER BY id DESC LIMIT 1",null);Run r=c.moveToFirst()?run(c):null;c.close();return r;}
    public static Run get(VaultDb db,long id){ensure(db);Cursor c=db.getReadableDatabase().rawQuery("SELECT * FROM cortex_audit_runs WHERE id=?",new String[]{String.valueOf(id)});Run r=c.moveToFirst()?run(c):null;c.close();return r;}

    public static void updateRun(VaultDb db,long id,String status,String phase,String current,int progress,String summary,String error){ensure(db);ContentValues v=new ContentValues();if(status!=null)v.put("status",status);if(phase!=null)v.put("phase",phase);if(current!=null)v.put("current_test",current);if(progress>=0)v.put("progress",Math.max(0,Math.min(100,progress)));if(summary!=null)v.put("summary",summary);if(error!=null)v.put("error",error);v.put("last_heartbeat",System.currentTimeMillis());if("complete".equals(status)||"canceled".equals(status))v.put("completed_at",System.currentTimeMillis());db.getWritableDatabase().update("cortex_audit_runs",v,"id=?",new String[]{String.valueOf(id)});}
    public static void beginTest(VaultDb db,long runId,TestDef t){ContentValues v=new ContentValues();v.put("status","running");v.put("passed",-1);v.put("started_at",System.currentTimeMillis());v.put("finished_at",0);v.put("duration_ms",0);v.put("detail","Running now…");db.getWritableDatabase().update("cortex_audit_tests",v,"run_id=? AND test_key=?",new String[]{String.valueOf(runId),t.key});updateRun(db,runId,"running","Automatic safe checks",t.title,-1,null,null);}
    public static void finishTest(VaultDb db,long runId,String key,String status,String severity,String detail,JSONObject evidence,long durationMs){ContentValues v=new ContentValues();v.put("status",status);v.put("passed","pass".equals(status)?1:("fail".equals(status)?0:-1));v.put("severity",severity==null?"info":severity);v.put("finished_at",System.currentTimeMillis());v.put("duration_ms",Math.max(0,durationMs));v.put("detail",detail==null?"":detail);v.put("evidence_json",evidence==null?"{}":evidence.toString());db.getWritableDatabase().update("cortex_audit_tests",v,"run_id=? AND test_key=?",new String[]{String.valueOf(runId),key});}
    public static void updateObservation(VaultDb db,long runId,String key,String status,String severity,String detail,JSONObject evidence){ContentValues v=new ContentValues();v.put("status",status);v.put("passed","pass".equals(status)?1:("fail".equals(status)?0:-1));v.put("severity",severity==null?"info":severity);v.put("detail",detail==null?"":detail);v.put("evidence_json",evidence==null?"{}":evidence.toString());v.put("finished_at","observing".equals(status)?0:System.currentTimeMillis());db.getWritableDatabase().update("cortex_audit_tests",v,"run_id=? AND test_key=?",new String[]{String.valueOf(runId),key});}

    public static void log(VaultDb db,long runId,String level,String component,String event,String detail,JSONObject metrics){ensure(db);ContentValues v=new ContentValues();v.put("run_id",runId);v.put("created_at",System.currentTimeMillis());v.put("level",level==null?"info":level);v.put("component",component==null?"":component);v.put("event",event==null?"":event);v.put("detail",detail==null?"":detail);v.put("metrics_json",metrics==null?"{}":metrics.toString());db.getWritableDatabase().insert("cortex_audit_events",null,v);}
    public static void sample(VaultDb db,long runId,String kind,JSONObject metrics){ensure(db);ContentValues v=new ContentValues();v.put("run_id",runId);v.put("captured_at",System.currentTimeMillis());v.put("kind",kind==null?"soak":kind);v.put("metrics_json",metrics==null?"{}":metrics.toString());db.getWritableDatabase().insert("cortex_audit_samples",null,v);updateRun(db,runId,null,null,null,-1,null,null);}

    public static int countTests(VaultDb db,long runId,String status){ensure(db);String q=status==null?"SELECT COUNT(*) FROM cortex_audit_tests WHERE run_id=?":"SELECT COUNT(*) FROM cortex_audit_tests WHERE run_id=? AND status=?";Cursor c=db.getReadableDatabase().rawQuery(q,status==null?new String[]{String.valueOf(runId)}:new String[]{String.valueOf(runId),status});int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
    public static int sampleCount(VaultDb db,long runId){Cursor c=db.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM cortex_audit_samples WHERE run_id=?",new String[]{String.valueOf(runId)});int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
    public static JSONArray testsJson(VaultDb db,long runId){return dump(db.getReadableDatabase(),"SELECT * FROM cortex_audit_tests WHERE run_id="+runId+" ORDER BY id");}
    public static JSONArray eventsJson(VaultDb db,long runId,int limit){return dump(db.getReadableDatabase(),"SELECT * FROM cortex_audit_events WHERE run_id="+runId+" ORDER BY created_at DESC LIMIT "+Math.max(1,limit));}

    public static JSONObject exportJson(Context c,VaultDb db){ensure(db);JSONObject o=new JSONObject();try{Run r=latest(db);o.put("audit_design","Persistent safe audit: immediate checks + 72-hour low-impact soak. Destructive writes are never faked; they remain explicit NOT RUN tests.");o.put("default_duration_hours",72);o.put("feature_catalog",catalogJson());if(r==null){o.put("status","never_started");return o;}JSONObject x=new JSONObject();x.put("id",r.id);x.put("run_uuid",r.uuid);x.put("status",r.status);x.put("phase",r.phase);x.put("current_test",r.currentTest);x.put("progress_percent",r.progress());x.put("started_at",r.startedAt);x.put("target_end_at",r.targetEndAt);x.put("completed_at",r.completedAt);x.put("last_heartbeat",r.lastHeartbeat);x.put("summary",r.summary);x.put("error",r.error);x.put("counts",statusCounts(db,r.id));o.put("latest_run",x);o.put("tests",testsJson(db,r.id));o.put("events",dump(db.getReadableDatabase(),"SELECT * FROM cortex_audit_events WHERE run_id="+r.id+" ORDER BY created_at"));o.put("samples",dump(db.getReadableDatabase(),"SELECT * FROM cortex_audit_samples WHERE run_id="+r.id+" ORDER BY captured_at"));}catch(Exception e){try{o.put("export_error",e.toString());}catch(Exception ignored){}}return o;}

    public static JSONArray catalogJson(){JSONArray a=new JSONArray();for(TestDef t:defs())try{JSONObject o=new JSONObject();o.put("test_key",t.key);o.put("feature",t.feature);o.put("title",t.title);o.put("mode",t.mode);o.put("description",t.description);o.put("expected",t.expected);a.put(o);}catch(Exception ignored){}return a;}
    public static JSONObject statusCounts(VaultDb db,long runId){JSONObject o=new JSONObject();try{Cursor c=db.getReadableDatabase().rawQuery("SELECT status,COUNT(*) FROM cortex_audit_tests WHERE run_id=? GROUP BY status",new String[]{String.valueOf(runId)});while(c.moveToNext())o.put(c.getString(0),c.getInt(1));c.close();}catch(Exception ignored){}return o;}

    private static Run run(Cursor c){Run r=new Run();r.id=g(c,"id");r.uuid=s(c,"run_uuid");r.status=s(c,"status");r.phase=s(c,"phase");r.currentTest=s(c,"current_test");r.storedProgress=(int)g(c,"progress");r.startedAt=g(c,"started_at");r.targetEndAt=g(c,"target_end_at");r.completedAt=g(c,"completed_at");r.lastHeartbeat=g(c,"last_heartbeat");r.summary=s(c,"summary");r.error=s(c,"error");return r;}
    private static JSONArray dump(SQLiteDatabase s,String q){JSONArray out=new JSONArray();Cursor c=null;try{c=s.rawQuery(q,null);String[] cols=c.getColumnNames();while(c.moveToNext()){JSONObject row=new JSONObject();for(int i=0;i<cols.length;i++){if(c.isNull(i))row.put(cols[i],JSONObject.NULL);else if(c.getType(i)==Cursor.FIELD_TYPE_INTEGER)row.put(cols[i],c.getLong(i));else if(c.getType(i)==Cursor.FIELD_TYPE_FLOAT)row.put(cols[i],c.getDouble(i));else if(c.getType(i)==Cursor.FIELD_TYPE_BLOB)row.put(cols[i],"<BLOB "+c.getBlob(i).length+" bytes>");else row.put(cols[i],c.getString(i));}out.put(row);}}catch(Exception ignored){}finally{if(c!=null)c.close();}return out;}
    private static String s(Cursor c,String n){int i=c.getColumnIndex(n);return i<0||c.isNull(i)?"":c.getString(i);}private static long g(Cursor c,String n){int i=c.getColumnIndex(n);return i<0||c.isNull(i)?0:c.getLong(i);}
}
