package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;

/** One authoritative real-device Cortex status test with guided remediation and final acceptance. */
public class CortexAuditActivity extends Activity {
    private LinearLayout body,statusBox,resultBox,hero;
    private TextView headline,summary,run;
    private volatile boolean destroyed=false;
    private final ArrayList<Row> lastRows=new ArrayList<>();
    private final ExecutorService worker=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"CortexExtensiveStatus");t.setPriority(Thread.NORM_PRIORITY-1);return t;});
    private int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);build();refreshStatus();}
    @Override protected void onResume(){super.onResume();refreshStatus();}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}

    private void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(14),dp(18),dp(30));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);head.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView title=CortexUi.plain(this,"Cortex Final Assessment",27,CortexUi.TEXT);CortexUi.medium(title);tx.addView(title);TextView sub=CortexUi.text(this,"One final check against Cortex's product goals. Every case shows what should happen and what actually happened on this device.",11,CortexUi.MUTED);sub.setPadding(0,dp(3),0,0);tx.addView(sub);body.addView(head);
        hero=CortexUi.card(this,22);hero.setPadding(dp(15),dp(15),dp(15),dp(15));headline=CortexUi.plain(this,"Checking Cortex…",19,CortexUi.TEXT);CortexUi.medium(headline);hero.addView(headline);summary=CortexUi.text(this,"Reading the live capability state.",11,CortexUi.MUTED);summary.setPadding(0,dp(6),0,0);hero.addView(summary);hero.setOnClickListener(v->showAttention());body.addView(hero,lp(0,10,0,0));
        run=CortexUi.action(this,"RUN FINAL APP ASSESSMENT",CortexUi.LIME,true);run.setOnClickListener(v->runExtensive());body.addView(run,lp(0,12,0,0));TextView matrix=CortexUi.action(this,"REFRESH LIVE STATUS",CortexUi.MUTED,false);matrix.setOnClickListener(v->refreshStatus());body.addView(matrix,lp(0,8,0,0));TextView export=CortexUi.action(this,"EXPORT SOURCE → UNDERSTOOD → SHOWN JSON",CortexUi.OLIVE,false);export.setOnClickListener(v->exportDiagnostic());body.addView(export,lp(0,8,0,0));
        body.addView(CortexUi.section(this,"Models, brain and runtime"));statusBox=new LinearLayout(this);statusBox.setOrientation(LinearLayout.VERTICAL);body.addView(statusBox);body.addView(CortexUi.section(this,"Final expected vs actual result"));resultBox=new LinearLayout(this);resultBox.setOrientation(LinearLayout.VERTICAL);body.addView(resultBox);setContentView(root);CortexUi.fitSystemBars(this,root);
    }

    private void refreshStatus(){if(destroyed||worker.isShutdown())return;try{worker.execute(()->{ArrayList<Row> rows=new ArrayList<>();int green=0,amber=0,red=0,quarantine=0;VaultDb db=null;try{db=new VaultDb(getApplicationContext());for(CortexCapabilityRegistry.Capability c:CortexCapabilityRegistry.all()){CortexCapabilityRegistry.State s=CortexCapabilityRegistry.evaluate(getApplicationContext(),db,c);String visual=visualStatus(c,s);rows.add(new Row(c.title,visual,s.detail));if("GREEN".equals(visual))green++;else if("RED".equals(visual))red++;else if("QUARANTINED".equals(visual))quarantine++;else amber++;}addRuntimeRows(rows);}catch(Throwable e){rows.add(new Row("System health evaluator","RED",e.getClass().getSimpleName()+": "+safe(e.getMessage())));red++;}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}final int g=green,a=amber,r=red,q=quarantine;post(()->renderStatus(rows,g,a,r,q));});}catch(RejectedExecutionException ignored){}}
    private void addRuntimeRows(ArrayList<Row> rows){boolean recovery=StartupSafetyGate.active();rows.add(new Row("Recovery safety gate",recovery?"GREEN":"RED",recovery?"Recovery protection is active.":"Recovery protection is unexpectedly disabled."));rows.add(nativeRow("OCR native runtime",CapabilitySupervisor.Capability.OCR_NATIVE));rows.add(nativeRow("ASR / Whisper native runtime",CapabilitySupervisor.Capability.ASR_NATIVE));rows.add(nativeRow("Local LLM native runtime",CapabilitySupervisor.Capability.LOCAL_LLM_NATIVE));boolean ext=ExternalBrainProvider.configured(this);rows.add(new Row("External reasoning brain",ext?"GREEN":"AMBER",ext?ExternalBrainProvider.activeProviderId(this)+" · "+ExternalBrainProvider.activeModel(this):"No external reasoning provider is configured."));rows.add(new Row("OpenRouter",OpenRouterKeyStore.has(this)?"GREEN":"AMBER",OpenRouterKeyStore.has(this)?OpenRouterModelConfig.generationModel(this):"Not configured."));rows.add(new Row("Gemini",GeminiKeyStore.has(this)?"GREEN":"AMBER",GeminiKeyStore.has(this)?"Configured":"Not configured."));boolean local=LocalModelManager.installed(this)&&LocalModelManager.verified(this);LocalLlmRuntime.State st=LocalLlmRuntime.state(this);rows.add(new Row("Local Qwen model",local?(recovery?"QUARANTINED":"GREEN"):"AMBER",local?(recovery?"Model is installed/verified but native inference is intentionally quarantined.":"Installed and verified."):"Optional local model is not installed/verified."+(safe(st.error).isEmpty()?"":" · "+safe(st.error))));}
    private Row nativeRow(String name,CapabilitySupervisor.Capability c){boolean allowed=CapabilitySupervisor.allowed(this,c);return new Row(name,allowed?"GREEN":"QUARANTINED",allowed?"Capability supervisor allows this runtime.":"Intentionally isolated by the recovery capability supervisor.");}
    private String visualStatus(CortexCapabilityRegistry.Capability c,CortexCapabilityRegistry.State s){if(("ocr".equals(c.key)||"audio_asr".equals(c.key)||"local_qwen".equals(c.key))&&StartupSafetyGate.active())return"QUARANTINED";if(CortexCapabilityRegistry.ACTIVE.equals(s.status)||CortexCapabilityRegistry.READY.equals(s.status))return"GREEN";if(CortexCapabilityRegistry.FAILED.equals(s.status)||CortexCapabilityRegistry.NOT_VERIFIED.equals(s.status))return"RED";return"AMBER";}

    private void runExtensive(){if(destroyed||worker.isShutdown())return;run.setEnabled(false);run.setText("RUNNING FINAL ASSESSMENT…");headline.setText("Testing Cortex against its goals…");resultBox.removeAllViews();try{worker.execute(()->{CortexFunctionalSelfTest.Report functional=CortexFunctionalSelfTest.run(getApplicationContext());CortexFinalAcceptanceAssessment.Report acceptance=CortexFinalAcceptanceAssessment.run(getApplicationContext());post(()->{renderAcceptance(functional,acceptance);run.setEnabled(true);run.setText("RUN FINAL APP ASSESSMENT AGAIN");refreshStatus();});});}catch(RejectedExecutionException ignored){}}
    private void renderStatus(ArrayList<Row> rows,int green,int amber,int red,int quarantine){if(destroyed)return;lastRows.clear();lastRows.addAll(rows);headline.setText(red==0?"SYSTEM HEALTHY":"SYSTEM NEEDS ATTENTION");headline.setTextColor(red==0?CortexUi.GREEN:CortexUi.RED);summary.setText("GREEN "+green+"   •   AMBER "+amber+"   •   RED "+red+"   •   QUARANTINED "+quarantine+(red+amber>0?"\nTap to review actionable setup.":""));statusBox.removeAllViews();for(Row row:rows)addRow(statusBox,row.title,row.state,row.detail);}
    private void renderAcceptance(CortexFunctionalSelfTest.Report functional,CortexFinalAcceptanceAssessment.Report acceptance){resultBox.removeAllViews();String finalState=acceptance.shipReady()&&functional.fail==0?"GREEN":"RED";String verdict=acceptance.shipReady()&&functional.fail==0?"SHIP READY":"NOT READY";addRow(resultBox,"FINAL VERDICT · "+verdict,finalState,"Acceptance: "+acceptance.pass+" pass · "+acceptance.warn+" warning · "+acceptance.fail+" failure\nFunctional: "+functional.pass+" pass · "+functional.warn+" warning · "+functional.fail+" failure");for(CortexFinalAcceptanceAssessment.Case c:acceptance.cases){String state="pass".equals(c.status)?"GREEN":("fail".equals(c.status)?"RED":"AMBER");String detail="Goal: "+c.goal+"\n\nExpected: "+c.expected+"\n\nActual: "+c.actual+(c.critical?"\n\nCritical acceptance case":"");addRow(resultBox,c.area+" · "+c.name,state,detail);}TextView divider=CortexUi.section(this,"Functional wiring details");resultBox.addView(divider);for(String line:functional.lines){String upper=line.toUpperCase(Locale.ROOT);String s=upper.startsWith("FAIL")?"RED":upper.startsWith("WARN")?"AMBER":"GREEN";addRow(resultBox,line,s,"");}}
    private void addRow(LinearLayout parent,String title,String state,String detail){LinearLayout card=CortexUi.card(this,17);card.setPadding(dp(12),dp(10),dp(12),dp(10));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView t=CortexUi.text(this,title,12,CortexUi.TEXT);CortexUi.medium(t);top.addView(t,new LinearLayout.LayoutParams(0,-2,1));TextView chip=CortexUi.chip(this,state,statusColor(state),true);top.addView(chip,new LinearLayout.LayoutParams(-2,dp(29)));card.addView(top);if(!safe(detail).isEmpty()){TextView d=CortexUi.text(this,detail,10,CortexUi.MUTED);d.setPadding(0,dp(5),0,0);d.setTextIsSelectable(true);card.addView(d);}if(!"GREEN".equals(state)&&CortexRemediation.canHandle(title)){TextView tap=CortexUi.plain(this,"Tap to fix / open setup",9,CortexUi.LIME);tap.setPadding(0,dp(6),0,0);card.addView(tap);card.setOnClickListener(v->CortexRemediation.open(this,title));}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(7));parent.addView(card,p);}

    private void showAttention(){ArrayList<String> labels=new ArrayList<>();ArrayList<Row> actions=new ArrayList<>();for(Row r:lastRows)if(!"GREEN".equals(r.state)&&CortexRemediation.canHandle(r.title)){labels.add(r.title+" · "+r.state);actions.add(r);}if(actions.isEmpty()){Toast.makeText(this,"No guided fix is currently required. Amber optional engines can stay optional.",Toast.LENGTH_LONG).show();return;}new AlertDialog.Builder(this).setTitle("Fix Cortex setup").setItems(labels.toArray(new String[0]),(d,w)->CortexRemediation.open(this,actions.get(w).title)).setNegativeButton("Close",null).show();}
    private void exportDiagnostic(){Toast.makeText(this,"Building bounded diagnostic JSON…",Toast.LENGTH_SHORT).show();new Thread(()->{try{CortexDiagnosticExporter.Exported e=CortexDiagnosticExporter.export(getApplicationContext());runOnUiThread(()->{try{Intent share=new Intent(Intent.ACTION_SEND);share.setType("application/json");share.putExtra(Intent.EXTRA_STREAM,e.uri);share.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(Intent.createChooser(share,"Share Cortex diagnostic JSON"));}catch(Throwable x){Toast.makeText(this,"JSON created but share sheet failed",Toast.LENGTH_LONG).show();}});}catch(Throwable e){runOnUiThread(()->Toast.makeText(this,"Diagnostic export failed: "+safe(e.getMessage()),Toast.LENGTH_LONG).show());}},"cortex-diagnostic-export").start();}
    private int statusColor(String s){if("GREEN".equals(s))return CortexUi.GREEN;if("RED".equals(s))return CortexUi.RED;if("QUARANTINED".equals(s))return CortexUi.COPPER;return CortexUi.YELLOW;}
    private void post(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())r.run();});}
    private LinearLayout.LayoutParams lp(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    private static String safe(String s){return s==null?"":s.trim();}
    private static final class Row{final String title,state,detail;Row(String t,String s,String d){title=t;state=s;detail=d;}}
}
