package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.util.*;

/** Human-readable live dashboard. Reports useful work, not implementation jargon. */
public class CortexStatusActivity extends Activity {
    VaultDb db;LinearLayout box;Handler h=new Handler(Looper.getMainLooper());TextView headline,current,fast,vision,model,storage;ProgressBar fastBar,visionBar;Button openVision;
    int bg=Color.rgb(11,12,14),surface=Color.rgb(24,26,30),text=Color.rgb(245,244,240),muted=Color.rgb(156,159,168),accent=Color.rgb(232,177,72),ok=Color.rgb(120,205,150),warn=Color.rgb(238,184,94),border=Color.rgb(47,50,57);
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}GradientDrawable round(int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setPlain(v,s);return v;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);VisualInsightStore.ensure(db);build();refresh();}
    @Override protected void onResume(){super.onResume();h.post(tick);ScreenshotWorkScheduler.kick(this);}
    @Override protected void onPause(){super.onPause();h.removeCallbacks(tick);}Runnable tick=new Runnable(){public void run(){if(!isFinishing()){refresh();h.postDelayed(this,1200);}}};

    void build(){ScrollView sv=new ScrollView(this);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(18),dp(18),dp(30));box.setBackgroundColor(bg);sv.addView(box);TextView title=tv("CORTEX STATUS",27,text);title.setTypeface(null,1);box.addView(title);TextView sub=tv("What Cortex is doing, what is useful already, and what is waiting.",13,muted);sub.setPadding(0,dp(4),0,dp(16));box.addView(sub);
        headline=card("RIGHT NOW");current=card("CURRENT IMAGE");fast=card("FAST TEXT EXTRACTION");fastBar=bar();box.addView(fastBar,barLp());vision=card("VISUAL INTELLIGENCE");visionBar=bar();box.addView(visionBar,barLp());openVision=button("OPEN VISUAL INTELLIGENCE INSPECTOR");openVision.setOnClickListener(v->{long id=currentVisualItem();Intent i=new Intent(this,VisualIntelligenceActivity.class);if(id>0)i.putExtra("item_id",id);startActivity(i);});box.addView(openVision,lp());model=card("LOCAL BRAIN");storage=card("VAULT");TextView note=tv("Text extraction is only supporting evidence. Visual Intelligence looks at the actual image, explains what it contains, why it may matter, and saves useful actions to the Vault. Strong cloud vision is used only after a local privacy/value check and for new screenshots by default.",12,muted);note.setPadding(dp(4),dp(10),dp(4),0);box.addView(note);setContentView(sv);}
    TextView card(String title){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(round(surface,border,20));TextView t=tv(title,11,accent);t.setTypeface(null,1);c.addView(t);TextView state=tv("",14,text);state.setPadding(0,dp(7),0,0);c.addView(state);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));box.addView(c,p);return state;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(text);b.setAllCaps(false);b.setBackground(round(surface,border,16));return b;}LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,0,0,dp(12));return p;}ProgressBar bar(){ProgressBar p=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);p.setMax(1000);return p;}LinearLayout.LayoutParams barLp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(7));p.setMargins(dp(4),-dp(5),dp(4),dp(12));return p;}

    void refresh(){SQLiteDatabase s=db.getReadableDatabase();int total=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE')");int analyzed=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND status='analyzed'");int queued=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND status='queued'");int analyzing=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND status='analyzing'");boolean charging=charging();
        long start=VisualInsightStore.existingBackgroundStart(this);int visionDone=VisualInsightStore.countDone(db),visionSkipped=VisualInsightStore.countSkipped(db),visionFailed=VisualInsightStore.countFailed(db),visionPending=start>0?VisualInsightStore.countPendingSince(db,start):0;String ws=VisualInsightStore.workerState(this),stage=VisualInsightStore.workerStage(this),detail=VisualInsightStore.workerDetail(this);long wi=VisualInsightStore.workerItem(this);
        String now;if(analyzing>0)now="Making a new screenshot searchable.";else if("running".equals(ws))now="Understanding a screenshot visually now.";else if(visionPending>0&&!charging)now="New screenshots are ready for visual understanding when the phone is charging.";else if(visionPending>0)now="Visual Intelligence is waiting for its background worker.";else now="Cortex is caught up with new screenshot work.";headline.setText(now+"\n"+(charging?"Phone is charging.":"Phone is not charging."));headline.setTextColor((queued==0&&analyzing==0&&visionPending==0&&!"running".equals(ws))?ok:text);
        if(wi>0){KnowledgeItem k=db.getById(wi);current.setText((k==null?"Screenshot":clean(k.title))+"\n"+empty(stage,"Visual Intelligence")+(detail.isEmpty()?"":"\n"+clip(detail,180)));}else{long latest=currentVisualItem();KnowledgeItem k=latest>0?db.getById(latest):null;current.setText(k==null?"No screenshot available yet.":"Latest screenshot: "+clean(k.title)+"\nOpen the inspector to see the real image and its useful result.");}
        fast.setText(analyzed+" of "+total+" screenshots have searchable evidence"+(queued>0?" • "+queued+" waiting":"")+(analyzing>0?" • "+analyzing+" being read":"")+"\nThis is supporting text extraction, not the final understanding.");fastBar.setProgress(total==0?0:(int)Math.min(1000,(analyzed*1000L)/total));
        int backgroundTotal=visionDone+visionSkipped+visionFailed+visionPending;int finished=visionDone+visionSkipped+visionFailed;vision.setText(visionDone+" screenshots fully understood with strong vision\n"+visionSkipped+" protected/skipped locally • "+visionFailed+" failed • "+visionPending+" new screenshots waiting\nOld screenshots are not bulk-sent to cloud; open any one in the inspector to analyze it deliberately.");visionBar.setProgress(backgroundTotal==0?0:(int)Math.min(1000,(finished*1000L)/backgroundTotal));
        LocalLlmRuntime.State rt=LocalLlmRuntime.state(this);model.setText(LocalModelManager.installed(this)?"Local Qwen is ready for reasoning.\nLast self-test: "+String.format(Locale.US,"%.2f tokens/sec",rt.tokensPerSecond):"Local Qwen is not ready yet.");model.setTextColor(LocalModelManager.installed(this)?ok:warn);
        int memories=count(s,"SELECT COUNT(*) FROM knowledge_items");int txt=count(s,"SELECT COUNT(*) FROM knowledge_items WHERE COALESCE(extracted_text,'')<>''");storage.setText(memories+" original memories saved • "+txt+" have supporting extracted text • "+visionDone+" have visual understanding\nOriginal images remain in the Vault even when an analysis is skipped or replaced.");}
    long currentVisualItem(){long wi=VisualInsightStore.workerItem(this);if(wi>0)return wi;try(Cursor c=db.getReadableDatabase().rawQuery("SELECT id FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') ORDER BY created_at DESC LIMIT 1",null)){return c.moveToFirst()?c.getLong(0):0;}}
    boolean charging(){Intent i=registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));if(i==null)return false;int st=i.getIntExtra(BatteryManager.EXTRA_STATUS,-1);return st==BatteryManager.BATTERY_STATUS_CHARGING||st==BatteryManager.BATTERY_STATUS_FULL;}
    int count(SQLiteDatabase s,String q){try(Cursor c=s.rawQuery(q,null)){return c.moveToFirst()?c.getInt(0):0;}catch(Exception e){return 0;}}String clean(String x){if(x==null||x.trim().isEmpty())return"Screenshot";String s=x.trim();return s.length()>90?s.substring(0,90)+"…":s;}String clip(String s,int n){return s==null?"":(s.length()<=n?s:s.substring(0,n)+"…");}String empty(String s,String f){return s==null||s.trim().isEmpty()?f:s;}
}
