package com.kareem.cortex;

import android.app.Activity;
import android.content.Intent;
import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.RippleDrawable;
import android.os.Build;
import android.view.*;
import android.widget.LinearLayout;
import android.widget.TextView;

/** Cortex visual system: neutral hierarchy, one brand accent, semantic colors only where meaning requires them. */
public final class CortexUi {
    public static final int BG=Color.rgb(9,10,12),SURFACE=Color.rgb(17,18,21),SURFACE_2=Color.rgb(22,23,27),SURFACE_3=Color.rgb(29,30,35),TEXT=Color.rgb(244,244,242),MUTED=Color.rgb(166,168,174),FAINT=Color.rgb(104,107,114);
    public static final int BRAND=Color.rgb(132,143,255),RED=Color.rgb(239,91,86),ORANGE=Color.rgb(224,164,75),YELLOW=Color.rgb(204,176,94),GREEN=Color.rgb(111,185,132);
    public static final int ACCENT=BRAND,SIGNAL=RED,AMBER=ORANGE,SAGE=GREEN,INFO=BRAND,VIOLET=BRAND,BORDER=Color.rgb(42,44,51),BORDER_SOFT=Color.rgb(31,33,39),HAIRLINE=Color.argb(28,255,255,255),COPPER=ORANGE,CORAL=RED,GOLD=YELLOW;
    private CortexUi(){}
    public static int dp(Activity a,int v){return(int)(v*a.getResources().getDisplayMetrics().density+.5f);}
    public static void applyWindow(Activity a){Window w=a.getWindow();w.setStatusBarColor(BG);w.setNavigationBarColor(BG);if(Build.VERSION.SDK_INT>=29)w.setNavigationBarContrastEnforced(false);if(Build.VERSION.SDK_INT>=23)w.getDecorView().setSystemUiVisibility(0);}
    public static void fitSystemBars(Activity a,View root){final int pl=root.getPaddingLeft(),pt=root.getPaddingTop(),pr=root.getPaddingRight(),pb=root.getPaddingBottom();root.setOnApplyWindowInsetsListener((v,insets)->{int l=0,t=0,r=0,b=0;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets x=insets.getInsets(WindowInsets.Type.systemBars());l=x.left;t=x.top;r=x.right;b=x.bottom;}else{l=insets.getSystemWindowInsetLeft();t=insets.getSystemWindowInsetTop();r=insets.getSystemWindowInsetRight();b=insets.getSystemWindowInsetBottom();}v.setPadding(pl+l,pt+t,pr+r,pb+b);return insets;});root.requestApplyInsets();}
    public static GradientDrawable round(Activity a,int fill,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(a,radius));if(stroke!=Color.TRANSPARENT)g.setStroke(dp(a,1),stroke);return g;}
    public static GradientDrawable gradient(Activity a,int start,int end,int stroke,int radius){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{start,end});g.setCornerRadius(dp(a,radius));if(stroke!=Color.TRANSPARENT)g.setStroke(dp(a,1),stroke);return g;}
    public static GradientDrawable velvet(Activity a,int radius){return gradient(a,SURFACE_2,SURFACE,HAIRLINE,radius);}public static GradientDrawable matte(Activity a,int radius){return round(a,SURFACE,HAIRLINE,radius);}public static View divider(Activity a){View v=new View(a);v.setBackgroundColor(BORDER_SOFT);return v;}
    public static<T extends View>T raised(Activity a,T v,int e){if(Build.VERSION.SDK_INT>=21){v.setElevation(dp(a,e));v.setTranslationZ(0f);}return v;}public static CortexGlyphView glyph(Activity a,String k,int c,boolean d){CortexGlyphView g=new CortexGlyphView(a,k,c,d);raised(a,g,2);return g;}
    public static View pressable(Activity a,View v,GradientDrawable base){if(Build.VERSION.SDK_INT>=21)v.setBackground(new RippleDrawable(ColorStateList.valueOf(Color.argb(18,255,255,255)),base,null));else v.setBackground(base);v.setClickable(true);v.setFocusable(true);raised(a,v,2);v.setOnTouchListener((x,e)->{if(Build.VERSION.SDK_INT>=21){if(e.getActionMasked()==MotionEvent.ACTION_DOWN){x.setTranslationZ(-dp(a,1));x.setScaleX(.992f);x.setScaleY(.992f);}else if(e.getActionMasked()==MotionEvent.ACTION_UP||e.getActionMasked()==MotionEvent.ACTION_CANCEL){x.setTranslationZ(0);x.setScaleX(1);x.setScaleY(1);}}return false;});return v;}
    public static TextView text(Activity a,String s,int sp,int c){TextView v=new TextView(a);v.setTextSize(sp);v.setTextColor(c);v.setLineSpacing(0,1.08f);CortexTextUi.setReadable(v,s==null?"":s);return v;}public static TextView plain(Activity a,String s,int sp,int c){TextView v=new TextView(a);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setPlain(v,s==null?"":s);return v;}public static void medium(TextView v){v.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));}public static void bold(TextView v){v.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));}
    public static LinearLayout card(Activity a,int r){LinearLayout c=new LinearLayout(a);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(a,16),dp(a,15),dp(a,16),dp(a,15));c.setBackground(round(a,SURFACE,HAIRLINE,r));raised(a,c,2);return c;}
    public static TextView chip(Activity a,String l,int c,boolean strong){TextView v=plain(a,l,strong?11:10,c);if(strong)medium(v);v.setGravity(Gravity.CENTER);v.setPadding(dp(a,11),0,dp(a,11),0);v.setBackground(round(a,Color.argb(strong?16:8,Color.red(c),Color.green(c),Color.blue(c)),Color.argb(strong?68:42,Color.red(c),Color.green(c),Color.blue(c)),999));return v;}
    public static TextView section(Activity a,String t){TextView h=plain(a,t,11,MUTED);medium(h);h.setPadding(0,dp(a,22),0,dp(a,9));return h;}public static TextView action(Activity a,String l,int c,boolean filled){TextView b=plain(a,l,12,c);medium(b);b.setGravity(Gravity.CENTER);b.setPadding(dp(a,14),0,dp(a,14),0);pressable(a,b,round(a,Color.argb(filled?20:6,Color.red(c),Color.green(c),Color.blue(c)),Color.argb(filled?90:48,Color.red(c),Color.green(c),Color.blue(c)),15));return b;}
    public static int semanticFor(String key){if(key==null)return BRAND;String k=key.toLowerCase();if(k.contains("urgent")||k.contains("error")||k.contains("alert"))return RED;if(k.contains("wait")||k.contains("remind")||k.contains("attention"))return ORANGE;if(k.contains("complete")||k.contains("resolved")||k.contains("healthy"))return GREEN;return BRAND;}

    /** Primary mental model: Now → Inbox → Library → Ask. Capture is the center action, not a destination. */
    public static void addBottomNav(Activity a,LinearLayout root,String selected,Runnable ignored){String current=primeKey(selected);LinearLayout bar=new LinearLayout(a);bar.setGravity(Gravity.CENTER);bar.setPadding(dp(a,7),dp(a,5),dp(a,7),dp(a,7));bar.setBackground(round(a,Color.rgb(13,14,17),Color.argb(34,255,255,255),22));addNav(a,bar,"today","Now",current,CompactTodayActivity.class);addNav(a,bar,"inbox","Inbox",current,InboxActivity.class);addCapture(a,bar);addNav(a,bar,"library","Library",current,ProposalPeopleProjectsActivity.class);addNav(a,bar,"ask","Ask",current,ProposalAskCortexActivity.class);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(a,66));p.setMargins(dp(a,12),dp(a,4),dp(a,12),dp(a,9));root.addView(bar,p);fitSystemBars(a,root);}
    private static void addCapture(Activity a,LinearLayout bar){TextView v=plain(a,"+",26,Color.WHITE);v.setGravity(Gravity.CENTER);v.setBackground(round(a,BRAND,Color.TRANSPARENT,999));raised(a,v,5);v.setOnClickListener(x->{try{Intent i=new Intent(a,InboxActivity.class);i.putExtra("focus_composer",true);i.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT|Intent.FLAG_ACTIVITY_SINGLE_TOP);a.startActivity(i);}catch(Throwable ignored){}});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(dp(a,50),dp(a,50));p.setMargins(dp(a,5),0,dp(a,5),0);bar.addView(v,p);}
    private static String primeKey(String s){if("home".equals(s)||"focus".equals(s)||"brief".equals(s)||"today".equals(s)||"now".equals(s))return"today";if("vault".equals(s)||"people".equals(s)||"memory".equals(s)||"world".equals(s)||"projects".equals(s)||"library".equals(s))return"library";if("ask".equals(s)||"brain".equals(s)||"cortex".equals(s))return"ask";if("input".equals(s)||"capture".equals(s)||"inbox".equals(s))return"inbox";return s==null?"":s;}
    private static void addNav(Activity a,LinearLayout bar,String key,String label,String selected,Class<?> target){boolean on=key.equals(selected);int color=on?BRAND:MUTED;TextView v=plain(a,label,10,color);if(on)medium(v);v.setGravity(Gravity.CENTER);if(on)v.setBackground(round(a,Color.argb(16,Color.red(BRAND),Color.green(BRAND),Color.blue(BRAND)),Color.argb(42,Color.red(BRAND),Color.green(BRAND),Color.blue(BRAND)),14));else v.setOnClickListener(x->{try{Intent i=new Intent(a,target);i.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT|Intent.FLAG_ACTIVITY_SINGLE_TOP);a.startActivity(i);}catch(Throwable ignored){}});bar.addView(v,new LinearLayout.LayoutParams(0,-1,1));}
}
