package com.kareem.cortex;

import android.app.Activity;
import android.content.Intent;
import android.content.res.ColorStateList;
import android.graphics.*;
import android.graphics.drawable.Drawable;
import android.graphics.drawable.GradientDrawable;
import android.graphics.drawable.RippleDrawable;
import android.os.Build;
import android.view.*;
import android.widget.LinearLayout;
import android.widget.TextView;

/** Cortex visual system: approved AMOLED graphite + faded lime. Preserve IA and behavior. */
public final class CortexUi {
    public static final int BG=Color.rgb(3,4,3),SURFACE=Color.rgb(12,13,12),SURFACE_2=Color.rgb(17,19,17),SURFACE_3=Color.rgb(23,25,22),TEXT=Color.rgb(245,247,241),MUTED=Color.rgb(161,163,157),FAINT=Color.rgb(92,95,89);
    public static final int BRAND=Color.rgb(185,218,77),AURORA=Color.rgb(130,149,60),RED=Color.rgb(239,92,73),ORANGE=Color.rgb(242,154,49),YELLOW=Color.rgb(240,184,56),GREEN=Color.rgb(111,202,86);
    public static final int ACCENT=BRAND,SIGNAL=BRAND,AMBER=YELLOW,SAGE=GREEN,INFO=BRAND,VIOLET=AURORA,BORDER=Color.rgb(43,46,41),BORDER_SOFT=Color.rgb(28,30,27),HAIRLINE=Color.argb(42,220,230,210),COPPER=ORANGE,CORAL=RED,GOLD=YELLOW,LIME=BRAND,OLIVE=AURORA;
    private CortexUi(){}
    public static int dp(Activity a,int v){return(int)(v*a.getResources().getDisplayMetrics().density+.5f);}
    public static Drawable aurora(Activity a){return round(a,BG,Color.TRANSPARENT,0);}
    public static void applyWindow(Activity a){Window w=a.getWindow();w.setStatusBarColor(BG);w.setNavigationBarColor(BG);w.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);if(Build.VERSION.SDK_INT>=29)w.setNavigationBarContrastEnforced(false);if(Build.VERSION.SDK_INT>=23)w.getDecorView().setSystemUiVisibility(0);}
    /** Keep content clear of system bars and IME. */
    public static void fitSystemBars(Activity a,View root){final int pl=root.getPaddingLeft(),pt=root.getPaddingTop(),pr=root.getPaddingRight(),pb=root.getPaddingBottom();root.setOnApplyWindowInsetsListener((v,insets)->{int l=0,t=0,r=0,b=0;if(Build.VERSION.SDK_INT>=30){android.graphics.Insets sys=insets.getInsets(WindowInsets.Type.systemBars());android.graphics.Insets ime=insets.getInsets(WindowInsets.Type.ime());l=sys.left;t=sys.top;r=sys.right;b=Math.max(sys.bottom,ime.bottom);}else{l=insets.getSystemWindowInsetLeft();t=insets.getSystemWindowInsetTop();r=insets.getSystemWindowInsetRight();b=insets.getSystemWindowInsetBottom();}v.setPadding(pl+l,pt+t,pr+r,pb+b);return insets;});root.requestApplyInsets();}
    public static GradientDrawable round(Activity a,int fill,int stroke,int radius){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(a,radius));if(stroke!=Color.TRANSPARENT)g.setStroke(dp(a,1),stroke);return g;}
    public static GradientDrawable gradient(Activity a,int start,int end,int stroke,int radius){GradientDrawable g=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{start,end});g.setCornerRadius(dp(a,radius));if(stroke!=Color.TRANSPARENT)g.setStroke(dp(a,1),stroke);return g;}
    public static GradientDrawable velvet(Activity a,int radius){return gradient(a,SURFACE_2,SURFACE,HAIRLINE,radius);}public static GradientDrawable matte(Activity a,int radius){return round(a,SURFACE,HAIRLINE,radius);}public static View divider(Activity a){View v=new View(a);v.setBackgroundColor(BORDER_SOFT);return v;}
    public static<T extends View>T raised(Activity a,T v,int e){if(Build.VERSION.SDK_INT>=21){v.setElevation(dp(a,e));v.setTranslationZ(0f);}return v;}public static CortexGlyphView glyph(Activity a,String k,int c,boolean d){CortexGlyphView g=new CortexGlyphView(a,k,c,d);raised(a,g,3);return g;}
    public static View pressable(Activity a,View v,GradientDrawable base){if(Build.VERSION.SDK_INT>=21)v.setBackground(new RippleDrawable(ColorStateList.valueOf(Color.argb(24,185,218,77)),base,null));else v.setBackground(base);v.setClickable(true);v.setFocusable(true);raised(a,v,3);v.setOnTouchListener((x,e)->{if(Build.VERSION.SDK_INT>=21){if(e.getActionMasked()==MotionEvent.ACTION_DOWN){x.setTranslationZ(-dp(a,1));x.setScaleX(.986f);x.setScaleY(.986f);}else if(e.getActionMasked()==MotionEvent.ACTION_UP||e.getActionMasked()==MotionEvent.ACTION_CANCEL){x.animate().scaleX(1).scaleY(1).translationZ(0).setDuration(110).start();}}return false;});return v;}
    public static TextView text(Activity a,String s,int sp,int c){TextView v=new TextView(a);v.setTextSize(sp);v.setTextColor(c);v.setLineSpacing(0,1.08f);CortexTextUi.setReadable(v,s==null?"":s);return v;}public static TextView plain(Activity a,String s,int sp,int c){TextView v=new TextView(a);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setPlain(v,s==null?"":s);return v;}public static void medium(TextView v){v.setTypeface(Typeface.create("sans-serif-medium",Typeface.NORMAL));}public static void bold(TextView v){v.setTypeface(Typeface.create("sans-serif",Typeface.BOLD));}
    public static LinearLayout card(Activity a,int r){LinearLayout c=new LinearLayout(a);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(a,17),dp(a,16),dp(a,17),dp(a,16));c.setBackground(velvet(a,r));raised(a,c,3);return c;}
    public static TextView chip(Activity a,String l,int c,boolean strong){TextView v=plain(a,l,strong?11:10,strong?TEXT:c);if(strong)medium(v);v.setGravity(Gravity.CENTER);v.setPadding(dp(a,12),0,dp(a,12),0);int fill=Color.argb(strong?24:12,Color.red(c),Color.green(c),Color.blue(c));int stroke=Color.argb(strong?92:54,Color.red(c),Color.green(c),Color.blue(c));v.setBackground(round(a,fill,stroke,999));return v;}
    public static TextView section(Activity a,String t){TextView h=plain(a,t,11,MUTED);medium(h);h.setPadding(0,dp(a,24),0,dp(a,10));return h;}public static TextView action(Activity a,String l,int c,boolean filled){TextView b=plain(a,l,12,filled?BG:c);medium(b);b.setGravity(Gravity.CENTER);b.setPadding(dp(a,14),0,dp(a,14),0);GradientDrawable base=filled?gradient(a,BRAND,Color.rgb(201,226,110),Color.TRANSPARENT,16):round(a,Color.argb(14,Color.red(c),Color.green(c),Color.blue(c)),Color.argb(70,Color.red(c),Color.green(c),Color.blue(c)),16);pressable(a,b,base);return b;}
    public static int semanticFor(String key){if(key==null)return BRAND;String k=key.toLowerCase();if(k.contains("urgent")||k.contains("error")||k.contains("alert"))return RED;if(k.contains("wait")||k.contains("remind")||k.contains("attention"))return YELLOW;if(k.contains("complete")||k.contains("resolved")||k.contains("healthy"))return GREEN;return BRAND;}

    /** Approved floating dock: Now / Inbox / Capture / Library / Ask. */
    public static void addBottomNav(Activity a,LinearLayout root,String selected,Runnable ignored){String current=primeKey(selected);LinearLayout bar=new LinearLayout(a);bar.setGravity(Gravity.CENTER);bar.setPadding(dp(a,8),dp(a,6),dp(a,8),dp(a,6));bar.setBackground(round(a,Color.rgb(10,11,10),BORDER,25));addNav(a,bar,"today","Now","clock",current,CompactTodayActivity.class);addNav(a,bar,"inbox","Inbox","note",current,InboxActivity.class);addCapture(a,bar);addNav(a,bar,"library","Library","file",current,ProposalPeopleProjectsActivity.class);addNav(a,bar,"ask","Ask","brain",current,ProposalAskCortexActivity.class);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(a,76));p.setMargins(dp(a,14),dp(a,4),dp(a,14),dp(a,10));root.addView(bar,p);raised(a,bar,9);fitSystemBars(a,root);}
    private static void addCapture(Activity a,LinearLayout bar){LinearLayout wrap=new LinearLayout(a);wrap.setGravity(Gravity.CENTER);TextView v=plain(a,"+",38,BG);v.setTypeface(Typeface.create("sans-serif-light",Typeface.NORMAL));v.setGravity(Gravity.CENTER);v.setBackground(round(a,BRAND,Color.rgb(205,229,116),999));raised(a,v,12);v.setOnClickListener(x->{try{Intent i=new Intent(a,InboxActivity.class);i.putExtra("focus_composer",true);i.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT|Intent.FLAG_ACTIVITY_SINGLE_TOP);a.startActivity(i);}catch(Throwable ignored){}});wrap.addView(v,new LinearLayout.LayoutParams(dp(a,60),dp(a,60)));bar.addView(wrap,new LinearLayout.LayoutParams(dp(a,70),-1));}
    private static String primeKey(String s){if("home".equals(s)||"focus".equals(s)||"brief".equals(s)||"today".equals(s)||"now".equals(s))return"today";if("vault".equals(s)||"people".equals(s)||"memory".equals(s)||"world".equals(s)||"projects".equals(s)||"library".equals(s))return"library";if("ask".equals(s)||"brain".equals(s)||"cortex".equals(s))return"ask";if("input".equals(s)||"capture".equals(s)||"inbox".equals(s))return"inbox";return s==null?"":s;}
    private static void addNav(Activity a,LinearLayout bar,String key,String label,String glyph,String selected,Class<?> target){boolean on=key.equals(selected);LinearLayout item=new LinearLayout(a);item.setOrientation(LinearLayout.VERTICAL);item.setGravity(Gravity.CENTER);if(on)item.setBackground(round(a,Color.argb(16,185,218,77),Color.argb(60,185,218,77),18));CortexGlyphView g=CortexUi.glyph(a,glyph,on?BRAND:FAINT,false);item.addView(g,new LinearLayout.LayoutParams(dp(a,32),dp(a,32)));TextView t=plain(a,label,9,on?BRAND:MUTED);if(on)medium(t);t.setGravity(Gravity.CENTER);item.addView(t,new LinearLayout.LayoutParams(-1,dp(a,18)));if(!on)item.setOnClickListener(x->{try{Intent i=new Intent(a,target);i.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT|Intent.FLAG_ACTIVITY_SINGLE_TOP);a.startActivity(i);}catch(Throwable ignored){}});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(a,2),0,dp(a,2),0);bar.addView(item,p);}
}
