package com.kareem.cortex;

import android.content.*;
import android.database.Cursor;
import org.json.*;
import java.util.*;
import java.util.concurrent.Callable;

/**
 * Goal-driven experimental user journeys.
 *
 * This is intentionally not a click-coverage robot. Each journey starts with a user goal and only
 * passes when the expected terminal UI/data state is observed. The accessibility service is merely
 * the test hand; the report is about Cortex behavior.
 */
public final class CortexExperimentalUserSuite {
    public enum Status { PASS, CONFIRMED_APP_BUG, QUALITY_PROBLEM, TEST_GAP, HARNESS_ISSUE }

    public static final class Journey {
        public String id="",goal="",expected="",actual="",severity="",evidence="";
        public Status status=Status.HARNESS_ISSUE;public long durationMs=0;public int attempts=1;
        JSONObject json(){JSONObject o=new JSONObject();try{o.put("id",id);o.put("goal",goal);o.put("status",status.name());o.put("severity",severity);o.put("expected",expected);o.put("actual",actual);o.put("duration_ms",durationMs);o.put("attempts",attempts);o.put("evidence",evidence);}catch(Exception ignored){}return o;}
    }

    public static final class Report {
        public long startedAt,finishedAt;public final ArrayList<Journey> journeys=new ArrayList<>();public String fatal="";
        public int count(Status s){int n=0;for(Journey j:journeys)if(j.status==s)n++;return n;}
        public JSONObject json(){JSONObject o=new JSONObject();JSONArray a=new JSONArray();try{o.put("schema_version",1);o.put("suite","CORTEX_EXPERIMENTAL_USER_JOURNEYS");o.put("started_at",startedAt);o.put("finished_at",finishedAt);o.put("duration_ms",Math.max(0,finishedAt-startedAt));o.put("passed",count(Status.PASS));o.put("confirmed_app_bugs",count(Status.CONFIRMED_APP_BUG));o.put("quality_problems",count(Status.QUALITY_PROBLEM));o.put("test_gaps",count(Status.TEST_GAP));o.put("harness_issues",count(Status.HARNESS_ISSUE));o.put("fatal",fatal);for(Journey j:journeys)a.put(j.json());o.put("journeys",a);}catch(Exception ignored){}return o;}
        public String markdown(){StringBuilder b=new StringBuilder();b.append("# CORTEX EXPERIMENTAL USER TEST\n\n");b.append("- Journeys: **").append(journeys.size()).append("**\n");b.append("- Passed: **").append(count(Status.PASS)).append("**\n");b.append("- Confirmed app bugs: **").append(count(Status.CONFIRMED_APP_BUG)).append("**\n");b.append("- Quality problems: **").append(count(Status.QUALITY_PROBLEM)).append("**\n");b.append("- Test gaps: **").append(count(Status.TEST_GAP)).append("**\n");b.append("- Harness issues: **").append(count(Status.HARNESS_ISSUE)).append("**\n");b.append("- Duration: ").append(Math.max(0,finishedAt-startedAt)).append(" ms\n");if(!fatal.isEmpty())b.append("- Fatal suite error: `").append(md(fatal)).append("`\n");section(b,"CONFIRMED CORTEX PROBLEMS",Status.CONFIRMED_APP_BUG);section(b,"QUALITY PROBLEMS",Status.QUALITY_PROBLEM);section(b,"TEST GAPS",Status.TEST_GAP);section(b,"HARNESS ISSUES",Status.HARNESS_ISSUE);section(b,"PASSED JOURNEYS",Status.PASS);b.append("\n## JOURNEY DETAILS\n");for(Journey j:journeys){b.append("\n### ").append(j.id).append(" · ").append(j.status).append(" · ").append(j.goal).append("\n\n");if(!j.severity.isEmpty())b.append("- Severity: **").append(j.severity).append("**\n");b.append("- Expected: ").append(md(j.expected)).append("\n- Actual: ").append(md(j.actual)).append("\n- Duration: ").append(j.durationMs).append(" ms\n- Attempts: ").append(j.attempts).append("\n");if(!j.evidence.isEmpty())b.append("- Evidence: ").append(md(j.evidence)).append("\n");}return b.toString();}
        private void section(StringBuilder b,String title,Status s){b.append("\n## ").append(title).append("\n");boolean any=false;for(Journey j:journeys)if(j.status==s){any=true;b.append("\n- **").append(j.id).append("** · ").append(j.goal);if(!j.severity.isEmpty())b.append(" · ").append(j.severity);b.append("\n  - Expected: ").append(md(j.expected)).append("\n  - Actual: ").append(md(j.actual)).append("\n");}if(!any)b.append("\nNone.\n");}
        private static String md(String s){return safe(s).replace("\n"," ").replace("|","\\|");}
    }

    private final Context app;private final Report report=new Report();
    private CortexExperimentalUserSuite(Context c){app=c.getApplicationContext();}
    public static Report run(Context c){return new CortexExperimentalUserSuite(c).runAll();}

    private Report runAll(){report.startedAt=System.currentTimeMillis();try{
        CortexRobotFixtures.prepare(app);
        if(!CortexScreenAccessibilityService.connected()){
            add("J00","Operate Cortex through the same UI a user sees","Accessibility test hand connected","Accessibility service is not connected",Status.HARNESS_ISSUE,"BLOCKER","Enable Cortex Accessibility access; no app behavior was judged",0);return finish();
        }
        journeyTextCapture();journeyBriefDedup();journeyLocalProposal();journeyBrainTerminal();journeyPeopleProjects();journeyHealthTimeline();journeyPromptLibrary();journeyVaultFilters();
        gap("J09","First-run permissions walkthrough","Clean-install onboarding reaches every required gate and resumes correctly","Not executed in this sandbox run because it requires resetting first-run device/account state safely");
        gap("J10","Real Health Connect permission and provider sync","Grant scopes and verify provider-origin data end to end","Local health timeline is tested separately; real Health Connect authorization is device-owned and was not mutated");
        gap("J11","Photo/PDF picker import with known fixture","Known media selected through Android picker persists and reaches analyzed result","System picker selection is intentionally not automated in this deterministic suite yet");
    }catch(Throwable e){report.fatal=e.getClass().getSimpleName()+": "+safe(e.getMessage());}finally{try{CortexRobotFixtures.cleanup(app);}catch(Throwable ignored){}}return finish();}
    private Report finish(){report.finishedAt=System.currentTimeMillis();return report;}

    private void journeyTextCapture(){final long start=System.currentTimeMillis();final String value="Cortex journey fixture: 3D printing عربي English round trip";try{
        int before=count("SELECT COUNT(*) FROM knowledge_items WHERE raw_text=?",value);Intent i=new Intent(app,ProposalCaptureActivity.class).putExtra("mode","text").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);app.startActivity(i);
        if(!waitText("Type or paste",5000)){bugOrHarness("J01","Capture a text note and find the exact saved evidence","Exact entered text exists in sandbox Vault after Capture","Text capture editor did not appear",Status.CONFIRMED_APP_BUG,"P1",start);return;}
        if(!setEditable("Type or paste",value)){bugOrHarness("J01","Capture a text note and find the exact saved evidence","Exact entered text exists in sandbox Vault after Capture","Could not enter fixture text through the visible editor",Status.HARNESS_ISSUE,"",start);return;}
        if(!click("Capture")){bugOrHarness("J01","Capture a text note and find the exact saved evidence","Exact entered text exists in sandbox Vault after Capture","Visible Capture action could not be pressed",Status.HARNESS_ISSUE,"",start);return;}
        boolean saved=waitUntil(()->count("SELECT COUNT(*) FROM knowledge_items WHERE raw_text=?",value)>before,5000);String ev=snapshotText();
        add("J01","Capture a text note and find the exact saved evidence","Exact entered text exists in sandbox Vault after Capture",saved?"Text persisted through the production capture UI":"Capture returned without the exact text appearing in the Vault",saved?Status.PASS:Status.CONFIRMED_APP_BUG,saved?"":"P0",clip(ev,650),System.currentTimeMillis()-start);
    }catch(Throwable e){exceptionJourney("J01","Capture a text note and find the exact saved evidence",e,start);}}

    private void journeyBriefDedup(){long start=System.currentTimeMillis();String phrase="Compare the two approved material options before issue.";try{launch(ProposalBriefActivity.class);if(!waitText(phrase,6000)){add("J02","Read the Brief without duplicated semantic items","Known decision appears once in the visible Brief","Decision fixture did not appear in Brief",Status.CONFIRMED_APP_BUG,"P1",clip(snapshotText(),700),elapsed(start));return;}String t=snapshotText();int n=occurrences(t,phrase);add("J02","Read the Brief without duplicated semantic items","Known decision appears exactly once in the visible Brief","Decision occurrence count = "+n,n==1?Status.PASS:Status.CONFIRMED_APP_BUG,n==1?"":"P1",clip(t,700),elapsed(start));}catch(Throwable e){exceptionJourney("J02","Read the Brief without duplicated semantic items",e,start);}}

    private void journeyLocalProposal(){long start=System.currentTimeMillis();try{launch(ProposalBriefActivity.class);if(!waitText("Prepare a note",6000)){add("J03","Approve a suggested local note and verify it really exists","Approved KNOWLEDGE_NOTE creates a NOTE row in sandbox Cortex","Useful Next Move did not expose the fixture note action",Status.QUALITY_PROBLEM,"P1",clip(snapshotText(),700),elapsed(start));return;}int before=count("SELECT COUNT(*) FROM derived_items WHERE kind='NOTE' AND metadata_json LIKE '%\"created_from\":\"brain_action\"%'");if(!click("Prepare a note")||!waitText("ADD TO CORTEX",3000)){add("J03","Approve a suggested local note and verify it really exists","Approved KNOWLEDGE_NOTE creates a NOTE row in sandbox Cortex","Proposal preview/approval UI did not reach ADD TO CORTEX",Status.CONFIRMED_APP_BUG,"P1",clip(snapshotText(),700),elapsed(start));return;}click("ADD TO CORTEX");boolean made=waitUntil(()->count("SELECT COUNT(*) FROM derived_items WHERE kind='NOTE' AND metadata_json LIKE '%\"created_from\":\"brain_action\"%'")>before,3000);add("J03","Approve a suggested local note and verify it really exists","Approved KNOWLEDGE_NOTE creates a NOTE row in sandbox Cortex",made?"Local note persisted after explicit approval":"Approval closed without a new NOTE row",made?Status.PASS:Status.CONFIRMED_APP_BUG,made?"":"P0",clip(snapshotText(),650),elapsed(start));}catch(Throwable e){exceptionJourney("J03","Approve a suggested local note and verify it really exists",e,start);}}

    private void journeyBrainTerminal(){long start=System.currentTimeMillis();try{Intent i=new Intent(app,ProposalAskCortexActivity.class).putExtra("prefill","What still needs my attention?").addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);app.startActivity(i);if(!waitText("Ask Brain",5000)){add("J04","Ask Brain and wait for the actual final answer","Brain leaves thinking state and returns a grounded answer or explicit terminal failure","Brain screen did not become ready",Status.CONFIRMED_APP_BUG,"P0",clip(snapshotText(),700),elapsed(start));return;}if(!click("Ask")){add("J04","Ask Brain and wait for the actual final answer","Brain leaves thinking state and returns a grounded answer or explicit terminal failure","Ask control could not be executed",Status.HARNESS_ISSUE,"",clip(snapshotText(),700),elapsed(start));return;}
        boolean terminal=waitUntil(()->{String x=snapshotText();return !busy(x)&&(containsAny(x,"Thursday","client feedback","material options","Prepare the revised proposal","Brain stopped safely"));},30000);String t=snapshotText();boolean failed=t.contains("Brain stopped safely");boolean grounded=containsAny(t,"Thursday","client feedback","material options","Prepare the revised proposal");Status st=!terminal?Status.QUALITY_PROBLEM:(failed||!grounded?Status.QUALITY_PROBLEM:Status.PASS);String actual=!terminal?"Still busy or no grounded terminal answer after 30 seconds":failed?"Brain reached an explicit failure state":"Terminal grounded answer became visible";add("J04","Ask Brain and wait for the actual final answer","Brain leaves thinking state and returns a grounded answer or explicit terminal failure",actual,st,st==Status.PASS?"":"P1",clip(t,900),elapsed(start));
    }catch(Throwable e){exceptionJourney("J04","Ask Brain and wait for the actual final answer",e,start);}}

    private void journeyPeopleProjects(){long start=System.currentTimeMillis();try{launch(ProposalPeopleProjectsActivity.class);boolean person=waitText("Robot Test Person",7000);boolean projectsClick=click("Projects");boolean project=projectsClick&&waitText("Robot Test Project",6000);Status st=person&&project?Status.PASS:Status.CONFIRMED_APP_BUG;add("J05","See confirmed People and Projects grounded in Cortex","Confirmed fixture person appears under People and confirmed fixture project under Projects","person="+person+", project="+project,st,st==Status.PASS?"":"P1",clip(snapshotText(),800),elapsed(start));}catch(Throwable e){exceptionJourney("J05","See confirmed People and Projects grounded in Cortex",e,start);}}

    private void journeyHealthTimeline(){long start=System.currentTimeMillis();try{launch(HealthFollowupActivity.class);boolean opened=waitText("HEALTH SOURCES",5000);int metrics=count("SELECT COUNT(*) FROM health_metrics");boolean visible=opened&&waitOrScrollAny(new String[]{"6842","72","98","3 measurements"},5000);Status st=metrics>=3&&visible?Status.PASS:(metrics>=3?Status.CONFIRMED_APP_BUG:Status.HARNESS_ISSUE);add("J06","Open Health follow-up and see existing grounded measurements","Synthetic health measurements already in Cortex appear in the Health timeline","sandbox metrics="+metrics+", measurement visible="+visible,st,st==Status.PASS?"":(st==Status.CONFIRMED_APP_BUG?"P1":""),clip(snapshotText(),850),elapsed(start));}catch(Throwable e){exceptionJourney("J06","Open Health follow-up and see existing grounded measurements",e,start);}}

    private void journeyPromptLibrary(){long start=System.currentTimeMillis();try{launch(PromptLibraryActivity.class);if(!waitText("Add recent Cortex text as prompt",5000)){add("J07","Add existing Cortex text to Prompt Library","Choosing Meeting follow-up creates a reusable prompt row","Prompt Library did not become ready",Status.CONFIRMED_APP_BUG,"P1",clip(snapshotText(),700),elapsed(start));return;}int before=count("SELECT COUNT(*) FROM prompt_library_items WHERE pinned=1");if(!click("Add recent Cortex text as prompt")||!waitText("Add to Prompt Library",4000)){add("J07","Add existing Cortex text to Prompt Library","Choosing Meeting follow-up creates a reusable prompt row","Prompt chooser did not open",Status.CONFIRMED_APP_BUG,"P1",clip(snapshotText(),700),elapsed(start));return;}if(!click("Meeting follow-up")){add("J07","Add existing Cortex text to Prompt Library","Choosing Meeting follow-up creates a reusable prompt row","Meeting follow-up candidate was not selectable",Status.HARNESS_ISSUE,"",clip(snapshotText(),700),elapsed(start));return;}boolean made=waitUntil(()->count("SELECT COUNT(*) FROM prompt_library_items WHERE pinned=1")>before,5000);add("J07","Add existing Cortex text to Prompt Library","Choosing Meeting follow-up creates a reusable prompt row",made?"Prompt was pinned and persisted":"Chooser closed without a new pinned prompt",made?Status.PASS:Status.CONFIRMED_APP_BUG,made?"":"P1",clip(snapshotText(),750),elapsed(start));}catch(Throwable e){exceptionJourney("J07","Add existing Cortex text to Prompt Library",e,start);}}

    private void journeyVaultFilters(){long start=System.currentTimeMillis();try{launch(VaultActivity.class);boolean all=waitText("Prescription image",5000);boolean img=click("Images")&&waitText("Prescription image",3000);click("All");boolean voice=click("Voice")&&waitText("Voice note",3000);click("All");boolean text=click("Text")&&waitText("Meeting follow-up",3000);Status st=all&&img&&voice&&text?Status.PASS:Status.CONFIRMED_APP_BUG;add("J08","Filter the Vault by real evidence type","Images shows image fixture, Voice shows voice fixture, Text shows text fixture","all="+all+", images="+img+", voice="+voice+", text="+text,st,st==Status.PASS?"":"P1",clip(snapshotText(),800),elapsed(start));}catch(Throwable e){exceptionJourney("J08","Filter the Vault by real evidence type",e,start);}}

    private void gap(String id,String goal,String expected,String actual){add(id,goal,expected,actual,Status.TEST_GAP,"",actual,0);}
    private void exceptionJourney(String id,String goal,Throwable e,long start){add(id,goal,"Journey reaches its expected terminal state","Test harness exception: "+e.getClass().getSimpleName(),Status.HARNESS_ISSUE,"",safe(e.getMessage()),elapsed(start));}
    private void bugOrHarness(String id,String goal,String expected,String actual,Status status,String severity,long start){add(id,goal,expected,actual,status,severity,clip(snapshotText(),700),elapsed(start));}
    private void add(String id,String goal,String expected,String actual,Status status,String severity,String evidence,long duration){Journey j=new Journey();j.id=id;j.goal=goal;j.expected=expected;j.actual=actual;j.status=status;j.severity=severity;j.evidence=evidence;j.durationMs=duration;report.journeys.add(j);}

    private void launch(Class<?> cls)throws Exception{Intent i=new Intent(app,cls).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);app.startActivity(i);Thread.sleep(180);}
    private boolean click(String needle){List<CortexScreenAccessibilityService.RobotNode> xs=CortexScreenAccessibilityService.robotClickableNodes();CortexScreenAccessibilityService.RobotNode best=null;String n=norm(needle);for(CortexScreenAccessibilityService.RobotNode x:xs){if(!x.enabled)continue;String l=norm(x.label);if(l.equals(n)){best=x;break;}if(l.contains(n)&&(best==null||x.label.length()<best.label.length()))best=x;}return best!=null&&CortexScreenAccessibilityService.robotClick(best.path);}
    private boolean setEditable(String hint,String value){List<CortexScreenAccessibilityService.RobotNode> xs=CortexScreenAccessibilityService.robotEditableNodes();CortexScreenAccessibilityService.RobotNode best=null;String h=norm(hint);for(CortexScreenAccessibilityService.RobotNode x:xs){String l=norm(x.label);if(l.contains(h)){best=x;break;}if(best==null)best=x;}return best!=null&&CortexScreenAccessibilityService.robotSetText(best.path,value);}
    private boolean waitText(String needle,long ms){return waitUntil(()->norm(snapshotText()).contains(norm(needle)),ms);}
    private boolean waitOrScrollAny(String[] needles,long ms){long end=System.currentTimeMillis()+ms;while(System.currentTimeMillis()<end){String t=snapshotText();for(String n:needles)if(t.contains(n))return true;if(!CortexScreenAccessibilityService.robotScrollForward())sleep(120);else sleep(220);}return false;}
    private boolean waitUntil(Callable<Boolean> c,long ms){long end=System.currentTimeMillis()+ms;while(System.currentTimeMillis()<end){try{if(Boolean.TRUE.equals(c.call()))return true;}catch(Throwable ignored){}sleep(120);}try{return Boolean.TRUE.equals(c.call());}catch(Throwable ignored){return false;}}
    private int count(String sql,String...args){VaultDb db=null;Cursor c=null;try{db=new VaultDb(app);c=db.getReadableDatabase().rawQuery(sql,args);return c.moveToFirst()?c.getInt(0):0;}catch(Throwable e){return-1;}finally{if(c!=null)c.close();if(db!=null)try{db.close();}catch(Throwable ignored){}}}
    private String snapshotText(){CortexScreenAccessibilityService.Snapshot s=CortexScreenAccessibilityService.snapshot();return s==null?"":safe(s.text);}
    private boolean busy(String s){String x=s.toLowerCase(Locale.ROOT);return x.contains("thinking •")||x.contains("understanding request")||x.contains("combining sources")||x.contains("local model refining")||x.contains("generating useful next moves")||x.contains("improving…");}
    private boolean containsAny(String s,String...xs){String n=norm(s);for(String x:xs)if(n.contains(norm(x)))return true;return false;}
    private static int occurrences(String s,String x){if(s==null||x==null||x.isEmpty())return 0;int n=0,p=0;while((p=s.indexOf(x,p))>=0){n++;p+=x.length();}return n;}
    private static String norm(String s){return safe(s).replaceAll("\\s+"," ").trim().toLowerCase(Locale.ROOT);}
    private static String clip(String s,int n){String x=safe(s).replaceAll("\\s+"," ");return x.length()<=n?x:x.substring(0,n)+"…";}
    private static long elapsed(long s){return Math.max(0,System.currentTimeMillis()-s);}
    private static void sleep(long ms){try{Thread.sleep(ms);}catch(InterruptedException e){Thread.currentThread().interrupt();}}
    private static String safe(String s){return s==null?"":s;}
}
