package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.util.*;

/** Cortex-only shadow lab. It never replaces production transcripts or edits source recordings. */
public class CortexAsrLabActivity extends Activity {
    private static final int PICK_MODEL=8401;
    LinearLayout body;TextView status,results;int bg=Color.rgb(12,13,15),panel=Color.rgb(24,26,29),text=Color.rgb(244,245,247),muted=Color.rgb(160,164,172),green=Color.rgb(165,220,67);
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);return v;}
    @Override public void onCreate(Bundle b){super.onCreate(b);build();refresh();}
    void build(){ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(18),dp(20),dp(32));body.setBackgroundColor(bg);sv.addView(body);TextView h=tv("CORTEX · ASR LAB",24,text);h.setTypeface(null,1);body.addView(h);TextView sub=tv("Shadow comparison on your existing Cortex voice notes. Stored transcripts and original WAV files stay unchanged.",13,muted);sub.setPadding(0,dp(7),0,dp(16));body.addView(sub);status=tv("",13,text);status.setPadding(dp(14),dp(14),dp(14),dp(14));status.setBackgroundColor(panel);body.addView(status);addButton("IMPORT LOCAL WHISPER MODEL",v->pickModel());addButton("PROBE GEMINI NANO / AICORE",v->probeNano());addButton("RUN CLEAN WHISPER · LATEST 10",v->runCorpus(new CleanWhisperAsrCandidate()));addButton("RUN ANDROID ON-DEVICE · LATEST 10",v->runCorpus(new AndroidOnDeviceAsrCandidate()));results=tv("No benchmark run yet.",13,muted);results.setPadding(dp(14),dp(16),dp(14),dp(16));results.setBackgroundColor(panel);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(18),0,0);body.addView(results,rp);setContentView(sv);}
    void addButton(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextColor(text);b.setBackgroundColor(panel);b.setOnClickListener(l);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(54));p.setMargins(0,dp(10),0,0);body.addView(b,p);}
    void refresh(){if(status==null)return;AndroidOnDeviceAsrCandidate a=new AndroidOnDeviceAsrCandidate();status.setText("Product: Cortex\nProduction ASR: unchanged\n"+LocalAsrModelStore.statusText(this)+"\nAndroid on-device: "+(a.isReady(this)?"ready":"unavailable on this device/service")+"\nReference: stored working transcript, not human Gold");}
    void pickModel(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("application/octet-stream");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,PICK_MODEL);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK_MODEL&&c==RESULT_OK&&d!=null&&d.getData()!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}status.setText("Importing local Whisper model…");new Thread(()->{try{LocalAsrModelStore.importModel(this,u);runOnUiThread(()->{refresh();Toast.makeText(this,"Local Whisper model ready",Toast.LENGTH_SHORT).show();});}catch(Exception e){runOnUiThread(()->{refresh();new AlertDialog.Builder(this).setTitle("Model import failed").setMessage(e.getMessage()).setPositiveButton("OK",null).show();});}},"cortex-model-import").start();}}
    void probeNano(){results.setText("Checking Gemini Nano / AICore locally…");GeminiNanoProbe.run(this,r->runOnUiThread(()->results.setText("Gemini Nano / AICore\n\nStatus: "+r.label+"\nSupported path: "+r.supported+"\n\n"+r.detail)));}
    ArrayList<KnowledgeItem> corpus(){ArrayList<KnowledgeItem> out=new ArrayList<>();try{for(KnowledgeItem k:new VaultDb(this).lexicalSearch("",250)){if(out.size()>=10)break;if(k==null||k.type==null)continue;String t=k.type.toUpperCase(Locale.US);if(!(t.equals("AUDIO")||t.equals("VOICE")))continue;if(k.attachmentPath==null||k.extractedText==null||k.extractedText.trim().isEmpty())continue;File f=new File(k.attachmentPath);if(f.exists()&&f.length()>44)out.add(k);}}catch(Exception ignored){}return out;}
    void runCorpus(AsrCandidate candidate){if(!candidate.isReady(this)){new AlertDialog.Builder(this).setTitle(candidate.displayName()).setMessage("This candidate is not ready on this phone. Import a Whisper model or check Android on-device recognition availability.").setPositiveButton("OK",null).show();return;}ArrayList<KnowledgeItem> items=corpus();if(items.isEmpty()){new AlertDialog.Builder(this).setTitle("No benchmark corpus yet").setMessage("Cortex could not find historical voice items that still have both the original audio file and a stored working transcript.").setPositiveButton("OK",null).show();return;}results.setText("Running "+candidate.displayName()+" on "+items.size()+" historical Cortex voice notes…\nStored data will not be changed.");Aggregate a=new Aggregate(candidate,items);a.next();}
    final class Aggregate{final AsrCandidate candidate;final ArrayList<KnowledgeItem> items;int index=0,ok=0,failed=0;long latency=0,refWords=0,wordEdits=0,refChars=0,charEdits=0,arWords=0,arEdits=0,enWords=0,enEdits=0,numRef=0,numMatch=0,dups=0,refSwitch=0,hypSwitch=0;final JSONArray details=new JSONArray();Aggregate(AsrCandidate c,ArrayList<KnowledgeItem> i){candidate=c;items=i;}
        void next(){if(index>=items.size()){finish();return;}KnowledgeItem k=items.get(index++);File f=new File(k.attachmentPath);long bytes=f.length(),mod=f.lastModified();candidate.transcribe(CortexAsrLabActivity.this,f,new AsrCandidate.Callback(){public void ok(TranscriptResult r,long ms){try{if(!f.exists()||f.length()!=bytes||f.lastModified()!=mod)throw new IllegalStateException("Candidate changed source WAV");AsrBenchmarkMetrics.Score s=AsrBenchmarkMetrics.score(k.extractedText,r.text);ok++;latency+=ms;refWords+=s.referenceWords;wordEdits+=s.wordEdits;refChars+=s.referenceChars;charEdits+=s.charEdits;arWords+=s.arabicReferenceWords;arEdits+=s.arabicWordEdits;enWords+=s.latinReferenceWords;enEdits+=s.latinWordEdits;numRef+=s.referenceNumbers;numMatch+=s.matchedNumbers;dups+=s.duplicateAdjacentWords;refSwitch+=s.referenceScriptSwitches;hypSwitch+=s.hypothesisScriptSwitches;JSONObject j=new JSONObject();j.put("item_id",k.id);j.put("latency_ms",ms);j.put("wer",s.wer);j.put("cer",s.cer);j.put("reference",k.extractedText);j.put("candidate",r.text);details.put(j);}catch(Exception e){failed++;}runOnUiThread(()->{results.setText("Running "+candidate.displayName()+"… "+index+"/"+items.size());next();});}public void fail(Exception e,long ms){failed++;runOnUiThread(()->{results.setText("Running "+candidate.displayName()+"… "+index+"/"+items.size()+"\nLast failure: "+e.getMessage());next();});}});}
        double pct(long n,long d){return d<=0?0:(100.0*n/d);}void finish(){String report=String.format(Locale.US,"%s\n\nSuccessful: %d/%d\nFailed: %d\nWER: %.1f%%\nCER: %.1f%%\nArabic WER: %.1f%%\nEnglish WER: %.1f%%\nNumber recall: %.1f%%\nCode-switch boundaries: %d candidate / %d reference\nAdjacent duplicates: %d\nAverage latency: %.2fs",candidate.displayName(),ok,items.size(),failed,pct(wordEdits,refWords),pct(charEdits,refChars),pct(arEdits,arWords),pct(enEdits,enWords),numRef==0?100:pct(numMatch,numRef),hypSwitch,refSwitch,dups,ok==0?0:(latency/1000.0/ok));File saved=saveReport(report);results.setText(report+(saved==null?"":"\n\nReport: "+saved.getAbsolutePath()));}
        File saveReport(String summary){try{File dir=new File(getFilesDir(),"asr_benchmarks");if(!dir.exists())dir.mkdirs();File f=new File(dir,"cortex_"+candidate.id()+"_"+System.currentTimeMillis()+".json");JSONObject root=new JSONObject();root.put("schema","CORTEX_ASR_CORPUS_V1");root.put("candidate",candidate.id());root.put("reference_kind","stored_working_transcript_not_human_gold");root.put("summary",summary);root.put("items",details);try(FileWriter w=new FileWriter(f)){w.write(root.toString(2));}return f;}catch(Exception e){return null;}}
    }
}
