package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.text.InputType;
import android.view.Gravity;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

/** User-triggered Cortex -> ChatGPT Plus Deep Brain transport. */
public final class DeepBrainActivity extends Activity {
    EditText question; TextView status,send,paste; volatile boolean destroyed=false,busy=false;
    final ExecutorService worker=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"cortex-deep-brain");t.setPriority(Thread.NORM_PRIORITY-1);return t;});
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);build();refresh();}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}

    void build(){ScrollView scroll=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(14),dp(20),dp(28));root.setBackgroundColor(CortexUi.BG);scroll.addView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));TextView h=CortexUi.plain(this,"ChatGPT Deep Brain",27,CortexUi.TEXT);CortexUi.medium(h);head.addView(h,new LinearLayout.LayoutParams(0,-2,1));root.addView(head);TextView intro=CortexUi.text(this,"Cortex prepares grounded Memory / Worlds / Situations context. ChatGPT does the deep reasoning. You then share the structured response back to Cortex, which validates it before updating priorities.",12,CortexUi.MUTED);intro.setPadding(0,dp(8),0,dp(14));root.addView(intro);TextView label=CortexUi.plain(this,"Question",11,CortexUi.MUTED);CortexUi.medium(label);root.addView(label);question=new EditText(this);question.setText("What needs my attention now, why, and what should I do next?");question.setTextColor(CortexUi.TEXT);question.setHintTextColor(CortexUi.FAINT);question.setTextSize(14);question.setMinLines(3);question.setMaxLines(7);question.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);question.setPadding(dp(14),dp(12),dp(14),dp(12));question.setBackground(CortexUi.round(this,CortexUi.SURFACE,android.graphics.Color.TRANSPARENT,18));root.addView(question,new LinearLayout.LayoutParams(-1,-2));send=CortexUi.action(this,"Send context to ChatGPT",CortexUi.ACCENT,true);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(50));sp.setMargins(0,dp(14),0,0);root.addView(send,sp);send.setOnClickListener(v->send());paste=CortexUi.action(this,"Paste / apply ChatGPT response",CortexUi.MUTED,false);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(48));pp.setMargins(0,dp(8),0,0);root.addView(paste,pp);paste.setOnClickListener(v->pasteDialog());TextView how=CortexUi.text(this,"Return path: in ChatGPT, share the response and choose “Apply ChatGPT to Cortex”. If the share option is unavailable, use Paste / apply above. Cortex will reject responses without a matching request_id.",11,CortexUi.MUTED);how.setPadding(0,dp(14),0,dp(12));root.addView(how);status=CortexUi.text(this,"",11,CortexUi.TEXT);status.setPadding(dp(12),dp(12),dp(12),dp(12));status.setBackground(CortexUi.round(this,CortexUi.SURFACE,android.graphics.Color.TRANSPARENT,16));root.addView(status);setContentView(scroll);CortexUi.fitSystemBars(this,scroll);}

    void send(){if(busy||destroyed)return;String q=question.getText().toString().trim();if(q.isEmpty()){question.setError("Ask something first");return;}setBusy(true,"Building grounded Cortex context…");worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());CognitiveDeepBrainPacketBuilderV4.Packet p=CognitiveDeepBrainPacketBuilderV4.build(db,q);CognitiveDeepBrainStoreV4.markExported(db,p.requestId);post(()->{setBusy(false,"Context packet ready · "+p.requestId);share(p.shareText);});}catch(Throwable e){post(()->setBusy(false,"Could not build Deep Brain packet: "+safe(e.getMessage())));}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}});}
    void share(String text){Intent base=new Intent(Intent.ACTION_SEND);base.setType("text/plain");base.putExtra(Intent.EXTRA_TEXT,text);base.putExtra(Intent.EXTRA_SUBJECT,"Cortex Deep Brain");try{Intent direct=new Intent(base);direct.setPackage("com.openai.chatgpt");startActivity(direct);}catch(Throwable noChatGpt){try{startActivity(Intent.createChooser(base,"Send Cortex context to ChatGPT"));}catch(Throwable e){Toast.makeText(this,"No compatible share app found",Toast.LENGTH_LONG).show();}}}
    void pasteDialog(){if(busy)return;final EditText e=new EditText(this);e.setHint("Paste the full CORTEX_RESPONSE_V1 response");e.setMinLines(8);e.setMaxLines(16);e.setGravity(Gravity.TOP);e.setTextColor(CortexUi.TEXT);e.setHintTextColor(CortexUi.FAINT);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE);new AlertDialog.Builder(this).setTitle("Apply ChatGPT response").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Validate & apply",(d,w)->apply(e.getText().toString())).show();}
    void apply(String raw){if(busy||raw==null||raw.trim().isEmpty())return;setBusy(true,"Validating ChatGPT response…");worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());CognitiveDeepBrainApplyV4.Result r=CognitiveDeepBrainApplyV4.apply(db,raw);post(()->{setBusy(false,r.human());if(!r.answer.isEmpty())new AlertDialog.Builder(this).setTitle("Deep Brain applied").setMessage(r.answer+"\n\n"+r.human()).setPositiveButton("Done",null).show();refresh();});}catch(Throwable e){post(()->setBusy(false,"Response rejected safely: "+safe(e.getMessage())));}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}});}

    void refresh(){worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());CognitiveDeepBrainStoreV4.Status s=CognitiveDeepBrainStoreV4.latest(db);String priorities=CognitiveDeepBrainStoreV4.latestPrioritySummary(db,8);post(()->{if(s==null){status.setText("No Deep Brain request yet.");return;}String when=new SimpleDateFormat("dd MMM · HH:mm",Locale.getDefault()).format(new Date(s.createdAt));StringBuilder b=new StringBuilder();b.append("Latest · ").append(s.state).append(" · ").append(when).append("\n").append(s.question);if(s.answer!=null&&!s.answer.trim().isEmpty())b.append("\n\nLast answer:\n").append(s.answer);if(priorities!=null&&!priorities.trim().isEmpty())b.append("\n\nCurrent suggested priorities:\n").append(priorities);status.setText(b.toString());});}catch(Throwable e){post(()->status.setText("Deep Brain status unavailable."));}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}});}
    void setBusy(boolean on,String message){busy=on;if(send!=null){send.setEnabled(!on);send.setText(on?"Working…":"Send context to ChatGPT");}if(paste!=null)paste.setEnabled(!on);if(status!=null&&message!=null&&!message.isEmpty())status.setText(message);}
    void post(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())try{r.run();}catch(Throwable ignored){}});}String safe(String s){return s==null||s.trim().isEmpty()?"unknown error":s.trim();}
}
