package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.*;

/** CORTEX UI DESIGN LOCK V1 controlled Cortex ↔ ChatGPT review workflow. */
public final class DeepReviewActivity extends Activity {
    static final String PREF="cortex_deep_review_v1",KEY_REQUEST="last_request_id";
    VaultDb db;EditText response;LinearLayout preview;TextView packState,returnState,validationState,schemaValue,groundValue,itemValue,confidenceValue,applyButton;DeepReviewContractV1.Review parsed;DeepReviewContractV1.PromptPack pack;String expectedRequestId="";
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);expectedRequestId=getSharedPreferences(PREF,MODE_PRIVATE).getString(KEY_REQUEST,"");build();preparePack();String incoming=getIntent()==null?"":getIntent().getStringExtra("deep_review_response");if(incoming!=null&&!incoming.trim().isEmpty()){response.setText(incoming);response.setSelection(response.length());returnState.setText("Received · ready to validate");validateResponse();}}
    @Override protected void onDestroy(){try{if(db!=null)db.close();}catch(Throwable ignored){}super.onDestroy();}

    void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);root.addView(header(),new LinearLayout.LayoutParams(-1,dp(72)));
        ScrollView sv=new ScrollView(this);sv.setVerticalScrollBarEnabled(false);sv.setClipToPadding(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),0,dp(18),dp(28));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        TextView sub=CortexUi.plain(this,"Cortex ↔ ChatGPT workflow with grounded verification",10,CortexUi.MUTED);sub.setPadding(dp(52),0,0,dp(12));body.addView(sub);

        LinearLayout context=CortexUi.card(this,17);context.setPadding(dp(14),dp(12),dp(14),dp(11));TextView ch=CortexUi.plain(this,"Context summary",11,CortexUi.LIME);CortexUi.medium(ch);context.addView(ch);LinearLayout metrics=new LinearLayout(this);metrics.setPadding(0,dp(10),0,dp(8));TextView evidence=metric(metrics,"evidence","0","Evidence items");TextView cognitive=metric(metrics,"brain","0","Cognitive items");TextView tokens=metric(metrics,"list","0","Tokens est.");context.addView(metrics,new LinearLayout.LayoutParams(-1,dp(66)));packState=CortexUi.plain(this,"Preparing local context…",9,CortexUi.MUTED);packState.setPadding(0,dp(6),0,0);context.addView(packState);context.setTag(new TextView[]{evidence,cognitive,tokens});addStep(body,1,"Build context pack","Ready",context,true);

        LinearLayout openRow=new LinearLayout(this);openRow.setGravity(Gravity.CENTER_VERTICAL);TextView openState=CortexUi.plain(this,expectedRequestId.isEmpty()?"Ready to open":"Previous request is waiting for a response",9,expectedRequestId.isEmpty()?CortexUi.LIME:CortexUi.YELLOW);openRow.addView(openState,new LinearLayout.LayoutParams(0,-2,1));TextView open=CortexUi.action(this,"Open in ChatGPT",CortexUi.LIME,false);open.setOnClickListener(v->openChatGPT());openRow.addView(open,new LinearLayout.LayoutParams(dp(160),dp(44)));addStep(body,2,"Open in ChatGPT",expectedRequestId.isEmpty()?"Not sent":"Waiting",openRow,!expectedRequestId.isEmpty());

        LinearLayout returnCard=CortexUi.card(this,17);returnCard.setPadding(dp(13),dp(11),dp(13),dp(12));LinearLayout codeHead=new LinearLayout(this);codeHead.setGravity(Gravity.CENTER_VERTICAL);TextView marker=CortexUi.plain(this,"CORTEX_REVIEW_V1",11,CortexUi.LIME);CortexUi.medium(marker);codeHead.addView(marker,new LinearLayout.LayoutParams(0,-2,1));TextView json=CortexUi.chip(this,"JSON",CortexUi.MUTED,false);codeHead.addView(json,new LinearLayout.LayoutParams(-2,dp(28)));returnCard.addView(codeHead);response=new EditText(this);response.setHint("{\n  \"request_id\": \"…\",\n  \"answer\": \"…\",\n  \"priority_items\": [ … ]\n}");response.setHintTextColor(Color.rgb(100,105,99));response.setTextColor(CortexUi.TEXT);response.setTextSize(10);response.setGravity(Gravity.TOP|Gravity.START);response.setMinLines(7);response.setMaxLines(16);response.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);response.setPadding(dp(11),dp(10),dp(11),dp(10));response.setBackground(CortexUi.round(this,Color.rgb(20,22,20),Color.rgb(55,59,53),12));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(9),0,dp(8));returnCard.addView(response,rp);LinearLayout returnActions=new LinearLayout(this);TextView paste=CortexUi.action(this,"Paste",CortexUi.MUTED,false);paste.setOnClickListener(v->pasteClipboard());returnActions.addView(paste,new LinearLayout.LayoutParams(0,dp(42),1));TextView validate=CortexUi.action(this,"Validate review",CortexUi.LIME,false);validate.setOnClickListener(v->validateResponse());LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(0,dp(42),1);vp.setMargins(dp(8),0,0,0);returnActions.addView(validate,vp);returnCard.addView(returnActions);returnState=CortexUi.plain(this,"Nothing returned yet",9,CortexUi.MUTED);returnState.setPadding(0,dp(8),0,0);returnCard.addView(returnState);addStep(body,3,"Return structured review","Awaiting response",returnCard,false);

        LinearLayout validation=CortexUi.card(this,17);validation.setPadding(dp(9),dp(10),dp(9),dp(10));LinearLayout values=new LinearLayout(this);schemaValue=validationCell(values,"shield","Schema","Pending");groundValue=validationCell(values,"check","Grounded","Pending");itemValue=validationCell(values,"list","Items","0");confidenceValue=validationCell(values,"wave","Confidence","—");validation.addView(values,new LinearLayout.LayoutParams(-1,dp(70)));validationState=CortexUi.plain(this,"No review has passed validation.",9,CortexUi.MUTED);validationState.setPadding(dp(4),dp(5),0,0);validation.addView(validationState);addStep(body,4,"Validate review","Required",validation,false);

        preview=new LinearLayout(this);preview.setOrientation(LinearLayout.VERTICAL);TextView wait=CortexUi.text(this,"Validated recommendations and their Evidence references will appear here before anything can be applied.",10,CortexUi.MUTED);wait.setPadding(dp(12),dp(10),dp(12),dp(10));wait.setBackground(CortexUi.round(this,Color.rgb(18,20,18),Color.rgb(47,51,45),14));preview.addView(wait);addStep(body,5,"Preview grounded diff","Not available yet",preview,false);

        LinearLayout apply=new LinearLayout(this);apply.setOrientation(LinearLayout.VERTICAL);TextView ready=CortexUi.plain(this,"Ready only after schema + grounding validation passes",9,CortexUi.MUTED);apply.addView(ready);applyButton=CortexUi.action(this,"✦  Apply grounded review",CortexUi.LIME,true);applyButton.setTextColor(CortexUi.BG);applyButton.setBackground(CortexUi.round(this,CortexUi.LIME,Color.rgb(210,235,121),999));applyButton.setEnabled(false);applyButton.setAlpha(.42f);applyButton.setOnClickListener(v->applyReview());LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(54));ap.setMargins(0,dp(10),0,0);apply.addView(applyButton,ap);LinearLayout trust=new LinearLayout(this);trust.setGravity(Gravity.CENTER);trust.setPadding(0,dp(9),0,0);trust.addView(new CortexLineIconView(this,"lock",CortexUi.MUTED),new LinearLayout.LayoutParams(dp(18),dp(18)));TextView safe=CortexUi.plain(this,"  Existing Evidence is never rewritten",9,CortexUi.MUTED);trust.addView(safe);apply.addView(trust);addStep(body,6,"Apply grounded review","User controlled",apply,false);

        setContentView(root);CortexUi.fitSystemBars(this,root);
    }

    View header(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(18),dp(8),dp(17),0);row.addView(circleButton("back",CortexUi.TEXT,()->finish()),new LinearLayout.LayoutParams(dp(48),dp(48)));CortexLineIconView logo=new CortexLineIconView(this,"logo",CortexUi.LIME);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(32),dp(32));lp.setMargins(dp(14),0,0,0);row.addView(logo,lp);TextView title=CortexUi.plain(this,"Deep Review",23,CortexUi.TEXT);CortexUi.bold(title);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(dp(7),0,0,0);row.addView(title,tp);row.addView(circleButton("history",CortexUi.TEXT,()->open(ReviewQueueActivity.class)),new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(dp(44),dp(44));mp.setMargins(dp(7),0,0,0);row.addView(circleButton("more",CortexUi.MUTED,()->open(SettingsActivity.class)),mp);return row;}

    void addStep(LinearLayout body,int number,String title,String status,View content,boolean done){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.TOP);TextView n=CortexUi.plain(this,String.valueOf(number),12,done?CortexUi.BG:CortexUi.LIME);CortexUi.bold(n);n.setGravity(Gravity.CENTER);n.setBackground(CortexUi.round(this,done?CortexUi.LIME:Color.rgb(8,10,8),CortexUi.LIME,999));row.addView(n,new LinearLayout.LayoutParams(dp(40),dp(40)));LinearLayout right=new LinearLayout(this);right.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(0,-2,1);rp.setMargins(dp(12),0,0,0);row.addView(right,rp);TextView h=CortexUi.plain(this,title,13,CortexUi.TEXT);CortexUi.medium(h);right.addView(h);TextView s=CortexUi.plain(this,status,9,done?CortexUi.LIME:CortexUi.MUTED);s.setPadding(0,dp(2),0,dp(7));right.addView(s);right.addView(content);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(13));body.addView(row,p);}

    TextView metric(LinearLayout row,String icon,String number,String label){LinearLayout cell=new LinearLayout(this);cell.setGravity(Gravity.CENTER_VERTICAL);cell.addView(new CortexLineIconView(this,icon,CortexUi.TEXT),new LinearLayout.LayoutParams(dp(26),dp(26)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(-2,-2);xp.setMargins(dp(7),0,0,0);cell.addView(tx,xp);TextView n=CortexUi.plain(this,number,14,CortexUi.TEXT);CortexUi.bold(n);tx.addView(n);TextView l=CortexUi.plain(this,label,8,CortexUi.MUTED);tx.addView(l);row.addView(cell,new LinearLayout.LayoutParams(0,-1,1));return n;}
    TextView validationCell(LinearLayout row,String icon,String label,String value){LinearLayout cell=new LinearLayout(this);cell.setOrientation(LinearLayout.VERTICAL);cell.setGravity(Gravity.CENTER);cell.addView(new CortexLineIconView(this,icon,CortexUi.LIME),new LinearLayout.LayoutParams(dp(26),dp(26)));TextView l=CortexUi.plain(this,label,8,CortexUi.MUTED);l.setPadding(0,dp(3),0,0);cell.addView(l);TextView v=CortexUi.plain(this,value,10,CortexUi.MUTED);CortexUi.medium(v);v.setPadding(0,dp(2),0,0);cell.addView(v);row.addView(cell,new LinearLayout.LayoutParams(0,-1,1));return v;}

    void preparePack(){try{pack=DeepReviewContractV1.build(db);Object tag=findContextTag();if(tag instanceof TextView[]){TextView[] x=(TextView[])tag;x[0].setText(String.valueOf(pack.evidenceCount));x[1].setText(String.valueOf(pack.stateCount));x[2].setText(String.valueOf(Math.max(1,pack.text.length()/4)));}packState.setText(pack.evidenceCount+" Evidence items  •  "+pack.stateCount+" cognitive items  •  local only until Open in ChatGPT");}catch(Throwable e){packState.setText("Could not build context safely");pack=null;}}
    Object findContextTag(){View root=((ViewGroup)((ViewGroup)findViewById(android.R.id.content)).getChildAt(0));return findTagged(root);}
    Object findTagged(View v){if(v==null)return null;Object t=v.getTag();if(t instanceof TextView[])return t;if(v instanceof ViewGroup){ViewGroup g=(ViewGroup)v;for(int i=0;i<g.getChildCount();i++){Object r=findTagged(g.getChildAt(i));if(r!=null)return r;}}return null;}

    void openChatGPT(){try{if(pack==null)preparePack();if(pack==null)throw new IllegalStateException();expectedRequestId=pack.requestId;getSharedPreferences(PREF,MODE_PRIVATE).edit().putString(KEY_REQUEST,pack.requestId).apply();packState.setText(pack.evidenceCount+" Evidence items  •  request "+pack.requestId);Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_SUBJECT,"Cortex Deep Review");send.putExtra(Intent.EXTRA_TEXT,pack.text);send.addFlags(Intent.FLAG_ACTIVITY_NEW_DOCUMENT);Intent direct=new Intent(send);direct.setPackage("com.openai.chatgpt");try{startActivity(direct);}catch(Throwable noChatGpt){startActivity(Intent.createChooser(send,"Open Deep Review with"));}}catch(Throwable e){Toast.makeText(this,"Could not open Deep Review safely",Toast.LENGTH_LONG).show();}}

    void pasteClipboard(){try{android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm==null||!cm.hasPrimaryClip()||cm.getPrimaryClip().getItemCount()==0){Toast.makeText(this,"Clipboard is empty",Toast.LENGTH_SHORT).show();return;}CharSequence s=cm.getPrimaryClip().getItemAt(0).coerceToText(this);response.setText(s==null?"":s.toString());response.setSelection(response.length());returnState.setText("Pasted · ready to validate");}catch(Throwable e){Toast.makeText(this,"Could not read clipboard",Toast.LENGTH_SHORT).show();}}

    void validateResponse(){parsed=null;try{parsed=DeepReviewContractV1.parse(db,response.getText().toString(),expectedRequestId);double avg=0;for(DeepReviewContractV1.Item x:parsed.items)avg+=x.confidence;if(!parsed.items.isEmpty())avg/=parsed.items.size();schemaValue.setText("Valid");schemaValue.setTextColor(CortexUi.LIME);groundValue.setText("Passed");groundValue.setTextColor(CortexUi.LIME);itemValue.setText(String.valueOf(parsed.items.size()));itemValue.setTextColor(CortexUi.LIME);confidenceValue.setText(parsed.items.isEmpty()?"—":String.format(Locale.US,"%.2f",avg));confidenceValue.setTextColor(CortexUi.LIME);validationState.setText("Passed · every imported cognitive item cites existing Evidence IDs");validationState.setTextColor(CortexUi.LIME);returnState.setText("Received · valid structured review");returnState.setTextColor(CortexUi.LIME);applyButton.setEnabled(true);applyButton.setAlpha(1f);renderPreview();}catch(Throwable e){schemaValue.setText("Invalid");schemaValue.setTextColor(CortexUi.RED);groundValue.setText("Blocked");groundValue.setTextColor(CortexUi.RED);itemValue.setText("0");confidenceValue.setText("—");validationState.setText("NOT APPLIED · "+safe(e));validationState.setTextColor(CortexUi.RED);applyButton.setEnabled(false);applyButton.setAlpha(.42f);preview.removeAllViews();TextView bad=CortexUi.text(this,"The response failed Cortex validation. No data was changed.",10,CortexUi.MUTED);bad.setPadding(dp(12),dp(10),dp(12),dp(10));bad.setBackground(CortexUi.round(this,Color.rgb(19,21,19),Color.rgb(60,64,58),14));preview.addView(bad);}}

    void renderPreview(){preview.removeAllViews();if(parsed==null)return;if(!parsed.answer.isEmpty()){TextView answer=CortexUi.text(this,parsed.answer,11,CortexUi.TEXT);answer.setPadding(dp(12),dp(10),dp(12),dp(10));answer.setBackground(CortexUi.round(this,Color.rgb(19,21,19),Color.rgb(52,56,50),13));preview.addView(answer);}int i=0;for(DeepReviewContractV1.Item x:parsed.items){if(i>=6)break;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(10),dp(8),dp(8),dp(8));row.setBackground(CortexUi.round(this,Color.rgb(22,24,22),Color.rgb(53,57,51),10));row.addView(new CortexLineIconView(this,"chevron",CortexUi.MUTED),new LinearLayout.LayoutParams(dp(20),dp(20)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(7),0,dp(5),0);row.addView(tx,xp);TextView title=CortexUi.text(this,x.title,11,CortexUi.TEXT);CortexUi.medium(title);tx.addView(title);TextView refs=CortexUi.plain(this,"Evidence "+ids(x.evidenceIds),8,CortexUi.MUTED);refs.setPadding(0,dp(2),0,0);tx.addView(refs);String priority=x.importance>=70?"↑ High":x.importance>=40?"↑ Medium":"Low";TextView p=CortexUi.plain(this,priority,9,x.importance>=70?CortexUi.LIME:x.importance>=40?CortexUi.ORANGE:CortexUi.MUTED);row.addView(p);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,i==0?dp(8):dp(1),0,0);preview.addView(row,rp);i++;}if(parsed.items.size()>6){TextView more=CortexUi.plain(this,"View full diff · "+parsed.items.size()+" recommendations",9,CortexUi.LIME);more.setGravity(Gravity.CENTER);more.setPadding(0,dp(10),0,dp(5));preview.addView(more);}}

    void applyReview(){if(parsed==null)return;new AlertDialog.Builder(this).setTitle("Apply grounded review?").setMessage("Only the validated, Evidence-grounded cognitive items in this preview will be added. Existing Evidence will not be rewritten and no external action will run.").setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{try{DeepReviewContractV1.ApplyResult r=DeepReviewContractV1.apply(db,parsed);getSharedPreferences(PREF,MODE_PRIVATE).edit().remove(KEY_REQUEST).apply();expectedRequestId="";validationState.setText("APPLIED · "+r.created+" grounded item"+(r.created==1?"":"s")+" added · review Evidence #"+r.reviewEvidenceId);validationState.setTextColor(CortexUi.LIME);applyButton.setEnabled(false);applyButton.setAlpha(.55f);Toast.makeText(this,"Deep Review applied to Cortex",Toast.LENGTH_LONG).show();}catch(Throwable e){validationState.setText("NOT APPLIED · "+safe(e));validationState.setTextColor(CortexUi.RED);}}).show();}

    View circleButton(String kind,int color,Runnable action){FrameLayout b=new FrameLayout(this);b.setBackground(CortexUi.round(this,Color.rgb(23,25,23),Color.rgb(55,59,53),999));b.addView(new CortexLineIconView(this,kind,color),new FrameLayout.LayoutParams(dp(26),dp(26),Gravity.CENTER));b.setOnClickListener(v->action.run());return b;}
    void open(Class<?> cls){try{startActivity(new Intent(this,cls));}catch(Throwable ignored){}}
    String ids(long[] xs){StringBuilder b=new StringBuilder();for(int i=0;i<xs.length;i++){if(i>0)b.append(", ");b.append('#').append(xs[i]);}return b.toString();}
    String safe(Throwable e){String s=e==null?"Unknown error":e.getMessage();return s==null||s.trim().isEmpty()?e.getClass().getSimpleName():s;}
}
