package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.os.Bundle;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.*;

/** Explicit, user-controlled Cortex ↔ ChatGPT reconciliation surface. */
public final class DeepReviewActivity extends Activity {
    static final String PREF="cortex_deep_review_v1",KEY_REQUEST="last_request_id";
    VaultDb db;EditText response;LinearLayout preview;TextView packState,validationState;DeepReviewContractV1.Review parsed;String expectedRequestId="";
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);expectedRequestId=getSharedPreferences(PREF,MODE_PRIVATE).getString(KEY_REQUEST,"");build();String incoming=getIntent()==null?"":getIntent().getStringExtra("deep_review_response");if(incoming!=null&&!incoming.trim().isEmpty()){response.setText(incoming);response.setSelection(response.length());validateResponse();}}
    @Override protected void onDestroy(){try{if(db!=null)db.close();}catch(Throwable ignored){}super.onDestroy();}

    void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setClipToPadding(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(10),dp(18),dp(25));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));body.addView(header());

        LinearLayout hero=CortexUi.card(this,25);hero.setPadding(dp(17),dp(17),dp(17),dp(17));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(CortexUi.glyph(this,"brain",CortexUi.RED,true),new LinearLayout.LayoutParams(dp(58),dp(58)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(14),0,0,0);top.addView(tx,xp);TextView h=CortexUi.plain(this,"Reconcile Cortex with ChatGPT",21,CortexUi.TEXT);CortexUi.medium(h);tx.addView(h);TextView sub=CortexUi.text(this,"Send a grounded snapshot out, get a machine-readable review back, then inspect exactly what Cortex would add before anything changes.",12,CortexUi.MUTED);sub.setPadding(0,dp(6),0,0);tx.addView(sub);hero.addView(top);TextView trust=CortexUi.plain(this,"USER CONTROLLED  •  GROUNDED IDS  •  PREVIEW BEFORE APPLY",8,CortexUi.GREEN);CortexUi.medium(trust);if(android.os.Build.VERSION.SDK_INT>=21)trust.setLetterSpacing(.07f);trust.setPadding(dp(2),dp(14),0,0);hero.addView(trust);body.addView(hero,margins(0,8,0,0));

        TextView contextHead=section("1  BUILD CONTEXT",CortexUi.ORANGE);body.addView(contextHead);LinearLayout pack=CortexUi.card(this,21);LinearLayout packTop=new LinearLayout(this);packTop.setGravity(Gravity.CENTER_VERTICAL);packTop.addView(CortexUi.glyph(this,"nodes",CortexUi.ORANGE,true),new LinearLayout.LayoutParams(dp(48),dp(48)));LinearLayout ptx=new LinearLayout(this);ptx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(0,-2,1);pp.setMargins(dp(11),0,0,0);packTop.addView(ptx,pp);TextView ph=CortexUi.plain(this,"Cortex context pack",15,CortexUi.TEXT);CortexUi.medium(ph);ptx.addView(ph);packState=CortexUi.text(this,expectedRequestId.isEmpty()?"Ready to build from Evidence + current cognitive state.":"A previous review request is waiting for a response.",10,CortexUi.MUTED);packState.setPadding(0,dp(4),0,0);ptx.addView(packState);pack.addView(packTop);TextView build=CortexUi.action(this,"Build & open in ChatGPT",CortexUi.ORANGE,true);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(50));bp.setMargins(0,dp(13),0,0);pack.addView(build,bp);build.setOnClickListener(v->buildAndShare());body.addView(pack);

        TextView responseHead=section("2  RETURN STRUCTURED REVIEW",CortexUi.YELLOW);body.addView(responseHead);LinearLayout returnCard=CortexUi.card(this,21);TextView hint=CortexUi.text(this,"In ChatGPT, return the CORTEX_REVIEW_V1 block. You can Share it back to Cortex or paste it here.",11,CortexUi.MUTED);returnCard.addView(hint);response=new EditText(this);response.setHint("CORTEX_REVIEW_V1\n{ ... }");response.setHintTextColor(CortexUi.FAINT);response.setTextColor(CortexUi.TEXT);response.setTextSize(11);response.setGravity(Gravity.TOP|Gravity.START);response.setMinLines(7);response.setMaxLines(15);response.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_NO_SUGGESTIONS);response.setPadding(dp(13),dp(12),dp(13),dp(12));response.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER,17));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,dp(12),0,0);returnCard.addView(response,rp);LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setPadding(0,dp(10),0,0);TextView paste=CortexUi.action(this,"Paste",CortexUi.MUTED,false),validate=CortexUi.action(this,"Validate review",CortexUi.YELLOW,true);actions.addView(paste,new LinearLayout.LayoutParams(0,dp(46),.38f));LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(0,dp(46),.62f);vp.setMargins(dp(8),0,0,0);actions.addView(validate,vp);returnCard.addView(actions);paste.setOnClickListener(v->pasteClipboard());validate.setOnClickListener(v->validateResponse());validationState=CortexUi.text(this,"Nothing has been applied.",9,CortexUi.FAINT);validationState.setPadding(dp(2),dp(9),0,0);returnCard.addView(validationState);body.addView(returnCard);

        TextView previewHead=section("3  PREVIEW & APPLY",CortexUi.GREEN);body.addView(previewHead);preview=new LinearLayout(this);preview.setOrientation(LinearLayout.VERTICAL);LinearLayout waiting=CortexUi.card(this,20);TextView w=CortexUi.text(this,"Validated changes will appear here as a grounded diff before Cortex accepts them.",11,CortexUi.MUTED);waiting.addView(w);preview.addView(waiting);body.addView(preview);

        LinearLayout how=CortexUi.card(this,20);TextView hh=CortexUi.plain(this,"Why this is safe",14,CortexUi.TEXT);CortexUi.medium(hh);how.addView(hh);TextView hb=CortexUi.text(this,"• Evidence remains immutable.\n• Every new cognitive item must cite existing Evidence IDs.\n• ChatGPT cannot mark anything completed or execute actions.\n• Apply adds grounded derived intelligence through Cortex’s canonical cognitive store.\n• Suggested actions remain proposals.",10,CortexUi.MUTED);hb.setPadding(0,dp(7),0,0);how.addView(hb);body.addView(how,margins(0,dp(14),0,0));
        CortexUi.addBottomNav(this,root,"brain",null);setContentView(root);
    }

    View header(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(5),dp(8),dp(2),dp(11));TextView back=CortexUi.plain(this,"‹",30,CortexUi.MUTED);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());row.addView(back,new LinearLayout.LayoutParams(dp(38),dp(40)));View dot=new View(this);dot.setBackground(CortexUi.round(this,CortexUi.RED,Color.TRANSPARENT,999));row.addView(dot,new LinearLayout.LayoutParams(dp(9),dp(9)));TextView c=CortexUi.plain(this,"C O R T E X",14,CortexUi.TEXT);CortexUi.bold(c);if(android.os.Build.VERSION.SDK_INT>=21)c.setLetterSpacing(.20f);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-2,dp(40));cp.setMargins(dp(11),0,0,0);row.addView(c,cp);View d=CortexUi.divider(this);LinearLayout.LayoutParams dv=new LinearLayout.LayoutParams(dp(1),dp(28));dv.setMargins(dp(12),0,dp(12),0);row.addView(d,dv);TextView sys=CortexUi.plain(this,"DEEP REVIEW",10,CortexUi.MUTED);if(android.os.Build.VERSION.SDK_INT>=21)sys.setLetterSpacing(.10f);row.addView(sys,new LinearLayout.LayoutParams(0,dp(40),1));CortexGlyphView ev=CortexUi.glyph(this,"nodes",CortexUi.GREEN,false);ev.setOnClickListener(v->startActivity(new Intent(this,EvidenceActivity.class)));row.addView(ev,new LinearLayout.LayoutParams(dp(46),dp(46)));return row;}
    TextView section(String t,int c){TextView h=CortexUi.plain(this,t,10,c);CortexUi.medium(h);if(android.os.Build.VERSION.SDK_INT>=21)h.setLetterSpacing(.08f);h.setPadding(dp(1),dp(20),0,dp(8));return h;}

    void buildAndShare(){try{DeepReviewContractV1.PromptPack p=DeepReviewContractV1.build(db);expectedRequestId=p.requestId;getSharedPreferences(PREF,MODE_PRIVATE).edit().putString(KEY_REQUEST,p.requestId).apply();packState.setText(p.evidenceCount+" Evidence items + "+p.stateCount+" current cognitive items  •  request "+p.requestId);Intent send=new Intent(Intent.ACTION_SEND);send.setType("text/plain");send.putExtra(Intent.EXTRA_SUBJECT,"Cortex Deep Review");send.putExtra(Intent.EXTRA_TEXT,p.text);send.addFlags(Intent.FLAG_ACTIVITY_NEW_DOCUMENT);Intent direct=new Intent(send);direct.setPackage("com.openai.chatgpt");try{startActivity(direct);}catch(Throwable noChatGpt){startActivity(Intent.createChooser(send,"Open Deep Review with"));}}catch(Throwable e){Toast.makeText(this,"Could not build Deep Review context",Toast.LENGTH_LONG).show();packState.setText("Context build failed safely. Nothing was sent.");}}

    void pasteClipboard(){try{android.content.ClipboardManager cm=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(cm==null||!cm.hasPrimaryClip()||cm.getPrimaryClip().getItemCount()==0){Toast.makeText(this,"Clipboard is empty",Toast.LENGTH_SHORT).show();return;}CharSequence s=cm.getPrimaryClip().getItemAt(0).coerceToText(this);response.setText(s==null?"":s.toString());response.setSelection(response.length());}catch(Throwable e){Toast.makeText(this,"Could not read clipboard",Toast.LENGTH_SHORT).show();}}

    void validateResponse(){parsed=null;try{parsed=DeepReviewContractV1.parse(db,response.getText().toString(),expectedRequestId);validationState.setText("VALID · "+parsed.items.size()+" grounded cognitive item"+(parsed.items.size()==1?"":"s")+" · "+parsed.actions.size()+" suggested action"+(parsed.actions.size()==1?"":"s"));validationState.setTextColor(CortexUi.GREEN);renderPreview();}catch(Throwable e){validationState.setText("NOT APPLIED · "+safe(e));validationState.setTextColor(CortexUi.RED);preview.removeAllViews();LinearLayout bad=CortexUi.card(this,20);TextView t=CortexUi.text(this,"The response failed Cortex validation. No data was changed.",11,CortexUi.MUTED);bad.addView(t);preview.addView(bad);}}

    void renderPreview(){preview.removeAllViews();if(parsed==null)return;if(!parsed.answer.isEmpty()){LinearLayout summary=CortexUi.card(this,20);TextView h=CortexUi.plain(this,"ChatGPT review",14,CortexUi.TEXT);CortexUi.medium(h);summary.addView(h);TextView b=CortexUi.text(this,parsed.answer,11,CortexUi.MUTED);b.setPadding(0,dp(6),0,0);summary.addView(b);preview.addView(summary);}
        int i=0;for(DeepReviewContractV1.Item x:parsed.items){LinearLayout card=CortexUi.card(this,18);LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);int c=kindColor(x.kind);row.addView(CortexUi.glyph(this,kindGlyph(x.kind),c,true),new LinearLayout.LayoutParams(dp(44),dp(44)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(dp(10),0,dp(7),0);row.addView(tx,tp);TextView h=CortexUi.text(this,x.title,13,CortexUi.TEXT);CortexUi.medium(h);tx.addView(h);TextView b=CortexUi.text(this,x.body,10,CortexUi.MUTED);b.setPadding(0,dp(4),0,0);tx.addView(b);row.addView(CortexUi.chip(this,x.kind,c,false),new LinearLayout.LayoutParams(-2,dp(30)));card.addView(row);TextView meta=CortexUi.plain(this,"IMPORTANCE "+x.importance+"  •  CONF "+Math.round(x.confidence*100)+"%  •  EVIDENCE "+ids(x.evidenceIds),8,CortexUi.FAINT);meta.setPadding(dp(2),dp(7),0,0);card.addView(meta);if(!x.reason.isEmpty()){TextView why=CortexUi.text(this,x.reason,9,CortexUi.MUTED);why.setPadding(dp(2),dp(5),0,0);card.addView(why);}preview.addView(card,margins(0,i++==0?8:7,0,0));}
        if(!parsed.actions.isEmpty()){LinearLayout act=CortexUi.card(this,18);TextView h=CortexUi.plain(this,"Suggested actions · proposals only",13,CortexUi.TEXT);CortexUi.medium(h);act.addView(h);for(DeepReviewContractV1.Action a:parsed.actions){TextView t=CortexUi.text(this,"• "+a.title+(a.why.isEmpty()?"":" — "+a.why),10,CortexUi.MUTED);t.setPadding(0,dp(6),0,0);act.addView(t);}preview.addView(act,margins(0,8,0,0));}
        TextView apply=CortexUi.action(this,"Apply grounded review to Cortex",CortexUi.GREEN,true);apply.setOnClickListener(v->applyReview());preview.addView(apply,margins(0,10,0,0));}

    void applyReview(){if(parsed==null)return;new AlertDialog.Builder(this).setTitle("Apply Deep Review?").setMessage("Cortex will add only the validated, evidence-grounded cognitive items shown in the preview. Existing Evidence will not be rewritten and no external action will run.").setNegativeButton("Cancel",null).setPositiveButton("Apply",(d,w)->{try{DeepReviewContractV1.ApplyResult r=DeepReviewContractV1.apply(db,parsed);getSharedPreferences(PREF,MODE_PRIVATE).edit().remove(KEY_REQUEST).apply();expectedRequestId="";validationState.setText("APPLIED · "+r.created+" grounded item"+(r.created==1?"":"s")+" added · review evidence #"+r.reviewEvidenceId);validationState.setTextColor(CortexUi.GREEN);Toast.makeText(this,"Deep Review applied to Cortex",Toast.LENGTH_LONG).show();}catch(Throwable e){validationState.setText("NOT APPLIED · "+safe(e));validationState.setTextColor(CortexUi.RED);}}).show();}

    int kindColor(String k){if("ACTION".equals(k)||"REVIEW".equals(k))return CortexUi.RED;if("WAITING".equals(k))return CortexUi.ORANGE;if("DECISION".equals(k)||"GOAL_SIGNAL".equals(k))return CortexUi.YELLOW;if("PROJECT_CANDIDATE".equals(k)||"IDEA".equals(k)||"OPPORTUNITY".equals(k)||"INSIGHT".equals(k)||"HYPOTHESIS".equals(k))return CortexUi.GREEN;return CortexUi.OLIVE;}
    String kindGlyph(String k){if("WAITING".equals(k))return"clock";if("DECISION".equals(k))return"decision";if("PROJECT_CANDIDATE".equals(k)||"GOAL_SIGNAL".equals(k))return"project";if("IDEA".equals(k)||"OPPORTUNITY".equals(k)||"INSIGHT".equals(k)||"HYPOTHESIS".equals(k))return"brain";return"open";}
    String ids(long[] xs){StringBuilder b=new StringBuilder();for(int i=0;i<xs.length;i++){if(i>0)b.append(", ");b.append('#').append(xs[i]);}return b.toString();}
    String safe(Throwable e){String s=e==null?"Unknown error":e.getMessage();return s==null||s.trim().isEmpty()?e.getClass().getSimpleName():s;}
    LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
}
