package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.database.Cursor;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.*;
import android.widget.*;

public class EnvironmentActivity extends Activity {
    static final int REQ_TREE=701;
    VaultDb db;LinearLayout box;TextView modelState,runtimeState,folderState,ocrState,providerState;ProgressBar modelProgress;Button modelAction,runtimeAction;Handler handler=new Handler(Looper.getMainLooper());boolean verifying=false;
    int bg=Color.rgb(11,12,14),surface=Color.rgb(24,26,30),text=Color.rgb(245,244,240),muted=Color.rgb(156,159,168),accent=Color.rgb(232,177,72),ok=Color.rgb(120,205,150),danger=Color.rgb(246,124,118),border=Color.rgb(47,50,57);
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setPlain(v,s);return v;}GradientDrawable round(int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);V41Maintenance.run(this,db);build();requestNotificationPermission();refresh();handler.postDelayed(()->LocalLlmRuntime.maybeAutoSelfTest(this,s->runOnUiThread(()->refresh())),800);}
    @Override protected void onResume(){super.onResume();refresh();handler.post(ticker);ScreenshotWorkScheduler.kick(this);}
    @Override protected void onPause(){super.onPause();handler.removeCallbacks(ticker);}
    Runnable ticker=new Runnable(){public void run(){if(!isFinishing()){refresh();handler.postDelayed(this,1000);}}};

    void build(){ScrollView sv=new ScrollView(this);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(18),dp(18),dp(28));box.setBackgroundColor(bg);sv.addView(box);TextView h=tv("CORTEX ENVIRONMENT",26,text);h.setTypeface(null,1);box.addView(h);TextView sub=tv("Prepare the phone for local AI, screenshot OCR and private-first reasoning.",13,muted);sub.setPadding(0,dp(4),0,dp(18));box.addView(sub);
        modelState=statusCard("LOCAL BRAIN MODEL","Qwen3-4B Q4_K_M • GGUF • 2.33 GB • verified official asset");modelProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);modelProgress.setMax(100);LinearLayout.LayoutParams pg=new LinearLayout.LayoutParams(-1,dp(8));pg.setMargins(0,0,0,dp(10));box.addView(modelProgress,pg);modelAction=button("DOWNLOAD MODEL");modelAction.setOnClickListener(v->modelAction());box.addView(modelAction,lp());Button remove=button("REMOVE LOCAL MODEL");remove.setOnClickListener(v->{LocalModelManager.remove(this);refresh();});box.addView(remove,lp());
        runtimeState=statusCard("LOCAL INFERENCE RUNTIME",LocalLlmRuntime.runtimeVersion()+" • CPU/NEON");runtimeAction=button("RUN LOCAL BRAIN SELF-TEST");runtimeAction.setOnClickListener(v->runSelfTest());box.addView(runtimeAction,lp());
        folderState=statusCard("SCREENSHOT SOURCE","Choose the folder Samsung saves screenshots into.");Button choose=button("CONNECT SCREENSHOT FOLDER");choose.setOnClickListener(v->chooseTree());box.addView(choose,lp());Button scan=button("SCAN NEW SCREENSHOTS");scan.setOnClickListener(v->scan());box.addView(scan,lp());Button repair=button("REPAIR + RE-ANALYZE SCREENSHOTS");repair.setOnClickListener(v->repairScreens());box.addView(repair,lp());
        ocrState=statusCard("OCR + LEARNING PIPELINE","Durable WorkManager queue • ML Kit Latin + bundled Tesseract Arabic • user teaching gate");providerState=statusCard("CLOUD FALLBACK","Gemini audio provider remains available; Groq remains fallback.");
        TextView debugTitle=tv("DEVELOPMENT EXPORT",11,accent);debugTitle.setTypeface(null,1);debugTitle.setPadding(dp(2),dp(10),0,dp(6));box.addView(debugTitle);TextView debugText=tv("One JSON snapshot with raw memories, OCR/transcripts, actions, temporal data, Smart Inbox state, model/runtime diagnostics, screenshot backlog, learning and health checks.",12,muted);debugText.setPadding(dp(2),0,dp(2),dp(9));box.addView(debugText);Button export=button("EXPORT DEBUG PACKAGE");export.setOnClickListener(v->DebugExporter.exportAndShare(this,db));box.addView(export,lp());
        TextView note=tv("Downloaded means bytes exist. Verified means official SHA-256 + GGUF passed. Installed appears only after Cortex loads Qwen through llama.cpp and a real local inference self-test returns successfully.",12,muted);note.setPadding(dp(2),dp(12),dp(2),0);box.addView(note);setContentView(sv);}

    TextView statusCard(String title,String sub){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(round(surface,border,20));TextView h=tv(title,11,accent);h.setTypeface(null,1);c.addView(h);TextView s=tv(sub,13,text);s.setPadding(0,dp(6),0,0);c.addView(s);TextView state=tv("",12,muted);state.setPadding(0,dp(8),0,0);c.addView(state);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));box.addView(c,p);return state;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(text);b.setAllCaps(false);b.setBackground(round(surface,border,16));return b;}LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,0,0,dp(9));return p;}

    void refresh(){
        LocalModelManager.Status s=LocalModelManager.status(this);StringBuilder d=new StringBuilder(s.label);if(s.percent>0)d.append(" • ").append(s.percent).append('%');if(s.done>0)d.append(" • ").append(LocalModelManager.human(s.done)).append(s.total>0?" / "+LocalModelManager.human(s.total):"");if(!s.detail.isEmpty())d.append("\n").append(s.detail);if(s.partialBytes>0&&!s.verified)d.append("\nResumable partial: ").append(LocalModelManager.human(s.partialBytes));if(s.httpStatus>0)d.append(" • HTTP ").append(s.httpStatus);modelState.setText(d.toString());modelState.setTextColor(s.failed?danger:(s.verified?ok:muted));modelProgress.setProgress(Math.max(0,Math.min(100,s.percent)));
        modelAction.setEnabled(!verifying);if(verifying)modelAction.setText("VERIFYING MODEL…");else if(s.verified)modelAction.setText("MODEL VERIFIED");else if("downloading".equals(s.state)||"connecting".equals(s.state)||"retrying".equals(s.state))modelAction.setText("PAUSE DOWNLOAD");else if("paused".equals(s.state)||"failed".equals(s.state)||"canceled".equals(s.state))modelAction.setText(s.partialBytes>0?"RESUME DOWNLOAD":"START DOWNLOAD");else if("verification_failed".equals(s.state))modelAction.setText("REDOWNLOAD MODEL");else if(LocalModelManager.filePresent(this)||"downloaded".equals(s.state))modelAction.setText("VERIFY DOWNLOADED MODEL");else modelAction.setText("DOWNLOAD MODEL");
        LocalLlmRuntime.State rt=LocalLlmRuntime.state(this);StringBuilder r=new StringBuilder(rt.label());if(rt.tokensPerSecond>0)r.append("\n").append(String.format(java.util.Locale.US,"%.2f tok/s",rt.tokensPerSecond)).append(" • ").append(rt.tokensGenerated).append(" tokens • ").append(rt.durationMs).append(" ms");if(!rt.selfTestText.isEmpty())r.append("\nSelf-test: ").append(clip(rt.selfTestText,120));if(!rt.error.isEmpty())r.append("\n").append(rt.error);runtimeState.setText(r.toString());runtimeState.setTextColor("ready".equals(rt.state)?ok:("failed".equals(rt.state)?danger:muted));runtimeAction.setEnabled(s.verified&&!"testing".equals(rt.state));runtimeAction.setText("testing".equals(rt.state)?"LOADING QWEN + SELF-TESTING…":("ready".equals(rt.state)?"RUN SELF-TEST AGAIN":"RUN LOCAL BRAIN SELF-TEST"));
        folderState.setText(ScreenshotIngestor.tree(this)==null?"Not connected":"Connected • "+ScreenshotIngestor.treeLabel(this));int queued=count("SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND status='queued'");int analyzing=count("SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND status='analyzing'");int analyzed=count("SELECT COUNT(*) FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND status='analyzed'");ocrState.setText((ArabicOcr.modelReady(this)?"Arabic OCR offline ready":"Arabic OCR model not ready")+" • analyzed "+analyzed+" • queued "+queued+" • analyzing "+analyzing+"\nTaught screenshots: "+ScreenshotLearning.taughtCount(db)+" • learned preference rules: "+ScreenshotLearning.learnedPreferenceCount(db));providerState.setText((GeminiKeyStore.has(this)?"Gemini configured":"Gemini not configured")+" • "+(GroqKeyStore.has(this)?"Groq fallback configured":"Groq fallback not configured"));
    }

    int count(String sql){Cursor c=db.getReadableDatabase().rawQuery(sql,null);int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
    String clip(String s,int n){return s.length()<=n?s:s.substring(0,n)+"…";}

    void runSelfTest(){if(!LocalModelManager.verified(this)){Toast.makeText(this,"Verify the Qwen model first",Toast.LENGTH_LONG).show();return;}Toast.makeText(this,"Loading Qwen locally and running a real inference self-test…",Toast.LENGTH_LONG).show();LocalLlmRuntime.runSelfTest(this,state->runOnUiThread(()->{refresh();Toast.makeText(this,"ready".equals(state.state)?"Local brain ready • real inference passed":"Local self-test failed: "+state.error,Toast.LENGTH_LONG).show();}));refresh();}
    void modelAction(){LocalModelManager.Status s=LocalModelManager.status(this);if(s.verified){runSelfTest();return;}if("downloading".equals(s.state)||"connecting".equals(s.state)||"retrying".equals(s.state)){LocalModelManager.pauseDownload(this);Toast.makeText(this,"Qwen download paused; progress is kept",Toast.LENGTH_SHORT).show();return;}if("paused".equals(s.state)||"failed".equals(s.state)||"canceled".equals(s.state)){LocalModelManager.resumeDownload(this);Toast.makeText(this,"Resuming Qwen from the saved partial file",Toast.LENGTH_LONG).show();return;}if("verification_failed".equals(s.state)){LocalModelManager.remove(this);LocalModelManager.startDownload(this);Toast.makeText(this,"Verification failed previously; clean download restarted",Toast.LENGTH_LONG).show();return;}if(LocalModelManager.filePresent(this)||"downloaded".equals(s.state)){verifyModel();return;}LocalModelManager.startDownload(this);Toast.makeText(this,"Cortex resumable Qwen download started",Toast.LENGTH_LONG).show();refresh();}
    void verifyModel(){if(verifying)return;verifying=true;refresh();new Thread(()->{LocalModelManager.Verification v=LocalModelManager.verify(this);runOnUiThread(()->{verifying=false;refresh();Toast.makeText(this,v.ok?"Verified: official SHA-256 + GGUF passed":v.message,Toast.LENGTH_LONG).show();if(v.ok)LocalLlmRuntime.maybeAutoSelfTest(this,state->runOnUiThread(()->refresh()));});}).start();}

    void requestNotificationPermission(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission("android.permission.POST_NOTIFICATIONS")!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{"android.permission.POST_NOTIFICATIONS"},702);}
    void chooseTree(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,REQ_TREE);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==REQ_TREE&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}ScreenshotIngestor.saveTree(this,u);refresh();scan();}}
    void scan(){if(ScreenshotIngestor.tree(this)==null){Toast.makeText(this,"Connect the screenshot folder first",Toast.LENGTH_LONG).show();return;}Toast.makeText(this,"Scanning screenshots…",Toast.LENGTH_SHORT).show();new Thread(()->{try{ScreenshotIngestor.Result r=ScreenshotIngestor.scan(this,db,3000);ScreenshotWorkScheduler.kick(this);runOnUiThread(()->Toast.makeText(this,"Imported "+r.imported+" • duplicates "+r.duplicates+(r.failed>0?" • failed "+r.failed:""),Toast.LENGTH_LONG).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Scan failed: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
    void repairScreens(){if(ScreenshotIngestor.tree(this)==null){Toast.makeText(this,"Connect the screenshot folder first",Toast.LENGTH_LONG).show();return;}Toast.makeText(this,"Repairing missing archived images…",Toast.LENGTH_SHORT).show();new Thread(()->{int n=ScreenshotIngestor.repairMissingAttachments(this,db,5000);ScreenshotWorkScheduler.kick(this);runOnUiThread(()->Toast.makeText(this,"Repaired and queued "+n+" missing screenshots",Toast.LENGTH_LONG).show());}).start();}
}
