package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.*;
import android.widget.*;

public class EnvironmentActivity extends Activity {
    static final int REQ_TREE=701;
    VaultDb db;LinearLayout box;TextView modelState,folderState,ocrState,providerState;ProgressBar modelProgress;Button modelAction;Handler handler=new Handler(Looper.getMainLooper());boolean verifying=false;
    int bg=Color.rgb(11,12,14),surface=Color.rgb(24,26,30),text=Color.rgb(245,244,240),muted=Color.rgb(156,159,168),accent=Color.rgb(232,177,72),ok=Color.rgb(120,205,150),danger=Color.rgb(246,124,118),border=Color.rgb(47,50,57);
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setPlain(v,s);return v;}GradientDrawable round(int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);build();refresh();}
    @Override protected void onResume(){super.onResume();refresh();handler.post(ticker);}
    @Override protected void onPause(){super.onPause();handler.removeCallbacks(ticker);}
    Runnable ticker=new Runnable(){public void run(){if(!isFinishing()){refresh();handler.postDelayed(this,1000);}}};

    void build(){ScrollView sv=new ScrollView(this);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(18),dp(18),dp(28));box.setBackgroundColor(bg);sv.addView(box);TextView h=tv("CORTEX ENVIRONMENT",26,text);h.setTypeface(null,1);box.addView(h);TextView sub=tv("Prepare the phone for local AI, screenshot OCR and private-first reasoning.",13,muted);sub.setPadding(0,dp(4),0,dp(18));box.addView(sub);
        modelState=statusCard("LOCAL BRAIN","Qwen3-4B Q4_K_M • GGUF • ~2.5 GB");modelProgress=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);modelProgress.setMax(100);LinearLayout.LayoutParams pg=new LinearLayout.LayoutParams(-1,dp(8));pg.setMargins(0,0,0,dp(10));box.addView(modelProgress,pg);modelAction=button("DOWNLOAD MODEL");modelAction.setOnClickListener(v->modelAction());box.addView(modelAction,lp());Button remove=button("REMOVE LOCAL MODEL");remove.setOnClickListener(v->{LocalModelManager.remove(this);refresh();});box.addView(remove,lp());
        folderState=statusCard("SCREENSHOT SOURCE","Choose the folder Samsung saves screenshots into.");Button choose=button("CONNECT SCREENSHOT FOLDER");choose.setOnClickListener(v->chooseTree());box.addView(choose,lp());Button scan=button("SCAN NEW SCREENSHOTS");scan.setOnClickListener(v->scan());box.addView(scan,lp());
        ocrState=statusCard("OCR PIPELINE","ML Kit Latin + Tesseract Arabic → structured screenshot memory");providerState=statusCard("CLOUD FALLBACK","Gemini audio provider remains available; local reasoning runtime is prepared separately.");
        TextView debugTitle=tv("DEVELOPMENT EXPORT",11,accent);debugTitle.setTypeface(null,1);debugTitle.setPadding(dp(2),dp(10),0,dp(6));box.addView(debugTitle);TextView debugText=tv("One JSON snapshot with raw memories, OCR/transcripts, actions, temporal data, Smart Inbox state, feature matrix, model state and automatic health checks. API keys and binary files are excluded.",12,muted);debugText.setPadding(dp(2),0,dp(2),dp(9));box.addView(debugText);Button export=button("EXPORT DEBUG PACKAGE");export.setOnClickListener(v->DebugExporter.exportAndShare(this,db));box.addView(export,lp());
        TextView note=tv("Truthful states: Downloaded means the GGUF file exists. Verified means SHA-256 + GGUF header passed. Installed will only be shown after the native inference runtime loads the model and passes a self-test.",12,muted);note.setPadding(dp(2),dp(12),dp(2),0);box.addView(note);setContentView(sv);}

    TextView statusCard(String title,String sub){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(16),dp(14),dp(16),dp(14));c.setBackground(round(surface,border,20));TextView h=tv(title,11,accent);h.setTypeface(null,1);c.addView(h);TextView s=tv(sub,13,text);s.setPadding(0,dp(6),0,0);c.addView(s);TextView state=tv("",12,muted);state.setPadding(0,dp(8),0,0);c.addView(state);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));box.addView(c,p);return state;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(text);b.setAllCaps(false);b.setBackground(round(surface,border,16));return b;}LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,0,0,dp(9));return p;}

    void refresh(){LocalModelManager.Status s=LocalModelManager.status(this);String detail=s.label;if(s.percent>0)detail+=" • "+s.percent+"%";if(s.done>0)detail+=" • "+LocalModelManager.human(s.done)+(s.total>0&&s.total!=s.done?" / "+LocalModelManager.human(s.total):"");if(s.verified)detail+=" • GGUF + SHA verified";if(s.verified&&!LocalModelManager.runtimeInstalled(this))detail+=" • inference runtime not installed yet";modelState.setText(detail);modelState.setTextColor(s.failed?danger:(s.verified?ok:muted));modelProgress.setProgress(Math.max(0,Math.min(100,s.percent)));modelAction.setEnabled(!verifying);if(verifying)modelAction.setText("VERIFYING MODEL…");else if(s.verified)modelAction.setText("MODEL VERIFIED");else if(LocalModelManager.filePresent(this)||s.percent>=100)modelAction.setText("VERIFY DOWNLOADED MODEL");else if(s.percent>0)modelAction.setText("DOWNLOADING "+s.percent+"%");else modelAction.setText("DOWNLOAD MODEL");folderState.setText(ScreenshotIngestor.tree(this)==null?"Not connected":"Connected • "+ScreenshotIngestor.treeLabel(this));ocrState.setText("Ready • screenshots are opened as image files, OCR-read, classified and stored with structured fields");providerState.setText((GeminiKeyStore.has(this)?"Gemini configured":"Gemini not configured")+" • "+(GroqKeyStore.has(this)?"Groq fallback configured":"Groq fallback not configured"));}

    void modelAction(){LocalModelManager.Status s=LocalModelManager.status(this);if(s.verified){Toast.makeText(this,"Model asset is verified. Native inference runtime is the remaining step.",Toast.LENGTH_LONG).show();return;}if(LocalModelManager.filePresent(this)||s.percent>=100){verifyModel();return;}if(s.percent>0&&s.percent<100){Toast.makeText(this,"Download is already running in Android Download Manager",Toast.LENGTH_LONG).show();return;}try{LocalModelManager.startDownload(this);Toast.makeText(this,"Direct model download started in the background",Toast.LENGTH_LONG).show();refresh();}catch(Exception e){Toast.makeText(this,e.getMessage(),Toast.LENGTH_LONG).show();}}
    void verifyModel(){if(verifying)return;verifying=true;refresh();new Thread(()->{LocalModelManager.Verification v=LocalModelManager.verify(this);runOnUiThread(()->{verifying=false;refresh();Toast.makeText(this,v.ok?"Verified: model file is genuine and GGUF-valid":v.message,Toast.LENGTH_LONG).show();});}).start();}

    void chooseTree(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,REQ_TREE);}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(req==REQ_TREE&&result==RESULT_OK&&data!=null&&data.getData()!=null){Uri u=data.getData();try{getContentResolver().takePersistableUriPermission(u,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}ScreenshotIngestor.saveTree(this,u);refresh();scan();}}
    void scan(){if(ScreenshotIngestor.tree(this)==null){Toast.makeText(this,"Connect the screenshot folder first",Toast.LENGTH_LONG).show();return;}Toast.makeText(this,"Scanning screenshots…",Toast.LENGTH_SHORT).show();new Thread(()->{try{ScreenshotIngestor.Result r=ScreenshotIngestor.scan(this,db,300);runOnUiThread(()->Toast.makeText(this,"Imported "+r.imported+" • duplicates "+r.duplicates+(r.failed>0?" • failed "+r.failed:""),Toast.LENGTH_LONG).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Scan failed: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
}
