package com.kareem.cortex;

import android.app.*;
import android.content.Intent;
import android.graphics.Color;
import android.os.Bundle;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** Read-only provenance surface: what Cortex actually captured, before interpretation. */
public final class EvidenceActivity extends Activity {
    VaultDb db;LinearLayout list,filterRow;EditText search;TextView stats;String filter="all";final SimpleDateFormat fmt=new SimpleDateFormat("dd MMM · HH:mm",Locale.US);
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);build();refresh();}
    @Override protected void onDestroy(){try{if(db!=null)db.close();}catch(Throwable ignored){}super.onDestroy();}

    void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setClipToPadding(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(10),dp(18),dp(24));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        body.addView(header());
        LinearLayout hero=CortexUi.card(this,24);hero.setPadding(dp(16),dp(16),dp(16),dp(15));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);top.addView(CortexUi.glyph(this,"nodes",CortexUi.GREEN,true),new LinearLayout.LayoutParams(dp(54),dp(54)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(13),0,0,0);top.addView(tx,xp);TextView h=CortexUi.plain(this,"What Cortex actually saw",20,CortexUi.TEXT);CortexUi.medium(h);tx.addView(h);TextView sub=CortexUi.text(this,"Raw captures, shares, notifications, files, screen context and analysis state. Evidence is shown here before memory, priority or interpretation.",11,CortexUi.MUTED);sub.setPadding(0,dp(5),0,0);tx.addView(sub);hero.addView(top);stats=CortexUi.plain(this,"",10,CortexUi.GREEN);CortexUi.medium(stats);stats.setPadding(dp(2),dp(13),0,0);hero.addView(stats);body.addView(hero,margins(0,8,0,0));

        search=new EditText(this);search.setHint("Search evidence…");search.setHintTextColor(CortexUi.FAINT);search.setTextColor(CortexUi.TEXT);search.setTextSize(13);search.setSingleLine(true);search.setPadding(dp(14),0,dp(14),0);search.setBackground(CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER,18));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(50));sp.setMargins(0,dp(14),0,0);body.addView(search,sp);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){refresh();}public void afterTextChanged(Editable e){}});
        HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);filterRow=new LinearLayout(this);filterRow.setOrientation(LinearLayout.HORIZONTAL);filterRow.setPadding(0,dp(10),0,dp(4));hsv.addView(filterRow);body.addView(hsv);renderFilters();
        TextView section=CortexUi.plain(this,"EVIDENCE STREAM",10,CortexUi.GREEN);CortexUi.medium(section);if(android.os.Build.VERSION.SDK_INT>=21)section.setLetterSpacing(.09f);section.setPadding(dp(1),dp(12),0,dp(8));body.addView(section);
        list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);
        CortexUi.addBottomNav(this,root,"evidence",null);setContentView(root);
    }

    View header(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(5),dp(8),dp(2),dp(11));TextView back=CortexUi.plain(this,"‹",30,CortexUi.MUTED);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());row.addView(back,new LinearLayout.LayoutParams(dp(38),dp(40)));View dot=new View(this);dot.setBackground(CortexUi.round(this,CortexUi.GREEN,Color.TRANSPARENT,999));LinearLayout.LayoutParams dpv=new LinearLayout.LayoutParams(dp(9),dp(9));dpv.setMargins(dp(2),0,0,0);row.addView(dot,dpv);TextView c=CortexUi.plain(this,"C O R T E X",14,CortexUi.TEXT);CortexUi.bold(c);if(android.os.Build.VERSION.SDK_INT>=21)c.setLetterSpacing(.20f);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-2,dp(40));cp.setMargins(dp(11),0,0,0);row.addView(c,cp);View d=CortexUi.divider(this);LinearLayout.LayoutParams dv=new LinearLayout.LayoutParams(dp(1),dp(28));dv.setMargins(dp(12),0,dp(12),0);row.addView(d,dv);TextView sys=CortexUi.plain(this,"EVIDENCE",10,CortexUi.MUTED);if(android.os.Build.VERSION.SDK_INT>=21)sys.setLetterSpacing(.10f);row.addView(sys,new LinearLayout.LayoutParams(0,dp(40),1));CortexGlyphView deep=CortexUi.glyph(this,"brain",CortexUi.GREEN,false);deep.setOnClickListener(v->startActivity(new Intent(this,DeepReviewActivity.class)));row.addView(deep,new LinearLayout.LayoutParams(dp(46),dp(46)));return row;}

    void renderFilters(){filterRow.removeAllViews();addFilter("all","All");addFilter("capture","Captures");addFilter("phone","Phone");addFilter("visual","Visual");addFilter("attention","Needs review");}
    void addFilter(String key,String label){boolean on=key.equals(filter);TextView v=CortexUi.chip(this,label,on?CortexUi.GREEN:CortexUi.MUTED,on);v.setOnClickListener(x->{filter=key;renderFilters();refresh();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(34));p.setMargins(0,0,dp(8),0);filterRow.addView(v,p);}

    void refresh(){if(db==null||list==null)return;String q=search==null?"":search.getText().toString();ArrayList<KnowledgeItem> all=db.lexicalSearch(q,240);int shown=0,processing=0,failed=0;list.removeAllViews();for(KnowledgeItem k:all){if(k==null)continue;if("queued".equals(k.status)||"analyzing".equals(k.status))processing++;if("analysis_failed".equals(k.status)||"failed_retryable".equals(k.status))failed++;if(!matches(k))continue;list.addView(row(k),margins(0,shown==0?0:8,0,0));shown++;if(shown>=120)break;}int total=db.lexicalSearch("",400).size();stats.setText(total+" captured  •  "+db.pendingCount()+" processing  •  "+db.failedCount()+" need review");if(shown==0){LinearLayout empty=CortexUi.card(this,20);TextView t=CortexUi.text(this,"No evidence matches this view.",13,CortexUi.MUTED);empty.addView(t);list.addView(empty);}}

    boolean matches(KnowledgeItem k){if("all".equals(filter))return true;String type=n(k.type).toUpperCase(Locale.US),src=n(k.source).toLowerCase(Locale.US),st=n(k.status);if("capture".equals(filter))return src.equals("manual")||src.equals("manual_recording")||src.equals("android_share")||src.equals("quick_capture")||src.contains("screen_understand");if("phone".equals(filter))return type.equals("NOTIFICATION")||type.equals("CONTACT")||src.contains("notification")||src.contains("phone")||src.contains("calendar")||src.contains("contacts");if("visual".equals(filter))return type.contains("IMAGE")||type.contains("SCREENSHOT")||src.contains("screen")||src.contains("photo");if("attention".equals(filter))return st.equals("queued")||st.equals("analyzing")||st.equals("analysis_failed")||st.equals("failed_retryable");return true;}

    View row(KnowledgeItem k){int color=color(k),iconColor=color;LinearLayout card=CortexUi.card(this,19);card.setPadding(0,0,0,0);LinearLayout main=new LinearLayout(this);main.setGravity(Gravity.CENTER_VERTICAL);main.setPadding(dp(11),dp(11),dp(10),dp(10));View rail=new View(this);rail.setBackground(CortexUi.round(this,color,Color.TRANSPARENT,999));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(dp(2),dp(50));rp.setMargins(0,0,dp(10),0);main.addView(rail,rp);main.addView(CortexUi.glyph(this,glyph(k),iconColor,false),new LinearLayout.LayoutParams(dp(46),dp(46)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(10),0,dp(8),0);main.addView(tx,xp);String title=empty(k.title)?friendly(k):k.title;TextView h=CortexUi.text(this,clip(title,90),14,CortexUi.TEXT);CortexUi.medium(h);h.setMaxLines(2);tx.addView(h);String body=!empty(k.summary)?k.summary:(!empty(k.extractedText)?k.extractedText:k.rawText);TextView sub=CortexUi.text(this,clip(body,130),10,CortexUi.MUTED);sub.setMaxLines(2);sub.setPadding(0,dp(4),0,0);tx.addView(sub);TextView meta=CortexUi.plain(this,"#"+k.id+"  •  "+friendlySource(k.source)+"  •  "+age(k.createdAt),8,CortexUi.FAINT);meta.setPadding(0,dp(5),0,0);tx.addView(meta);main.addView(CortexUi.chip(this,statusLabel(k.status),statusColor(k.status),false),new LinearLayout.LayoutParams(-2,dp(30)));card.addView(main);card.setOnClickListener(v->detail(k));return card;}

    void detail(KnowledgeItem k){StringBuilder b=new StringBuilder();b.append("Evidence #").append(k.id).append("\n").append(n(k.type)).append(" · ").append(friendlySource(k.source)).append("\n").append(fmt.format(new Date(k.createdAt))).append("\n\n");if(!empty(k.summary))b.append("SUMMARY\n").append(k.summary).append("\n\n");if(!empty(k.extractedText))b.append("EXTRACTED\n").append(k.extractedText).append("\n\n");if(!empty(k.rawText))b.append("RAW\n").append(k.rawText).append("\n\n");b.append("STATUS\n").append(n(k.status));if(!empty(k.analysisError))b.append("\n\nANALYSIS ERROR\n").append(k.analysisError);new AlertDialog.Builder(this).setTitle(empty(k.title)?"Evidence":k.title).setMessage(b.toString()).setPositiveButton("Close",null).show();}

    int color(KnowledgeItem k){String t=n(k.type).toUpperCase(Locale.US);if(t.contains("AUDIO"))return CortexUi.RED;if(t.contains("IMAGE")||t.contains("SCREENSHOT"))return CortexUi.GREEN;if(t.contains("FILE")||t.contains("PDF")||t.contains("DOCUMENT"))return CortexUi.ORANGE;if(t.contains("TEXT")||t.contains("NOTE"))return CortexUi.YELLOW;if(t.contains("NOTIFICATION"))return CortexUi.OLIVE;return CortexUi.GREEN;}
    String glyph(KnowledgeItem k){String t=n(k.type).toUpperCase(Locale.US);if(t.contains("AUDIO"))return"wave";if(t.contains("IMAGE")||t.contains("SCREENSHOT"))return"photo";if(t.contains("FILE")||t.contains("PDF")||t.contains("DOCUMENT"))return"file";if(t.contains("TEXT")||t.contains("NOTE"))return"text";return"nodes";}
    int statusColor(String s){s=n(s);if(s.equals("analysis_failed")||s.equals("failed_retryable"))return CortexUi.RED;if(s.equals("queued")||s.equals("analyzing"))return CortexUi.ORANGE;return CortexUi.GREEN;}
    String statusLabel(String s){s=n(s);if(s.equals("analysis_failed")||s.equals("failed_retryable"))return"REVIEW";if(s.equals("queued"))return"QUEUED";if(s.equals("analyzing"))return"READING";return"READY";}
    String friendly(KnowledgeItem k){String t=n(k.type).toLowerCase(Locale.US).replace('_',' ');return t.isEmpty()?"Captured evidence":Character.toUpperCase(t.charAt(0))+t.substring(1);}
    String friendlySource(String s){String x=n(s).replace('_',' ').replace('-',' ').trim();return x.isEmpty()?"Cortex":x;}
    String age(long when){long d=Math.max(0,System.currentTimeMillis()-when),m=d/60000;if(m<1)return"now";if(m<60)return m+"m";long h=m/60;if(h<24)return h+"h";long day=h/24;if(day<14)return day+"d";return fmt.format(new Date(when));}
    String clip(String s,int n){String x=EvidenceActivity.n(s).replaceAll("\\s+"," ").trim();return x.length()>n?x.substring(0,n)+"…":x;}
    LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    static boolean empty(String s){return s==null||s.trim().isEmpty();}static String n(String s){return s==null?"":s;}
}
