package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.os.Bundle;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** CORTEX UI DESIGN LOCK V1 dedicated immutable Evidence ledger. */
public final class EvidenceActivity extends Activity {
    VaultDb db;LinearLayout list,filterRow;EditText search;String filter="all";long expandedId=0;int totalCount,processingCount,reviewedCount;TextView totalStat,processingStat,reviewedStat;final SimpleDateFormat fmt=new SimpleDateFormat("dd MMM · HH:mm",Locale.US);
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);build();refresh();}
    @Override protected void onDestroy(){try{if(db!=null)db.close();}catch(Throwable ignored){}super.onDestroy();}

    void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);
        root.addView(header(),new LinearLayout.LayoutParams(-1,dp(72)));

        LinearLayout searchWrap=new LinearLayout(this);searchWrap.setGravity(Gravity.CENTER_VERTICAL);searchWrap.setPadding(dp(14),0,dp(10),0);searchWrap.setBackground(CortexUi.round(this,Color.rgb(20,22,20),Color.rgb(55,59,53),16));searchWrap.addView(new CortexLineIconView(this,"search",CortexUi.LIME),new LinearLayout.LayoutParams(dp(28),dp(28)));
        search=new EditText(this);search.setHint("Search evidence by content, source, or tags…");search.setHintTextColor(CortexUi.MUTED);search.setTextColor(CortexUi.TEXT);search.setTextSize(12);search.setSingleLine(true);search.setPadding(dp(10),0,dp(8),0);search.setBackgroundColor(Color.TRANSPARENT);searchWrap.addView(search,new LinearLayout.LayoutParams(0,-1,1));searchWrap.addView(new CortexLineIconView(this,"list",CortexUi.LIME),new LinearLayout.LayoutParams(dp(28),dp(28)));LinearLayout.LayoutParams swp=new LinearLayout.LayoutParams(-1,dp(54));swp.setMargins(dp(18),dp(2),dp(18),0);root.addView(searchWrap,swp);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){refresh();}public void afterTextChanged(Editable e){}});

        HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);filterRow=new LinearLayout(this);filterRow.setOrientation(LinearLayout.HORIZONTAL);filterRow.setPadding(dp(18),dp(12),dp(10),dp(8));hsv.addView(filterRow);root.addView(hsv,new LinearLayout.LayoutParams(-1,dp(58)));

        LinearLayout sort=new LinearLayout(this);sort.setGravity(Gravity.CENTER_VERTICAL);sort.setPadding(dp(19),dp(3),dp(18),dp(5));TextView newest=CortexUi.plain(this,"Sorted by newest ⌄",10,CortexUi.MUTED);sort.addView(newest,new LinearLayout.LayoutParams(0,-2,1));sort.addView(new CortexLineIconView(this,"list",CortexUi.LIME),new LinearLayout.LayoutParams(dp(28),dp(28)));root.addView(sort,new LinearLayout.LayoutParams(-1,dp(42)));

        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setClipToPadding(false);sv.setVerticalScrollBarEnabled(false);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);list.setPadding(dp(18),0,dp(18),dp(18));sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        root.addView(summaryBar(),new LinearLayout.LayoutParams(-1,dp(78)));setContentView(root);CortexUi.fitSystemBars(this,root);
    }

    View header(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(18),dp(8),dp(17),0);row.addView(circleButton("back",CortexUi.TEXT,()->finish()),new LinearLayout.LayoutParams(dp(48),dp(48)));CortexLineIconView logo=new CortexLineIconView(this,"logo",CortexUi.LIME);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(dp(32),dp(32));lp.setMargins(dp(14),0,0,0);row.addView(logo,lp);TextView title=CortexUi.plain(this,"Evidence",24,CortexUi.TEXT);CortexUi.bold(title);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(0,-2,1);tp.setMargins(dp(7),0,0,0);row.addView(title,tp);row.addView(new CortexLineIconView(this,"search",CortexUi.TEXT),new LinearLayout.LayoutParams(dp(34),dp(34)));LinearLayout.LayoutParams fp=new LinearLayout.LayoutParams(dp(34),dp(34));fp.setMargins(dp(16),0,0,0);row.addView(new CortexLineIconView(this,"filter",CortexUi.TEXT),fp);return row;}

    View summaryBar(){LinearLayout outer=new LinearLayout(this);outer.setPadding(dp(18),dp(6),dp(18),dp(10));LinearLayout bar=new LinearLayout(this);bar.setGravity(Gravity.CENTER);bar.setBackground(CortexUi.round(this,Color.rgb(19,21,19),Color.rgb(41,45,40),16));totalStat=summaryCell(bar,"evidence",CortexUi.LIME,"0","Total items",0);processingStat=summaryCell(bar,"history",CortexUi.ORANGE,"0","Processing",1);reviewedStat=summaryCell(bar,"shield",CortexUi.LIME,"0","Reviewed",2);outer.addView(bar,new LinearLayout.LayoutParams(-1,-1));return outer;}
    TextView summaryCell(LinearLayout row,String icon,int color,String value,String label,int index){if(index>0){View d=new View(this);d.setBackgroundColor(Color.rgb(56,60,54));row.addView(d,new LinearLayout.LayoutParams(dp(1),dp(38)));}LinearLayout cell=new LinearLayout(this);cell.setGravity(Gravity.CENTER);cell.addView(new CortexLineIconView(this,icon,color),new LinearLayout.LayoutParams(dp(30),dp(30)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(-2,-2);xp.setMargins(dp(8),0,0,0);cell.addView(tx,xp);TextView n=CortexUi.plain(this,value,15,color);CortexUi.bold(n);tx.addView(n);TextView l=CortexUi.plain(this,label,9,CortexUi.MUTED);tx.addView(l);row.addView(cell,new LinearLayout.LayoutParams(0,-1,1));return n;}

    void refresh(){if(db==null||list==null)return;String q=search==null?"":search.getText().toString();ArrayList<KnowledgeItem> all=db.lexicalSearch(q,260);totalCount=all.size();processingCount=0;reviewedCount=0;for(KnowledgeItem k:all){if(k==null)continue;if(processing(k))processingCount++;else if(!failed(k))reviewedCount++;}if(totalStat!=null){totalStat.setText(String.valueOf(totalCount));processingStat.setText(String.valueOf(processingCount));reviewedStat.setText(String.valueOf(reviewedCount));}renderFilters();list.removeAllViews();int shown=0;for(KnowledgeItem k:all){if(k==null||!matches(k))continue;list.addView(row(k),margins(0,shown==0?0:1,0,0));if(expandedId==k.id)list.addView(detailPanel(k),margins(dp(46),-1,dp(8),dp(8)));shown++;if(shown>=140)break;}if(shown==0){TextView empty=CortexUi.text(this,"No evidence matches this view.",12,CortexUi.MUTED);empty.setGravity(Gravity.CENTER);empty.setPadding(0,dp(42),0,dp(42));list.addView(empty);}}

    void renderFilters(){if(filterRow==null)return;filterRow.removeAllViews();addFilter("all","All  "+totalCount);addFilter("processing","Processing  "+processingCount);addFilter("reviewed","Reviewed  "+reviewedCount);addFilter("files","Files");addFilter("voice","Voice");addFilter("photos","Photos");}
    void addFilter(String key,String label){boolean on=key.equals(filter);TextView c=CortexUi.plain(this,label,10,on?CortexUi.LIME:CortexUi.TEXT);c.setGravity(Gravity.CENTER);c.setPadding(dp(13),0,dp(13),0);c.setBackground(CortexUi.round(this,on?Color.argb(15,185,218,77):Color.rgb(20,22,20),on?CortexUi.LIME:Color.rgb(58,62,56),999));c.setOnClickListener(v->{filter=key;expandedId=0;refresh();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(38));p.setMargins(0,0,dp(8),0);filterRow.addView(c,p);}

    boolean matches(KnowledgeItem k){if("all".equals(filter))return true;String type=n(k.type).toUpperCase(Locale.US);if("processing".equals(filter))return processing(k);if("reviewed".equals(filter))return !processing(k)&&!failed(k);if("files".equals(filter))return type.contains("FILE")||type.contains("PDF")||type.contains("DOCUMENT");if("voice".equals(filter))return type.contains("AUDIO")||n(k.source).contains("record");if("photos".equals(filter))return type.contains("IMAGE")||type.contains("SCREENSHOT")||n(k.source).contains("photo")||n(k.source).contains("screen");return true;}

    View row(KnowledgeItem k){int color=statusColor(k),typeColor=CortexUi.LIME;LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setPadding(0,0,0,0);card.setBackground(CortexUi.round(this,Color.rgb(19,21,19),Color.rgb(55,59,53),10));LinearLayout main=new LinearLayout(this);main.setGravity(Gravity.CENTER_VERTICAL);main.setPadding(dp(11),dp(10),dp(10),dp(10));View dot=new View(this);dot.setBackground(CortexUi.round(this,color,Color.TRANSPARENT,999));LinearLayout.LayoutParams dotp=new LinearLayout.LayoutParams(dp(6),dp(6));dotp.setMargins(0,0,dp(8),0);main.addView(dot,dotp);main.addView(iconDisc(glyph(k),CortexUi.TEXT),new LinearLayout.LayoutParams(dp(46),dp(46)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(11),0,dp(7),0);main.addView(tx,xp);TextView title=CortexUi.text(this,clip(empty(k.title)?friendly(k):k.title,86),13,CortexUi.TEXT);CortexUi.medium(title);title.setMaxLines(2);tx.addView(title);TextView meta=CortexUi.plain(this,age(k.createdAt)+"  •  "+friendlySource(k.source),9,CortexUi.MUTED);meta.setPadding(0,dp(3),0,0);tx.addView(meta);TextView state=CortexUi.plain(this,statusLabel(k),9,color);state.setPadding(0,dp(4),0,0);tx.addView(state);TextView tag=CortexUi.chip(this,typeTag(k),typeColor,false);main.addView(tag,new LinearLayout.LayoutParams(-2,dp(29)));LinearLayout.LayoutParams mop=new LinearLayout.LayoutParams(dp(22),dp(28));mop.setMargins(dp(6),0,0,0);main.addView(new CortexLineIconView(this,"more",CortexUi.MUTED),mop);card.addView(main);card.setOnClickListener(v->{expandedId=expandedId==k.id?0:k.id;refresh();});return card;}

    View detailPanel(KnowledgeItem k){LinearLayout panel=new LinearLayout(this);panel.setOrientation(LinearLayout.VERTICAL);panel.setPadding(dp(13),dp(12),dp(13),dp(11));panel.setBackground(CortexUi.round(this,Color.rgb(11,13,11),CortexUi.LIME,15));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);head.addView(new CortexLineIconView(this,"deep",CortexUi.LIME),new LinearLayout.LayoutParams(dp(24),dp(24)));TextView h=CortexUi.plain(this,!empty(k.extractedText)?"Extracted content":"Source content",10,CortexUi.LIME);CortexUi.medium(h);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(0,-2,1);hp.setMargins(dp(7),0,0,0);head.addView(h,hp);TextView id=CortexUi.plain(this,"Evidence #"+k.id,9,CortexUi.MUTED);head.addView(id);panel.addView(head);String body=!empty(k.extractedText)?k.extractedText:(!empty(k.rawText)?k.rawText:k.summary);TextView text=CortexUi.text(this,clip(body,1100),11,CortexUi.MUTED);text.setTextIsSelectable(true);text.setPadding(dp(10),dp(10),dp(10),dp(10));text.setBackground(CortexUi.round(this,Color.rgb(22,24,22),Color.rgb(58,62,56),12));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,-2);bp.setMargins(0,dp(9),0,dp(9));panel.addView(text,bp);LinearLayout foot=new LinearLayout(this);foot.setGravity(Gravity.CENTER_VERTICAL);foot.addView(new CortexLineIconView(this,"shield",CortexUi.LIME),new LinearLayout.LayoutParams(dp(22),dp(22)));TextView prov=CortexUi.plain(this,"Provenance",9,CortexUi.LIME);prov.setPadding(dp(6),0,0,0);foot.addView(prov);TextView fp=CortexUi.plain(this,"  sha256:"+shortFp(k.fingerprint),9,CortexUi.MUTED);foot.addView(fp,new LinearLayout.LayoutParams(0,-2,1));CortexLineIconView copy=new CortexLineIconView(this,"copy",CortexUi.MUTED);copy.setOnClickListener(v->copy(k.fingerprint));foot.addView(copy,new LinearLayout.LayoutParams(dp(22),dp(22)));CortexLineIconView lock=new CortexLineIconView(this,"lock",CortexUi.MUTED);LinearLayout.LayoutParams lk=new LinearLayout.LayoutParams(dp(22),dp(22));lk.setMargins(dp(10),0,0,0);foot.addView(lock,lk);TextView imm=CortexUi.plain(this,"Immutable",9,CortexUi.MUTED);imm.setPadding(dp(4),0,0,0);foot.addView(imm);panel.addView(foot);return panel;}

    View iconDisc(String kind,int color){FrameLayout b=new FrameLayout(this);b.setBackground(CortexUi.round(this,Color.rgb(22,24,22),Color.rgb(67,72,65),999));b.addView(new CortexLineIconView(this,kind,color),new FrameLayout.LayoutParams(dp(28),dp(28),Gravity.CENTER));return b;}
    View circleButton(String kind,int color,Runnable action){FrameLayout b=new FrameLayout(this);b.setBackground(CortexUi.round(this,Color.rgb(23,25,23),Color.rgb(55,59,53),999));b.addView(new CortexLineIconView(this,kind,color),new FrameLayout.LayoutParams(dp(27),dp(27),Gravity.CENTER));b.setOnClickListener(v->action.run());return b;}
    void copy(String s){try{((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(android.content.ClipData.newPlainText("Cortex provenance",n(s)));Toast.makeText(this,"Provenance copied",Toast.LENGTH_SHORT).show();}catch(Throwable ignored){}}

    boolean processing(KnowledgeItem k){String s=n(k.status);return s.equals("queued")||s.equals("analyzing");}boolean failed(KnowledgeItem k){String s=n(k.status);return s.equals("analysis_failed")||s.equals("failed_retryable");}
    int statusColor(KnowledgeItem k){if(failed(k))return CortexUi.RED;if(processing(k))return CortexUi.ORANGE;return CortexUi.LIME;}
    String statusLabel(KnowledgeItem k){if(failed(k))return"Needs review";if(processing(k))return"Processing  ↻";return"Reviewed  ✓";}
    String typeTag(KnowledgeItem k){String t=n(k.type).toUpperCase(Locale.US);if(t.contains("AUDIO"))return"Voice";if(t.contains("SCREENSHOT"))return"Screenshot";if(t.contains("IMAGE"))return"Photo";if(t.contains("FILE")||t.contains("PDF")||t.contains("DOCUMENT"))return"File";if(n(k.source).contains("clipboard"))return"Clipboard";return"Evidence";}
    String glyph(KnowledgeItem k){String t=n(k.type).toUpperCase(Locale.US);if(t.contains("AUDIO"))return"wave";if(t.contains("IMAGE")||t.contains("SCREENSHOT"))return"photo";return"file";}
    String friendly(KnowledgeItem k){String t=n(k.type).toLowerCase(Locale.US).replace('_',' ');return t.isEmpty()?"Captured evidence":Character.toUpperCase(t.charAt(0))+t.substring(1);}
    String friendlySource(String s){String x=n(s).replace('_',' ').replace('-',' ').trim();return x.isEmpty()?"Cortex":x;}
    String age(long when){long d=Math.max(0,System.currentTimeMillis()-when),m=d/60000;if(m<1)return"Now";if(m<60)return m+"m ago";long h=m/60;if(h<24)return h+"h ago";long day=h/24;if(day<7)return day+"d ago";return fmt.format(new Date(when));}
    String shortFp(String s){String x=n(s);if(x.length()<=16)return x;return x.substring(0,7)+"…"+x.substring(x.length()-6);}
    String clip(String s,int max){String x=n(s).replaceAll("\\s+"," ").trim();return x.length()>max?x.substring(0,max)+"…":x;}
    LinearLayout.LayoutParams margins(int l,int t,int r,int b){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(dp(l),dp(t),dp(r),dp(b));return p;}
    static boolean empty(String s){return s==null||s.trim().isEmpty();}static String n(String s){return s==null?"":s;}
}
