package com.kareem.cortex;

import android.app.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

/** Advanced Diagnostics: explicit real provider checks using synthetic/non-private inputs only. */
public class ExternalModelCheckActivity extends Activity {
    TextView status,detail,run,retryVision;volatile boolean destroyed=false;final ExecutorService worker=Executors.newSingleThreadExecutor();ExternalBrainProvider.HealthReport lastAsk,lastVision;GeminiCognitiveReasoningProviderV4.HealthReport lastGeminiBrain;
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);build();}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}

    void build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(18),dp(20),dp(28));root.setBackgroundColor(CortexUi.BG);sv.addView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView h=CortexUi.plain(this,"External model check",27,CortexUi.TEXT);CortexUi.medium(h);head.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView close=CortexUi.chip(this,"Close",CortexUi.MUTED,false);close.setOnClickListener(v->finish());head.addView(close);root.addView(head);TextView intro=CortexUi.text(this,"Three explicit real tests: automatic Gemini Deep Brain, optional Ask/external reasoning, and production Gemini Vision. No personal Cortex evidence is sent by these health checks.",12,CortexUi.MUTED);intro.setPadding(0,dp(8),0,dp(16));root.addView(intro);
        LinearLayout card=CortexUi.card(this,22);status=CortexUi.text(this,"Not checked yet",17,CortexUi.TEXT);CortexUi.medium(status);card.addView(status);detail=CortexUi.text(this,"Press the button below to test the same production Gemini transport Cortex uses for autonomous prioritization.",12,CortexUi.MUTED);detail.setPadding(0,dp(9),0,0);detail.setTextIsSelectable(true);card.addView(detail);root.addView(card,new LinearLayout.LayoutParams(-1,-2));run=CortexUi.action(this,"Run Gemini Brain + Ask + Vision checks",CortexUi.ACCENT,true);run.setOnClickListener(v->runCheck());LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(50));rp.setMargins(0,dp(14),0,0);root.addView(run,rp);
        TextView vh=CortexUi.section(this,"Visual Intelligence recovery");vh.setPadding(0,dp(18),0,dp(8));root.addView(vh);retryVision=CortexUi.action(this,"Run Gemini Vision check before retry",CortexUi.MUTED,false);retryVision.setEnabled(false);retryVision.setAlpha(.45f);retryVision.setOnClickListener(v->retryFailedVision());root.addView(retryVision,new LinearLayout.LayoutParams(-1,dp(48)));setContentView(sv);}

    void runCheck(){if(destroyed||worker.isShutdown())return;run.setEnabled(false);run.setText("Checking automatic Gemini Brain…");status.setText("RUNNING");detail.setText("1/3 · Testing Gemini Deep Brain with the exact production endpoint and structured-output schema…");try{worker.execute(()->{
        GeminiCognitiveReasoningProviderV4.HealthReport geminiBrain=GeminiCognitiveReasoningProviderV4.healthCheck(getApplicationContext());lastGeminiBrain=geminiBrain;post(()->{run.setText("Checking Ask/external reasoning…");detail.setText("AUTOMATIC GEMINI DEEP BRAIN\n"+geminiBrain.human()+"\n\n2/3 · Testing the optional Ask/external route…");});
        ExternalBrainProvider.HealthReport ask=ExternalBrainProvider.healthCheck(getApplicationContext());lastAsk=ask;post(()->{run.setText("Checking Gemini Vision…");detail.setText("AUTOMATIC GEMINI DEEP BRAIN\n"+geminiBrain.human()+"\n\nASK / EXTERNAL REASONING\n"+ask.human()+"\n\n3/3 · Testing Gemini Vision with a generated synthetic image…");});
        ExternalBrainProvider.HealthReport vision=GeminiVisionAnalyzer.healthCheck(getApplicationContext());lastVision=vision;log(geminiBrain,ask,vision);post(()->show(geminiBrain,ask,vision));
    });}catch(RejectedExecutionException e){run.setEnabled(true);run.setText("Run Gemini Brain + Ask + Vision checks");}}

    void log(GeminiCognitiveReasoningProviderV4.HealthReport geminiBrain,ExternalBrainProvider.HealthReport ask,ExternalBrainProvider.HealthReport vision){VaultDb db=null;try{db=new VaultDb(getApplicationContext());JSONObject g=new JSONObject().put("provider","gemini").put("configured",geminiBrain.configured).put("ok",geminiBrain.ok).put("model",geminiBrain.model).put("http_code",geminiBrain.httpCode).put("latency_ms",geminiBrain.latencyMs).put("status",geminiBrain.status).put("error",geminiBrain.error),a=metrics(ask),v=metrics(vision);if(geminiBrain.ok)DiagnosticsLog.info(db,"ExternalModelCheck","gemini_deep_brain_end_to_end","pass",0,0,0,0,0,geminiBrain.latencyMs,g);else DiagnosticsLog.warn(db,"ExternalModelCheck","gemini_deep_brain_end_to_end","fail","GEMINI_DEEP_BRAIN_CHECK",0,0,0,0,0,g);if(ask.ok)DiagnosticsLog.info(db,"ExternalModelCheck","ask_external_end_to_end","pass",0,0,0,0,0,ask.latencyMs,a);else DiagnosticsLog.warn(db,"ExternalModelCheck","ask_external_end_to_end","fail","ASK_EXTERNAL_CHECK",0,0,0,0,0,a);if(vision.ok)DiagnosticsLog.info(db,"ExternalModelCheck","vision_end_to_end","pass",0,0,0,0,0,vision.latencyMs,v);else DiagnosticsLog.warn(db,"ExternalModelCheck","vision_end_to_end","fail","VISION_MODEL_CHECK",0,0,0,0,0,v);}catch(Throwable ignored){}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}}
    JSONObject metrics(ExternalBrainProvider.HealthReport r){try{return new JSONObject().put("provider",r.provider).put("configured",r.configured).put("ok",r.ok).put("model",r.model).put("http_code",r.httpCode).put("latency_ms",r.latencyMs).put("status",r.status).put("error",r.error);}catch(Throwable e){return new JSONObject();}}

    void show(GeminiCognitiveReasoningProviderV4.HealthReport geminiBrain,ExternalBrainProvider.HealthReport ask,ExternalBrainProvider.HealthReport vision){if(destroyed)return;boolean core=geminiBrain.ok;if(core)status.setText("CORE PASS · automatic Gemini Deep Brain ready");else status.setText("CORE FAIL · automatic Gemini Deep Brain unavailable");long checked=Math.max(geminiBrain.checkedAt,Math.max(ask.checkedAt,vision.checkedAt));String when=new SimpleDateFormat("dd MMM yyyy · HH:mm:ss",Locale.getDefault()).format(new Date(checked));int failed=failedVisionCount();boolean imagesCloud=PrivacyPolicy.canUseCloud(this,"images"),canRetry=vision.ok&&imagesCloud&&failed>0;StringBuilder text=new StringBuilder();text.append("AUTOMATIC GEMINI DEEP BRAIN\n").append(geminiBrain.human()).append("\n\nASK / EXTERNAL REASONING\n").append(ask.human()).append("\n\nPRODUCTION GEMINI VISION\n").append(vision.human()).append("\n\nChecked: ").append(when).append("\n\nIMPORTANT: Gemini Deep Brain is the autonomous model-ranking lane. Ask/OpenRouter passing does not compensate for a failed Gemini Deep Brain check.\nImages privacy: ").append(PrivacyPolicy.label(PrivacyPolicy.mode(this,"images"))).append("\nVisual failures currently stored: ").append(failed);detail.setText(text.toString());run.setEnabled(true);run.setText("Run Gemini Brain + Ask + Vision checks again");retryVision.setEnabled(canRetry);retryVision.setAlpha(canRetry?1f:.45f);if(failed<=0)retryVision.setText("No failed visual items to retry");else if(!vision.ok)retryVision.setText("Gemini Vision must pass before retry");else if(!imagesCloud)retryVision.setText("Images are "+PrivacyPolicy.label(PrivacyPolicy.mode(this,"images"))+" · retry stays protected");else retryVision.setText("Retry failed visual understanding ("+Math.min(50,failed)+")");if(geminiBrain.ok&&CognitiveAutoReasoningSettingsV4.enabled(this))CognitiveReasoningOrchestratorV4.schedule(this,"external_model_check_passed");}

    int failedVisionCount(){VaultDb db=null;try{db=new VaultDb(getApplicationContext());return VisualInsightStore.countFailed(db);}catch(Throwable e){return 0;}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}}
    void retryFailedVision(){if(lastVision==null||!lastVision.ok){Toast.makeText(this,"Run a successful Gemini Vision check first",Toast.LENGTH_LONG).show();return;}if(!PrivacyPolicy.canUseCloud(this,"images")){Toast.makeText(this,"Images are "+PrivacyPolicy.label(PrivacyPolicy.mode(this,"images"))+". Change Images privacy before background cloud retry.",Toast.LENGTH_LONG).show();return;}retryVision.setEnabled(false);retryVision.setText("Re-queuing failed visual items…");try{worker.execute(()->{VaultDb db=null;int n=0;try{db=new VaultDb(getApplicationContext());n=VisualInsightStore.requeueFailed(db,50);DiagnosticsLog.info(db,"VisualRecovery","manual_requeue","ok",0,0,0,0,0,0,new JSONObject().put("requeued",n).put("vision_provider",lastVision.model));}catch(Throwable ignored){}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}if(n>0)VisualIntelligenceScheduler.kick(getApplicationContext());final int count=n;post(()->{Toast.makeText(this,count+" visual item"+(count==1?"":"s")+" queued for safe retry",Toast.LENGTH_LONG).show();retryVision.setText("Retry requested · "+count+" queued");});});}catch(RejectedExecutionException ignored){}}
    void post(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())r.run();});}
}
