package com.kareem.cortex;

import android.app.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

/** Advanced Diagnostics: real Brain + real synthetic Vision checks; never uploads private Cortex evidence. */
public class ExternalModelCheckActivity extends Activity {
    TextView status,detail,run,retryVision;volatile boolean destroyed=false;final ExecutorService worker=Executors.newSingleThreadExecutor();ExternalBrainProvider.HealthReport lastBrain,lastVision;
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);build();runCheck();}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}

    void build(){ScrollView sv=new ScrollView(this);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(dp(20),dp(18),dp(20),dp(28));root.setBackgroundColor(CortexUi.BG);sv.addView(root);LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView h=CortexUi.plain(this,"External model check",27,CortexUi.TEXT);CortexUi.medium(h);head.addView(h,new LinearLayout.LayoutParams(0,-2,1));TextView close=CortexUi.chip(this,"Close",CortexUi.MUTED,false);close.setOnClickListener(v->finish());head.addView(close);root.addView(head);TextView intro=CortexUi.text(this,"Two real tests: Primary Brain (OpenRouter/OX Alpha when configured) and production Gemini Vision using a generated non-private image. No personal Cortex evidence is sent.",12,CortexUi.MUTED);intro.setPadding(0,dp(8),0,dp(16));root.addView(intro);
        LinearLayout card=CortexUi.card(this,22);status=CortexUi.text(this,"Not checked yet",17,CortexUi.TEXT);CortexUi.medium(status);card.addView(status);detail=CortexUi.text(this,"",12,CortexUi.MUTED);detail.setPadding(0,dp(9),0,0);detail.setTextIsSelectable(true);card.addView(detail);root.addView(card,new LinearLayout.LayoutParams(-1,-2));run=CortexUi.action(this,"Run Brain + Vision checks",CortexUi.ACCENT,true);run.setOnClickListener(v->runCheck());LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(50));rp.setMargins(0,dp(14),0,0);root.addView(run,rp);
        TextView vh=CortexUi.section(this,"Visual Intelligence recovery");vh.setPadding(0,dp(18),0,dp(8));root.addView(vh);retryVision=CortexUi.action(this,"Retry failed visual understanding",CortexUi.MUTED,false);retryVision.setEnabled(false);retryVision.setAlpha(.45f);retryVision.setOnClickListener(v->retryFailedVision());root.addView(retryVision,new LinearLayout.LayoutParams(-1,dp(48)));setContentView(sv);}

    void runCheck(){if(destroyed||worker.isShutdown())return;run.setEnabled(false);run.setText("Checking Primary Brain…");status.setText("RUNNING");detail.setText("1/2 · Testing the configured primary Brain route with a minimal non-private request…");try{worker.execute(()->{
        ExternalBrainProvider.HealthReport brain=ExternalBrainProvider.healthCheck(getApplicationContext());lastBrain=brain;post(()->{run.setText("Checking Gemini Vision…");detail.setText("Primary Brain\n"+brain.human()+"\n\n2/2 · Testing production Gemini Vision with a generated synthetic image…");});
        ExternalBrainProvider.HealthReport vision=GeminiVisionAnalyzer.healthCheck(getApplicationContext());lastVision=vision;log(brain,vision);post(()->show(brain,vision));
    });}catch(RejectedExecutionException e){run.setEnabled(true);run.setText("Run Brain + Vision checks");}}

    void log(ExternalBrainProvider.HealthReport brain,ExternalBrainProvider.HealthReport vision){VaultDb db=null;try{db=new VaultDb(getApplicationContext());JSONObject b=metrics(brain),v=metrics(vision);if(brain.ok)DiagnosticsLog.info(db,"ExternalModelCheck","brain_end_to_end","pass",0,0,0,0,0,brain.latencyMs,b);else DiagnosticsLog.warn(db,"ExternalModelCheck","brain_end_to_end","fail","EXTERNAL_BRAIN_CHECK",0,0,0,0,0,b);if(vision.ok)DiagnosticsLog.info(db,"ExternalModelCheck","vision_end_to_end","pass",0,0,0,0,0,vision.latencyMs,v);else DiagnosticsLog.warn(db,"ExternalModelCheck","vision_end_to_end","fail","VISION_MODEL_CHECK",0,0,0,0,0,v);}catch(Throwable ignored){}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}}
    JSONObject metrics(ExternalBrainProvider.HealthReport r){try{return new JSONObject().put("provider",r.provider).put("configured",r.configured).put("ok",r.ok).put("model",r.model).put("http_code",r.httpCode).put("latency_ms",r.latencyMs).put("status",r.status).put("error",r.error);}catch(Throwable e){return new JSONObject();}}

    void show(ExternalBrainProvider.HealthReport brain,ExternalBrainProvider.HealthReport vision){if(destroyed)return;boolean both=brain.ok&&vision.ok;if(both)status.setText("PASS · Brain + Vision ready");else if(brain.ok)status.setText("PARTIAL · Brain ready · Vision unavailable");else if(vision.ok)status.setText("PARTIAL · Vision ready · Brain unavailable");else status.setText("FAIL · external AI routes unavailable");String when=new SimpleDateFormat("dd MMM yyyy · HH:mm:ss",Locale.getDefault()).format(new Date(Math.max(brain.checkedAt,vision.checkedAt)));int failed=failedVisionCount();boolean imagesCloud=PrivacyPolicy.canUseCloud(this,"images"),canRetry=vision.ok&&imagesCloud&&failed>0;StringBuilder text=new StringBuilder();text.append("PRIMARY BRAIN\n").append(brain.human()).append("\n\nPRODUCTION VISION\n").append(vision.human()).append("\n\nChecked: ").append(when).append("\n\nCombined Brain falls back to local Cortex when its remote route fails. Visual recovery specifically requires Gemini Vision, not merely a Brain-provider PASS.\nImages privacy: ").append(PrivacyPolicy.label(PrivacyPolicy.mode(this,"images"))).append("\nVisual failures currently stored: ").append(failed);detail.setText(text.toString());run.setEnabled(true);run.setText("Run Brain + Vision checks again");retryVision.setEnabled(canRetry);retryVision.setAlpha(canRetry?1f:.45f);if(failed<=0)retryVision.setText("No failed visual items to retry");else if(!vision.ok)retryVision.setText("Gemini Vision must pass before retry");else if(!imagesCloud)retryVision.setText("Images are "+PrivacyPolicy.label(PrivacyPolicy.mode(this,"images"))+" · retry stays protected");else retryVision.setText("Retry failed visual understanding ("+Math.min(50,failed)+")");}

    int failedVisionCount(){VaultDb db=null;try{db=new VaultDb(getApplicationContext());return VisualInsightStore.countFailed(db);}catch(Throwable e){return 0;}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}}
    void retryFailedVision(){if(lastVision==null||!lastVision.ok){Toast.makeText(this,"Run a successful Gemini Vision check first",Toast.LENGTH_LONG).show();return;}if(!PrivacyPolicy.canUseCloud(this,"images")){Toast.makeText(this,"Images are "+PrivacyPolicy.label(PrivacyPolicy.mode(this,"images"))+". Change Images privacy before background cloud retry.",Toast.LENGTH_LONG).show();return;}retryVision.setEnabled(false);retryVision.setText("Re-queuing failed visual items…");try{worker.execute(()->{VaultDb db=null;int n=0;try{db=new VaultDb(getApplicationContext());n=VisualInsightStore.requeueFailed(db,50);DiagnosticsLog.info(db,"VisualRecovery","manual_requeue","ok",0,0,0,0,0,0,new JSONObject().put("requeued",n).put("vision_provider",lastVision.model));}catch(Throwable ignored){}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}if(n>0)VisualIntelligenceScheduler.kick(getApplicationContext());final int count=n;post(()->{Toast.makeText(this,count+" visual item"+(count==1?"":"s")+" queued for safe retry",Toast.LENGTH_LONG).show();retryVision.setText("Retry requested · "+count+" queued");});});}catch(RejectedExecutionException ignored){}}
    void post(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())r.run();});}
}
