package com.kareem.cortex;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.net.Uri;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

/** Data, privacy and integration controls with safe preview/approval for mutations. */
public class FeatureHubActivity extends Activity {
    static final int REQ_CAL=501,REQ_CONTACTS=502,REQ_RESTORE=503,REQ_BACKUP=504,REQ_FILE=505;LinearLayout body;volatile boolean destroyed=false;final ExecutorService worker=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"cortex-integrations");t.setPriority(Thread.NORM_PRIORITY-1);return t;});
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);VaultDb db=new VaultDb(this);try{FeatureStore.ensure(db);}finally{db.close();}build();}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),dp(26));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));TextView h=CortexUi.plain(this,"Data & integrations",27,CortexUi.TEXT);CortexUi.medium(h);head.addView(h,new LinearLayout.LayoutParams(0,-2,1));body.addView(head);
        body.addView(CortexUi.section(this,"Data"));row("Backup & restore","Export your Cortex archive or validate a backup before restoring",this::backupRestore);row("Import file","Choose a file from Android Files or Drive and open its Cortex result",this::pickFile);
        body.addView(CortexUi.section(this,"Privacy"));row("Privacy controls","Choose how each source may be processed or used by cloud AI",this::showPrivacy);row("Phone context access","Notifications, Accessibility and Usage Access",()->startActivity(new Intent(this,PhoneContextAccessActivity.class)));row("Notification access","Manage notification capture permission",this::notificationMemory);
        body.addView(CortexUi.section(this,"Integrations"));row("Calendar","Import Android Calendar events; writes use approval-first drafts",this::syncCalendar);row("Contacts","Import Android contacts for grounded person identity",this::syncContacts);
        body.addView(CortexUi.section(this,"Execution"));row("Approval-first action handoff","Verify Calendar, email and message drafts through the real Android handlers. Cortex never presses Send/Save for you.",this::showActionHandoff);
        setContentView(root);CortexUi.fitSystemBars(this,root);}
    void row(String title,String sub,Runnable action){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(2),dp(14),dp(2),dp(14));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);TextView t=CortexUi.plain(this,title,15,CortexUi.TEXT);CortexUi.medium(t);text.addView(t);TextView s=CortexUi.text(this,sub,11,CortexUi.MUTED);s.setPadding(0,dp(3),0,0);text.addView(s);c.addView(text,new LinearLayout.LayoutParams(0,-2,1));TextView go=CortexUi.plain(this,"›",25,CortexUi.MUTED);go.setGravity(Gravity.CENTER);c.addView(go,new LinearLayout.LayoutParams(dp(32),dp(44)));CortexUi.pressable(this,c,CortexUi.round(this,android.graphics.Color.TRANSPARENT,android.graphics.Color.TRANSPARENT,12));c.setOnClickListener(v->{if(!destroyed)action.run();});body.addView(c);body.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}

    void showPrivacy(){String[] sources={"audio","notifications","images","files","contacts","calendar","phone_context"};String[] labels=new String[sources.length];for(int i=0;i<sources.length;i++)labels[i]=cap(sources[i])+" — "+PrivacyPolicy.label(PrivacyPolicy.mode(this,sources[i]));new AlertDialog.Builder(this).setTitle("Privacy controls").setItems(labels,(d,w)->choosePrivacy(sources[w])).setNegativeButton("Close",null).show();}
    void choosePrivacy(String source){String[] opts={"AI allowed","Local only","Never collect"},vals={PrivacyPolicy.AI_ALLOWED,PrivacyPolicy.LOCAL_ONLY,PrivacyPolicy.NEVER};new AlertDialog.Builder(this).setTitle(cap(source)).setSingleChoiceItems(opts,index(vals,PrivacyPolicy.mode(this,source)),null).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{AlertDialog a=(AlertDialog)d;int pos=a.getListView().getCheckedItemPosition();if(pos>=0){PrivacyPolicy.set(this,source,vals[pos]);Toast.makeText(this,opts[pos],Toast.LENGTH_SHORT).show();}}).show();}int index(String[] x,String v){for(int i=0;i<x.length;i++)if(x[i].equals(v))return i;return 0;}
    void notificationMemory(){String mode=PrivacyPolicy.mode(this,"notifications");new AlertDialog.Builder(this).setTitle("Notification access").setMessage("Current privacy mode: "+PrivacyPolicy.label(mode)).setNegativeButton("Close",null).setNeutralButton("Privacy",(d,w)->showPrivacy()).setPositiveButton("Open Android settings",(d,w)->{try{startActivity(new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS));}catch(Throwable e){Toast.makeText(this,"Could not open settings",Toast.LENGTH_LONG).show();}}).show();}

    void backupRestore(){String[] opts={"Export backup","Validate + restore backup"};new AlertDialog.Builder(this).setTitle("Backup & restore").setItems(opts,(d,w)->{if(w==0)startBackup();else startRestore();}).setNegativeButton("Close",null).show();}
    void startBackup(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/zip");i.putExtra(Intent.EXTRA_TITLE,"Cortex-backup-"+new SimpleDateFormat("yyyy-MM-dd-HHmm",Locale.US).format(new Date())+".zip");startActivityForResult(i,REQ_BACKUP);}
    void startRestore(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/zip");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,REQ_RESTORE);}

    void showActionHandoff(){String[] opts={"Calendar draft","Email draft","Message draft"};new AlertDialog.Builder(this).setTitle("Test approval-first execution").setMessage("Cortex will only open a prepared draft in the owning app. Nothing is saved or sent unless you explicitly confirm there.").setItems(opts,(d,w)->confirmDraft(w)).setNegativeButton("Close",null).show();}
    void confirmDraft(int which){String kind=which==0?"calendar event":which==1?"email":"message";new AlertDialog.Builder(this).setTitle("Open "+kind+" draft?").setMessage("This verifies the real Android handoff. Cortex will not complete the external action automatically.").setNegativeButton("Cancel",null).setPositiveButton("Open draft",(d,w)->{boolean ok;if(which==0)ok=CortexActionExecutor.calendarDraft(this,"Cortex approval-first draft","Diagnostic draft from Cortex. Delete/close it unless you intentionally want to save it.",System.currentTimeMillis()+60L*60L*1000L);else if(which==1)ok=CortexActionExecutor.emailDraft(this,"","Cortex approval-first draft","This is a Cortex draft. Nothing was sent automatically.");else ok=CortexActionExecutor.messageDraft(this,"","This is a Cortex draft. Nothing was sent automatically.");if(!ok)Toast.makeText(this,"No compatible Android handler was available",Toast.LENGTH_LONG).show();}).show();}

    void syncCalendar(){if(!PrivacyPolicy.canCollect(this,"calendar")){Toast.makeText(this,"Calendar is set to Never collect",Toast.LENGTH_LONG).show();return;}if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.READ_CALENDAR)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.READ_CALENDAR},REQ_CAL);return;}doCalendar();}
    void syncContacts(){if(!PrivacyPolicy.canCollect(this,"contacts")){Toast.makeText(this,"Contacts are set to Never collect",Toast.LENGTH_LONG).show();return;}if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.READ_CONTACTS},REQ_CONTACTS);return;}doContacts();}
    void doCalendar(){Toast.makeText(this,"Importing calendar…",Toast.LENGTH_SHORT).show();executeDb("calendar",db->IntegrationEngine.importCalendar(getApplicationContext(),db));}
    void doContacts(){Toast.makeText(this,"Importing contacts…",Toast.LENGTH_SHORT).show();executeDb("contacts",db->IntegrationEngine.importContacts(getApplicationContext(),db));}
    interface DbWork{int run(VaultDb db)throws Exception;}
    void executeDb(String label,DbWork work){try{worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());int n=work.run(db);final int count=n;post(()->Toast.makeText(this,count+" "+label+" item"+(count==1?"":"s")+" imported",Toast.LENGTH_LONG).show());}catch(Throwable e){post(()->Toast.makeText(this,cap(label)+" import failed safely",Toast.LENGTH_LONG).show());}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}});}catch(RejectedExecutionException ignored){}}
    void pickFile(){if(!PrivacyPolicy.canCollect(this,"files")){Toast.makeText(this,"Files are set to Never collect",Toast.LENGTH_LONG).show();return;}Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivityForResult(i,REQ_FILE);}

    @Override public void onRequestPermissionsResult(int req,String[] p,int[] g){super.onRequestPermissionsResult(req,p,g);if(g.length==0||g[0]!=PackageManager.PERMISSION_GRANTED){Toast.makeText(this,"Permission not granted",Toast.LENGTH_SHORT).show();return;}if(req==REQ_CAL)doCalendar();else if(req==REQ_CONTACTS)doContacts();}
    @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;Uri u=data.getData();if(req==REQ_BACKUP)backupAsync(u);else if(req==REQ_RESTORE)inspectRestore(u);else if(req==REQ_FILE)openImportResult(u);}
    void backupAsync(Uri u){Toast.makeText(this,"Creating backup…",Toast.LENGTH_SHORT).show();try{worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());int n=BackupExporter.write(getApplicationContext(),db,u);post(()->Toast.makeText(this,"Backup complete • "+n+" memories",Toast.LENGTH_LONG).show());}catch(Throwable e){post(()->Toast.makeText(this,"Backup failed safely",Toast.LENGTH_LONG).show());}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}});}catch(RejectedExecutionException ignored){}}
    void inspectRestore(Uri u){Toast.makeText(this,"Checking backup before restore…",Toast.LENGTH_SHORT).show();try{worker.execute(()->{BackupImporter.Inspection x=BackupImporter.inspect(getApplicationContext(),u);post(()->{if(!x.valid){new AlertDialog.Builder(this).setTitle("Backup cannot be restored").setMessage(x.human()).setPositiveButton("Close",null).show();return;}new AlertDialog.Builder(this).setTitle("Restore this validated backup?").setMessage(x.human()+"\n\nThe next step will add non-duplicate memories to the live Vault. Existing memories are not intentionally deleted.").setNegativeButton("Cancel",null).setPositiveButton("Restore",(d,w)->restoreAsync(u)).show();});});}catch(RejectedExecutionException ignored){}}
    void restoreAsync(Uri u){Toast.makeText(this,"Restoring validated backup…",Toast.LENGTH_SHORT).show();try{worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());int n=BackupImporter.restore(getApplicationContext(),db,u);post(()->Toast.makeText(this,"Restore complete • "+n+" added",Toast.LENGTH_LONG).show());}catch(Throwable e){post(()->Toast.makeText(this,"Restore stopped safely: "+safe(e.getMessage()),Toast.LENGTH_LONG).show());}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}});}catch(RejectedExecutionException ignored){}}
    void openImportResult(Uri u){try{Intent i=new Intent(this,CaptureActivity.class);String mime=getContentResolver().getType(u);i.setAction(Intent.ACTION_SEND);i.setType(mime==null?"application/octet-stream":mime);i.putExtra(Intent.EXTRA_STREAM,u);i.setClipData(ClipData.newUri(getContentResolver(),"Cortex import",u));i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);startActivity(i);}catch(Throwable e){Toast.makeText(this,"Could not open Cortex import",Toast.LENGTH_LONG).show();}}
    void post(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())try{r.run();}catch(Throwable ignored){}});}String cap(String s){return s==null||s.isEmpty()?"":Character.toUpperCase(s.charAt(0))+s.substring(1);}String safe(String s){return s==null?"":s;}
}
