package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.provider.Settings;
import android.view.*;
import android.widget.*;

/** PRIME input surface: intentional capture plus Everywhere Cortex controls. */
public class InputActivity extends Activity {
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);build();}
    @Override protected void onPostResume(){super.onPostResume();StartupMaintenance.schedule(this);}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(16),dp(20),dp(28));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Input",31,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);TextView sub=CortexUi.text(this,"Capture anything. Cortex will understand it, connect it, and suggest what to do next.",12,CortexUi.MUTED);sub.setPadding(0,dp(4),0,0);titles.addView(sub);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView settings=CortexUi.chip(this,"Settings",CortexUi.MUTED,false);settings.setOnClickListener(v->open(SettingsActivity.class));head.addView(settings,new LinearLayout.LayoutParams(-2,dp(36)));body.addView(head);
        body.addView(CortexUi.section(this,"Capture"));LinearLayout row1=new LinearLayout(this);row1.setOrientation(LinearLayout.HORIZONTAL);addTile(row1,"Voice","Speak naturally\nArabic + English","voice",0);addTile(row1,"Text / Paste","Notes, prompts, ideas\nor copied text","text",8);body.addView(row1,new LinearLayout.LayoutParams(-1,dp(132)));LinearLayout row2=new LinearLayout(this);row2.setOrientation(LinearLayout.HORIZONTAL);addTile(row2,"Photo","Take or import\nvisual evidence","photo",0);addTile(row2,"File","Documents, audio\nand attachments","file",8);LinearLayout.LayoutParams r2=new LinearLayout.LayoutParams(-1,dp(132));r2.setMargins(0,dp(8),0,0);body.addView(row2,r2);

        TextView everywhere=CortexUi.section(this,"Everywhere Cortex");everywhere.setTextSize(17);everywhere.setPadding(0,dp(24),0,dp(10));body.addView(everywhere);LinearLayout hero=CortexUi.card(this,24);hero.setPadding(dp(18),dp(17),dp(18),dp(17));TextView eh=CortexUi.plain(this,"Cortex from anywhere on your phone",18,CortexUi.TEXT);CortexUi.medium(eh);hero.addView(eh);TextView ed=CortexUi.text(this,"Understand the current app, share anything into Cortex, or start voice capture without navigating back here. Every path returns to the same understanding/result flow.",12,CortexUi.MUTED);ed.setPadding(0,dp(7),0,dp(14));hero.addView(ed);body.addView(hero);

        boolean screenReady=CortexScreenAccessibilityService.connected();LinearLayout screen=CortexUi.card(this,20);screen.setPadding(dp(16),dp(15),dp(16),dp(15));TextView et=CortexUi.plain(this,"Understand this screen",15,CortexUi.TEXT);CortexUi.medium(et);screen.addView(et);TextView eb=CortexUi.text(this,screenReady?"READY · Use the Understand screen Quick Settings tile while any app is visible. Cortex will open the captured screen context as a result.":"SETUP NEEDED · Enable Cortex Screen Understanding once, then add the Understand screen Quick Settings tile.",12,screenReady?CortexUi.SAGE:CortexUi.MUTED);eb.setPadding(0,dp(6),0,0);screen.addView(eb);TextView screenAction=CortexUi.action(this,screenReady?"Open Quick Settings setup":"Enable screen understanding",CortexUi.ACCENT,true);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,dp(46));ep.setMargins(0,dp(12),0,0);screen.addView(screenAction,ep);screenAction.setOnClickListener(v->{try{startActivity(new Intent(screenReady?"android.settings.QUICK_SETTINGS_SETTINGS":Settings.ACTION_ACCESSIBILITY_SETTINGS));}catch(Throwable e){try{startActivity(new Intent(Settings.ACTION_ACCESSIBILITY_SETTINGS));}catch(Throwable ignored){}}});LinearLayout.LayoutParams scp=new LinearLayout.LayoutParams(-1,-2);scp.setMargins(0,dp(10),0,0);body.addView(screen,scp);

        LinearLayout share=CortexUi.card(this,20);share.setPadding(dp(16),dp(15),dp(16),dp(15));TextView st=CortexUi.plain(this,"From another app",15,CortexUi.TEXT);CortexUi.medium(st);share.addView(st);TextView sb=CortexUi.text(this,"READY · Android Share → Cortex accepts text, links, screenshots, audio and files. A single shared item opens its Cortex understanding result immediately.",12,CortexUi.SAGE);sb.setPadding(0,dp(6),0,0);share.addView(sb);TextView shareHelp=CortexUi.action(this,"Show share instruction",CortexUi.MUTED,false);LinearLayout.LayoutParams shp=new LinearLayout.LayoutParams(-1,dp(44));shp.setMargins(0,dp(10),0,0);share.addView(shareHelp,shp);shareHelp.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("Share to Cortex").setMessage("In any app, tap Share and choose Cortex. Cortex imports the original item safely, analyzes it, then opens What Cortex understood + useful next actions.").setPositiveButton("Got it",null).show());LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,-2);sp.setMargins(0,dp(10),0,0);body.addView(share,sp);

        LinearLayout voiceTile=CortexUi.card(this,20);voiceTile.setPadding(dp(16),dp(15),dp(16),dp(15));TextView vt=CortexUi.plain(this,"Quick voice",15,CortexUi.TEXT);CortexUi.medium(vt);voiceTile.addView(vt);TextView vb=CortexUi.text(this,"Start the exact same one-tap voice capture now, or use the Cortex Voice Quick Settings tile from any app.",12,CortexUi.MUTED);vb.setPadding(0,dp(6),0,0);voiceTile.addView(vb);TextView voiceNow=CortexUi.action(this,"Start quick voice now",CortexUi.ACCENT,true);LinearLayout.LayoutParams vnp=new LinearLayout.LayoutParams(-1,dp(46));vnp.setMargins(0,dp(12),0,0);voiceTile.addView(voiceNow,vnp);voiceNow.setOnClickListener(v->capture("voice"));LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(-1,-2);vp.setMargins(0,dp(10),0,0);body.addView(voiceTile,vp);
        CortexUi.addBottomNav(this,root,"input",null);setContentView(root);}

    void addTile(LinearLayout row,String title,String description,String mode,int left){LinearLayout tile=CortexUi.card(this,22);tile.setGravity(Gravity.CENTER_VERTICAL);tile.setPadding(dp(16),dp(14),dp(16),dp(14));CortexUi.pressable(this,tile,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,22));TextView t=CortexUi.plain(this,title,16,CortexUi.TEXT);CortexUi.medium(t);tile.addView(t);TextView d=CortexUi.text(this,description,11,CortexUi.MUTED);d.setPadding(0,dp(6),0,0);tile.addView(d);tile.setOnClickListener(v->capture(mode));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(left),0,0,0);row.addView(tile,p);}
    void capture(String mode){try{Intent i=new Intent(this,CaptureActivity.class);i.putExtra("mode",mode);startActivity(i);}catch(Throwable ignored){}}void open(Class<?> cls){try{startActivity(new Intent(this,cls));}catch(Throwable ignored){}}
}
