package com.kareem.cortex;

import android.Manifest;
import android.app.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.media.MediaPlayer;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.JSONObject;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.*;

public class MainActivity extends Activity {
    static final int REQ_MIC=77,REQ_IMPORT_AUDIO=78;
    VaultDb db;LinearLayout list;EditText search;TextView count;Handler handler=new Handler(Looper.getMainLooper());Runnable pendingSearch,recordTick;
    AudioCapture recorder=new AudioCapture();File recordingFile;AlertDialog recordingDialog;long recordingStarted;
    int bg=Color.rgb(16,17,20),panel=Color.rgb(24,26,31),text=Color.rgb(243,244,246),muted=Color.rgb(165,168,176),accent=Color.rgb(232,177,72),danger=Color.rgb(255,139,139);

    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);buildUi();int imported=new ShareImporter(this,db).importIntent(getIntent());refresh("");queue();new Thread(()->{try{SemanticIndex.ensureIndexed(db,80);}catch(Exception ignored){}}).start();if(imported>0)Toast.makeText(this,"Saved to Cortex",Toast.LENGTH_SHORT).show();}
    @Override protected void onNewIntent(android.content.Intent i){super.onNewIntent(i);setIntent(i);int n=new ShareImporter(this,db).importIntent(i);refresh(search.getText().toString());queue();if(n>0)Toast.makeText(this,"Saved to Cortex",Toast.LENGTH_SHORT).show();}
    @Override protected void onDestroy(){super.onDestroy();if(recorder.isRunning())try{File f=recorder.stop();if(f!=null)f.delete();}catch(Exception ignored){} }

    TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setReadable(v,s);return v;}int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}void pad(View v,int a){v.setPadding(dp(a),dp(a),dp(a),dp(a));}
    Button smallButton(String label){Button b=new Button(this);b.setText(label);b.setTextSize(10);b.setTextColor(text);b.setBackgroundColor(panel);return b;}

    void buildUi(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(bg);pad(root,16);
        TextView title=tv("CORTEX",26,text);title.setTypeface(null,1);root.addView(title);TextView sub=tv("Your second brain • capture everything → understand → recall",14,muted);sub.setPadding(0,0,0,dp(12));root.addView(sub);
        LinearLayout searchRow=new LinearLayout(this);searchRow.setOrientation(LinearLayout.HORIZONTAL);search=new EditText(this);search.setHint("Search by words or meaning…");search.setHintTextColor(muted);search.setTextColor(text);search.setSingleLine(true);search.setBackgroundColor(panel);pad(search,12);searchRow.addView(search,new LinearLayout.LayoutParams(0,dp(50),1));Button add=new Button(this);add.setText("+");add.setTextSize(24);add.setTextColor(Color.BLACK);add.setBackgroundColor(accent);LinearLayout.LayoutParams addp=new LinearLayout.LayoutParams(dp(58),dp(50));addp.setMargins(dp(8),0,0,0);searchRow.addView(add,addp);root.addView(searchRow);
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);actions.setPadding(0,dp(8),0,0);Button voice=smallButton("● VOICE");Button ask=smallButton("ASK");Button packs=smallButton("PACKS");actions.addView(voice,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(44),1);bp.setMargins(dp(7),0,0,0);actions.addView(ask,bp);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(44),1);cp.setMargins(dp(7),0,0,0);actions.addView(packs,cp);root.addView(actions);
        count=tv("",12,muted);count.setPadding(0,dp(8),0,dp(8));root.addView(count);ScrollView sv=new ScrollView(this);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);sv.addView(list);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int b,int c){if(pendingSearch!=null)handler.removeCallbacks(pendingSearch);String q=s.toString();pendingSearch=()->refresh(q);handler.postDelayed(pendingSearch,220);}public void afterTextChanged(Editable e){}});
        add.setOnClickListener(v->showAddMenu());packs.setOnClickListener(v->showPacks());ask.setOnClickListener(v->showAsk());voice.setOnClickListener(v->startVoiceCapture());voice.setOnLongClickListener(v->{showAsrSettingsDialog();return true;});
    }

    void showAddMenu(){String[] choices={"Quick note / text","Prompt + example result","Record voice","Import recording for transcription test","ASR provider settings"};new AlertDialog.Builder(this).setTitle("Add to Cortex").setItems(choices,(d,w)->{if(w==0)addTextDialog();else if(w==1)promptBundleDialog();else if(w==2)startVoiceCapture();else if(w==3)startImportRecording();else showAsrSettingsDialog();}).show();}
    void startImportRecording(){if(!GroqKeyStore.has(this)&&!GeminiKeyStore.has(this)){showAsrSettingsDialog();Toast.makeText(this,"Add at least one ASR provider key, then choose Import recording again",Toast.LENGTH_LONG).show();return;}try{android.content.Intent i=new android.content.Intent(android.content.Intent.ACTION_OPEN_DOCUMENT);i.addCategory(android.content.Intent.CATEGORY_OPENABLE);i.setType("audio/*");startActivityForResult(i,REQ_IMPORT_AUDIO);}catch(Exception e){Toast.makeText(this,"Could not open audio picker: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    @Override protected void onActivityResult(int req,int result,android.content.Intent data){super.onActivityResult(req,result,data);if(req!=REQ_IMPORT_AUDIO||result!=RESULT_OK||data==null||data.getData()==null)return;android.net.Uri uri=data.getData();try{String mime=getContentResolver().getType(uri);long id=new ShareImporter(this,db).importAudio(uri,mime);if(id>0){Toast.makeText(this,"Recording imported — transcribing…",Toast.LENGTH_SHORT).show();refresh(search.getText().toString());queue();}else Toast.makeText(this,"Could not import recording or it already exists",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"Could not import recording: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    void addTextDialog(){EditText e=new EditText(this);e.setHint("Paste a note, URL, log, research, data…");e.setMinLines(7);new AlertDialog.Builder(this).setTitle("Quick capture").setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(d,w)->{String s=e.getText().toString().trim();if(s.isEmpty())return;String cat=AutoClassifier.category(s,"text/plain");long id=db.insert("TEXT","manual",AutoClassifier.title(s,"text/plain"),s,cat,AutoClassifier.tags(s,cat),"",Fingerprint.text(s),"{}");if(id<0)Toast.makeText(this,"Already in Cortex",Toast.LENGTH_SHORT).show();else{refresh(search.getText().toString());queue();}}).show();}
    void promptBundleDialog(){LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(20),0,dp(20),0);EditText prompt=field("Prompt *",5),input=field("Example input / context (optional)",3),result=field("Example result *",5);Spinner rating=new Spinner(this);String[] ratings={"Rating: not set","Rating: 1/5","Rating: 2/5","Rating: 3/5","Rating: 4/5","Rating: 5/5"};rating.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,ratings));box.addView(prompt);box.addView(input);box.addView(result);box.addView(rating);new AlertDialog.Builder(this).setTitle("Prompt + example").setView(box).setNegativeButton("Cancel",null).setPositiveButton("Save bundle",(d,w)->{String p=prompt.getText().toString().trim(),in=input.getText().toString().trim(),out=result.getText().toString().trim();if(p.isEmpty()||out.isEmpty()){Toast.makeText(this,"Prompt and result are required",Toast.LENGTH_SHORT).show();return;}long pid=db.insert("AI_PROMPT","manual",AutoClassifier.title(p,"text/plain"),p,"AI Prompts",AutoClassifier.tags(p,"AI Prompts")+",example","",Fingerprint.text("prompt|"+p),"{}");if(pid<0)pid=-pid;long iid=0;if(!in.isEmpty()){iid=db.insert("EXAMPLE_INPUT","manual",AutoClassifier.title(in,"text/plain"),in,"Examples","example,input","",Fingerprint.text("input|"+in),"{}");if(iid<0)iid=-iid;}long oid=db.insert("AI_RESULT","manual","Example result",out,"Examples","example,result","",Fingerprint.text("result|"+out),"{}");if(oid<0)oid=-oid;db.addExample(pid,iid,oid,rating.getSelectedItemPosition(),"");refresh(search.getText().toString());queue();Toast.makeText(this,"Prompt bundle saved",Toast.LENGTH_SHORT).show();}).show();}
    EditText field(String hint,int lines){EditText e=new EditText(this);e.setHint(hint);e.setMinLines(lines);e.setGravity(Gravity.TOP);return e;}

    void showAsrSettingsDialog(){
        String[] rows={"Groq Whisper Large v3 — "+(GroqKeyStore.has(this)?"configured":"missing"),"Gemini 3.6 Flash — "+(GeminiKeyStore.has(this)?"configured":"missing")};
        new AlertDialog.Builder(this).setTitle("ASR provider settings").setMessage("Cortex uses Gemini first and keeps Groq available as a fallback. Keys are encrypted with Android Keystore.").setItems(rows,(d,w)->{if(w==0)showGroqKeyDialog(false);else showGeminiKeyDialog();}).setNegativeButton("Close",null).show();
    }

    void showGroqKeyDialog(boolean continueToRecord){
        EditText e=new EditText(this);e.setHint("Paste Groq API key");e.setSingleLine(true);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);pad(e,12);
        boolean configured=GroqKeyStore.has(this);AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle(configured?"Groq transcription key":"Enable Groq transcription").setMessage("Paste the key once. Cortex encrypts it with Android Keystore and sends audio directly to Groq Whisper Large v3.").setView(e).setNegativeButton("Cancel",null).setPositiveButton(configured?"Replace key":"Save & continue",null);if(configured)b.setNeutralButton("Remove key",null);AlertDialog d=b.create();
        d.setOnShowListener(x->{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String key=e.getText().toString().trim();if(key.isEmpty()){e.setError("API key required");return;}try{GroqKeyStore.save(this,key);d.dismiss();Toast.makeText(this,"Groq transcription enabled",Toast.LENGTH_SHORT).show();if(continueToRecord)startVoiceCapture();}catch(Exception ex){Toast.makeText(this,"Could not save key: "+ex.getMessage(),Toast.LENGTH_LONG).show();}});if(configured)d.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{GroqKeyStore.clear(this);d.dismiss();Toast.makeText(this,"Groq key removed",Toast.LENGTH_SHORT).show();});});d.show();
    }

    void showGeminiKeyDialog(){
        EditText e=new EditText(this);e.setHint("Paste Gemini API key");e.setSingleLine(true);e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);pad(e,12);
        boolean configured=GeminiKeyStore.has(this);AlertDialog.Builder b=new AlertDialog.Builder(this).setTitle(configured?"Gemini transcription key":"Enable Gemini transcription").setMessage("Cortex encrypts this key with Android Keystore and sends audio to Gemini 3.6 Flash for transcription.").setView(e).setNegativeButton("Cancel",null).setPositiveButton(configured?"Replace key":"Save",null);if(configured)b.setNeutralButton("Remove key",null);AlertDialog d=b.create();
        d.setOnShowListener(x->{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String key=e.getText().toString().trim();if(key.isEmpty()){e.setError("API key required");return;}try{GeminiKeyStore.save(this,key);d.dismiss();Toast.makeText(this,"Gemini transcription enabled",Toast.LENGTH_SHORT).show();}catch(Exception ex){Toast.makeText(this,"Could not save Gemini key: "+ex.getMessage(),Toast.LENGTH_LONG).show();}});if(configured)d.getButton(AlertDialog.BUTTON_NEUTRAL).setOnClickListener(v->{GeminiKeyStore.clear(this);d.dismiss();Toast.makeText(this,"Gemini key removed",Toast.LENGTH_SHORT).show();});});d.show();
    }

    void startVoiceCapture(){if(!GroqKeyStore.has(this)&&!GeminiKeyStore.has(this)){showAsrSettingsDialog();return;}if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.RECORD_AUDIO)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.RECORD_AUDIO},REQ_MIC);return;}beginVoiceCapture();}
    @Override public void onRequestPermissionsResult(int req,String[] perms,int[] grants){super.onRequestPermissionsResult(req,perms,grants);if(req==REQ_MIC&&grants.length>0&&grants[0]==PackageManager.PERMISSION_GRANTED)beginVoiceCapture();else if(req==REQ_MIC)Toast.makeText(this,"Microphone permission is required for recording",Toast.LENGTH_LONG).show();}
    void beginVoiceCapture(){try{
        recordingFile=recorder.start(this);recordingStarted=System.currentTimeMillis();TextView timer=tv("Recording 00:00\nArabic + English transcription after you stop.",18,text);pad(timer,24);recordingDialog=new AlertDialog.Builder(this).setTitle("Cortex Voice").setView(timer).setCancelable(false).setPositiveButton("STOP & SAVE",null).setNegativeButton("CANCEL",null).create();recordingDialog.setOnShowListener(x->{recordingDialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->finishVoice(true));recordingDialog.getButton(AlertDialog.BUTTON_NEGATIVE).setOnClickListener(v->finishVoice(false));});recordingDialog.show();recordTick=new Runnable(){public void run(){long sec=(System.currentTimeMillis()-recordingStarted)/1000;timer.setText(String.format(Locale.US,"Recording %02d:%02d\nArabic + English transcription after you stop.",sec/60,sec%60));if(recorder.isRunning())handler.postDelayed(this,1000);}};handler.post(recordTick);
    }catch(Exception e){Toast.makeText(this,"Could not start recording: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    void finishVoice(boolean save){try{File f=recorder.stop();if(recordTick!=null)handler.removeCallbacks(recordTick);if(recordingDialog!=null)recordingDialog.dismiss();if(f==null)return;if(!save){f.delete();Toast.makeText(this,"Recording discarded",Toast.LENGTH_SHORT).show();return;}JSONObject m=new JSONObject();m.put("mime","audio/wav");m.put("bytes",f.length());m.put("recorded_at",System.currentTimeMillis());long id=db.insert("AUDIO","manual_recording","Voice recording","","Voice & Audio","voice,audio,transcript",f.getAbsolutePath(),Fingerprint.file(f.getAbsolutePath()),m.toString());if(id<0){f.delete();Toast.makeText(this,"Already in Cortex",Toast.LENGTH_SHORT).show();}else{Toast.makeText(this,"Voice saved — transcribing…",Toast.LENGTH_SHORT).show();refresh(search.getText().toString());queue();}}catch(Exception e){Toast.makeText(this,"Could not save recording: "+e.getMessage(),Toast.LENGTH_LONG).show();}}

    void queue(){AnalysisQueue.kick(this,db,()->runOnUiThread(()->refresh(search==null?"":search.getText().toString())));}
    void refresh(String q){ArrayList<KnowledgeItem> items=db.search(q);list.removeAllViews();int pending=db.pendingCount(),failed=db.failedCount();boolean semantic=q!=null&&!q.trim().isEmpty();count.setText(items.size()+" items"+(semantic?"  •  hybrid semantic recall":"")+(pending>0?"  •  "+pending+" analyzing":"")+(failed>0?"  •  "+failed+" failed":""));for(KnowledgeItem k:items)addMemoryCard(k);}
    void addMemoryCard(KnowledgeItem k){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setBackgroundResource(R.drawable.rounded_panel);pad(card,14);card.setClickable(true);card.setOnClickListener(v->detail(k));TextView t=tv(k.title,17,text);t.setTypeface(null,1);card.addView(t);TextView meta=tv(k.category+"  •  "+k.type+"  •  "+fmt(k.createdAt),12,muted);meta.setPadding(0,dp(5),0,dp(7));card.addView(meta);boolean retryable="failed_retryable".equals(k.status);String preview;if(retryable&&"AUDIO".equals(k.type))preview="Audio captured — transcription failed. Tap to review or Re-analyze.";else{preview=!empty(k.summary)?k.summary:(!empty(k.rawText)?k.rawText:k.extractedText);if(empty(preview)&&("SCREENSHOT".equals(k.type)||"IMAGE".equals(k.type)))preview="Image stored locally";if(empty(preview)&&"AUDIO".equals(k.type))preview="Audio stored locally • transcription pending";}if(preview!=null&&preview.length()>240)preview=preview.substring(0,240)+"…";card.addView(tv(preview==null?"":preview,14,text));TextView st=tv(statusText(k.status,k.analysisError),12,statusColor(k.status));st.setPadding(0,dp(8),0,0);card.addView(st);if(retryable){Button retry=smallButton("RE-ANALYZE");retry.setOnClickListener(v->{db.retry(k.id);refresh(search.getText().toString());queue();});LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(42));rp.setMargins(0,dp(8),0,0);card.addView(retry,rp);}if(!empty(k.tags)){TextView tags=tv("# "+k.tags.replace(",","   # "),11,muted);tags.setPadding(0,dp(6),0,0);card.addView(tags);}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));list.addView(card,p);}

    void showAsk(){EditText q=new EditText(this);q.setHint("Ask about anything saved in Cortex…");q.setMinLines(3);AlertDialog dlg=new AlertDialog.Builder(this).setTitle("Ask Cortex").setMessage("Retrieval mode • answers come only from your saved memory").setView(q).setNegativeButton("Cancel",null).setPositiveButton("Search",null).create();dlg.setOnShowListener(x->dlg.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{String s=q.getText().toString().trim();if(s.isEmpty())return;ArrayList<SemanticHit> hits=SemanticIndex.search(db,s,6);dlg.dismiss();showAskResults(s,hits);}));dlg.show();}
    void showAskResults(String question,ArrayList<SemanticHit> hits){ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);pad(box,16);sv.addView(box);section(box,"QUESTION",question);section(box,"MODE","Hybrid retrieval • "+SemanticIndex.providerLabel()+"\nNo generated facts are used in this build.");if(hits.isEmpty())section(box,"RESULT","No strong memory match found.");else{section(box,"BEST EVIDENCE","Cortex found "+hits.size()+" relevant memories. Tap any source to open it.");for(SemanticHit h:hits)addHitCard(box,h);}new AlertDialog.Builder(this).setTitle("Ask Cortex").setView(sv).setNegativeButton("Close",null).show();}
    void addHitCard(LinearLayout box,SemanticHit h){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setBackgroundResource(R.drawable.rounded_panel);pad(c,12);c.setClickable(true);c.setOnClickListener(v->detail(h.item));TextView t=tv(h.item.title,15,text);t.setTypeface(null,1);c.addView(t);c.addView(tv("Relevance "+Math.round(h.score*100)+"%  •  "+h.item.category,11,muted));TextView sn=tv(h.snippet,13,text);sn.setPadding(0,dp(5),0,0);c.addView(sn);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,0);box.addView(c,p);}
    void showPacks(){ArrayList<ContextPack> packs=ContextEngine.build(db);if(packs.isEmpty()){Toast.makeText(this,"No Context Packs yet — add a few related memories",Toast.LENGTH_LONG).show();return;}String[] labels=new String[packs.size()];for(int i=0;i<packs.size();i++)labels[i]=packs.get(i).title+"   •   "+packs.get(i).items.size()+" items";new AlertDialog.Builder(this).setTitle("Context Packs").setItems(labels,(d,w)->showPackDetail(packs.get(w))).setNegativeButton("Close",null).show();}
    void showPackDetail(ContextPack p){ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);pad(box,16);sv.addView(box);section(box,"WHY CORTEX GROUPED THESE",p.reason+"\n"+p.items.size()+" related memories");for(KnowledgeItem k:p.items){LinearLayout card=new LinearLayout(this);card.setOrientation(LinearLayout.VERTICAL);card.setBackgroundResource(R.drawable.rounded_panel);pad(card,12);card.setClickable(true);card.setOnClickListener(v->detail(k));TextView t=tv(k.title,16,text);t.setTypeface(null,1);card.addView(t);card.addView(tv(k.category+"  •  "+fmt(k.createdAt),11,muted));String preview=!empty(k.summary)?k.summary:(!empty(k.rawText)?k.rawText:k.extractedText);if(preview==null)preview="";if(preview.length()>180)preview=preview.substring(0,180)+"…";TextView pv=tv(preview,13,text);pv.setPadding(0,dp(5),0,0);card.addView(pv);LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(-1,-2);q.setMargins(0,dp(8),0,0);box.addView(card,q);}new AlertDialog.Builder(this).setTitle(p.title).setView(sv).setNegativeButton("Close",null).show();}

    String statusText(String st,String err){if("analyzed".equals(st))return "● Analyzed + indexed";if("analyzing".equals(st))return "● Analyzing…";if("queued".equals(st))return "● Queued for analysis";if("failed_retryable".equals(st))return "● Transcription incomplete — retry available";if("analysis_failed".equals(st))return "● Analysis failed"+(empty(err)?"":" — "+err);return "● "+st;}int statusColor(String st){return ("analysis_failed".equals(st)||"failed_retryable".equals(st))?danger:("analyzed".equals(st)?muted:accent);}
    void detail(KnowledgeItem k){ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);pad(box,16);sv.addView(box);File attachment=!empty(k.attachmentPath)?new File(k.attachmentPath):null;if(attachment!=null&&attachment.exists()&&("SCREENSHOT".equals(k.type)||"IMAGE".equals(k.type))){Bitmap b=BitmapFactory.decodeFile(k.attachmentPath);if(b!=null){ImageView im=new ImageView(this);im.setImageBitmap(b);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.CENTER_INSIDE);box.addView(im,new LinearLayout.LayoutParams(-1,dp(260)));}}if("AUDIO".equals(k.type)&&attachment!=null&&attachment.exists()){Button play=new Button(this);play.setText("▶ PLAY AUDIO");play.setOnClickListener(v->playAudio(attachment));box.addView(play);Button feedback=new Button(this);feedback.setText("SEND TRANSCRIPTION FEEDBACK");feedback.setOnClickListener(v->FeedbackShare.send(this,k,attachment,k.analysisError));box.addView(feedback);String info=AudioStore.info(db,k.id);if(!empty(info))section(box,"AUDIO",info);ArrayList<String> ts=AudioStore.segments(db,k.id);if(!ts.isEmpty())section(box,"TIMED TRANSCRIPT",join(ts));}
        boolean retryable="failed_retryable".equals(k.status);if(retryable&&"AUDIO".equals(k.type)){section(box,"TRANSCRIPTION","Audio captured — transcription failed. The rejected partial transcript was not analyzed.");if(!empty(k.analysisError))section(box,"DIAGNOSTICS",k.analysisError);}else{section(box,"SUMMARY",empty(k.summary)?"Analysis pending":k.summary);if(!empty(k.extractedText))section(box,"EXTRACTED / TRANSCRIPT TEXT",k.extractedText);}ArrayList<String> vf=db.visionFields(k.id);if(!vf.isEmpty())section(box,"VISION",join(vf));if(!empty(k.rawText))section(box,"SOURCE TEXT",k.rawText);ArrayList<String> es=db.entities(k.id);if(!es.isEmpty())section(box,"ENTITIES",join(es));ArrayList<String> as=db.actions(k.id);if(!as.isEmpty())section(box,"OPEN ACTIONS",join(as));if("AI_PROMPT".equals(k.type)){ArrayList<String> ex=db.exampleDetails(k.id);if(!ex.isEmpty())section(box,"EXAMPLE BUNDLE",String.join("\n\n———\n\n",ex));}ArrayList<SemanticHit> rel=SemanticIndex.related(db,k,5);if(!rel.isEmpty()){TextView h=tv("RELATED MEMORIES",11,accent);h.setTypeface(null,1);h.setPadding(0,dp(12),0,dp(4));box.addView(h);for(SemanticHit hit:rel)addHitCard(box,hit);}section(box,"SEMANTIC INDEX",SemanticIndex.providerLabel()+"\nChunk-level local index");section(box,"METADATA",k.category+"\n"+k.tags+"\nSource: "+k.source+"\nStatus: "+k.status+"\nCaptured: "+fmt(k.createdAt));AlertDialog.Builder builder=new AlertDialog.Builder(this).setTitle(k.title).setView(sv).setNegativeButton("Close",null);if("failed_retryable".equals(k.status)||"analysis_failed".equals(k.status))builder.setNeutralButton("Re-analyze",null);AlertDialog dlg=builder.create();dlg.setOnShowListener(x->{Button retry=dlg.getButton(AlertDialog.BUTTON_NEUTRAL);if(retry!=null)retry.setOnClickListener(v->{db.retry(k.id);dlg.dismiss();refresh(search.getText().toString());queue();});});dlg.show();}
    void playAudio(File f){try{MediaPlayer p=new MediaPlayer();p.setDataSource(f.getAbsolutePath());p.setOnCompletionListener(x->{x.release();});p.prepare();p.start();}catch(Exception e){Toast.makeText(this,"Playback failed: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
    void section(LinearLayout box,String heading,String body){TextView h=tv(heading,11,accent);h.setTypeface(null,1);h.setPadding(0,dp(12),0,dp(4));box.addView(h);box.addView(tv(body,14,text));}String join(ArrayList<String> xs){StringBuilder s=new StringBuilder();for(String x:xs){if(s.length()>0)s.append("\n");s.append("• ").append(x);}return s.toString();}boolean empty(String s){return s==null||s.trim().isEmpty();}String fmt(long ms){return new SimpleDateFormat("dd MMM • HH:mm",Locale.getDefault()).format(new Date(ms));}
}
