package com.kareem.cortex;

import android.app.Notification;
import android.content.pm.ApplicationInfo;
import android.os.Build;
import android.os.Bundle;
import android.os.Parcelable;
import android.service.notification.NotificationListenerService;
import android.service.notification.StatusBarNotification;
import org.json.JSONArray;
import org.json.JSONObject;

/** Raw-first notification capture. Android identity/lifecycle are evidence; Cortex meaning is downstream. */
public class NotificationCaptureService extends NotificationListenerService {
    @Override public void onListenerConnected(){super.onListenerConnected();if(StartupSafetyGate.active())return;try{StatusBarNotification[] xs=getActiveNotifications();if(xs!=null)for(StatusBarNotification x:xs)ingest(x,"active_snapshot");}catch(Throwable ignored){}}
    @Override public void onNotificationPosted(StatusBarNotification sbn){if(StartupSafetyGate.active())return;ingest(sbn,"posted");}
    @Override public void onNotificationRemoved(StatusBarNotification sbn){if(StartupSafetyGate.active())return;removed(sbn,0);}
    @Override public void onNotificationRemoved(StatusBarNotification sbn,RankingMap rankingMap,int reason){if(StartupSafetyGate.active())return;removed(sbn,reason);}

    private void removed(StatusBarNotification sbn,int reason){
        if(StartupSafetyGate.active()||sbn==null)return;VaultDb db=null;
        try{
            String pkg=sbn.getPackageName()==null?"":sbn.getPackageName(),app=label(pkg),why=removalReason(reason);long now=System.currentTimeMillis();
            JSONObject m=new JSONObject().put("capture_kind","android_notification").put("capture_mode","removed").put("package",pkg).put("app_label",app).put("notification_id",sbn.getId()).put("notification_key",sbn.getKey()==null?"":sbn.getKey()).put("notification_tag",sbn.getTag()==null?"":sbn.getTag()).put("tag",sbn.getTag()==null?"":sbn.getTag()).put("removal_reason_code",reason).put("removal_reason",why).put("removed_at",now);
            if(sbn.getGroupKey()!=null)m.put("group_key",sbn.getGroupKey());
            db=new VaultDb(this);PhoneContextStore.ensure(db);NotificationEventEngine.Result p=NotificationEventEngine.ingest(db,pkg,app,"removed","","",now,m);UniversalEventEngine.Result u=UniversalEventEngine.processNotification(this,db,p,pkg,app,"removed","","",now,m);
            if("waiting".equals(u.state))UniversalSemanticScheduler.kick(this);StatefulMeaningScheduler.kick(this);
            m.put("pipeline_transition",p.transition).put("technical_type",p.technicalType).put("platform_hint",p.platformHint).put("raw_observation_id",u.rawId).put("notification_stream_id",u.streamId).put("semantic_event_id",u.semanticEventId);
            PhoneContextStore.record(db,"notification_context","notification_listener",pkg,app,"","removed","",now,m);
        }catch(Throwable error){logFailure(error,sbn);}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}
    }

    private void ingest(StatusBarNotification sbn,String captureMode){VaultDb db=null;try{
        if(StartupSafetyGate.active())return;if(sbn==null||sbn.getNotification()==null)return;if(getPackageName().equals(sbn.getPackageName()))return;if(!PrivacyPolicy.canCollect(this,"notifications"))return;
        Notification n=sbn.getNotification();Bundle e=n.extras==null?new Bundle():n.extras;String pkg=sbn.getPackageName()==null?"":sbn.getPackageName(),app=label(pkg);String title=str(e.getCharSequence(Notification.EXTRA_TITLE)),text=str(e.getCharSequence(Notification.EXTRA_TEXT)),big=str(e.getCharSequence(Notification.EXTRA_BIG_TEXT));if(!big.isEmpty())text=big;
        JSONArray lines=textLines(e),messages=messages(e);if(text.isEmpty()&&lines.length()>0)text=joinLines(lines);if(text.isEmpty()&&messages.length()>0)text=joinMessages(messages);String visible=(title+(title.isEmpty()||text.isEmpty()?"":"\n")+text).trim();boolean ongoing=(n.flags&Notification.FLAG_ONGOING_EVENT)!=0;

        String hint=inferKind(n,e);JSONObject meta=new JSONObject();meta.put("capture_kind","android_notification");meta.put("capture_mode",captureMode);meta.put("package",pkg);meta.put("app_label",app);meta.put("posted_at",sbn.getPostTime());meta.put("notification_id",sbn.getId());meta.put("notification_tag",sbn.getTag()==null?"":sbn.getTag());meta.put("tag",sbn.getTag()==null?"":sbn.getTag());meta.put("ongoing",ongoing);meta.put("clearable",sbn.isClearable());meta.put("has_visible_text",!visible.isEmpty());meta.put("flags",n.flags);meta.put("priority",n.priority);meta.put("visibility",n.visibility);meta.put("number",n.number);meta.put("when",n.when);meta.put("color",n.color);meta.put("platform_hint",hint);meta.put("notification_kind",hint);
        if(sbn.getKey()!=null)meta.put("notification_key",sbn.getKey());if(sbn.getGroupKey()!=null)meta.put("group_key",sbn.getGroupKey());if(n.category!=null)meta.put("category",n.category);if(Build.VERSION.SDK_INT>=20){meta.put("local_only",(n.flags&Notification.FLAG_LOCAL_ONLY)!=0);meta.put("group_summary",(n.flags&Notification.FLAG_GROUP_SUMMARY)!=0);if(n.getGroup()!=null)meta.put("group",n.getGroup());if(n.getSortKey()!=null)meta.put("sort_key",n.getSortKey());}
        if(Build.VERSION.SDK_INT>=26&&n.getChannelId()!=null)meta.put("channel_id",n.getChannelId());if(Build.VERSION.SDK_INT>=26)meta.put("timeout_after",n.getTimeoutAfter());if(Build.VERSION.SDK_INT>=26&&n.getShortcutId()!=null)meta.put("shortcut_id",n.getShortcutId());
        meta.put("title",title);meta.put("text",str(e.getCharSequence(Notification.EXTRA_TEXT)));meta.put("big_text",big);meta.put("text_lines",lines);meta.put("messages",messages);put(meta,"sub_text",e.getCharSequence(Notification.EXTRA_SUB_TEXT));put(meta,"summary_text",e.getCharSequence(Notification.EXTRA_SUMMARY_TEXT));put(meta,"info_text",e.getCharSequence(Notification.EXTRA_INFO_TEXT));put(meta,"title_big",e.getCharSequence(Notification.EXTRA_TITLE_BIG));put(meta,"conversation_title",Build.VERSION.SDK_INT>=24?e.getCharSequence(Notification.EXTRA_CONVERSATION_TITLE):null);put(meta,"template",e.getString(Notification.EXTRA_TEMPLATE));
        meta.put("progress",e.getInt(Notification.EXTRA_PROGRESS,0));meta.put("progress_max",e.getInt(Notification.EXTRA_PROGRESS_MAX,0));meta.put("progress_indeterminate",e.getBoolean(Notification.EXTRA_PROGRESS_INDETERMINATE,false));meta.put("action_count",n.actions==null?0:n.actions.length);JSONArray actions=new JSONArray();if(n.actions!=null)for(Notification.Action a:n.actions){if(a==null)continue;JSONObject x=new JSONObject();x.put("title",str(a.title));if(Build.VERSION.SDK_INT>=20)x.put("remote_input_count",a.getRemoteInputs()==null?0:a.getRemoteInputs().length);actions.put(x);}meta.put("actions",actions);meta.put("has_content_intent",n.contentIntent!=null);meta.put("has_delete_intent",n.deleteIntent!=null);meta.put("has_fullscreen_intent",n.fullScreenIntent!=null);meta.put("has_custom_content",n.contentView!=null||n.bigContentView!=null||n.headsUpContentView!=null);

        db=new VaultDb(this);PhoneContextStore.ensure(db);
        NotificationEventEngine.Result platform=NotificationEventEngine.ingest(db,pkg,app,"posted",title,text,sbn.getPostTime(),meta);
        UniversalEventEngine.Result semantic=UniversalEventEngine.processNotification(this,db,platform,pkg,app,"posted",title,text,sbn.getPostTime(),meta);
        if("waiting".equals(semantic.state))UniversalSemanticScheduler.kick(this);StatefulMeaningScheduler.kick(this);
        meta.put("pipeline_transition",platform.transition).put("technical_type",platform.technicalType).put("platform_hint",platform.platformHint).put("raw_observation_id",semantic.rawId).put("notification_stream_id",semantic.streamId).put("semantic_event_id",semantic.semanticEventId).put("semantic_type",semantic.semanticType).put("semantic_state",semantic.state).put("semantic_route",semantic.route);

        if(platform.semanticEventId>0)PhoneContextStore.record(db,"notification_context","notification_listener",pkg,app,"","notification_"+platform.transition.toLowerCase(),visible,sbn.getPostTime(),meta);
    }catch(Throwable error){logFailure(error,sbn);}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}}

    private static String removalReason(int reason){switch(reason){case REASON_CLICK:return"click";case REASON_CANCEL:return"user_cancel";case REASON_CANCEL_ALL:return"user_cancel_all";case REASON_ERROR:return"error";case REASON_PACKAGE_CHANGED:return"package_changed";case REASON_USER_STOPPED:return"user_stopped";case REASON_PACKAGE_BANNED:return"package_banned";case REASON_APP_CANCEL:return"app_cancel";case REASON_APP_CANCEL_ALL:return"app_cancel_all";case REASON_LISTENER_CANCEL:return"listener_cancel";case REASON_LISTENER_CANCEL_ALL:return"listener_cancel_all";case REASON_GROUP_SUMMARY_CANCELED:return"group_summary_canceled";case REASON_GROUP_OPTIMIZATION:return"group_optimization";case REASON_PACKAGE_SUSPENDED:return"package_suspended";case REASON_PROFILE_TURNED_OFF:return"profile_turned_off";case REASON_UNAUTOBUNDLED:return"unautobundled";case REASON_CHANNEL_BANNED:return"channel_banned";case REASON_SNOOZED:return"snoozed";case REASON_TIMEOUT:return"timeout";case REASON_CHANNEL_REMOVED:return"channel_removed";case REASON_CLEAR_DATA:return"clear_data";case REASON_ASSISTANT_CANCEL:return"assistant_cancel";default:return reason==0?"unknown":"reason_"+reason;}}
    private void logFailure(Throwable error,StatusBarNotification sbn){if(StartupSafetyGate.active())return;android.util.Log.e("CortexNotification","Notification ingestion failed",error);VaultDb d=null;try{d=new VaultDb(this);JSONObject meta=new JSONObject();meta.put("package",sbn==null?"":String.valueOf(sbn.getPackageName()));DiagnosticsLog.error(d,"NotificationCaptureService","notification_ingest",error,"NOTIFICATION_INGEST",0,0,0,0,0,meta);}catch(Throwable ignored){}finally{if(d!=null)try{d.close();}catch(Throwable ignored){}}}
    private static JSONArray textLines(Bundle e){JSONArray out=new JSONArray();try{CharSequence[] xs=e.getCharSequenceArray(Notification.EXTRA_TEXT_LINES);if(xs!=null)for(CharSequence x:xs)if(x!=null&&!str(x).isEmpty())out.put(str(x));}catch(Throwable ignored){}return out;}
    private static JSONArray messages(Bundle e){JSONArray out=new JSONArray();try{Parcelable[] xs=e.getParcelableArray(Notification.EXTRA_MESSAGES);if(xs!=null)for(Parcelable p:xs){if(!(p instanceof Bundle))continue;Bundle b=(Bundle)p;JSONObject m=new JSONObject();String text=str(b.getCharSequence("text")),sender=str(b.getCharSequence("sender"));m.put("text",text);m.put("sender",sender);m.put("time",b.getLong("time",0));if(!text.isEmpty()||!sender.isEmpty())out.put(m);}}catch(Throwable ignored){}return out;}
    private static String joinLines(JSONArray a){StringBuilder b=new StringBuilder();for(int i=0;i<a.length();i++){String x=a.optString(i,"");if(x.isEmpty())continue;if(b.length()>0)b.append("\n");b.append(x);if(b.length()>1600)break;}return b.toString();}
    private static String joinMessages(JSONArray a){StringBuilder b=new StringBuilder();for(int i=0;i<a.length();i++){JSONObject m=a.optJSONObject(i);if(m==null)continue;String sender=m.optString("sender",""),text=m.optString("text","");if(text.isEmpty())continue;if(b.length()>0)b.append("\n");if(!sender.isEmpty())b.append(sender).append(": ");b.append(text);if(b.length()>1600)break;}return b.toString();}
    private static void put(JSONObject o,String key,Object value){try{String x=value==null?"":String.valueOf(value).trim();if(!x.isEmpty())o.put(key,x);}catch(Throwable ignored){}}
    private String label(String pkg){if(pkg==null||pkg.isEmpty())return"Notification";try{ApplicationInfo ai=getPackageManager().getApplicationInfo(pkg,0);CharSequence x=getPackageManager().getApplicationLabel(ai);return x==null?pkg:x.toString();}catch(Throwable e){return pkg;}}
    private static String inferKind(Notification n,Bundle e){String c=n==null||n.category==null?"":n.category;if(Notification.CATEGORY_MESSAGE.equals(c)||e.getParcelableArray(Notification.EXTRA_MESSAGES)!=null)return"message";if(Notification.CATEGORY_EMAIL.equals(c))return"email";if(Notification.CATEGORY_CALL.equals(c))return"call";if(Notification.CATEGORY_PROMO.equals(c))return"promotion";if(Notification.CATEGORY_SOCIAL.equals(c))return"social";if(Notification.CATEGORY_RECOMMENDATION.equals(c))return"recommendation";if(Notification.CATEGORY_PROGRESS.equals(c))return"progress";if(Notification.CATEGORY_SERVICE.equals(c))return"service";if(Notification.CATEGORY_TRANSPORT.equals(c))return"media";if(Notification.CATEGORY_ALARM.equals(c))return"alarm";if(Notification.CATEGORY_REMINDER.equals(c))return"reminder";if(Notification.CATEGORY_EVENT.equals(c))return"event";return"notification";}
    private static String str(CharSequence s){return s==null?"":s.toString().trim();}
}
