package com.kareem.cortex;

import android.content.ContentValues;
import android.database.Cursor;
import org.json.JSONObject;
import java.text.SimpleDateFormat;
import java.util.*;

/** Turns isolated notification text into a grounded event summary using only nearby captured evidence. */
public final class NotificationEnrichmentEngine {
    private NotificationEnrichmentEngine(){}

    public static void enrich(VaultDb db,long signalId,long itemId,long threadId,MasterRelevanceFilter.Signal signal){if(db==null||signal==null||signalId<=0)return;try{String state=eventState(signal.body+" "+signal.title);if(state.isEmpty())return;ArrayList<String> related=related(db,signal.source,threadId,signal.occurredAt,signalId);String source=friendlySource(signal.source),when=new SimpleDateFormat("dd MMM yyyy · HH:mm",Locale.getDefault()).format(new Date(signal.occurredAt>0?signal.occurredAt:System.currentTimeMillis()));String subject=subjectHint(related);StringBuilder summary=new StringBuilder();if(!subject.isEmpty())summary.append(source).append(" · ").append(subject).append(" · ");else summary.append(source).append(" · ");summary.append(humanState(state)).append(" at ").append(when).append('.');if(subject.isEmpty()&&!related.isEmpty())summary.append(" Related captured context: ").append(clip(related.get(0),240));String s=summary.toString();
            if(itemId>0){ContentValues v=new ContentValues();v.put("summary",s);v.put("updated_at",System.currentTimeMillis());db.getWritableDatabase().update("knowledge_items",v,"id=?",new String[]{String.valueOf(itemId)});}
            if(threadId>0){ContentValues v=new ContentValues();v.put("summary",s);v.put("updated_at",System.currentTimeMillis());db.getWritableDatabase().update("signal_threads",v,"id=?",new String[]{String.valueOf(threadId)});}
            JSONObject m=new JSONObject().put("state",state).put("source",signal.source).put("related_count",related.size()).put("subject_grounded",!subject.isEmpty()).put("summary",s);DiagnosticsLog.info(db,"NotificationEnrichment","event_summary","ok",itemId,threadId,signalId,0,0,0,m);
        }catch(Throwable ignored){}
    }

    private static ArrayList<String> related(VaultDb db,String source,long threadId,long at,long exclude){ArrayList<String> out=new ArrayList<>();long end=at>0?at:System.currentTimeMillis(),start=end-12L*60L*60L*1000L;Cursor c;if(threadId>0)c=db.getReadableDatabase().rawQuery("SELECT title,body FROM raw_signals WHERE id<>? AND (thread_id=? OR source=?) AND occurred_at BETWEEN ? AND ? ORDER BY occurred_at DESC,id DESC LIMIT 12",new String[]{String.valueOf(exclude),String.valueOf(threadId),safe(source),String.valueOf(start),String.valueOf(end)});else c=db.getReadableDatabase().rawQuery("SELECT title,body FROM raw_signals WHERE id<>? AND source=? AND occurred_at BETWEEN ? AND ? ORDER BY occurred_at DESC,id DESC LIMIT 12",new String[]{String.valueOf(exclude),safe(source),String.valueOf(start),String.valueOf(end)});while(c.moveToNext()){String t=safe(c.getString(0)),b=safe(c.getString(1)),x=!b.trim().isEmpty()?b:t;x=x.replaceAll("\\s+"," ").trim();if(!x.isEmpty()&&!isBareStatus(x))out.add(x);}c.close();return out;}
    private static String eventState(String text){String x=safe(text).toLowerCase(Locale.ROOT);if(has(x,"delivered","تم التوصيل","تم توصيل","وصل طلبك","تم التسليم"))return"delivered";if(has(x,"out for delivery","on the way","في الطريق","الطلب في الطريق"))return"on_the_way";if(has(x,"shipped","تم الشحن","شحنت"))return"shipped";if(has(x,"ready for pickup","ready to collect","جاهز للاستلام"))return"ready";if(has(x,"order confirmed","order accepted","تم تأكيد الطلب","تم قبول الطلب"))return"confirmed";if(has(x,"cancelled","canceled","تم الإلغاء","ملغي"))return"cancelled";if(has(x,"payment received","payment successful","تم الدفع","تمت عملية الدفع"))return"paid";if(has(x,"appointment confirmed","موعدك مؤكد","تم تأكيد الموعد"))return"appointment_confirmed";return"";}
    private static String humanState(String s){if("delivered".equals(s))return"order/delivery confirmed delivered";if("on_the_way".equals(s))return"order/delivery is on the way";if("shipped".equals(s))return"shipment confirmed shipped";if("ready".equals(s))return"order is ready";if("confirmed".equals(s))return"order confirmed";if("cancelled".equals(s))return"order/event cancelled";if("paid".equals(s))return"payment confirmed";if("appointment_confirmed".equals(s))return"appointment confirmed";return s.replace('_',' ');}
    private static String subjectHint(ArrayList<String> xs){for(String x:xs){String y=x.replaceAll("\\s+"," ").trim();String low=y.toLowerCase(Locale.ROOT);for(String marker:new String[]{" from "," by "," لدى "," من مطعم "," من "}){int p=low.indexOf(marker);if(p>=0){String tail=y.substring(p+marker.length()).trim();tail=tail.split("[|•·\\n,;:]")[0].trim();if(tail.length()>=3&&tail.length()<=80&&!looksStatus(tail))return tail;}}}return"";}
    private static boolean isBareStatus(String s){String x=s.toLowerCase(Locale.ROOT);return looksStatus(x)&&x.length()<90;}private static boolean looksStatus(String x){return eventState(x).length()>0;}private static boolean has(String x,String...ys){for(String y:ys)if(x.contains(y))return true;return false;}private static String friendlySource(String s){String x=safe(s);if(x.equals("com.talabat"))return"Talabat";int p=x.lastIndexOf('.');if(p>=0&&p<x.length()-1)x=x.substring(p+1);return x.isEmpty()?"Notification":Character.toUpperCase(x.charAt(0))+x.substring(1);}private static String clip(String s,int n){String x=safe(s);return x.length()<=n?x:x.substring(0,n)+"…";}private static String safe(String s){return s==null?"":s;}
}
