package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import com.google.mlkit.vision.common.InputImage;
import com.google.mlkit.vision.text.TextRecognition;
import com.google.mlkit.vision.text.TextRecognizer;
import com.google.mlkit.vision.text.latin.TextRecognizerOptions;
import java.io.File;
import java.util.*;

public class OcrTestActivity extends Activity {
    VaultDb db;LinearLayout box;TextView state,stats;int bg=Color.rgb(11,12,14),surface=Color.rgb(24,26,30),text=Color.rgb(245,244,240),muted=Color.rgb(156,159,168),accent=Color.rgb(232,177,72),ok=Color.rgb(120,205,150),danger=Color.rgb(246,124,118),border=Color.rgb(47,50,57);
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setReadable(v,s);return v;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);ensureTable();build();refreshStats();}
    void ensureTable(){db.getWritableDatabase().execSQL("CREATE TABLE IF NOT EXISTS ocr_tests(id INTEGER PRIMARY KEY AUTOINCREMENT,item_id INTEGER,created_at INTEGER,latin_text TEXT,arabic_text TEXT,merged_text TEXT,latin_ms INTEGER,arabic_ms INTEGER,total_ms INTEGER,language_mode TEXT,quality TEXT,latin_status TEXT,arabic_status TEXT)");}
    void build(){ScrollView sv=new ScrollView(this);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(18),dp(18),dp(30));box.setBackgroundColor(bg);sv.addView(box);TextView h=tv("OCR TEST LAB",26,text);h.setTypeface(null,1);box.addView(h);box.addView(tv("ML Kit Latin and bundled Tesseract Arabic are compared on the same screenshot. The same central OCR evidence gate used by production is shown here; rejected raw Arabic remains diagnostic-only and never enters Cortex memory/search.",13,muted));stats=card("TEST HISTORY","");state=card("CURRENT TEST","Choose a screenshot to begin.");Button choose=button("CHOOSE RECENT SCREENSHOT");choose.setOnClickListener(v->chooseRecent());box.addView(choose,lp());Button latest=button("TEST LATEST SCREENSHOT");latest.setOnClickListener(v->testLatest());box.addView(latest,lp());setContentView(sv);}
    TextView card(String title,String value){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackgroundColor(surface);TextView h=tv(title,11,accent);h.setTypeface(null,1);c.addView(h);TextView t=tv(value,13,text);t.setPadding(0,dp(6),0,0);c.addView(t);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(12),0,dp(10));box.addView(c,p);return t;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(text);b.setBackgroundColor(surface);return b;}LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,0,0,dp(9));return p;}
    void refreshStats(){Cursor c=db.getReadableDatabase().rawQuery("SELECT COUNT(*),SUM(CASE WHEN quality='empty' THEN 1 ELSE 0 END),SUM(CASE WHEN quality IN ('gibberish-suspected','arabic-rejected') THEN 1 ELSE 0 END),SUM(CASE WHEN language_mode='mixed' THEN 1 ELSE 0 END) FROM ocr_tests",null);if(c.moveToFirst())stats.setText("tests "+c.getInt(0)+" • empty "+c.getInt(1)+" • rejected/suspect "+c.getInt(2)+" • mixed "+c.getInt(3));c.close();}
    void testLatest(){ArrayList<KnowledgeItem> xs=recent(1);if(xs.isEmpty()){Toast.makeText(this,"No screenshot with an archived image found",Toast.LENGTH_LONG).show();return;}runTest(xs.get(0));}
    void chooseRecent(){ArrayList<KnowledgeItem> xs=recent(40);if(xs.isEmpty()){Toast.makeText(this,"No screenshots found",Toast.LENGTH_LONG).show();return;}String[] labels=new String[xs.size()];for(int i=0;i<xs.size();i++){KnowledgeItem k=xs.get(i);labels[i]="#"+k.id+" • "+clip(k.title,70);}new AlertDialog.Builder(this).setTitle("Choose screenshot").setItems(labels,(d,w)->runTest(xs.get(w))).setNegativeButton("Cancel",null).show();}
    ArrayList<KnowledgeItem> recent(int limit){ArrayList<KnowledgeItem> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT id FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND attachment_path IS NOT NULL AND attachment_path<>'' ORDER BY created_at DESC LIMIT "+limit,null);while(c.moveToNext()){KnowledgeItem k=db.getById(c.getLong(0));if(k!=null&&new File(k.attachmentPath).exists())out.add(k);}c.close();return out;}
    void runTest(KnowledgeItem item){File f=new File(item.attachmentPath);state.setText("Testing #"+item.id+" • "+clip(item.title,80)+"\nRunning ML Kit Latin…");long started=System.currentTimeMillis(),latinStart=started;try{InputImage image=InputImage.fromFilePath(this,Uri.fromFile(f));TextRecognizer rec=TextRecognition.getClient(TextRecognizerOptions.DEFAULT_OPTIONS);rec.process(image).addOnSuccessListener(r->{String latin=r.getText()==null?"":r.getText().trim();long latinMs=System.currentTimeMillis()-latinStart;rec.close();state.setText("ML Kit done in "+latinMs+" ms\nRunning Tesseract Arabic…");runArabic(item,f,started,latin,latinMs,"ready");}).addOnFailureListener(e->{rec.close();runArabic(item,f,started,"",System.currentTimeMillis()-latinStart,"failed: "+e.getClass().getSimpleName());});}catch(Exception e){state.setText("Test failed: "+e.getClass().getSimpleName()+": "+e.getMessage());}}
    void runArabic(KnowledgeItem item,File f,long started,String latin,long latinMs,String latinStatus){long a=System.currentTimeMillis();ArabicOcr.recognizeDetailed(this,f,latin,result->runOnUiThread(()->{long arabicMs=System.currentTimeMillis()-a,total=System.currentTimeMillis()-started;AnalysisResult merged=VisionInterpreter.interpret(item,latin,result.text,result.status);String mergedText=merged.extractedText==null?"":merged.extractedText.trim();String lang=languageMode(mergedText),quality=!result.accepted&&!result.rawText.isEmpty()?"arabic-rejected":OcrGarbageGate.qualityLabel(mergedText);save(item.id,latin,result.rawText,mergedText,latinMs,arabicMs,total,lang,quality,latinStatus,result.status);showResult(item,latin,result,mergedText,latinMs,arabicMs,total,lang,quality,latinStatus);refreshStats();}));}
    void save(long id,String latin,String arabic,String merged,long l,long a,long total,String lang,String quality,String ls,String as){android.content.ContentValues v=new android.content.ContentValues();v.put("item_id",id);v.put("created_at",System.currentTimeMillis());v.put("latin_text",latin);v.put("arabic_text",arabic);v.put("merged_text",merged);v.put("latin_ms",l);v.put("arabic_ms",a);v.put("total_ms",total);v.put("language_mode",lang);v.put("quality",quality);v.put("latin_status",ls);v.put("arabic_status",as);db.getWritableDatabase().insert("ocr_tests",null,v);}
    void showResult(KnowledgeItem item,String latin,ArabicOcr.Result ar,String merged,long l,long a,long total,String lang,String quality,String ls){state.setText("#"+item.id+" • "+quality+" • "+lang+" • total "+total+" ms\nML Kit "+l+" ms • Tesseract "+a+" ms • Arabic confidence "+ar.meanConfidence+"%");ScrollView sv=new ScrollView(this);LinearLayout p=new LinearLayout(this);p.setOrientation(LinearLayout.VERTICAL);p.setPadding(dp(14),dp(8),dp(14),dp(18));sv.addView(p);addBlock(p,"ML KIT LATIN • "+ls,latin);addBlock(p,"TESSERACT ARABIC RAW • "+ar.status,ar.rawText);if(!ar.rawText.isEmpty()){String verdict=(ar.accepted?"ACCEPTED INTO CORTEX EVIDENCE":"REJECTED FROM CORTEX EVIDENCE");String metrics=ar.gate==null?"":("\n"+ar.gate.compactMetrics()+" • Arabic words "+Math.round(ar.gate.arabicWordShare*100)+"% • common hits "+ar.gate.commonWordHits);addBlock(p,"CENTRAL ARABIC GATE",verdict+"\n"+ar.gateReason+metrics);}OcrGarbageGate.Quality safe=OcrGarbageGate.assessText(merged);addBlock(p,"CORTEX SAFE MERGED • "+quality+" • "+lang,"quality "+String.format(Locale.US,"%.2f",safe.score)+" • symbols "+Math.round(safe.symbolNoise*100)+"% • digits "+Math.round(safe.digitShare*100)+"%\n\n"+merged);new AlertDialog.Builder(this).setTitle("OCR comparison #"+item.id).setView(sv).setPositiveButton("Close",null).show();}
    void addBlock(LinearLayout p,String h,String body){TextView t=tv(h,11,accent);t.setTypeface(null,1);t.setPadding(0,dp(12),0,dp(5));p.addView(t);TextView b=tv(body==null||body.isEmpty()?"[empty]":body,13,text);b.setTextIsSelectable(true);p.addView(b);}
    String languageMode(String s){boolean ar=false,la=false;for(int i=0;i<s.length();i++){char c=s.charAt(i);if((c>='\u0600'&&c<='\u06ff')||(c>='\u0750'&&c<='\u077f'))ar=true;else if((c>='A'&&c<='Z')||(c>='a'&&c<='z'))la=true;}return ar&&la?"mixed":ar?"arabic":la?"latin":"unknown";}
    String quality(String s){return OcrGarbageGate.qualityLabel(s);}
    String clip(String s,int n){if(s==null)return"";return s.length()<=n?s:s.substring(0,n)+"…";}
}
