package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;

/** PRIME contextual browser over the unified entity/project graph. */
public class PeopleProjectsActivity extends Activity {
    VaultDb db;LinearLayout feed,tabs;String mode="people";volatile int generation=0;final ExecutorService loader=Executors.newSingleThreadExecutor();
    int dp(int x){return CortexUi.dp(this,x);}
    static final class Row {long id;String kind,name;int mentions;boolean candidate;Row(long id,String kind,String name,int mentions,boolean candidate){this.id=id;this.kind=kind;this.name=name;this.mentions=mentions;this.candidate=candidate;}}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);CognitiveStore.ensure(db);build();refreshAsync();}
    @Override protected void onResume(){super.onResume();if(db!=null&&!loader.isShutdown())refreshAsync();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),0);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"People / Projects",29,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);TextView sub=CortexUi.text(this,"Context connected across messages, files, decisions and memory.",11,CortexUi.MUTED);sub.setPadding(0,dp(3),0,0);titles.addView(sub);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView archive=CortexUi.chip(this,"Archive",CortexUi.MUTED,false);archive.setOnClickListener(v->startActivity(new Intent(this,VaultActivity.class)));head.addView(archive,new LinearLayout.LayoutParams(-2,dp(36)));body.addView(head);
        tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);tabs.setPadding(0,dp(16),0,dp(8));addTab("People","people");addTab("Projects","projects");body.addView(tabs,new LinearLayout.LayoutParams(-1,dp(62)));
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,dp(4),0,dp(24));sv.addView(feed);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"people",null);setContentView(root);styleTabs();}
    void addTab(String label,String key){TextView t=CortexUi.chip(this,label,CortexUi.MUTED,false);t.setTag(key);t.setOnClickListener(v->{mode=(String)v.getTag();styleTabs();refreshAsync();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(40),1);if(tabs.getChildCount()>0)p.setMargins(dp(8),0,0,0);tabs.addView(t,p);}void styleTabs(){for(int i=0;i<tabs.getChildCount();i++){TextView t=(TextView)tabs.getChildAt(i);boolean on=mode.equals(t.getTag());t.setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);t.setBackground(CortexUi.round(this,on?CortexUi.SURFACE_2:CortexUi.SURFACE,on?CortexUi.ACCENT:CortexUi.BORDER_SOFT,999));if(on)CortexUi.medium(t);}}

    void refreshAsync(){if(loader.isShutdown()||db==null)return;final int g=++generation;final String wanted=mode;loader.execute(()->{try{ArrayList<Row> rows="people".equals(wanted)?people():projects();runOnUiThread(()->{if(g==generation&&!isFinishing()&&!isDestroyed())render(rows,wanted);});}catch(Throwable e){runOnUiThread(()->{if(g==generation&&!isFinishing()&&!isDestroyed()){feed.removeAllViews();feed.addView(CortexUi.text(this,"Could not load context.",12,CortexUi.MUTED));}});}});}
    ArrayList<Row> people(){ArrayList<Row> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT n.id,n.kind,n.canonical_name,COUNT(l.id) FROM entity_nodes n LEFT JOIN source_links l ON l.to_type='entity' AND l.to_id=n.id WHERE n.status='active' AND (upper(n.kind) LIKE '%PERSON%' OR upper(n.kind) LIKE '%CONTACT%' OR upper(n.kind)='PEOPLE') GROUP BY n.id ORDER BY COUNT(l.id) DESC,n.updated_at DESC LIMIT 120",null);while(c.moveToNext())out.add(new Row(c.getLong(0),nz(c.getString(1)),nz(c.getString(2)),c.getInt(3),false));c.close();return dedupe(out);}
    ArrayList<Row> projects(){ArrayList<Row> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT n.id,n.kind,n.canonical_name,COUNT(l.id) FROM entity_nodes n LEFT JOIN source_links l ON l.to_type='entity' AND l.to_id=n.id WHERE n.status='active' AND upper(n.kind) LIKE '%PROJECT%' GROUP BY n.id ORDER BY COUNT(l.id) DESC,n.updated_at DESC LIMIT 100",null);while(c.moveToNext())out.add(new Row(c.getLong(0),nz(c.getString(1)),nz(c.getString(2)),c.getInt(3),false));c.close();Cursor d=db.getReadableDatabase().rawQuery("SELECT id,title FROM derived_items WHERE kind='PROJECT_CANDIDATE' AND state IN ('pending','open') ORDER BY importance DESC,updated_at DESC LIMIT 60",null);while(d.moveToNext())out.add(new Row(d.getLong(0),"PROJECT_CANDIDATE",nz(d.getString(1)),0,true));d.close();return dedupe(out);}
    ArrayList<Row> dedupe(ArrayList<Row> xs){LinkedHashMap<String,Row> map=new LinkedHashMap<>();for(Row r:xs){String key=LocalSemanticEmbedder.norm(r.name);if(key.isEmpty())continue;Row old=map.get(key);if(old==null||(!r.candidate&&old.candidate)||r.mentions>old.mentions)map.put(key,r);}return new ArrayList<>(map.values());}

    void render(ArrayList<Row> rows,String wanted){feed.removeAllViews();if(rows.isEmpty()){LinearLayout c=CortexUi.card(this,22);c.setGravity(Gravity.CENTER);c.setPadding(dp(20),dp(46),dp(20),dp(46));TextView h=CortexUi.plain(this,"people".equals(wanted)?"No connected people yet":"No projects yet",18,CortexUi.TEXT);CortexUi.medium(h);h.setGravity(Gravity.CENTER);c.addView(h);TextView b=CortexUi.text(this,"Cortex will build this view only from grounded or confirmed context.",12,CortexUi.MUTED);b.setGravity(Gravity.CENTER);b.setPadding(0,dp(7),0,0);c.addView(b);feed.addView(c);return;}for(Row r:rows)addRow(r);}
    void addRow(Row r){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(2),dp(14),dp(2),dp(14));CortexUi.pressable(this,c,CortexUi.round(this,Color.TRANSPARENT,Color.TRANSPARENT,12));TextView n=CortexUi.text(this,r.name,15,CortexUi.TEXT);CortexUi.medium(n);c.addView(n);String meta=r.candidate?"Project candidate · needs your confirmation":friendly(r.kind)+(r.mentions>0?"  •  "+r.mentions+" linked references":"");TextView m=CortexUi.plain(this,meta,10,r.candidate?CortexUi.ACCENT:CortexUi.MUTED);m.setPadding(0,dp(4),0,0);c.addView(m);c.setOnClickListener(v->detail(r));feed.addView(c);feed.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}

    void detail(Row r){
        Dialog d=new Dialog(this);LinearLayout c=CortexUi.card(this,24);c.setPadding(dp(18),dp(18),dp(18),dp(18));TextView h=CortexUi.text(this,r.name,22,CortexUi.TEXT);CortexUi.medium(h);c.addView(h);TextView meta=CortexUi.plain(this,r.candidate?"Project candidate":friendly(r.kind),11,CortexUi.MUTED);meta.setPadding(0,dp(5),0,dp(10));c.addView(meta);
        ArrayList<String> evidence=evidence(r);if(r.candidate){TextView body=CortexUi.text(this,"Cortex detected project-like context. It stays a candidate until you explicitly create it.",12,CortexUi.MUTED);c.addView(body);}else{TextView body=CortexUi.text(this,r.mentions+" linked context reference"+(r.mentions==1?"":"s")+" currently support this entity.",12,CortexUi.MUTED);c.addView(body);}
        if(!evidence.isEmpty()){TextView eh=CortexUi.section(this,"Grounding");eh.setPadding(0,dp(14),0,dp(5));c.addView(eh);for(String x:evidence){TextView e=CortexUi.text(this,"• "+x,11,CortexUi.MUTED);e.setPadding(0,dp(3),0,dp(2));c.addView(e);}}
        if(r.candidate){TextView create=CortexUi.action(this,"Create project",CortexUi.ACCENT,true);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(46));pp.setMargins(0,dp(16),0,0);c.addView(create,pp);create.setOnClickListener(v->{create.setEnabled(false);boolean ok=ProjectCandidateStore.confirm(db,r.id);Toast.makeText(this,ok?"Project created":"Could not create project",Toast.LENGTH_SHORT).show();if(ok){d.dismiss();refreshAsync();}});}
        TextView archive=CortexUi.action(this,"Open archive",CortexUi.MUTED,false);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(44));ap.setMargins(0,dp(8),0,0);c.addView(archive,ap);archive.setOnClickListener(v->{d.dismiss();startActivity(new Intent(this,VaultActivity.class));});TextView close=CortexUi.action(this,"Close",CortexUi.MUTED,false);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(44));cp.setMargins(0,dp(8),0,0);c.addView(close,cp);close.setOnClickListener(v->d.dismiss());d.setContentView(c);Window w=d.getWindow();if(w!=null)w.setBackgroundDrawableResource(android.R.color.transparent);d.show();if(d.getWindow()!=null)d.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.92f),-2);
    }

    ArrayList<String> evidence(Row r){ArrayList<String> out=new ArrayList<>();if(r.candidate){Cursor c=db.getReadableDatabase().query("derived_items",new String[]{"body","source_key"},"id=?",new String[]{String.valueOf(r.id)},null,null,null,"1");if(c.moveToFirst()){String body=nz(c.getString(0)),source=nz(c.getString(1));if(!body.isEmpty())out.add(clip(body.replace("\n---\n"," · "),220));if(!source.isEmpty())out.add("Source: "+sourceLabel(source));}c.close();return out;}
        Cursor c=db.getReadableDatabase().rawQuery("SELECT k.title FROM source_links l JOIN knowledge_items k ON l.from_type='memory' AND l.from_id=k.id WHERE l.to_type='entity' AND l.to_id=? ORDER BY l.created_at DESC LIMIT 5",new String[]{String.valueOf(r.id)});while(c.moveToNext()){String x=nz(c.getString(0));if(!x.isEmpty())out.add(clip(x,120));}c.close();return out;}
    String sourceLabel(String s){String x=nz(s);int p=x.lastIndexOf('.');if(p>=0&&p<x.length()-1)x=x.substring(p+1);return x.replace('_',' ');}
    String clip(String x,int n){return x.length()<=n?x:x.substring(0,n)+"…";}
    String friendly(String kind){String k=nz(kind).toLowerCase(Locale.ROOT);if(k.contains("person")||k.contains("contact"))return"Person";if(k.contains("project"))return"Project";return kind;}String nz(String s){return s==null?"":s.trim();}
    @Override protected void onDestroy(){generation++;loader.shutdownNow();if(db!=null){try{db.close();}catch(Throwable ignored){}db=null;}super.onDestroy();}
}
