package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.os.Bundle;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;

/** PRIME contextual browser over identified People and explicitly confirmed Projects. */
public class PeopleProjectsActivity extends Activity {
    VaultDb db;LinearLayout feed,tabs;EditText search;String mode="people";volatile int generation=0;final ExecutorService loader=Executors.newSingleThreadExecutor();boolean maintained=false;ArrayList<Row> lastRows=new ArrayList<>();String lastMode="people";
    int dp(int x){return CortexUi.dp(this,x);}
    static final class Row {long id;String kind,name,key;int mentions;boolean candidate,identified;Row(long id,String kind,String name,String key,int mentions,boolean candidate,boolean identified){this.id=id;this.kind=kind;this.name=name;this.key=key;this.mentions=mentions;this.candidate=candidate;this.identified=identified;}}
    static final class ContextRef {long itemId;String title,preview,relation;ContextRef(long id,String t,String p,String r){itemId=id;title=t;preview=p;relation=r;}}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);CognitiveStore.ensure(db);build();refreshAsync();}
    @Override protected void onResume(){super.onResume();if(db!=null&&!loader.isShutdown())refreshAsync();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),0);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"People / Projects",29,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);TextView sub=CortexUi.text(this,"Useful relationship and project context — grounded, not guessed.",11,CortexUi.MUTED);sub.setPadding(0,dp(3),0,0);titles.addView(sub);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView archive=CortexUi.chip(this,"Archive",CortexUi.MUTED,false);archive.setOnClickListener(v->startActivity(new Intent(this,VaultActivity.class)));head.addView(archive,new LinearLayout.LayoutParams(-2,dp(36)));body.addView(head);
        tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);tabs.setPadding(0,dp(16),0,dp(8));addTab("People","people");addTab("Projects","projects");body.addView(tabs,new LinearLayout.LayoutParams(-1,dp(62)));
        LinearLayout sb=CortexUi.card(this,16);sb.setOrientation(LinearLayout.HORIZONTAL);sb.setGravity(Gravity.CENTER_VERTICAL);sb.setPadding(dp(12),0,dp(12),0);TextView mark=CortexUi.plain(this,"⌕",19,CortexUi.MUTED);mark.setGravity(Gravity.CENTER);sb.addView(mark,new LinearLayout.LayoutParams(dp(28),dp(44)));search=new EditText(this);search.setHint("Search people or projects");search.setHintTextColor(CortexUi.FAINT);search.setTextColor(CortexUi.TEXT);search.setTextSize(13);search.setSingleLine(true);search.setBackgroundColor(Color.TRANSPARENT);search.setPadding(dp(4),0,0,0);sb.addView(search,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(44));sp.setMargins(0,0,0,dp(6));body.addView(sb,sp);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){render(lastRows,lastMode);}public void afterTextChanged(Editable e){}});
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,dp(4),0,dp(24));sv.addView(feed);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"people",null);setContentView(root);styleTabs();}
    void addTab(String label,String key){TextView t=CortexUi.chip(this,label,CortexUi.MUTED,false);t.setTag(key);t.setOnClickListener(v->{mode=(String)v.getTag();styleTabs();if(search!=null)search.setText("");refreshAsync();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(40),1);if(tabs.getChildCount()>0)p.setMargins(dp(8),0,0,0);tabs.addView(t,p);}void styleTabs(){for(int i=0;i<tabs.getChildCount();i++){TextView t=(TextView)tabs.getChildAt(i);boolean on=mode.equals(t.getTag());t.setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);t.setBackground(CortexUi.round(this,on?CortexUi.SURFACE_2:CortexUi.SURFACE,on?CortexUi.ACCENT:CortexUi.BORDER_SOFT,999));if(on)CortexUi.medium(t);}}

    void refreshAsync(){if(loader.isShutdown()||db==null)return;final int g=++generation;final String wanted=mode;loader.execute(()->{try{if(!maintained){EntityGraphMaintenance.run(db);maintained=true;}ArrayList<Row> rows="people".equals(wanted)?people():projects();runOnUiThread(()->{if(g==generation&&!isFinishing()&&!isDestroyed()){lastRows=rows;lastMode=wanted;render(rows,wanted);}});}catch(Throwable e){runOnUiThread(()->{if(g==generation&&!isFinishing()&&!isDestroyed()){feed.removeAllViews();feed.addView(CortexUi.text(this,"Could not load grounded context.",12,CortexUi.MUTED));}});}});}

    ArrayList<Row> people(){ArrayList<Row> out=new ArrayList<>();String sql="SELECT n.id,n.kind,n.canonical_name,n.normalized_key,COUNT(l.id),n.metadata_json FROM entity_nodes n LEFT JOIN source_links l ON l.to_type='entity' AND l.to_id=n.id WHERE n.status='active' AND upper(n.kind)='PERSON' AND (COALESCE(n.metadata_json,'') LIKE '%\"identity\":\"phone\"%' OR COALESCE(n.metadata_json,'') LIKE '%\"confirmed\":true%') GROUP BY n.id ORDER BY COUNT(l.id) DESC,n.updated_at DESC LIMIT 160";Cursor c=db.getReadableDatabase().rawQuery(sql,null);while(c.moveToNext()){String meta=nz(c.getString(5));out.add(new Row(c.getLong(0),nz(c.getString(1)),nz(c.getString(2)),nz(c.getString(3)),c.getInt(4),false,meta.contains("\"identity\":\"phone\"")));}c.close();return out;}
    ArrayList<Row> projects(){ArrayList<Row> out=new ArrayList<>();String sql="SELECT n.id,n.kind,n.canonical_name,n.normalized_key,COUNT(l.id) FROM entity_nodes n LEFT JOIN source_links l ON l.to_type='entity' AND l.to_id=n.id WHERE n.status='active' AND upper(n.kind)='PROJECT' AND COALESCE(n.metadata_json,'') LIKE '%\"created_from\":\"project_candidate\"%' GROUP BY n.id ORDER BY COUNT(l.id) DESC,n.updated_at DESC LIMIT 100";Cursor c=db.getReadableDatabase().rawQuery(sql,null);while(c.moveToNext())out.add(new Row(c.getLong(0),nz(c.getString(1)),nz(c.getString(2)),nz(c.getString(3)),c.getInt(4),false,false));c.close();Cursor d=db.getReadableDatabase().rawQuery("SELECT id,title FROM derived_items WHERE kind='PROJECT_CANDIDATE' AND state IN ('pending','open') ORDER BY importance DESC,updated_at DESC LIMIT 80",null);while(d.moveToNext()){String name=EntityQualityPolicy.cleanProjectName(nz(d.getString(1)));if(EntityQualityPolicy.plausibleProject(name))out.add(new Row(d.getLong(0),"PROJECT_CANDIDATE",name,"candidate|"+LocalSemanticEmbedder.norm(name),0,true,false));}d.close();return dedupeProjects(out);}
    ArrayList<Row> dedupeProjects(ArrayList<Row> xs){LinkedHashMap<String,Row> map=new LinkedHashMap<>();for(Row r:xs){String key=LocalSemanticEmbedder.norm(r.name);if(key.isEmpty())continue;Row old=map.get(key);if(old==null||(!r.candidate&&old.candidate)||r.mentions>old.mentions)map.put(key,r);}return new ArrayList<>(map.values());}

    void render(ArrayList<Row> rows,String wanted){if(feed==null)return;feed.removeAllViews();String q=search==null?"":LocalSemanticEmbedder.norm(search.getText().toString());ArrayList<Row> shown=new ArrayList<>();for(Row r:rows)if(q.isEmpty()||LocalSemanticEmbedder.norm(r.name).contains(q))shown.add(r);if(shown.isEmpty()){LinearLayout c=CortexUi.card(this,22);c.setGravity(Gravity.CENTER);c.setPadding(dp(20),dp(42),dp(20),dp(42));TextView h=CortexUi.plain(this,q.isEmpty()?("people".equals(wanted)?"No identified people yet":"No confirmed projects yet"):"No match",17,CortexUi.TEXT);CortexUi.medium(h);h.setGravity(Gravity.CENTER);c.addView(h);TextView b=CortexUi.text(this,"people".equals(wanted)?"Mentions stay as evidence until Cortex has a stable identity.":"Inferred project names stay as candidates until you confirm them.",11,CortexUi.MUTED);b.setGravity(Gravity.CENTER);b.setPadding(0,dp(7),0,0);c.addView(b);feed.addView(c);return;}for(Row r:shown)addRow(r);}
    void addRow(Row r){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(2),dp(13),dp(2),dp(13));CortexUi.pressable(this,c,CortexUi.round(this,Color.TRANSPARENT,Color.TRANSPARENT,12));TextView n=CortexUi.text(this,r.name,15,CortexUi.TEXT);CortexUi.medium(n);c.addView(n);String meta=r.candidate?"Project candidate · needs confirmation":(r.identified?"Identified person":"Confirmed project")+(r.mentions>0?"  •  "+r.mentions+" grounded reference"+(r.mentions==1?"":"s"):"");TextView m=CortexUi.plain(this,meta,10,r.candidate?CortexUi.ACCENT:CortexUi.MUTED);m.setPadding(0,dp(4),0,0);c.addView(m);c.setOnClickListener(v->detail(r));feed.addView(c);feed.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}

    void detail(Row r){Dialog d=new Dialog(this);LinearLayout c=CortexUi.card(this,24);c.setPadding(dp(18),dp(18),dp(18),dp(18));TextView h=CortexUi.text(this,r.name,22,CortexUi.TEXT);CortexUi.medium(h);c.addView(h);TextView meta=CortexUi.plain(this,r.candidate?"Inferred project candidate":(r.identified?"Identified person":"Confirmed project"),11,CortexUi.MUTED);meta.setPadding(0,dp(5),0,dp(10));c.addView(meta);
        ArrayList<ContextRef> recent=r.candidate?new ArrayList<>():recentContext(r);ArrayList<String> ev=evidence(r);TextView body=CortexUi.text(this,r.candidate?"This is not a project yet. Cortex only detected project-like wording; you decide whether it becomes one.":(r.identified?"Identity details stay in the background. This view prioritizes the useful context Cortex can actually ground to this person.":"This project exists because it was explicitly confirmed."),12,CortexUi.MUTED);c.addView(body);
        if(!recent.isEmpty()){TextView rh=CortexUi.section(this,"Recent useful context");rh.setPadding(0,dp(14),0,dp(5));c.addView(rh);for(int i=0;i<Math.min(4,recent.size());i++){ContextRef x=recent.get(i);TextView e=CortexUi.text(this,"• "+x.title+(x.preview.isEmpty()?"":" — "+clip(x.preview,120)),11,CortexUi.TEXT);e.setPadding(0,dp(3),0,dp(3));final long id=x.itemId;e.setOnClickListener(v->{d.dismiss();openEvidence(id);});c.addView(e);}}
        if(!ev.isEmpty()){TextView eh=CortexUi.section(this,"Grounding details");eh.setPadding(0,dp(14),0,dp(5));c.addView(eh);for(String x:ev){TextView e=CortexUi.text(this,"• "+x,11,CortexUi.MUTED);e.setPadding(0,dp(3),0,dp(2));c.addView(e);}}
        if(r.candidate){TextView create=CortexUi.action(this,"Create project",CortexUi.ACCENT,true);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(46));pp.setMargins(0,dp(16),0,0);c.addView(create,pp);create.setOnClickListener(v->{create.setEnabled(false);boolean ok=ProjectCandidateStore.confirm(db,r.id);Toast.makeText(this,ok?"Project created":"Could not create project",Toast.LENGTH_SHORT).show();if(ok){d.dismiss();maintained=false;refreshAsync();}});TextView dismiss=CortexUi.action(this,"Not a project",CortexUi.MUTED,false);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(-1,dp(44));xp.setMargins(0,dp(8),0,0);c.addView(dismiss,xp);dismiss.setOnClickListener(v->{if(EntityGraphMaintenance.dismissCandidate(db,r.id)){d.dismiss();refreshAsync();}});}else{LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);TextView rename=CortexUi.action(this,"Rename",CortexUi.MUTED,false);TextView hide=CortexUi.action(this,r.identified?"Hide person":"Not a project",CortexUi.MUTED,false);row.addView(rename,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(0,dp(44),1);hp.setMargins(dp(8),0,0,0);row.addView(hide,hp);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(44));rp.setMargins(0,dp(14),0,0);c.addView(row,rp);rename.setOnClickListener(v->renameDialog(r,d));hide.setOnClickListener(v->{if(EntityGraphMaintenance.dismissEntity(db,r.id)){d.dismiss();refreshAsync();}});}
        long target=!recent.isEmpty()?recent.get(0).itemId:firstEvidenceMemoryId(r);if(target>0){TextView archive=CortexUi.action(this,"Open latest evidence",CortexUi.ACCENT,false);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(44));ap.setMargins(0,dp(8),0,0);c.addView(archive,ap);archive.setOnClickListener(v->{d.dismiss();openEvidence(target);});}
        TextView close=CortexUi.action(this,"Close",CortexUi.MUTED,false);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(44));cp.setMargins(0,dp(8),0,0);c.addView(close,cp);close.setOnClickListener(v->d.dismiss());d.setContentView(c);d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.92f),-2);}}

    void openEvidence(long id){Intent i=new Intent(this,VaultActivity.class);i.putExtra("item_id",id);startActivity(i);}
    void renameDialog(Row r,Dialog parent){EditText e=new EditText(this);e.setText(r.name);e.setSelection(e.length());e.setSingleLine(true);new AlertDialog.Builder(this).setTitle("Rename "+(r.identified?"person":"project")).setView(e).setNegativeButton("Cancel",null).setPositiveButton("Save",(x,w)->{String name=e.getText().toString().trim();if(EntityGraphMaintenance.rename(db,r.id,name)){r.name=name;parent.dismiss();refreshAsync();}else Toast.makeText(this,"Could not rename",Toast.LENGTH_SHORT).show();}).show();}

    ArrayList<ContextRef> recentContext(Row r){ArrayList<ContextRef> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT k.id,k.title,k.summary,k.extracted_text,k.raw_text,k.source,l.relation FROM source_links l JOIN knowledge_items k ON l.from_type='memory' AND l.from_id=k.id WHERE l.to_type='entity' AND l.to_id=? ORDER BY l.created_at DESC LIMIT 14",new String[]{String.valueOf(r.id)});while(c.moveToNext()){String source=nz(c.getString(5));if("contacts_sync".equals(source))continue;String title=nz(c.getString(1));String preview=nz(c.getString(2));if(preview.isEmpty())preview=nz(c.getString(3));if(preview.isEmpty())preview=nz(c.getString(4));out.add(new ContextRef(c.getLong(0),title.isEmpty()?"Linked evidence":title,preview,nz(c.getString(6))));if(out.size()>=6)break;}c.close();return out;}
    long firstEvidenceMemoryId(Row r){if(r.candidate)return 0;Cursor c=db.getReadableDatabase().rawQuery("SELECT l.from_id FROM source_links l WHERE l.from_type='memory' AND l.to_type='entity' AND l.to_id=? ORDER BY l.created_at DESC LIMIT 1",new String[]{String.valueOf(r.id)});long id=c.moveToFirst()?c.getLong(0):0;c.close();return id;}
    ArrayList<String> evidence(Row r){ArrayList<String> out=new ArrayList<>();if(r.candidate){Cursor c=db.getReadableDatabase().query("derived_items",new String[]{"body","source_key"},"id=?",new String[]{String.valueOf(r.id)},null,null,null,"1");if(c.moveToFirst()){String body=nz(c.getString(0)),source=nz(c.getString(1));if(!body.isEmpty())out.add(clip(body.replace("\n---\n"," · "),220));if(!source.isEmpty())out.add("Source: "+sourceLabel(source));}c.close();return out;}Cursor m=db.getReadableDatabase().query("entity_nodes",new String[]{"metadata_json"},"id=?",new String[]{String.valueOf(r.id)},null,null,null,"1");if(m.moveToFirst()){String meta=nz(m.getString(0));try{org.json.JSONObject o=new org.json.JSONObject(meta);String phone=o.optString("phone_identity","");if(!phone.isEmpty())out.add("Stable identity verified");}catch(Exception ignored){}}m.close();Cursor c=db.getReadableDatabase().rawQuery("SELECT k.title,l.relation FROM source_links l JOIN knowledge_items k ON l.from_type='memory' AND l.from_id=k.id WHERE l.to_type='entity' AND l.to_id=? ORDER BY l.created_at DESC LIMIT 6",new String[]{String.valueOf(r.id)});while(c.moveToNext()){String title=nz(c.getString(0)),rel=nz(c.getString(1));String x=title+(rel.isEmpty()?"":" · "+rel.replace('_',' '));if(!x.trim().isEmpty()&&!out.contains(x))out.add(clip(x,160));}c.close();return out;}
    String sourceLabel(String s){String x=nz(s);int p=x.lastIndexOf('.');if(p>=0&&p<x.length()-1)x=x.substring(p+1);return x.replace('_',' ');}String clip(String x,int n){String s=nz(x);return s.length()<=n?s:s.substring(0,n)+"…";}String nz(String s){return s==null?"":s.trim();}
    @Override protected void onDestroy(){generation++;loader.shutdownNow();if(db!=null){try{db.close();}catch(Throwable ignored){}db=null;}super.onDestroy();}
}
