package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.Color;
import android.os.Bundle;
import android.text.*;
import android.view.*;
import android.widget.*;
import androidx.swiperefreshlayout.widget.SwipeRefreshLayout;
import java.util.*;
import java.util.concurrent.*;

/** Atlas is Cortex's living world model: people/projects plus their grounded current state. */
public class PeopleProjectsActivity extends Activity {
    VaultDb db;LinearLayout feed,tabs;EditText search;SwipeRefreshLayout swipe;String mode="people";volatile int generation=0;final ExecutorService loader=Executors.newSingleThreadExecutor();boolean maintained=false;ArrayList<Row> lastRows=new ArrayList<>();String lastMode="people";
    int dp(int x){return CortexUi.dp(this,x);}
    static final class Row {long id;String kind,name,key;int mentions;boolean candidate,identified;String liveKind="",liveTitle="",liveBody="";long liveUpdatedAt=0,liveItemId=0,latestMemoryId=0,latestContextAt=0;String latestContext="";Row(long id,String kind,String name,String key,int mentions,boolean candidate,boolean identified){this.id=id;this.kind=kind;this.name=name;this.key=key;this.mentions=mentions;this.candidate=candidate;this.identified=identified;}}
    static final class ContextRef {long itemId,createdAt;String title,preview,relation;ContextRef(long id,long at,String t,String p,String r){itemId=id;createdAt=at;title=t;preview=p;relation=r;}}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);CognitiveStore.ensure(db);build();refreshAsync();}
    @Override protected void onResume(){super.onResume();if(db!=null&&!loader.isShutdown())refreshAsync();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),0);
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Atlas",29,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);TextView sub=CortexUi.text(this,"People and projects as Cortex understands them — current state, open loops and recent change.",11,CortexUi.MUTED);sub.setPadding(0,dp(3),0,0);titles.addView(sub);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView archive=CortexUi.chip(this,"Evidence",CortexUi.MUTED,false);archive.setOnClickListener(v->startActivity(new Intent(this,VaultActivity.class)));head.addView(archive,new LinearLayout.LayoutParams(-2,dp(36)));body.addView(head);
        tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);tabs.setPadding(0,dp(16),0,dp(8));addTab("People","people");addTab("Projects","projects");body.addView(tabs,new LinearLayout.LayoutParams(-1,dp(62)));
        LinearLayout sb=CortexUi.card(this,16);sb.setOrientation(LinearLayout.HORIZONTAL);sb.setGravity(Gravity.CENTER_VERTICAL);sb.setPadding(dp(12),0,dp(12),0);TextView mark=CortexUi.plain(this,"⌕",19,CortexUi.MUTED);mark.setGravity(Gravity.CENTER);sb.addView(mark,new LinearLayout.LayoutParams(dp(28),dp(44)));search=new EditText(this);search.setHint("Search Atlas");search.setHintTextColor(CortexUi.FAINT);search.setTextColor(CortexUi.TEXT);search.setTextSize(13);search.setSingleLine(true);search.setBackgroundColor(Color.TRANSPARENT);search.setPadding(dp(4),0,0,0);sb.addView(search,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(44));sp.setMargins(0,0,0,dp(6));body.addView(sb,sp);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){render(lastRows,lastMode);}public void afterTextChanged(Editable e){}});
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,dp(4),0,dp(24));sv.addView(feed);swipe=new SwipeRefreshLayout(this);swipe.setColorSchemeColors(CortexUi.BRAND,CortexUi.BLUE,CortexUi.ORANGE);swipe.setProgressBackgroundColorSchemeColor(CortexUi.SURFACE);swipe.addView(sv,new ViewGroup.LayoutParams(-1,-1));swipe.setOnRefreshListener(this::refreshAsync);body.addView(swipe,new LinearLayout.LayoutParams(-1,0,1));root.addView(body,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"people",null);setContentView(root);CortexUi.fitSystemBars(this,root);styleTabs();}
    void addTab(String label,String key){TextView t=CortexUi.chip(this,label,CortexUi.MUTED,false);t.setTag(key);t.setOnClickListener(v->{mode=(String)v.getTag();styleTabs();if(search!=null)search.setText("");refreshAsync();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(40),1);if(tabs.getChildCount()>0)p.setMargins(dp(8),0,0,0);tabs.addView(t,p);}void styleTabs(){for(int i=0;i<tabs.getChildCount();i++){TextView t=(TextView)tabs.getChildAt(i);boolean on=mode.equals(t.getTag());t.setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);t.setBackground(CortexUi.round(this,on?CortexUi.SURFACE_2:CortexUi.SURFACE,on?CortexUi.ACCENT:CortexUi.BORDER_SOFT,999));if(on)CortexUi.medium(t);}}

    void refreshAsync(){if(loader.isShutdown()||db==null)return;final int g=++generation;final String wanted=mode;loader.execute(()->{try{SituationLifecycle.reconcile(db);if(!maintained){EntityGraphMaintenance.run(db);maintained=true;}ArrayList<Row> rows="people".equals(wanted)?people():projects();for(Row r:rows)if(!r.candidate)enrich(r);rows.sort((a,b)->{boolean aa=!a.liveKind.isEmpty(),bb=!b.liveKind.isEmpty();if(aa!=bb)return aa?-1:1;long at=Math.max(a.liveUpdatedAt,a.latestContextAt),bt=Math.max(b.liveUpdatedAt,b.latestContextAt);int z=Long.compare(bt,at);return z!=0?z:Integer.compare(b.mentions,a.mentions);});runOnUiThread(()->{if(g==generation&&!isFinishing()&&!isDestroyed()){lastRows=rows;lastMode=wanted;render(rows,wanted);finishRefresh();}});}catch(Throwable e){runOnUiThread(()->{if(g==generation&&!isFinishing()&&!isDestroyed()){feed.removeAllViews();feed.addView(CortexUi.text(this,"Could not build Atlas right now.",12,CortexUi.MUTED));finishRefresh();}});}});}
    void finishRefresh(){if(swipe!=null)swipe.setRefreshing(false);}

    ArrayList<Row> people(){ArrayList<Row> out=new ArrayList<>();String sql="SELECT n.id,n.kind,n.canonical_name,n.normalized_key,COUNT(l.id),n.metadata_json FROM entity_nodes n LEFT JOIN source_links l ON l.to_type='entity' AND l.to_id=n.id WHERE n.status='active' AND upper(n.kind)='PERSON' AND (COALESCE(n.metadata_json,'') LIKE '%\"identity\":\"phone\"%' OR COALESCE(n.metadata_json,'') LIKE '%\"confirmed\":true%') GROUP BY n.id ORDER BY n.updated_at DESC LIMIT 160";Cursor c=db.getReadableDatabase().rawQuery(sql,null);try{while(c.moveToNext()){String meta=nz(c.getString(5));out.add(new Row(c.getLong(0),nz(c.getString(1)),nz(c.getString(2)),nz(c.getString(3)),c.getInt(4),false,meta.contains("\"identity\":\"phone\"")));}}finally{c.close();}return out;}
    ArrayList<Row> projects(){ArrayList<Row> out=new ArrayList<>();String sql="SELECT n.id,n.kind,n.canonical_name,n.normalized_key,COUNT(l.id) FROM entity_nodes n LEFT JOIN source_links l ON l.to_type='entity' AND l.to_id=n.id WHERE n.status='active' AND upper(n.kind)='PROJECT' AND COALESCE(n.metadata_json,'') LIKE '%\"created_from\":\"project_candidate\"%' GROUP BY n.id ORDER BY n.updated_at DESC LIMIT 100";Cursor c=db.getReadableDatabase().rawQuery(sql,null);try{while(c.moveToNext())out.add(new Row(c.getLong(0),nz(c.getString(1)),nz(c.getString(2)),nz(c.getString(3)),c.getInt(4),false,false));}finally{c.close();}Cursor d=db.getReadableDatabase().rawQuery("SELECT id,title FROM derived_items WHERE kind='PROJECT_CANDIDATE' AND state IN ('pending','open') ORDER BY importance DESC,updated_at DESC LIMIT 80",null);try{while(d.moveToNext()){String name=EntityQualityPolicy.cleanProjectName(nz(d.getString(1)));if(EntityQualityPolicy.plausibleProject(name))out.add(new Row(d.getLong(0),"PROJECT_CANDIDATE",name,"candidate|"+LocalSemanticEmbedder.norm(name),0,true,false));}}finally{d.close();}return dedupeProjects(out);}
    ArrayList<Row> dedupeProjects(ArrayList<Row> xs){LinkedHashMap<String,Row> map=new LinkedHashMap<>();for(Row r:xs){String key=LocalSemanticEmbedder.norm(r.name);if(key.isEmpty())continue;Row old=map.get(key);if(old==null||(!r.candidate&&old.candidate)||r.mentions>old.mentions)map.put(key,r);}return new ArrayList<>(map.values());}

    void enrich(Row r){ArrayList<ContextRef> recent=recentContext(r);if(!recent.isEmpty()){ContextRef x=recent.get(0);r.latestMemoryId=x.itemId;r.latestContextAt=x.createdAt;r.latestContext=x.title+(x.preview.isEmpty()?"":" — "+clip(x.preview,90));}
        String sql="SELECT d.id,d.kind,d.title,d.body,d.confidence,d.importance,d.thread_id,d.anchor_signal_id,d.updated_at FROM derived_items d WHERE d.state='open' AND d.kind IN ('ACTION','WAITING','DECISION','REMINDER','ALERT','CHANGE') AND (EXISTS(SELECT 1 FROM source_links l WHERE l.from_type='derived' AND l.from_id=d.id AND l.to_type='entity' AND l.to_id=?) OR EXISTS(SELECT 1 FROM source_links dm JOIN source_links me ON dm.to_type='memory' AND me.from_type='memory' AND me.from_id=dm.to_id AND me.to_type='entity' AND me.to_id=? WHERE dm.from_type='derived' AND dm.from_id=d.id) OR EXISTS(SELECT 1 FROM source_links rs WHERE rs.from_type='raw_signal' AND rs.from_id=d.anchor_signal_id AND rs.to_type='entity' AND rs.to_id=?)) ORDER BY d.updated_at DESC LIMIT 12";
        String id=String.valueOf(r.id);Cursor c=db.getReadableDatabase().rawQuery(sql,new String[]{id,id,id});PrimeBriefStore.Item best=null;try{while(c.moveToNext()){PrimeBriefStore.Item x=new PrimeBriefStore.Item(c.getLong(0),nz(c.getString(1)),nz(c.getString(2)),nz(c.getString(3)),"atlas","open",c.getDouble(4),c.getInt(5),c.getLong(6),c.getLong(7),c.getLong(8));if(!SituationLifecycle.shouldSurface(db,x)||PrimeBriefStore.hardSurfaceNoise(x))continue;if(best==null||x.attentionScore>best.attentionScore||(x.attentionScore==best.attentionScore&&x.updatedAt>best.updatedAt))best=x;}}finally{c.close();}if(best!=null){r.liveItemId=best.id;r.liveKind=best.attentionKind;r.liveTitle=CandidateConsolidator.presentationTitle(best);r.liveBody=best.body;r.liveUpdatedAt=best.updatedAt;}}

    void render(ArrayList<Row> rows,String wanted){if(feed==null)return;feed.removeAllViews();String q=search==null?"":LocalSemanticEmbedder.norm(search.getText().toString());ArrayList<Row> shown=new ArrayList<>();for(Row r:rows)if(q.isEmpty()||LocalSemanticEmbedder.norm(r.name).contains(q))shown.add(r);if(shown.isEmpty()){LinearLayout c=CortexUi.card(this,22);c.setGravity(Gravity.CENTER);c.setPadding(dp(20),dp(42),dp(20),dp(42));TextView h=CortexUi.plain(this,q.isEmpty()?("people".equals(wanted)?"No grounded people yet":"No grounded projects yet"):"No match",17,CortexUi.TEXT);CortexUi.medium(h);h.setGravity(Gravity.CENTER);c.addView(h);TextView b=CortexUi.text(this,"people".equals(wanted)?"People appear after Cortex has a stable identity, not from loose name guesses.":"Projects appear when they are confirmed; candidates stay reviewable instead of becoming facts.",11,CortexUi.MUTED);b.setGravity(Gravity.CENTER);b.setPadding(0,dp(7),0,0);c.addView(b);feed.addView(c);return;}for(Row r:shown)addRow(r);}
    void addRow(Row r){LinearLayout c=CortexUi.card(this,18);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(14),dp(13),dp(14),dp(13));TextView n=CortexUi.text(this,r.name,16,CortexUi.TEXT);CortexUi.medium(n);c.addView(n);if(r.candidate){TextView m=CortexUi.plain(this,"PROJECT CANDIDATE · NEEDS YOUR CONFIRMATION",9,CortexUi.ORANGE);m.setPadding(0,dp(5),0,0);c.addView(m);}else if(!r.liveKind.isEmpty()){TextView state=CortexUi.plain(this,r.liveKind+" · "+age(r.liveUpdatedAt),9,colorFor(r.liveKind));state.setPadding(0,dp(5),0,0);c.addView(state);String summary=!r.liveTitle.isEmpty()?r.liveTitle:r.liveBody;TextView s=CortexUi.text(this,clip(summary,150),12,CortexUi.TEXT);s.setMaxLines(2);s.setPadding(0,dp(5),0,0);c.addView(s);}else if(!r.latestContext.isEmpty()){TextView state=CortexUi.plain(this,"NO OPEN LOOP · LAST CONTEXT "+age(r.latestContextAt),9,CortexUi.MUTED);state.setPadding(0,dp(5),0,0);c.addView(state);TextView s=CortexUi.text(this,clip(r.latestContext,140),11,CortexUi.MUTED);s.setMaxLines(2);s.setPadding(0,dp(4),0,0);c.addView(s);}else{TextView state=CortexUi.plain(this,"NO ACTIVE SITUATION",9,CortexUi.FAINT);state.setPadding(0,dp(5),0,0);c.addView(state);}c.setOnClickListener(v->detail(r));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(8));feed.addView(c,p);}
    int colorFor(String kind){if("ACTION".equals(kind)||"REMINDER".equals(kind))return CortexUi.BRAND;if("WAITING".equals(kind))return CortexUi.AURORA;if("DECISION".equals(kind))return CortexUi.ORANGE;return CortexUi.BLUE;}

    void detail(Row r){Dialog d=new Dialog(this);ScrollView sv=new ScrollView(this);LinearLayout c=CortexUi.card(this,24);c.setPadding(dp(18),dp(18),dp(18),dp(18));sv.addView(c);TextView h=CortexUi.text(this,r.name,22,CortexUi.TEXT);CortexUi.medium(h);c.addView(h);if(!r.liveKind.isEmpty()){TextView state=CortexUi.section(this,"Current state");state.setPadding(0,dp(12),0,dp(5));c.addView(state);TextView live=CortexUi.text(this,r.liveKind+" · "+clip(!r.liveTitle.isEmpty()?r.liveTitle:r.liveBody,220),12,CortexUi.TEXT);c.addView(live);}else{TextView quiet=CortexUi.text(this,"No grounded open loop is active for this "+(r.identified?"person":"project")+" right now.",12,CortexUi.MUTED);quiet.setPadding(0,dp(10),0,0);c.addView(quiet);}ArrayList<ContextRef> recent=r.candidate?new ArrayList<>():recentContext(r);if(!recent.isEmpty()){TextView rh=CortexUi.section(this,"Recent grounded context");rh.setPadding(0,dp(14),0,dp(5));c.addView(rh);for(int i=0;i<Math.min(5,recent.size());i++){ContextRef x=recent.get(i);TextView e=CortexUi.text(this,"• "+x.title+(x.preview.isEmpty()?"":" — "+clip(x.preview,120)),11,CortexUi.TEXT);e.setPadding(0,dp(3),0,dp(3));final long mid=x.itemId;e.setOnClickListener(v->{d.dismiss();openEvidence(mid);});c.addView(e);}}TextView grounding=CortexUi.plain(this,r.mentions+" grounded link"+(r.mentions==1?"":"s")+" in Cortex evidence",9,CortexUi.FAINT);grounding.setPadding(0,dp(12),0,0);c.addView(grounding);
        if(r.candidate){TextView create=CortexUi.action(this,"Create project",CortexUi.ACCENT,true);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,dp(46));pp.setMargins(0,dp(16),0,0);c.addView(create,pp);create.setOnClickListener(v->{boolean ok=ProjectCandidateStore.confirm(db,r.id);Toast.makeText(this,ok?"Project created":"Could not create project",Toast.LENGTH_SHORT).show();if(ok){d.dismiss();maintained=false;refreshAsync();}});}else{TextView ask=CortexUi.action(this,r.identified?"Ask Brain about this person":"Ask Brain about this project",CortexUi.ACCENT,true);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-1,dp(46));bp.setMargins(0,dp(14),0,0);c.addView(ask,bp);ask.setOnClickListener(v->{d.dismiss();openEntityBrain(r);});}
        TextView close=CortexUi.action(this,"Close",CortexUi.MUTED,false);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(44));cp.setMargins(0,dp(8),0,0);c.addView(close,cp);close.setOnClickListener(v->d.dismiss());d.setContentView(sv);d.show();Window w=d.getWindow();if(w!=null){w.setBackgroundDrawableResource(android.R.color.transparent);w.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.92f),(int)(getResources().getDisplayMetrics().heightPixels*.82f));}}

    void openEntityBrain(Row r){try{Intent i=new Intent(this,AskCortexActivity.class);if(r.latestMemoryId>0)i.putExtra("item_id",r.latestMemoryId);String subject=r.identified?"person":"project";i.putExtra("prefill","Using only grounded Cortex evidence for the "+subject+" ‘"+r.name+"’, tell me the current state, unresolved open loops, what changed recently, and the best next action. Distinguish facts from uncertainty and do not infer from the name alone.");startActivity(i);}catch(Throwable e){Toast.makeText(this,"Could not open Brain",Toast.LENGTH_SHORT).show();}}
    void openEvidence(long id){Intent i=new Intent(this,VaultActivity.class);i.putExtra("item_id",id);startActivity(i);}
    ArrayList<ContextRef> recentContext(Row r){ArrayList<ContextRef> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT k.id,k.created_at,k.title,k.summary,k.extracted_text,k.raw_text,k.source,l.relation FROM source_links l JOIN knowledge_items k ON l.from_type='memory' AND l.from_id=k.id WHERE l.to_type='entity' AND l.to_id=? ORDER BY l.created_at DESC LIMIT 16",new String[]{String.valueOf(r.id)});try{while(c.moveToNext()){String source=nz(c.getString(6));if("contacts_sync".equals(source))continue;String title=nz(c.getString(2));String preview=nz(c.getString(3));if(preview.isEmpty())preview=nz(c.getString(4));if(preview.isEmpty())preview=nz(c.getString(5));out.add(new ContextRef(c.getLong(0),c.getLong(1),title.isEmpty()?"Linked evidence":title,preview,nz(c.getString(7))));if(out.size()>=6)break;}}finally{c.close();}return out;}
    String age(long at){if(at<=0)return"unknown";long m=Math.max(0,(System.currentTimeMillis()-at)/60000);if(m<1)return"now";if(m<60)return m+"m";long h=m/60;if(h<24)return h+"h";long d=h/24;return d+"d";}String clip(String x,int n){String s=nz(x);return s.length()<=n?s:s.substring(0,n)+"…";}String nz(String s){return s==null?"":s.trim();}
    @Override protected void onDestroy(){generation++;loader.shutdownNow();if(db!=null){try{db.close();}catch(Throwable ignored){}db=null;}super.onDestroy();}
}
