package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** PRIME Brief: recent intentional captures plus grounded derived intelligence. */
public class PremiumHomeActivity extends Activity {
    VaultDb db;LinearLayout content;volatile int refreshGeneration=0;
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);CognitiveStore.ensure(db);build();refreshAsync();new Thread(()->{try{TemporalResolver.backfill(db,250);V41Maintenance.run(this,db);ContactSafetyMaintenance.run(db);}catch(Throwable ignored){}},"CortexMaintenance").start();}
    @Override protected void onResume(){super.onResume();if(db!=null)refreshAsync();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(20),dp(14),dp(20),dp(26));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));header();TextView loading=CortexUi.text(this,"Building your brief…",12,CortexUi.MUTED);loading.setPadding(0,dp(24),0,0);content.addView(loading);CortexUi.addBottomNav(this,root,"brief",null);setContentView(root);}
    void header(){LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView title=CortexUi.plain(this,"Brief",31,CortexUi.TEXT);CortexUi.medium(title);titles.addView(title);TextView subtitle=CortexUi.text(this,"What just happened, what needs you, and what Cortex thinks matters.",11,CortexUi.MUTED);subtitle.setPadding(0,dp(3),0,0);titles.addView(subtitle);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView settings=CortexUi.chip(this,"Settings",CortexUi.MUTED,false);settings.setOnClickListener(v->open(SettingsActivity.class));head.addView(settings,new LinearLayout.LayoutParams(-2,dp(36)));content.addView(head);}

    void refreshAsync(){final int g=++refreshGeneration;new Thread(()->{try{PrimeBriefStore.Snapshot s=PrimeBriefStore.load(db);runOnUiThread(()->{if(g!=refreshGeneration||isFinishing())return;render(s);});}catch(Throwable e){runOnUiThread(()->{if(g==refreshGeneration&&!isFinishing())renderError();});}},"CortexPrimeBrief").start();}

    void render(PrimeBriefStore.Snapshot s){while(content.getChildCount()>1)content.removeViewAt(1);if(s.empty()){LinearLayout empty=CortexUi.card(this,24);empty.setPadding(dp(18),dp(28),dp(18),dp(28));TextView h=CortexUi.plain(this,"Nothing needs you right now",19,CortexUi.TEXT);CortexUi.medium(h);empty.addView(h);TextView b=CortexUi.text(this,"New captures will appear here while Cortex analyzes them, then useful actions, waiting items, reviews and insights will surface with their reason and source.",12,CortexUi.MUTED);b.setPadding(0,dp(7),0,0);empty.addView(b);LinearLayout.LayoutParams ep=new LinearLayout.LayoutParams(-1,-2);ep.setMargins(0,dp(22),0,0);content.addView(empty,ep);return;}
        if(!s.recent.isEmpty()){content.addView(CortexUi.section(this,"Recent"));for(int i=0;i<Math.min(6,s.recent.size());i++)recentRow(s.recent.get(i));}
        if(!s.actions.isEmpty()){content.addView(CortexUi.section(this,"Needs you"));for(int i=0;i<Math.min(6,s.actions.size());i++)derivedRow(s.actions.get(i));}
        if(!s.waiting.isEmpty()){content.addView(CortexUi.section(this,"Waiting"));for(int i=0;i<Math.min(5,s.waiting.size());i++)derivedRow(s.waiting.get(i));}
        if(!s.reviews.isEmpty()){content.addView(CortexUi.section(this,"Needs your review"));for(int i=0;i<Math.min(4,s.reviews.size());i++)reviewRow(s.reviews.get(i));TextView all=CortexUi.action(this,"Review all ("+s.reviews.size()+")",CortexUi.MUTED,false);all.setOnClickListener(v->open(ReviewQueueActivity.class));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(42));ap.setMargins(0,dp(8),0,0);content.addView(all,ap);}
        if(!s.worthKnowing.isEmpty()){content.addView(CortexUi.section(this,"Worth knowing"));for(int i=0;i<Math.min(6,s.worthKnowing.size());i++)derivedRow(s.worthKnowing.get(i));}
        if(!s.changes.isEmpty()){content.addView(CortexUi.section(this,"Changed & evolving"));for(int i=0;i<Math.min(6,s.changes.size());i++)derivedRow(s.changes.get(i));}
    }

    void recentRow(KnowledgeItem k){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(2),dp(12),dp(2),dp(12));CortexUi.pressable(this,row,CortexUi.round(this,Color.TRANSPARENT,Color.TRANSPARENT,12));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=CortexUi.text(this,empty(k.title)?friendlyType(k.type):k.title,14,CortexUi.TEXT);CortexUi.medium(title);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView badge=CortexUi.chip(this,recentStatus(k.status),statusColor(k.status),true);top.addView(badge,new LinearLayout.LayoutParams(-2,dp(30)));row.addView(top);String preview=!empty(k.summary)?k.summary:(!empty(k.extractedText)?k.extractedText:k.rawText);if(!empty(preview)){TextView p=CortexUi.text(this,clip(preview,160),12,CortexUi.MUTED);p.setMaxLines(3);p.setPadding(0,dp(5),0,0);row.addView(p);}TextView meta=CortexUi.plain(this,friendlyType(k.type)+"  •  "+age(k.createdAt)+"  •  captured by you",10,CortexUi.MUTED);meta.setPadding(0,dp(6),0,0);row.addView(meta);row.setOnClickListener(v->{Intent i=new Intent(this,CaptureResultActivity.class);i.putExtra("item_id",k.id);startActivity(i);});content.addView(row);content.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}

    void derivedRow(PrimeBriefStore.Item x){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(2),dp(13),dp(2),dp(13));CortexUi.pressable(this,row,CortexUi.round(this,Color.TRANSPARENT,Color.TRANSPARENT,12));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView title=CortexUi.text(this,cleanTitle(x.title,x.kind),14,CortexUi.TEXT);CortexUi.medium(title);top.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView badge=CortexUi.chip(this,friendlyKind(x.kind),kindColor(x.kind),true);top.addView(badge,new LinearLayout.LayoutParams(-2,dp(30)));row.addView(top);String preview=cleanBody(x.body);if(!preview.isEmpty()){TextView body=CortexUi.text(this,clip(preview,180),12,CortexUi.MUTED);body.setPadding(0,dp(5),0,0);body.setMaxLines(3);row.addView(body);}TextView meta=CortexUi.plain(this,"Why: "+whyShort(x)+"  •  "+age(x.updatedAt),10,CortexUi.MUTED);meta.setPadding(0,dp(6),0,0);row.addView(meta);row.setOnClickListener(v->derivedDetail(x));content.addView(row);content.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}

    void reviewRow(ReviewQueueStore.Item x){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.VERTICAL);row.setPadding(dp(2),dp(13),dp(2),dp(13));CortexUi.pressable(this,row,CortexUi.round(this,Color.TRANSPARENT,Color.TRANSPARENT,12));TextView title=CortexUi.text(this,cleanTitle(x.title,x.candidateKind),14,CortexUi.TEXT);CortexUi.medium(title);row.addView(title);String body=cleanBody(x.body);if(!body.isEmpty()){TextView b=CortexUi.text(this,clip(body,180),12,CortexUi.MUTED);b.setPadding(0,dp(5),0,0);b.setMaxLines(3);row.addView(b);}TextView meta=CortexUi.plain(this,"Possible "+friendlyKind(x.candidateKind)+"  •  source "+sourceLabel(x.sourceKey)+"  •  "+age(x.createdAt),10,CortexUi.ACCENT);meta.setPadding(0,dp(6),0,0);row.addView(meta);row.setOnClickListener(v->open(ReviewQueueActivity.class));content.addView(row);content.addView(CortexUi.divider(this),new LinearLayout.LayoutParams(-1,dp(1)));}

    void derivedDetail(PrimeBriefStore.Item x){Dialog d=new Dialog(this);LinearLayout c=CortexUi.card(this,25);c.setPadding(dp(18),dp(18),dp(18),dp(18));TextView h=CortexUi.text(this,cleanTitle(x.title,x.kind),21,CortexUi.TEXT);CortexUi.medium(h);c.addView(h);TextView meta=CortexUi.plain(this,friendlyKind(x.kind)+"  •  "+sourceLabel(x.source)+"  •  "+exactTime(x.updatedAt),10,CortexUi.MUTED);meta.setPadding(0,dp(5),0,dp(12));c.addView(meta);if(!cleanBody(x.body).isEmpty()){TextView b=CortexUi.text(this,cleanBody(x.body),13,CortexUi.TEXT);b.setTextIsSelectable(true);c.addView(b);}TextView whyHead=CortexUi.section(this,"Why this is here");whyHead.setPadding(0,dp(14),0,dp(6));c.addView(whyHead);c.addView(CortexUi.text(this,whyLong(x),12,CortexUi.MUTED));TextView confidence=CortexUi.plain(this,"Confidence "+Math.round(x.confidence*100)+"%  •  priority "+x.importance,10,CortexUi.MUTED);confidence.setPadding(0,dp(10),0,0);c.addView(confidence);TextView close=CortexUi.action(this,"Close",CortexUi.MUTED,false);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,dp(44));cp.setMargins(0,dp(16),0,0);c.addView(close,cp);close.setOnClickListener(v->d.dismiss());d.setContentView(c);Window w=d.getWindow();if(w!=null)w.setBackgroundDrawableResource(android.R.color.transparent);d.show();if(d.getWindow()!=null)d.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.92f),-2);}

    String whyShort(PrimeBriefStore.Item x){return friendlyKind(x.kind).toLowerCase(Locale.ROOT)+" from "+sourceLabel(x.source)+" · "+Math.round(x.confidence*100)+"%";}
    String whyLong(PrimeBriefStore.Item x){String role;if("ACTION".equalsIgnoreCase(x.kind))role="Cortex believes this is an open commitment that may need you.";else if("WAITING".equalsIgnoreCase(x.kind))role="Cortex believes someone or something may owe you a follow-up.";else if("DECISION".equalsIgnoreCase(x.kind))role="Cortex detected a decision worth keeping visible.";else role="Cortex considered this useful enough to keep in the Brief.";return role+" Source: "+sourceLabel(x.source)+". Confidence: "+Math.round(x.confidence*100)+"%.";}
    String recentStatus(String s){String x=n(s);if("analyzed".equals(x))return"Understood";if("analysis_failed".equals(x)||"failed_retryable".equals(x))return"Needs retry";return"Analyzing";}int statusColor(String s){return"analyzed".equals(n(s))?CortexUi.SAGE:("analysis_failed".equals(n(s))||"failed_retryable".equals(n(s))?CortexUi.ACCENT:CortexUi.MUTED);}String friendlyType(String t){if("AUDIO".equals(t))return"Voice";if("FILE".equals(t))return"File";if("SCREENSHOT".equals(t)||"IMAGE".equals(t))return"Image";return"Text";}
    void renderError(){while(content.getChildCount()>1)content.removeViewAt(1);TextView t=CortexUi.text(this,"Brief could not load right now. Your data is still safe.",12,CortexUi.MUTED);t.setPadding(0,dp(24),0,0);content.addView(t);}void open(Class<?> c){Intent i=new Intent(this,c);i.addFlags(Intent.FLAG_ACTIVITY_REORDER_TO_FRONT|Intent.FLAG_ACTIVITY_SINGLE_TOP);startActivity(i);}
    String friendlyKind(String k){String x=n(k).toUpperCase(Locale.ROOT);if("ACTION".equals(x))return"Action";if("WAITING".equals(x))return"Waiting";if("DECISION".equals(x))return"Decision";if("PROJECT_CANDIDATE".equals(x))return"Project";if("GOAL_SIGNAL".equals(x))return"Goal";if("IDEA".equals(x))return"Idea";if("OPPORTUNITY".equals(x))return"Opportunity";if("INSIGHT".equals(x))return"Insight";if("HYPOTHESIS".equals(x))return"Hypothesis";return x.isEmpty()?"Update":x;}int kindColor(String k){if("ACTION".equalsIgnoreCase(k))return CortexUi.ACCENT;if("WAITING".equalsIgnoreCase(k))return CortexUi.GOLD;if("DECISION".equalsIgnoreCase(k))return CortexUi.SAGE;if("OPPORTUNITY".equalsIgnoreCase(k)||"IDEA".equalsIgnoreCase(k)||"INSIGHT".equalsIgnoreCase(k))return CortexUi.SAGE;return CortexUi.MUTED;}
    String sourceLabel(String s){String x=n(s);if(x.isEmpty())return"Cortex";int p=x.lastIndexOf('.');if(p>=0&&p<x.length()-1)x=x.substring(p+1);x=x.replace('_',' ');return Character.toUpperCase(x.charAt(0))+x.substring(1);}String cleanTitle(String s,String kind){String x=n(s);if(x.isEmpty())return friendlyKind(kind);x=x.replace(" · Action","").replace(" · Waiting","").replace(" · Decision","").replace(" · Review action","").replace(" · Review waiting","").replace(" · Review decision","");return x.trim();}String cleanBody(String s){return n(s).replace("\n---\n","\n").trim();}String clip(String s,int max){String x=n(s);return x.length()<=max?x:x.substring(0,max)+"…";}String age(long ms){long m=Math.max(0,System.currentTimeMillis()-ms)/60000;if(m<1)return"now";if(m<60)return m+"m";long h=m/60;if(h<24)return h+"h";long d=h/24;return d<7?d+"d":new SimpleDateFormat("dd MMM",Locale.getDefault()).format(new Date(ms));}String exactTime(long ms){return new SimpleDateFormat("dd MMM · HH:mm",Locale.getDefault()).format(new Date(ms));}boolean empty(String s){return s==null||s.trim().isEmpty();}String n(String s){return s==null?"":s.trim();}
}
