package com.kareem.cortex;

import android.database.Cursor;
import java.util.*;

/** Read model for PRIME Brief. Uses unified derived intelligence plus the materialized attention feed. */
public final class PrimeBriefStore {
    private PrimeBriefStore(){}
    public static final class Item {public final long id,threadId,signalId,updatedAt;public final String kind,title,body,source,state;public final double confidence;public final int importance;Item(long id,String kind,String title,String body,String source,String state,double confidence,int importance,long threadId,long signalId,long updatedAt){this.id=id;this.kind=n(kind);this.title=n(title);this.body=n(body);this.source=n(source);this.state=n(state);this.confidence=confidence;this.importance=importance;this.threadId=threadId;this.signalId=signalId;this.updatedAt=updatedAt;}}
    public static final class Snapshot {public final ArrayList<KnowledgeItem> recent;public final ArrayList<Item> actions,waiting,decisions,changes,worthKnowing;public final ArrayList<ReviewQueueStore.Item> reviews;public final ArrayList<AttentionFeedStore.Item> attention,comingUp,insights,projects;Snapshot(ArrayList<KnowledgeItem> recent,ArrayList<Item>a,ArrayList<Item>w,ArrayList<Item>d,ArrayList<Item>c,ArrayList<Item>k,ArrayList<ReviewQueueStore.Item>r,ArrayList<AttentionFeedStore.Item>attention,ArrayList<AttentionFeedStore.Item>comingUp,ArrayList<AttentionFeedStore.Item>insights,ArrayList<AttentionFeedStore.Item>projects){this.recent=recent;actions=a;waiting=w;decisions=d;changes=c;worthKnowing=k;reviews=r;this.attention=attention;this.comingUp=comingUp;this.insights=insights;this.projects=projects;}public boolean empty(){return recent.isEmpty()&&actions.isEmpty()&&waiting.isEmpty()&&decisions.isEmpty()&&reviews.isEmpty()&&changes.isEmpty()&&worthKnowing.isEmpty()&&attention.isEmpty()&&comingUp.isEmpty()&&insights.isEmpty()&&projects.isEmpty();}}
    public static Snapshot load(VaultDb db){CognitiveStore.ensure(db);CortexAttentionSchema.ensure(db);AttentionMaintenance.refresh(db);DerivedAttentionBridge.refresh(db);ArrayList<AttentionFeedStore.Item> attention=new ArrayList<>(AttentionFeedStore.loadNow(db,5)),coming=new ArrayList<>(AttentionFeedStore.loadComingUp(db,5)),insights=new ArrayList<>(AttentionFeedStore.loadSection(db,"INSIGHTS",6,true)),projects=new ArrayList<>(AttentionFeedStore.loadSection(db,"PROJECTS",6,true));ArrayList<Item> actions=suppressAttentionThreads(query(db,"ACTION",12),attention,coming,12);return new Snapshot(recentCaptures(db,10),actions,query(db,"WAITING",12),query(db,"DECISION",8),recentChanges(db,10),worthKnowing(db,10),ReviewQueueStore.pending(db,12),attention,coming,insights,projects);}
    private static ArrayList<Item> suppressAttentionThreads(ArrayList<Item> legacy,ArrayList<AttentionFeedStore.Item> now,ArrayList<AttentionFeedStore.Item> coming,int limit){HashSet<Long> threads=new HashSet<>();for(AttentionFeedStore.Item x:now)if(x.threadId>0)threads.add(x.threadId);for(AttentionFeedStore.Item x:coming)if(x.threadId>0)threads.add(x.threadId);ArrayList<Item> out=new ArrayList<>();for(Item x:legacy){if(x.threadId>0&&threads.contains(x.threadId))continue;out.add(x);if(out.size()>=limit)break;}return out;}
    private static ArrayList<KnowledgeItem> recentCaptures(VaultDb db,int limit){ArrayList<KnowledgeItem> out=new ArrayList<>();for(KnowledgeItem k:db.lexicalSearch("",100)){if(!intentionalCapture(k))continue;out.add(k);if(out.size()>=limit)break;}return out;}
    private static boolean intentionalCapture(KnowledgeItem k){if(k==null)return false;String s=n(k.source);if("CONTACT".equals(k.type)||"NOTIFICATION".equals(k.type))return false;return"manual".equals(s)||"manual_recording".equals(s)||"android_share".equals(s)||"audio_import".equals(s)||"quick_capture".equals(s)||"screen_understanding".equals(s)||"screen_understand".equals(s);}
    private static ArrayList<Item> query(VaultDb db,String kind,int limit){ArrayList<Item> out=new ArrayList<>();Cursor c=db.getReadableDatabase().query("derived_items",new String[]{"id","kind","title","body","source_key","state","confidence","importance","thread_id","anchor_signal_id","updated_at"},"kind=? AND state='open'",new String[]{kind},null,null,"importance DESC, updated_at DESC",String.valueOf(limit*3));while(c.moveToNext())out.add(from(c));c.close();return dedupe(out,limit);}
    private static ArrayList<Item> recentChanges(VaultDb db,int limit){ArrayList<Item> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,kind,title,body,source_key,state,confidence,importance,thread_id,anchor_signal_id,updated_at FROM derived_items WHERE state IN ('open','pending') AND kind IN ('DECISION','PROJECT_CANDIDATE','GOAL_SIGNAL') ORDER BY updated_at DESC,importance DESC LIMIT ?",new String[]{String.valueOf(limit*3)});while(c.moveToNext())out.add(from(c));c.close();return dedupe(out,limit);}
    private static ArrayList<Item> worthKnowing(VaultDb db,int limit){ArrayList<Item> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,kind,title,body,source_key,state,confidence,importance,thread_id,anchor_signal_id,updated_at FROM derived_items WHERE state='open' AND kind IN ('IDEA','OPPORTUNITY','INSIGHT','HYPOTHESIS') ORDER BY importance DESC,updated_at DESC LIMIT ?",new String[]{String.valueOf(limit*3)});while(c.moveToNext())out.add(from(c));c.close();return dedupe(out,limit);}
    private static ArrayList<Item> dedupe(ArrayList<Item> xs,int limit){LinkedHashMap<String,Item> map=new LinkedHashMap<>();for(Item x:xs){String basis=!x.body.isEmpty()?x.body:x.title;String key=x.kind+"|"+LocalSemanticEmbedder.norm(basis);if(key.length()>180)key=key.substring(0,180);Item old=map.get(key);if(old==null||x.importance>old.importance||x.updatedAt>old.updatedAt)map.put(key,x);}ArrayList<Item> out=new ArrayList<>(map.values());out.sort((a,b)->{int z=Integer.compare(b.importance,a.importance);return z!=0?z:Long.compare(b.updatedAt,a.updatedAt);});if(out.size()>limit)return new ArrayList<>(out.subList(0,limit));return out;}
    private static Item from(Cursor c){return new Item(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getInt(7),c.getLong(8),c.getLong(9),c.getLong(10));}private static String n(String s){return s==null?"":s.trim();}
}
