package com.kareem.cortex;

import android.database.Cursor;
import java.util.*;

/** Read model for Now/Brief. Only validated projections may surface; raw capture never becomes a Brief item. */
public final class PrimeBriefStore {
    private PrimeBriefStore(){}
    public static final class Item {public final long id,threadId,signalId,updatedAt;public final String kind,title,body,source,state;public final double confidence;public final int importance;Item(long id,String kind,String title,String body,String source,String state,double confidence,int importance,long threadId,long signalId,long updatedAt){this.id=id;this.kind=n(kind);this.title=n(title);this.body=n(body);this.source=n(source);this.state=n(state);this.confidence=confidence;this.importance=importance;this.threadId=threadId;this.signalId=signalId;this.updatedAt=updatedAt;}}
    public static final class Snapshot {public final ArrayList<KnowledgeItem> recent;public final ArrayList<Item> actions,waiting,decisions,changes,worthKnowing;public final ArrayList<ReviewQueueStore.Item> reviews;Snapshot(ArrayList<KnowledgeItem> recent,ArrayList<Item>a,ArrayList<Item>w,ArrayList<Item>d,ArrayList<Item>c,ArrayList<Item>k,ArrayList<ReviewQueueStore.Item>r){this.recent=recent;actions=a;waiting=w;decisions=d;changes=c;worthKnowing=k;reviews=r;}public boolean empty(){return recent.isEmpty()&&actions.isEmpty()&&waiting.isEmpty()&&decisions.isEmpty()&&reviews.isEmpty()&&changes.isEmpty()&&worthKnowing.isEmpty();}}
    public static Snapshot load(VaultDb db){CognitiveStore.ensure(db);UniversalEventStore.ensure(db.getWritableDatabase());UniversalProjectionPolicy.sanitizeExisting(db.getWritableDatabase());return new Snapshot(intentionalCaptures(db,6),attention(db,"ACTION",12),attention(db,"WAITING",12),attention(db,"DECISION",8),meaningfulChanges(db,12),legacyWorthKnowing(db,8),ReviewQueueStore.pending(db,12));}
    private static ArrayList<KnowledgeItem> intentionalCaptures(VaultDb db,int limit){ArrayList<KnowledgeItem> out=new ArrayList<>();for(KnowledgeItem k:db.captureSearch("",120)){String s=n(k.source);if(!("manual".equals(s)||"quick_capture".equals(s)||"android_share".equals(s)))continue;out.add(k);if(out.size()>=limit)break;}return out;}
    private static ArrayList<Item> attention(VaultDb db,String kind,int limit){ArrayList<Item> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT a.id,a.kind,a.title,a.body,a.source_key,a.state,a.confidence,a.priority,a.situation_id,a.semantic_event_id,a.updated_at,e.semantic_type,e.intent FROM ue_attention_items a JOIN ue_semantic_events e ON e.id=a.semantic_event_id WHERE a.kind=? AND a.state='open' AND e.semantic_state='complete' AND e.superseded_by=0 ORDER BY a.priority DESC,a.updated_at DESC LIMIT ?",new String[]{kind,String.valueOf(limit*3)});while(c.moveToNext()){String validated=UniversalProjectionPolicy.validateAttention(c.getString(11),c.getString(12),c.getString(1),c.getDouble(6));if(!kind.equals(validated))continue;out.add(new Item(UniversalEventStore.ATTENTION_COMPAT_OFFSET+c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getInt(7),c.getLong(8),0,c.getLong(10)));}c.close();if(out.size()<limit){Cursor l=db.getReadableDatabase().rawQuery("SELECT d.id,d.kind,d.title,d.body,d.source_key,d.state,d.confidence,d.importance,d.thread_id,d.anchor_signal_id,d.updated_at FROM derived_items d WHERE d.kind=? AND d.state='open' AND COALESCE(d.candidate_kind,'')<>'UE_ATTENTION' AND NOT EXISTS(SELECT 1 FROM raw_signals r WHERE r.id=d.anchor_signal_id AND r.kind='notification') ORDER BY d.importance DESC,d.updated_at DESC LIMIT ?",new String[]{kind,String.valueOf(limit)});while(l.moveToNext())out.add(fromLegacy(l));l.close();}return dedupe(out,limit);}
    private static ArrayList<Item> meaningfulChanges(VaultDb db,int limit){ArrayList<Item> out=new ArrayList<>();long since=System.currentTimeMillis()-48L*60L*60L*1000L;Cursor c=db.getReadableDatabase().rawQuery("SELECT e.id,e.semantic_type,e.subject,e.summary,s.source_type,e.semantic_state,e.confidence,CASE WHEN e.semantic_type IN ('decision','commitment','action_request') THEN 75 ELSE 45 END,e.stream_id,e.raw_observation_id,e.occurred_at FROM ue_semantic_events e JOIN ue_streams s ON s.id=e.stream_id WHERE e.meaningful=1 AND e.superseded_by=0 AND e.semantic_state='complete' AND e.confidence>=0.70 AND e.semantic_type NOT IN ('technical_state','notification_event','CortexEvent','call_event') AND (TRIM(COALESCE(e.subject,''))<>'' OR TRIM(COALESCE(e.summary,''))<>'') AND e.occurred_at>=? ORDER BY e.occurred_at DESC LIMIT ?",new String[]{String.valueOf(since),String.valueOf(limit*5)});while(c.moveToNext()){if(!UniversalProjectionPolicy.userFacingSemantic(c.getString(1),c.getString(5),c.getDouble(6),c.getString(2),c.getString(3)))continue;out.add(new Item(c.getLong(0),"CHANGE",CanonicalPresentation.cleanTitle(c.getString(4),c.getString(1),c.getString(2),c.getString(2)),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getInt(7),c.getLong(8),0,c.getLong(10)));}c.close();return dedupe(out,limit);}
    private static ArrayList<Item> legacyWorthKnowing(VaultDb db,int limit){ArrayList<Item> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,kind,title,body,source_key,state,confidence,importance,thread_id,anchor_signal_id,updated_at FROM derived_items WHERE state='open' AND COALESCE(candidate_kind,'')<>'UE_ATTENTION' AND kind IN ('IDEA','OPPORTUNITY','INSIGHT','HYPOTHESIS') AND NOT EXISTS(SELECT 1 FROM raw_signals r WHERE r.id=anchor_signal_id AND r.kind='notification') ORDER BY importance DESC,updated_at DESC LIMIT ?",new String[]{String.valueOf(limit*3)});while(c.moveToNext())out.add(fromLegacy(c));c.close();return dedupe(out,limit);}
    private static Item fromLegacy(Cursor c){return new Item(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getInt(7),c.getLong(8),c.getLong(9),c.getLong(10));}

    /** Collapse duplicate read-model cards without deleting source events. Same situation always wins; otherwise use bounded semantic overlap. */
    private static ArrayList<Item> dedupe(ArrayList<Item> xs,int limit){
        ArrayList<Item> ordered=new ArrayList<>(xs);ordered.sort((a,b)->{int z=Integer.compare(b.importance,a.importance);return z!=0?z:Long.compare(b.updatedAt,a.updatedAt);});
        ArrayList<Item> out=new ArrayList<>();
        for(Item x:ordered){int match=-1;for(int i=0;i<out.size();i++)if(sameProjection(out.get(i),x)){match=i;break;}if(match<0)out.add(x);else if(better(x,out.get(match)))out.set(match,x);}
        out.sort((a,b)->{int z=Integer.compare(b.importance,a.importance);return z!=0?z:Long.compare(b.updatedAt,a.updatedAt);});
        if(out.size()>limit)return new ArrayList<>(out.subList(0,limit));return out;
    }
    private static boolean better(Item a,Item b){if(a.importance!=b.importance)return a.importance>b.importance;if(Double.compare(a.confidence,b.confidence)!=0)return a.confidence>b.confidence;return a.updatedAt>b.updatedAt;}
    private static boolean sameProjection(Item a,Item b){
        if(!a.kind.equals(b.kind))return false;
        if(a.threadId>0&&b.threadId>0&&a.threadId==b.threadId)return true;
        if(Math.abs(a.updatedAt-b.updatedAt)>6L*60L*60L*1000L)return false;
        Set<String> aa=topicTokens(a),bb=topicTokens(b);if(aa.size()<3||bb.size()<3)return false;int shared=0;for(String x:aa)if(bb.contains(x))shared++;double overlap=(double)shared/(double)Math.min(aa.size(),bb.size());return shared>=3&&overlap>=0.55;
    }
    private static Set<String> topicTokens(Item x){String s=LocalSemanticEmbedder.norm(n(x.title)+" "+n(x.body)).toLowerCase(Locale.ROOT);String[] parts=s.split("[^\\p{L}\\p{N}]+");HashSet<String> out=new HashSet<>();for(String p:parts){String w=stem(p);if(w.length()<4||STOP.contains(w))continue;out.add(w);}return out;}
    private static String stem(String w){String x=n(w).toLowerCase(Locale.ROOT);if(x.length()>7&&x.endsWith("ing"))x=x.substring(0,x.length()-3);else if(x.length()>6&&x.endsWith("ed"))x=x.substring(0,x.length()-2);else if(x.length()>5&&x.endsWith("s"))x=x.substring(0,x.length()-1);return x;}
    private static final Set<String> STOP=new HashSet<>(Arrays.asList("that","this","with","from","were","was","are","the","and","for","your","user","some","have","has","into","than","then","been","being","received","indicating","recommending","about","after","before","على","الى","إلى","هذا","هذه","التي","الذي","كان","كانت","تم","من","في"));
    private static String n(String s){return s==null?"":s.trim();}
}
