package com.kareem.cortex;

import android.database.Cursor;
import java.util.*;

/** Read model for NOW. Raw captures and derived rows are not useful merely because they exist. */
public final class PrimeBriefStore {
    private PrimeBriefStore(){}
    public static final class Item {public final long id,threadId,signalId,updatedAt;public final String kind,title,body,source,state;public final double confidence;public final int importance;Item(long id,String kind,String title,String body,String source,String state,double confidence,int importance,long threadId,long signalId,long updatedAt){this.id=id;this.kind=n(kind);this.title=n(title);this.body=n(body);this.source=n(source);this.state=n(state);this.confidence=confidence;this.importance=importance;this.threadId=threadId;this.signalId=signalId;this.updatedAt=updatedAt;}}
    public static final class Snapshot {public final ArrayList<KnowledgeItem> recent;public final ArrayList<Item> actions,waiting,decisions,changes,worthKnowing;public final ArrayList<ReviewQueueStore.Item> reviews;Snapshot(ArrayList<KnowledgeItem> recent,ArrayList<Item>a,ArrayList<Item>w,ArrayList<Item>d,ArrayList<Item>c,ArrayList<Item>k,ArrayList<ReviewQueueStore.Item>r){this.recent=recent;actions=a;waiting=w;decisions=d;changes=c;worthKnowing=k;reviews=r;}public boolean empty(){return actions.isEmpty()&&waiting.isEmpty()&&decisions.isEmpty()&&reviews.isEmpty();}}

    /** NOW precedence: Needs You > Waiting > Decisions. Everything else belongs in History/Search. */
    public static Snapshot load(VaultDb db){CognitiveStore.ensure(db);try{ContextResolver.refresh(db);}catch(Throwable ignored){}LinkedHashSet<String> claimed=new LinkedHashSet<>();ArrayList<Item> actions=claimLane(query(db,"ACTION",24),claimed,12);ArrayList<Item> waiting=claimLane(query(db,"WAITING",24),claimed,12);ArrayList<Item> decisions=claimLane(query(db,"DECISION",20),claimed,10);ArrayList<Item> knowing=claimLane(worthKnowing(db,20),claimed,10);ArrayList<Item> changes=claimLane(recentChanges(db,20),claimed,10);return new Snapshot(recentCaptures(db,10),actions,waiting,decisions,changes,knowing,ReviewQueueStore.pending(db,12));}

    private static ArrayList<Item> claimLane(ArrayList<Item> xs,Set<String> claimed,int limit){ArrayList<Item> out=new ArrayList<>();for(Item x:xs){String key=identity(x);if(claimed.contains(key))continue;claimed.add(key);out.add(x);if(out.size()>=limit)break;}return out;}
    private static String identity(Item x){if(x==null)return"null";if(x.signalId>0)return"signal:"+x.signalId;if(x.id>0)return"derived:"+x.id;String basis=!x.body.isEmpty()?x.body:x.title;String semantic=LocalSemanticEmbedder.norm(basis);if(semantic.length()>220)semantic=semantic.substring(0,220);return"semantic:"+semantic;}

    private static ArrayList<KnowledgeItem> recentCaptures(VaultDb db,int limit){ArrayList<KnowledgeItem> out=new ArrayList<>();for(KnowledgeItem k:db.lexicalSearch("",100)){if(!intentionalCapture(k))continue;out.add(k);if(out.size()>=limit)break;}return out;}
    private static boolean intentionalCapture(KnowledgeItem k){if(k==null)return false;String s=n(k.source);if("CONTACT".equals(k.type)||"NOTIFICATION".equals(k.type))return false;return"manual".equals(s)||"manual_recording".equals(s)||"android_share".equals(s)||"audio_import".equals(s)||"quick_capture".equals(s)||"screen_understanding".equals(s)||"screen_understand".equals(s);}
    private static ArrayList<Item> query(VaultDb db,String kind,int limit){ArrayList<Item> out=new ArrayList<>();Cursor c=db.getReadableDatabase().query("derived_items",new String[]{"id","kind","title","body","source_key","state","confidence","importance","thread_id","anchor_signal_id","updated_at"},"kind=? AND state='open'",new String[]{kind},null,null,"importance DESC, updated_at DESC",String.valueOf(limit*4));while(c.moveToNext()){Item x=from(c);if(truthVisible(x))out.add(x);}c.close();return dedupe(out,limit);}
    static boolean truthVisible(Item x){if(x==null)return false;if("DECISION".equalsIgnoreCase(x.kind))return CortexTruthPolicy.confirmedDecision(x.title,x.body,x.source);if("ACTION".equalsIgnoreCase(x.kind))return CortexTruthPolicy.confirmedAction(x.title,x.body,x.source,x.confidence);if("WAITING".equalsIgnoreCase(x.kind))return CortexTruthPolicy.confirmedWaiting(x.title,x.body,x.source,x.confidence);return true;}
    private static ArrayList<Item> recentChanges(VaultDb db,int limit){ArrayList<Item> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,kind,title,body,source_key,state,confidence,importance,thread_id,anchor_signal_id,updated_at FROM derived_items WHERE state IN ('open','pending') AND kind IN ('PROJECT_CANDIDATE','GOAL_SIGNAL') ORDER BY updated_at DESC,importance DESC LIMIT ?",new String[]{String.valueOf(limit*3)});while(c.moveToNext())out.add(from(c));c.close();return dedupe(out,limit);}
    private static ArrayList<Item> worthKnowing(VaultDb db,int limit){ArrayList<Item> out=new ArrayList<>();Cursor c=db.getReadableDatabase().rawQuery("SELECT id,kind,title,body,source_key,state,confidence,importance,thread_id,anchor_signal_id,updated_at FROM derived_items WHERE state='open' AND kind IN ('IDEA','OPPORTUNITY','INSIGHT','HYPOTHESIS') ORDER BY importance DESC,updated_at DESC LIMIT ?",new String[]{String.valueOf(limit*3)});while(c.moveToNext())out.add(from(c));c.close();return dedupe(out,limit);}
    private static ArrayList<Item> dedupe(ArrayList<Item> xs,int limit){LinkedHashMap<String,Item> map=new LinkedHashMap<>();for(Item x:xs){String key=identity(x);Item old=map.get(key);if(old==null||x.importance>old.importance||x.updatedAt>old.updatedAt)map.put(key,x);}ArrayList<Item> out=new ArrayList<>(map.values());out.sort((a,b)->{int z=Integer.compare(b.importance,a.importance);return z!=0?z:Long.compare(b.updatedAt,a.updatedAt);});if(out.size()>limit)return new ArrayList<>(out.subList(0,limit));return out;}
    private static Item from(Cursor c){return new Item(c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getDouble(6),c.getInt(7),c.getLong(8),c.getLong(9),c.getLong(10));}
    private static String n(String s){return s==null?"":s.trim();}
}
