package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;

/** Reusable Prompt / AI Library with real Brain runs, saved results and ratings. */
public final class PromptLibraryActivity extends Activity {
    LinearLayout list;TextView summary;volatile boolean destroyed=false,busy=false;final ExecutorService worker=Executors.newSingleThreadExecutor();
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);build();load();}
    @Override protected void onResume(){super.onResume();load();}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),dp(30));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout hs=new LinearLayout(this);hs.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Prompt Library",27,CortexUi.TEXT);CortexUi.medium(h);hs.addView(h);hs.addView(CortexUi.text(this,"Reuse prompts, run them through Brain, keep the latest result/provider/latency, and rate what works.",11,CortexUi.MUTED));head.addView(hs,new LinearLayout.LayoutParams(0,-2,1));body.addView(head);summary=CortexUi.text(this,"Loading…",12,CortexUi.MUTED);summary.setPadding(0,dp(10),0,dp(10));body.addView(summary);TextView add=CortexUi.action(this,"Add recent Cortex text as prompt",CortexUi.ACCENT,true);add.setOnClickListener(v->chooseRecent());body.addView(add,new LinearLayout.LayoutParams(-1,dp(48)));TextView note=CortexUi.text(this,"Run with Brain uses Combined mode: Cortex context + OX Alpha/OpenRouter when configured, with the normal fallback chain. A run never sends a draft/action externally.",11,CortexUi.MUTED);note.setPadding(0,dp(10),0,dp(14));body.addView(note);list=new LinearLayout(this);list.setOrientation(LinearLayout.VERTICAL);body.addView(list);setContentView(root);CortexUi.fitSystemBars(this,root);}

    void load(){if(destroyed||worker.isShutdown())return;try{worker.execute(()->{VaultDb db=null;ArrayList<PromptLibraryStore.Entry> xs=new ArrayList<>();try{db=new VaultDb(getApplicationContext());PromptLibraryStore.ensure(db);xs=PromptLibraryStore.list(db,120);}catch(Throwable ignored){}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}final ArrayList<PromptLibraryStore.Entry> out=xs;post(()->render(out));});}catch(RejectedExecutionException ignored){}}
    void render(ArrayList<PromptLibraryStore.Entry> xs){if(destroyed)return;summary.setText(xs.size()+" reusable/prompt-tagged item"+(xs.size()==1?"":"s")+(busy?" · Brain run in progress":""));list.removeAllViews();if(xs.isEmpty()){TextView empty=CortexUi.text(this,"No reusable prompts yet. Add one from recent Cortex text above.",13,CortexUi.MUTED);empty.setPadding(0,dp(18),0,0);list.addView(empty);return;}for(PromptLibraryStore.Entry e:xs)addCard(e);}
    void addCard(PromptLibraryStore.Entry e){LinearLayout c=CortexUi.card(this,18);c.setPadding(dp(14),dp(12),dp(14),dp(12));TextView title=CortexUi.text(this,e.title.isEmpty()?"Prompt #"+e.itemId:e.title,14,CortexUi.TEXT);CortexUi.medium(title);c.addView(title);TextView prompt=CortexUi.text(this,clip(e.prompt,900),12,CortexUi.TEXT);prompt.setTextIsSelectable(true);prompt.setPadding(0,dp(6),0,0);c.addView(prompt);String rating=e.rating>0?"Useful":e.rating<0?"Not useful":"Not rated";String meta="Used "+e.useCount+" · "+rating+(e.lastProvider.isEmpty()?"":" · last "+e.lastProvider+(e.lastLatencyMs>0?" · "+friendlyMs(e.lastLatencyMs):""));TextView m=CortexUi.plain(this,meta,10,CortexUi.MUTED);m.setPadding(0,dp(7),0,0);c.addView(m);if(!e.lastResult.isEmpty()){TextView lh=CortexUi.plain(this,"Latest result",10,CortexUi.ACCENT);CortexUi.medium(lh);lh.setPadding(0,dp(9),0,0);c.addView(lh);TextView lr=CortexUi.text(this,clip(e.lastResult,1200),11,CortexUi.MUTED);lr.setTextIsSelectable(true);lr.setPadding(0,dp(4),0,0);c.addView(lr);}
        TextView run=CortexUi.action(this,busy?"Brain busy…":"Run with Brain (Combined)",CortexUi.ACCENT,true);run.setEnabled(!busy);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(44));rp.setMargins(0,dp(10),0,0);c.addView(run,rp);run.setOnClickListener(v->runPrompt(e));
        LinearLayout rate=new LinearLayout(this);rate.setOrientation(LinearLayout.HORIZONTAL);TextView good=CortexUi.action(this,"Useful",CortexUi.SAGE,false),bad=CortexUi.action(this,"Not useful",CortexUi.MUTED,false);rate.addView(good,new LinearLayout.LayoutParams(0,dp(40),1));LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(0,dp(40),1);bp.setMargins(dp(7),0,0,0);rate.addView(bad,bp);LinearLayout.LayoutParams rr=new LinearLayout.LayoutParams(-1,-2);rr.setMargins(0,dp(7),0,0);c.addView(rate,rr);good.setOnClickListener(v->rate(e.itemId,1));bad.setOnClickListener(v->rate(e.itemId,-1));
        LinearLayout actions=new LinearLayout(this);actions.setOrientation(LinearLayout.HORIZONTAL);TextView source=CortexUi.action(this,"Open evidence",CortexUi.MUTED,false),remove=CortexUi.action(this,e.pinned?"Remove":"Pin",CortexUi.MUTED,false);actions.addView(source,new LinearLayout.LayoutParams(0,dp(40),1));LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(40),1);xp.setMargins(dp(7),0,0,0);actions.addView(remove,xp);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,-2);ap.setMargins(0,dp(7),0,0);c.addView(actions,ap);source.setOnClickListener(v->openEvidence(e.itemId));remove.setOnClickListener(v->pin(e.itemId,!e.pinned));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(9));list.addView(c,cp);}

    void runPrompt(PromptLibraryStore.Entry e){if(busy||destroyed)return;busy=true;load();Toast.makeText(this,"Brain is running this prompt…",Toast.LENGTH_SHORT).show();try{worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());LocalAskRouter.Result r=BrainRouter.fast(getApplicationContext(),db,e.prompt,"combined",0,null);PromptLibraryStore.recordRun(db,e.itemId,r.answer,r.provider,r.totalMs);final String answer=r.answer,provider=r.provider;final long ms=r.totalMs;post(()->{busy=false;load();TextView text=CortexUi.text(this,answer,13,CortexUi.TEXT);text.setTextIsSelectable(true);int p=dp(16);text.setPadding(p,p,p,p);ScrollView s=new ScrollView(this);s.addView(text);new AlertDialog.Builder(this).setTitle("Brain result · "+provider+" · "+friendlyMs(ms)).setView(s).setNegativeButton("Close",null).setPositiveButton("Open Brain",(d,w)->{Intent i=new Intent(this,AskCortexActivity.class);i.putExtra("prefill",e.prompt);startActivity(i);}).show();});}catch(Throwable ex){post(()->{busy=false;load();Toast.makeText(this,"Prompt run stopped safely: "+safe(ex.getMessage()),Toast.LENGTH_LONG).show();});}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}});}catch(RejectedExecutionException ex){busy=false;load();}}
    void rate(long id,int value){try{worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());PromptLibraryStore.rate(db,id,value);CortexActionExecutor.recordFeedback(db,id,"prompt_rating",String.valueOf(value));}catch(Throwable ignored){}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}post(this::load);});}catch(RejectedExecutionException ignored){}}
    void pin(long id,boolean on){try{worker.execute(()->{VaultDb db=null;try{db=new VaultDb(getApplicationContext());if(on)PromptLibraryStore.pin(db,id);else PromptLibraryStore.unpin(db,id);}catch(Throwable ignored){}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}post(this::load);});}catch(RejectedExecutionException ignored){}}
    void chooseRecent(){if(destroyed||worker.isShutdown())return;try{worker.execute(()->{VaultDb db=null;ArrayList<PromptLibraryStore.Entry> xs=new ArrayList<>();try{db=new VaultDb(getApplicationContext());xs=PromptLibraryStore.recentTextCandidates(db,60);}catch(Throwable ignored){}finally{if(db!=null)try{db.close();}catch(Throwable ignored){}}final ArrayList<PromptLibraryStore.Entry> out=xs;post(()->{if(out.isEmpty()){Toast.makeText(this,"No analyzed text/file memories are available yet",Toast.LENGTH_LONG).show();return;}String[] labels=new String[out.size()];for(int i=0;i<out.size();i++){PromptLibraryStore.Entry e=out.get(i);labels[i]=(e.title.isEmpty()?"Memory #"+e.itemId:e.title)+"\n"+clip(e.prompt,90);}new AlertDialog.Builder(this).setTitle("Add to Prompt Library").setItems(labels,(d,w)->pin(out.get(w).itemId,true)).setNegativeButton("Cancel",null).show();});});}catch(RejectedExecutionException ignored){}}
    void openEvidence(long id){try{Intent i=new Intent(this,VaultActivity.class);i.putExtra("item_id",id);startActivity(i);}catch(Throwable e){Toast.makeText(this,"Could not open source evidence",Toast.LENGTH_SHORT).show();}}
    void post(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())try{r.run();}catch(Throwable ignored){}});}String clip(String s,int n){String x=safe(s);return x.length()<=n?x:x.substring(0,n)+"…";}String friendlyMs(long ms){return ms<1000?ms+" ms":String.format(Locale.US,"%.1f s",ms/1000f);}String safe(String s){return s==null?"":s;}
}
