package com.kareem.cortex;

import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import java.util.*;

/** User-controlled reusable prompt library metadata layered over existing Cortex memories. */
public final class PromptLibraryStore {
    private PromptLibraryStore(){}
    public static final class Entry {public long itemId,pinnedAt,lastRunAt,lastLatencyMs;public int useCount,rating;public boolean pinned;public String title="",prompt="",lastResult="",lastProvider="";}

    public static void ensure(VaultDb db){SQLiteDatabase s=db.getWritableDatabase();s.execSQL("CREATE TABLE IF NOT EXISTS prompt_library_items(item_id INTEGER PRIMARY KEY,pinned INTEGER DEFAULT 1,pinned_at INTEGER NOT NULL,use_count INTEGER DEFAULT 0,rating INTEGER DEFAULT 0,last_run_at INTEGER DEFAULT 0,last_latency_ms INTEGER DEFAULT 0,last_provider TEXT,last_result TEXT,updated_at INTEGER NOT NULL)");s.execSQL("CREATE INDEX IF NOT EXISTS idx_prompt_library_updated ON prompt_library_items(updated_at DESC)");}
    public static void pin(VaultDb db,long itemId){if(itemId<=0)return;ensure(db);long now=System.currentTimeMillis();ContentValues v=new ContentValues();v.put("item_id",itemId);v.put("pinned",1);v.put("pinned_at",now);v.put("updated_at",now);db.getWritableDatabase().insertWithOnConflict("prompt_library_items",null,v,SQLiteDatabase.CONFLICT_IGNORE);ContentValues u=new ContentValues();u.put("pinned",1);u.put("updated_at",now);db.getWritableDatabase().update("prompt_library_items",u,"item_id=?",new String[]{String.valueOf(itemId)});}
    public static void unpin(VaultDb db,long itemId){ensure(db);ContentValues v=new ContentValues();v.put("pinned",0);v.put("updated_at",System.currentTimeMillis());db.getWritableDatabase().update("prompt_library_items",v,"item_id=?",new String[]{String.valueOf(itemId)});}
    public static void rate(VaultDb db,long itemId,int rating){ensure(db);pin(db,itemId);ContentValues v=new ContentValues();v.put("rating",Math.max(-1,Math.min(1,rating)));v.put("updated_at",System.currentTimeMillis());db.getWritableDatabase().update("prompt_library_items",v,"item_id=?",new String[]{String.valueOf(itemId)});}
    public static void recordRun(VaultDb db,long itemId,String result,String provider,long latencyMs){ensure(db);pin(db,itemId);ContentValues v=new ContentValues();v.put("use_count",useCount(db,itemId)+1);v.put("last_run_at",System.currentTimeMillis());v.put("last_latency_ms",Math.max(0,latencyMs));v.put("last_provider",safe(provider));v.put("last_result",clip(result,8000));v.put("updated_at",System.currentTimeMillis());db.getWritableDatabase().update("prompt_library_items",v,"item_id=?",new String[]{String.valueOf(itemId)});}
    public static ArrayList<Entry> list(VaultDb db,int limit){ensure(db);int lim=Math.max(1,Math.min(300,limit));String q="SELECT k.id,k.title,COALESCE(NULLIF(k.raw_text,''),NULLIF(k.extracted_text,''),k.summary,''),COALESCE(p.pinned,0),COALESCE(p.pinned_at,0),COALESCE(p.use_count,0),COALESCE(p.rating,0),COALESCE(p.last_run_at,0),COALESCE(p.last_latency_ms,0),COALESCE(p.last_provider,''),COALESCE(p.last_result,'') FROM knowledge_items k LEFT JOIN prompt_library_items p ON p.item_id=k.id WHERE COALESCE(p.pinned,0)=1 OR lower(COALESCE(k.tags,'')) LIKE '%prompt%' OR lower(COALESCE(k.category,'')) LIKE '%prompt%' OR lower(COALESCE(k.source,'')) LIKE '%prompt%' ORDER BY COALESCE(p.pinned,0) DESC,COALESCE(p.updated_at,k.updated_at) DESC LIMIT ?";Cursor c=db.getReadableDatabase().rawQuery(q,new String[]{String.valueOf(lim)});ArrayList<Entry> out=new ArrayList<>();while(c.moveToNext()){Entry e=new Entry();e.itemId=c.getLong(0);e.title=safe(c.getString(1));e.prompt=safe(c.getString(2));e.pinned=c.getInt(3)==1;e.pinnedAt=c.getLong(4);e.useCount=c.getInt(5);e.rating=c.getInt(6);e.lastRunAt=c.getLong(7);e.lastLatencyMs=c.getLong(8);e.lastProvider=safe(c.getString(9));e.lastResult=safe(c.getString(10));if(!e.prompt.isEmpty())out.add(e);}c.close();return out;}
    public static ArrayList<Entry> recentTextCandidates(VaultDb db,int limit){int lim=Math.max(1,Math.min(100,limit));Cursor c=db.getReadableDatabase().rawQuery("SELECT id,title,COALESCE(NULLIF(raw_text,''),NULLIF(extracted_text,''),summary,'') FROM knowledge_items WHERE type IN ('TEXT','FILE') AND status='analyzed' ORDER BY updated_at DESC LIMIT ?",new String[]{String.valueOf(lim)});ArrayList<Entry> out=new ArrayList<>();while(c.moveToNext()){Entry e=new Entry();e.itemId=c.getLong(0);e.title=safe(c.getString(1));e.prompt=safe(c.getString(2));if(!e.prompt.isEmpty())out.add(e);}c.close();return out;}
    private static int useCount(VaultDb db,long id){Cursor c=db.getReadableDatabase().rawQuery("SELECT use_count FROM prompt_library_items WHERE item_id=?",new String[]{String.valueOf(id)});int n=c.moveToFirst()?c.getInt(0):0;c.close();return n;}
    private static String clip(String s,int n){String x=safe(s);return x.length()<=n?x:x.substring(0,n)+"…";}private static String safe(String s){return s==null?"":s.trim();}
}
