package com.kareem.cortex;

import android.content.Intent;
import android.database.Cursor;
import android.graphics.Color;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.util.*;

/** PRIME World: people and projects as useful relationship/situation intelligence. */
public final class ProposalPeopleProjectsActivity extends PeopleProjectsActivity {
    @Override void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(10),dp(18),0);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));body.addView(header());
        TextView expl=CortexUi.text(this,"Open relationships and projects first. Raw references stay in the background.",11,CortexUi.MUTED);expl.setPadding(dp(4),0,dp(4),dp(5));body.addView(expl);
        tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);tabs.setPadding(0,dp(10),0,dp(8));addTab("People","people");addTab("Projects","projects");body.addView(tabs,new LinearLayout.LayoutParams(-1,dp(56)));
        LinearLayout sb=CortexUi.card(this,18);sb.setOrientation(LinearLayout.HORIZONTAL);sb.setGravity(Gravity.CENTER_VERTICAL);sb.setPadding(dp(9),dp(4),dp(10),dp(4));sb.addView(CortexUi.glyph(this,"search",CortexUi.GREEN,false),new LinearLayout.LayoutParams(dp(38),dp(38)));search=new EditText(this);search.setHint("Search people or projects");search.setHintTextColor(CortexUi.FAINT);search.setTextColor(CortexUi.TEXT);search.setTextSize(13);search.setSingleLine(true);search.setBackgroundColor(Color.TRANSPARENT);search.setPadding(dp(9),0,0,0);sb.addView(search,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(52));sp.setMargins(0,0,0,dp(7));body.addView(sb,sp);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int count){render(lastRows,lastMode);}public void afterTextChanged(Editable e){}});
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);sv.setClipToPadding(false);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,dp(5),0,dp(24));sv.addView(feed);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"world",null);setContentView(root);styleTabs();
    }

    View header(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(5),dp(8),dp(2),dp(7));View dot=new View(this);dot.setBackground(CortexUi.round(this,CortexUi.GREEN,Color.TRANSPARENT,999));row.addView(dot,new LinearLayout.LayoutParams(dp(9),dp(9)));TextView c=CortexUi.plain(this,"C O R T E X",14,CortexUi.TEXT);CortexUi.bold(c);if(android.os.Build.VERSION.SDK_INT>=21)c.setLetterSpacing(.20f);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-2,dp(40));cp.setMargins(dp(12),0,0,0);row.addView(c,cp);View d=CortexUi.divider(this);LinearLayout.LayoutParams dv=new LinearLayout.LayoutParams(dp(1),dp(28));dv.setMargins(dp(12),0,dp(12),0);row.addView(d,dv);TextView sys=CortexUi.plain(this,"WORLD",10,CortexUi.MUTED);if(android.os.Build.VERSION.SDK_INT>=21)sys.setLetterSpacing(.10f);row.addView(sys,new LinearLayout.LayoutParams(0,dp(40),1));CortexGlyphView archive=CortexUi.glyph(this,"file",CortexUi.GREEN,false);archive.setOnClickListener(v->startActivity(new Intent(this,VaultActivity.class)));row.addView(archive,new LinearLayout.LayoutParams(dp(46),dp(46)));return row;}

    @Override void styleTabs(){if(tabs==null)return;for(int i=0;i<tabs.getChildCount();i++){TextView t=(TextView)tabs.getChildAt(i);boolean on=mode.equals(t.getTag());int color="people".equals(t.getTag())?CortexUi.GREEN:CortexUi.YELLOW;t.setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);int wash=on?Color.argb(18,Color.red(color),Color.green(color),Color.blue(color)):Color.TRANSPARENT;t.setBackground(CortexUi.round(this,wash,on?Color.argb(80,Color.red(color),Color.green(color),Color.blue(color)):CortexUi.BORDER_SOFT,999));CortexUi.raised(this,t,on?3:1);if(on)CortexUi.medium(t);}}

    @Override void addRow(Row r){
        Insight in=relationshipInsight(r);int color=r.candidate?CortexUi.ORANGE:(in.openCount>0?CortexUi.RED:CortexUi.GREEN);String icon="people".equals(mode)?"person":"project";
        LinearLayout card=CortexUi.card(this,18);card.setPadding(0,0,0,0);LinearLayout main=new LinearLayout(this);main.setGravity(Gravity.CENTER_VERTICAL);main.setPadding(dp(11),dp(11),dp(10),dp(9));
        View rail=new View(this);rail.setBackground(CortexUi.round(this,color,Color.TRANSPARENT,999));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(dp(3),dp(52));rp.setMargins(0,0,dp(10),0);main.addView(rail,rp);main.addView(CortexUi.glyph(this,icon,color,true),new LinearLayout.LayoutParams(dp(46),dp(46)));
        LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(11),0,dp(8),0);main.addView(tx,xp);TextView n=CortexUi.text(this,r.name,15,CortexUi.TEXT);CortexUi.medium(n);n.setMaxLines(2);tx.addView(n);
        String meta=r.candidate?"Needs confirmation":in.statusLine;TextView m=CortexUi.plain(this,meta,10,r.candidate?CortexUi.ORANGE:(in.openCount>0?CortexUi.RED:CortexUi.MUTED));m.setPadding(0,dp(4),0,0);tx.addView(m);main.addView(CortexUi.chip(this,r.candidate?"REVIEW":(in.openCount>0?"OPEN":"CONTEXT"),color,true),new LinearLayout.LayoutParams(-2,dp(32)));card.addView(main);main.setOnClickListener(v->detail(r));

        if(!r.candidate){LinearLayout intel=new LinearLayout(this);intel.setOrientation(LinearLayout.VERTICAL);intel.setPadding(dp(14),0,dp(12),dp(10));if(!in.latest.isEmpty()){TextView last=CortexUi.text(this,"Latest · "+proposalClip(in.latest,190),11,CortexUi.TEXT);last.setPadding(0,0,0,dp(4));intel.addView(last);}TextView next=CortexUi.text(this,"Next · "+in.next,11,in.openCount>0?CortexUi.TEXT:CortexUi.MUTED);intel.addView(next);card.addView(intel);}

        ArrayList<ContextRef> recent=r.candidate?new ArrayList<>():safeRecent(r);StringBuilder result=new StringBuilder();result.append(r.candidate?"Project candidate":"people".equals(mode)?"Relationship":"Project").append(": ").append(r.name);result.append("\nStatus: ").append(in.statusLine);if(!in.latest.isEmpty())result.append("\nLatest useful context: ").append(in.latest);result.append("\nBest next move: ").append(in.next);if(r.mentions>0)result.append("\nGrounded references: ").append(r.mentions);long sourceId=recent.isEmpty()?0:recent.get(0).itemId;
        LinearLayout host=new LinearLayout(this);host.setOrientation(LinearLayout.VERTICAL);host.setPadding(dp(12),0,dp(10),dp(8));card.addView(host);ProposalUi.attach(this,db,host,new ResultProposalEngine.Target("World","world_"+r.kind+"_"+r.id,r.name,result.toString(),sourceId,r.kind,false));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);if(feed.getChildCount()>0)cp.setMargins(0,dp(8),0,0);feed.addView(card,cp);
    }

    private Insight relationshipInsight(Row r){if(r.candidate)return new Insight(0,"Project candidate","Confirm whether this is a real project","");int open=0;String latest="";String q="%"+r.name+"%";Cursor c=null;try{c=db.getReadableDatabase().rawQuery("SELECT kind,title,body,updated_at FROM derived_items WHERE state IN ('open','pending') AND (title LIKE ? OR body LIKE ?) ORDER BY importance DESC,updated_at DESC LIMIT 5",new String[]{q,q});while(c.moveToNext()){open++;if(latest.isEmpty())latest=ppNz(c.getString(1))+(ppNz(c.getString(2)).isEmpty()?"":" — "+ppNz(c.getString(2)));}}catch(Throwable ignored){}finally{if(c!=null)c.close();}ArrayList<ContextRef> recent=safeRecent(r);if(latest.isEmpty()&&!recent.isEmpty()){ContextRef x=recent.get(0);latest=ppNz(x.title)+(ppNz(x.preview).isEmpty()?"":" — "+ppNz(x.preview));}String status=open>0?open+" open situation"+(open==1?"":"s"):(recent.isEmpty()?"No active grounded context":"No open situation · recent context available");String next=open>0?"Open the current situation and resolve, follow up, or schedule the next step":(recent.isEmpty()?"No action needed until new evidence arrives":"Review the latest context only if this relationship/project is active");return new Insight(open,status,next,latest);}
    static final class Insight{final int openCount;final String statusLine,next,latest;Insight(int o,String s,String n,String l){openCount=o;statusLine=s;next=n;latest=l;}}

    @Override void openEntityBrain(Row r,long focal){String subject=r.identified?"identified person":"confirmed project";CortexActionExecutor.openBrain(this,focal,"Focus on the "+subject+" ‘"+r.name+"’. Start with what is CURRENTLY OPEN, what changed most recently, what is waiting on them versus waiting on me, related projects/situations, and the single best next action. Use grounded Cortex evidence connected to this exact "+(r.identified?"person":"project")+". Do not infer facts from the name alone and do not lead with reference counts.");}
    private ArrayList<ContextRef> safeRecent(Row r){try{return recentContext(r);}catch(Throwable e){return new ArrayList<>();}}
    private static String proposalClip(String s,int n){String x=s==null?"":s.replaceAll("\\s+"," ").trim();return x.length()>n?x.substring(0,n)+"…":x;}
    private static String ppNz(String s){return s==null?"":s.trim();}
}
