package com.kareem.cortex;

import android.content.Intent;
import android.graphics.Color;
import android.text.InputType;
import android.view.*;
import android.widget.*;
import java.util.ArrayList;

/** Cortex intelligence surface with grounded answers and executable proposals. */
public final class ProposalAskCortexActivity extends AskCortexActivity {
    @Override void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackground(CortexUi.aurora(this));root.addView(header());
        modeBar=new LinearLayout(this);modeBar.setOrientation(LinearLayout.HORIZONTAL);modeBar.setPadding(dp(18),dp(4),dp(18),0);addMode("Your data","your_data");addMode("External","external");addMode("Combined","combined");root.addView(modeBar,new LinearLayout.LayoutParams(-1,dp(44)));
        modeNote=CortexUi.plain(this,"Combined · Cortex context + configured external AI, with local fallback",9,CortexUi.MUTED);modeNote.setPadding(dp(19),dp(2),dp(18),dp(4));root.addView(modeNote,new LinearLayout.LayoutParams(-1,dp(29)));contextNote=CortexUi.text(this,"",10,CortexUi.ORANGE);contextNote.setPadding(dp(18),dp(4),dp(18),dp(6));contextNote.setVisibility(View.GONE);root.addView(contextNote);styleModes();
        scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);conversation=new LinearLayout(this);conversation.setOrientation(LinearLayout.VERTICAL);conversation.setPadding(dp(18),dp(8),dp(18),dp(18));scroll.addView(conversation);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));suggestions();
        LinearLayout composer=CortexUi.card(this,26);composer.setOrientation(LinearLayout.HORIZONTAL);composer.setGravity(Gravity.CENTER_VERTICAL);composer.setPadding(dp(8),dp(7),dp(7),dp(7));composer.addView(CortexUi.glyph(this,"brain",CortexUi.BRAND,true),new LinearLayout.LayoutParams(dp(42),dp(42)));input=new EditText(this);input.setHint("Ask Cortex anything about your world…");input.setHintTextColor(CortexUi.FAINT);input.setTextColor(CortexUi.TEXT);input.setTextSize(14);input.setMinLines(1);input.setMaxLines(4);input.setSingleLine(false);input.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_MULTI_LINE|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);input.setPadding(dp(10),dp(10),dp(8),dp(10));input.setBackgroundColor(Color.TRANSPARENT);composer.addView(input,new LinearLayout.LayoutParams(0,-2,1));send=CortexUi.action(this,"Ask",CortexUi.BRAND,true);LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(72),dp(46));sp.setMargins(dp(6),0,0,0);composer.addView(send,sp);send.setOnClickListener(v->submit());LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(dp(18),dp(5),dp(18),dp(4));root.addView(composer,cp);CortexUi.addBottomNav(this,root,"cortex",null);setContentView(root);
    }

    View header(){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(20),dp(16),dp(18),dp(8));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);TextView eye=CortexUi.plain(this,"COGNITIVE INTERFACE",10,CortexUi.BRAND);CortexUi.medium(eye);if(android.os.Build.VERSION.SDK_INT>=21)eye.setLetterSpacing(.15f);tx.addView(eye);TextView c=CortexUi.plain(this,"Ask Cortex",32,CortexUi.TEXT);CortexUi.bold(c);tx.addView(c);TextView sub=CortexUi.plain(this,"Grounded in your memory. Ready to reason and act.",11,CortexUi.MUTED);sub.setPadding(0,dp(2),0,0);tx.addView(sub);row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));TextView orb=CortexUi.plain(this,"●",24,CortexUi.BRAND);orb.setGravity(Gravity.CENTER);orb.setBackground(CortexUi.round(this,Color.argb(30,Color.red(CortexUi.BRAND),Color.green(CortexUi.BRAND),Color.blue(CortexUi.BRAND)),Color.argb(100,Color.red(CortexUi.BRAND),Color.green(CortexUi.BRAND),Color.blue(CortexUi.BRAND)),999));row.addView(orb,new LinearLayout.LayoutParams(dp(48),dp(48)));CortexGlyphView settings=CortexUi.glyph(this,"settings",CortexUi.MUTED,false);settings.setOnClickListener(v->{try{startActivity(new Intent(this,SettingsActivity.class));}catch(Throwable ignored){}});LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(dp(46),dp(46));sp.setMargins(dp(7),0,0,0);row.addView(settings,sp);return row;}

    @Override void styleModes(){if(modeBar==null)return;for(int i=0;i<modeBar.getChildCount();i++){TextView t=(TextView)modeBar.getChildAt(i);boolean on=sourceMode.equals(t.getTag());String key=(String)t.getTag();int color="your_data".equals(key)?CortexUi.GREEN:"external".equals(key)?CortexUi.AURORA:CortexUi.BRAND;t.setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);int wash=on?Color.argb(30,Color.red(color),Color.green(color),Color.blue(color)):Color.argb(8,255,255,255);t.setBackground(CortexUi.round(this,wash,on?Color.argb(88,Color.red(color),Color.green(color),Color.blue(color)):CortexUi.BORDER_SOFT,999));if(on)CortexUi.medium(t);}if(modeNote!=null){if("combined".equals(sourceMode))modeNote.setText("Combined · Cortex memory + external reasoning, with local fallback");else if("external".equals(sourceMode))modeNote.setText("External intelligence only · Cortex memory stays private");else modeNote.setText("Private Cortex data only · fully grounded in your local memory");}}

    @Override void addSuggestion(String s){LinearLayout card=CortexUi.card(this,20);card.setOrientation(LinearLayout.HORIZONTAL);card.setGravity(Gravity.CENTER_VERTICAL);card.setPadding(dp(9),dp(7),dp(12),dp(7));card.addView(CortexUi.glyph(this,"brain",CortexUi.AURORA,false),new LinearLayout.LayoutParams(dp(36),dp(36)));TextView c=CortexUi.plain(this,s,12,CortexUi.TEXT);c.setGravity(Gravity.CENTER_VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,dp(42),1);xp.setMargins(dp(9),0,0,0);card.addView(c,xp);TextView go=CortexUi.plain(this,"›",22,CortexUi.BRAND);go.setGravity(Gravity.CENTER);card.addView(go,new LinearLayout.LayoutParams(dp(28),dp(38)));card.setOnClickListener(v->{if(destroyed)return;input.setText(s);input.setSelection(input.length());submit();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,0,0,dp(8));conversation.addView(card,p);}

    @Override void addUser(String q){String shown=q==null?"":q.trim();if(focalItemId>0&&shown.length()>420){String title="attached Cortex item";try{KnowledgeItem k=db==null?null:db.getById(focalItemId);if(k!=null&&k.title!=null&&!k.title.trim().isEmpty())title=proposalClip(k.title,72);}catch(Throwable ignored){}shown="Analyze attached Cortex context · "+title;}else if(shown.length()>900)shown=proposalClip(shown,900);LinearLayout wrap=new LinearLayout(this);wrap.setGravity(Gravity.RIGHT);TextView bubble=CortexUi.text(this,shown,14,CortexUi.TEXT);bubble.setPadding(dp(15),dp(12),dp(15),dp(12));bubble.setBackground(CortexUi.gradient(this,Color.argb(58,Color.red(CortexUi.BRAND),Color.green(CortexUi.BRAND),Color.blue(CortexUi.BRAND)),Color.argb(26,Color.red(CortexUi.AURORA),Color.green(CortexUi.AURORA),Color.blue(CortexUi.AURORA)),Color.argb(84,Color.red(CortexUi.BRAND),Color.green(CortexUi.BRAND),Color.blue(CortexUi.BRAND)),20));CortexUi.raised(this,bubble,4);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(dp(42),dp(14),0,dp(10));wrap.addView(bubble,p);conversation.addView(wrap);}

    @Override TextView thinking(String s){TextView t=CortexUi.plain(this,s,11,CortexUi.MUTED);t.setPadding(dp(13),dp(10),dp(13),dp(10));t.setBackground(CortexUi.velvet(this,16));CortexUi.raised(this,t,3);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,-2);p.setMargins(0,0,dp(48),dp(8));conversation.addView(t,p);return t;}

    @Override void addStructuredActions(LinearLayout card,LocalAskRouter.Result r){if(db==null||r.jobId<=0||"your_data".equals(r.sourceMode))return;ArrayList<BrainActionStore.Action> xs;try{xs=BrainActionStore.list(db,r.jobId);}catch(Throwable e){return;}if(xs.isEmpty())return;TextView head=CortexUi.plain(this,"Suggested next actions",10,CortexUi.MUTED);CortexUi.medium(head);head.setPadding(0,dp(14),0,dp(7));card.addView(head);for(BrainActionStore.Action x:xs){int color=actionColor(x.type);LinearLayout row=CortexUi.card(this,18);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(8),dp(7),dp(10),dp(7));row.addView(CortexUi.glyph(this,actionGlyph(x.type),color,!x.ready()),new LinearLayout.LayoutParams(dp(40),dp(40)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(9),0,dp(7),0);row.addView(tx,xp);TextView title=CortexUi.text(this,x.title,12,CortexUi.TEXT);CortexUi.medium(title);title.setMaxLines(2);tx.addView(title);TextView state=CortexUi.plain(this,x.ready()?"Ready":"Needs details",9,x.ready()?CortexUi.MUTED:color);state.setPadding(0,dp(3),0,0);tx.addView(state);row.addView(CortexUi.chip(this,x.ready()?"READY":"DETAILS",color,false),new LinearLayout.LayoutParams(-2,dp(30)));row.setOnClickListener(v->CortexActionDispatcher.preview(this,db,x));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,0);card.addView(row,p);}TextView trust=CortexUi.plain(this,"Validated locally. External changes always open as a preview/draft before confirmation.",9,CortexUi.FAINT);trust.setPadding(0,dp(7),0,0);card.addView(trust);}

    private String actionGlyph(String type){if("CALENDAR_EVENT".equals(type)||"CALENDAR_RESCHEDULE".equals(type)||"REMINDER".equals(type)||"WAIT_FOR".equals(type))return"clock";if("CALL".equals(type))return"phone";if("MESSAGE_DRAFT".equals(type)||"EMAIL_DRAFT".equals(type))return"note";if("PROJECT_LINK".equals(type))return"project";if("WEB_SEARCH".equals(type))return"search";if("TASK".equals(type))return"check";return"action";}
    private int actionColor(String type){if("WAIT_FOR".equals(type)||"REMINDER".equals(type))return CortexUi.ORANGE;if("CALENDAR_EVENT".equals(type)||"CALENDAR_RESCHEDULE".equals(type))return CortexUi.YELLOW;if("PROJECT_LINK".equals(type)||"TASK".equals(type)||"KNOWLEDGE_NOTE".equals(type))return CortexUi.GREEN;return CortexUi.BRAND;}

    @Override void addAnswer(LocalAskRouter.Result r,String q,boolean refined){int before=conversation==null?0:conversation.getChildCount();super.addAnswer(r,q,refined);if(conversation==null||db==null||r==null||conversation.getChildCount()<=before)return;LinearLayout answerCard=null;for(int i=conversation.getChildCount()-1;i>=before;i--){View v=conversation.getChildAt(i);if(v instanceof LinearLayout){answerCard=(LinearLayout)v;break;}}if(answerCard==null)return;answerCard.setPadding(dp(15),dp(14),dp(15),dp(14));answerCard.setBackground(CortexUi.velvet(this,24));CortexUi.raised(this,answerCard,5);if(answerCard.getChildCount()>0&&answerCard.getChildAt(0) instanceof LinearLayout){LinearLayout labelRow=(LinearLayout)answerCard.getChildAt(0);labelRow.setGravity(Gravity.CENTER_VERTICAL);CortexGlyphView icon=CortexUi.glyph(this,"brain",CortexUi.BRAND,true);labelRow.addView(icon,0,new LinearLayout.LayoutParams(dp(38),dp(38)));if(labelRow.getChildCount()>1){View text=labelRow.getChildAt(1);if(text!=null){ViewGroup.LayoutParams raw=text.getLayoutParams();if(raw instanceof LinearLayout.LayoutParams)((LinearLayout.LayoutParams)raw).setMargins(dp(8),0,0,0);}}}String safeAnswer=r.answer==null||r.answer.trim().isEmpty()||"null".equalsIgnoreCase(r.answer.trim())?"Cortex did not receive a usable answer from the model.":r.answer;boolean cloudAllowed=!"your_data".equals(r.sourceMode);long sourceId="combined".equals(r.sourceMode)?Math.max(0,focalItemId):0;String title=q==null||q.trim().isEmpty()?"Cortex answer":"Cortex · "+proposalClip(q,72);ResultProposalEngine.Target target=new ResultProposalEngine.Target("Cortex answer","cortex_"+(r.jobId>0?r.jobId:System.nanoTime()),title,safeAnswer,sourceId,"CORTEX_RESULT",cloudAllowed);ProposalUi.attach(this,db,answerCard,target);}

    private static String proposalClip(String s,int n){String x=s==null?"":s.replaceAll("\\s+"," ").trim();return x.length()>n?x.substring(0,n)+"…":x;}
}
