package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** v50 focus surface: calm segmented navigation, grouped attention cards and persistent bottom nav. */
public class SmartInboxActivity extends Activity {
    VaultDb db;LinearLayout feed,statsRow,tabs;String mode="needs";TextView tabNeeds,tabInbox,tabWaiting,tabActions,topMore;
    int dp(int x){return CortexUi.dp(this,x);}TextView tv(String s,int sp,int c){TextView v=CortexUi.text(this,s,sp,c);v.setTextIsSelectable(true);return v;}TextView plain(String s,int sp,int c){return CortexUi.plain(this,s,sp,c);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);FeatureStore.ensure(db);String m=getIntent().getStringExtra("mode");if(m!=null&&!m.isEmpty())mode=m;build();refresh();}
    @Override protected void onResume(){super.onResume();if(db!=null)refresh();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);
        LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(14),dp(16),0);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout hs=new LinearLayout(this);hs.setOrientation(LinearLayout.VERTICAL);TextView title=plain("Focus",29,CortexUi.TEXT);CortexUi.medium(title);hs.addView(title);hs.addView(plain("Cortex separates what needs you from what can wait.",11,CortexUi.MUTED));head.addView(hs,new LinearLayout.LayoutParams(0,-2,1));topMore=plain("•••",18,CortexUi.TEXT);topMore.setGravity(Gravity.CENTER);CortexUi.pressable(this,topMore,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER,17));topMore.setOnClickListener(this::showMore);head.addView(topMore,new LinearLayout.LayoutParams(dp(48),dp(48)));body.addView(head);
        statsRow=new LinearLayout(this);statsRow.setOrientation(LinearLayout.HORIZONTAL);LinearLayout.LayoutParams sr=new LinearLayout.LayoutParams(-1,dp(82));sr.setMargins(0,dp(15),0,0);body.addView(statsRow,sr);
        HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);tabs.setPadding(0,dp(12),0,dp(9));hsv.addView(tabs);body.addView(hsv,new LinearLayout.LayoutParams(-1,dp(56)));
        tabNeeds=tab("Needs","needs");tabInbox=tab("Inbox","inbox");tabWaiting=tab("Waiting","waiting");tabActions=tab("Actions","action");
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,0,0,dp(18));sv.addView(feed);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        CortexUi.addBottomNav(this,root,"inbox",()->showMore(topMore));setContentView(root);}

    TextView tab(String label,String key){TextView t=CortexUi.chip(this,label,CortexUi.MUTED,false);t.setGravity(Gravity.CENTER);t.setOnClickListener(v->{mode=key;refresh();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(36));p.setMargins(0,0,dp(8),0);tabs.addView(t,p);return t;}
    void styleTabs(){TextView[] bs={tabNeeds,tabInbox,tabWaiting,tabActions};String[] ks={"needs","inbox","waiting","action"};for(int i=0;i<bs.length;i++){boolean on=ks[i].equals(mode);bs[i].setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);if(on)CortexUi.medium(bs[i]);bs[i].setBackground(CortexUi.round(this,on?Color.rgb(52,39,30):CortexUi.SURFACE,on?CortexUi.COPPER:CortexUi.BORDER_SOFT,999));}}

    void refresh(){int needs=FeatureStore.needsCount(db),inbox=FeatureStore.inbox(db,500).size(),waiting=countBucket("Waiting"),actions=countBucket("Action");statsRow.removeAllViews();addMetric("Needs",needs,CortexUi.CORAL,0,()->{mode="needs";refresh();});addMetric("Waiting",waiting,CortexUi.GOLD,8,()->{mode="waiting";refresh();});addMetric("Actions",actions,CortexUi.SAGE,8,()->{mode="action";refresh();});styleTabs();feed.removeAllViews();ArrayList<FeatureStore.InboxEntry> xs=entries();if(xs.isEmpty()){emptyState();return;}if("needs".equals(mode)){ArrayList<FeatureStore.InboxEntry> urgent=new ArrayList<>(),high=new ArrayList<>(),review=new ArrayList<>();for(FeatureStore.InboxEntry e:xs){if(e.score>=100)urgent.add(e);else if(e.score>=70)high.add(e);else review.add(e);}addGroup("Urgent now",urgent,CortexUi.CORAL);addGroup("High priority",high,CortexUi.GOLD);addGroup("Needs review",review,CortexUi.COPPER);}else{TextView section=CortexUi.section(this,sectionName());section.setPadding(0,dp(4),0,dp(9));feed.addView(section);for(FeatureStore.InboxEntry e:xs)addEntry(e);} }
    void addMetric(String label,int value,int color,int left,Runnable open){LinearLayout c=CortexUi.card(this,19);c.setPadding(dp(13),dp(11),dp(13),dp(10));CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,19));TextView n=plain(String.valueOf(value),23,color);CortexUi.medium(n);c.addView(n);c.addView(plain(label,10,CortexUi.MUTED));c.setOnClickListener(v->open.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(left),0,0,0);statsRow.addView(c,p);}String sectionName(){if("waiting".equals(mode))return"Waiting on something";if("action".equals(mode))return"Open actions";return"Inbox";}
    int countBucket(String bucket){LinkedHashSet<Long> ids=new LinkedHashSet<>();for(FeatureStore.InboxEntry e:FeatureStore.needs(db,400))if(bucket.equals(e.bucket))ids.add(e.item.id);for(FeatureStore.InboxEntry e:FeatureStore.inbox(db,400))if(bucket.equals(e.bucket))ids.add(e.item.id);return ids.size();}

    ArrayList<FeatureStore.InboxEntry> entries(){if("needs".equals(mode))return FeatureStore.needs(db,150);if("inbox".equals(mode))return FeatureStore.inbox(db,150);String bucket="waiting".equals(mode)?"Waiting":"Action";LinkedHashMap<Long,FeatureStore.InboxEntry> map=new LinkedHashMap<>();for(FeatureStore.InboxEntry e:FeatureStore.needs(db,300))if(bucket.equals(e.bucket))map.put(e.item.id,e);for(FeatureStore.InboxEntry e:FeatureStore.inbox(db,300))if(bucket.equals(e.bucket))map.put(e.item.id,e);return new ArrayList<>(map.values());}
    void addGroup(String title,ArrayList<FeatureStore.InboxEntry> xs,int color){if(xs.isEmpty())return;LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(dp(2),dp(10),0,dp(8));TextView dot=plain("●",9,color);row.addView(dot,new LinearLayout.LayoutParams(dp(18),-2));TextView h=plain(title.toUpperCase(Locale.US),11,CortexUi.MUTED);CortexUi.medium(h);h.setLetterSpacing(.07f);row.addView(h,new LinearLayout.LayoutParams(0,-2,1));row.addView(plain(String.valueOf(xs.size()),10,color));feed.addView(row);for(FeatureStore.InboxEntry e:xs)addEntry(e);}

    void emptyState(){LinearLayout box=CortexUi.card(this,22);box.setGravity(Gravity.CENTER);box.setPadding(dp(20),dp(42),dp(20),dp(42));TextView icon=plain("✓",29,CortexUi.SAGE);icon.setGravity(Gravity.CENTER);box.addView(icon);TextView h=plain(emptyTitle(),18,CortexUi.TEXT);CortexUi.medium(h);h.setGravity(Gravity.CENTER);h.setPadding(0,dp(7),0,0);box.addView(h);TextView b=tv(emptyMessage(),12,CortexUi.MUTED);b.setGravity(Gravity.CENTER);b.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);b.setPadding(0,dp(6),0,0);box.addView(b);feed.addView(box);}String emptyTitle(){if("needs".equals(mode))return"Nothing needs you right now";if("waiting".equals(mode))return"Nothing waiting";if("action".equals(mode))return"No open actions";return"Inbox clear";}String emptyMessage(){if("needs".equals(mode))return"Cortex will surface anything urgent, due, waiting or unresolved here.";if("waiting".equals(mode))return"Pending results and replies will appear here.";if("action".equals(mode))return"Detected tasks will appear here automatically.";return"New captures stay here until Cortex or you sorts them.";}

    void addEntry(FeatureStore.InboxEntry e){ArrayList<String> rawActs=FeatureStore.openActions(db,e.item.id);ArrayList<String> acts=InboxPresentation.actionParts(rawActs);LinearLayout c=CortexUi.card(this,22);c.setPadding(dp(16),dp(15),dp(16),dp(13));CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,22));c.setOnClickListener(v->detail(e));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.TOP);TextView t=tv(InboxPresentation.title(e.item,rawActs),16,CortexUi.TEXT);CortexUi.medium(t);t.setMaxLines(2);t.setEllipsize(android.text.TextUtils.TruncateAt.END);head.addView(t,new LinearLayout.LayoutParams(0,-2,1));if(e.score>0){TextView pri=CortexUi.chip(this,FeatureStore.priorityLabel(e.score),priorityColor(e.score),true);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-2,dp(27));pp.setMargins(dp(8),0,0,0);head.addView(pri,pp);}c.addView(head);
        TextView meta=plain(e.bucket+"  •  "+friendlyType(e.item.type)+"  •  "+age(e.item.createdAt),10,CortexUi.MUTED);meta.setPadding(0,dp(5),0,0);c.addView(meta);addReasonChips(c,e);String p=InboxPresentation.preview(e.item,rawActs);if(!empty(p)){TextView body=tv(p,13,CortexUi.TEXT);body.setPadding(0,dp(10),0,0);body.setMaxLines(4);c.addView(body);}if(!acts.isEmpty())addActionRows(c,acts,InboxPresentation.due(rawActs));
        LinearLayout footer=new LinearLayout(this);footer.setOrientation(LinearLayout.HORIZONTAL);footer.setGravity(Gravity.CENTER_VERTICAL);footer.setPadding(0,dp(12),0,0);TextView primary=CortexUi.action(this,acts.isEmpty()?"Clear":"Done",acts.isEmpty()?CortexUi.MUTED:CortexUi.SAGE,false),snooze=CortexUi.action(this,"Snooze",CortexUi.MUTED,false),more=CortexUi.action(this,"•••",CortexUi.MUTED,false);addControl(footer,primary,0,1);addControl(footer,snooze,7,1);LinearLayout.LayoutParams mp=new LinearLayout.LayoutParams(dp(48),dp(43));mp.setMargins(dp(7),0,0,0);footer.addView(more,mp);c.addView(footer);
        primary.setOnClickListener(v->{if(acts.isEmpty())FeatureStore.dismissAttention(db,e.item.id);else FeatureStore.markDone(db,e.item.id);Toast.makeText(this,acts.isEmpty()?"Cleared":"Action closed",Toast.LENGTH_SHORT).show();refresh();});snooze.setOnClickListener(v->snooze(e));more.setOnClickListener(v->moreMenu(e,more));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(10));feed.addView(c,cp);}

    void addReasonChips(LinearLayout parent,FeatureStore.InboxEntry e){if(empty(e.reason)&&!e.pinned)return;HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);ArrayList<String> labels=new ArrayList<>();if(!empty(e.reason)){for(String x:e.reason.split("•")){String v=reasonLabel(x.trim());if(!empty(v)&&!labels.contains(v))labels.add(v);}}if(e.pinned&&!labels.contains("Pinned"))labels.add("Pinned");for(String x:labels){TextView ch=CortexUi.chip(this,x,chipColor(x),false);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(27));p.setMargins(0,0,dp(6),0);row.addView(ch,p);}hsv.addView(row);LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,dp(33));hp.setMargins(0,dp(8),0,0);parent.addView(hsv,hp);}String reasonLabel(String x){String l=x.toLowerCase(Locale.US);if(l.contains("open action"))return x.replace("open action","action");if(l.contains("due date"))return"Due";if(l.contains("follow-up"))return"Follow-up";if(l.contains("pinned"))return"Pinned";if(l.contains("waiting"))return"Waiting";if(l.contains("failed"))return"Needs retry";return x;}int chipColor(String x){String l=x.toLowerCase(Locale.US);if(l.contains("due")||l.contains("follow"))return CortexUi.GOLD;if(l.contains("retry"))return CortexUi.CORAL;if(l.contains("pinned"))return CortexUi.COPPER;if(l.contains("action"))return CortexUi.SAGE;return CortexUi.MUTED;}
    void addActionRows(LinearLayout parent,ArrayList<String> acts,String due){TextView h=CortexUi.section(this,"Open actions");h.setTextColor(CortexUi.COPPER);h.setPadding(0,dp(12),0,dp(5));parent.addView(h);for(String a:acts){LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setGravity(Gravity.TOP);TextView box=plain("□",18,CortexUi.COPPER);box.setGravity(Gravity.TOP);row.addView(box,new LinearLayout.LayoutParams(dp(27),dp(34)));TextView body=tv(a,13,CortexUi.TEXT);body.setPadding(dp(2),0,0,dp(6));row.addView(body,new LinearLayout.LayoutParams(0,-2,1));parent.addView(row);}if(!empty(due)){TextView d=CortexUi.chip(this,"Due  "+due,CortexUi.GOLD,false);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(28));p.setMargins(0,dp(4),0,0);parent.addView(d,p);}}
    void addControl(LinearLayout row,View v,int left,int weight){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(43),weight);p.setMargins(dp(left),0,0,0);row.addView(v,p);}

    void moreMenu(FeatureStore.InboxEntry e,View anchor){PopupMenu p=new PopupMenu(this,anchor);p.getMenu().add(e.pinned?"Unpin":"Pin");p.getMenu().add("Move bucket");if("failed_retryable".equals(e.item.status)||"analysis_failed".equals(e.item.status))p.getMenu().add("Re-analyze");p.getMenu().add("Clear from attention");p.setOnMenuItemClickListener(m->{String x=m.getTitle().toString();if("Pin".equals(x)){FeatureStore.pin(db,e.item.id,true);refresh();}else if("Unpin".equals(x)){FeatureStore.pin(db,e.item.id,false);refresh();}else if("Move bucket".equals(x))chooseBucket(e);else if("Re-analyze".equals(x))reanalyze(e.item);else{FeatureStore.dismissAttention(db,e.item.id);refresh();}return true;});p.show();}
    void snooze(FeatureStore.InboxEntry e){String[] x={"3 hours","Tomorrow","3 days","7 days"};new AlertDialog.Builder(this).setTitle("Snooze").setItems(x,(d,w)->{long now=System.currentTimeMillis(),until;if(w==0)until=now+3L*60*60*1000;else if(w==1)until=now+24L*60*60*1000;else if(w==2)until=now+3L*24*60*60*1000;else until=now+7L*24*60*60*1000;FeatureStore.snooze(db,e.item.id,until);Toast.makeText(this,"Snoozed until "+fmt(until),Toast.LENGTH_LONG).show();refresh();}).setNegativeButton("Cancel",null).show();}
    void chooseBucket(FeatureStore.InboxEntry e){String[] b={"Action","Waiting","Decision","Project","Person","Reference","Needs attention"};new AlertDialog.Builder(this).setTitle("Move to bucket").setItems(b,(d,w)->{FeatureStore.setBucket(db,e.item.id,b[w]);Toast.makeText(this,"Moved to "+b[w],Toast.LENGTH_SHORT).show();refresh();}).setNegativeButton("Cancel",null).show();}
    void reanalyze(KnowledgeItem k){FeatureStore.resetAttention(db,k.id);db.retry(k.id);Toast.makeText(this,"Re-analyzing…",Toast.LENGTH_SHORT).show();AnalysisQueue.kick(this,db,()->runOnUiThread(this::refresh));refresh();}
    void detail(FeatureStore.InboxEntry e){KnowledgeItem k=db.getById(e.item.id);if(k==null)return;ScrollView sv=new ScrollView(this);LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(18),dp(8),dp(18),dp(18));box.setBackgroundColor(CortexUi.BG);sv.addView(box);addReasonChips(box,e);ArrayList<String> raw=FeatureStore.openActions(db,k.id),acts=InboxPresentation.actionParts(raw);if(!acts.isEmpty())addActionRows(box,acts,InboxPresentation.due(raw));label(box,"What Cortex understood");box.addView(tv(empty(e.reason)?e.bucket:e.reason,13,CortexUi.TEXT));if(!empty(k.summary)){label(box,"Summary");box.addView(tv(k.summary,14,CortexUi.TEXT));}if(!empty(k.extractedText)){label(box,"Transcript");String x=k.extractedText;if(x.length()>6000)x=x.substring(0,6000)+"…";box.addView(tv(x,13,CortexUi.MUTED));}label(box,"State");box.addView(plain("Bucket: "+e.bucket+"\nPriority: "+FeatureStore.priorityLabel(e.score)+"\nStatus: "+k.status+"\nCaptured: "+fmt(k.createdAt),11,CortexUi.MUTED));new AlertDialog.Builder(this).setTitle(InboxPresentation.title(k,raw)).setView(sv).setNegativeButton("Close",null).show();}
    void label(LinearLayout p,String s){TextView h=CortexUi.section(this,s);h.setTextColor(CortexUi.COPPER);p.addView(h);}void showMore(View anchor){PopupMenu p=new PopupMenu(this,anchor);p.getMenu().add("Capture something");p.getMenu().add("Brain & context");p.getMenu().add("Environment & Local AI");p.getMenu().add("Full app audit");p.setOnMenuItemClickListener(m->{String s=m.getTitle().toString();if(s.startsWith("Capture"))startActivity(new Intent(this,MainActivity.class));else if(s.startsWith("Brain"))startActivity(new Intent(this,BrainActivity.class));else if(s.startsWith("Environment"))startActivity(new Intent(this,EnvironmentActivity.class));else startActivity(new Intent(this,CortexAuditActivity.class));return true;});p.show();}
    int priorityColor(int score){if(score>=100)return CortexUi.CORAL;if(score>=70)return CortexUi.GOLD;if(score>=45)return CortexUi.COPPER;return CortexUi.MUTED;}String friendlyType(String s){if("AUDIO".equals(s))return"Voice";if("SCREENSHOT".equals(s)||"IMAGE".equals(s))return"Image";return s==null?"Memory":s;}String age(long ms){long d=Math.max(0,System.currentTimeMillis()-ms);long h=d/(60*60*1000);if(h<1)return"just now";if(h<24)return h+"h ago";return h/24+"d ago";}String fmt(long ms){return new SimpleDateFormat("dd MMM • HH:mm",Locale.getDefault()).format(new Date(ms));}boolean empty(String s){return s==null||s.trim().isEmpty();}
    @Override protected void onDestroy(){super.onDestroy();if(db!=null)db.close();}
}
