package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.os.Bundle;
import android.text.TextUtils;
import android.view.*;
import android.widget.*;
import java.text.SimpleDateFormat;
import java.util.*;

/** Focus is intentionally only three views: Needs, Waiting and Actions. */
public class SmartInboxActivity extends Activity {
    VaultDb db;LinearLayout feed,tabs;TextView tabNeeds,tabWaiting,tabActions,needsCount,waitingCount,actionsCount;String mode="needs";volatile int generation=0;
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);FeatureStore.ensure(db);String m=getIntent().getStringExtra("mode");if("waiting".equals(m)||"action".equals(m)||"needs".equals(m))mode=m;build();refreshAsync();}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);String m=i.getStringExtra("mode");if("waiting".equals(m)||"action".equals(m)||"needs".equals(m))mode=m;refreshAsync();}
    @Override protected void onResume(){super.onResume();if(db!=null)refreshAsync();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),0);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Focus",29,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);titles.addView(CortexUi.plain(this,"Only things that require a decision, action or wait",11,CortexUi.MUTED));head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView settings=CortexUi.chip(this,"SETTINGS",CortexUi.MUTED,false);settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));head.addView(settings,new LinearLayout.LayoutParams(-2,dp(36)));body.addView(head);

        LinearLayout stats=new LinearLayout(this);stats.setOrientation(LinearLayout.HORIZONTAL);needsCount=metric(stats,"Needs",0);waitingCount=metric(stats,"Waiting",8);actionsCount=metric(stats,"Actions",8);LinearLayout.LayoutParams stp=new LinearLayout.LayoutParams(-1,dp(82));stp.setMargins(0,dp(16),0,0);body.addView(stats,stp);
        tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);tabs.setPadding(0,dp(14),0,dp(10));tabNeeds=tab("Needs","needs");tabWaiting=tab("Waiting","waiting");tabActions=tab("Actions","action");body.addView(tabs,new LinearLayout.LayoutParams(-1,dp(58)));
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,0,0,dp(20));sv.addView(feed);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"focus",null);setContentView(root);styleTabs();}

    TextView metric(LinearLayout row,String label,int left){LinearLayout c=CortexUi.card(this,18);c.setPadding(dp(12),dp(10),dp(12),dp(9));TextView n=CortexUi.plain(this,"—",22,CortexUi.TEXT);CortexUi.medium(n);c.addView(n);c.addView(CortexUi.plain(this,label,10,CortexUi.MUTED));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(left),0,0,0);row.addView(c,p);return n;}
    TextView tab(String label,String key){TextView t=CortexUi.chip(this,label,CortexUi.MUTED,false);t.setOnClickListener(v->{if(key.equals(mode))return;mode=key;styleTabs();refreshAsync();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(38),1);p.setMargins(0,0,dp("action".equals(key)?0:8),0);tabs.addView(t,p);return t;}
    void styleTabs(){TextView[] x={tabNeeds,tabWaiting,tabActions};String[] k={"needs","waiting","action"};for(int i=0;i<x.length;i++){boolean on=k[i].equals(mode);x[i].setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);x[i].setBackground(CortexUi.round(this,on?CortexUi.SURFACE_2:CortexUi.SURFACE,on?CortexUi.ACCENT:CortexUi.BORDER_SOFT,999));if(on)CortexUi.medium(x[i]);}}

    void refreshAsync(){final int g=++generation;new Thread(()->{try{ArrayList<FeatureStore.InboxEntry> needs=FeatureStore.needs(db,120),inbox=FeatureStore.inbox(db,140);LinkedHashMap<Long,FeatureStore.InboxEntry> waiting=new LinkedHashMap<>(),actions=new LinkedHashMap<>();mergeBucket(waiting,needs,"Waiting");mergeBucket(waiting,inbox,"Waiting");mergeBucket(actions,needs,"Action");mergeBucket(actions,inbox,"Action");ArrayList<FeatureStore.InboxEntry> visible="waiting".equals(mode)?new ArrayList<>(waiting.values()):"action".equals(mode)?new ArrayList<>(actions.values()):needs;runOnUiThread(()->{if(g!=generation||isFinishing())return;needsCount.setText(String.valueOf(needs.size()));waitingCount.setText(String.valueOf(waiting.size()));actionsCount.setText(String.valueOf(actions.size()));render(visible);});}catch(Throwable e){runOnUiThread(()->{if(g==generation)showError(e);});}},"CortexFocusRefresh").start();}
    void mergeBucket(LinkedHashMap<Long,FeatureStore.InboxEntry> out,ArrayList<FeatureStore.InboxEntry> xs,String bucket){for(FeatureStore.InboxEntry e:xs)if(bucket.equals(e.bucket))out.put(e.item.id,e);}

    void render(ArrayList<FeatureStore.InboxEntry> xs){feed.removeAllViews();TextView section=CortexUi.section(this,"needs".equals(mode)?"Needs your attention":"waiting".equals(mode)?"Waiting on":"Open actions");section.setPadding(0,dp(4),0,dp(9));feed.addView(section);if(xs.isEmpty()){emptyState();return;}for(FeatureStore.InboxEntry e:xs)addEntry(e);}
    void emptyState(){LinearLayout c=CortexUi.card(this,24);c.setGravity(Gravity.CENTER);c.setPadding(dp(22),dp(42),dp(22),dp(42));TextView mark=CortexUi.plain(this,"✓",28,CortexUi.SAGE);mark.setGravity(Gravity.CENTER);c.addView(mark);String t="needs".equals(mode)?"Nothing needs you":"waiting".equals(mode)?"Nothing waiting":"No open actions";TextView h=CortexUi.plain(this,t,18,CortexUi.TEXT);CortexUi.medium(h);h.setGravity(Gravity.CENTER);h.setPadding(0,dp(8),0,0);c.addView(h);TextView b=CortexUi.text(this,"Cortex will put something here only when it has a real reason.",12,CortexUi.MUTED);b.setGravity(Gravity.CENTER);b.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);b.setPadding(0,dp(5),0,0);c.addView(b);feed.addView(c);}
    void showError(Throwable e){feed.removeAllViews();LinearLayout c=CortexUi.card(this,22);TextView t=CortexUi.text(this,"Focus could not refresh: "+(e.getMessage()==null?e.getClass().getSimpleName():e.getMessage()),12,CortexUi.MUTED);c.addView(t);feed.addView(c);}

    void addEntry(FeatureStore.InboxEntry e){ArrayList<String> acts=FeatureStore.openActions(db,e.item.id);LinearLayout c=CortexUi.card(this,22);c.setPadding(dp(16),dp(15),dp(16),dp(14));CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,22));TextView title=CortexUi.text(this,clean(e.item.title),16,CortexUi.TEXT);CortexUi.medium(title);title.setMaxLines(2);title.setEllipsize(TextUtils.TruncateAt.END);c.addView(title);TextView meta=CortexUi.plain(this,friendly(e.item.type)+"  •  "+age(e.item.createdAt)+(empty(e.reason)?"":"  •  "+shortReason(e.reason)),10,CortexUi.MUTED);meta.setPadding(0,dp(5),0,0);c.addView(meta);String preview=preview(e.item);if(!empty(preview)){TextView p=CortexUi.text(this,clip(preview,210),13,CortexUi.TEXT);p.setMaxLines(4);p.setPadding(0,dp(10),0,0);c.addView(p);}if(!acts.isEmpty()){TextView ah=CortexUi.plain(this,"OPEN ACTION",10,CortexUi.ACCENT);CortexUi.medium(ah);ah.setPadding(0,dp(12),0,dp(4));c.addView(ah);for(int i=0;i<Math.min(3,acts.size());i++){TextView a=CortexUi.text(this,"• "+acts.get(i),12,CortexUi.TEXT);a.setPadding(0,dp(2),0,dp(2));c.addView(a);}}
        LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.HORIZONTAL);controls.setPadding(0,dp(13),0,0);boolean failed="failed_retryable".equals(e.item.status)||"analysis_failed".equals(e.item.status);TextView primary=CortexUi.action(this,failed?"Retry":acts.isEmpty()?"Clear":"Done",failed?CortexUi.ACCENT:acts.isEmpty()?CortexUi.MUTED:CortexUi.SAGE,false);TextView snooze=CortexUi.action(this,"Snooze 1d",CortexUi.MUTED,false);controls.addView(primary,new LinearLayout.LayoutParams(0,dp(43),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(0,dp(43),1);sp.setMargins(dp(8),0,0,0);controls.addView(snooze,sp);c.addView(controls);primary.setOnClickListener(v->{if(failed){FeatureStore.resetAttention(db,e.item.id);db.retry(e.item.id);AnalysisQueue.kick(this,db,this::refreshAsync);}else if(acts.isEmpty())FeatureStore.dismissAttention(db,e.item.id);else FeatureStore.markDone(db,e.item.id);refreshAsync();});snooze.setOnClickListener(v->{FeatureStore.snooze(db,e.item.id,System.currentTimeMillis()+24L*60*60*1000);refreshAsync();});c.setOnClickListener(v->{Intent i=new Intent(this,VaultActivity.class);i.putExtra("item_id",e.item.id);startActivity(i);});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));feed.addView(c,p);}

    String preview(KnowledgeItem k){if(!empty(k.summary))return k.summary;if(!empty(k.extractedText))return k.extractedText;return k.rawText;}String clean(String s){return empty(s)?"Memory":s.trim();}String shortReason(String s){String x=s.replace(" • "," · ");return x.length()>58?x.substring(0,58)+"…":x;}String friendly(String s){if("AUDIO".equals(s))return"Voice";if("FILE".equals(s))return"File";if("SCREENSHOT".equals(s)||"IMAGE".equals(s))return"Image";return"Memory";}String clip(String s,int n){return s==null?"":s.length()<=n?s:s.substring(0,n)+"…";}boolean empty(String s){return s==null||s.trim().isEmpty();}String age(long ms){long m=Math.max(0,System.currentTimeMillis()-ms)/60000;if(m<1)return"now";if(m<60)return m+"m";long h=m/60;if(h<24)return h+"h";long d=h/24;return d<7?d+"d":new SimpleDateFormat("dd MMM",Locale.getDefault()).format(new Date(ms));}
}
