package com.kareem.cortex;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONObject;

/** Exhaustive v64 architecture checks injected into the single Full Cortex Diagnostic. */
public final class UniversalPipelineDiagnostics {
    private UniversalPipelineDiagnostics(){}
    public static void apply(Context c,VaultDb vault,long runId){SQLiteDatabase db=vault.getWritableDatabase();UniversalEventStore.ensure(db);test(db,runId,"ue_raw_ssot","Universal Event Engine","Immutable raw observation store",rawSsot(db));test(db,runId,"ue_stream_coalescing","Universal Event Engine","Stateful stream coalescing",streams(db));test(db,runId,"ue_semantic_integrity","Universal Event Engine","Semantic event provenance",semantic(db));test(db,runId,"ue_projection_separation","Now / Brief / Capture / Brain","Projection separation",projections(db));test(db,runId,"ue_memory_guard","Brain Memory","Explicit memory promotion guard",memory(db));test(db,runId,"ue_replay_readiness","Replay & Reprocessing","Replay readiness",replay(db));test(db,runId,"ue_synthetic_e2e","Universal Event Engine","Synthetic end-to-end request pipeline",synthetic(c,vault,db));test(db,runId,"ue_pipeline_failures","Universal Event Engine","Pipeline stage failures",failures(db));}

    static final class Check{final String status,severity,detail;final JSONObject evidence;Check(String s,String v,String d,JSONObject e){status=s;severity=v;detail=d;evidence=e;}}
    private static Check rawSsot(SQLiteDatabase db){long raw=q(db,"SELECT COUNT(*) FROM ue_raw_observations"),missing=q(db,"SELECT COUNT(*) FROM ue_raw_observations WHERE COALESCE(payload_json,'')='' OR COALESCE(immutable_hash,'')='' OR occurred_at<=0");JSONObject e=o("raw",raw,"missing_required",missing,"processor",UniversalEventStore.PROCESSOR_VERSION);return new Check(missing==0?"pass":"fail",missing==0?"ok":"error",raw+" immutable raw observation(s); "+missing+" missing required evidence fields",e);}
    private static Check streams(SQLiteDatabase db){long raw=q(db,"SELECT COUNT(*) FROM ue_raw_observations"),streams=q(db,"SELECT COUNT(*) FROM ue_streams"),semantic=q(db,"SELECT COUNT(*) FROM ue_semantic_events WHERE superseded_by=0"),noise=q(db,"SELECT COUNT(*) FROM ue_pipeline_stages WHERE stage='COALESCED' AND detail LIKE '%no new semantic event%'");boolean ok=streams<=raw||raw==0;JSONObject e=o("raw",raw,"streams",streams,"semantic",semantic,"coalesced_noise",noise);return new Check(ok?"pass":"fail",ok?"ok":"error","raw="+raw+" • streams="+streams+" • semantic="+semantic+" • coalesced noise="+noise,e);}
    private static Check semantic(SQLiteDatabase db){long total=q(db,"SELECT COUNT(*) FROM ue_semantic_events"),orphanRaw=q(db,"SELECT COUNT(*) FROM ue_semantic_events e LEFT JOIN ue_raw_observations r ON r.id=e.raw_observation_id WHERE r.id IS NULL"),orphanStream=q(db,"SELECT COUNT(*) FROM ue_semantic_events e LEFT JOIN ue_streams s ON s.id=e.stream_id WHERE s.id IS NULL"),waiting=q(db,"SELECT COUNT(*) FROM ue_semantic_events WHERE semantic_state='waiting' AND superseded_by=0");boolean ok=orphanRaw==0&&orphanStream==0;return new Check(ok?"pass":"fail",ok?"ok":"error",total+" semantic event(s) • orphan raw="+orphanRaw+" • orphan stream="+orphanStream+" • waiting model="+waiting,o("total",total,"orphan_raw",orphanRaw,"orphan_stream",orphanStream,"waiting",waiting));}
    private static Check projections(SQLiteDatabase db){long badAttention=q(db,"SELECT COUNT(*) FROM ue_attention_items a LEFT JOIN ue_semantic_events e ON e.id=a.semantic_event_id WHERE e.id IS NULL"),legacyArtifacts=q(db,"SELECT COUNT(*) FROM ue_legacy_classification WHERE classification='captured_artifact'"),promotedArtifacts=q(db,"SELECT COUNT(*) FROM ue_legacy_classification l JOIN ue_memory_promotions m ON m.knowledge_item_id=l.knowledge_item_id AND m.state='promoted' WHERE l.classification='captured_artifact'"),open=q(db,"SELECT COUNT(*) FROM ue_attention_items WHERE state='open'");boolean ok=badAttention==0;return new Check(ok?"pass":"fail",ok?"ok":"error","Now attention="+open+" • capture artifacts="+legacyArtifacts+" • explicitly promoted artifacts="+promotedArtifacts+" • orphan attention="+badAttention,o("open_attention",open,"capture_artifacts",legacyArtifacts,"promoted_artifacts",promotedArtifacts,"orphan_attention",badAttention));}
    private static Check memory(SQLiteDatabase db){long promoted=q(db,"SELECT COUNT(*) FROM ue_memory_promotions WHERE state='promoted'"),bad=q(db,"SELECT COUNT(*) FROM ue_memory_promotions m LEFT JOIN knowledge_items k ON k.id=m.knowledge_item_id WHERE m.state='promoted' AND (k.id IS NULL OR k.source<>'universal_memory')"),start=q(db,"SELECT COALESCE(MIN(created_at),9223372036854775807) FROM ue_raw_observations"),rawNotifMem=q(db,"SELECT COUNT(*) FROM knowledge_items WHERE (source='notification_listener' OR type='NOTIFICATION') AND created_at>"+start);boolean ok=bad==0&&rawNotifMem==0;return new Check(ok?"pass":"fail",ok?"ok":"error",promoted+" explicit semantic memory promotion(s) • invalid="+bad+" • new raw notification memories="+rawNotifMem,o("promoted",promoted,"invalid",bad,"new_raw_notification_memories",rawNotifMem));}
    private static Check replay(SQLiteDatabase db){long raw=q(db,"SELECT COUNT(*) FROM ue_raw_observations"),bad=q(db,"SELECT COUNT(*) FROM ue_raw_observations WHERE COALESCE(payload_json,'')=''"),requests=q(db,"SELECT COUNT(*) FROM ue_reprocess_requests"),revisions=q(db,"SELECT COUNT(*) FROM ue_semantic_events WHERE revision>1");boolean ok=bad==0;return new Check(ok?"pass":"fail",ok?"ok":"error",raw+" raw object(s) replayable • requests="+requests+" • rebuilt revisions="+revisions,o("raw",raw,"missing_payload",bad,"requests",requests,"revisions",revisions));}
    private static Check synthetic(Context context,VaultDb vault,SQLiteDatabase db){boolean started=false;try{db.beginTransaction();started=true;long now=System.currentTimeMillis();JSONObject meta=new JSONObject().put("platform_hint","message").put("notification_kind","message").put("template","android.app.Notification$MessagingStyle").put("notification_key","cortex-audit-synthetic").put("shortcut_id","audit-person").put("conversation_title","Cortex Audit Person");NotificationEventEngine.Result platform=new NotificationEventEngine.Result(900001,900001,900001,"NEW","conversation_notification","message",true);UniversalEventEngine.Result r=UniversalEventEngine.processNotification(context,vault,platform,"cortex.audit.synthetic","Cortex Audit","posted","Cortex Audit Person","Please send me the report urgently",now,meta);boolean raw=r.rawId>0,semantic=r.semanticEventId>0,action=r.attentionId>0,actionType="action_request".equals(r.semanticType),noMemory=r.memoryItemId==0;long compat=r.attentionId>0?UniversalEventStore.ATTENTION_COMPAT_OFFSET+r.attentionId:0;boolean mirror=compat>0&&one(db,"SELECT 1 FROM derived_items WHERE id="+compat+" AND candidate_kind='UE_ATTENTION' LIMIT 1");if(mirror){ContentValues resolved=new ContentValues();resolved.put("state","resolved");resolved.put("updated_at",now+1);db.update("derived_items",resolved,"id=?",new String[]{String.valueOf(compat)});}boolean propagated=r.attentionId>0&&one(db,"SELECT 1 FROM ue_attention_items WHERE id="+r.attentionId+" AND state='resolved' LIMIT 1");boolean ok=raw&&semantic&&action&&actionType&&noMemory&&mirror&&propagated;JSONObject e=o("raw_created",raw,"semantic_created",semantic,"attention_created",action,"semantic_type",r.semanticType,"raw_memory_created",r.memoryItemId,"compat_mirror",mirror,"resolve_propagated",propagated);return new Check(ok?"pass":"fail",ok?"ok":"error",ok?"Synthetic request passed capture → stream → semantic → situation/attention → UI-resolution bridge without raw-memory pollution.":"Synthetic universal pipeline failed one or more boundaries.",e);}catch(Throwable e){return new Check("fail","error","Synthetic universal pipeline threw "+e.getClass().getSimpleName()+": "+String.valueOf(e.getMessage()),o("exception",e.toString()));}finally{if(started)try{db.endTransaction();}catch(Throwable ignored){}}}
    private static Check failures(SQLiteDatabase db){long failed=q(db,"SELECT COUNT(*) FROM ue_pipeline_stages WHERE state='failed'"),waiting=q(db,"SELECT COUNT(*) FROM ue_pipeline_stages WHERE state='waiting'");return new Check(failed==0?"pass":"warn",failed==0?"ok":"warning","Pipeline failures="+failed+" • intentionally waiting semantic stages="+waiting,o("failed",failed,"waiting",waiting));}

    private static void test(SQLiteDatabase db,long runId,String key,String feature,String title,Check x){long now=System.currentTimeMillis();ContentValues v=new ContentValues();v.put("run_id",runId);v.put("test_key",key);v.put("feature",feature);v.put("title",title);v.put("mode","auto");v.put("status",x.status);v.put("passed","pass".equals(x.status)?1:("fail".equals(x.status)?0:-1));v.put("severity",x.severity);v.put("description","Cortex v64 universal-event architecture invariant.");v.put("expected","Raw evidence is preserved and projections remain referentially consistent.");v.put("started_at",now);v.put("finished_at",now);v.put("duration_ms",0);v.put("detail",x.detail);v.put("evidence_json",x.evidence.toString());db.insertWithOnConflict("cortex_audit_tests",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    private static long q(SQLiteDatabase db,String sql){Cursor c=db.rawQuery(sql,null);long n=c.moveToFirst()?c.getLong(0):0;c.close();return n;}private static boolean one(SQLiteDatabase db,String sql){Cursor c=db.rawQuery(sql,null);boolean yes=c.moveToFirst();c.close();return yes;}
    private static JSONObject o(Object... kv){JSONObject x=new JSONObject();try{for(int i=0;i+1<kv.length;i+=2)x.put(String.valueOf(kv[i]),kv[i+1]);}catch(Exception ignored){}return x;}
}
