package com.kareem.cortex;

import android.content.ContentValues;
import android.database.Cursor;
import androidx.annotation.NonNull;
import androidx.work.Worker;
import androidx.work.WorkerParameters;

/** Rebuilds derived semantic interpretation from immutable raw evidence without deleting history. */
public final class UniversalReplayWorker extends Worker {
    public UniversalReplayWorker(@NonNull android.content.Context c,@NonNull WorkerParameters p){super(c,p);}
    @NonNull @Override public Result doWork(){if(StartupSafetyGate.active())return Result.success();long requestId=getInputData().getLong("request_id",0);if(requestId<=0)return Result.failure();VaultDb db=new VaultDb(getApplicationContext());try{UniversalEventStore.ensure(db.getWritableDatabase());Cursor rq=db.getReadableDatabase().rawQuery("SELECT from_at,to_at FROM ue_reprocess_requests WHERE id=? LIMIT 1",new String[]{String.valueOf(requestId)});if(!rq.moveToFirst()){rq.close();return Result.failure();}long from=rq.getLong(0),to=rq.getLong(1);rq.close();long total=UniversalEventStore.scalar(db.getReadableDatabase(),"SELECT COUNT(*) FROM ue_raw_observations WHERE source_type='notification' AND occurred_at BETWEEN ? AND ?",new String[]{String.valueOf(from),String.valueOf(to)});ContentValues start=new ContentValues();start.put("state","running");start.put("total",total);start.put("updated_at",System.currentTimeMillis());db.getWritableDatabase().update("ue_reprocess_requests",start,"id=?",new String[]{String.valueOf(requestId)});Cursor c=db.getReadableDatabase().rawQuery("SELECT id FROM ue_raw_observations WHERE source_type='notification' AND occurred_at BETWEEN ? AND ? ORDER BY id ASC",new String[]{String.valueOf(from),String.valueOf(to)});int processed=0,failed=0;while(c.moveToNext()){if(isStopped()){c.close();return Result.retry();}long raw=c.getLong(0);try{UniversalEventEngine.reprocessNotification(getApplicationContext(),db,raw);processed++;}catch(Throwable e){failed++;}if((processed+failed)%25==0)progress(db,requestId,processed,failed);}c.close();ContentValues done=new ContentValues();done.put("state",failed==0?"complete":"complete_with_errors");done.put("processed",processed);done.put("failed",failed);done.put("updated_at",System.currentTimeMillis());done.put("completed_at",System.currentTimeMillis());db.getWritableDatabase().update("ue_reprocess_requests",done,"id=?",new String[]{String.valueOf(requestId)});return Result.success();}catch(Throwable e){ContentValues v=new ContentValues();v.put("state","failed");v.put("error",String.valueOf(e));v.put("updated_at",System.currentTimeMillis());db.getWritableDatabase().update("ue_reprocess_requests",v,"id=?",new String[]{String.valueOf(requestId)});return Result.failure();}finally{db.close();}}
    private static void progress(VaultDb db,long id,int processed,int failed){ContentValues v=new ContentValues();v.put("processed",processed);v.put("failed",failed);v.put("updated_at",System.currentTimeMillis());db.getWritableDatabase().update("ue_reprocess_requests",v,"id=?",new String[]{String.valueOf(id)});}
}
