package com.kareem.cortex;

import android.content.Context;
import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONObject;
import java.util.Locale;

/**
 * Hybrid universal event understanding pipeline.
 * Deterministic interpretation handles high-confidence cases. Ambiguous events are queued for
 * local semantic reasoning instead of being guessed into memory.
 */
public final class UniversalEventEngine {
    public static final class Result {
        public final long rawId,streamId,semanticEventId,situationId,attentionId,memoryItemId,aiJobId;
        public final String semanticType,intent,state,route,reason;
        Result(long raw,long stream,long sem,long sit,long att,long mem,long job,String type,String i,String st,String r,String why){rawId=raw;streamId=stream;semanticEventId=sem;situationId=sit;attentionId=att;memoryItemId=mem;aiJobId=job;semanticType=n(type);intent=n(i);state=n(st);route=n(r);reason=n(why);}
    }

    private static final String MEMORY_POLICY="memory_promotion_001";
    private UniversalEventEngine(){}

    public static Result processNotification(Context context,VaultDb vault,NotificationEventEngine.Result platform,String pkg,String appLabel,String eventType,String title,String body,long occurredAt,JSONObject metadata){
        SQLiteDatabase db=vault.getWritableDatabase();UniversalEventStore.ensure(db);JSONObject meta=metadata==null?new JSONObject():metadata;String sourceKey=n(pkg),technical=platform==null?n(meta.optString("technical_type","")):platform.technicalType,hint=platform==null?n(meta.optString("platform_hint","")):platform.platformHint;String external=platform==null?Fingerprint.text(sourceKey+"|"+meta.optString("notification_key","")+"|"+meta.optInt("notification_id",0)):String.valueOf(platform.streamId);
        long raw=UniversalEventStore.appendRaw(db,"notification",sourceKey,String.valueOf(platform==null?0:platform.rawId),eventType,hint,technical,title,body,meta,occurredAt);UniversalEventStore.stage(db,raw,0,"CAPTURED","complete","android_notification_listener","Immutable notification observation stored","");
        boolean meaningful=platform!=null&&platform.semanticEventId>0;String hash=Fingerprint.text(title+"\n"+body+"\n"+meta.toString());long stream=UniversalEventStore.upsertStream(db,"notification",external,"removed".equals(eventType)?"removed":"active",hash,title,body,hint,technical,occurredAt,meaningful,meta);UniversalEventStore.stage(db,raw,0,"NORMALIZED","complete","universal_event_engine","Source normalized and attached to stateful stream","");
        if(!meaningful){UniversalEventStore.stage(db,raw,0,"COALESCED","complete","notification_state_coalescer","State update retained as raw evidence; no new semantic event required","");return new Result(raw,stream,0,0,0,0,0,"technical_state","","complete","deterministic","coalesced state/noise update");}

        Interpretation x=interpret(technical,hint,title,body,meta,eventType);String semanticState=x.needsModel?"waiting":"complete";String route=x.needsModel?routeFor(context):"deterministic";long sem=UniversalEventStore.insertSemantic(db,raw,stream,1,x.type,x.intent,x.subject,x.summary,x.confidence,semanticState,true,route,x.reason,occurredAt);UniversalEventStore.stage(db,raw,sem,"COALESCED","complete","notification_state_coalescer","Meaningful transition emitted","");UniversalEventStore.stage(db,raw,sem,"UNDERSTANDING",x.needsModel?"waiting":"complete",route,x.needsModel?"Stored safely; waiting for semantic model pass":"High-confidence deterministic semantic interpretation","");

        String person=extractPerson(title,meta);if(!person.isEmpty()){long entity=UniversalEventStore.entity(db,"PERSON",person,new JSONObject());UniversalEventStore.linkEntity(db,sem,entity,"participant",0.96);}
        long situation=0,attention=0,memory=0,job=0;String situationKey=situationKey(sourceKey,person,x,meta);
        if(x.opensSituation){situation=UniversalEventStore.upsertSituation(db,situationKey,x.situationKind,CanonicalPresentation.cleanTitle("notification",x.type,person.isEmpty()?x.subject:person,x.subject),x.summary,"open",x.priority,x.confidence,occurredAt,meta);UniversalEventStore.linkSituationEvent(db,situation,sem,"supports");UniversalEventStore.stage(db,raw,sem,"LINKING","complete","situation_engine","Semantic event linked to an open situation","");}
        if(x.attentionKind!=null){String atTitle=CanonicalPresentation.cleanTitle("notification",x.type,person.isEmpty()?x.subject:person,x.subject);attention=UniversalEventStore.attention(db,sem,situation,x.attentionKind,atTitle,CanonicalPresentation.cleanBody(x.summary),x.priority,x.confidence,sourceKey,x.reason);UniversalEventStore.stage(db,raw,sem,"EVALUATING","complete","attention_engine","Attention projection created: "+x.attentionKind,"");}
        if(x.promoteMemory){memory=promoteMemory(vault,db,sem,x,sourceKey,person,meta);UniversalEventStore.stage(db,raw,sem,"MEMORY","complete","memory_promotion_engine",memory>0?"Durable semantic memory promoted":"Promotion skipped safely","");}
        if(x.needsModel){JSONObject input=new JSONObject();try{input.put("semantic_event_id",sem);input.put("raw_observation_id",raw);input.put("source_type","notification");input.put("technical_type",technical);input.put("platform_hint",hint);input.put("title",title);input.put("body",body);input.put("metadata",meta);}catch(Exception ignored){}job=AiJobStore.create(vault,"semantic_event_understanding",route,input.toString(),55);}
        UniversalEventStore.stage(db,raw,sem,"COMPLETE",x.needsModel?"waiting":"complete","universal_event_engine",x.needsModel?"Grounded event stored; model refinement pending":"Event fully projected","");return new Result(raw,stream,sem,situation,attention,memory,job,x.type,x.intent,semanticState,route,x.reason);
    }

    public static Result reprocessNotification(Context context,VaultDb vault,long rawId){SQLiteDatabase db=vault.getWritableDatabase();UniversalEventStore.ensure(db);Cursor c=db.rawQuery("SELECT source_key,event_type,platform_hint,technical_type,title,body,payload_json,occurred_at FROM ue_raw_observations WHERE id=? AND source_type='notification' LIMIT 1",new String[]{String.valueOf(rawId)});if(!c.moveToFirst()){c.close();return new Result(rawId,0,0,0,0,0,0,"unknown","","failed","none","raw observation not found");}String source=c.getString(0),eventType=c.getString(1),hint=c.getString(2),tech=c.getString(3),title=c.getString(4),body=c.getString(5),payload=c.getString(6);long occurred=c.getLong(7);c.close();JSONObject meta;try{meta=new JSONObject(payload);}catch(Exception e){meta=new JSONObject();}long stream=0;Cursor s=db.rawQuery("SELECT id FROM ue_streams WHERE source_type='notification' AND external_key=(SELECT external_key FROM ue_streams WHERE id IN (SELECT stream_id FROM ue_semantic_events WHERE raw_observation_id=? ORDER BY id DESC LIMIT 1) LIMIT 1)",new String[]{String.valueOf(rawId)});if(s.moveToFirst())stream=s.getLong(0);s.close();Interpretation x=interpret(tech,hint,title,body,meta,eventType);int revision=1;Cursor r=db.rawQuery("SELECT COALESCE(MAX(revision),0)+1 FROM ue_semantic_events WHERE raw_observation_id=?",new String[]{String.valueOf(rawId)});if(r.moveToFirst())revision=r.getInt(0);r.close();long sem=UniversalEventStore.insertSemantic(db,rawId,stream,revision,x.type,x.intent,x.subject,x.summary,x.confidence,x.needsModel?"waiting":"complete",true,x.needsModel?routeFor(context):"deterministic","reprocessed: "+x.reason,occurred);ContentValues u=new ContentValues();u.put("superseded_by",sem);db.update("ue_semantic_events",u,"raw_observation_id=? AND id<>? AND superseded_by=0",new String[]{String.valueOf(rawId),String.valueOf(sem)});UniversalEventStore.stage(db,rawId,sem,"REPROCESSED","complete","universal_replay","Derived interpretation rebuilt from immutable raw evidence","");return new Result(rawId,stream,sem,0,0,0,0,x.type,x.intent,x.needsModel?"waiting":"complete",x.needsModel?routeFor(context):"deterministic",x.reason);}

    private static long promoteMemory(VaultDb vault,SQLiteDatabase db,long eventId,Interpretation x,String sourceKey,String person,JSONObject meta){if(eventId<=0||!x.promoteMemory||x.confidence<0.82)return 0;Cursor check=db.rawQuery("SELECT knowledge_item_id FROM ue_memory_promotions WHERE semantic_event_id=? AND state='promoted' LIMIT 1",new String[]{String.valueOf(eventId)});long existing=check.moveToFirst()?check.getLong(0):0;check.close();if(existing>0)return existing;String title=CanonicalPresentation.cleanTitle("memory",x.type,person.isEmpty()?x.subject:person,x.subject);JSONObject m=new JSONObject();try{m.put("semantic_event_id",eventId);m.put("source",sourceKey);m.put("semantic_type",x.type);m.put("promotion_policy",MEMORY_POLICY);m.put("source_metadata",meta);}catch(Exception ignored){}long inserted=vault.insert("MEMORY","universal_memory",title,x.summary,"Memory","semantic,"+x.type.toLowerCase(Locale.ROOT),"",Fingerprint.text("ue-memory|"+eventId),m.toString());long item=inserted<0?-inserted:inserted;ContentValues p=new ContentValues();p.put("semantic_event_id",eventId);p.put("knowledge_item_id",item);p.put("state",item>0?"promoted":"failed");p.put("policy_version",MEMORY_POLICY);p.put("score",x.memoryScore);p.put("reason",x.reason);p.put("created_at",System.currentTimeMillis());p.put("updated_at",System.currentTimeMillis());db.insertWithOnConflict("ue_memory_promotions",null,p,SQLiteDatabase.CONFLICT_REPLACE);return item;}

    private static Interpretation interpret(String technical,String hint,String title,String body,JSONObject meta,String eventType){String text=(n(title)+"\n"+n(body)).trim(),low=text.toLowerCase(Locale.ROOT),tech=n(technical).toLowerCase(Locale.ROOT);Interpretation x=new Interpretation();x.subject=n(title);x.summary=CanonicalPresentation.cleanBody(body.isEmpty()?title:body);x.priority=35;x.confidence=.78;x.reason="meaningful Android notification transition";
        if("conversation_notification".equals(tech)){
            x.type="conversation_message";x.intent="message";x.priority=50;x.opensSituation=true;x.situationKind="conversation";x.confidence=.86;
            if(matchesRequest(low)){x.type="action_request";x.intent="request";x.attentionKind="ACTION";x.priority=90;x.confidence=.94;x.reason="explicit incoming request directed to the user";x.situationKind="open_request";}
            else if(matchesDecision(low)){x.type="decision";x.intent="decision";x.attentionKind="DECISION";x.priority=76;x.confidence=.88;x.promoteMemory=true;x.memoryScore=.91;x.reason="explicit decision language";x.situationKind="decision";}
            else if(matchesCommitment(low)){x.type="commitment";x.intent="commitment";x.attentionKind="WAITING";x.priority=72;x.confidence=.86;x.promoteMemory=true;x.memoryScore=.87;x.reason="explicit commitment/future obligation";x.situationKind="commitment";}
            else{x.needsModel=true;x.confidence=.58;x.reason="conversation meaning needs semantic model/context";}
        }else if("progress_state".equals(tech)||"download_state".equals(tech)||"service_state".equals(tech)){x.type="technical_state";x.intent="state_change";x.priority=8;x.confidence=.98;x.summary=CanonicalPresentation.cleanBody(text);x.reason="technical state transition; preserved but not promoted to memory";}
        else if("call_hint".equals(tech)){x.type="call_event";x.intent="call";x.priority=55;x.confidence=.9;if(low.contains("missed")||low.contains("فائت")||low.contains("لم يتم الرد")){x.attentionKind="ACTION";x.priority=78;x.reason="missed call may require response";x.opensSituation=true;x.situationKind="missed_call";}}
        else if("email_hint".equals(tech)){x.type="email_event";x.intent="email";x.priority=45;x.confidence=.72;x.needsModel=true;x.reason="email content needs semantic/contextual interpretation";}
        else if("alarm".equals(tech)||"reminder".equals(tech)||"event".equals(tech)){x.type=tech+"_event";x.intent=tech;x.priority=65;x.confidence=.91;x.attentionKind="ACTION";x.reason="explicit time-sensitive Android event";}
        else{x.type="notification_event";x.intent="notification";x.priority=30;x.confidence=.55;x.needsModel=!text.isEmpty();x.reason=text.isEmpty()?"metadata-only notification":"generic notification needs semantic/contextual interpretation";}
        if("removed".equals(eventType)&&"technical_state".equals(x.type)){x.priority=4;}return x;}

    private static boolean matchesRequest(String s){return containsAny(s,"ابعت","ابعث","هات ","محتاجك","محتاج منك","لو سمحت","ضروري","please send","send me","can you","could you","need you to","please ");}
    private static boolean matchesDecision(String s){return containsAny(s,"قررنا","قررت","تم الاتفاق","اتفقنا","القرار","we decided","decided that","agreed that","final decision");}
    private static boolean matchesCommitment(String s){return containsAny(s,"هبعت","هعمل","هكلم","هراجع","هنعمل","هخلص","هتكون","سأرسل","سوف ","i will","i'll ","we will","we'll ","promise","by tomorrow","بكرة","غدا");}
    private static boolean containsAny(String s,String... xs){for(String x:xs)if(s.contains(x))return true;return false;}
    private static String extractPerson(String title,JSONObject meta){String p=n(meta.optString("conversation_title",""));if(!p.isEmpty())return p;return n(title);}
    private static String situationKey(String source,String person,Interpretation x,JSONObject meta){String shortcut=n(meta.optString("shortcut_id",""));String basis=!shortcut.isEmpty()?shortcut:(!person.isEmpty()?person:x.subject);return Fingerprint.text("situation|"+source+"|"+x.situationKind+"|"+basis);}
    private static String routeFor(Context c){try{if(LocalModelManager.installed(c))return"local_background_model";}catch(Throwable ignored){}try{if(GeminiNanoProbe.quickAvailability(c).available)return"gemini_nano_foreground_deferred";}catch(Throwable ignored){}return"local_semantic_deferred";}
    private static String n(String s){return s==null?"":s.trim();}

    private static final class Interpretation {String type="notification_event",intent="notification",subject="",summary="",attentionKind=null,situationKind="event",reason="";int priority=30;double confidence=.5,memoryScore=0;boolean needsModel=false,opensSituation=false,promoteMemory=false;}
}
