package com.kareem.cortex;

import android.content.ContentValues;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONObject;
import java.util.*;

/** Cortex universal event ledger. Raw observations are immutable; UI reads projections only. */
public final class UniversalEventStore {
    public static final String PROCESSOR_VERSION="uee_001";
    public static final long ATTENTION_COMPAT_OFFSET=1000000000000L;
    private UniversalEventStore(){}

    public static void ensure(SQLiteDatabase db){
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_raw_observations(id INTEGER PRIMARY KEY AUTOINCREMENT,source_type TEXT NOT NULL,source_key TEXT NOT NULL,source_observation_key TEXT,event_type TEXT NOT NULL,platform_hint TEXT,technical_type TEXT,title TEXT,body TEXT,payload_json TEXT NOT NULL,immutable_hash TEXT NOT NULL,occurred_at INTEGER NOT NULL,created_at INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_raw_time ON ue_raw_observations(occurred_at DESC)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_raw_source ON ue_raw_observations(source_type,source_key,occurred_at ASC)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_raw_hash ON ue_raw_observations(immutable_hash)");
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_streams(id INTEGER PRIMARY KEY AUTOINCREMENT,source_type TEXT NOT NULL,external_key TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'active',current_hash TEXT,current_title TEXT,current_body TEXT,platform_hint TEXT,technical_type TEXT,observation_count INTEGER DEFAULT 0,meaningful_count INTEGER DEFAULT 0,first_seen_at INTEGER NOT NULL,last_seen_at INTEGER NOT NULL,last_meaningful_at INTEGER DEFAULT 0,metadata_json TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,UNIQUE(source_type,external_key))");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_stream_recent ON ue_streams(last_seen_at DESC)");
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_semantic_events(id INTEGER PRIMARY KEY AUTOINCREMENT,raw_observation_id INTEGER NOT NULL,stream_id INTEGER NOT NULL,revision INTEGER NOT NULL DEFAULT 1,semantic_type TEXT NOT NULL,intent TEXT,subject TEXT,summary TEXT,confidence REAL DEFAULT 0,semantic_state TEXT NOT NULL DEFAULT 'complete',meaningful INTEGER NOT NULL DEFAULT 1,processor_version TEXT NOT NULL,model_route TEXT,reason TEXT,occurred_at INTEGER NOT NULL,created_at INTEGER NOT NULL,superseded_by INTEGER DEFAULT 0)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_semantic_recent ON ue_semantic_events(occurred_at DESC)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_semantic_stream ON ue_semantic_events(stream_id,occurred_at ASC)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_semantic_state ON ue_semantic_events(semantic_state,occurred_at ASC)");
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_entities(id INTEGER PRIMARY KEY AUTOINCREMENT,kind TEXT NOT NULL,canonical_name TEXT NOT NULL,normalized_key TEXT NOT NULL UNIQUE,metadata_json TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");db.execSQL("CREATE TABLE IF NOT EXISTS ue_event_entity_links(id INTEGER PRIMARY KEY AUTOINCREMENT,semantic_event_id INTEGER NOT NULL,entity_id INTEGER NOT NULL,relation TEXT NOT NULL,confidence REAL DEFAULT 0,created_at INTEGER NOT NULL,UNIQUE(semantic_event_id,entity_id,relation))");
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_situations(id INTEGER PRIMARY KEY AUTOINCREMENT,situation_key TEXT NOT NULL UNIQUE,kind TEXT NOT NULL,title TEXT NOT NULL,summary TEXT,state TEXT NOT NULL DEFAULT 'open',priority INTEGER DEFAULT 0,confidence REAL DEFAULT 0,opened_at INTEGER NOT NULL,last_changed_at INTEGER NOT NULL,resolved_at INTEGER DEFAULT 0,metadata_json TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_situations_state ON ue_situations(state,priority DESC,last_changed_at DESC)");db.execSQL("CREATE TABLE IF NOT EXISTS ue_situation_events(id INTEGER PRIMARY KEY AUTOINCREMENT,situation_id INTEGER NOT NULL,semantic_event_id INTEGER NOT NULL,relation TEXT NOT NULL,created_at INTEGER NOT NULL,UNIQUE(situation_id,semantic_event_id,relation))");
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_attention_items(id INTEGER PRIMARY KEY AUTOINCREMENT,semantic_event_id INTEGER NOT NULL,situation_id INTEGER DEFAULT 0,kind TEXT NOT NULL,title TEXT NOT NULL,body TEXT,state TEXT NOT NULL DEFAULT 'open',priority INTEGER DEFAULT 0,confidence REAL DEFAULT 0,source_key TEXT,reason TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,resolved_at INTEGER DEFAULT 0,UNIQUE(semantic_event_id,kind))");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_attention_open ON ue_attention_items(state,priority DESC,updated_at DESC)");
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_memory_promotions(id INTEGER PRIMARY KEY AUTOINCREMENT,semantic_event_id INTEGER NOT NULL UNIQUE,knowledge_item_id INTEGER NOT NULL DEFAULT 0,state TEXT NOT NULL,policy_version TEXT NOT NULL,score REAL DEFAULT 0,reason TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_memory_item ON ue_memory_promotions(knowledge_item_id,state)");
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_pipeline_stages(id INTEGER PRIMARY KEY AUTOINCREMENT,raw_observation_id INTEGER NOT NULL,semantic_event_id INTEGER DEFAULT 0,stage TEXT NOT NULL,state TEXT NOT NULL,engine TEXT,attempt INTEGER DEFAULT 1,detail TEXT,error TEXT,started_at INTEGER NOT NULL,completed_at INTEGER DEFAULT 0,UNIQUE(raw_observation_id,stage,attempt))");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_stage_recent ON ue_pipeline_stages(started_at DESC)");db.execSQL("CREATE INDEX IF NOT EXISTS idx_ue_stage_state ON ue_pipeline_stages(state,started_at DESC)");
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_reprocess_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,from_at INTEGER NOT NULL,to_at INTEGER NOT NULL,processor_version TEXT NOT NULL,state TEXT NOT NULL DEFAULT 'queued',total INTEGER DEFAULT 0,processed INTEGER DEFAULT 0,failed INTEGER DEFAULT 0,error TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,completed_at INTEGER DEFAULT 0)");
        db.execSQL("CREATE TABLE IF NOT EXISTS ue_legacy_classification(knowledge_item_id INTEGER PRIMARY KEY,classification TEXT NOT NULL,reason TEXT,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL)");
        if(tableExists(db,"derived_items"))db.execSQL("CREATE TRIGGER IF NOT EXISTS trg_ue_attention_compat_resolve AFTER UPDATE OF state ON derived_items WHEN NEW.id>="+ATTENTION_COMPAT_OFFSET+" AND NEW.candidate_kind='UE_ATTENTION' BEGIN UPDATE ue_attention_items SET state=NEW.state,updated_at=NEW.updated_at,resolved_at=CASE WHEN NEW.state='resolved' THEN NEW.updated_at ELSE resolved_at END WHERE id=NEW.id-"+ATTENTION_COMPAT_OFFSET+"; END");
        backfillLegacy(db);
    }

    private static void backfillLegacy(SQLiteDatabase db){if(!tableExists(db,"knowledge_items"))return;long now=System.currentTimeMillis();db.execSQL("INSERT OR IGNORE INTO ue_legacy_classification(knowledge_item_id,classification,reason,created_at,updated_at) SELECT id,CASE WHEN type IN ('SCREENSHOT','IMAGE','AUDIO','FILE','NOTIFICATION') OR source IN ('screenshot-folder','screen_understanding','screen_understand','audio_import','manual_recording') THEN 'captured_artifact' ELSE 'memory_candidate' END,'v7 non-destructive legacy classification',?,? FROM knowledge_items",new Object[]{now,now});}
    public static long appendRaw(SQLiteDatabase db,String sourceType,String sourceKey,String observationKey,String eventType,String platformHint,String technicalType,String title,String body,JSONObject payload,long occurredAt){ensure(db);long now=System.currentTimeMillis(),when=occurredAt>0?occurredAt:now;String json=payload==null?"{}":payload.toString();String hash=Fingerprint.text(sourceType+"|"+sourceKey+"|"+eventType+"|"+title+"|"+body+"|"+json+"|"+when);ContentValues v=new ContentValues();v.put("source_type",n(sourceType));v.put("source_key",n(sourceKey));v.put("source_observation_key",n(observationKey));v.put("event_type",n(eventType));v.put("platform_hint",n(platformHint));v.put("technical_type",n(technicalType));v.put("title",n(title));v.put("body",n(body));v.put("payload_json",json);v.put("immutable_hash",hash);v.put("occurred_at",when);v.put("created_at",now);return db.insertOrThrow("ue_raw_observations",null,v);}
    public static long upsertStream(SQLiteDatabase db,String sourceType,String externalKey,String state,String hash,String title,String body,String platformHint,String technicalType,long occurredAt,boolean meaningful,JSONObject meta){ensure(db);long now=System.currentTimeMillis(),when=occurredAt>0?occurredAt:now,id=0;int count=0,meaningfulCount=0;Cursor c=db.rawQuery("SELECT id,observation_count,meaningful_count FROM ue_streams WHERE source_type=? AND external_key=? LIMIT 1",new String[]{n(sourceType),n(externalKey)});if(c.moveToFirst()){id=c.getLong(0);count=c.getInt(1);meaningfulCount=c.getInt(2);}c.close();ContentValues v=new ContentValues();v.put("state",n(state));v.put("current_hash",n(hash));v.put("current_title",n(title));v.put("current_body",n(body));v.put("platform_hint",n(platformHint));v.put("technical_type",n(technicalType));v.put("observation_count",count+1);v.put("meaningful_count",meaningful?meaningfulCount+1:meaningfulCount);v.put("last_seen_at",when);if(meaningful)v.put("last_meaningful_at",when);v.put("metadata_json",meta==null?"{}":meta.toString());v.put("updated_at",now);if(id>0){db.update("ue_streams",v,"id=?",new String[]{String.valueOf(id)});return id;}v.put("source_type",n(sourceType));v.put("external_key",n(externalKey));v.put("first_seen_at",when);v.put("created_at",now);return db.insertOrThrow("ue_streams",null,v);}
    public static long insertSemantic(SQLiteDatabase db,long rawId,long streamId,int revision,String type,String intent,String subject,String summary,double confidence,String state,boolean meaningful,String route,String reason,long occurredAt){ensure(db);ContentValues v=new ContentValues();v.put("raw_observation_id",rawId);v.put("stream_id",streamId);v.put("revision",Math.max(1,revision));v.put("semantic_type",n(type));v.put("intent",n(intent));v.put("subject",n(subject));v.put("summary",n(summary));v.put("confidence",confidence);v.put("semantic_state",n(state));v.put("meaningful",meaningful?1:0);v.put("processor_version",PROCESSOR_VERSION);v.put("model_route",n(route));v.put("reason",n(reason));v.put("occurred_at",occurredAt);v.put("created_at",System.currentTimeMillis());return db.insertOrThrow("ue_semantic_events",null,v);}
    public static void stage(SQLiteDatabase db,long rawId,long semanticId,String stage,String state,String engine,String detail,String error){ensure(db);long now=System.currentTimeMillis();ContentValues v=new ContentValues();v.put("raw_observation_id",rawId);v.put("semantic_event_id",semanticId);v.put("stage",n(stage));v.put("state",n(state));v.put("engine",n(engine));v.put("attempt",1);v.put("detail",n(detail));v.put("error",n(error));v.put("started_at",now);if("complete".equals(state)||"failed".equals(state)||"waiting".equals(state))v.put("completed_at",now);db.insertWithOnConflict("ue_pipeline_stages",null,v,SQLiteDatabase.CONFLICT_REPLACE);}
    public static long entity(SQLiteDatabase db,String kind,String name,JSONObject meta){String canonical=n(name);if(canonical.isEmpty())return 0;String key=kind.toLowerCase(Locale.ROOT)+"|"+canonical.toLowerCase(Locale.ROOT);long now=System.currentTimeMillis();Cursor c=db.rawQuery("SELECT id FROM ue_entities WHERE normalized_key=? LIMIT 1",new String[]{key});long id=c.moveToFirst()?c.getLong(0):0;c.close();ContentValues v=new ContentValues();v.put("kind",n(kind).toUpperCase(Locale.ROOT));v.put("canonical_name",canonical);v.put("normalized_key",key);v.put("metadata_json",meta==null?"{}":meta.toString());v.put("updated_at",now);if(id>0){db.update("ue_entities",v,"id=?",new String[]{String.valueOf(id)});return id;}v.put("created_at",now);return db.insertOrThrow("ue_entities",null,v);}
    public static void linkEntity(SQLiteDatabase db,long eventId,long entityId,String relation,double confidence){if(eventId<=0||entityId<=0)return;ContentValues v=new ContentValues();v.put("semantic_event_id",eventId);v.put("entity_id",entityId);v.put("relation",n(relation));v.put("confidence",confidence);v.put("created_at",System.currentTimeMillis());db.insertWithOnConflict("ue_event_entity_links",null,v,SQLiteDatabase.CONFLICT_IGNORE);}
    public static long upsertSituation(SQLiteDatabase db,String key,String kind,String title,String summary,String state,int priority,double confidence,long occurredAt,JSONObject meta){ensure(db);long now=System.currentTimeMillis(),id=0;Cursor c=db.rawQuery("SELECT id FROM ue_situations WHERE situation_key=? LIMIT 1",new String[]{n(key)});if(c.moveToFirst())id=c.getLong(0);c.close();ContentValues v=new ContentValues();v.put("kind",n(kind));v.put("title",n(title));v.put("summary",n(summary));v.put("state",n(state));v.put("priority",priority);v.put("confidence",confidence);v.put("last_changed_at",occurredAt);v.put("metadata_json",meta==null?"{}":meta.toString());v.put("updated_at",now);if("resolved".equals(state))v.put("resolved_at",occurredAt);if(id>0){db.update("ue_situations",v,"id=?",new String[]{String.valueOf(id)});return id;}v.put("situation_key",n(key));v.put("opened_at",occurredAt);v.put("created_at",now);return db.insertOrThrow("ue_situations",null,v);}
    public static void linkSituationEvent(SQLiteDatabase db,long situationId,long eventId,String relation){if(situationId<=0||eventId<=0)return;ContentValues v=new ContentValues();v.put("situation_id",situationId);v.put("semantic_event_id",eventId);v.put("relation",n(relation));v.put("created_at",System.currentTimeMillis());db.insertWithOnConflict("ue_situation_events",null,v,SQLiteDatabase.CONFLICT_IGNORE);}
    public static long attention(SQLiteDatabase db,long eventId,long situationId,String kind,String title,String body,int priority,double confidence,String sourceKey,String reason){if(eventId<=0)return 0;long now=System.currentTimeMillis();ContentValues v=new ContentValues();v.put("semantic_event_id",eventId);v.put("situation_id",situationId);v.put("kind",n(kind));v.put("title",n(title));v.put("body",n(body));v.put("state","open");v.put("priority",priority);v.put("confidence",confidence);v.put("source_key",n(sourceKey));v.put("reason",n(reason));v.put("created_at",now);v.put("updated_at",now);long id=db.insertWithOnConflict("ue_attention_items",null,v,SQLiteDatabase.CONFLICT_IGNORE);if(id<=0){Cursor c=db.rawQuery("SELECT id FROM ue_attention_items WHERE semantic_event_id=? AND kind=? LIMIT 1",new String[]{String.valueOf(eventId),n(kind)});id=c.moveToFirst()?c.getLong(0):0;c.close();}if(id>0)mirrorAttention(db,id,eventId,situationId,kind,title,body,priority,confidence,sourceKey,reason,now);return id;}
    private static void mirrorAttention(SQLiteDatabase db,long attentionId,long eventId,long situationId,String kind,String title,String body,int priority,double confidence,String sourceKey,String reason,long now){if(!tableExists(db,"derived_items"))return;long mirrorId=ATTENTION_COMPAT_OFFSET+attentionId;ContentValues d=new ContentValues();d.put("id",mirrorId);d.put("kind",n(kind));d.put("title",n(title));d.put("body",n(body));d.put("state","open");d.put("confidence",confidence);d.put("importance",priority);d.put("fingerprint","ue_attention_"+attentionId);JSONObject meta=new JSONObject();try{meta.put("ue_attention_id",attentionId);meta.put("semantic_event_id",eventId);meta.put("situation_id",situationId);meta.put("reason",reason);}catch(Exception ignored){}d.put("metadata_json",meta.toString());d.put("created_at",now);d.put("updated_at",now);d.put("source_key",n(sourceKey));d.put("thread_id",situationId);d.put("anchor_signal_id",0);d.put("candidate_kind","UE_ATTENTION");d.put("semantic_key","ue_attention_"+attentionId);db.insertWithOnConflict("derived_items",null,d,SQLiteDatabase.CONFLICT_REPLACE);}
    public static boolean isPromotedMemory(SQLiteDatabase db,long itemId){ensure(db);Cursor c=db.rawQuery("SELECT 1 FROM ue_memory_promotions WHERE knowledge_item_id=? AND state='promoted' LIMIT 1",new String[]{String.valueOf(itemId)});boolean yes=c.moveToFirst();c.close();return yes;}
    public static boolean isLegacyCapture(SQLiteDatabase db,long itemId){ensure(db);Cursor c=db.rawQuery("SELECT 1 FROM ue_legacy_classification WHERE knowledge_item_id=? AND classification='captured_artifact' LIMIT 1",new String[]{String.valueOf(itemId)});boolean yes=c.moveToFirst();c.close();return yes;}
    public static long scalar(SQLiteDatabase db,String sql,String[] args){Cursor c=db.rawQuery(sql,args);long n=c.moveToFirst()?c.getLong(0):0;c.close();return n;}private static boolean tableExists(SQLiteDatabase db,String table){Cursor c=db.rawQuery("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1",new String[]{table});boolean e=c.moveToFirst();c.close();return e;}private static String n(String s){return s==null?"":s.trim();}
}
