package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.os.Bundle;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.io.File;
import java.util.*;

/** v50 Vault: searchable evidence library with visual-first cards and a persistent navigation shell. */
public class VaultActivity extends Activity {
    VaultDb db;LinearLayout feed,tabs;EditText search;TextView count,topMore;String filter="ALL";long initialItem=0;boolean openedInitial=false;
    int dp(int x){return CortexUi.dp(this,x);}TextView plain(String s,int sp,int c){return CortexUi.plain(this,s,sp,c);}TextView readable(String s,int sp,int c){return CortexUi.text(this,s,sp,c);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);ScreenshotLearning.ensure(db);VisualInsightStore.ensure(db);V43Maintenance.run(this,db);initialItem=getIntent().getLongExtra("item_id",0);build();refresh();}
    @Override protected void onResume(){super.onResume();if(db!=null)refresh();ScreenshotWorkScheduler.kick(this);}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);
        LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(14),dp(16),0);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=plain("Vault",29,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);count=plain("",11,CortexUi.MUTED);titles.addView(count);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));topMore=plain("•••",18,CortexUi.TEXT);topMore.setGravity(Gravity.CENTER);CortexUi.pressable(this,topMore,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER,17));topMore.setOnClickListener(this::showMore);head.addView(topMore,new LinearLayout.LayoutParams(dp(48),dp(48)));body.addView(head);

        LinearLayout searchBox=new LinearLayout(this);searchBox.setOrientation(LinearLayout.HORIZONTAL);searchBox.setGravity(Gravity.CENTER_VERTICAL);searchBox.setPadding(dp(13),0,dp(10),0);searchBox.setBackground(CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,18));TextView mag=plain("⌕",22,CortexUi.MUTED);mag.setGravity(Gravity.CENTER);searchBox.addView(mag,new LinearLayout.LayoutParams(dp(30),dp(50)));search=new EditText(this);search.setHint("Search memories, screenshots, transcripts…");search.setHintTextColor(CortexUi.FAINT);search.setTextColor(CortexUi.TEXT);search.setTextSize(13);search.setSingleLine(true);search.setBackgroundColor(Color.TRANSPARENT);search.setPadding(dp(4),0,dp(4),0);searchBox.addView(search,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout.LayoutParams sbp=new LinearLayout.LayoutParams(-1,dp(50));sbp.setMargins(0,dp(14),0,dp(11));body.addView(searchBox,sbp);
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int c){refresh();}public void afterTextChanged(Editable e){}});

        HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);hsv.addView(tabs);body.addView(hsv,new LinearLayout.LayoutParams(-1,dp(42)));
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,dp(10),0,dp(18));sv.addView(feed);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        CortexUi.addBottomNav(this,root,"vault",()->showMore(topMore));setContentView(root);}

    void refresh(){tabs.removeAllViews();String[] fs={"ALL","SCREENSHOTS","VOICE","FILES","TEXT"};for(String f:fs)addTab(f);feed.removeAllViews();String q=search==null?"":search.getText().toString().trim();ArrayList<KnowledgeItem> all=db.lexicalSearch(q,2000);int shown=0;for(KnowledgeItem k:all){if(!match(k))continue;addCard(k);shown++;}count.setText(shown+" shown  •  "+total()+" memories");if(shown==0)emptyState(q);if(initialItem>0&&!openedInitial){openedInitial=true;KnowledgeItem k=db.getById(initialItem);if(k!=null)detail(k);}}
    void addTab(String f){boolean on=f.equals(filter);TextView t=CortexUi.chip(this,label(f),on?CortexUi.COPPER:CortexUi.MUTED,on);t.setOnClickListener(v->{filter=f;refresh();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(34));p.setMargins(0,0,dp(7),0);tabs.addView(t,p);}String label(String x){if("SCREENSHOTS".equals(x))return"Images";if("VOICE".equals(x))return"Voice";if("FILES".equals(x))return"Files";if("TEXT".equals(x))return"Text";return"All";}
    boolean match(KnowledgeItem k){if("ALL".equals(filter))return true;if("VOICE".equals(filter))return"AUDIO".equals(k.type);if("SCREENSHOTS".equals(filter))return isShot(k);if("FILES".equals(filter))return"FILE".equals(k.type);return !"AUDIO".equals(k.type)&&!isShot(k)&&!"FILE".equals(k.type);}boolean isShot(KnowledgeItem k){return"SCREENSHOT".equals(k.type)||"IMAGE".equals(k.type);}

    void emptyState(String q){LinearLayout e=CortexUi.card(this,22);e.setGravity(Gravity.CENTER);e.setPadding(dp(22),dp(40),dp(22),dp(40));TextView icon=plain(q.isEmpty()?"◇":"⌕",28,CortexUi.COPPER);icon.setGravity(Gravity.CENTER);e.addView(icon);TextView t=plain(q.isEmpty()?"Nothing in this view yet":"No matching memory",17,CortexUi.TEXT);CortexUi.medium(t);t.setGravity(Gravity.CENTER);t.setPadding(0,dp(7),0,0);e.addView(t);TextView b=readable(q.isEmpty()?"Try another filter or capture something new.":"Try fewer words or switch back to All.",12,CortexUi.MUTED);b.setGravity(Gravity.CENTER);b.setTextAlignment(View.TEXT_ALIGNMENT_CENTER);b.setPadding(0,dp(5),0,0);e.addView(b);feed.addView(e);}

    void addCard(KnowledgeItem k){LinearLayout c=CortexUi.card(this,21);c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.TOP);c.setPadding(dp(12),dp(12),dp(13),dp(12));CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,21));View media=media(k);c.addView(media,new LinearLayout.LayoutParams(dp(84),dp(84)));LinearLayout words=new LinearLayout(this);words.setOrientation(LinearLayout.VERTICAL);words.setPadding(dp(13),0,0,0);TextView t=readable(clean(k.title),15,CortexUi.TEXT);CortexUi.medium(t);t.setMaxLines(2);t.setEllipsize(android.text.TextUtils.TruncateAt.END);words.addView(t);TextView meta=plain(friendly(k.type)+"  •  "+age(captureTime(k)),10,CortexUi.MUTED);meta.setPadding(0,dp(4),0,0);words.addView(meta);
        if(isShot(k)){VisualInsightStore.Insight vi=VisualInsightStore.get(db,k.id);if(vi!=null&&vi.ready()){TextView v=readable(clip(vi.description,125),12,CortexUi.TEXT);v.setMaxLines(3);v.setPadding(0,dp(7),0,0);words.addView(v);TextView state=plain("✦ "+friendlyVisual(vi.contentType)+"  •  "+vi.usefulnessScore+"/100",10,CortexUi.COPPER);state.setPadding(0,dp(5),0,0);words.addView(state);}else{String raw=raw(k);if(!raw.isEmpty()){TextView v=readable(clip(raw,105),11,CortexUi.MUTED);v.setMaxLines(2);v.setPadding(0,dp(7),0,0);words.addView(v);}TextView st=plain(vi==null?"Visual understanding pending":"Visual: "+vi.status.replace('_',' '),10,CortexUi.FAINT);st.setPadding(0,dp(5),0,0);words.addView(st);}}
        else{String raw=raw(k);if(!raw.isEmpty()){TextView v=readable(clip(raw,140),12,CortexUi.MUTED);v.setMaxLines(3);v.setPadding(0,dp(7),0,0);words.addView(v);}}
        c.addView(words,new LinearLayout.LayoutParams(0,-2,1));c.setOnClickListener(v->detail(k));c.setOnLongClickListener(v->{itemMenu(k,c);return true;});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(9));feed.addView(c,p);}

    View media(KnowledgeItem k){if(isShot(k)&&k.attachmentPath!=null&&!k.attachmentPath.isEmpty()){Bitmap b=previewSmall(k.attachmentPath);if(b!=null){ImageView im=new ImageView(this);im.setImageBitmap(b);im.setScaleType(ImageView.ScaleType.CENTER_CROP);im.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER_SOFT,16));im.setClipToOutline(true);return im;}}TextView icon=plain("AUDIO".equals(k.type)?"◉":"FILE".equals(k.type)?"▤":"◆",24,"AUDIO".equals(k.type)?CortexUi.GOLD:CortexUi.COPPER);icon.setGravity(Gravity.CENTER);icon.setBackground(CortexUi.round(this,Color.rgb(44,37,31),CortexUi.BORDER_SOFT,16));return icon;}
    void itemMenu(KnowledgeItem k,View anchor){PopupMenu p=new PopupMenu(this,anchor);p.getMenu().add("Open detail");if(isShot(k))p.getMenu().add("Open Visual Intelligence");p.getMenu().add("Share / capture actions");p.setOnMenuItemClickListener(m->{String x=m.getTitle().toString();if(x.startsWith("Open detail"))detail(k);else if(x.startsWith("Open Visual")){Intent i=new Intent(this,VisualIntelligenceActivity.class);i.putExtra("item_id",k.id);startActivity(i);}else startActivity(new Intent(this,MainActivity.class));return true;});p.show();}

    String statusLabel(KnowledgeItem k){if("analyzed".equals(k.status))return isShot(k)?"Stored + searchable":"Analyzed";if("queued".equals(k.status))return"Queued";if("analyzing".equals(k.status))return"Analyzing";if("analysis_failed".equals(k.status)||"failed_retryable".equals(k.status))return"Analysis failed";return k.status==null?"":k.status;}

    void detail(KnowledgeItem k){ScrollView sv=new ScrollView(this);LinearLayout b=new LinearLayout(this);b.setOrientation(LinearLayout.VERTICAL);b.setPadding(dp(18),dp(10),dp(18),dp(20));b.setBackgroundColor(CortexUi.BG);sv.addView(b);
        if(isShot(k)&&k.attachmentPath!=null&&!k.attachmentPath.isEmpty()){ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.FIT_CENTER);Bitmap bmp=preview(k.attachmentPath);if(bmp!=null)im.setImageBitmap(bmp);im.setBackground(CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,18));b.addView(im,new LinearLayout.LayoutParams(-1,-2));}
        label(b,"Source");b.addView(plain(friendly(k.type)+"  •  "+k.source+"\nCaptured "+new java.text.SimpleDateFormat("dd MMM yyyy • HH:mm",Locale.getDefault()).format(new Date(captureTime(k)))+"  •  "+statusLabel(k),11,CortexUi.MUTED));
        if(isShot(k)){VisualInsightStore.Insight vi=VisualInsightStore.get(db,k.id);label(b,"Visual Intelligence");if(vi!=null&&vi.ready()){b.addView(readable(empty(vi.description,"No description"),14,CortexUi.TEXT));if(!empty(vi.usefulnessReason," ").trim().isEmpty()){TextView why=readable(vi.usefulnessReason,12,CortexUi.MUTED);why.setPadding(0,dp(8),0,0);b.addView(why);}ArrayList<String> acts=vi.actionLabels();if(!acts.isEmpty()){label(b,"Suggested actions");b.addView(readable(bullets(acts),12,CortexUi.TEXT));}if(!vi.visibleText.trim().isEmpty()){label(b,"Visible text");b.addView(readable(vi.visibleText,12,CortexUi.MUTED));}}else b.addView(readable(vi==null?"Strong visual understanding has not run yet.":"Visual status: "+vi.status+(vi.error.isEmpty()?"":"\n"+vi.error),12,CortexUi.MUTED));TextView inspect=CortexUi.action(this,vi!=null&&vi.ready()?"Open Visual Intelligence":"Understand this image",CortexUi.COPPER,true);inspect.setOnClickListener(v->{Intent i=new Intent(this,VisualIntelligenceActivity.class);i.putExtra("item_id",k.id);startActivity(i);});LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,dp(48));ip.setMargins(0,dp(12),0,0);b.addView(inspect,ip);}
        if(k.extractedText!=null&&!k.extractedText.trim().isEmpty()){label(b,"Supporting extracted text");b.addView(readable(k.extractedText,12,CortexUi.MUTED));}if(k.summary!=null&&!k.summary.trim().isEmpty()){label(b,"Summary");b.addView(readable(k.summary,13,CortexUi.TEXT));}
        if(isShot(k)){ArrayList<String> chosen=ScreenshotLearning.selected(db,k.id);label(b,"What matters to you");b.addView(readable(chosen.isEmpty()?"Not taught manually yet.":bullets(chosen),12,chosen.isEmpty()?CortexUi.MUTED:CortexUi.TEXT));TextView teach=CortexUi.action(this,"Teach Cortex what matters",CortexUi.COPPER,false);teach.setOnClickListener(v->teach(k));LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,dp(46));tp.setMargins(0,dp(10),0,0);b.addView(teach,tp);}
        AlertDialog d=new AlertDialog.Builder(this).setTitle(clean(k.title)).setView(sv).setNegativeButton("Close",null).create();d.setOnShowListener(x->{Window w=d.getWindow();if(w!=null)w.setBackgroundDrawable(CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER,22));});d.show();}

    void teach(KnowledgeItem k){String type=ScreenshotLearning.contentType(db,k.id);String[] opts=ScreenshotLearning.options(type);boolean[] checked=ScreenshotLearning.suggested(db,type,opts);for(String old:ScreenshotLearning.selected(db,k.id))for(int i=0;i<opts.length;i++)if(opts[i].equals(old))checked[i]=true;new AlertDialog.Builder(this).setTitle("What matters here? • "+type).setMultiChoiceItems(opts,checked,(d,w,on)->checked[w]=on).setPositiveButton("Save",(d,w)->{ScreenshotLearning.record(db,k.id,type,opts,checked);Toast.makeText(this,"Cortex learned your priorities",Toast.LENGTH_LONG).show();refresh();}).setNegativeButton("Cancel",null).show();}
    void showMore(View anchor){PopupMenu p=new PopupMenu(this,anchor);p.getMenu().add("Capture something");p.getMenu().add("Brain & context");p.getMenu().add("Environment & Local AI");p.getMenu().add("Full app audit");p.setOnMenuItemClickListener(m->{String s=m.getTitle().toString();if(s.startsWith("Capture"))startActivity(new Intent(this,MainActivity.class));else if(s.startsWith("Brain"))startActivity(new Intent(this,BrainActivity.class));else if(s.startsWith("Environment"))startActivity(new Intent(this,EnvironmentActivity.class));else startActivity(new Intent(this,CortexAuditActivity.class));return true;});p.show();}

    Bitmap previewSmall(String path){try{File f=new File(path);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeFile(f.getAbsolutePath(),o);int sample=1;while(Math.max(o.outWidth,o.outHeight)/sample>320)sample*=2;BitmapFactory.Options d=new BitmapFactory.Options();d.inSampleSize=sample;return BitmapFactory.decodeFile(f.getAbsolutePath(),d);}catch(Exception e){return null;}}
    Bitmap preview(String path){try{File f=new File(path);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeFile(f.getAbsolutePath(),o);int sample=1;while(Math.max(o.outWidth,o.outHeight)/sample>1600)sample*=2;BitmapFactory.Options d=new BitmapFactory.Options();d.inSampleSize=sample;return BitmapFactory.decodeFile(f.getAbsolutePath(),d);}catch(Exception e){return null;}}
    long total(){Cursor c=db.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM knowledge_items",null);long n=c.moveToFirst()?c.getLong(0):0;c.close();return n;}long captureTime(KnowledgeItem k){if(k.metadataJson!=null&&!k.metadataJson.isEmpty())try{org.json.JSONObject o=new org.json.JSONObject(k.metadataJson);long x=o.optLong("source_modified",0);if(x>0)return x;}catch(Exception ignored){}return k.createdAt;}
    void label(LinearLayout p,String s){TextView h=CortexUi.section(this,s);h.setTextColor(CortexUi.COPPER);p.addView(h);}String raw(KnowledgeItem k){if(k.rawText!=null&&!k.rawText.trim().isEmpty())return k.rawText;if(k.extractedText!=null&&!k.extractedText.trim().isEmpty())return k.extractedText;return k.summary==null?"":k.summary;}String clean(String s){if(s==null||s.trim().isEmpty())return"Memory";String x=s.trim();if(x.regionMatches(true,0,"Voice:",0,6))x=x.substring(6).trim();return x;}String friendly(String s){if("AUDIO".equals(s))return"Voice";if("SCREENSHOT".equals(s))return"Screenshot";if("IMAGE".equals(s))return"Image";return s==null?"Memory":s;}String friendlyVisual(String s){return s==null?"visual":s.replace('_',' ');}String clip(String s,int n){return s==null?"":(s.length()<=n?s:s.substring(0,n)+"…");}String bullets(ArrayList<String> xs){StringBuilder s=new StringBuilder();for(String x:xs)s.append("• ").append(x).append('\n');return s.toString().trim();}String age(long ms){long m=Math.max(0,System.currentTimeMillis()-ms)/60000;if(m<1)return"now";if(m<60)return m+"m";long h=m/60;if(h<24)return h+"h";return h/24+"d";}String empty(String s,String f){return s==null||s.trim().isEmpty()?f:s.trim();}
    @Override protected void onDestroy(){super.onDestroy();if(db!=null)db.close();}
}
