package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

/** Fast evidence library. Search is async and renders a bounded result set instead of thousands of Views. */
public class VaultActivity extends Activity {
    VaultDb db;LinearLayout feed,tabs;EditText search;TextView count;String filter="ALL";long initialItem=0;boolean openedInitial=false;Handler handler=new Handler(Looper.getMainLooper());Runnable pending;volatile int generation=0;volatile boolean destroyed=false;
    final ExecutorService loader=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"cortex-vault-search");t.setPriority(Thread.NORM_PRIORITY-1);return t;});
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(getApplicationContext());VisualInsightStore.ensure(db);initialItem=getIntent().getLongExtra("item_id",0);build();refreshAsync();ScreenshotWorkScheduler.kick(this);}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);long id=i.getLongExtra("item_id",0);if(id>0){initialItem=id;openedInitial=false;}refreshAsync();}
    @Override protected void onResume(){super.onResume();if(db!=null&&!destroyed)refreshAsync();}
    @Override protected void onDestroy(){destroyed=true;generation++;handler.removeCallbacksAndMessages(null);loader.shutdownNow();if(db!=null){try{db.close();}catch(Throwable ignored){}db=null;}super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),0);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Vault",29,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);count=CortexUi.plain(this,"Loading…",11,CortexUi.MUTED);titles.addView(count);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView settings=CortexUi.chip(this,"SETTINGS",CortexUi.MUTED,false);settings.setOnClickListener(v->{try{startActivity(new Intent(this,SettingsActivity.class));}catch(Throwable ignored){}});head.addView(settings,new LinearLayout.LayoutParams(-2,dp(36)));body.addView(head);
        LinearLayout sb=CortexUi.card(this,18);sb.setOrientation(LinearLayout.HORIZONTAL);sb.setGravity(Gravity.CENTER_VERTICAL);sb.setPadding(dp(13),0,dp(12),0);TextView mark=CortexUi.plain(this,"⌕",20,CortexUi.MUTED);mark.setGravity(Gravity.CENTER);sb.addView(mark,new LinearLayout.LayoutParams(dp(30),dp(50)));search=new EditText(this);search.setHint("Search words or meaning");search.setHintTextColor(CortexUi.FAINT);search.setTextColor(CortexUi.TEXT);search.setTextSize(14);search.setSingleLine(true);search.setBackgroundColor(Color.TRANSPARENT);search.setPadding(dp(4),0,0,0);sb.addView(search,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout.LayoutParams sbp=new LinearLayout.LayoutParams(-1,dp(50));sbp.setMargins(0,dp(15),0,dp(10));body.addView(sb,sbp);
        search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int a){}public void onTextChanged(CharSequence s,int st,int before,int c){if(pending!=null)handler.removeCallbacks(pending);pending=VaultActivity.this::refreshAsync;handler.postDelayed(pending,220);}public void afterTextChanged(Editable e){}});
        HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);tabs=new LinearLayout(this);tabs.setOrientation(LinearLayout.HORIZONTAL);hsv.addView(tabs);body.addView(hsv,new LinearLayout.LayoutParams(-1,dp(44)));for(String f:new String[]{"ALL","SCREENSHOTS","VOICE","FILES","TEXT"})addTab(f);
        ScrollView sv=new ScrollView(this);sv.setFillViewport(true);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,dp(10),0,dp(20));sv.addView(feed);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"vault",null);setContentView(root);}

    void addTab(String f){boolean on=f.equals(filter);TextView t=CortexUi.chip(this,label(f),on?CortexUi.ACCENT:CortexUi.MUTED,on);t.setTag(f);t.setOnClickListener(v->{if(destroyed)return;filter=(String)v.getTag();styleTabs();refreshAsync();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(34));p.setMargins(0,0,dp(7),0);tabs.addView(t,p);}void styleTabs(){for(int i=0;i<tabs.getChildCount();i++){TextView t=(TextView)tabs.getChildAt(i);boolean on=filter.equals(t.getTag());t.setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);t.setBackground(CortexUi.round(this,on?CortexUi.SURFACE_2:CortexUi.SURFACE,on?CortexUi.ACCENT:CortexUi.BORDER_SOFT,999));if(on)CortexUi.medium(t);}}
    String label(String x){if("SCREENSHOTS".equals(x))return"Images";if("VOICE".equals(x))return"Voice";if("FILES".equals(x))return"Files";if("TEXT".equals(x))return"Text";return"All";}

    void refreshAsync(){if(destroyed||loader.isShutdown())return;final int g=++generation;final String q=search==null?"":search.getText().toString().trim();final String f=filter;try{loader.execute(()->{VaultDb local=null;try{local=new VaultDb(getApplicationContext());ArrayList<KnowledgeItem> raw=local.lexicalSearch(q,90),shown=new ArrayList<>();for(KnowledgeItem k:raw)if(match(k,f)){shown.add(k);if(shown.size()>=60)break;}long total=total(local);postUi(()->{if(g!=generation)return;render(shown,total,q);});}catch(Throwable e){postUi(()->{if(g==generation&&feed!=null){feed.removeAllViews();TextView x=CortexUi.text(this,"Vault search paused safely. Try again.",12,CortexUi.MUTED);feed.addView(x);}});}finally{if(local!=null)try{local.close();}catch(Throwable ignored){}}});}catch(RejectedExecutionException ignored){}}
    void postUi(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())try{r.run();}catch(Throwable ignored){}});}
    boolean match(KnowledgeItem k,String f){if("ALL".equals(f))return true;if("VOICE".equals(f))return"AUDIO".equals(k.type);if("SCREENSHOTS".equals(f))return isShot(k);if("FILES".equals(f))return"FILE".equals(k.type);return!"AUDIO".equals(k.type)&&!isShot(k)&&!"FILE".equals(k.type);}
    void render(ArrayList<KnowledgeItem> xs,long total,String q){if(destroyed||feed==null||count==null)return;count.setText(xs.size()+" shown  •  "+total+" memories");feed.removeAllViews();if(xs.isEmpty()){LinearLayout e=CortexUi.card(this,22);e.setGravity(Gravity.CENTER);e.setPadding(dp(20),dp(40),dp(20),dp(40));TextView h=CortexUi.plain(this,q.isEmpty()?"Nothing here yet":"No matching memory",18,CortexUi.TEXT);CortexUi.medium(h);h.setGravity(Gravity.CENTER);e.addView(h);TextView b=CortexUi.text(this,q.isEmpty()?"Capture something new or choose another filter.":"Try fewer words or another filter.",12,CortexUi.MUTED);b.setGravity(Gravity.CENTER);b.setPadding(0,dp(6),0,0);e.addView(b);feed.addView(e);}else for(KnowledgeItem k:xs)addCard(k);if(initialItem>0&&!openedInitial&&db!=null){openedInitial=true;try{KnowledgeItem k=db.getById(initialItem);if(k!=null)detail(k);}catch(Throwable ignored){}}}

    void addCard(KnowledgeItem k){LinearLayout c=CortexUi.card(this,21);c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(12),dp(12),dp(13),dp(12));CortexUi.pressable(this,c,CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,21));TextView badge=CortexUi.chip(this,badge(k),CortexUi.ACCENT,true);c.addView(badge,new LinearLayout.LayoutParams(dp(58),dp(36)));LinearLayout text=new LinearLayout(this);text.setOrientation(LinearLayout.VERTICAL);text.setPadding(dp(13),0,0,0);TextView title=CortexUi.text(this,displayTitle(k),15,CortexUi.TEXT);CortexUi.medium(title);title.setMaxLines(2);title.setEllipsize(TextUtils.TruncateAt.END);text.addView(title);TextView meta=CortexUi.plain(this,cardMeta(k),10,CortexUi.MUTED);meta.setPadding(0,dp(4),0,0);text.addView(meta);String previewText=preview(k);if(!empty(previewText)){TextView body=CortexUi.text(this,clip(previewText,130),12,CortexUi.MUTED);body.setMaxLines(3);body.setPadding(0,dp(6),0,0);text.addView(body);}c.addView(text,new LinearLayout.LayoutParams(0,-2,1));c.setOnClickListener(v->{if(!destroyed)detail(k);});LinearLayout.LayoutParams cardParams=new LinearLayout.LayoutParams(-1,-2);cardParams.setMargins(0,0,0,dp(9));feed.addView(c,cardParams);}

    void detail(KnowledgeItem k){if(destroyed||db==null||k==null)return;final Dialog d=new Dialog(this);ScrollView sv=new ScrollView(this);LinearLayout b=CortexUi.card(this,26);b.setPadding(dp(18),dp(18),dp(18),dp(18));sv.addView(b);TextView title=CortexUi.text(this,displayTitle(k),21,CortexUi.TEXT);CortexUi.medium(title);b.addView(title);MemoryProvenance.Info provenance=MemoryProvenance.from(this,k);TextView meta=CortexUi.plain(this,detailMeta(k,provenance),10,CortexUi.MUTED);meta.setPadding(0,dp(5),0,dp(12));b.addView(meta);if(provenance.notification){label(b,"Origin");LinearLayout origin=CortexUi.card(this,16);origin.setPadding(dp(13),dp(11),dp(13),dp(11));origin.addView(CortexUi.text(this,"From: "+provenance.sourceLabel(),12,CortexUi.TEXT));origin.addView(provenanceLine("Captured as: "+provenance.captureLabel()));origin.addView(provenanceLine("Received: "+provenance.exactTime()));if(!empty(provenance.channel))origin.addView(provenanceLine("Channel: "+provenance.channel));if(!empty(provenance.packageName))origin.addView(provenanceLine("Package: "+provenance.packageName));b.addView(origin);label(b,"Why Cortex kept it");b.addView(CortexUi.text(this,provenance.whyKept(),12,CortexUi.MUTED));}
        if(isShot(k)&&!empty(k.attachmentPath)){Bitmap bm=previewImage(k.attachmentPath);if(bm!=null){ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.FIT_CENTER);im.setImageBitmap(bm);im.setBackground(CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER_SOFT,18));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,-2);ip.setMargins(0,0,0,dp(13));b.addView(im,ip);d.setOnDismissListener(x->{try{if(!bm.isRecycled())bm.recycle();}catch(Throwable ignored){}});}}
        VisualInsightStore.Insight vi=null;try{vi=isShot(k)?VisualInsightStore.get(db,k.id):null;}catch(Throwable ignored){}if(vi!=null&&vi.ready()&&!empty(vi.description)){label(b,"Visual understanding");b.addView(CortexUi.text(this,vi.description,13,CortexUi.TEXT));}
        String raw=!empty(k.extractedText)?k.extractedText:k.rawText;if(!empty(k.summary)&&VoiceTextPresentation.materiallyDifferent(k.summary,raw)){label(b,"Summary");b.addView(CortexUi.text(this,k.summary,13,CortexUi.TEXT));}if(!empty(raw)){label(b,"AUDIO".equals(k.type)?"Transcript":"Stored evidence");String shown=clip(raw,20000);if(raw.length()>shown.length())shown+="\n\n[Display truncated for stability — full evidence remains stored.]";TextView r=CortexUi.text(this,shown,12,CortexUi.MUTED);r.setTextIsSelectable(true);b.addView(r);}
        LinearLayout buttons=new LinearLayout(this);buttons.setOrientation(LinearLayout.HORIZONTAL);buttons.setPadding(0,dp(16),0,0);TextView close=CortexUi.action(this,"Close",CortexUi.MUTED,false);buttons.addView(close,new LinearLayout.LayoutParams(0,dp(46),1));if(isShot(k)){TextView visual=CortexUi.action(this,"Visual intelligence",CortexUi.ACCENT,true);LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(0,dp(46),1);vp.setMargins(dp(9),0,0,0);buttons.addView(visual,vp);visual.setOnClickListener(v->{d.dismiss();try{Intent i=new Intent(this,VisualIntelligenceActivity.class);i.putExtra("item_id",k.id);startActivity(i);}catch(Throwable ignored){}});}b.addView(buttons);close.setOnClickListener(v->d.dismiss());d.setContentView(sv);Window w=d.getWindow();if(w!=null)w.setBackgroundDrawableResource(android.R.color.transparent);d.setOnShowListener(x->{Window ww=d.getWindow();if(ww!=null)ww.setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94f),(int)(getResources().getDisplayMetrics().heightPixels*.86f));});try{d.show();}catch(Throwable ignored){}}
    TextView provenanceLine(String s){TextView t=CortexUi.text(this,s,11,CortexUi.MUTED);t.setPadding(0,dp(4),0,0);return t;}
    void label(LinearLayout b,String s){TextView h=CortexUi.section(this,s);h.setPadding(0,dp(14),0,dp(7));b.addView(h);}
    Bitmap previewImage(String path){try{return SafeImageDecoder.decode(new File(path),1200,1_600_000L);}catch(Throwable e){return null;}}

    String cardMeta(KnowledgeItem k){MemoryProvenance.Info p=MemoryProvenance.from(this,k);if(p.notification)return"Notification  •  "+p.sourceLabel()+"  •  "+age(p.occurredAt);return friendly(k.type)+"  •  "+age(k.createdAt);}
    String detailMeta(KnowledgeItem k,MemoryProvenance.Info p){if(p.notification)return"Notification  •  "+p.sourceLabel()+"  •  "+p.exactTime();return friendly(k.type)+"  •  "+age(k.createdAt)+"  •  "+(empty(k.source)?"local":k.source);}
    long total(VaultDb source){Cursor c=null;try{c=source.getReadableDatabase().rawQuery("SELECT COUNT(*) FROM knowledge_items",null);return c.moveToFirst()?c.getLong(0):0;}catch(Throwable e){return 0;}finally{if(c!=null)c.close();}}String preview(KnowledgeItem k){if(!empty(k.summary))return k.summary;if(!empty(k.extractedText))return k.extractedText;return k.rawText;}String badge(KnowledgeItem k){if("AUDIO".equals(k.type))return"VOICE";if("NOTIFICATION".equals(k.type))return"NOTIF";if(isShot(k))return"IMAGE";if("FILE".equals(k.type))return"FILE";return"TEXT";}String friendly(String s){if("AUDIO".equals(s))return"Voice";if("NOTIFICATION".equals(s))return"Notification";if("SCREENSHOT".equals(s)||"IMAGE".equals(s))return"Image";if("FILE".equals(s))return"File";return"Memory";}boolean isShot(KnowledgeItem k){return"SCREENSHOT".equals(k.type)||"IMAGE".equals(k.type);}String displayTitle(KnowledgeItem k){String s=clean(k==null?null:k.title);return k!=null&&"AUDIO".equals(k.type)?VoiceTextPresentation.compactTitle(s):s;}String clean(String s){return empty(s)?"Memory":s.trim();}String clip(String s,int n){return s==null?"":s.length()<=n?s:s.substring(0,n)+"…";}boolean empty(String s){return s==null||s.trim().isEmpty();}String age(long ms){long m=Math.max(0,System.currentTimeMillis()-ms)/60000;if(m<1)return"now";if(m<60)return m+"m";long h=m/60;if(h<24)return h+"h";long days=h/24;return days<7?days+"d":new SimpleDateFormat("dd MMM",Locale.getDefault()).format(new Date(ms));}
}
