package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.os.*;
import android.text.*;
import android.view.*;
import android.widget.*;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

/** Capture archive only. Durable knowledge belongs to Brain; this screen is intentional source evidence. */
public class VaultActivity extends Activity {
    VaultDb db;LinearLayout feed,tabs;EditText search;TextView count;String filter="ALL";long initialItem;boolean openedInitial,destroyed;Handler handler=new Handler(Looper.getMainLooper());Runnable pending;volatile int generation;final ExecutorService loader=Executors.newSingleThreadExecutor();
    int dp(int x){return CortexUi.dp(this,x);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(getApplicationContext());VisualInsightStore.ensure(db);initialItem=getIntent().getLongExtra("item_id",0);build();refreshAsync();}
    @Override protected void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);initialItem=i.getLongExtra("item_id",0);openedInitial=false;refreshAsync();}
    @Override protected void onResume(){super.onResume();if(!destroyed)refreshAsync();}
    @Override protected void onDestroy(){destroyed=true;generation++;handler.removeCallbacksAndMessages(null);loader.shutdownNow();if(db!=null)try{db.close();}catch(Throwable ignored){}super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(20),dp(14),dp(20),0);root.addView(body,new LinearLayout.LayoutParams(-1,0,1));LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Captured Evidence",29,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);count=CortexUi.plain(this,"Loading…",11,CortexUi.MUTED);titles.addView(count);head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));TextView settings=CortexUi.chip(this,"SETTINGS",CortexUi.MUTED,false);settings.setOnClickListener(v->startActivity(new Intent(this,SettingsActivity.class)));head.addView(settings,new LinearLayout.LayoutParams(-2,dp(36)));body.addView(head);
        LinearLayout sb=CortexUi.card(this,18);sb.setOrientation(LinearLayout.HORIZONTAL);sb.setGravity(Gravity.CENTER_VERTICAL);sb.setPadding(dp(13),0,dp(12),0);TextView icon=CortexUi.plain(this,"⌕",20,CortexUi.MUTED);icon.setGravity(Gravity.CENTER);sb.addView(icon,new LinearLayout.LayoutParams(dp(30),dp(50)));search=new EditText(this);search.setHint("Search captured evidence");search.setHintTextColor(CortexUi.FAINT);search.setTextColor(CortexUi.TEXT);search.setTextSize(14);search.setSingleLine(true);search.setBackgroundColor(Color.TRANSPARENT);search.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);sb.addView(search,new LinearLayout.LayoutParams(0,dp(50),1));LinearLayout.LayoutParams sp=new LinearLayout.LayoutParams(-1,dp(50));sp.setMargins(0,dp(15),0,dp(10));body.addView(sb,sp);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){if(pending!=null)handler.removeCallbacks(pending);pending=VaultActivity.this::refreshAsync;handler.postDelayed(pending,220);}public void afterTextChanged(Editable e){}});
        HorizontalScrollView hsv=new HorizontalScrollView(this);hsv.setHorizontalScrollBarEnabled(false);tabs=new LinearLayout(this);hsv.addView(tabs);body.addView(hsv,new LinearLayout.LayoutParams(-1,dp(44)));for(String f:new String[]{"ALL","IMAGES","VOICE","FILES","TEXT"})addTab(f);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);feed=new LinearLayout(this);feed.setOrientation(LinearLayout.VERTICAL);feed.setPadding(0,dp(10),0,dp(20));sv.addView(feed);body.addView(sv,new LinearLayout.LayoutParams(-1,0,1));CortexUi.addBottomNav(this,root,"capture",null);setContentView(root);CortexUi.fitSystemBars(this,root);}
    void addTab(String f){TextView t=CortexUi.chip(this,titleCase(f),f.equals(filter)?CortexUi.ACCENT:CortexUi.MUTED,f.equals(filter));t.setTag(f);t.setOnClickListener(v->{filter=(String)v.getTag();styleTabs();refreshAsync();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-2,dp(34));p.setMargins(0,0,dp(7),0);tabs.addView(t,p);}void styleTabs(){for(int i=0;i<tabs.getChildCount();i++){TextView t=(TextView)tabs.getChildAt(i);boolean on=filter.equals(t.getTag());t.setTextColor(on?CortexUi.TEXT:CortexUi.MUTED);t.setBackground(CortexUi.round(this,on?CortexUi.SURFACE_2:CortexUi.SURFACE,on?CortexUi.ACCENT:CortexUi.BORDER_SOFT,999));}}
    void refreshAsync(){if(destroyed||loader.isShutdown())return;int g=++generation;String q=search==null?"":search.getText().toString().trim(),f=filter;try{loader.execute(()->{VaultDb local=null;try{local=new VaultDb(getApplicationContext());ArrayList<KnowledgeItem> raw=local.captureSearch(q,500),intentional=new ArrayList<>(),shown=new ArrayList<>();for(KnowledgeItem k:raw){if(!IntentionalCapturePolicy.visibleInCapturedLibrary(k))continue;intentional.add(k);if(match(k,f)&&shown.size()<60)shown.add(k);}long total=intentional.size();post(()->{if(g==generation)render(shown,total,q);});}catch(Throwable e){post(()->error(e));}finally{if(local!=null)try{local.close();}catch(Throwable ignored){}}});}catch(Throwable ignored){}}
    boolean match(KnowledgeItem k,String f){if("ALL".equals(f))return true;if("VOICE".equals(f))return"AUDIO".equals(k.type);if("IMAGES".equals(f))return isImage(k);if("FILES".equals(f))return"FILE".equals(k.type)||"DOCUMENT".equals(k.type)||"PDF".equals(k.type);return!"AUDIO".equals(k.type)&&!isImage(k)&&!"FILE".equals(k.type)&&!"DOCUMENT".equals(k.type)&&!"PDF".equals(k.type);}
    void render(ArrayList<KnowledgeItem> xs,long total,String q){if(feed==null)return;count.setText(xs.size()+" shown  •  "+total+" captured items");feed.removeAllViews();if(xs.isEmpty()){LinearLayout e=CortexUi.card(this,22);e.setPadding(dp(20),dp(34),dp(20),dp(34));TextView h=CortexUi.plain(this,q.isEmpty()?"No captured evidence yet":"No matching capture",18,CortexUi.TEXT);CortexUi.medium(h);h.setGravity(Gravity.CENTER);e.addView(h);TextView b=CortexUi.text(this,"Things you intentionally capture live here. Passive phone context stays inspectable in its own evidence pipeline.",12,CortexUi.MUTED);b.setGravity(Gravity.CENTER);b.setPadding(0,dp(7),0,0);e.addView(b);feed.addView(e);}else for(KnowledgeItem k:xs)addCard(k);if(initialItem>0&&!openedInitial){openedInitial=true;KnowledgeItem k=db.getById(initialItem);if(k!=null&&IntentionalCapturePolicy.visibleInCapturedLibrary(k))detail(k);}}
    void addCard(KnowledgeItem k){LinearLayout c=CortexUi.card(this,21);c.setOrientation(LinearLayout.HORIZONTAL);c.setGravity(Gravity.CENTER_VERTICAL);c.setPadding(dp(12),dp(12),dp(13),dp(12));TextView badge=CortexUi.chip(this,badge(k),CortexUi.ACCENT,true);c.addView(badge,new LinearLayout.LayoutParams(dp(62),dp(36)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);tx.setPadding(dp(13),0,0,0);TextView h=CortexUi.text(this,displayTitle(k),15,CortexUi.TEXT);CortexUi.medium(h);h.setMaxLines(2);h.setEllipsize(TextUtils.TruncateAt.END);h.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);tx.addView(h);TextView meta=CortexUi.plain(this,friendly(k.type)+"  •  "+age(k.createdAt)+"  •  captured evidence",10,CortexUi.MUTED);meta.setPadding(0,dp(4),0,0);tx.addView(meta);String p=preview(k);if(!p.isEmpty()){TextView b=CortexUi.text(this,clip(p,150),12,CortexUi.MUTED);b.setMaxLines(3);b.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);b.setPadding(0,dp(6),0,0);tx.addView(b);}c.addView(tx,new LinearLayout.LayoutParams(0,-2,1));c.setOnClickListener(v->detail(k));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,0,0,dp(9));feed.addView(c,cp);}
    void detail(KnowledgeItem k){Dialog d=new Dialog(this);ScrollView sv=new ScrollView(this);LinearLayout box=CortexUi.card(this,26);box.setPadding(dp(18),dp(18),dp(18),dp(18));sv.addView(box);TextView h=CortexUi.text(this,displayTitle(k),21,CortexUi.TEXT);CortexUi.medium(h);h.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);box.addView(h);TextView meta=CortexUi.plain(this,friendly(k.type)+"  •  "+exact(k.createdAt)+"  •  "+IntentionalCapturePolicy.sourceLabel(k.source),10,CortexUi.MUTED);meta.setPadding(0,dp(5),0,dp(12));box.addView(meta);if(isImage(k)&&!safe(k.attachmentPath).isEmpty()){Bitmap bm=previewImage(k.attachmentPath);if(bm!=null){ImageView im=new ImageView(this);im.setAdjustViewBounds(true);im.setScaleType(ImageView.ScaleType.FIT_CENTER);im.setImageBitmap(bm);box.addView(im);d.setOnDismissListener(x->{try{if(!bm.isRecycled())bm.recycle();}catch(Throwable ignored){}});}}String text=preview(k);if(!text.isEmpty()){TextView label=CortexUi.section(this,"Stored evidence");box.addView(label);TextView t=CortexUi.text(this,clip(text,20000),12,CortexUi.MUTED);t.setTextIsSelectable(true);t.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);box.addView(t);}if("AUDIO".equals(k.type)){TextView open=CortexUi.action(this,"Open voice detail",CortexUi.LIME,true);LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,dp(46));op.setMargins(0,dp(16),0,0);box.addView(open,op);open.setOnClickListener(v->{d.dismiss();Intent i=new Intent(this,VoiceDetailActivity.class);i.putExtra("item_id",k.id);startActivity(i);});}TextView close=CortexUi.action(this,"Close",CortexUi.MUTED,false);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(46));p.setMargins(0,dp(10),0,0);box.addView(close,p);close.setOnClickListener(v->d.dismiss());d.setContentView(sv);try{d.show();if(d.getWindow()!=null){d.getWindow().setBackgroundDrawableResource(android.R.color.transparent);d.getWindow().setDimAmount(.72f);d.getWindow().addFlags(WindowManager.LayoutParams.FLAG_DIM_BEHIND);d.getWindow().setLayout((int)(getResources().getDisplayMetrics().widthPixels*.94f),WindowManager.LayoutParams.WRAP_CONTENT);}}catch(Throwable ignored){}}
    Bitmap previewImage(String path){try{return SafeImageDecoder.decode(new File(path),1200,1_600_000L);}catch(Throwable e){return null;}}
    void error(Throwable e){if(feed==null)return;feed.removeAllViews();feed.addView(CortexUi.text(this,"Captured evidence could not be loaded safely. "+e.getClass().getSimpleName(),12,CortexUi.MUTED));}void post(Runnable r){if(!destroyed)runOnUiThread(()->{if(!destroyed)r.run();});}
    String preview(KnowledgeItem k){String s=!safe(k.summary).isEmpty()?k.summary:(!safe(k.extractedText).isEmpty()?k.extractedText:k.rawText);return CanonicalPresentation.cleanBody(s);}String displayTitle(KnowledgeItem k){return CanonicalPresentation.cleanTitle(k.type,k.type,k.title,k.title);}String badge(KnowledgeItem k){if("AUDIO".equals(k.type))return"VOICE";if(isImage(k))return"IMAGE";if("FILE".equals(k.type)||"DOCUMENT".equals(k.type)||"PDF".equals(k.type))return"FILE";return"TEXT";}String friendly(String t){if("AUDIO".equals(t))return"Voice";if(isImageType(t))return"Image";if("FILE".equals(t)||"DOCUMENT".equals(t)||"PDF".equals(t))return"File";return"Text";}boolean isImage(KnowledgeItem k){return isImageType(k.type);}boolean isImageType(String t){return"SCREENSHOT".equals(t)||"IMAGE".equals(t);}String safe(String s){return s==null?"":s.trim();}String clip(String s,int n){return s==null?"":s.length()<=n?s:s.substring(0,n)+"…";}String titleCase(String s){if("ALL".equals(s))return"All";return s.substring(0,1)+s.substring(1).toLowerCase(Locale.ROOT);}String age(long ms){long m=Math.max(0,System.currentTimeMillis()-ms)/60000;if(m<1)return"now";if(m<60)return m+"m";long h=m/60;if(h<24)return h+"h";return(h/24)+"d";}String exact(long ms){return new SimpleDateFormat("dd MMM yyyy • HH:mm",Locale.getDefault()).format(new Date(ms));}
}
