package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.File;
import java.net.URLEncoder;
import java.util.*;

/** Human-facing inspector: original image first, then meaning, text, usefulness and actions. */
public class VisualIntelligenceActivity extends Activity {
    VaultDb db;KnowledgeItem item;VisualInsightStore.Insight insight;LinearLayout box;ImageView image;TextView title,state,description,visible,usefulness,actions;Button analyze,search,copy,useful,notUseful,older;
    int bg=Color.rgb(11,12,14),surface=Color.rgb(24,26,30),text=Color.rgb(245,244,240),muted=Color.rgb(156,159,168),accent=Color.rgb(232,177,72),ok=Color.rgb(120,205,150),danger=Color.rgb(246,124,118),border=Color.rgb(47,50,57);
    int dp(int x){return(int)(x*getResources().getDisplayMetrics().density+.5f);}TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setTextSize(sp);v.setTextColor(c);CortexTextUi.setReadable(v,s);return v;}GradientDrawable round(int fill,int stroke,int r){GradientDrawable g=new GradientDrawable();g.setColor(fill);g.setCornerRadius(dp(r));g.setStroke(dp(1),stroke);return g;}
    @Override public void onCreate(Bundle b){super.onCreate(b);db=new VaultDb(this);VisualInsightStore.ensure(db);build();long id=getIntent().getLongExtra("item_id",0);load(id>0?id:latest());}

    void build(){ScrollView sv=new ScrollView(this);box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.setPadding(dp(16),dp(16),dp(16),dp(32));box.setBackgroundColor(bg);sv.addView(box);TextView h=tv("VISUAL INTELLIGENCE",27,text);h.setTypeface(null,1);box.addView(h);TextView sub=tv("See the actual image, what Cortex understands, why it may matter, and what you can do with it.",13,muted);sub.setPadding(0,dp(4),0,dp(14));box.addView(sub);
        image=new ImageView(this);image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setBackground(round(surface,border,18));box.addView(image,new LinearLayout.LayoutParams(-1,-2));
        title=card("IMAGE");state=card("CORTEX STATUS");description=card("CORTEX SEES");visible=card("VISIBLE TEXT");usefulness=card("WHY THIS MAY MATTER");actions=card("SUGGESTED ACTIONS");
        analyze=button("ANALYZE THIS IMAGE WITH STRONG VISION");analyze.setOnClickListener(v->analyze(false));box.addView(analyze,lp());search=button("SEARCH THIS ONLINE");search.setOnClickListener(v->search());box.addView(search,lp());copy=button("COPY RECREATE PROMPT");copy.setOnClickListener(v->copyPrompt());box.addView(copy,lp());
        LinearLayout votes=new LinearLayout(this);votes.setOrientation(LinearLayout.HORIZONTAL);useful=button("USEFUL");notUseful=button("NOT USEFUL");useful.setOnClickListener(v->vote(1));notUseful.setOnClickListener(v->vote(-1));votes.addView(useful,new LinearLayout.LayoutParams(0,dp(48),1));LinearLayout.LayoutParams np=new LinearLayout.LayoutParams(0,dp(48),1);np.setMargins(dp(8),0,0,0);votes.addView(notUseful,np);box.addView(votes,new LinearLayout.LayoutParams(-1,dp(48)));
        older=button("OPEN NEXT OLDER SCREENSHOT");older.setOnClickListener(v->{long id=olderThan(item==null?Long.MAX_VALUE:item.createdAt);if(id>0)load(id);else Toast.makeText(this,"No older screenshot found",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams op=lp();op.setMargins(0,dp(9),0,0);box.addView(older,op);setContentView(sv);}
    TextView card(String label){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(15),dp(13),dp(15),dp(13));c.setBackground(round(surface,border,18));TextView l=tv(label,11,accent);l.setTypeface(null,1);c.addView(l);TextView x=tv("",13,text);x.setPadding(0,dp(6),0,0);c.addView(x);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(10),0,0);box.addView(c,p);return x;}
    Button button(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(text);b.setAllCaps(false);b.setBackground(round(surface,border,16));return b;}LinearLayout.LayoutParams lp(){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(48));p.setMargins(0,dp(9),0,0);return p;}

    void load(long id){item=id>0?db.getById(id):null;if(item==null){title.setText("No screenshot available");return;}insight=VisualInsightStore.get(db,item.id);title.setText(clean(item.title)+"\nCaptured: "+new java.text.SimpleDateFormat("dd MMM • HH:mm",Locale.getDefault()).format(new Date(item.createdAt)));showImage(item.attachmentPath);refresh();}
    void refresh(){insight=VisualInsightStore.get(db,item.id);if(insight==null){VisualTriage.Result t=VisualTriage.evaluate(item);state.setText("Stored in Vault. Strong visual understanding has not run yet.\nLocal value score: "+t.valueScore+"/100\nPrivacy pre-check: "+t.privacy+"\n"+t.reason);description.setText("Not analyzed visually yet.");visible.setText(item.extractedText==null||item.extractedText.trim().isEmpty()?"Quick OCR found no readable text. This does not mean the image has no useful visual content.":clip(item.extractedText,1600));usefulness.setText("Run strong vision to learn what the image is, what it contains and how it could help you.");actions.setText("No visual actions generated yet.");analyze.setText(t.sensitive?"REVIEW PRIVACY + ANALYZE":"ANALYZE THIS IMAGE WITH STRONG VISION");search.setEnabled(false);copy.setEnabled(false);useful.setEnabled(false);notUseful.setEnabled(false);return;}
        if("local_only".equals(insight.status)){state.setText("Protected locally • not sent to cloud\n"+insight.error);description.setText("Cloud vision was blocked by the local privacy guard.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1600));usefulness.setText("You can explicitly override the privacy block for this image if you decide it is safe.");actions.setText("No cloud actions generated.");analyze.setText("ANALYZE IN CLOUD ANYWAY");analyze.setEnabled(true);search.setEnabled(false);copy.setEnabled(false);return;}
        if("failed".equals(insight.status)||"waiting_provider".equals(insight.status)){state.setText(("failed".equals(insight.status)?"Vision analysis failed":"Waiting for provider")+"\n"+insight.error);analyze.setText("TRY VISUAL ANALYSIS AGAIN");description.setText("No reliable visual result yet.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1600));usefulness.setText("");actions.setText("");return;}
        if("skipped".equals(insight.status)){state.setText("Skipped by local value filter\n"+insight.error);description.setText("This looked like transient/low-value UI. The original image remains safely stored in Vault.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1600));usefulness.setText("Override the filter if you want a full visual analysis.");actions.setText("");analyze.setText("ANALYZE ANYWAY");return;}
        state.setText("Visual understanding ready • "+insight.provider+"\nType: "+friendly(insight.contentType)+" • usefulness "+insight.usefulnessScore+"/100"+(insight.userValue==1?" • marked useful":insight.userValue==-1?" • marked not useful":""));description.setText(empty(insight.description,"No description returned."));visible.setText(empty(insight.visibleText,"The vision model found no important readable text."));usefulness.setText(empty(insight.usefulnessReason,"No strong usefulness signal returned."));ArrayList<String> labels=insight.actionLabels();actions.setText(labels.isEmpty()?"Reference only":bullets(labels));analyze.setText("RE-ANALYZE WITH STRONG VISION");search.setEnabled(insight.searchQuery!=null&&!insight.searchQuery.trim().isEmpty());copy.setEnabled(insight.recreationPrompt!=null&&!insight.recreationPrompt.trim().isEmpty());useful.setEnabled(true);notUseful.setEnabled(true);}

    void analyze(boolean override){VisualTriage.Result t=VisualTriage.evaluate(item);if((t.sensitive||"local_only".equals(insight==null?"":insight.status))&&!override){new AlertDialog.Builder(this).setTitle("Privacy guard blocked cloud vision").setMessage(t.reason+"\n\nThe original stays local. Send this image to Gemini anyway?").setPositiveButton("Send anyway",(d,w)->analyze(true)).setNegativeButton("Keep local",null).show();return;}analyze.setEnabled(false);state.setText("Understanding the actual image…\nObjects • text • context • usefulness • actions");new Thread(()->{try{JSONObject r=GeminiVisionAnalyzer.analyze(this,item);VisualInsightStore.saveModel(db,item.id,r.optString("_provider","gemini-vision"),r);runOnUiThread(()->{analyze.setEnabled(true);refresh();Toast.makeText(this,"Visual understanding saved to Vault",Toast.LENGTH_LONG).show();});}catch(Exception e){VisualInsightStore.saveState(db,item.id,"failed","safe",e.getMessage());runOnUiThread(()->{analyze.setEnabled(true);refresh();});}}).start();}
    void search(){if(insight==null||insight.searchQuery.trim().isEmpty())return;try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?q="+URLEncoder.encode(insight.searchQuery,"UTF-8"))));}catch(Exception e){Toast.makeText(this,"Could not open web search",Toast.LENGTH_SHORT).show();}}
    void copyPrompt(){if(insight==null||insight.recreationPrompt.trim().isEmpty())return;android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("Cortex recreation prompt",insight.recreationPrompt));Toast.makeText(this,"Recreation prompt copied",Toast.LENGTH_SHORT).show();}
    void vote(int v){VisualInsightStore.setUserValue(db,item.id,v);refresh();Toast.makeText(this,v>0?"Marked useful — Cortex can learn from this":"Marked not useful",Toast.LENGTH_SHORT).show();}
    void showImage(String path){try{File f=new File(path==null?"":path);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeFile(f.getAbsolutePath(),o);int sample=1;while(Math.max(o.outWidth,o.outHeight)/sample>1800)sample*=2;BitmapFactory.Options d=new BitmapFactory.Options();d.inSampleSize=sample;image.setImageBitmap(BitmapFactory.decodeFile(f.getAbsolutePath(),d));}catch(Exception e){image.setImageDrawable(null);}}
    long latest(){Cursor c=db.getReadableDatabase().rawQuery("SELECT id FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') ORDER BY created_at DESC LIMIT 1",null);long id=c.moveToFirst()?c.getLong(0):0;c.close();return id;}
    long olderThan(long at){Cursor c=db.getReadableDatabase().rawQuery("SELECT id FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND created_at<? ORDER BY created_at DESC LIMIT 1",new String[]{String.valueOf(at)});long id=c.moveToFirst()?c.getLong(0):0;c.close();return id;}
    String bullets(ArrayList<String>a){StringBuilder b=new StringBuilder();for(String x:a)b.append("• ").append(x).append('\n');return b.toString().trim();}String clean(String s){return s==null||s.trim().isEmpty()?"Screenshot":s.trim();}String clip(String s,int n){return s==null?"":(s.length()<=n?s:s.substring(0,n)+"…");}String friendly(String s){return s==null?"unknown":s.replace('_',' ');}String empty(String s,String fallback){return s==null||s.trim().isEmpty()?fallback:s.trim();}
}
