package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.os.Bundle;
import android.view.*;
import android.widget.*;
import java.util.*;

/** User-visible recovery truth for strong visual understanding. Mutations are explicit and bounded. */
public final class VisualRecoveryActivity extends Activity {
    VaultDb db;LinearLayout body,issuesHost;TextView summary;
    int dp(int x){return CortexUi.dp(this,x);}

    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);VisualInsightStore.ensure(db);VisualRecoveryStore.ensure(db);VisualRecoveryStore.adoptLegacyFailures(db);build();refresh();}
    @Override protected void onResume(){super.onResume();refresh();}
    @Override protected void onDestroy(){if(db!=null)try{db.close();}catch(Throwable ignored){}db=null;super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(12),dp(18),dp(28));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout titles=new LinearLayout(this);titles.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Visual recovery",27,CortexUi.TEXT);CortexUi.medium(h);titles.addView(h);titles.addView(CortexUi.plain(this,"Recovering is not failure. Terminal is not success.",10,CortexUi.MUTED));head.addView(titles,new LinearLayout.LayoutParams(0,-2,1));body.addView(head);
        LinearLayout card=CortexUi.card(this,18);card.setPadding(dp(13),dp(12),dp(13),dp(12));summary=CortexUi.text(this,"",11,CortexUi.TEXT);card.addView(summary);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(0,dp(12),0,0);body.addView(card,cp);
        LinearLayout controls=new LinearLayout(this);controls.setOrientation(LinearLayout.HORIZONTAL);controls.setPadding(0,dp(8),0,0);TextView retry=CortexUi.action(this,"Retry recoverable now",CortexUi.ORANGE,false);TextView latest=CortexUi.action(this,"Open latest issue",CortexUi.YELLOW,false);controls.addView(retry,new LinearLayout.LayoutParams(0,dp(44),1));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(44),1);lp.setMargins(dp(8),0,0,0);controls.addView(latest,lp);body.addView(controls);retry.setOnClickListener(v->retryRecoverable());latest.setOnClickListener(v->openLatest());
        TextView reset=CortexUi.action(this,"Reset terminal retry budget…",CortexUi.RED,false);LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,dp(44));rp.setMargins(0,dp(8),0,0);body.addView(reset,rp);reset.setOnClickListener(v->confirmResetTerminal());
        TextView boundary=CortexUi.plain(this,"Retry-now preserves attempt counts. Terminal reset is separate because it deliberately starts a fresh bounded retry budget after the underlying image/provider problem has been fixed.",9,CortexUi.MUTED);boundary.setPadding(dp(2),dp(7),dp(2),dp(5));body.addView(boundary);
        issuesHost=new LinearLayout(this);issuesHost.setOrientation(LinearLayout.VERTICAL);body.addView(issuesHost,new LinearLayout.LayoutParams(-1,-2));setContentView(root);CortexUi.fitSystemBars(this,root);}

    void refresh(){if(db==null||issuesHost==null)return;VisualRecoveryStore.adoptLegacyFailures(db);int done=VisualInsightStore.countDone(db),recovering=VisualRecoveryStore.countRecoverable(db),terminal=VisualRecoveryStore.countTerminal(db),rate=VisualInsightStore.countRateLimited(db);long delay=VisualRecoveryStore.nextDelayMs(db);String worker=VisualInsightStore.workerState(this),stage=VisualInsightStore.workerStage(this),detail=VisualInsightStore.workerDetail(this);StringBuilder s=new StringBuilder();s.append("DONE · ").append(done).append("\nRECOVERING · ").append(recovering).append("\nTERMINAL · ").append(terminal).append("\nRATE LIMITED · ").append(rate);if(delay>0)s.append("\nNEXT AUTOMATIC RETRY · ~").append(Math.max(1,Math.round(delay/1000.0))).append("s");s.append("\nWORKER · ").append(empty(worker,"idle"));if(!stage.isEmpty())s.append(" · ").append(stage);if(!detail.isEmpty())s.append("\n").append(clip(detail,220));summary.setText(s.toString());
        issuesHost.removeAllViews();TextView head=CortexUi.plain(this,"UNRESOLVED ITEMS",9,CortexUi.MUTED);CortexUi.medium(head);head.setPadding(dp(2),dp(18),0,dp(8));issuesHost.addView(head);int added=listIssues();if(added==0){TextView empty=CortexUi.text(this,"No unresolved visual recovery items.",11,CortexUi.MUTED);empty.setPadding(dp(3),dp(8),dp(3),dp(8));issuesHost.addView(empty);}}

    int listIssues(){Cursor c=null;int n=0;try{c=db.getReadableDatabase().rawQuery("SELECT r.item_id,r.attempt_count,r.failure_kind,r.recoverable,r.next_retry_at,r.next_action,r.last_error,r.updated_at,COALESCE(k.title,''),COALESCE(v.status,'') FROM visual_recovery r LEFT JOIN knowledge_items k ON k.id=r.item_id LEFT JOIN visual_insights v ON v.item_id=r.item_id WHERE COALESCE(v.status,'') NOT IN ('done','local_only','skipped') ORDER BY r.recoverable DESC,r.updated_at DESC LIMIT 30",null);while(c.moveToNext()){long id=c.getLong(0),next=c.getLong(4);int attempts=c.getInt(1);String kind=n(c.getString(2)),action=n(c.getString(5)),error=n(c.getString(6)),title=n(c.getString(8)),status=n(c.getString(9));boolean recoverable=c.getInt(3)!=0;LinearLayout row=CortexUi.card(this,16);row.setPadding(dp(11),dp(10),dp(11),dp(10));LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);int color=recoverable?CortexUi.ORANGE:CortexUi.RED;top.addView(CortexUi.glyph(this,recoverable?"clock":"action",color,false),new LinearLayout.LayoutParams(dp(34),dp(34)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);LinearLayout.LayoutParams xp=new LinearLayout.LayoutParams(0,-2,1);xp.setMargins(dp(9),0,dp(6),0);top.addView(tx,xp);TextView t=CortexUi.text(this,title.isEmpty()?"Image #"+id:title,12,CortexUi.TEXT);CortexUi.medium(t);t.setMaxLines(1);tx.addView(t);String state=(recoverable?"RECOVERING":"TERMINAL")+" · "+empty(kind,"unknown")+" · attempt "+attempts+"/"+VisualFailurePolicy.MAX_TRANSIENT_ATTEMPTS;TextView m=CortexUi.plain(this,state,8,color);m.setPadding(0,dp(3),0,0);tx.addView(m);TextView open=CortexUi.chip(this,"OPEN",color,false);top.addView(open,new LinearLayout.LayoutParams(-2,dp(30)));row.addView(top);StringBuilder d=new StringBuilder();if(!status.isEmpty())d.append("status: ").append(status);if(recoverable&&next>System.currentTimeMillis())d.append(d.length()>0?" · ":"").append("retry ~").append(Math.max(1,Math.round((next-System.currentTimeMillis())/1000.0))).append("s");if(!action.isEmpty())d.append("\nNext action: ").append(action);if(!error.isEmpty())d.append("\nLast error: ").append(clip(error,220));TextView details=CortexUi.text(this,d.toString(),9,CortexUi.MUTED);details.setPadding(dp(1),dp(6),0,0);row.addView(details);row.setOnClickListener(v->openItem(id));LinearLayout.LayoutParams rp=new LinearLayout.LayoutParams(-1,-2);rp.setMargins(0,0,0,dp(8));issuesHost.addView(row,rp);n++;}}catch(Throwable e){TextView err=CortexUi.text(this,"Could not read visual recovery ledger: "+e.getClass().getSimpleName(),10,CortexUi.RED);issuesHost.addView(err);}finally{if(c!=null)c.close();}return n;}

    void retryRecoverable(){if(db==null)return;int n=VisualRecoveryStore.retryRecoverableNow(db);if(n>0){VisualIntelligenceScheduler.kick(this);CortexHaptics.confirm(summary);Toast.makeText(this,"Queued "+n+" recoverable visual item"+(n==1?"":"s")+" using existing bounded attempt history",Toast.LENGTH_LONG).show();}else Toast.makeText(this,"No recoverable visual items to retry",Toast.LENGTH_SHORT).show();refresh();}
    void openLatest(){long id=VisualRecoveryStore.latestIssueId(db);if(id<=0){Toast.makeText(this,"No unresolved visual issue",Toast.LENGTH_SHORT).show();return;}openItem(id);}
    void openItem(long id){Intent i=new Intent(this,VisualIntelligenceActivity.class);i.putExtra("item_id",id);startActivity(i);}
    void confirmResetTerminal(){int terminal=VisualRecoveryStore.countTerminal(db);if(terminal<=0){Toast.makeText(this,"No terminal visual failures",Toast.LENGTH_SHORT).show();return;}new AlertDialog.Builder(this).setTitle("Reset terminal retry budget?").setMessage(terminal+" terminal visual item"+(terminal==1?" has":"s have")+" exhausted or non-recoverable retry state. Use this only after fixing the provider, access or archived-image cause. Cortex will start a fresh bounded retry budget; successful/protected items are untouched.").setNegativeButton("Cancel",null).setPositiveButton("Reset + retry",(d,w)->{int n=VisualRecoveryStore.resetTerminalBudget(db,Math.min(100,terminal));if(n>0){VisualIntelligenceScheduler.kick(this);CortexHaptics.confirm(summary);Toast.makeText(this,"Reset "+n+" terminal visual retry budget"+(n==1?"":"s"),Toast.LENGTH_LONG).show();}refresh();}).show();}
    static String clip(String s,int max){String x=n(s).replaceAll("\\s+"," ");return x.length()<=max?x:x.substring(0,max)+"…";}static String empty(String s,String fallback){String x=n(s);return x.isEmpty()?fallback:x;}static String n(String s){return s==null?"":s.trim();}
}
