package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.net.Uri;
import android.os.Bundle;
import android.os.SystemClock;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.File;
import java.net.URLEncoder;
import java.util.*;

/** v50 image-first inspector: original evidence, Cortex understanding, privacy and executable actions. */
public class VisualIntelligenceActivity extends Activity {
    VaultDb db;KnowledgeItem item;VisualInsightStore.Insight insight;LinearLayout body,actionRow;ImageView image;TextView title,state,description,visible,usefulness,actions,analyze,search,copy,useful,notUseful,older;
    int dp(int x){return CortexUi.dp(this,x);}TextView tv(String s,int sp,int c){return CortexUi.text(this,s,sp,c);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(this);VisualInsightStore.ensure(db);InteractionTelemetry.ensure(db);build();long id=getIntent().getLongExtra("item_id",0);load(id>0?id:latest());}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(13),dp(16),dp(24));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout hs=new LinearLayout(this);hs.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Visual Intelligence",25,CortexUi.TEXT);CortexUi.medium(h);hs.addView(h);hs.addView(CortexUi.plain(this,"See what Cortex sees — without losing the original.",11,CortexUi.MUTED));head.addView(hs,new LinearLayout.LayoutParams(0,-2,1));body.addView(head);
        image=new ImageView(this);image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setBackground(CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,22));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,-2);ip.setMargins(0,dp(12),0,0);body.addView(image,ip);
        title=infoCard("IMAGE",CortexUi.MUTED);state=infoCard("STATUS",CortexUi.COPPER);description=infoCard("WHAT CORTEX SEES",CortexUi.TEXT);usefulness=infoCard("WHY IT MAY MATTER",CortexUi.GOLD);actions=infoCard("USEFUL ACTIONS",CortexUi.COPPER);visible=infoCard("VISIBLE TEXT",CortexUi.MUTED);
        analyze=CortexUi.action(this,"✦  Understand this image",CortexUi.COPPER,true);analyze.setOnClickListener(v->analyze(false));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(50));ap.setMargins(0,dp(12),0,0);body.addView(analyze,ap);
        actionRow=new LinearLayout(this);actionRow.setOrientation(LinearLayout.HORIZONTAL);actionRow.setPadding(0,dp(9),0,0);search=CortexUi.action(this,"Search",CortexUi.COPPER,false);copy=CortexUi.action(this,"Prompt",CortexUi.GOLD,false);useful=CortexUi.action(this,"Useful",CortexUi.SAGE,false);notUseful=CortexUi.action(this,"Not useful",CortexUi.CORAL,false);search.setOnClickListener(v->search());copy.setOnClickListener(v->copyPrompt());useful.setOnClickListener(v->vote(1));notUseful.setOnClickListener(v->vote(-1));addAction(search,0);addAction(copy,7);body.addView(actionRow,new LinearLayout.LayoutParams(-1,dp(53)));
        LinearLayout voteRow=new LinearLayout(this);voteRow.setOrientation(LinearLayout.HORIZONTAL);addTo(voteRow,useful,0);addTo(voteRow,notUseful,7);LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(-1,dp(46));vp.setMargins(0,dp(8),0,0);body.addView(voteRow,vp);
        older=CortexUi.action(this,"Open next older screenshot",CortexUi.MUTED,false);older.setOnClickListener(v->{long id=olderThan(item==null?Long.MAX_VALUE:item.createdAt);if(id>0)load(id);else Toast.makeText(this,"No older screenshot found",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,dp(44));op.setMargins(0,dp(9),0,0);body.addView(older,op);setContentView(root);}
    TextView infoCard(String label,int accent){LinearLayout c=CortexUi.card(this,20);c.setPadding(dp(15),dp(13),dp(15),dp(14));TextView l=CortexUi.plain(this,label,10,accent);CortexUi.medium(l);l.setLetterSpacing(.08f);c.addView(l);TextView x=tv("",13,CortexUi.TEXT);x.setPadding(0,dp(7),0,0);x.setTextIsSelectable(true);c.addView(x);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(9),0,0);body.addView(c,p);return x;}void addAction(View v,int left){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(44),1);p.setMargins(dp(left),0,0,0);actionRow.addView(v,p);}void addTo(LinearLayout r,View v,int left){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(left),0,0,0);r.addView(v,p);}

    void load(long id){item=id>0?db.getById(id):null;if(item==null){title.setText("No screenshot available");return;}insight=VisualInsightStore.get(db,item.id);title.setText(clean(item.title)+"\nCaptured "+new java.text.SimpleDateFormat("dd MMM • HH:mm",Locale.getDefault()).format(new Date(item.createdAt)));showImage(item.attachmentPath);refresh();}
    void refresh(){if(item==null)return;insight=VisualInsightStore.get(db,item.id);if(insight==null){VisualTriage.Result t=VisualTriage.evaluate(item);state.setText((t.sensitive?"Protected locally":"Ready for visual understanding")+"\nPrivacy: "+t.privacy+" • score "+t.privacyScore+"/100\n"+t.reason);description.setText("Strong visual understanding has not run yet.");visible.setText(item.extractedText==null||item.extractedText.trim().isEmpty()?"Supporting OCR found no reliable text. The image may still contain useful visual information.":clip(item.extractedText,1500));usefulness.setText("Run strong vision to understand objects, context, visual style, important text and possible uses.");actions.setText("No actions generated yet.");analyze.setText(t.sensitive?"Review privacy + analyze":"✦  Understand this image");enable(false,false,false);return;}
        if("local_only".equals(insight.status)){state.setText("Protected locally • not sent to cloud\n"+insight.error);description.setText("Privacy Guard v2 blocked automatic cloud analysis.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1500));usefulness.setText("The original stays local. You can explicitly override this block if you decide the image is safe to send.");actions.setText("No cloud actions generated.");analyze.setText("Analyze in cloud anyway");enable(false,false,false);return;}
        if("failed".equals(insight.status)||"waiting_provider".equals(insight.status)){state.setText(("failed".equals(insight.status)?"Visual analysis failed":"Waiting for provider")+"\n"+insight.error);description.setText("No reliable visual result yet.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1500));usefulness.setText("Retry when ready.");actions.setText("No actions available yet.");analyze.setText("Try visual analysis again");enable(false,false,false);return;}
        if("skipped".equals(insight.status)){state.setText("Skipped as low-value/transient UI\n"+insight.error);description.setText("The original remains in Vault.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1500));usefulness.setText("Override the filter if this screen matters to you.");actions.setText("No actions generated.");analyze.setText("Analyze anyway");enable(false,false,false);return;}
        state.setText("Understanding ready  •  "+friendly(insight.contentType)+"\n"+insight.provider+"  •  usefulness "+insight.usefulnessScore+"/10"+(insight.userValue==1?"  •  marked useful":insight.userValue==-1?"  •  marked not useful":""));description.setText(empty(insight.description,"No description returned."));visible.setText(empty(insight.visibleText,"No important readable text was returned."));usefulness.setText(empty(insight.usefulnessReason,"No strong usefulness signal returned."));ArrayList<String> labels=insight.actionLabels();actions.setText(labels.isEmpty()?"Reference only":bullets(labels));analyze.setText("Re-analyze with strong vision");enable(insight.searchQuery!=null&&!insight.searchQuery.trim().isEmpty(),insight.recreationPrompt!=null&&!insight.recreationPrompt.trim().isEmpty(),true);}
    void enable(boolean canSearch,boolean canPrompt,boolean canVote){search.setEnabled(canSearch);copy.setEnabled(canPrompt);useful.setEnabled(canVote);notUseful.setEnabled(canVote);search.setAlpha(canSearch?1f:.35f);copy.setAlpha(canPrompt?1f:.35f);useful.setAlpha(canVote?1f:.35f);notUseful.setAlpha(canVote?1f:.35f);analyze.setEnabled(true);}

    void analyze(boolean override){long tap=SystemClock.elapsedRealtime();InteractionTelemetry.log(db,"Visual Intelligence","analyze_image","tap",item==null?0:item.id,0,"received",override?"Cloud privacy override requested":"Analyze button tapped",null);VisualTriage.Result t=VisualTriage.evaluate(item);if((t.sensitive||"local_only".equals(insight==null?"":insight.status))&&!override){InteractionTelemetry.log(db,"Visual Intelligence","analyze_image","privacy_block",item.id,SystemClock.elapsedRealtime()-tap,"blocked",t.reason,null);new AlertDialog.Builder(this).setTitle("Protected by Privacy Guard").setMessage(t.reason+"\n\nThis image has not been sent to Gemini. Send it anyway?").setPositiveButton("Send anyway",(d,w)->analyze(true)).setNegativeButton("Keep local",null).show();return;}analyze.setEnabled(false);analyze.setText("Tap received • starting…");state.setText("Preparing strong visual understanding…\nNext: upload → understand → extract useful actions");long ack=SystemClock.elapsedRealtime()-tap;InteractionTelemetry.log(db,"Visual Intelligence","analyze_image","ui_ack",item.id,ack,"ok","UI acknowledged analysis request",null);new Thread(()->{long work=SystemClock.elapsedRealtime();try{runOnUiThread(()->{analyze.setText("Understanding image…");state.setText("Strong vision is reading the actual image…\nObjects • Arabic/English text • context • usefulness • actions");});JSONObject r=GeminiVisionAnalyzer.analyze(this,item);long providerMs=SystemClock.elapsedRealtime()-work;VisualInsightStore.saveModel(db,item.id,r.optString("_provider","gemini-vision"),r);JSONObject metrics=new JSONObject().put("provider",r.optString("_provider","")).put("provider_ms",providerMs).put("privacy_override",override).put("diagnostics",r.optJSONObject("_diagnostics"));InteractionTelemetry.log(db,"Visual Intelligence","analyze_image","complete",item.id,SystemClock.elapsedRealtime()-tap,"ok","Visual understanding saved",metrics);runOnUiThread(()->{analyze.setEnabled(true);refresh();Toast.makeText(this,"Visual understanding saved",Toast.LENGTH_LONG).show();});}catch(Exception e){String msg=e.getClass().getSimpleName()+": "+(e.getMessage()==null?"":e.getMessage());VisualInsightStore.saveState(db,item.id,"failed",t.sensitive?"local_override":"safe",msg);InteractionTelemetry.log(db,"Visual Intelligence","analyze_image","complete",item.id,SystemClock.elapsedRealtime()-tap,"failed",msg,null);runOnUiThread(()->{analyze.setEnabled(true);refresh();});}}).start();}
    void search(){if(insight==null||insight.searchQuery.trim().isEmpty())return;long t=SystemClock.elapsedRealtime();InteractionTelemetry.log(db,"Visual Intelligence","search_online","tap",item.id,0,"received",insight.searchQuery,null);try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?q="+URLEncoder.encode(insight.searchQuery,"UTF-8"))));InteractionTelemetry.log(db,"Visual Intelligence","search_online","intent_opened",item.id,SystemClock.elapsedRealtime()-t,"ok","Browser search intent opened",null);}catch(Exception e){InteractionTelemetry.log(db,"Visual Intelligence","search_online","intent_opened",item.id,SystemClock.elapsedRealtime()-t,"failed",e.toString(),null);Toast.makeText(this,"Could not open web search",Toast.LENGTH_SHORT).show();}}
    void copyPrompt(){if(insight==null||insight.recreationPrompt.trim().isEmpty())return;long t=SystemClock.elapsedRealtime();android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);c.setPrimaryClip(ClipData.newPlainText("Cortex recreation prompt",insight.recreationPrompt));InteractionTelemetry.log(db,"Visual Intelligence","copy_recreate_prompt","complete",item.id,SystemClock.elapsedRealtime()-t,"ok","Recreation prompt copied to clipboard",null);Toast.makeText(this,"Recreation prompt copied",Toast.LENGTH_SHORT).show();}
    void vote(int v){VisualInsightStore.setUserValue(db,item.id,v);InteractionTelemetry.log(db,"Visual Intelligence","rate_insight","complete",item.id,0,"ok",v>0?"useful":"not_useful",null);refresh();Toast.makeText(this,v>0?"Marked useful — Cortex can learn from this":"Marked not useful",Toast.LENGTH_SHORT).show();}
    void showImage(String path){try{File f=new File(path==null?"":path);BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeFile(f.getAbsolutePath(),o);int sample=1;while(Math.max(o.outWidth,o.outHeight)/sample>1800)sample*=2;BitmapFactory.Options d=new BitmapFactory.Options();d.inSampleSize=sample;image.setImageBitmap(BitmapFactory.decodeFile(f.getAbsolutePath(),d));}catch(Exception e){image.setImageDrawable(null);}}
    long latest(){Cursor c=db.getReadableDatabase().rawQuery("SELECT id FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') ORDER BY created_at DESC LIMIT 1",null);long id=c.moveToFirst()?c.getLong(0):0;c.close();return id;}long olderThan(long at){Cursor c=db.getReadableDatabase().rawQuery("SELECT id FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND created_at<? ORDER BY created_at DESC LIMIT 1",new String[]{String.valueOf(at)});long id=c.moveToFirst()?c.getLong(0):0;c.close();return id;}
    String bullets(ArrayList<String>a){StringBuilder b=new StringBuilder();for(String x:a)b.append("• ").append(x).append('\n');return b.toString().trim();}String clean(String s){return s==null||s.trim().isEmpty()?"Screenshot":s.trim();}String clip(String s,int n){return s==null?"":(s.length()<=n?s:s.substring(0,n)+"…");}String friendly(String s){return s==null?"unknown":s.replace('_',' ');}String empty(String s,String fallback){return s==null||s.trim().isEmpty()?fallback:s.trim();}
    @Override protected void onDestroy(){super.onDestroy();if(db!=null)db.close();}
}
