package com.kareem.cortex;

import android.app.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.graphics.drawable.BitmapDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.os.SystemClock;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.File;
import java.net.URLEncoder;
import java.util.*;
import java.util.concurrent.*;

/** v50 image-first inspector: original evidence, Cortex understanding, privacy and executable actions. */
public class VisualIntelligenceActivity extends Activity {
    VaultDb db;KnowledgeItem item;VisualInsightStore.Insight insight;LinearLayout body,actionRow;ImageView image;TextView title,state,description,visible,usefulness,actions,analyze,search,copy,useful,notUseful,older;volatile boolean destroyed=false;
    final ExecutorService worker=Executors.newSingleThreadExecutor(r->{Thread t=new Thread(r,"cortex-visual-ui");t.setPriority(Thread.NORM_PRIORITY-1);return t;});
    int dp(int x){return CortexUi.dp(this,x);}TextView tv(String s,int sp,int c){return CortexUi.text(this,s,sp,c);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(getApplicationContext());VisualInsightStore.ensure(db);InteractionTelemetry.ensure(db);build();long id=getIntent().getLongExtra("item_id",0);load(id>0?id:latest());}
    @Override protected void onDestroy(){destroyed=true;worker.shutdownNow();recycleImage();if(db!=null){try{db.close();}catch(Throwable ignored){}db=null;}super.onDestroy();}

    void build(){LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView sv=new ScrollView(this);sv.setFillViewport(true);body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(16),dp(13),dp(16),dp(24));sv.addView(body);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
        LinearLayout head=new LinearLayout(this);head.setOrientation(LinearLayout.HORIZONTAL);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(42),dp(48)));LinearLayout hs=new LinearLayout(this);hs.setOrientation(LinearLayout.VERTICAL);TextView h=CortexUi.plain(this,"Visual Intelligence",25,CortexUi.TEXT);CortexUi.medium(h);hs.addView(h);hs.addView(CortexUi.plain(this,"See what Cortex sees — without losing the original.",11,CortexUi.MUTED));head.addView(hs,new LinearLayout.LayoutParams(0,-2,1));body.addView(head);
        image=new ImageView(this);image.setAdjustViewBounds(true);image.setScaleType(ImageView.ScaleType.FIT_CENTER);image.setBackground(CortexUi.round(this,CortexUi.SURFACE,CortexUi.BORDER_SOFT,22));LinearLayout.LayoutParams ip=new LinearLayout.LayoutParams(-1,-2);ip.setMargins(0,dp(12),0,0);body.addView(image,ip);
        title=infoCard("IMAGE",CortexUi.MUTED);state=infoCard("STATUS",CortexUi.COPPER);description=infoCard("WHAT CORTEX SEES",CortexUi.TEXT);usefulness=infoCard("WHY IT MAY MATTER",CortexUi.GOLD);actions=infoCard("USEFUL ACTIONS",CortexUi.COPPER);visible=infoCard("VISIBLE TEXT",CortexUi.MUTED);
        analyze=CortexUi.action(this,"✦  Understand this image",CortexUi.COPPER,true);analyze.setOnClickListener(v->analyze(false));LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(-1,dp(50));ap.setMargins(0,dp(12),0,0);body.addView(analyze,ap);
        actionRow=new LinearLayout(this);actionRow.setOrientation(LinearLayout.HORIZONTAL);actionRow.setPadding(0,dp(9),0,0);search=CortexUi.action(this,"Search",CortexUi.COPPER,false);copy=CortexUi.action(this,"Prompt",CortexUi.GOLD,false);useful=CortexUi.action(this,"Useful",CortexUi.SAGE,false);notUseful=CortexUi.action(this,"Not useful",CortexUi.CORAL,false);search.setOnClickListener(v->search());copy.setOnClickListener(v->copyPrompt());useful.setOnClickListener(v->vote(1));notUseful.setOnClickListener(v->vote(-1));addAction(search,0);addAction(copy,7);body.addView(actionRow,new LinearLayout.LayoutParams(-1,dp(53)));
        LinearLayout voteRow=new LinearLayout(this);voteRow.setOrientation(LinearLayout.HORIZONTAL);addTo(voteRow,useful,0);addTo(voteRow,notUseful,7);LinearLayout.LayoutParams vp=new LinearLayout.LayoutParams(-1,dp(46));vp.setMargins(0,dp(8),0,0);body.addView(voteRow,vp);
        older=CortexUi.action(this,"Open next older screenshot",CortexUi.MUTED,false);older.setOnClickListener(v->{if(destroyed||db==null)return;long id=olderThan(item==null?Long.MAX_VALUE:item.createdAt);if(id>0)load(id);else Toast.makeText(this,"No older screenshot found",Toast.LENGTH_SHORT).show();});LinearLayout.LayoutParams op=new LinearLayout.LayoutParams(-1,dp(44));op.setMargins(0,dp(9),0,0);body.addView(older,op);setContentView(root);}
    TextView infoCard(String label,int accent){LinearLayout c=CortexUi.card(this,20);c.setPadding(dp(15),dp(13),dp(15),dp(14));TextView l=CortexUi.plain(this,label,10,accent);CortexUi.medium(l);l.setLetterSpacing(.08f);c.addView(l);TextView x=tv("",13,CortexUi.TEXT);x.setPadding(0,dp(7),0,0);x.setTextIsSelectable(true);c.addView(x);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(9),0,0);body.addView(c,p);return x;}void addAction(View v,int left){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(44),1);p.setMargins(dp(left),0,0,0);actionRow.addView(v,p);}void addTo(LinearLayout r,View v,int left){LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-1,1);p.setMargins(dp(left),0,0,0);r.addView(v,p);}

    void load(long id){if(destroyed||db==null)return;try{item=id>0?db.getById(id):null;if(item==null){title.setText("No screenshot available");return;}insight=VisualInsightStore.get(db,item.id);title.setText(clean(item.title)+"\nCaptured "+new java.text.SimpleDateFormat("dd MMM • HH:mm",Locale.getDefault()).format(new Date(item.createdAt)));showImage(item.attachmentPath);refresh();}catch(Throwable e){title.setText("Image is safe, but this view could not load it right now.");}}
    void refresh(){if(destroyed||db==null||item==null)return;try{insight=VisualInsightStore.get(db,item.id);if(insight==null){VisualTriage.Result t=VisualTriage.evaluate(item);state.setText((t.sensitive?"Protected locally":"Ready for visual understanding")+"\nPrivacy: "+t.privacy+" • score "+t.privacyScore+"/100\n"+t.reason);description.setText("Strong visual understanding has not run yet.");visible.setText(item.extractedText==null||item.extractedText.trim().isEmpty()?"Supporting OCR found no reliable text. The image may still contain useful visual information.":clip(item.extractedText,1500));usefulness.setText("Run strong vision to understand objects, context, visual style, important text and possible uses.");actions.setText("No actions generated yet.");analyze.setText(t.sensitive?"Review privacy + analyze":"✦  Understand this image");enable(false,false,false);return;}
        if("local_only".equals(insight.status)){state.setText("Protected locally • not sent to cloud\n"+insight.error);description.setText("Privacy Guard v2 blocked automatic cloud analysis.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1500));usefulness.setText("The original stays local. You can explicitly override this block if you decide the image is safe to send.");actions.setText("No cloud actions generated.");analyze.setText("Analyze in cloud anyway");enable(false,false,false);return;}
        if("rate_limited".equals(insight.status)){long wait=VisionRateLimitGate.remainingMs(this);state.setText("Waiting for Gemini quota"+(wait>0?" • retry window ~"+Math.max(1,Math.round(wait/1000.0))+"s":"")+"\nNo image data was lost or discarded.");description.setText("Gemini temporarily refused more requests. Cortex paused the visual queue instead of marking this image as failed.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1500));usefulness.setText("Background items retry automatically after the cooldown. For an older manually opened image, retry after the quota window clears.");actions.setText("No actions available until strong vision completes.");analyze.setText(wait>0?"Waiting for provider quota":"Try visual analysis again");enable(false,false,false);analyze.setEnabled(wait<=0);return;}
        if("failed".equals(insight.status)||"waiting_provider".equals(insight.status)){state.setText(("failed".equals(insight.status)?"Visual analysis failed":"Waiting for provider")+"\n"+insight.error);description.setText("No reliable visual result yet.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1500));usefulness.setText("Retry when ready.");actions.setText("No actions available yet.");analyze.setText("Try visual analysis again");enable(false,false,false);return;}
        if("skipped".equals(insight.status)){state.setText("Skipped as low-value/transient UI\n"+insight.error);description.setText("The original remains in Vault.");visible.setText(item.extractedText==null?"":clip(item.extractedText,1500));usefulness.setText("Override the filter if this screen matters to you.");actions.setText("No actions generated.");analyze.setText("Analyze anyway");enable(false,false,false);return;}
        state.setText("Understanding ready  •  "+friendly(insight.contentType)+"\n"+insight.provider+"  •  usefulness "+insight.usefulnessScore+"/10"+(insight.userValue==1?"  •  marked useful":insight.userValue==-1?"  •  marked not useful":""));description.setText(empty(insight.description,"No description returned."));visible.setText(empty(insight.visibleText,"No important readable text was returned."));usefulness.setText(empty(insight.usefulnessReason,"No strong usefulness signal returned."));ArrayList<String> labels=insight.actionLabels();actions.setText(labels.isEmpty()?"Reference only":bullets(labels));analyze.setText("Re-analyze with strong vision");enable(insight.searchQuery!=null&&!insight.searchQuery.trim().isEmpty(),insight.recreationPrompt!=null&&!insight.recreationPrompt.trim().isEmpty(),true);}catch(Throwable e){if(!destroyed){state.setText("Visual state could not refresh safely.");analyze.setEnabled(true);}}}
    void enable(boolean canSearch,boolean canPrompt,boolean canVote){if(destroyed)return;search.setEnabled(canSearch);copy.setEnabled(canPrompt);useful.setEnabled(canVote);notUseful.setEnabled(canVote);search.setAlpha(canSearch?1f:.35f);copy.setAlpha(canPrompt?1f:.35f);useful.setAlpha(canVote?1f:.35f);notUseful.setAlpha(canVote?1f:.35f);analyze.setEnabled(true);}

    void analyze(boolean override){if(destroyed||db==null||item==null)return;final KnowledgeItem target=item;final long targetId=target.id;long tap=SystemClock.elapsedRealtime();try{InteractionTelemetry.log(db,"Visual Intelligence","analyze_image","tap",targetId,0,"received",override?"Cloud privacy override requested":"Analyze button tapped",null);}catch(Throwable ignored){}VisualTriage.Result t=VisualTriage.evaluate(target);if((t.sensitive||"local_only".equals(insight==null?"":insight.status))&&!override){try{InteractionTelemetry.log(db,"Visual Intelligence","analyze_image","privacy_block",targetId,SystemClock.elapsedRealtime()-tap,"blocked",t.reason,null);}catch(Throwable ignored){}new AlertDialog.Builder(this).setTitle("Protected by Privacy Guard").setMessage(t.reason+"\n\nThis image has not been sent to Gemini. Send it anyway?").setPositiveButton("Send anyway",(d,w)->analyze(true)).setNegativeButton("Keep local",null).show();return;}long cooldown=VisionRateLimitGate.remainingMs(this);if(cooldown>0){Toast.makeText(this,"Gemini quota is cooling down • retry in about "+Math.max(1,Math.round(cooldown/1000.0))+"s",Toast.LENGTH_LONG).show();refresh();return;}analyze.setEnabled(false);analyze.setText("Tap received • starting…");state.setText("Preparing strong visual understanding…\nNext: upload → understand → extract useful actions");long ack=SystemClock.elapsedRealtime()-tap;try{InteractionTelemetry.log(db,"Visual Intelligence","analyze_image","ui_ack",targetId,ack,"ok","UI acknowledged analysis request",null);}catch(Throwable ignored){}
        try{worker.execute(()->{Context app=getApplicationContext();VaultDb workDb=null;long work=SystemClock.elapsedRealtime();try{postUi(()->{analyze.setText("Understanding image…");state.setText("Strong vision is reading the actual image…\nObjects • Arabic/English text • context • usefulness • actions");});JSONObject r=GeminiVisionAnalyzer.analyze(app,target);long providerMs=SystemClock.elapsedRealtime()-work;workDb=new VaultDb(app);VisualInsightStore.ensure(workDb);InteractionTelemetry.ensure(workDb);VisualInsightStore.saveModel(workDb,targetId,r.optString("_provider","gemini-vision"),r);JSONObject metrics=new JSONObject().put("provider",r.optString("_provider","")).put("provider_ms",providerMs).put("privacy_override",override).put("diagnostics",r.optJSONObject("_diagnostics"));InteractionTelemetry.log(workDb,"Visual Intelligence","analyze_image","complete",targetId,SystemClock.elapsedRealtime()-tap,"ok","Visual understanding saved",metrics);postUi(()->{if(item!=null&&item.id==targetId)refresh();analyze.setEnabled(true);Toast.makeText(this,"Visual understanding saved",Toast.LENGTH_LONG).show();});}
            catch(Throwable e){try{if(workDb==null)workDb=new VaultDb(app);VisualInsightStore.ensure(workDb);String msg=e.getClass().getSimpleName()+": "+(e.getMessage()==null?"":e.getMessage());boolean rate=e instanceof GeminiVisionAnalyzer.VisionException&&((GeminiVisionAnalyzer.VisionException)e).rateLimited();VisualInsightStore.saveState(workDb,targetId,rate?"rate_limited":"failed",t.sensitive?"local_override":"safe",msg);try{InteractionTelemetry.ensure(workDb);InteractionTelemetry.log(workDb,"Visual Intelligence","analyze_image","complete",targetId,SystemClock.elapsedRealtime()-tap,rate?"waiting":"failed",msg,null);}catch(Throwable ignored){}postUi(()->{if(item!=null&&item.id==targetId)refresh();analyze.setEnabled(true);});}catch(Throwable ignored){postUi(()->{analyze.setEnabled(true);state.setText("Visual analysis stopped safely. Try again later.");});}}
            finally{if(workDb!=null)try{workDb.close();}catch(Throwable ignored){}}});}
        catch(RejectedExecutionException e){analyze.setEnabled(true);}
    }
    void postUi(Runnable r){if(destroyed||isFinishing()||isDestroyed())return;runOnUiThread(()->{if(!destroyed&&!isFinishing()&&!isDestroyed())try{r.run();}catch(Throwable ignored){}});}
    void search(){if(destroyed||db==null||item==null||insight==null||insight.searchQuery==null||insight.searchQuery.trim().isEmpty())return;long t=SystemClock.elapsedRealtime();try{InteractionTelemetry.log(db,"Visual Intelligence","search_online","tap",item.id,0,"received",insight.searchQuery,null);}catch(Throwable ignored){}try{startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse("https://www.google.com/search?q="+URLEncoder.encode(insight.searchQuery,"UTF-8"))));try{InteractionTelemetry.log(db,"Visual Intelligence","search_online","intent_opened",item.id,SystemClock.elapsedRealtime()-t,"ok","Browser search intent opened",null);}catch(Throwable ignored){}}catch(Throwable e){try{InteractionTelemetry.log(db,"Visual Intelligence","search_online","intent_opened",item.id,SystemClock.elapsedRealtime()-t,"failed",e.toString(),null);}catch(Throwable ignored){}Toast.makeText(this,"Could not open web search",Toast.LENGTH_SHORT).show();}}
    void copyPrompt(){if(destroyed||db==null||item==null||insight==null||insight.recreationPrompt==null||insight.recreationPrompt.trim().isEmpty())return;try{long t=SystemClock.elapsedRealtime();android.content.ClipboardManager c=(android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE);if(c!=null)c.setPrimaryClip(ClipData.newPlainText("Cortex recreation prompt",insight.recreationPrompt));InteractionTelemetry.log(db,"Visual Intelligence","copy_recreate_prompt","complete",item.id,SystemClock.elapsedRealtime()-t,"ok","Recreation prompt copied to clipboard",null);Toast.makeText(this,"Recreation prompt copied",Toast.LENGTH_SHORT).show();}catch(Throwable e){Toast.makeText(this,"Could not copy prompt",Toast.LENGTH_SHORT).show();}}
    void vote(int v){if(destroyed||db==null||item==null)return;try{VisualInsightStore.setUserValue(db,item.id,v);InteractionTelemetry.log(db,"Visual Intelligence","rate_insight","complete",item.id,0,"ok",v>0?"useful":"not_useful",null);refresh();Toast.makeText(this,v>0?"Marked useful — Cortex can learn from this":"Marked not useful",Toast.LENGTH_SHORT).show();}catch(Throwable e){Toast.makeText(this,"Could not save rating",Toast.LENGTH_SHORT).show();}}
    void showImage(String path){Bitmap next=null;try{File f=new File(path==null?"":path);next=SafeImageDecoder.decode(f,1600,2_500_000L);}catch(Throwable ignored){}Bitmap old=currentBitmap();image.setImageBitmap(next);if(old!=null&&old!=next)try{if(!old.isRecycled())old.recycle();}catch(Throwable ignored){}}
    Bitmap currentBitmap(){try{if(image!=null&&image.getDrawable() instanceof BitmapDrawable)return((BitmapDrawable)image.getDrawable()).getBitmap();}catch(Throwable ignored){}return null;}void recycleImage(){Bitmap b=currentBitmap();if(image!=null)image.setImageDrawable(null);if(b!=null)try{if(!b.isRecycled())b.recycle();}catch(Throwable ignored){}}
    long latest(){if(db==null)return 0;Cursor c=null;try{c=db.getReadableDatabase().rawQuery("SELECT id FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') ORDER BY created_at DESC LIMIT 1",null);return c.moveToFirst()?c.getLong(0):0;}catch(Throwable e){return 0;}finally{if(c!=null)c.close();}}long olderThan(long at){if(db==null)return 0;Cursor c=null;try{c=db.getReadableDatabase().rawQuery("SELECT id FROM knowledge_items WHERE source='screenshot-folder' AND type IN ('SCREENSHOT','IMAGE') AND created_at<? ORDER BY created_at DESC LIMIT 1",new String[]{String.valueOf(at)});return c.moveToFirst()?c.getLong(0):0;}catch(Throwable e){return 0;}finally{if(c!=null)c.close();}}
    String bullets(ArrayList<String>a){StringBuilder b=new StringBuilder();for(String x:a)b.append("• ").append(x).append('\n');return b.toString().trim();}String clean(String s){return s==null||s.trim().isEmpty()?"Screenshot":s.trim();}String clip(String s,int n){return s==null?"":(s.length()<=n?s:s.substring(0,n)+"…");}String friendly(String s){return s==null?"unknown":s.replace('_',' ');}String empty(String s,String fallback){return s==null||s.trim().isEmpty()?fallback:s.trim();}
}
