package com.kareem.cortex;

import android.app.Activity;
import android.database.Cursor;
import android.media.MediaPlayer;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.View;
import android.widget.*;
import org.json.JSONObject;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.*;

/** Voice evidence detail: media-first player, transcript, understanding, provenance and shown state remain separate. */
public final class VoiceDetailActivity extends Activity {
    private VaultDb db;private KnowledgeItem item;private MediaPlayer player;private Handler ui=new Handler(Looper.getMainLooper());private CortexRingButton play;private TextView current,total;private SeekBar seek;private CortexWaveformView wave;private LinearLayout tabRow,tabContent;private String tab="transcript";private int dp(int v){return CortexUi.dp(this,v);}
    @Override public void onCreate(Bundle b){super.onCreate(b);CortexUi.applyWindow(this);db=new VaultDb(getApplicationContext());item=db.getById(getIntent().getLongExtra("item_id",0));build();}
    @Override protected void onDestroy(){ui.removeCallbacksAndMessages(null);if(wave!=null)wave.setPlaying(false);if(player!=null)try{player.release();}catch(Throwable ignored){}if(db!=null)try{db.close();}catch(Throwable ignored){}super.onDestroy();}

    private void build(){
        LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(CortexUi.BG);ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setVerticalScrollBarEnabled(false);LinearLayout body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);body.setPadding(dp(18),dp(8),dp(18),dp(30));scroll.addView(body);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);CortexUi.fitSystemBars(this,root);
        LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL);TextView back=CortexUi.plain(this,"‹",34,CortexUi.TEXT);back.setGravity(Gravity.CENTER);back.setOnClickListener(v->finish());head.addView(back,new LinearLayout.LayoutParams(dp(40),dp(48)));LinearLayout tx=new LinearLayout(this);tx.setOrientation(LinearLayout.VERTICAL);head.addView(tx,new LinearLayout.LayoutParams(0,-2,1));tx.addView(CortexUi.eyebrow(this,"CORTEX · VOICE MEMORY",CortexUi.LIME));TextView h=CortexUi.plain(this,"Voice detail",30,CortexUi.TEXT);CortexUi.medium(h);tx.addView(h);body.addView(head);
        if(item==null){LinearLayout error=CortexUi.card(this,22);error.addView(CortexUi.text(this,"This voice capture could not be found. The rest of Cortex remains unchanged.",12,CortexUi.MUTED));body.addView(error);return;}
        String title=safe(item.title);if(title.isEmpty()||"Voice recording".equalsIgnoreCase(title)){String x=first(item.summary,item.extractedText,item.rawText);title=x.isEmpty()?"Voice recording":clip(x,80);}TextView name=CortexUi.text(this,title,18,CortexUi.TEXT);CortexUi.medium(name);name.setPadding(dp(2),dp(10),dp(2),0);body.addView(name);TextView meta=CortexUi.plain(this,stamp(item.createdAt)+" · "+friendlyState(item.status),10,CortexUi.MUTED);meta.setPadding(dp(2),dp(5),dp(2),dp(10));body.addView(meta);

        LinearLayout playerCard=CortexUi.card(this,24);playerCard.setPadding(dp(16),dp(15),dp(16),dp(15));wave=new CortexWaveformView(this);wave.setAccent(CortexUi.LIME);wave.setAudioPath(item.attachmentPath);playerCard.addView(wave,new LinearLayout.LayoutParams(-1,dp(82)));
        seek=new SeekBar(this);seek.setMax(1000);seek.setProgressTintList(android.content.res.ColorStateList.valueOf(CortexUi.LIME));seek.setProgressBackgroundTintList(android.content.res.ColorStateList.valueOf(CortexUi.BORDER));seek.setThumbTintList(android.content.res.ColorStateList.valueOf(CortexUi.TEXT));playerCard.addView(seek,new LinearLayout.LayoutParams(-1,dp(28)));LinearLayout times=new LinearLayout(this);times.setGravity(Gravity.CENTER_VERTICAL);current=CortexUi.plain(this,"0:00",9,CortexUi.MUTED);times.addView(current,new LinearLayout.LayoutParams(0,-2,1));total=CortexUi.plain(this,"0:00",9,CortexUi.MUTED);times.addView(total);playerCard.addView(times);
        LinearLayout controls=new LinearLayout(this);controls.setGravity(Gravity.CENTER);TextView speed=control("1×"),back15=control("↶ 15"),fwd15=control("15 ↷");controls.addView(speed,new LinearLayout.LayoutParams(0,dp(44),1));controls.addView(back15,new LinearLayout.LayoutParams(0,dp(44),1));play=new CortexRingButton(this);play.setAccent(CortexUi.LIME);play.setGlyph(CortexRingButton.Glyph.PLAY);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(dp(76),dp(76));pp.setMargins(dp(8),0,dp(8),0);controls.addView(play,pp);controls.addView(fwd15,new LinearLayout.LayoutParams(0,dp(44),1));playerCard.addView(controls);body.addView(playerCard);CortexMotion.hero(playerCard);
        speed.setOnClickListener(v->Toast.makeText(this,"Playback speed stays at 1× for this build",Toast.LENGTH_SHORT).show());back15.setOnClickListener(v->jump(-15000));fwd15.setOnClickListener(v->jump(15000));play.setOnClickListener(v->toggle());seek.setOnSeekBarChangeListener(new SeekBar.OnSeekBarChangeListener(){public void onProgressChanged(SeekBar s,int p,boolean user){if(user&&player!=null){int d=player.getDuration();if(d>0)player.seekTo(d*p/1000);}}public void onStartTrackingTouch(SeekBar s){}public void onStopTrackingTouch(SeekBar s){}});preparePlayer();

        tabRow=new LinearLayout(this);tabRow.setOrientation(LinearLayout.HORIZONTAL);tabRow.setPadding(0,dp(14),0,dp(10));body.addView(tabRow);tabContent=new LinearLayout(this);tabContent.setOrientation(LinearLayout.VERTICAL);body.addView(tabContent);renderTabs();renderTab();
    }

    private TextView control(String label){TextView t=CortexUi.plain(this,label,11,CortexUi.TEXT);CortexUi.medium(t);t.setGravity(Gravity.CENTER);CortexUi.pressable(this,t,CortexUi.round(this,CortexUi.SURFACE_2,CortexUi.BORDER_SOFT,999));return t;}
    private void preparePlayer(){try{File f=new File(safe(item.attachmentPath));if(!f.isFile()){play.setEnabled(false);return;}player=new MediaPlayer();player.setDataSource(f.getAbsolutePath());player.prepare();total.setText(duration(player.getDuration()));player.setOnCompletionListener(p->{play.setGlyph(CortexRingButton.Glyph.PLAY);play.setProgress(0);seek.setProgress(0);wave.setProgress(0);wave.setPlaying(false);});ui.post(tick);}catch(Throwable ignored){play.setEnabled(false);}}
    private final Runnable tick=new Runnable(){public void run(){try{if(player!=null){int d=player.getDuration(),p=player.getCurrentPosition();boolean isPlaying=player.isPlaying();if(d>0){float f=p/(float)d;seek.setProgress((int)(1000L*p/d));wave.setProgress(f);play.setProgress(f);current.setText(duration(p));}play.setGlyph(isPlaying?CortexRingButton.Glyph.PAUSE:CortexRingButton.Glyph.PLAY);wave.setPlaying(isPlaying);}}catch(Throwable ignored){}ui.postDelayed(this,90);}};
    private void toggle(){if(player==null)return;try{if(player.isPlaying())player.pause();else player.start();CortexMotion.haptic(play,false);CortexMotion.pulseOnce(play);wave.setPlaying(player.isPlaying());play.setGlyph(player.isPlaying()?CortexRingButton.Glyph.PAUSE:CortexRingButton.Glyph.PLAY);}catch(Throwable ignored){}}
    private void jump(int delta){if(player==null)return;try{int to=Math.max(0,Math.min(player.getDuration(),player.getCurrentPosition()+delta));player.seekTo(to);CortexMotion.haptic(play,false);}catch(Throwable ignored){}}

    private void renderTabs(){tabRow.removeAllViews();addTab("Transcript","transcript",0);addTab("Understood","understood",6);addTab("Source","source",6);addTab("Shown","shown",6);}
    private void addTab(String label,String key,int left){boolean on=key.equals(tab);TextView t=CortexUi.chip(this,label,on?CortexUi.LIME:CortexUi.MUTED,on);t.setGravity(Gravity.CENTER);t.setOnClickListener(v->{if(key.equals(tab))return;tab=key;CortexMotion.haptic(v,false);renderTabs();renderTab();});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(34),1);p.setMargins(dp(left),0,0,0);tabRow.addView(t,p);}
    private void renderTab(){tabContent.removeAllViews();if("transcript".equals(tab))transcript();else if("understood".equals(tab))understood();else if("source".equals(tab))source();else shown();CortexMotion.stagger(tabContent);}
    private void transcript(){String raw=first(item.extractedText,item.rawText);LinearLayout card=CortexUi.card(this,20);card.addView(CortexUi.eyebrow(this,"TRANSCRIPT",CortexUi.LIME));TextView t=CortexUi.text(this,raw.isEmpty()?"Transcript is not available yet.":raw,13,raw.isEmpty()?CortexUi.MUTED:CortexUi.TEXT);t.setTextIsSelectable(true);t.setPadding(0,dp(9),0,0);card.addView(t);tabContent.addView(card);}
    private void understood(){LinearLayout card=CortexUi.card(this,20);card.addView(CortexUi.eyebrow(this,"AI SUMMARY",CortexUi.YELLOW));String sum=safe(item.summary);TextView t=CortexUi.text(this,sum.isEmpty()?"Cortex has not produced a separate grounded summary yet.":sum,13,sum.isEmpty()?CortexUi.MUTED:CortexUi.TEXT);t.setPadding(0,dp(9),0,0);card.addView(t);String raw=first(item.extractedText,item.rawText);if(!raw.isEmpty()&&!sum.isEmpty()){TextView boundary=CortexUi.plain(this,"Derived understanding · original transcript stays unchanged",9,CortexUi.YELLOW);boundary.setPadding(0,dp(10),0,0);card.addView(boundary);}tabContent.addView(card);}
    private void source(){LinearLayout card=CortexUi.card(this,20);card.addView(CortexUi.eyebrow(this,"SOURCE & PROVENANCE",CortexUi.YELLOW));card.addView(line("Captured by",safe(item.source).isEmpty()?"Cortex":item.source));card.addView(line("Captured",stamp(item.createdAt)));card.addView(line("Format","WAV · 16 kHz mono PCM"));String file=safe(item.attachmentPath);card.addView(line("Original",file.isEmpty()?"Stored evidence":new File(file).getName()));TextView note=CortexUi.text(this,"Playback reads the stored original. Transcript and analysis are separate derived layers.",10,CortexUi.MUTED);note.setPadding(0,dp(11),0,0);card.addView(note);tabContent.addView(card);}
    private void shown(){LinearLayout card=CortexUi.card(this,20);card.addView(CortexUi.eyebrow(this,"ATTENTION BOUNDARY",CortexUi.LIME));String status=shownStatus();TextView h=CortexUi.plain(this,status,16,CortexUi.TEXT);CortexUi.medium(h);h.setPadding(0,dp(9),0,0);card.addView(h);TextView note=CortexUi.text(this,"Capture does not equal interruption. Only CortexAttentionJudge can materialize an item in Now, and the original voice evidence remains here either way.",11,CortexUi.MUTED);note.setPadding(0,dp(7),0,0);card.addView(note);tabContent.addView(card);}
    private View line(String k,String v){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);row.setPadding(0,dp(10),0,0);TextView a=CortexUi.plain(this,k,10,CortexUi.MUTED);row.addView(a,new LinearLayout.LayoutParams(0,-2,1));TextView b=CortexUi.text(this,v,10,CortexUi.TEXT);b.setTextIsSelectable(true);row.addView(b);return row;}
    private String shownStatus(){long sem=0;try{JSONObject j=new JSONObject(safe(item.metadataJson));sem=j.optLong("semantic_event_id",0);}catch(Throwable ignored){}if(sem<=0)return"Not currently linked to a shown attention item";Cursor c=null;try{c=db.getReadableDatabase().rawQuery("SELECT state FROM ue_attention_items WHERE semantic_event_id=? ORDER BY id DESC LIMIT 1",new String[]{String.valueOf(sem)});if(c.moveToFirst())return"open".equalsIgnoreCase(c.getString(0))?"Shown in Now":"Previously shown · now handled";}catch(Throwable ignored){}finally{if(c!=null)c.close();}return"Not shown in Now";}
    private String friendlyState(String s){String x=safe(s).toLowerCase(Locale.ROOT);if("analyzed".equals(x)||"done".equals(x)||"complete".equals(x))return"Analyzed";if("queued".equals(x)||"analyzing".equals(x)||"processing".equals(x)||"pending".equals(x))return"Processing";return x.isEmpty()?"Captured":x.replace('_',' ');}private String stamp(long t){return new SimpleDateFormat("dd MMM yyyy · HH:mm",Locale.getDefault()).format(new Date(t));}private String duration(long ms){long sec=Math.max(0,ms/1000);return String.format(Locale.US,"%d:%02d",sec/60,sec%60);}private static String first(String...xs){if(xs!=null)for(String x:xs)if(x!=null&&!x.trim().isEmpty())return x.trim();return"";}private static String safe(String s){return s==null?"":s.trim();}private static String clip(String s,int n){String x=safe(s).replaceAll("\\s+"," ");return x.length()<=n?x:x.substring(0,n)+"…";}
}
