package com.kareem.promptdeck;
import android.app.*;import android.content.*;import android.graphics.Typeface;import android.net.Uri;import android.os.Bundle;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;
public class MainActivity extends Activity{
 static final int IMPORT_REQ=1001,EXPORT_REQ=1002;static final String PREFS="promptdeck",CUSTOM="custom_commands_v1";
 static class Cmd{int id;String command,category,description,instruction;boolean custom;Cmd(JSONObject o,boolean x)throws JSONException{id=o.optInt("id",0);command=clean(o.optString("command",""));category=o.optString("category","Custom");description=o.optString("description",o.optString("description_ar",""));instruction=o.optString("instruction","");custom=x;if(command.isEmpty()||instruction.trim().isEmpty())throw new JSONException("required");}JSONObject json()throws JSONException{JSONObject o=new JSONObject();o.put("id",id);o.put("command",command);o.put("category",category);o.put("description",description);o.put("instruction",instruction);return o;}static String clean(String s){s=s==null?"":s.trim();while(s.startsWith("/"))s=s.substring(1);return s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9_-]","");}}
 static class Group{String title,sub;String[] names;Group(String a,String b,String...n){title=a;sub=b;names=n;}}
 final ArrayList<Cmd>all=new ArrayList<>(),selected=new ArrayList<>();LinearLayout root;EditText context,finalPrompt;
 final Group[] groups={
 new Group("✍️ Writing & Rewriting","كتابة وإعادة صياغة وتحسين النص","rewrite","rephrase","paraphrase","polish","proofread","grammar","shorten","expand","simplify","clarify","humanize","professional","formal","casual","tone","translate","arabic"),
 new Group("🧠 Thinking & Ideas","أفكار، نقد، زوايا جديدة واتخاذ قرار","brainstorm","ideas","angles","alternative","critique","challenge","devilsadvocate","blindspots","assumptions","firstprinciples","counterexample","socratic","tradeoffs","decision","recommend","rank"),
 new Group("🔍 Research & Analysis","بحث، تحقق، أدلة وفهم المعلومات","research","verify","sources","evidence","facts","deepdive","insights","trends","data","compare","proscons","summary","summarize","extract","classify"),
 new Group("📋 Planning & Execution","خطط، أولويات، خطوات وتنفيذ","plan","strategy","roadmap","checklist","todo","priority","workflow","timeline","action","requirements","constraints","risks","acceptance","spec","estimate"),
 new Group("🎓 Learning & Study","شرح، تعلم، مراجعة واختبارات","eli5","explain","steps","examples","analogy","study","quiz","flashcards","teach","hint","test","review","memorize","mistakes"),
 new Group("💼 Work & Career","إيميلات، CV، مقابلات واجتماعات","email","reply","followup","request","apology","resume","coverletter","interview","meeting","minutes"),
 new Group("📱 Content Creation","محتوى، Hooks، Scripts وSocial Media","hook","caption","script","carousel","reel","viral","cta","story","headline"),
 new Group("🛠️ Problem Solving & Technical","تشخيص، إصلاح، اختبار وتحسين","rootcause","debug","fix","check","optimize","better","edgecases","refactor","tests","security","rubric","score"),
 new Group("📊 Data & Formatting","تنظيم وعرض وتحويل البيانات","table","bullets","outline","format","json","csv","schema","template","prompt")};
 public void onCreate(Bundle b){super.onCreate(b);load();home();}
 void load(){all.clear();try{JSONArray a=new JSONArray(readAsset("commands.json"));for(int i=0;i<a.length();i++)all.add(new Cmd(a.getJSONObject(i),false));JSONArray c=new JSONArray(getSharedPreferences(PREFS,MODE_PRIVATE).getString(CUSTOM,"[]"));for(int i=0;i<c.length();i++)try{all.add(new Cmd(c.getJSONObject(i),true));}catch(Exception ignored){}}catch(Exception e){throw new RuntimeException(e);}}
 void base(String title,String sub){ScrollView sv=new ScrollView(this);root=vbox();root.setPadding(dp(18),dp(18),dp(18),dp(40));sv.addView(root);setContentView(sv);root.addView(t(title,29,true));root.addView(t(sub,15,false));}
 void home(){base("PromptDeck","دليل أوامر ChatGPT — اختار القسم، افهم كل command، وركّب اللي محتاجه.");root.addView(h("Categories"));for(Group g:groups){Button x=card(g.title,g.sub);x.setOnClickListener(v->group(g));root.addView(x);}Button custom=card("➕ My Prompt Library","أضف أو استورد prompts جديدة واحفظها عندك");custom.setOnClickListener(v->library());root.addView(custom);if(!selected.isEmpty()){Button compose=card("🧩 My Prompt Stack · "+selected.size(),"راجع الأوامر اللي اخترتها وابنِ Prompt واحد");compose.setOnClickListener(v->stack());root.addView(compose);}}
 void group(Group g){base(g.title,g.sub+"\nاضغط على أي command عشان تشوف شرحه بالتفصيل.");LinkedHashMap<String,ArrayList<Cmd>> subs=new LinkedHashMap<>();for(String n:g.names){Cmd c=find(n);if(c!=null){String s=subcat(c.command,g.title);if(!subs.containsKey(s))subs.put(s,new ArrayList<>());subs.get(s).add(c);}}for(Map.Entry<String,ArrayList<Cmd>> en:subs.entrySet()){root.addView(h(en.getKey()));for(Cmd c:en.getValue()){Button x=commandCard(c);x.setOnClickListener(v->detail(c,g));root.addView(x);}}Button back=b("← Categories");back.setOnClickListener(v->home());root.addView(back);}
 String subcat(String c,String group){if(group.contains("Writing")){if(has(c,"rewrite,rephrase,paraphrase,polish,proofread,grammar"))return"Rewrite & Improve";if(has(c,"humanize,professional,formal,casual,tone"))return"Tone & Style";if(has(c,"shorten,expand,simplify,clarify"))return"Length & Clarity";return"Language & Translation";}if(group.contains("Thinking")){if(has(c,"brainstorm,ideas,angles,alternative"))return"Generate Ideas";if(has(c,"critique,challenge,devilsadvocate,blindspots,counterexample"))return"Challenge & Critique";return"Reason & Decide";}if(group.contains("Research")){if(has(c,"research,sources,evidence,verify,facts"))return"Research & Verification";if(has(c,"compare,proscons"))return"Compare";return"Analyze & Extract";}if(group.contains("Planning")){if(has(c,"plan,strategy,roadmap"))return"Strategy & Roadmap";if(has(c,"requirements,constraints,risks,acceptance,spec"))return"Define the Work";return"Tasks & Execution";}if(group.contains("Learning")){if(has(c,"eli5,explain,steps,examples,analogy,teach"))return"Understand & Learn";return"Practice & Remember";}if(group.contains("Work")){if(has(c,"email,reply,followup,request,apology"))return"Messages & Email";if(has(c,"resume,coverletter,interview"))return"Career";return"Meetings";}if(group.contains("Content")){if(has(c,"hook,headline,caption,cta,viral"))return"Attention & Engagement";return"Content Formats";}if(group.contains("Technical")){if(has(c,"rootcause,debug,fix,check"))return"Diagnose & Fix";return"Improve & Validate";}return"Structure & Convert";}
 boolean has(String c,String csv){return Arrays.asList(csv.split(",")).contains(c);}Button commandCard(Cmd c){Button x=card("/"+c.command,c.description);x.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);return x;}
 void detail(Cmd c,Group g){base("/"+c.command,c.description);root.addView(h("بيعمل إيه؟"));root.addView(t(explain(c),16,false));root.addView(h("استخدمه لما"));root.addView(t(useWhen(c),16,false));root.addView(h("مثال"));root.addView(t("/"+c.command+"  "+example(c),16,false));root.addView(h("التعليمات اللي هتتبعت لـ ChatGPT"));root.addView(t(c.instruction,14,false));String related=related(c.command);if(!related.isEmpty()){root.addView(h("يشتغل كويس مع"));root.addView(t(related,16,true));}Button add=b(selected.contains(c)?"✓ Added to Prompt Stack":"＋ Add to Prompt Stack");add.setOnClickListener(v->{if(!selected.contains(c)){selected.add(c);toast("Added /"+c.command);}stack();});root.addView(add);Button back=b("← Back to "+g.title.replaceAll("^[^A-Za-z]*",""));back.setOnClickListener(v->group(g));root.addView(back);}
 String explain(Cmd c){return c.description+".\n\n"+c.instruction;}String useWhen(Cmd c){String n=c.command;if(has(n,"compare,proscons,rank,recommend,decision"))return"عندك أكتر من اختيار وعاوز تفهم الفرق أو توصل لقرار.";if(has(n,"research,verify,sources,evidence,facts"))return"محتاج معلومة موثوقة أو عاوز تتأكد من ادعاء قبل ما تعتمد عليه.";if(has(n,"rewrite,rephrase,polish,proofread,grammar,humanize"))return"عندك نص موجود وعاوز تطلعه بشكل أحسن بدل ما تبدأ من الصفر.";if(has(n,"brainstorm,ideas,angles,alternative"))return"محتاج توسع مساحة الاختيارات وتطلع أفكار أو اتجاهات جديدة.";if(has(n,"debug,rootcause,fix,check,tests"))return"في مشكلة أو نتيجة غلط وعاوز تشخص السبب وتوصل لإصلاح قابل للاختبار.";if(has(n,"plan,strategy,roadmap,action,priority"))return"عندك هدف وعاوز تحوله لترتيب عملي واضح بدل كلام عام.";return"لما تكون محتاج الوظيفة دي كخطوة واضحة داخل طلب أكبر.";}String example(Cmd c){return "طبّق الأمر ده على الموضوع أو النص اللي هبعته، واديني نتيجة واضحة وعملية.";}String related(String n){if(has(n,"research,verify,sources,evidence"))return"/research  /verify  /sources  /evidence  /facts";if(has(n,"critique,challenge,blindspots,devilsadvocate"))return"/critique  /challenge  /blindspots  /improve";if(has(n,"rewrite,rephrase,polish,proofread"))return"/rewrite  /clarify  /polish  /professional";if(has(n,"plan,strategy,roadmap,action"))return"/strategy  /roadmap  /priority  /action";if(has(n,"debug,fix,check,tests"))return"/rootcause  /debug  /fix  /tests  /check";return"";}
 void stack(){base("My Prompt Stack",selected.isEmpty()?"اختار commands من الأقسام الأول.":"الترتيب مهم: كل خطوة هتبني على اللي قبلها.");for(int i=0;i<selected.size();i++){final int k=i;Cmd c=selected.get(i);LinearLayout row=hbox();row.addView(t((i+1)+". /"+c.command+"\n"+c.description,15,true),new LinearLayout.LayoutParams(0,-2,1));Button up=b("↑"),dn=b("↓"),rm=b("×");up.setOnClickListener(v->{if(k>0)Collections.swap(selected,k,k-1);stack();});dn.setOnClickListener(v->{if(k<selected.size()-1)Collections.swap(selected,k,k+1);stack();});rm.setOnClickListener(v->{selected.remove(k);stack();});row.addView(up);row.addView(dn);row.addView(rm);root.addView(row);}if(!selected.isEmpty()){root.addView(h("Your request / context"));context=e("اكتب هنا الموضوع أو النص اللي عاوز تطبق عليه الـcommands…",5);root.addView(context);Button build=b("Build Final Prompt");build.setOnClickListener(v->build());root.addView(build);}Button more=b("＋ Add more commands");more.setOnClickListener(v->home());root.addView(more);}
 void build(){String user=context.getText().toString().trim();base("Final Prompt","راجع الـPrompt النهائي، وبعدها انسخه أو ابعته لـChatGPT.");StringBuilder p=new StringBuilder("Help me with the request below by following these steps in order. Each step should build on the useful findings of the previous one.\n\n");for(int i=0;i<selected.size();i++)p.append(i+1).append(". ").append(selected.get(i).instruction).append("\n");if(!user.isEmpty())p.append("\nMy request / context:\n").append(user);p.append("\n\nGive me one clear, coherent final answer. Show useful conclusions and evidence, but do not expose private chain-of-thought.");finalPrompt=e("",10);finalPrompt.setText(p);root.addView(finalPrompt);Button send=b("Send to ChatGPT");send.setOnClickListener(v->send());root.addView(send);Button copy=b("Copy Prompt");copy.setOnClickListener(v->copy());root.addView(copy);Button edit=b("← Edit Stack");edit.setOnClickListener(v->stack());root.addView(edit);}
 void library(){base("My Prompt Library",all.size()+" prompts available. Custom prompts can be imported as .promptdeck.json.");Button add=b("＋ Add prompt");add.setOnClickListener(v->showAdd());root.addView(add);Button imp=b("Import JSON pack");imp.setOnClickListener(v->openImport());root.addView(imp);Button exp=b("Export custom prompts");exp.setOnClickListener(v->openExport());root.addView(exp);ArrayList<Cmd> custom=new ArrayList<>();for(Cmd c:all)if(c.custom)custom.add(c);if(!custom.isEmpty()){root.addView(h("My custom prompts"));for(Cmd c:custom)root.addView(commandCard(c));}Button back=b("← Categories");back.setOnClickListener(v->home());root.addView(back);}
 void showAdd(){LinearLayout x=vbox();EditText cmd=e("Command name",1),cat=e("Category",1),desc=e("Short explanation",2),inst=e("Full ChatGPT instruction",5);x.addView(cmd);x.addView(cat);x.addView(desc);x.addView(inst);AlertDialog d=new AlertDialog.Builder(this).setTitle("Add prompt").setView(x).setNegativeButton("Cancel",null).setPositiveButton("Add",null).create();d.setOnShowListener(z->d.getButton(-1).setOnClickListener(v->{try{JSONObject o=new JSONObject();o.put("id",nextId());o.put("command",cmd.getText());o.put("category",cat.getText());o.put("description",desc.getText());o.put("instruction",inst.getText());all.add(new Cmd(o,true));saveCustom();d.dismiss();library();}catch(Exception e){toast("Name and instruction required");}}));d.show();}
 int nextId(){int m=10000;for(Cmd c:all)m=Math.max(m,c.id+1);return m;}Cmd find(String n){for(Cmd c:all)if(c.command.equals(n))return c;return null;}void saveCustom(){JSONArray a=new JSONArray();for(Cmd c:all)if(c.custom)try{a.put(c.json());}catch(Exception ignored){}getSharedPreferences(PREFS,MODE_PRIVATE).edit().putString(CUSTOM,a.toString()).apply();}
 void openImport(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");startActivityForResult(i,IMPORT_REQ);}void openExport(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"PromptDeck-custom.promptdeck.json");startActivityForResult(i,EXPORT_REQ);}protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;try{if(r==IMPORT_REQ)importPack(data.getData());else if(r==EXPORT_REQ)exportPack(data.getData());}catch(Exception e){toast("File error");}}
 void importPack(Uri u)throws Exception{Object p=new JSONTokener(readUri(u)).nextValue();JSONArray a=p instanceof JSONArray?(JSONArray)p:((JSONObject)p).getJSONArray("commands");int n=0;for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);o.put("id",nextId());Cmd c=new Cmd(o,true);all.add(c);n++;}catch(Exception ignored){}saveCustom();toast("Imported "+n);library();}void exportPack(Uri u)throws Exception{JSONObject p=new JSONObject();p.put("format","promptdeck-pack");p.put("version",1);JSONArray a=new JSONArray();for(Cmd c:all)if(c.custom)a.put(c.json());p.put("commands",a);OutputStream out=getContentResolver().openOutputStream(u,"w");out.write(p.toString(2).getBytes(StandardCharsets.UTF_8));out.close();toast("Exported");}
 void copy(){((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("PromptDeck",finalPrompt.getText()));toast("Copied");}void send(){Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,finalPrompt.getText().toString());i.setPackage("com.openai.chatgpt");try{startActivity(i);}catch(Exception e){i.setPackage(null);startActivity(Intent.createChooser(i,"Send prompt"));}}
 Button card(String a,String b){Button x=new Button(this);x.setAllCaps(false);x.setText(a+"\n"+b);x.setTextSize(16);x.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);x.setPadding(dp(16),dp(14),dp(16),dp(14));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(6),0,dp(3));x.setLayoutParams(lp);return x;}LinearLayout vbox(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}LinearLayout hbox(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}TextView t(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(dp(5),dp(7),dp(5),dp(7));if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}TextView h(String s){TextView v=t(s,20,true);v.setPadding(dp(2),dp(20),dp(2),dp(7));return v;}EditText e(String hint,int lines){EditText x=new EditText(this);x.setHint(hint);x.setMinLines(lines);x.setGravity(Gravity.TOP|Gravity.START);return x;}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);return x;}int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}String readAsset(String n)throws IOException{return slurp(getAssets().open(n));}String readUri(Uri u)throws IOException{return slurp(getContentResolver().openInputStream(u));}String slurp(InputStream in)throws IOException{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[4096];int n;while((n=in.read(b))>0)o.write(b,0,n);in.close();return o.toString(StandardCharsets.UTF_8.name());}
}