package com.kareem.promptdeck;

import android.app.*;import android.content.*;import android.graphics.Typeface;import android.net.Uri;import android.os.Bundle;import android.text.*;import android.view.*;import android.widget.*;import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.util.*;

public class MainActivity extends Activity{
 static final int IMPORT_REQ=1001,EXPORT_REQ=1002;static final String PREFS="promptdeck",CUSTOM="custom_commands_v1";
 static class Cmd{int id;String command,category,description,instruction;boolean custom;Cmd(JSONObject o,boolean x)throws JSONException{id=o.optInt("id",0);command=clean(o.optString("command",""));category=o.optString("category","Custom").trim();if(category.isEmpty())category="Custom";description=o.optString("description",o.optString("description_ar","")).trim();instruction=o.optString("instruction","").trim();custom=x;if(command.isEmpty()||instruction.isEmpty())throw new JSONException("required");}JSONObject json()throws JSONException{JSONObject o=new JSONObject();o.put("id",id);o.put("command",command);o.put("category",category);o.put("description",description);o.put("instruction",instruction);return o;}static String clean(String s){if(s==null)return"";s=s.trim();while(s.startsWith("/"))s=s.substring(1);return s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9_-]","");}}
 final ArrayList<Cmd>all=new ArrayList<>(),selected=new ArrayList<>();EditText need,finalPrompt,search;LinearLayout root,chain,list,cats;TextView recommendation;String activeCategory="All";
 public void onCreate(Bundle b){super.onCreate(b);load();home();acceptShared(getIntent());}public void onNewIntent(Intent i){super.onNewIntent(i);setIntent(i);acceptShared(i);}
 void load(){all.clear();try{JSONArray a=new JSONArray(readAsset("commands.json"));for(int i=0;i<a.length();i++)all.add(new Cmd(a.getJSONObject(i),false));JSONArray c=new JSONArray(getSharedPreferences(PREFS,MODE_PRIVATE).getString(CUSTOM,"[]"));for(int i=0;i<c.length();i++)try{all.add(new Cmd(c.getJSONObject(i),true));}catch(Exception ignored){}}catch(Exception e){throw new RuntimeException(e);}}
 void base(String title,String sub){ScrollView sv=new ScrollView(this);root=vbox();root.setPadding(dp(20),dp(18),dp(20),dp(36));sv.addView(root);setContentView(sv);root.addView(t(title,30,true));root.addView(t(sub,15,false));}
 void home(){base("PromptDeck","Tell me what you want ChatGPT to do. PromptDeck will build the right prompt for you.");root.addView(h("What do you need?"));need=e("مثال: قارن بين الاختيارين دول، تحقق من المعلومات، وقولي أنهي أفضل وليه…",6);root.addView(need);root.addView(t("اختار نوع المساعدة الأقرب لطلبك",14,false));card("🔍  Research & Analyze","ابحث، حلل، قارن وتحقق من المعلومات",new String[]{"research","compare","verify","recommend"});card("✍️  Write & Improve","اكتب أو أعد الصياغة وحسّن الأسلوب والوضوح",new String[]{"rewrite","clarify","polish","professional"});card("💡  Think & Solve","ولّد أفكار، انتقدها، اكشف المخاطر واختر الأفضل",new String[]{"brainstorm","critique","blindspots","recommend"});card("🛠️  Build & Plan","حوّل الفكرة لخطة ومتطلبات وخطوات تنفيذ واضحة",new String[]{"requirements","strategy","roadmap","action"});root.addView(h("أو استخدم وصفة جاهزة"));LinearLayout r=vbox();recipe(r,"قرار مهم","Research → Compare → Pros & Cons → Verify → Recommend",new String[]{"research","compare","proscons","verify","recommend"});recipe(r,"حل مشكلة","Root cause → Debug → Fix → Check",new String[]{"rootcause","debug","fix","check"});recipe(r,"خطة مشروع","Brainstorm → Strategy → Roadmap → Priority → Action",new String[]{"brainstorm","strategy","roadmap","priority","action"});root.addView(r);Button adv=b("Advanced · Browse all prompts");adv.setOnClickListener(v->advanced());root.addView(adv);Button lib=b("Prompt Library · Add / Import / Export");lib.setOnClickListener(v->library());root.addView(lib);}
 void card(String title,String sub,String[] names){Button x=new Button(this);x.setAllCaps(false);x.setText(title+"\n"+sub);x.setTextSize(16);x.setGravity(Gravity.START|Gravity.CENTER_VERTICAL);x.setPadding(dp(18),dp(16),dp(18),dp(16));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,dp(8),0,dp(4));x.setLayoutParams(lp);x.setOnClickListener(v->{select(names);composer(title);});root.addView(x);}
 void recipe(LinearLayout box,String title,String sub,String[]names){Button x=b(title+"\n"+sub);x.setGravity(Gravity.START);x.setTextSize(14);x.setOnClickListener(v->{select(names);composer(title);});box.addView(x,new LinearLayout.LayoutParams(-1,-2));}
 void select(String[]names){selected.clear();for(String n:names){Cmd c=find(n);if(c!=null)selected.add(c);}}
 void composer(String source){String text=need==null?"":need.getText().toString();base("Your prompt plan","PromptDeck picked a workflow for your task. You can use it immediately or adjust it.");need=e("Your request / context",5);need.setText(text);need.addTextChangedListener(watcher(()->updatePrompt()));root.addView(need);recommendation=t("Recommended workflow",18,true);root.addView(recommendation);chain=vbox();root.addView(chain);renderChain();Button add=b("+ Add another step");add.setOnClickListener(v->advanced());root.addView(add);Button build=b("✓ Build Prompt");build.setTextSize(17);build.setOnClickListener(v->ready());root.addView(build);Button back=b("← Start over");back.setOnClickListener(v->home());root.addView(back);}
 void renderChain(){if(chain==null)return;chain.removeAllViews();for(int i=0;i<selected.size();i++){final int k=i;Cmd c=selected.get(i);LinearLayout row=hbox();String label=friendly(c.command);TextView tx=t((i+1)+".  "+label+(c.description.isEmpty()?"":"\n"+c.description),15,true);row.addView(tx,new LinearLayout.LayoutParams(0,-2,1));Button up=b("↑"),dn=b("↓"),rm=b("×");up.setOnClickListener(v->{if(k>0)Collections.swap(selected,k,k-1);renderChain();});dn.setOnClickListener(v->{if(k<selected.size()-1)Collections.swap(selected,k,k+1);renderChain();});rm.setOnClickListener(v->{selected.remove(k);renderChain();});row.addView(up);row.addView(dn);row.addView(rm);chain.addView(row);}}
 String friendly(String s){return s.substring(0,1).toUpperCase(Locale.ROOT)+s.substring(1).replace("proscons","Pros & Cons").replace("deepdive","Deep Dive").replace("rootcause","Root Cause").replace("blindspots","Blind Spots");}
 void ready(){if(selected.isEmpty()){toast("Choose at least one step");return;}String text=need.getText().toString();base("Your prompt is ready ✓","Preview it if you want, then copy it or open ChatGPT.");need=e("",1);need.setText(text);need.setVisibility(View.GONE);finalPrompt=e("",10);updatePrompt();finalPrompt.setVisibility(View.GONE);root.addView(finalPrompt);Button preview=b("Preview prompt");preview.setOnClickListener(v->{finalPrompt.setVisibility(finalPrompt.getVisibility()==View.VISIBLE?View.GONE:View.VISIBLE);preview.setText(finalPrompt.getVisibility()==View.VISIBLE?"Hide preview":"Preview prompt");});root.addView(preview);Button send=b("Open in ChatGPT");send.setTextSize(18);send.setOnClickListener(v->send());root.addView(send);Button copy=b("Copy prompt");copy.setOnClickListener(v->copy());root.addView(copy);Button edit=b("← Edit workflow");edit.setOnClickListener(v->composer("edit"));root.addView(edit);}
 void updatePrompt(){if(finalPrompt==null)return;String user=need==null?"":need.getText().toString().trim();StringBuilder p=new StringBuilder("Help me with the request below by following these steps in order. Each step should build on the useful findings of the previous one.\n\n");for(int i=0;i<selected.size();i++){Cmd c=selected.get(i);p.append(i+1).append(". ").append(c.instruction).append('\n');}if(!user.isEmpty())p.append("\nMy request / context:\n").append(user);p.append("\n\nGive me one clear, coherent final answer. Show useful conclusions and evidence, but do not expose private chain-of-thought.");finalPrompt.setText(p.toString());}
 void advanced(){String text=need==null?"":need.getText().toString();base("Advanced prompts","Choose individual tools only when you want precise control. Tap a prompt to add it to your workflow.");Button done=b("✓ Done");done.setOnClickListener(v->{if(selected.isEmpty()){toast("Choose at least one prompt");return;}composer("advanced");});root.addView(done);search=e("Search prompts…",1);root.addView(search);search.addTextChangedListener(watcher(()->renderList()));HorizontalScrollView hs=new HorizontalScrollView(this);cats=hbox();hs.addView(cats);root.addView(hs);list=vbox();root.addView(list);rebuildCats();renderList();need=e("",1);need.setText(text);need.setVisibility(View.GONE);}
 void rebuildCats(){if(cats==null)return;cats.removeAllViews();LinkedHashSet<String>s=new LinkedHashSet<>();s.add("All");for(Cmd c:all)s.add(c.category);for(String z:s){Button x=b(z);x.setOnClickListener(v->{activeCategory=z;rebuildCats();renderList();});cats.addView(x);}}
 void renderList(){if(list==null)return;list.removeAllViews();String q=search==null?"":search.getText().toString().toLowerCase(Locale.ROOT);for(Cmd c:all){if(!activeCategory.equals("All")&&!activeCategory.equals(c.category))continue;String blob=(c.command+" "+c.description+" "+c.instruction).toLowerCase(Locale.ROOT);if(!q.trim().isEmpty()&&!blob.contains(q.trim()))continue;Button x=b(friendly(c.command)+(c.description.isEmpty()?"":"\n"+c.description));x.setGravity(Gravity.START);x.setOnClickListener(v->{if(!selected.contains(c))selected.add(c);toast(friendly(c.command)+" added");});list.addView(x,new LinearLayout.LayoutParams(-1,-2));}}
 void library(){base("Prompt Library",all.size()+" prompts available. Add your own or import a PromptDeck JSON pack.");Button add=b("+ Add a prompt");add.setOnClickListener(v->showAdd());root.addView(add);Button imp=b("Import .promptdeck.json");imp.setOnClickListener(v->openImport());root.addView(imp);Button exp=b("Export my custom prompts");exp.setOnClickListener(v->openExport());root.addView(exp);root.addView(t("Custom prompts stay on this device and can be reused in any workflow.",14,false));Button back=b("← Back home");back.setOnClickListener(v->home());root.addView(back);}
 void showAdd(){LinearLayout x=vbox();x.setPadding(dp(16),0,dp(16),0);EditText cmd=e("Short name, e.g. architectreview",1),cat=e("Category",1),desc=e("What does it do?",2),inst=e("Full instruction for ChatGPT",5);x.addView(cmd);x.addView(cat);x.addView(desc);x.addView(inst);AlertDialog d=new AlertDialog.Builder(this).setTitle("Add prompt").setView(x).setNegativeButton("Cancel",null).setPositiveButton("Add",null).create();d.setOnShowListener(z->d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener(v->{try{JSONObject o=new JSONObject();o.put("id",nextId());o.put("command",cmd.getText());o.put("category",cat.getText());o.put("description",desc.getText());o.put("instruction",inst.getText());Cmd c=new Cmd(o,true);all.add(c);saveCustom();d.dismiss();library();toast("Prompt added");}catch(Exception ex){toast("Name and instruction are required");}}));d.show();}
 int nextId(){int m=10000;for(Cmd c:all)m=Math.max(m,c.id+1);return m;}Cmd find(String n){for(Cmd c:all)if(c.command.equals(n))return c;return null;}void saveCustom(){JSONArray a=new JSONArray();for(Cmd c:all)if(c.custom)try{a.put(c.json());}catch(Exception ignored){}getSharedPreferences(PREFS,MODE_PRIVATE).edit().putString(CUSTOM,a.toString()).apply();}
 void openImport(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");startActivityForResult(i,IMPORT_REQ);}void openExport(){Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("application/json");i.putExtra(Intent.EXTRA_TITLE,"PromptDeck-custom.promptdeck.json");startActivityForResult(i,EXPORT_REQ);}
 protected void onActivityResult(int r,int result,Intent data){super.onActivityResult(r,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;try{if(r==IMPORT_REQ)importPack(data.getData());else if(r==EXPORT_REQ)exportPack(data.getData());}catch(Exception e){toast("File error: "+e.getMessage());}}
 void importPack(Uri u)throws Exception{Object p=new JSONTokener(readUri(u)).nextValue();JSONArray a;if(p instanceof JSONArray)a=(JSONArray)p;else{JSONObject o=(JSONObject)p;a=o.has("commands")?o.getJSONArray("commands"):new JSONArray().put(o);}int n=0;for(int i=0;i<a.length();i++)try{JSONObject o=a.getJSONObject(i);o.put("id",nextId());Cmd c=new Cmd(o,true);boolean dup=false;for(Cmd z:all)if(z.command.equals(c.command)&&z.instruction.equals(c.instruction))dup=true;if(!dup){all.add(c);n++;}}catch(Exception ignored){}saveCustom();toast("Imported "+n+" prompts");library();}
 void exportPack(Uri u)throws Exception{JSONObject p=new JSONObject();p.put("format","promptdeck-pack");p.put("version",1);JSONArray a=new JSONArray();for(Cmd c:all)if(c.custom)a.put(c.json());p.put("commands",a);OutputStream out=getContentResolver().openOutputStream(u,"w");out.write(p.toString(2).getBytes(StandardCharsets.UTF_8));out.close();toast("Exported");}
 void copy(){String s=finalPrompt.getText().toString();((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("PromptDeck",s));toast("Prompt copied");}void send(){String s=finalPrompt.getText().toString();Intent i=new Intent(Intent.ACTION_SEND);i.setType("text/plain");i.putExtra(Intent.EXTRA_TEXT,s);i.setPackage("com.openai.chatgpt");try{startActivity(i);}catch(Exception e){i.setPackage(null);startActivity(Intent.createChooser(i,"Send prompt"));}}
 void acceptShared(Intent i){if(i!=null&&need!=null&&Intent.ACTION_SEND.equals(i.getAction())){String s=i.getStringExtra(Intent.EXTRA_TEXT);if(s!=null)need.setText(s);}}
 String readAsset(String n)throws IOException{return slurp(getAssets().open(n));}String readUri(Uri u)throws IOException{return slurp(getContentResolver().openInputStream(u));}String slurp(InputStream in)throws IOException{ByteArrayOutputStream o=new ByteArrayOutputStream();byte[]b=new byte[4096];int n;while((n=in.read(b))>0)o.write(b,0,n);in.close();return o.toString(StandardCharsets.UTF_8.name());}
 LinearLayout vbox(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}LinearLayout hbox(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}TextView t(String s,int z,boolean bold){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(dp(5),dp(7),dp(5),dp(7));if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;}TextView h(String s){TextView v=t(s,20,true);v.setPadding(dp(2),dp(22),dp(2),dp(8));return v;}EditText e(String hint,int lines){EditText x=new EditText(this);x.setHint(hint);x.setMinLines(lines);x.setGravity(Gravity.TOP|Gravity.START);x.setPadding(dp(14),dp(12),dp(14),dp(12));return x;}Button b(String s){Button x=new Button(this);x.setText(s);x.setAllCaps(false);x.setTextSize(13);x.setPadding(dp(12),dp(8),dp(12),dp(8));return x;}int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}TextWatcher watcher(Runnable r){return new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int b,int c){}public void onTextChanged(CharSequence s,int a,int b,int c){}public void afterTextChanged(Editable e){r.run();}};}
}