package com.kareem.cortex;

import static org.junit.Assert.*;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import org.json.JSONObject;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.RobolectricTestRunner;

@RunWith(RobolectricTestRunner.class)
public class StatefulMeaningAcceptanceTest {
    SQLiteDatabase db;
    @Before public void before(){db=SQLiteDatabase.create(null);UniversalEventStore.ensure(db);StatefulMeaningStore.ensure(db);}
    @After public void after(){if(db!=null)db.close();}

    @Test public void gate01_sameSbnKeyResolvesOneSourceInstance(){String a=StatefulMeaningPolicy.notificationInstanceKey("pkg","key-1","","",7,"","A"),b=StatefulMeaningPolicy.notificationInstanceKey("pkg","key-1","other","group",8,"tag","B");assertEquals(a,b);}
    @Test public void gate02_thirtyUpdatesPreserveThirtyObservations(){JSONObject m=meta("k30");for(int i=0;i<30;i++)StatefulMeaningStore.observeNotification(db,i+1,"pkg","conversation_notification","posted","A","message "+i,1000+i,m);assertEquals(30,count("SELECT observation_count FROM ue_source_instances WHERE instance_key LIKE 'sbn|%k30'"));}
    @Test public void gate03_exactDuplicateUpdatesDoNotMultiplyTransitions(){JSONObject m=meta("dup");for(int i=0;i<20;i++)StatefulMeaningStore.observeNotification(db,i+1,"pkg","conversation_notification","posted","Same","Body",1000+i,m);assertEquals(1,count("SELECT transition_count FROM ue_source_instances WHERE instance_key LIKE 'sbn|%dup'"));}
    @Test public void gate04_progressUpdatesStayOneInstance(){JSONObject m=meta("download");for(int i=1;i<=9;i++)StatefulMeaningStore.observeNotification(db,i,"downloads","progress_state","posted","Download",i*10+"%",1000+i,m);assertEquals(1,count("SELECT COUNT(*) FROM ue_source_instances"));}
    @Test public void gate05_removalReasonIsPreservedInLifecycleState(){assertEquals("removed:click",StatefulMeaningPolicy.lifecycleState("conversation_notification","removed","A","B","click"));}
    @Test public void gate06_simpleRemovalDoesNotEmitUserSemanticFact(){assertFalse(StatefulMeaningPolicy.shouldEmitSemanticFact("conversation_notification","posted","removed:user_cancel","A","B"));}
    @Test public void gate07_progressIsNotFactUntilTerminal(){assertFalse(StatefulMeaningPolicy.shouldEmitSemanticFact("progress_state","progress","progress","Download","44%"));assertTrue(StatefulMeaningPolicy.shouldEmitSemanticFact("progress_state","progress","completed","Download","Complete"));}
    @Test public void gate08_ringingCallIsStateNotFact(){assertFalse(StatefulMeaningPolicy.shouldEmitSemanticFact("call_hint","","ringing","Incoming call","01000000000"));}
    @Test public void gate09_missedCallCanBecomeFact(){assertTrue(StatefulMeaningPolicy.shouldEmitSemanticFact("call_hint","ringing","missed","Missed call","01000000000"));}
    @Test public void gate10_googleAndGmsSecurityShareCorrelationKey(){long t=10_000;String a=StatefulMeaningPolicy.correlationKey("security_alert","Google security alert","Saved passwords found online change password","com.google.android.googlequicksearchbox",t),b=StatefulMeaningPolicy.correlationKey("security_alert","Google Play services","Google password compromised; change password","com.google.android.gms",t+20_000);assertEquals(a,b);}
    @Test public void gate11_differentProvidersDoNotFalseMergeSecurity(){long t=10_000;String a=StatefulMeaningPolicy.correlationKey("security_alert","Google security alert","password found online","g",t),b=StatefulMeaningPolicy.correlationKey("security_alert","Microsoft security alert","password found online","m",t);assertNotEquals(a,b);}
    @Test public void gate12_crossSourceSecurityCreatesOneSituation(){long a=StatefulMeaningStore.correlate(db,1,0,"google","security_alert","Google security alert","Saved passwords found online",.95,1000),b=StatefulMeaningStore.correlate(db,2,0,"gms","security_alert","Google Play services","Google password found online",.95,2000);assertEquals(a,b);assertEquals(1,count("SELECT COUNT(*) FROM ue_situation_state_v2"));}
    @Test public void gate13_supportingEvidenceDoesNotCreateSecondBriefDelta(){long s=StatefulMeaningStore.correlate(db,1,0,"google","security_alert","Google security alert","Google password found online",.95,1000);StatefulMeaningStore.correlate(db,2,0,"gms","security_alert","Google security alert","Google password found online",.95,2000);assertEquals(1,count("SELECT COUNT(*) FROM ue_situation_transitions WHERE situation_id="+s));}
    @Test public void gate14_materialChangeCreatesSituationDelta(){long s=StatefulMeaningStore.correlate(db,1,0,"google","security_alert","Google security alert","Google password found online",.95,1000);StatefulMeaningStore.correlate(db,2,0,"gms","security_alert","Google password unauthorized login from another country detected; change it now",.95,2000);assertEquals(2,count("SELECT COUNT(*) FROM ue_situation_transitions WHERE situation_id="+s));}
    @Test public void gate15_routineWeatherIsCaptureOnly(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("weather_event","weather",.95,"OPENED",1,"23° in New Cairo City","Clear weather and 23°");assertTrue(d.capture);assertFalse(d.now);assertFalse(d.brief);}
    @Test public void gate16_severeWeatherCanEnterBrief(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("weather_event","weather",.95,"MATERIAL_UPDATE",1,"New Cairo weather","Severe thunderstorm warning with heavy rain");assertTrue(d.brief);assertFalse(d.now);}
    @Test public void gate17_socialUpdateDefaultsCaptureOnly(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("social_update","info",.92,"OPENED",1,"Nabil","Nabil has a new story");assertTrue(d.capture);assertFalse(d.now);assertFalse(d.brief);}
    @Test public void gate18_explicitRequestEntersNow(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("action_request","request",.94,"OPENED",1,"Karim","Please send me the email urgently");assertTrue(d.now);}
    @Test public void gate19_ordinaryMessageDoesNotEnterNowOrBrief(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("conversation_message","message",.91,"OPENED",1,"Ahmed","How are you?");assertTrue(d.capture);assertFalse(d.now);assertFalse(d.brief);}
    @Test public void gate20_decisionCanEnterBrainAndBrief(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("decision","decision",.90,"OPENED",1,"Project","We decided to use option B");assertTrue(d.brief);assertTrue(d.brain);}
    @Test public void gate21_commitmentCanEnterNowBriefBrain(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("commitment","commitment",.90,"OPENED",1,"Ahmed","I will send it tomorrow");assertTrue(d.now);assertTrue(d.brief);assertTrue(d.brain);}
    @Test public void gate22_answeredCallIsCaptureOnly(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("call_event","call",.95,"OPENED",1,"01000000000","Answered call ended");assertTrue(d.capture);assertFalse(d.now);assertFalse(d.brief);}
    @Test public void gate23_singleMissedCallDoesNotAutomaticallyEnterNow(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("call_event","call",.95,"OPENED",1,"01000000000","Missed call");assertFalse(d.now);}
    @Test public void gate24_repeatedMissedCallsCanEnterNow(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("call_event","call",.95,"MATERIAL_UPDATE",3,"01000000000","Missed call repeated");assertTrue(d.now);assertTrue(d.brief);}
    @Test public void gate25_lowConfidenceNeverEscapesCapture(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("action_request","request",.55,"OPENED",1,"X","Send this");assertTrue(d.capture);assertFalse(d.now);assertFalse(d.brief);assertFalse(d.brain);}
    @Test public void gate26_identicalFactIsNotMaterialChange(){assertFalse(StatefulMeaningPolicy.materialChange("Google password found online","Google password found online"));}
    @Test public void gate27_substantiallyDifferentFactIsMaterialChange(){assertTrue(StatefulMeaningPolicy.materialChange("Clear weather 23 degrees","Severe thunderstorm warning heavy rain flooding expected"));}
    @Test public void gate28_supportingEvidenceIsNotMaterialTransition(){assertFalse(StatefulMeaningPolicy.materialTransition("SUPPORTING_EVIDENCE"));}
    @Test public void gate29_exactDeliveryDetectionRequiresSameHash(){assertTrue(StatefulMeaningPolicy.sameExactDelivery("k","h","h"));assertFalse(StatefulMeaningPolicy.sameExactDelivery("k","h","x"));}
    @Test public void gate30_sbnKeyHasIdentityPriority(){String k=StatefulMeaningPolicy.notificationInstanceKey("pkg","authoritative","shortcut","group",99,"tag","title");assertTrue(k.contains("authoritative"));assertFalse(k.contains("shortcut"));}
    @Test public void gate31_shortcutIsStableFallbackIdentity(){assertEquals(StatefulMeaningPolicy.notificationInstanceKey("pkg","","person-1","g",1,"","A"),StatefulMeaningPolicy.notificationInstanceKey("pkg","","person-1","other",2,"x","B"));}
    @Test public void gate32_samePhoneWithinWindowCorrelates(){long t=20L*60L*1000L;String a=StatefulMeaningPolicy.correlationKey("call_event","01006091092","Missed call","phone",t),b=StatefulMeaningPolicy.correlationKey("call_event","01006091092","Missed call again","truecaller",t+60_000);assertEquals(a,b);}
    @Test public void gate33_samePhoneOutsideWindowDoesNotForceMerge(){long t=20L*60L*1000L;String a=StatefulMeaningPolicy.correlationKey("call_event","01006091092","Missed call","phone",t),b=StatefulMeaningPolicy.correlationKey("call_event","01006091092","Missed call","phone",t+11L*60L*1000L);assertNotEquals(a,b);}
    @Test public void gate34_projectionWritesAreIdempotent(){StatefulMeaningPolicy.ProjectionDecision d=StatefulMeaningPolicy.projection("action_request","request",.95,"OPENED",1,"A","Send me the email");StatefulMeaningStore.recordProjectionDecision(db,77,5,d);StatefulMeaningStore.recordProjectionDecision(db,77,5,d);assertEquals(4,count("SELECT COUNT(*) FROM ue_projection_decisions WHERE semantic_event_id=77"));}
    @Test public void gate35_rebuilderIsIdempotent(){long raw=UniversalEventStore.appendRaw(db,"notification","pkg","obs","posted","message","conversation_notification","Ahmed","Hello",new JSONObject(),1000);long stream=UniversalEventStore.upsertStream(db,"notification","external","active","h","Ahmed","Hello","message","conversation_notification",1000,true,new JSONObject());UniversalEventStore.insertSemantic(db,raw,stream,1,"conversation_message","message","Ahmed","Hello",.91,"complete",true,"local","test",1000);assertTrue(rebuild(db)>0);long instances=count("SELECT COUNT(*) FROM ue_source_instances"),decisions=count("SELECT COUNT(*) FROM ue_projection_decisions");assertEquals(0,rebuild(db));assertEquals(instances,count("SELECT COUNT(*) FROM ue_source_instances"));assertEquals(decisions,count("SELECT COUNT(*) FROM ue_projection_decisions"));}

    private JSONObject meta(String key){JSONObject j=new JSONObject();try{j.put("notification_key",key);}catch(Exception ignored){}return j;}
    private long count(String sql){Cursor c=db.rawQuery(sql,null);long n=c.moveToFirst()?c.getLong(0):0;c.close();return n;}
    private int rebuild(SQLiteDatabase ignored){VaultDbLike v=new VaultDbLike(db);return v.run();}

    /** Tiny adapter reproduces the rebuilder's idempotent two-stage contract without touching a device database. */
    private static final class VaultDbLike {
        final SQLiteDatabase db;VaultDbLike(SQLiteDatabase d){db=d;}
        int run(){int done=0;Cursor c=db.rawQuery("SELECT r.id,r.source_key,r.technical_type,r.event_type,r.title,r.body,r.occurred_at,r.payload_json FROM ue_raw_observations r WHERE r.source_type='notification' AND NOT EXISTS(SELECT 1 FROM ue_source_transitions t WHERE t.raw_observation_id=r.id) ORDER BY r.id",null);while(c.moveToNext()){JSONObject m;try{m=new JSONObject(c.getString(7));}catch(Exception e){m=new JSONObject();}StatefulMeaningStore.observeNotification(db,c.getLong(0),c.getString(1),c.getString(2),c.getString(3),c.getString(4),c.getString(5),c.getLong(6),m);done++;}c.close();c=db.rawQuery("SELECT e.id,e.raw_observation_id,e.semantic_type,e.intent,e.subject,e.summary,e.confidence,e.occurred_at,r.source_key,COALESCE(t.source_instance_id,0) FROM ue_semantic_events e JOIN ue_raw_observations r ON r.id=e.raw_observation_id LEFT JOIN ue_source_transitions t ON t.raw_observation_id=e.raw_observation_id WHERE e.semantic_state='complete' AND e.superseded_by=0 AND NOT EXISTS(SELECT 1 FROM ue_projection_decisions p WHERE p.semantic_event_id=e.id AND p.policy_version=?) ORDER BY e.id",new String[]{StatefulMeaningPolicy.VERSION});while(c.moveToNext()){long event=c.getLong(0);String type=c.getString(2),intent=c.getString(3),subject=c.getString(4),summary=c.getString(5);double conf=c.getDouble(6);long sit=StatefulMeaningStore.correlate(db,event,c.getLong(9),c.getString(8),type,subject,summary,conf,c.getLong(7));String transition="OPENED";Cursor t=db.rawQuery("SELECT last_transition_kind,member_count FROM ue_situation_state_v2 WHERE situation_id=?",new String[]{String.valueOf(sit)});int repeats=1;if(t.moveToFirst()){transition=t.getString(0);repeats=t.getInt(1);}t.close();StatefulMeaningStore.recordProjectionDecision(db,event,sit,StatefulMeaningPolicy.projection(type,intent,conf,transition,repeats,subject,summary));done++;}c.close();return done;}
    }
}
